In [274]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from tabulate import tabulate
from tqdm import tqdm
from pycoingecko import CoinGeckoAPI
from datetime import datetime

#####  A fazer: 

1. Trend stability
2. Support / resistance levels 
3. Implement vs. BTC complete functionalities (relative performance and strategy) -> then, can start thinking on allocation protocols

4. Keep state of trends at asset and portfolio level historically

In [275]:


class TrendAnalyzer:
    """
    A class to analyze price trends for multiple cryptocurrency assets, storing all data and classifications.

    Attributes:
        asset_ids (list): List of asset IDs to analyze
        data_path (str): Path to the directory containing candle data
        btc_data_path (str): Path to the Bitcoin data file
        use_btc_adjusted (bool): Whether to prioritize BTC-adjusted prices in output (default: True)
        verbose (bool): Whether to print detailed processing information (default: True)
        ticker_mapping (dict): Mapping from ticker symbols to asset IDs
        asset_data (dict): Dictionary storing raw data, indicators, classifications, and signals for each asset
        current_date (datetime): Current date for data currency validation
    """

    def __init__(self, asset_ids, data_path, btc_data_path, use_btc_adjusted=True, verbose=True):
        """
        Initialize the TrendAnalyzer with a list of asset IDs.

        Args:
            asset_ids (list): List of asset IDs to analyze
            data_path (str): Path to the directory containing candle data
            btc_data_path (str): Path to the Bitcoin data file
            use_btc_adjusted (bool): Whether to prioritize BTC-adjusted prices in output (default: True)
            verbose (bool): Whether to print detailed processing information (default: True)
        """
        self.asset_ids = asset_ids
        self.data_path = data_path
        self.btc_data_path = btc_data_path
        self.use_btc_adjusted = use_btc_adjusted
        self.verbose = verbose
        self.ma_periods = {
            'Short Term': [3, 5, 7, 14],
            'Medium Term': [21, 30, 45, 63],
            'Long Term': [84, 100, 120, 150, 200, 252, 365]
        }
        self.ticker_mapping = self._get_ticker_mapping()
        self.asset_data = {}  # Initialize state dictionary
        self.current_date = datetime(2025, 3, 11)  # Set current date as specified

    def _get_ticker_mapping(self):
        """
        Retrieve ticker mapping using CoinGecko API.

        Returns:
            dict: Mapping from ticker symbols (upper-case) to asset IDs
        """
        cg = CoinGeckoAPI()
        coins_list = cg.get_coins_list()
        coins_df = pd.DataFrame(coins_list)
        
        known_mappings = {
            'VIRTUAL': 'virtual-protocol',
            'HYPE': 'hyperliquid',
            'YNE': 'yesnoerror'
        }
        
        mapping = {}
        for ticker, coin_id in known_mappings.items():
            if coin_id in self.asset_ids:
                mapping[ticker] = coin_id
        
        filtered_coins_df = coins_df[coins_df['id'].isin(self.asset_ids)]
        for _, row in filtered_coins_df.iterrows():
            ticker = row['symbol'].upper()
            if ticker not in mapping:
                mapping[ticker] = row['id']
        
        return mapping

    def _load_data(self, asset_id):
        """
        Load and merge asset data with Bitcoin data if applicable.

        Args:
            asset_id (str): Asset ID to load data for

        Returns:
            pd.DataFrame: Loaded and processed raw data, or empty DataFrame if file not found
        """
        data_path = f"{self.data_path}{asset_id}_candles.csv"
        try:
            data = pd.read_csv(data_path)
        except FileNotFoundError:
            if self.verbose:
                print(f"Warning: File not found for {asset_id}: {data_path}")
            return pd.DataFrame()
        
        data['date'] = pd.to_datetime(data['date'])
        data.dropna(inplace=True)
        if self.verbose:
            print(f"Initial columns after loading asset data for {asset_id}: {list(data.columns)}")

        if asset_id != 'bitcoin':
            btc_data = pd.read_csv(self.btc_data_path)
            btc_data['date'] = pd.to_datetime(btc_data['date'])
            btc_data = btc_data[['date', 'close']].rename(columns={'close': 'btc_close'})
            if self.verbose:
                print(f"Bitcoin data columns: {list(btc_data.columns)}")
            data = data.merge(btc_data, on='date', how='left')
            if self.verbose:
                print(f"Columns after merge for {asset_id}: {list(data.columns)}")
            if 'close' in data.columns and 'btc_close' in data.columns:
                data[f'{asset_id}_btc'] = data['close'] / data['btc_close']
            else:
                if self.verbose:
                    print(f"Missing columns after merge for {asset_id}. Available columns: {list(data.columns)}")
            data = data.drop(columns=['btc_close'], errors='ignore')
            if self.verbose:
                print(f"Columns after dropping 'btc_close' for {asset_id}: {list(data.columns)}")

        # Check if data is current
        if not data.empty:
            latest_date = data['date'].max()
            if self.verbose and (self.current_date - latest_date).days > 7:
                print(f"Warning: Data for {asset_id} is outdated (latest date: {latest_date.date()}, current date: {self.current_date.date()})")
        
        return data

    def _calculate_indicators(self, data, price_column, asset_id, suffix=''):
        """
        Calculate Simple Moving Averages (SMAs) and Rate of Change (RoC) indicators for a given price column.

        Args:
            data (pd.DataFrame): DataFrame to calculate indicators for
            price_column (str): Name of the price column to use
            asset_id (str): Asset ID being processed
            suffix (str): Suffix to append to indicator column names (e.g., 'USD', 'BTC')
        """
        if price_column not in data.columns and not data.empty:
            raise KeyError(f"Column '{price_column}' not found for {asset_id}. Available columns: {list(data.columns)}")
        if not data.empty:
            data[price_column] = pd.to_numeric(data[price_column], errors='coerce')
            data.dropna(subset=[price_column], inplace=True)
            if self.verbose:
                print(f"Columns after numeric conversion and dropna for {asset_id} ({price_column}): {list(data.columns)}")
            
            for term, periods in self.ma_periods.items():
                for period in periods:
                    data[f'SMA_{suffix}_{period}'] = data[price_column].rolling(
                        window=period, min_periods=period
                    ).mean()
            
            for term, periods in self.ma_periods.items():
                for period in periods:
                    data[f'RoC_{suffix}_{period}'] = (
                        (data[price_column] - data[price_column].shift(period))
                        / data[price_column].shift(period) * 100
                    )
            if self.verbose:
                print(f"Columns after calculating indicators for {asset_id} ({suffix}): {list(data.columns)}")

    def classify_trend(self, mas, rocs, data, suffix):
        """
        Classify the trend based on moving averages and rate of change for a specific price column.

        Args:
            mas (pd.Series): Series of moving averages
            rocs (pd.Series): Series of rates of change
            data (pd.DataFrame): DataFrame containing the asset's price data
            suffix (str): Suffix indicating the price basis (e.g., 'USD', 'BTC')

        Returns:
            str: Trend classification ('Strong Bull', 'Weak Bull', 'Strong Bear', 'Weak Bear', 'Neutral')
        """
        n_mas = len(mas.dropna())
        n_rocs = len(rocs.dropna())
        if n_mas == 0 or n_rocs == 0:
            return "Neutral"
        
        pos_mas = 0
        for col in mas.index:
            period = int(col.replace(f'SMA_{suffix}_', ''))
            current_ma = data[f'SMA_{suffix}_{period}'].iloc[-1]
            prev_ma = data[f'SMA_{suffix}_{period}'].iloc[-2] if len(data) > 1 else np.nan
            if not np.isnan(current_ma) and not np.isnan(prev_ma) and current_ma > prev_ma:
                pos_mas += 1
        
        pos_mas = pos_mas / n_mas * 100 if n_mas > 0 else 0
        pos_rocs = sum(1 for roc in rocs if roc > 0) / n_rocs * 100 if n_rocs > 0 else 0
        
        avg_pos = (pos_mas + pos_rocs) / 2
        
        if avg_pos >= 75:
            return "Strong Bull"
        elif avg_pos >= 50:
            return "Weak Bull"
        elif avg_pos <= 25:
            return "Strong Bear"
        elif avg_pos <= 40:
            return "Weak Bear"
        return "Neutral"

    def _create_classified_data(self, data, asset_id):
        """
        Create a DataFrame with historical trend classifications for both USD and BTC price columns.

        Args:
            data (pd.DataFrame): DataFrame with price and indicator data
            asset_id (str): Asset ID being processed

        Returns:
            pd.DataFrame: DataFrame with trend classifications for both USD and BTC
        """
        if data.empty:
            return pd.DataFrame()
        classified_data = data.copy()

        # USD classifications
        usd_price_column = 'close'
        self._calculate_indicators(classified_data, usd_price_column, asset_id, suffix='USD')
        
        short_term_mas_usd = [f'SMA_USD_{period}' for period in self.ma_periods['Short Term']]
        medium_term_mas_usd = [f'SMA_USD_{period}' for period in self.ma_periods['Medium Term']]
        long_term_mas_usd = [f'SMA_USD_{period}' for period in self.ma_periods['Long Term']]
        
        short_term_rocs_usd = [f'RoC_USD_{period}' for period in self.ma_periods['Short Term']]
        medium_term_rocs_usd = [f'RoC_USD_{period}' for period in self.ma_periods['Medium Term']]
        long_term_rocs_usd = [f'RoC_USD_{period}' for period in self.ma_periods['Long Term']]

        classified_data['Short Term (USD)'] = classified_data.apply(
            lambda row: self.classify_trend(row[short_term_mas_usd], row[short_term_rocs_usd], classified_data, 'USD'), axis=1
        )
        classified_data['Medium Term (USD)'] = classified_data.apply(
            lambda row: self.classify_trend(row[medium_term_mas_usd], row[medium_term_rocs_usd], classified_data, 'USD'), axis=1
        )
        classified_data['Long Term (USD)'] = classified_data.apply(
            lambda row: self.classify_trend(row[long_term_mas_usd], row[long_term_rocs_usd], classified_data, 'USD'), axis=1
        )
        classified_data['Overall (USD)'] = classified_data.apply(
            lambda row: self._compute_overall_classification(
                [row['Short Term (USD)'], row['Medium Term (USD)'], row['Long Term (USD)']]
            ), axis=1
        )

        # BTC classifications (except for Bitcoin)
        if asset_id != 'bitcoin' and f'{asset_id}_btc' in classified_data.columns:
            btc_price_column = f'{asset_id}_btc'
            self._calculate_indicators(classified_data, btc_price_column, asset_id, suffix='BTC')
            
            short_term_mas_btc = [f'SMA_BTC_{period}' for period in self.ma_periods['Short Term']]
            medium_term_mas_btc = [f'SMA_BTC_{period}' for period in self.ma_periods['Medium Term']]
            long_term_mas_btc = [f'SMA_BTC_{period}' for period in self.ma_periods['Long Term']]
            
            short_term_rocs_btc = [f'RoC_BTC_{period}' for period in self.ma_periods['Short Term']]
            medium_term_rocs_btc = [f'RoC_BTC_{period}' for period in self.ma_periods['Medium Term']]
            long_term_rocs_btc = [f'RoC_BTC_{period}' for period in self.ma_periods['Long Term']]

            classified_data['Short Term (BTC)'] = classified_data.apply(
                lambda row: self.classify_trend(row[short_term_mas_btc], row[short_term_rocs_btc], classified_data, 'BTC'), axis=1
            )
            classified_data['Medium Term (BTC)'] = classified_data.apply(
                lambda row: self.classify_trend(row[medium_term_mas_btc], row[medium_term_rocs_btc], classified_data, 'BTC'), axis=1
            )
            classified_data['Long Term (BTC)'] = classified_data.apply(
                lambda row: self.classify_trend(row[long_term_mas_btc], row[long_term_rocs_btc], classified_data, 'BTC'), axis=1
            )
            classified_data['Overall (BTC)'] = classified_data.apply(
                lambda row: self._compute_overall_classification(
                    [row['Short Term (BTC)'], row['Medium Term (BTC)'], row['Long Term (BTC)']]
                ), axis=1
            )
        else:
            # For Bitcoin, set BTC trends to NaN
            classified_data['Short Term (BTC)'] = pd.NA
            classified_data['Medium Term (BTC)'] = pd.NA
            classified_data['Long Term (BTC)'] = pd.NA
            classified_data['Overall (BTC)'] = pd.NA
        
        return classified_data

    def _compute_overall_classification(self, trends):
        """
        Compute the overall trend classification based on individual timeframes.

        Args:
            trends (list): List of trend classifications for Short Term, Medium Term, and Long Term

        Returns:
            str: Overall trend classification
        """
        overall_pos = sum(1 for c in trends if c in ["Strong Bull", "Weak Bull"]) / len(trends) * 100
        if overall_pos >= 75:
            return "Strong Bull"
        elif overall_pos >= 50:
            return "Weak Bull"
        elif overall_pos <= 25:
            return "Strong Bear"
        elif overall_pos <= 40:
            return "Weak Bear"
        return "Neutral"

    def analyze(self, asset_id, data, suffix):
        """
        Analyze trends for a single asset using a specific price suffix.

        Args:
            asset_id (str): Asset ID to analyze
            data (pd.DataFrame): DataFrame containing price data
            suffix (str): Suffix indicating the price basis (e.g., 'USD', 'BTC')

        Returns:
            dict: Dictionary of trend classifications for Short Term, Medium Term, Long Term, and Overall
        """
        if data.empty:
            return {'Short Term': 'N/A', 'Medium Term': 'N/A', 'Long Term': 'N/A', 'Overall': 'N/A'}
        classifications = {}
        for term in ['Short Term', 'Medium Term', 'Long Term']:
            classifications[term] = data[f'{term} ({suffix})'].iloc[-1]
        classifications['Overall'] = data[f'Overall ({suffix})'].iloc[-1]
        if self.verbose:
            for term, classification in classifications.items():
                print(f"{term} classification for {asset_id} ({suffix}): {classification}")
        return classifications

    def create_chart(self, asset_id, data, price_column):
        """
        Create a Plotly chart of price and SMAs for a single asset.

        Args:
            asset_id (str): Asset ID to create chart for
            data (pd.DataFrame): DataFrame containing price and SMA data
            price_column (str): Name of the price column to plot

        Returns:
            go.Figure: Plotly figure object, or None if no data
        """
        if data.empty:
            if self.verbose:
                print(f"No data available to create chart for {asset_id} ({price_column})")
            return None
        selected_smas = [14, 30, 63, 200]
        suffix = 'USD' if price_column == 'close' else 'BTC'
        fig = go.Figure()

        fig.add_trace(go.Scatter(
            x=data['date'],
            y=data[price_column],
            mode='lines',
            name='Price',
            line=dict(color='green'),
            yaxis='y1'
        ))

        colors = ['red', 'orange', 'purple', 'gray']
        for i, period in enumerate(selected_smas):
            fig.add_trace(go.Scatter(
                x=data['date'],
                y=data[f'SMA_{suffix}_{period}'],
                mode='lines',
                name=f'SMA{period}',
                line=dict(color=colors[i % len(colors)], width=2),
                yaxis='y1'
            ))

        fig.update_layout(
            title=f"{asset_id.upper()} Price and SMAs ({suffix})",
            xaxis_title="Date",
            yaxis_title=f"Price ({suffix})",
            yaxis=dict(type='log', autorange=True, gridcolor='lightgray'),
            xaxis=dict(gridcolor='lightgray'),
            template="plotly_white",
            showlegend=True,
            height=500,
            margin=dict(l=50, r=50, t=100, b=50)
        )
        return fig

    def analyze_multiple_assets(self):
        """
        Analyze trends for all assets, store data in state, and output a consolidated table using ticker symbols.

        Returns:
            pd.DataFrame: DataFrame containing the most recent trend analysis for all assets
        """
        self.asset_data = {}  # Initialize state dictionary
        results = []
        reverse_mapping = {v: k for k, v in self.ticker_mapping.items()}
        
        for asset_id in tqdm(self.asset_ids, desc="Analyzing assets", disable=not self.verbose):
            # Load raw data
            raw_data = self._load_data(asset_id)
            
            # Process classifications for both USD and BTC in a single DataFrame
            classified_data = self._create_classified_data(raw_data, asset_id)

            # Store all data in state
            self.asset_data[asset_id] = {
                'raw_data': raw_data.copy(),
                'classified_data': classified_data.copy(),
                'price_column_usd': 'close',
                'price_column_btc': f'{asset_id}_btc' if asset_id != 'bitcoin' and f'{asset_id}_btc' in classified_data.columns else None
            }

            # Get the most recent classifications
            latest_classifications = classified_data.iloc[-1].to_dict() if not classified_data.empty else {
                'Short Term (USD)': 'N/A',
                'Medium Term (USD)': 'N/A',
                'Long Term (USD)': 'N/A',
                'Overall (USD)': 'N/A',
                'Short Term (BTC)': 'N/A',
                'Medium Term (BTC)': 'N/A',
                'Long Term (BTC)': 'N/A',
                'Overall (BTC)': 'N/A'
            }

            ticker = reverse_mapping.get(asset_id, asset_id.upper())
            results.append({
                'Ticker': ticker,
                'Short Term Trend (USD)': latest_classifications.get('Short Term (USD)', 'N/A'),
                'Medium Term Trend (USD)': latest_classifications.get('Medium Term (USD)', 'N/A'),
                'Long Term Trend (USD)': latest_classifications.get('Long Term (USD)', 'N/A'),
                'Overall Trend (USD)': latest_classifications.get('Overall (USD)', 'N/A'),
                'Short Term Trend (BTC)': latest_classifications.get('Short Term (BTC)', 'N/A'),
                'Medium Term Trend (BTC)': latest_classifications.get('Medium Term (BTC)', 'N/A'),
                'Long Term Trend (BTC)': latest_classifications.get('Long Term (BTC)', 'N/A'),
                'Overall Trend (BTC)': latest_classifications.get('Overall (BTC)', 'N/A'),
                'Latest Date': classified_data['date'].iloc[-1].date() if not classified_data.empty else None
            })

        summary_df = pd.DataFrame(results)
        
        if self.verbose:
            print("\nMost Recent Trend Analysis Summary for Multiple Assets (as of March 11, 2025):")
            print(tabulate(summary_df, headers='keys', tablefmt='pretty', showindex=False))
        
        return summary_df

# Usage
if __name__ == "__main__":
    from scripts.assetsRoster import carteira_AC, carteira_HB, carteira_LC, carteira_EXC, others

    # Combine all unique assets from the portfolio
    all_assets = list(set(carteira_AC + carteira_HB + carteira_LC + carteira_EXC + others))
    
    analyzer = TrendAnalyzer(
        asset_ids=all_assets,
        data_path='/Users/valter.rebelo/MissionControl/data/micro/candleData/',
        btc_data_path='/Users/valter.rebelo/MissionControl/data/micro/assetData/bitcoin.csv',
        use_btc_adjusted=False,
        verbose=True
    )
    summary_df = analyzer.analyze_multiple_assets()

    # Example access to stored data with unified DataFrame
    for asset_id in all_assets:
        if asset_id in analyzer.asset_data:
            print(f"\nUnified Classified Data for {asset_id}:")
            print(analyzer.asset_data[asset_id]['classified_data'].tail())

Analyzing assets:   0%|          | 0/128 [00:00<?, ?it/s]

Initial columns after loading asset data for bitcoin: ['date', 'open', 'high', 'low', 'close']
Columns after numeric conversion and dropna for bitcoin (close): ['date', 'open', 'high', 'low', 'close']
Columns after calculating indicators for bitcoin (USD): ['date', 'open', 'high', 'low', 'close', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']

Analyzing assets:   1%|          | 1/128 [00:03<06:38,  3.14s/it]

Initial columns after loading asset data for illuvium: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for illuvium: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for illuvium: ['date', 'open', 'high', 'low', 'close', 'illuvium_btc']
Columns after numeric conversion and dropna for illuvium (close): ['date', 'open', 'high', 'low', 'close', 'illuvium_btc']
Columns after calculating indicators for illuvium (USD): ['date', 'open', 'high', 'low', 'close', 'illuvium_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for illuvium (illuvium_btc): ['date', 'open', 'high', 'low', 'close', 'illuvium_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for illuvium (BTC): ['date', 'open', 'high', 'low', 'close', 'illuvium_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:   2%|▏         | 2/128 [00:05<05:13,  2.49s/it]

Initial columns after loading asset data for immutable-x: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for immutable-x: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for immutable-x: ['date', 'open', 'high', 'low', 'close', 'immutable-x_btc']
Columns after numeric conversion and dropna for immutable-x (close): ['date', 'open', 'high', 'low', 'close', 'immutable-x_btc']
Columns after calculating indicators for immutable-x (USD): ['date', 'open', 'high', 'low', 'close', 'immutable-x_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for immutable-x (immutable-x_btc): ['date', 'open', 'high', 'low', 'close', 'immutable-x_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for immutable-x (BTC): ['date', 'open', 'high', 'low', 'close', 'immutable-x_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:   2%|▏         | 3/128 [00:06<04:32,  2.18s/it]

Initial columns after loading asset data for acala: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for acala: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for acala: ['date', 'open', 'high', 'low', 'close', 'acala_btc']
Columns after numeric conversion and dropna for acala (close): ['date', 'open', 'high', 'low', 'close', 'acala_btc']
Columns after calculating indicators for acala (USD): ['date', 'open', 'high', 'low', 'close', 'acala_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for acala (acala_btc): ['date', 'open', 'high', 'low', 'close', 'acala_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for acala (BTC): ['date', 'open', 'high', 'low', 'close', 'acala_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:   3%|▎         | 4/128 [00:08<04:15,  2.06s/it]

Initial columns after loading asset data for virtual-protocol: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for virtual-protocol: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for virtual-protocol: ['date', 'open', 'high', 'low', 'close', 'virtual-protocol_btc']
Columns after numeric conversion and dropna for virtual-protocol (close): ['date', 'open', 'high', 'low', 'close', 'virtual-protocol_btc']
Columns after calculating indicators for virtual-protocol (USD): ['date', 'open', 'high', 'low', 'close', 'virtual-protocol_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for virtual-protocol (virtual-protocol_btc): ['date', 'open', 'high', 'low', 'close', 'virtual-protocol_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for virtual-protocol (BTC): ['date', 'open', 'high', 'low', 'close', 'virtual-protocol_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:   5%|▍         | 6/128 [00:09<02:11,  1.08s/it]

Initial columns after loading asset data for aixbt: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for aixbt: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for aixbt: ['date', 'open', 'high', 'low', 'close', 'aixbt_btc']
Columns after numeric conversion and dropna for aixbt (close): ['date', 'open', 'high', 'low', 'close', 'aixbt_btc']
Columns after calculating indicators for aixbt (USD): ['date', 'open', 'high', 'low', 'close', 'aixbt_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for aixbt (aixbt_btc): ['date', 'open', 'high', 'low', 'close', 'aixbt_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for aixbt (BTC): ['date', 'open', 'high', 'low', 'close', 'aixbt_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']
Initial columns after loading asset data for bitcoin-cash: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for bitcoin-cash: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for bitcoin-cash: ['date', 'open', 'high', 'low', 'close', 'bitcoin-cash_btc']
Columns after numeric conversion and dropna for bitcoin-cash (close): ['date', 'open', 'high', 'low', 'close', 'bitcoin-cash_btc']
Columns after calculating indicators for bitcoin-cash (USD): ['date', 'open', 'high', 'low', 'close', 'bitcoin-cash_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for bitcoin-cash (bitcoin-cash_btc): ['date', 'open', 'high', 'low', 'close', 'bitcoin-cash_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for bitcoin-cash (BTC): ['date', 'open', 'high', 'low', 'close', 'bitcoin-cash_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:   5%|▌         | 7/128 [00:13<04:12,  2.08s/it]

Initial columns after loading asset data for kryptonite: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for kryptonite: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for kryptonite: ['date', 'open', 'high', 'low', 'close', 'kryptonite_btc']
Columns after numeric conversion and dropna for kryptonite (close): ['date', 'open', 'high', 'low', 'close', 'kryptonite_btc']
Columns after calculating indicators for kryptonite (USD): ['date', 'open', 'high', 'low', 'close', 'kryptonite_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for kryptonite (kryptonite_btc): ['date', 'open', 'high', 'low', 'close', 'kryptonite_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for kryptonite (BTC): ['date', 'open', 'high', 'low', 'close', 'kryptonite_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:   6%|▋         | 8/128 [00:14<03:21,  1.68s/it]

Initial columns after loading asset data for maker: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for maker: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for maker: ['date', 'open', 'high', 'low', 'close', 'maker_btc']
Columns after numeric conversion and dropna for maker (close): ['date', 'open', 'high', 'low', 'close', 'maker_btc']
Columns after calculating indicators for maker (USD): ['date', 'open', 'high', 'low', 'close', 'maker_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for maker (maker_btc): ['date', 'open', 'high', 'low', 'close', 'maker_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for maker (BTC): ['date', 'open', 'high', 'low', 'close', 'maker_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:   7%|▋         | 9/128 [00:18<04:33,  2.30s/it]

Initial columns after loading asset data for curve-dao-token: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for curve-dao-token: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for curve-dao-token: ['date', 'open', 'high', 'low', 'close', 'curve-dao-token_btc']
Columns after numeric conversion and dropna for curve-dao-token (close): ['date', 'open', 'high', 'low', 'close', 'curve-dao-token_btc']
Columns after calculating indicators for curve-dao-token (USD): ['date', 'open', 'high', 'low', 'close', 'curve-dao-token_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for curve-dao-token (curve-dao-token_btc): ['date', 'open', 'high', 'low', 'close', 'curve-dao-token_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for curve-dao-token (BTC): ['date', 'open', 'high', 'low', 'close', 'curve-dao-token_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:   8%|▊         | 10/128 [00:20<04:32,  2.31s/it]

Initial columns after loading asset data for multibit: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for multibit: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for multibit: ['date', 'open', 'high', 'low', 'close', 'multibit_btc']
Columns after numeric conversion and dropna for multibit (close): ['date', 'open', 'high', 'low', 'close', 'multibit_btc']
Columns after calculating indicators for multibit (USD): ['date', 'open', 'high', 'low', 'close', 'multibit_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for multibit (multibit_btc): ['date', 'open', 'high', 'low', 'close', 'multibit_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for multibit (BTC): ['date', 'open', 'high', 'low', 'close', 'multibit_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:   9%|▊         | 11/128 [00:21<03:32,  1.81s/it]

Initial columns after loading asset data for echelon-prime: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for echelon-prime: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for echelon-prime: ['date', 'open', 'high', 'low', 'close', 'echelon-prime_btc']
Columns after numeric conversion and dropna for echelon-prime (close): ['date', 'open', 'high', 'low', 'close', 'echelon-prime_btc']
Columns after calculating indicators for echelon-prime (USD): ['date', 'open', 'high', 'low', 'close', 'echelon-prime_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for echelon-prime (echelon-prime_btc): ['date', 'open', 'high', 'low', 'close', 'echelon-prime_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for echelon-prime (BTC): ['date', 'open', 'high', 'low', 'close', 'echelon-prime_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:   9%|▉         | 12/128 [00:22<03:03,  1.58s/it]

Initial columns after loading asset data for arbitrum: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for arbitrum: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for arbitrum: ['date', 'open', 'high', 'low', 'close', 'arbitrum_btc']
Columns after numeric conversion and dropna for arbitrum (close): ['date', 'open', 'high', 'low', 'close', 'arbitrum_btc']
Columns after calculating indicators for arbitrum (USD): ['date', 'open', 'high', 'low', 'close', 'arbitrum_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for arbitrum (arbitrum_btc): ['date', 'open', 'high', 'low', 'close', 'arbitrum_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for arbitrum (BTC): ['date', 'open', 'high', 'low', 'close', 'arbitrum_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  10%|█         | 13/128 [00:23<02:42,  1.41s/it]

Initial columns after loading asset data for aurory: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for aurory: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for aurory: ['date', 'open', 'high', 'low', 'close', 'aurory_btc']
Columns after numeric conversion and dropna for aurory (close): ['date', 'open', 'high', 'low', 'close', 'aurory_btc']
Columns after calculating indicators for aurory (USD): ['date', 'open', 'high', 'low', 'close', 'aurory_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for aurory (aurory_btc): ['date', 'open', 'high', 'low', 'close', 'aurory_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for aurory (BTC): ['date', 'open', 'high', 'low', 'close', 'aurory_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  12%|█▏        | 15/128 [00:25<02:05,  1.11s/it]

Initial columns after loading asset data for fartcoin: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for fartcoin: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for fartcoin: ['date', 'open', 'high', 'low', 'close', 'fartcoin_btc']
Columns after numeric conversion and dropna for fartcoin (close): ['date', 'open', 'high', 'low', 'close', 'fartcoin_btc']
Columns after calculating indicators for fartcoin (USD): ['date', 'open', 'high', 'low', 'close', 'fartcoin_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for fartcoin (fartcoin_btc): ['date', 'open', 'high', 'low', 'close', 'fartcoin_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for fartcoin (BTC): ['date', 'open', 'high', 'low', 'close', 'fartcoin_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']
Initial columns after loading asset data for ronin: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for ronin: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for ronin: ['date', 'open', 'high', 'low', 'close', 'ronin_btc']
Columns after numeric conversion and dropna for ronin (close): ['date', 'open', 'high', 'low', 'close', 'ronin_btc']
Columns after calculating indicators for ronin (USD): ['date', 'open', 'high', 'low', 'close', 'ronin_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for ronin (ronin_btc): ['date', 'open', 'high', 'low', 'close', 'ronin_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for ronin (BTC): ['date', 'open', 'high', 'low', 'close', 'ronin_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  12%|█▎        | 16/128 [00:26<02:20,  1.26s/it]

Initial columns after loading asset data for alpha-finance: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for alpha-finance: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for alpha-finance: ['date', 'open', 'high', 'low', 'close', 'alpha-finance_btc']
Columns after numeric conversion and dropna for alpha-finance (close): ['date', 'open', 'high', 'low', 'close', 'alpha-finance_btc']
Columns after calculating indicators for alpha-finance (USD): ['date', 'open', 'high', 'low', 'close', 'alpha-finance_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for alpha-finance (alpha-finance_btc): ['date', 'open', 'high', 'low', 'close', 'alpha-finance_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for alpha-finance (BTC): ['date', 'open', 'high', 'low', 'close', 'alpha-finance_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  13%|█▎        | 17/128 [00:29<02:52,  1.55s/it]

Initial columns after loading asset data for frax-share: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for frax-share: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for frax-share: ['date', 'open', 'high', 'low', 'close', 'frax-share_btc']
Columns after numeric conversion and dropna for frax-share (close): ['date', 'open', 'high', 'low', 'close', 'frax-share_btc']
Columns after calculating indicators for frax-share (USD): ['date', 'open', 'high', 'low', 'close', 'frax-share_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for frax-share (frax-share_btc): ['date', 'open', 'high', 'low', 'close', 'frax-share_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for frax-share (BTC): ['date', 'open', 'high', 'low', 'close', 'frax-share_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  14%|█▍        | 18/128 [00:31<03:17,  1.79s/it]

Initial columns after loading asset data for polymath: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for polymath: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for polymath: ['date', 'open', 'high', 'low', 'close', 'polymath_btc']
Columns after numeric conversion and dropna for polymath (close): ['date', 'open', 'high', 'low', 'close', 'polymath_btc']
Columns after calculating indicators for polymath (USD): ['date', 'open', 'high', 'low', 'close', 'polymath_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for polymath (polymath_btc): ['date', 'open', 'high', 'low', 'close', 'polymath_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for polymath (BTC): ['date', 'open', 'high', 'low', 'close', 'polymath_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  15%|█▍        | 19/128 [00:35<04:14,  2.33s/it]

Initial columns after loading asset data for band-protocol: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for band-protocol: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for band-protocol: ['date', 'open', 'high', 'low', 'close', 'band-protocol_btc']
Columns after numeric conversion and dropna for band-protocol (close): ['date', 'open', 'high', 'low', 'close', 'band-protocol_btc']
Columns after calculating indicators for band-protocol (USD): ['date', 'open', 'high', 'low', 'close', 'band-protocol_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for band-protocol (band-protocol_btc): ['date', 'open', 'high', 'low', 'close', 'band-protocol_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for band-protocol (BTC): ['date', 'open', 'high', 'low', 'close', 'band-protocol_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  16%|█▌        | 20/128 [00:37<04:26,  2.47s/it]

Initial columns after loading asset data for pax-gold: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for pax-gold: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for pax-gold: ['date', 'open', 'high', 'low', 'close', 'pax-gold_btc']
Columns after numeric conversion and dropna for pax-gold (close): ['date', 'open', 'high', 'low', 'close', 'pax-gold_btc']
Columns after calculating indicators for pax-gold (USD): ['date', 'open', 'high', 'low', 'close', 'pax-gold_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for pax-gold (pax-gold_btc): ['date', 'open', 'high', 'low', 'close', 'pax-gold_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for pax-gold (BTC): ['date', 'open', 'high', 'low', 'close', 'pax-gold_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  16%|█▋        | 21/128 [00:41<04:47,  2.69s/it]

Initial columns after loading asset data for conic-finance: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for conic-finance: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for conic-finance: ['date', 'open', 'high', 'low', 'close', 'conic-finance_btc']
Columns after numeric conversion and dropna for conic-finance (close): ['date', 'open', 'high', 'low', 'close', 'conic-finance_btc']
Columns after calculating indicators for conic-finance (USD): ['date', 'open', 'high', 'low', 'close', 'conic-finance_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for conic-finance (conic-finance_btc): ['date', 'open', 'high', 'low', 'close', 'conic-finance_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for conic-finance (BTC): ['date', 'open', 'high', 'low', 'close', 'conic-finance_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  17%|█▋        | 22/128 [00:42<04:02,  2.29s/it]

Initial columns after loading asset data for render-token: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for render-token: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for render-token: ['date', 'open', 'high', 'low', 'close', 'render-token_btc']
Columns after numeric conversion and dropna for render-token (close): ['date', 'open', 'high', 'low', 'close', 'render-token_btc']
Columns after calculating indicators for render-token (USD): ['date', 'open', 'high', 'low', 'close', 'render-token_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for render-token (render-token_btc): ['date', 'open', 'high', 'low', 'close', 'render-token_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for render-token (BTC): ['date', 'open', 'high', 'low', 'close', 'render-token_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  18%|█▊        | 23/128 [00:44<04:04,  2.33s/it]

Initial columns after loading asset data for pendle: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for pendle: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for pendle: ['date', 'open', 'high', 'low', 'close', 'pendle_btc']
Columns after numeric conversion and dropna for pendle (close): ['date', 'open', 'high', 'low', 'close', 'pendle_btc']
Columns after calculating indicators for pendle (USD): ['date', 'open', 'high', 'low', 'close', 'pendle_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for pendle (pendle_btc): ['date', 'open', 'high', 'low', 'close', 'pendle_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for pendle (BTC): ['date', 'open', 'high', 'low', 'close', 'pendle_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  19%|█▉        | 24/128 [00:46<03:50,  2.22s/it]

Initial columns after loading asset data for jupiter-exchange-solana: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for jupiter-exchange-solana: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for jupiter-exchange-solana: ['date', 'open', 'high', 'low', 'close', 'jupiter-exchange-solana_btc']
Columns after numeric conversion and dropna for jupiter-exchange-solana (close): ['date', 'open', 'high', 'low', 'close', 'jupiter-exchange-solana_btc']
Columns after calculating indicators for jupiter-exchange-solana (USD): ['date', 'open', 'high', 'low', 'close', 'jupiter-exchange-solana_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for jupiter-exchange-solana (jupiter-exchange-solana_btc): ['date', 'open', 'high', 'low', 'close', 'jupiter-exchange-solana_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for jupiter-exchange-solana (BTC): ['date', 'open', 'high', 'low', 'close', 'jupiter-exchange-solana_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  20%|█▉        | 25/128 [00:47<02:57,  1.73s/it]

Initial columns after loading asset data for decentraland: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for decentraland: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for decentraland: ['date', 'open', 'high', 'low', 'close', 'decentraland_btc']
Columns after numeric conversion and dropna for decentraland (close): ['date', 'open', 'high', 'low', 'close', 'decentraland_btc']
Columns after calculating indicators for decentraland (USD): ['date', 'open', 'high', 'low', 'close', 'decentraland_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for decentraland (decentraland_btc): ['date', 'open', 'high', 'low', 'close', 'decentraland_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for decentraland (BTC): ['date', 'open', 'high', 'low', 'close', 'decentraland_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  20%|██        | 26/128 [00:51<03:58,  2.34s/it]

Initial columns after loading asset data for dydx: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for dydx: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for dydx: ['date', 'open', 'high', 'low', 'close', 'dydx_btc']
Columns after numeric conversion and dropna for dydx (close): ['date', 'open', 'high', 'low', 'close', 'dydx_btc']
Columns after calculating indicators for dydx (USD): ['date', 'open', 'high', 'low', 'close', 'dydx_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for dydx (dydx_btc): ['date', 'open', 'high', 'low', 'close', 'dydx_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for dydx (BTC): ['date', 'open', 'high', 'low', 'close', 'dydx_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  21%|██        | 27/128 [00:52<03:39,  2.18s/it]

Initial columns after loading asset data for tribe-2: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for tribe-2: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for tribe-2: ['date', 'open', 'high', 'low', 'close', 'tribe-2_btc']
Columns after numeric conversion and dropna for tribe-2 (close): ['date', 'open', 'high', 'low', 'close', 'tribe-2_btc']
Columns after calculating indicators for tribe-2 (USD): ['date', 'open', 'high', 'low', 'close', 'tribe-2_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for tribe-2 (tribe-2_btc): ['date', 'open', 'high', 'low', 'close', 'tribe-2_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for tribe-2 (BTC): ['date', 'open', 'high', 'low', 'close', 'tribe-2_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  22%|██▏       | 28/128 [00:54<03:33,  2.13s/it]

Initial columns after loading asset data for mintlayer: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for mintlayer: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for mintlayer: ['date', 'open', 'high', 'low', 'close', 'mintlayer_btc']
Columns after numeric conversion and dropna for mintlayer (close): ['date', 'open', 'high', 'low', 'close', 'mintlayer_btc']
Columns after calculating indicators for mintlayer (USD): ['date', 'open', 'high', 'low', 'close', 'mintlayer_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for mintlayer (mintlayer_btc): ['date', 'open', 'high', 'low', 'close', 'mintlayer_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for mintlayer (BTC): ['date', 'open', 'high', 'low', 'close', 'mintlayer_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  23%|██▎       | 29/128 [00:55<02:57,  1.80s/it]

Initial columns after loading asset data for swarm: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for swarm: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for swarm: ['date', 'open', 'high', 'low', 'close', 'swarm_btc']
Columns after numeric conversion and dropna for swarm (close): ['date', 'open', 'high', 'low', 'close', 'swarm_btc']
Columns after calculating indicators for swarm (USD): ['date', 'open', 'high', 'low', 'close', 'swarm_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for swarm (swarm_btc): ['date', 'open', 'high', 'low', 'close', 'swarm_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for swarm (BTC): ['date', 'open', 'high', 'low', 'close', 'swarm_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  23%|██▎       | 30/128 [01:00<04:19,  2.65s/it]

Initial columns after loading asset data for fantom: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for fantom: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for fantom: ['date', 'open', 'high', 'low', 'close', 'fantom_btc']
Columns after numeric conversion and dropna for fantom (close): ['date', 'open', 'high', 'low', 'close', 'fantom_btc']
Columns after calculating indicators for fantom (USD): ['date', 'open', 'high', 'low', 'close', 'fantom_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for fantom (fantom_btc): ['date', 'open', 'high', 'low', 'close', 'fantom_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for fantom (BTC): ['date', 'open', 'high', 'low', 'close', 'fantom_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  24%|██▍       | 31/128 [01:03<04:34,  2.83s/it]

Initial columns after loading asset data for pepe: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for pepe: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for pepe: ['date', 'open', 'high', 'low', 'close', 'pepe_btc']
Columns after numeric conversion and dropna for pepe (close): ['date', 'open', 'high', 'low', 'close', 'pepe_btc']
Columns after calculating indicators for pepe (USD): ['date', 'open', 'high', 'low', 'close', 'pepe_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for pepe (pepe_btc): ['date', 'open', 'high', 'low', 'close', 'pepe_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for pepe (BTC): ['date', 'open', 'high', 'low', 'close', 'pepe_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  25%|██▌       | 32/128 [01:04<03:38,  2.27s/it]

Initial columns after loading asset data for prisma-governance-token: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for prisma-governance-token: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for prisma-governance-token: ['date', 'open', 'high', 'low', 'close', 'prisma-governance-token_btc']
Columns after numeric conversion and dropna for prisma-governance-token (close): ['date', 'open', 'high', 'low', 'close', 'prisma-governance-token_btc']
Columns after calculating indicators for prisma-governance-token (USD): ['date', 'open', 'high', 'low', 'close', 'prisma-governance-token_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for prisma-governance-token (prisma-governance-token_btc): ['date', 'open', 'high', 'low', 'close', 'prisma-governance-token_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for prisma-governance-token (BTC): ['date', 'open', 'high', 'low', 'close', 'prisma-governance-token_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  26%|██▌       | 33/128 [01:05<02:51,  1.80s/it]

Initial columns after loading asset data for dodo: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for dodo: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for dodo: ['date', 'open', 'high', 'low', 'close', 'dodo_btc']
Columns after numeric conversion and dropna for dodo (close): ['date', 'open', 'high', 'low', 'close', 'dodo_btc']
Columns after calculating indicators for dodo (USD): ['date', 'open', 'high', 'low', 'close', 'dodo_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for dodo (dodo_btc): ['date', 'open', 'high', 'low', 'close', 'dodo_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for dodo (BTC): ['date', 'open', 'high', 'low', 'close', 'dodo_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  27%|██▋       | 34/128 [01:07<03:07,  1.99s/it]

Initial columns after loading asset data for celestia: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for celestia: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for celestia: ['date', 'open', 'high', 'low', 'close', 'celestia_btc']
Columns after numeric conversion and dropna for celestia (close): ['date', 'open', 'high', 'low', 'close', 'celestia_btc']
Columns after calculating indicators for celestia (USD): ['date', 'open', 'high', 'low', 'close', 'celestia_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for celestia (celestia_btc): ['date', 'open', 'high', 'low', 'close', 'celestia_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for celestia (BTC): ['date', 'open', 'high', 'low', 'close', 'celestia_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  27%|██▋       | 35/128 [01:08<02:34,  1.66s/it]

Initial columns after loading asset data for rari-governance-token: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for rari-governance-token: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for rari-governance-token: ['date', 'open', 'high', 'low', 'close', 'rari-governance-token_btc']
Columns after numeric conversion and dropna for rari-governance-token (close): ['date', 'open', 'high', 'low', 'close', 'rari-governance-token_btc']
Columns after calculating indicators for rari-governance-token (USD): ['date', 'open', 'high', 'low', 'close', 'rari-governance-token_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for rari-governance-token (rari-governance-token_btc): ['date', 'open', 'high', 'low', 'close', 'rari-governance-token_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for rari-governance-token (BTC): ['date', 'open', 'high', 'low', 'close', 'rari-governance-token_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  28%|██▊       | 36/128 [01:11<02:50,  1.86s/it]

Initial columns after loading asset data for vela-token: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for vela-token: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for vela-token: ['date', 'open', 'high', 'low', 'close', 'vela-token_btc']
Columns after numeric conversion and dropna for vela-token (close): ['date', 'open', 'high', 'low', 'close', 'vela-token_btc']
Columns after calculating indicators for vela-token (USD): ['date', 'open', 'high', 'low', 'close', 'vela-token_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for vela-token (vela-token_btc): ['date', 'open', 'high', 'low', 'close', 'vela-token_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for vela-token (BTC): ['date', 'open', 'high', 'low', 'close', 'vela-token_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  29%|██▉       | 37/128 [01:12<02:28,  1.63s/it]

Initial columns after loading asset data for perpetual-protocol: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for perpetual-protocol: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for perpetual-protocol: ['date', 'open', 'high', 'low', 'close', 'perpetual-protocol_btc']
Columns after numeric conversion and dropna for perpetual-protocol (close): ['date', 'open', 'high', 'low', 'close', 'perpetual-protocol_btc']
Columns after calculating indicators for perpetual-protocol (USD): ['date', 'open', 'high', 'low', 'close', 'perpetual-protocol_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for perpetual-protocol (perpetual-protocol_btc): ['date', 'open', 'high', 'low', 'close', 'perpetual-protocol_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for perpetual-protocol (BTC): ['date', 'open', 'high', 'low', 'close', 'perpetual-protocol_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  30%|██▉       | 38/128 [01:14<02:50,  1.90s/it]

Initial columns after loading asset data for havven: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for havven: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for havven: ['date', 'open', 'high', 'low', 'close', 'havven_btc']
Columns after numeric conversion and dropna for havven (close): ['date', 'open', 'high', 'low', 'close', 'havven_btc']
Columns after calculating indicators for havven (USD): ['date', 'open', 'high', 'low', 'close', 'havven_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for havven (havven_btc): ['date', 'open', 'high', 'low', 'close', 'havven_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for havven (BTC): ['date', 'open', 'high', 'low', 'close', 'havven_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  31%|███▏      | 40/128 [01:18<02:31,  1.72s/it]

Initial columns after loading asset data for sonic-3: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for sonic-3: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for sonic-3: ['date', 'open', 'high', 'low', 'close', 'sonic-3_btc']
Columns after numeric conversion and dropna for sonic-3 (close): ['date', 'open', 'high', 'low', 'close', 'sonic-3_btc']
Columns after calculating indicators for sonic-3 (USD): ['date', 'open', 'high', 'low', 'close', 'sonic-3_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for sonic-3 (sonic-3_btc): ['date', 'open', 'high', 'low', 'close', 'sonic-3_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for sonic-3 (BTC): ['date', 'open', 'high', 'low', 'close', 'sonic-3_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']
Initial columns after loading asset data for rainbow-token-2: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for rainbow-token-2: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for rainbow-token-2: ['date', 'open', 'high', 'low', 'close', 'rainbow-token-2_btc']
Columns after numeric conversion and dropna for rainbow-token-2 (close): ['date', 'open', 'high', 'low', 'close', 'rainbow-token-2_btc']
Columns after calculating indicators for rainbow-token-2 (USD): ['date', 'open', 'high', 'low', 'close', 'rainbow-token-2_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for rainbow-token-2 (rainbow-token-2_btc): ['date', 'open', 'high', 'low', 'close', 'rainbow-token-2_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for rainbow-token-2 (BTC): ['date', 'open', 'high', 'low', 'close', 'rainbow-token-2_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  32%|███▏      | 41/128 [01:20<02:25,  1.67s/it]

Initial columns after loading asset data for ethereum: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for ethereum: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for ethereum: ['date', 'open', 'high', 'low', 'close', 'ethereum_btc']
Columns after numeric conversion and dropna for ethereum (close): ['date', 'open', 'high', 'low', 'close', 'ethereum_btc']
Columns after calculating indicators for ethereum (USD): ['date', 'open', 'high', 'low', 'close', 'ethereum_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for ethereum (ethereum_btc): ['date', 'open', 'high', 'low', 'close', 'ethereum_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for ethereum (BTC): ['date', 'open', 'high', 'low', 'close', 'ethereum_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  33%|███▎      | 42/128 [01:24<03:45,  2.62s/it]

Initial columns after loading asset data for botto: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for botto: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for botto: ['date', 'open', 'high', 'low', 'close', 'botto_btc']
Columns after numeric conversion and dropna for botto (close): ['date', 'open', 'high', 'low', 'close', 'botto_btc']
Columns after calculating indicators for botto (USD): ['date', 'open', 'high', 'low', 'close', 'botto_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for botto (botto_btc): ['date', 'open', 'high', 'low', 'close', 'botto_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for botto (BTC): ['date', 'open', 'high', 'low', 'close', 'botto_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  34%|███▎      | 43/128 [01:26<03:20,  2.36s/it]

Initial columns after loading asset data for cosmos: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for cosmos: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for cosmos: ['date', 'open', 'high', 'low', 'close', 'cosmos_btc']
Columns after numeric conversion and dropna for cosmos (close): ['date', 'open', 'high', 'low', 'close', 'cosmos_btc']
Columns after calculating indicators for cosmos (USD): ['date', 'open', 'high', 'low', 'close', 'cosmos_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for cosmos (cosmos_btc): ['date', 'open', 'high', 'low', 'close', 'cosmos_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for cosmos (BTC): ['date', 'open', 'high', 'low', 'close', 'cosmos_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  34%|███▍      | 44/128 [01:29<03:35,  2.57s/it]

Initial columns after loading asset data for the-open-network: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for the-open-network: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for the-open-network: ['date', 'open', 'high', 'low', 'close', 'the-open-network_btc']
Columns after numeric conversion and dropna for the-open-network (close): ['date', 'open', 'high', 'low', 'close', 'the-open-network_btc']
Columns after calculating indicators for the-open-network (USD): ['date', 'open', 'high', 'low', 'close', 'the-open-network_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for the-open-network (the-open-network_btc): ['date', 'open', 'high', 'low', 'close', 'the-open-network_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for the-open-network (BTC): ['date', 'open', 'high', 'low', 'close', 'the-open-network_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  35%|███▌      | 45/128 [01:31<03:20,  2.42s/it]

Initial columns after loading asset data for ethereum-classic: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for ethereum-classic: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for ethereum-classic: ['date', 'open', 'high', 'low', 'close', 'ethereum-classic_btc']
Columns after numeric conversion and dropna for ethereum-classic (close): ['date', 'open', 'high', 'low', 'close', 'ethereum-classic_btc']
Columns after calculating indicators for ethereum-classic (USD): ['date', 'open', 'high', 'low', 'close', 'ethereum-classic_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for ethereum-classic (ethereum-classic_btc): ['date', 'open', 'high', 'low', 'close', 'ethereum-classic_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for ethereum-classic (BTC): ['date', 'open', 'high', 'low', 'close', 'ethereum-classic_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  36%|███▌      | 46/128 [01:36<04:06,  3.01s/it]

Initial columns after loading asset data for chainlink: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for chainlink: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for chainlink: ['date', 'open', 'high', 'low', 'close', 'chainlink_btc']
Columns after numeric conversion and dropna for chainlink (close): ['date', 'open', 'high', 'low', 'close', 'chainlink_btc']
Columns after calculating indicators for chainlink (USD): ['date', 'open', 'high', 'low', 'close', 'chainlink_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for chainlink (chainlink_btc): ['date', 'open', 'high', 'low', 'close', 'chainlink_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for chainlink (BTC): ['date', 'open', 'high', 'low', 'close', 'chainlink_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  37%|███▋      | 47/128 [01:39<04:20,  3.22s/it]

Initial columns after loading asset data for polkadot: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for polkadot: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for polkadot: ['date', 'open', 'high', 'low', 'close', 'polkadot_btc']
Columns after numeric conversion and dropna for polkadot (close): ['date', 'open', 'high', 'low', 'close', 'polkadot_btc']
Columns after calculating indicators for polkadot (USD): ['date', 'open', 'high', 'low', 'close', 'polkadot_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for polkadot (polkadot_btc): ['date', 'open', 'high', 'low', 'close', 'polkadot_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for polkadot (BTC): ['date', 'open', 'high', 'low', 'close', 'polkadot_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  38%|███▊      | 48/128 [01:42<03:55,  2.95s/it]

Initial columns after loading asset data for internet-computer: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for internet-computer: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for internet-computer: ['date', 'open', 'high', 'low', 'close', 'internet-computer_btc']
Columns after numeric conversion and dropna for internet-computer (close): ['date', 'open', 'high', 'low', 'close', 'internet-computer_btc']
Columns after calculating indicators for internet-computer (USD): ['date', 'open', 'high', 'low', 'close', 'internet-computer_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for internet-computer (internet-computer_btc): ['date', 'open', 'high', 'low', 'close', 'internet-computer_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for internet-computer (BTC): ['date', 'open', 'high', 'low', 'close', 'internet-computer_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  38%|███▊      | 49/128 [01:44<03:29,  2.65s/it]

Initial columns after loading asset data for bittensor: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for bittensor: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for bittensor: ['date', 'open', 'high', 'low', 'close', 'bittensor_btc']
Columns after numeric conversion and dropna for bittensor (close): ['date', 'open', 'high', 'low', 'close', 'bittensor_btc']
Columns after calculating indicators for bittensor (USD): ['date', 'open', 'high', 'low', 'close', 'bittensor_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for bittensor (bittensor_btc): ['date', 'open', 'high', 'low', 'close', 'bittensor_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for bittensor (BTC): ['date', 'open', 'high', 'low', 'close', 'bittensor_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  39%|███▉      | 50/128 [01:45<02:49,  2.17s/it]

Initial columns after loading asset data for gmx: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for gmx: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for gmx: ['date', 'open', 'high', 'low', 'close', 'gmx_btc']
Columns after numeric conversion and dropna for gmx (close): ['date', 'open', 'high', 'low', 'close', 'gmx_btc']
Columns after calculating indicators for gmx (USD): ['date', 'open', 'high', 'low', 'close', 'gmx_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for gmx (gmx_btc): ['date', 'open', 'high', 'low', 'close', 'gmx_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for gmx (BTC): ['date', 'open', 'high', 'low', 'close', 'gmx_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  40%|███▉      | 51/128 [01:47<02:38,  2.05s/it]

Initial columns after loading asset data for neon: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for neon: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for neon: ['date', 'open', 'high', 'low', 'close', 'neon_btc']
Columns after numeric conversion and dropna for neon (close): ['date', 'open', 'high', 'low', 'close', 'neon_btc']
Columns after calculating indicators for neon (USD): ['date', 'open', 'high', 'low', 'close', 'neon_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for neon (neon_btc): ['date', 'open', 'high', 'low', 'close', 'neon_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for neon (BTC): ['date', 'open', 'high', 'low', 'close', 'neon_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  41%|████      | 52/128 [01:47<02:08,  1.69s/it]

Initial columns after loading asset data for gains-network: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for gains-network: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for gains-network: ['date', 'open', 'high', 'low', 'close', 'gains-network_btc']
Columns after numeric conversion and dropna for gains-network (close): ['date', 'open', 'high', 'low', 'close', 'gains-network_btc']
Columns after calculating indicators for gains-network (USD): ['date', 'open', 'high', 'low', 'close', 'gains-network_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for gains-network (gains-network_btc): ['date', 'open', 'high', 'low', 'close', 'gains-network_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for gains-network (BTC): ['date', 'open', 'high', 'low', 'close', 'gains-network_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  41%|████▏     | 53/128 [01:49<02:07,  1.70s/it]

Initial columns after loading asset data for crypto-com-chain: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for crypto-com-chain: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for crypto-com-chain: ['date', 'open', 'high', 'low', 'close', 'crypto-com-chain_btc']
Columns after numeric conversion and dropna for crypto-com-chain (close): ['date', 'open', 'high', 'low', 'close', 'crypto-com-chain_btc']
Columns after calculating indicators for crypto-com-chain (USD): ['date', 'open', 'high', 'low', 'close', 'crypto-com-chain_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for crypto-com-chain (crypto-com-chain_btc): ['date', 'open', 'high', 'low', 'close', 'crypto-com-chain_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for crypto-com-chain (BTC): ['date', 'open', 'high', 'low', 'close', 'crypto-com-chain_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  42%|████▏     | 54/128 [01:52<02:42,  2.19s/it]

Initial columns after loading asset data for tezos: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for tezos: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for tezos: ['date', 'open', 'high', 'low', 'close', 'tezos_btc']
Columns after numeric conversion and dropna for tezos (close): ['date', 'open', 'high', 'low', 'close', 'tezos_btc']
Columns after calculating indicators for tezos (USD): ['date', 'open', 'high', 'low', 'close', 'tezos_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for tezos (tezos_btc): ['date', 'open', 'high', 'low', 'close', 'tezos_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for tezos (BTC): ['date', 'open', 'high', 'low', 'close', 'tezos_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  43%|████▎     | 55/128 [01:56<03:06,  2.56s/it]

Initial columns after loading asset data for gala: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for gala: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for gala: ['date', 'open', 'high', 'low', 'close', 'gala_btc']
Columns after numeric conversion and dropna for gala (close): ['date', 'open', 'high', 'low', 'close', 'gala_btc']
Columns after calculating indicators for gala (USD): ['date', 'open', 'high', 'low', 'close', 'gala_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for gala (gala_btc): ['date', 'open', 'high', 'low', 'close', 'gala_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for gala (BTC): ['date', 'open', 'high', 'low', 'close', 'gala_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  44%|████▍     | 56/128 [01:58<02:58,  2.48s/it]

Initial columns after loading asset data for yield-guild-games: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for yield-guild-games: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for yield-guild-games: ['date', 'open', 'high', 'low', 'close', 'yield-guild-games_btc']
Columns after numeric conversion and dropna for yield-guild-games (close): ['date', 'open', 'high', 'low', 'close', 'yield-guild-games_btc']
Columns after calculating indicators for yield-guild-games (USD): ['date', 'open', 'high', 'low', 'close', 'yield-guild-games_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for yield-guild-games (yield-guild-games_btc): ['date', 'open', 'high', 'low', 'close', 'yield-guild-games_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for yield-guild-games (BTC): ['date', 'open', 'high', 'low', 'close', 'yield-guild-games_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  45%|████▍     | 57/128 [02:00<02:42,  2.29s/it]

Initial columns after loading asset data for my-neighbor-alice: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for my-neighbor-alice: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for my-neighbor-alice: ['date', 'open', 'high', 'low', 'close', 'my-neighbor-alice_btc']
Columns after numeric conversion and dropna for my-neighbor-alice (close): ['date', 'open', 'high', 'low', 'close', 'my-neighbor-alice_btc']
Columns after calculating indicators for my-neighbor-alice (USD): ['date', 'open', 'high', 'low', 'close', 'my-neighbor-alice_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for my-neighbor-alice (my-neighbor-alice_btc): ['date', 'open', 'high', 'low', 'close', 'my-neighbor-alice_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for my-neighbor-alice (BTC): ['date', 'open', 'high', 'low', 'close', 'my-neighbor-alice_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  45%|████▌     | 58/128 [02:02<02:34,  2.21s/it]

Initial columns after loading asset data for near: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for near: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for near: ['date', 'open', 'high', 'low', 'close', 'near_btc']
Columns after numeric conversion and dropna for near (close): ['date', 'open', 'high', 'low', 'close', 'near_btc']
Columns after calculating indicators for near (USD): ['date', 'open', 'high', 'low', 'close', 'near_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for near (near_btc): ['date', 'open', 'high', 'low', 'close', 'near_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for near (BTC): ['date', 'open', 'high', 'low', 'close', 'near_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  46%|████▌     | 59/128 [02:04<02:33,  2.23s/it]

Initial columns after loading asset data for lido-dao: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for lido-dao: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for lido-dao: ['date', 'open', 'high', 'low', 'close', 'lido-dao_btc']
Columns after numeric conversion and dropna for lido-dao (close): ['date', 'open', 'high', 'low', 'close', 'lido-dao_btc']
Columns after calculating indicators for lido-dao (USD): ['date', 'open', 'high', 'low', 'close', 'lido-dao_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for lido-dao (lido-dao_btc): ['date', 'open', 'high', 'low', 'close', 'lido-dao_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for lido-dao (BTC): ['date', 'open', 'high', 'low', 'close', 'lido-dao_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  47%|████▋     | 60/128 [02:06<02:29,  2.20s/it]

Initial columns after loading asset data for yearn-finance: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for yearn-finance: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for yearn-finance: ['date', 'open', 'high', 'low', 'close', 'yearn-finance_btc']
Columns after numeric conversion and dropna for yearn-finance (close): ['date', 'open', 'high', 'low', 'close', 'yearn-finance_btc']
Columns after calculating indicators for yearn-finance (USD): ['date', 'open', 'high', 'low', 'close', 'yearn-finance_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for yearn-finance (yearn-finance_btc): ['date', 'open', 'high', 'low', 'close', 'yearn-finance_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for yearn-finance (BTC): ['date', 'open', 'high', 'low', 'close', 'yearn-finance_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  48%|████▊     | 61/128 [02:09<02:35,  2.33s/it]

Initial columns after loading asset data for tether: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for tether: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for tether: ['date', 'open', 'high', 'low', 'close', 'tether_btc']
Columns after numeric conversion and dropna for tether (close): ['date', 'open', 'high', 'low', 'close', 'tether_btc']
Columns after calculating indicators for tether (USD): ['date', 'open', 'high', 'low', 'close', 'tether_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for tether (tether_btc): ['date', 'open', 'high', 'low', 'close', 'tether_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for tether (BTC): ['date', 'open', 'high', 'low', 'close', 'tether_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  48%|████▊     | 62/128 [02:14<03:28,  3.15s/it]

Initial columns after loading asset data for usd-coin: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for usd-coin: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for usd-coin: ['date', 'open', 'high', 'low', 'close', 'usd-coin_btc']
Columns after numeric conversion and dropna for usd-coin (close): ['date', 'open', 'high', 'low', 'close', 'usd-coin_btc']
Columns after calculating indicators for usd-coin (USD): ['date', 'open', 'high', 'low', 'close', 'usd-coin_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for usd-coin (usd-coin_btc): ['date', 'open', 'high', 'low', 'close', 'usd-coin_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for usd-coin (BTC): ['date', 'open', 'high', 'low', 'close', 'usd-coin_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  49%|████▉     | 63/128 [02:17<03:26,  3.18s/it]

Initial columns after loading asset data for flow: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for flow: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for flow: ['date', 'open', 'high', 'low', 'close', 'flow_btc']
Columns after numeric conversion and dropna for flow (close): ['date', 'open', 'high', 'low', 'close', 'flow_btc']
Columns after calculating indicators for flow (USD): ['date', 'open', 'high', 'low', 'close', 'flow_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for flow (flow_btc): ['date', 'open', 'high', 'low', 'close', 'flow_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for flow (BTC): ['date', 'open', 'high', 'low', 'close', 'flow_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  50%|█████     | 64/128 [02:20<03:04,  2.88s/it]

Initial columns after loading asset data for balancer: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for balancer: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for balancer: ['date', 'open', 'high', 'low', 'close', 'balancer_btc']
Columns after numeric conversion and dropna for balancer (close): ['date', 'open', 'high', 'low', 'close', 'balancer_btc']
Columns after calculating indicators for balancer (USD): ['date', 'open', 'high', 'low', 'close', 'balancer_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for balancer (balancer_btc): ['date', 'open', 'high', 'low', 'close', 'balancer_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for balancer (BTC): ['date', 'open', 'high', 'low', 'close', 'balancer_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  51%|█████     | 65/128 [02:22<02:53,  2.76s/it]

Initial columns after loading asset data for blockstack: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for blockstack: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for blockstack: ['date', 'open', 'high', 'low', 'close', 'blockstack_btc']
Columns after numeric conversion and dropna for blockstack (close): ['date', 'open', 'high', 'low', 'close', 'blockstack_btc']
Columns after calculating indicators for blockstack (USD): ['date', 'open', 'high', 'low', 'close', 'blockstack_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for blockstack (blockstack_btc): ['date', 'open', 'high', 'low', 'close', 'blockstack_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for blockstack (BTC): ['date', 'open', 'high', 'low', 'close', 'blockstack_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  52%|█████▏    | 66/128 [02:25<02:51,  2.76s/it]

Initial columns after loading asset data for eos: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for eos: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for eos: ['date', 'open', 'high', 'low', 'close', 'eos_btc']
Columns after numeric conversion and dropna for eos (close): ['date', 'open', 'high', 'low', 'close', 'eos_btc']
Columns after calculating indicators for eos (USD): ['date', 'open', 'high', 'low', 'close', 'eos_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for eos (eos_btc): ['date', 'open', 'high', 'low', 'close', 'eos_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for eos (BTC): ['date', 'open', 'high', 'low', 'close', 'eos_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  52%|█████▏    | 67/128 [02:29<03:14,  3.19s/it]

Initial columns after loading asset data for akash-network: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for akash-network: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for akash-network: ['date', 'open', 'high', 'low', 'close', 'akash-network_btc']
Columns after numeric conversion and dropna for akash-network (close): ['date', 'open', 'high', 'low', 'close', 'akash-network_btc']
Columns after calculating indicators for akash-network (USD): ['date', 'open', 'high', 'low', 'close', 'akash-network_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for akash-network (akash-network_btc): ['date', 'open', 'high', 'low', 'close', 'akash-network_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for akash-network (BTC): ['date', 'open', 'high', 'low', 'close', 'akash-network_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  53%|█████▎    | 68/128 [02:31<02:54,  2.90s/it]

Initial columns after loading asset data for cardano: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for cardano: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for cardano: ['date', 'open', 'high', 'low', 'close', 'cardano_btc']
Columns after numeric conversion and dropna for cardano (close): ['date', 'open', 'high', 'low', 'close', 'cardano_btc']
Columns after calculating indicators for cardano (USD): ['date', 'open', 'high', 'low', 'close', 'cardano_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for cardano (cardano_btc): ['date', 'open', 'high', 'low', 'close', 'cardano_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for cardano (BTC): ['date', 'open', 'high', 'low', 'close', 'cardano_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  54%|█████▍    | 69/128 [02:35<03:06,  3.15s/it]

Initial columns after loading asset data for solana: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for solana: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for solana: ['date', 'open', 'high', 'low', 'close', 'solana_btc']
Columns after numeric conversion and dropna for solana (close): ['date', 'open', 'high', 'low', 'close', 'solana_btc']
Columns after calculating indicators for solana (USD): ['date', 'open', 'high', 'low', 'close', 'solana_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for solana (solana_btc): ['date', 'open', 'high', 'low', 'close', 'solana_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for solana (BTC): ['date', 'open', 'high', 'low', 'close', 'solana_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  55%|█████▍    | 70/128 [02:38<02:55,  3.02s/it]

Initial columns after loading asset data for nunet: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for nunet: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for nunet: ['date', 'open', 'high', 'low', 'close', 'nunet_btc']
Columns after numeric conversion and dropna for nunet (close): ['date', 'open', 'high', 'low', 'close', 'nunet_btc']
Columns after calculating indicators for nunet (USD): ['date', 'open', 'high', 'low', 'close', 'nunet_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for nunet (nunet_btc): ['date', 'open', 'high', 'low', 'close', 'nunet_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for nunet (BTC): ['date', 'open', 'high', 'low', 'close', 'nunet_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  55%|█████▌    | 71/128 [02:39<02:29,  2.62s/it]

Initial columns after loading asset data for raydium: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for raydium: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for raydium: ['date', 'open', 'high', 'low', 'close', 'raydium_btc']
Columns after numeric conversion and dropna for raydium (close): ['date', 'open', 'high', 'low', 'close', 'raydium_btc']
Columns after calculating indicators for raydium (USD): ['date', 'open', 'high', 'low', 'close', 'raydium_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for raydium (raydium_btc): ['date', 'open', 'high', 'low', 'close', 'raydium_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for raydium (BTC): ['date', 'open', 'high', 'low', 'close', 'raydium_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  56%|█████▋    | 72/128 [02:41<02:17,  2.46s/it]

Initial columns after loading asset data for smartcash: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for smartcash: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for smartcash: ['date', 'open', 'high', 'low', 'close', 'smartcash_btc']
Columns after numeric conversion and dropna for smartcash (close): ['date', 'open', 'high', 'low', 'close', 'smartcash_btc']
Columns after calculating indicators for smartcash (USD): ['date', 'open', 'high', 'low', 'close', 'smartcash_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for smartcash (smartcash_btc): ['date', 'open', 'high', 'low', 'close', 'smartcash_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for smartcash (BTC): ['date', 'open', 'high', 'low', 'close', 'smartcash_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  57%|█████▋    | 73/128 [02:45<02:37,  2.86s/it]

Initial columns after loading asset data for sui: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for sui: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for sui: ['date', 'open', 'high', 'low', 'close', 'sui_btc']
Columns after numeric conversion and dropna for sui (close): ['date', 'open', 'high', 'low', 'close', 'sui_btc']
Columns after calculating indicators for sui (USD): ['date', 'open', 'high', 'low', 'close', 'sui_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for sui (sui_btc): ['date', 'open', 'high', 'low', 'close', 'sui_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for sui (BTC): ['date', 'open', 'high', 'low', 'close', 'sui_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  58%|█████▊    | 74/128 [02:46<02:03,  2.29s/it]

Initial columns after loading asset data for true-usd: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for true-usd: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for true-usd: ['date', 'open', 'high', 'low', 'close', 'true-usd_btc']
Columns after numeric conversion and dropna for true-usd (close): ['date', 'open', 'high', 'low', 'close', 'true-usd_btc']
Columns after calculating indicators for true-usd (USD): ['date', 'open', 'high', 'low', 'close', 'true-usd_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for true-usd (true-usd_btc): ['date', 'open', 'high', 'low', 'close', 'true-usd_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for true-usd (BTC): ['date', 'open', 'high', 'low', 'close', 'true-usd_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  59%|█████▊    | 75/128 [02:50<02:21,  2.67s/it]

Initial columns after loading asset data for pancakeswap-token: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for pancakeswap-token: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for pancakeswap-token: ['date', 'open', 'high', 'low', 'close', 'pancakeswap-token_btc']
Columns after numeric conversion and dropna for pancakeswap-token (close): ['date', 'open', 'high', 'low', 'close', 'pancakeswap-token_btc']
Columns after calculating indicators for pancakeswap-token (USD): ['date', 'open', 'high', 'low', 'close', 'pancakeswap-token_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for pancakeswap-token (pancakeswap-token_btc): ['date', 'open', 'high', 'low', 'close', 'pancakeswap-token_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for pancakeswap-token (BTC): ['date', 'open', 'high', 'low', 'close', 'pancakeswap-token_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  59%|█████▉    | 76/128 [02:52<02:13,  2.57s/it]

Initial columns after loading asset data for thorchain: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for thorchain: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for thorchain: ['date', 'open', 'high', 'low', 'close', 'thorchain_btc']
Columns after numeric conversion and dropna for thorchain (close): ['date', 'open', 'high', 'low', 'close', 'thorchain_btc']
Columns after calculating indicators for thorchain (USD): ['date', 'open', 'high', 'low', 'close', 'thorchain_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for thorchain (thorchain_btc): ['date', 'open', 'high', 'low', 'close', 'thorchain_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for thorchain (BTC): ['date', 'open', 'high', 'low', 'close', 'thorchain_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  60%|██████    | 77/128 [02:55<02:19,  2.74s/it]

Initial columns after loading asset data for dash: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for dash: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for dash: ['date', 'open', 'high', 'low', 'close', 'dash_btc']
Columns after numeric conversion and dropna for dash (close): ['date', 'open', 'high', 'low', 'close', 'dash_btc']
Columns after calculating indicators for dash (USD): ['date', 'open', 'high', 'low', 'close', 'dash_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for dash (dash_btc): ['date', 'open', 'high', 'low', 'close', 'dash_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for dash (BTC): ['date', 'open', 'high', 'low', 'close', 'dash_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  61%|██████    | 78/128 [03:01<03:01,  3.64s/it]

Initial columns after loading asset data for litecoin: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for litecoin: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for litecoin: ['date', 'open', 'high', 'low', 'close', 'litecoin_btc']
Columns after numeric conversion and dropna for litecoin (close): ['date', 'open', 'high', 'low', 'close', 'litecoin_btc']
Columns after calculating indicators for litecoin (USD): ['date', 'open', 'high', 'low', 'close', 'litecoin_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for litecoin (litecoin_btc): ['date', 'open', 'high', 'low', 'close', 'litecoin_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for litecoin (BTC): ['date', 'open', 'high', 'low', 'close', 'litecoin_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  62%|██████▏   | 79/128 [03:07<03:33,  4.36s/it]

Initial columns after loading asset data for ripple: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for ripple: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for ripple: ['date', 'open', 'high', 'low', 'close', 'ripple_btc']
Columns after numeric conversion and dropna for ripple (close): ['date', 'open', 'high', 'low', 'close', 'ripple_btc']
Columns after calculating indicators for ripple (USD): ['date', 'open', 'high', 'low', 'close', 'ripple_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for ripple (ripple_btc): ['date', 'open', 'high', 'low', 'close', 'ripple_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for ripple (BTC): ['date', 'open', 'high', 'low', 'close', 'ripple_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  62%|██████▎   | 80/128 [03:13<03:53,  4.86s/it]

Initial columns after loading asset data for genopets: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for genopets: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for genopets: ['date', 'open', 'high', 'low', 'close', 'genopets_btc']
Columns after numeric conversion and dropna for genopets (close): ['date', 'open', 'high', 'low', 'close', 'genopets_btc']
Columns after calculating indicators for genopets (USD): ['date', 'open', 'high', 'low', 'close', 'genopets_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for genopets (genopets_btc): ['date', 'open', 'high', 'low', 'close', 'genopets_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for genopets (BTC): ['date', 'open', 'high', 'low', 'close', 'genopets_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  63%|██████▎   | 81/128 [03:15<03:04,  3.92s/it]

Initial columns after loading asset data for avalanche-2: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for avalanche-2: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for avalanche-2: ['date', 'open', 'high', 'low', 'close', 'avalanche-2_btc']
Columns after numeric conversion and dropna for avalanche-2 (close): ['date', 'open', 'high', 'low', 'close', 'avalanche-2_btc']
Columns after calculating indicators for avalanche-2 (USD): ['date', 'open', 'high', 'low', 'close', 'avalanche-2_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for avalanche-2 (avalanche-2_btc): ['date', 'open', 'high', 'low', 'close', 'avalanche-2_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for avalanche-2 (BTC): ['date', 'open', 'high', 'low', 'close', 'avalanche-2_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  64%|██████▍   | 82/128 [03:17<02:37,  3.42s/it]

Initial columns after loading asset data for the-sandbox: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for the-sandbox: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for the-sandbox: ['date', 'open', 'high', 'low', 'close', 'the-sandbox_btc']
Columns after numeric conversion and dropna for the-sandbox (close): ['date', 'open', 'high', 'low', 'close', 'the-sandbox_btc']
Columns after calculating indicators for the-sandbox (USD): ['date', 'open', 'high', 'low', 'close', 'the-sandbox_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for the-sandbox (the-sandbox_btc): ['date', 'open', 'high', 'low', 'close', 'the-sandbox_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for the-sandbox (BTC): ['date', 'open', 'high', 'low', 'close', 'the-sandbox_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  65%|██████▍   | 83/128 [03:19<02:19,  3.10s/it]

Initial columns after loading asset data for numeraire: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for numeraire: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for numeraire: ['date', 'open', 'high', 'low', 'close', 'numeraire_btc']
Columns after numeric conversion and dropna for numeraire (close): ['date', 'open', 'high', 'low', 'close', 'numeraire_btc']
Columns after calculating indicators for numeraire (USD): ['date', 'open', 'high', 'low', 'close', 'numeraire_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for numeraire (numeraire_btc): ['date', 'open', 'high', 'low', 'close', 'numeraire_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for numeraire (BTC): ['date', 'open', 'high', 'low', 'close', 'numeraire_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  66%|██████▌   | 84/128 [03:23<02:29,  3.40s/it]

Initial columns after loading asset data for lisk: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for lisk: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for lisk: ['date', 'open', 'high', 'low', 'close', 'lisk_btc']
Columns after numeric conversion and dropna for lisk (close): ['date', 'open', 'high', 'low', 'close', 'lisk_btc']
Columns after calculating indicators for lisk (USD): ['date', 'open', 'high', 'low', 'close', 'lisk_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for lisk (lisk_btc): ['date', 'open', 'high', 'low', 'close', 'lisk_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for lisk (BTC): ['date', 'open', 'high', 'low', 'close', 'lisk_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  66%|██████▋   | 85/128 [03:28<02:41,  3.75s/it]

Initial columns after loading asset data for terra-luna-2: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for terra-luna-2: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for terra-luna-2: ['date', 'open', 'high', 'low', 'close', 'terra-luna-2_btc']
Columns after numeric conversion and dropna for terra-luna-2 (close): ['date', 'open', 'high', 'low', 'close', 'terra-luna-2_btc']
Columns after calculating indicators for terra-luna-2 (USD): ['date', 'open', 'high', 'low', 'close', 'terra-luna-2_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for terra-luna-2 (terra-luna-2_btc): ['date', 'open', 'high', 'low', 'close', 'terra-luna-2_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for terra-luna-2 (BTC): ['date', 'open', 'high', 'low', 'close', 'terra-luna-2_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  67%|██████▋   | 86/128 [03:29<02:08,  3.07s/it]

Initial columns after loading asset data for genesysgo-shadow: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for genesysgo-shadow: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for genesysgo-shadow: ['date', 'open', 'high', 'low', 'close', 'genesysgo-shadow_btc']
Columns after numeric conversion and dropna for genesysgo-shadow (close): ['date', 'open', 'high', 'low', 'close', 'genesysgo-shadow_btc']
Columns after calculating indicators for genesysgo-shadow (USD): ['date', 'open', 'high', 'low', 'close', 'genesysgo-shadow_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for genesysgo-shadow (genesysgo-shadow_btc): ['date', 'open', 'high', 'low', 'close', 'genesysgo-shadow_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for genesysgo-shadow (BTC): ['date', 'open', 'high', 'low', 'close', 'genesysgo-shadow_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  68%|██████▊   | 87/128 [03:31<01:48,  2.64s/it]

Initial columns after loading asset data for helium: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for helium: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for helium: ['date', 'open', 'high', 'low', 'close', 'helium_btc']
Columns after numeric conversion and dropna for helium (close): ['date', 'open', 'high', 'low', 'close', 'helium_btc']
Columns after calculating indicators for helium (USD): ['date', 'open', 'high', 'low', 'close', 'helium_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for helium (helium_btc): ['date', 'open', 'high', 'low', 'close', 'helium_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for helium (BTC): ['date', 'open', 'high', 'low', 'close', 'helium_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  69%|██████▉   | 88/128 [03:34<01:43,  2.59s/it]

Initial columns after loading asset data for optimism: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for optimism: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for optimism: ['date', 'open', 'high', 'low', 'close', 'optimism_btc']
Columns after numeric conversion and dropna for optimism (close): ['date', 'open', 'high', 'low', 'close', 'optimism_btc']
Columns after calculating indicators for optimism (USD): ['date', 'open', 'high', 'low', 'close', 'optimism_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for optimism (optimism_btc): ['date', 'open', 'high', 'low', 'close', 'optimism_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for optimism (BTC): ['date', 'open', 'high', 'low', 'close', 'optimism_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  70%|██████▉   | 89/128 [03:35<01:27,  2.24s/it]

Initial columns after loading asset data for ondo-finance: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for ondo-finance: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for ondo-finance: ['date', 'open', 'high', 'low', 'close', 'ondo-finance_btc']
Columns after numeric conversion and dropna for ondo-finance (close): ['date', 'open', 'high', 'low', 'close', 'ondo-finance_btc']
Columns after calculating indicators for ondo-finance (USD): ['date', 'open', 'high', 'low', 'close', 'ondo-finance_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for ondo-finance (ondo-finance_btc): ['date', 'open', 'high', 'low', 'close', 'ondo-finance_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for ondo-finance (BTC): ['date', 'open', 'high', 'low', 'close', 'ondo-finance_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  70%|███████   | 90/128 [03:36<01:06,  1.75s/it]

Initial columns after loading asset data for wrapped-nxm: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for wrapped-nxm: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for wrapped-nxm: ['date', 'open', 'high', 'low', 'close', 'wrapped-nxm_btc']
Columns after numeric conversion and dropna for wrapped-nxm (close): ['date', 'open', 'high', 'low', 'close', 'wrapped-nxm_btc']
Columns after calculating indicators for wrapped-nxm (USD): ['date', 'open', 'high', 'low', 'close', 'wrapped-nxm_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for wrapped-nxm (wrapped-nxm_btc): ['date', 'open', 'high', 'low', 'close', 'wrapped-nxm_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for wrapped-nxm (BTC): ['date', 'open', 'high', 'low', 'close', 'wrapped-nxm_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  71%|███████   | 91/128 [03:38<01:11,  1.93s/it]

Initial columns after loading asset data for hedera-hashgraph: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for hedera-hashgraph: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for hedera-hashgraph: ['date', 'open', 'high', 'low', 'close', 'hedera-hashgraph_btc']
Columns after numeric conversion and dropna for hedera-hashgraph (close): ['date', 'open', 'high', 'low', 'close', 'hedera-hashgraph_btc']
Columns after calculating indicators for hedera-hashgraph (USD): ['date', 'open', 'high', 'low', 'close', 'hedera-hashgraph_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for hedera-hashgraph (hedera-hashgraph_btc): ['date', 'open', 'high', 'low', 'close', 'hedera-hashgraph_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for hedera-hashgraph (BTC): ['date', 'open', 'high', 'low', 'close', 'hedera-hashgraph_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  72%|███████▏  | 92/128 [03:41<01:21,  2.26s/it]

Initial columns after loading asset data for arweave: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for arweave: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for arweave: ['date', 'open', 'high', 'low', 'close', 'arweave_btc']
Columns after numeric conversion and dropna for arweave (close): ['date', 'open', 'high', 'low', 'close', 'arweave_btc']
Columns after calculating indicators for arweave (USD): ['date', 'open', 'high', 'low', 'close', 'arweave_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for arweave (arweave_btc): ['date', 'open', 'high', 'low', 'close', 'arweave_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for arweave (BTC): ['date', 'open', 'high', 'low', 'close', 'arweave_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  73%|███████▎  | 93/128 [03:44<01:27,  2.50s/it]

Initial columns after loading asset data for badger-dao: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for badger-dao: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for badger-dao: ['date', 'open', 'high', 'low', 'close', 'badger-dao_btc']
Columns after numeric conversion and dropna for badger-dao (close): ['date', 'open', 'high', 'low', 'close', 'badger-dao_btc']
Columns after calculating indicators for badger-dao (USD): ['date', 'open', 'high', 'low', 'close', 'badger-dao_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for badger-dao (badger-dao_btc): ['date', 'open', 'high', 'low', 'close', 'badger-dao_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for badger-dao (BTC): ['date', 'open', 'high', 'low', 'close', 'badger-dao_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  73%|███████▎  | 94/128 [03:46<01:21,  2.41s/it]

Initial columns after loading asset data for mantra-dao: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for mantra-dao: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for mantra-dao: ['date', 'open', 'high', 'low', 'close', 'mantra-dao_btc']
Columns after numeric conversion and dropna for mantra-dao (close): ['date', 'open', 'high', 'low', 'close', 'mantra-dao_btc']
Columns after calculating indicators for mantra-dao (USD): ['date', 'open', 'high', 'low', 'close', 'mantra-dao_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for mantra-dao (mantra-dao_btc): ['date', 'open', 'high', 'low', 'close', 'mantra-dao_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for mantra-dao (BTC): ['date', 'open', 'high', 'low', 'close', 'mantra-dao_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  75%|███████▌  | 96/128 [03:49<00:54,  1.71s/it]

Initial columns after loading asset data for hyperliquid: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for hyperliquid: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for hyperliquid: ['date', 'open', 'high', 'low', 'close', 'hyperliquid_btc']
Columns after numeric conversion and dropna for hyperliquid (close): ['date', 'open', 'high', 'low', 'close', 'hyperliquid_btc']
Columns after calculating indicators for hyperliquid (USD): ['date', 'open', 'high', 'low', 'close', 'hyperliquid_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for hyperliquid (hyperliquid_btc): ['date', 'open', 'high', 'low', 'close', 'hyperliquid_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for hyperliquid (BTC): ['date', 'open', 'high', 'low', 'close', 'hyperliquid_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']
Initial columns after loading asset data for audius: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for audius: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for audius: ['date', 'open', 'high', 'low', 'close', 'audius_btc']
Columns after numeric conversion and dropna for audius (close): ['date', 'open', 'high', 'low', 'close', 'audius_btc']
Columns after calculating indicators for audius (USD): ['date', 'open', 'high', 'low', 'close', 'audius_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for audius (audius_btc): ['date', 'open', 'high', 'low', 'close', 'audius_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for audius (BTC): ['date', 'open', 'high', 'low', 'close', 'audius_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  77%|███████▋  | 98/128 [03:51<00:40,  1.36s/it]

Initial columns after loading asset data for griffain: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for griffain: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for griffain: ['date', 'open', 'high', 'low', 'close', 'griffain_btc']
Columns after numeric conversion and dropna for griffain (close): ['date', 'open', 'high', 'low', 'close', 'griffain_btc']
Columns after calculating indicators for griffain (USD): ['date', 'open', 'high', 'low', 'close', 'griffain_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for griffain (griffain_btc): ['date', 'open', 'high', 'low', 'close', 'griffain_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for griffain (BTC): ['date', 'open', 'high', 'low', 'close', 'griffain_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']
Initial columns after loading asset data for ethena: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for ethena: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for ethena: ['date', 'open', 'high', 'low', 'close', 'ethena_btc']
Columns after numeric conversion and dropna for ethena (close): ['date', 'open', 'high', 'low', 'close', 'ethena_btc']
Columns after calculating indicators for ethena (USD): ['date', 'open', 'high', 'low', 'close', 'ethena_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for ethena (ethena_btc): ['date', 'open', 'high', 'low', 'close', 'ethena_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for ethena (BTC): ['date', 'open', 'high', 'low', 'close', 'ethena_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  77%|███████▋  | 99/128 [03:52<00:31,  1.10s/it]

Initial columns after loading asset data for beam-2: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for beam-2: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for beam-2: ['date', 'open', 'high', 'low', 'close', 'beam-2_btc']
Columns after numeric conversion and dropna for beam-2 (close): ['date', 'open', 'high', 'low', 'close', 'beam-2_btc']
Columns after calculating indicators for beam-2 (USD): ['date', 'open', 'high', 'low', 'close', 'beam-2_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for beam-2 (beam-2_btc): ['date', 'open', 'high', 'low', 'close', 'beam-2_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for beam-2 (BTC): ['date', 'open', 'high', 'low', 'close', 'beam-2_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  78%|███████▊  | 100/128 [03:52<00:27,  1.02it/s]

Initial columns after loading asset data for aave: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for aave: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for aave: ['date', 'open', 'high', 'low', 'close', 'aave_btc']
Columns after numeric conversion and dropna for aave (close): ['date', 'open', 'high', 'low', 'close', 'aave_btc']
Columns after calculating indicators for aave (USD): ['date', 'open', 'high', 'low', 'close', 'aave_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for aave (aave_btc): ['date', 'open', 'high', 'low', 'close', 'aave_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for aave (BTC): ['date', 'open', 'high', 'low', 'close', 'aave_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  79%|███████▉  | 101/128 [03:55<00:39,  1.45s/it]

Initial columns after loading asset data for matic-network: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for matic-network: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for matic-network: ['date', 'open', 'high', 'low', 'close', 'matic-network_btc']
Columns after numeric conversion and dropna for matic-network (close): ['date', 'open', 'high', 'low', 'close', 'matic-network_btc']
Columns after calculating indicators for matic-network (USD): ['date', 'open', 'high', 'low', 'close', 'matic-network_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for matic-network (matic-network_btc): ['date', 'open', 'high', 'low', 'close', 'matic-network_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for matic-network (BTC): ['date', 'open', 'high', 'low', 'close', 'matic-network_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  80%|███████▉  | 102/128 [03:58<00:49,  1.92s/it]

Initial columns after loading asset data for omisego: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for omisego: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for omisego: ['date', 'open', 'high', 'low', 'close', 'omisego_btc']
Columns after numeric conversion and dropna for omisego (close): ['date', 'open', 'high', 'low', 'close', 'omisego_btc']
Columns after calculating indicators for omisego (USD): ['date', 'open', 'high', 'low', 'close', 'omisego_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for omisego (omisego_btc): ['date', 'open', 'high', 'low', 'close', 'omisego_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for omisego (BTC): ['date', 'open', 'high', 'low', 'close', 'omisego_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  81%|████████▏ | 104/128 [04:02<00:43,  1.80s/it]

Initial columns after loading asset data for orbit-3: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for orbit-3: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for orbit-3: ['date', 'open', 'high', 'low', 'close', 'orbit-3_btc']
Columns after numeric conversion and dropna for orbit-3 (close): ['date', 'open', 'high', 'low', 'close', 'orbit-3_btc']
Columns after calculating indicators for orbit-3 (USD): ['date', 'open', 'high', 'low', 'close', 'orbit-3_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for orbit-3 (orbit-3_btc): ['date', 'open', 'high', 'low', 'close', 'orbit-3_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for orbit-3 (BTC): ['date', 'open', 'high', 'low', 'close', 'orbit-3_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']
Initial columns after loading asset data for kujira: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for kujira: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for kujira: ['date', 'open', 'high', 'low', 'close', 'kujira_btc']
Columns after numeric conversion and dropna for kujira (close): ['date', 'open', 'high', 'low', 'close', 'kujira_btc']
Columns after calculating indicators for kujira (USD): ['date', 'open', 'high', 'low', 'close', 'kujira_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for kujira (kujira_btc): ['date', 'open', 'high', 'low', 'close', 'kujira_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for kujira (BTC): ['date', 'open', 'high', 'low', 'close', 'kujira_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  82%|████████▏ | 105/128 [04:04<00:40,  1.77s/it]

Initial columns after loading asset data for wibx: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for wibx: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for wibx: ['date', 'open', 'high', 'low', 'close', 'wibx_btc']
Columns after numeric conversion and dropna for wibx (close): ['date', 'open', 'high', 'low', 'close', 'wibx_btc']
Columns after calculating indicators for wibx (USD): ['date', 'open', 'high', 'low', 'close', 'wibx_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for wibx (wibx_btc): ['date', 'open', 'high', 'low', 'close', 'wibx_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for wibx (BTC): ['date', 'open', 'high', 'low', 'close', 'wibx_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  84%|████████▎ | 107/128 [04:07<00:31,  1.49s/it]

Initial columns after loading asset data for yne: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for yne: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for yne: ['date', 'open', 'high', 'low', 'close', 'yne_btc']
Columns after numeric conversion and dropna for yne (close): ['date', 'open', 'high', 'low', 'close', 'yne_btc']
Columns after calculating indicators for yne (USD): ['date', 'open', 'high', 'low', 'close', 'yne_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for yne (yne_btc): ['date', 'open', 'high', 'low', 'close', 'yne_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for yne (BTC): ['date', 'open', 'high', 'low', 'close', 'yne_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']
Initial columns after loading asset data for injective-protocol: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for injective-protocol: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for injective-protocol: ['date', 'open', 'high', 'low', 'close', 'injective-protocol_btc']
Columns after numeric conversion and dropna for injective-protocol (close): ['date', 'open', 'high', 'low', 'close', 'injective-protocol_btc']
Columns after calculating indicators for injective-protocol (USD): ['date', 'open', 'high', 'low', 'close', 'injective-protocol_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for injective-protocol (injective-protocol_btc): ['date', 'open', 'high', 'low', 'close', 'injective-protocol_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for injective-protocol (BTC): ['date', 'open', 'high', 'low', 'close', 'injective-protocol_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  85%|████████▌ | 109/128 [04:09<00:23,  1.24s/it]

Initial columns after loading asset data for heyanon: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for heyanon: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for heyanon: ['date', 'open', 'high', 'low', 'close', 'heyanon_btc']
Columns after numeric conversion and dropna for heyanon (close): ['date', 'open', 'high', 'low', 'close', 'heyanon_btc']
Columns after calculating indicators for heyanon (USD): ['date', 'open', 'high', 'low', 'close', 'heyanon_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for heyanon (heyanon_btc): ['date', 'open', 'high', 'low', 'close', 'heyanon_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for heyanon (BTC): ['date', 'open', 'high', 'low', 'close', 'heyanon_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']
Initial columns after loading asset data for ethervista: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for ethervista: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for ethervista: ['date', 'open', 'high', 'low', 'close', 'ethervista_btc']
Columns after numeric conversion and dropna for ethervista (close): ['date', 'open', 'high', 'low', 'close', 'ethervista_btc']
Columns after calculating indicators for ethervista (USD): ['date', 'open', 'high', 'low', 'close', 'ethervista_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']

Analyzing assets:  86%|████████▌ | 110/128 [04:09<00:17,  1.05it/s]

Columns after numeric conversion and dropna for ethervista (ethervista_btc): ['date', 'open', 'high', 'low', 'close', 'ethervista_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for ethervista (BTC): ['date', 'open', 'high', 'low', 'close', 'ethervista_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']
Initial columns after loading asset data for zcash: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for zcash: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for zcash: ['date', 'open', 'high', 'low', 'close', 'zcash_btc']
Columns after numeric conversion and dropna for zcash (close): ['date', 'open', 'high', 'low', 'close', 'zcash_btc']
Columns after calculating indicators for zcash (USD): ['date', 'open', 'high', 'low', 'close', 'zcash_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for zcash (zcash_btc): ['date', 'open', 'high', 'low', 'close', 'zcash_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for zcash (BTC): ['date', 'open', 'high', 'low', 'close', 'zcash_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  87%|████████▋ | 111/128 [04:13<00:33,  1.94s/it]

Initial columns after loading asset data for star-atlas-dao: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for star-atlas-dao: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for star-atlas-dao: ['date', 'open', 'high', 'low', 'close', 'star-atlas-dao_btc']
Columns after numeric conversion and dropna for star-atlas-dao (close): ['date', 'open', 'high', 'low', 'close', 'star-atlas-dao_btc']
Columns after calculating indicators for star-atlas-dao (USD): ['date', 'open', 'high', 'low', 'close', 'star-atlas-dao_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for star-atlas-dao (star-atlas-dao_btc): ['date', 'open', 'high', 'low', 'close', 'star-atlas-dao_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for star-atlas-dao (BTC): ['date', 'open', 'high', 'low', 'close', 'star-atlas-dao_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  88%|████████▊ | 112/128 [04:15<00:30,  1.92s/it]

Initial columns after loading asset data for axie-infinity: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for axie-infinity: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for axie-infinity: ['date', 'open', 'high', 'low', 'close', 'axie-infinity_btc']
Columns after numeric conversion and dropna for axie-infinity (close): ['date', 'open', 'high', 'low', 'close', 'axie-infinity_btc']
Columns after calculating indicators for axie-infinity (USD): ['date', 'open', 'high', 'low', 'close', 'axie-infinity_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for axie-infinity (axie-infinity_btc): ['date', 'open', 'high', 'low', 'close', 'axie-infinity_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for axie-infinity (BTC): ['date', 'open', 'high', 'low', 'close', 'axie-infinity_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  88%|████████▊ | 113/128 [04:18<00:30,  2.03s/it]

Initial columns after loading asset data for kyber-network-crystal: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for kyber-network-crystal: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for kyber-network-crystal: ['date', 'open', 'high', 'low', 'close', 'kyber-network-crystal_btc']
Columns after numeric conversion and dropna for kyber-network-crystal (close): ['date', 'open', 'high', 'low', 'close', 'kyber-network-crystal_btc']
Columns after calculating indicators for kyber-network-crystal (USD): ['date', 'open', 'high', 'low', 'close', 'kyber-network-crystal_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for kyber-network-crystal (kyber-network-crystal_btc): ['date', 'open', 'high', 'low', 'close', 'kyber-network-crystal_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for kyber-network-crystal (BTC): ['date', 'open', 'high', 'low', 'close', 'kyber-network-crystal_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  89%|████████▉ | 114/128 [04:20<00:28,  2.04s/it]

Initial columns after loading asset data for binancecoin: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for binancecoin: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for binancecoin: ['date', 'open', 'high', 'low', 'close', 'binancecoin_btc']
Columns after numeric conversion and dropna for binancecoin (close): ['date', 'open', 'high', 'low', 'close', 'binancecoin_btc']
Columns after calculating indicators for binancecoin (USD): ['date', 'open', 'high', 'low', 'close', 'binancecoin_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for binancecoin (binancecoin_btc): ['date', 'open', 'high', 'low', 'close', 'binancecoin_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for binancecoin (BTC): ['date', 'open', 'high', 'low', 'close', 'binancecoin_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  90%|████████▉ | 115/128 [04:24<00:34,  2.67s/it]

Initial columns after loading asset data for monero: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for monero: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for monero: ['date', 'open', 'high', 'low', 'close', 'monero_btc']
Columns after numeric conversion and dropna for monero (close): ['date', 'open', 'high', 'low', 'close', 'monero_btc']
Columns after calculating indicators for monero (USD): ['date', 'open', 'high', 'low', 'close', 'monero_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for monero (monero_btc): ['date', 'open', 'high', 'low', 'close', 'monero_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for monero (BTC): ['date', 'open', 'high', 'low', 'close', 'monero_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  91%|█████████ | 116/128 [04:29<00:42,  3.51s/it]

Initial columns after loading asset data for secret: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for secret: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for secret: ['date', 'open', 'high', 'low', 'close', 'secret_btc']
Columns after numeric conversion and dropna for secret (close): ['date', 'open', 'high', 'low', 'close', 'secret_btc']
Columns after calculating indicators for secret (USD): ['date', 'open', 'high', 'low', 'close', 'secret_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for secret (secret_btc): ['date', 'open', 'high', 'low', 'close', 'secret_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for secret (BTC): ['date', 'open', 'high', 'low', 'close', 'secret_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  91%|█████████▏| 117/128 [04:32<00:34,  3.13s/it]

Initial columns after loading asset data for radiant-capital: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for radiant-capital: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for radiant-capital: ['date', 'open', 'high', 'low', 'close', 'radiant-capital_btc']
Columns after numeric conversion and dropna for radiant-capital (close): ['date', 'open', 'high', 'low', 'close', 'radiant-capital_btc']
Columns after calculating indicators for radiant-capital (USD): ['date', 'open', 'high', 'low', 'close', 'radiant-capital_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for radiant-capital (radiant-capital_btc): ['date', 'open', 'high', 'low', 'close', 'radiant-capital_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for radiant-capital (BTC): ['date', 'open', 'high', 'low', 'close', 'radiant-capital_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  92%|█████████▏| 118/128 [04:33<00:25,  2.60s/it]

Initial columns after loading asset data for stellar: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for stellar: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for stellar: ['date', 'open', 'high', 'low', 'close', 'stellar_btc']
Columns after numeric conversion and dropna for stellar (close): ['date', 'open', 'high', 'low', 'close', 'stellar_btc']
Columns after calculating indicators for stellar (USD): ['date', 'open', 'high', 'low', 'close', 'stellar_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for stellar (stellar_btc): ['date', 'open', 'high', 'low', 'close', 'stellar_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for stellar (BTC): ['date', 'open', 'high', 'low', 'close', 'stellar_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  93%|█████████▎| 119/128 [04:38<00:31,  3.50s/it]

Initial columns after loading asset data for compound-governance-token: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for compound-governance-token: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for compound-governance-token: ['date', 'open', 'high', 'low', 'close', 'compound-governance-token_btc']
Columns after numeric conversion and dropna for compound-governance-token (close): ['date', 'open', 'high', 'low', 'close', 'compound-governance-token_btc']
Columns after calculating indicators for compound-governance-token (USD): ['date', 'open', 'high', 'low', 'close', 'compound-governance-token_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for compound-governance-token (compound-governance-token_btc): ['date', 'open', 'high', 'low', 'close', 'compound-governance-token_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for compound-governance-token (BTC): ['date', 'open', 'high', 'low', 'close', 'compound-governance-token_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  94%|█████████▍| 120/128 [04:41<00:25,  3.18s/it]

Initial columns after loading asset data for ether-fi: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for ether-fi: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for ether-fi: ['date', 'open', 'high', 'low', 'close', 'ether-fi_btc']
Columns after numeric conversion and dropna for ether-fi (close): ['date', 'open', 'high', 'low', 'close', 'ether-fi_btc']
Columns after calculating indicators for ether-fi (USD): ['date', 'open', 'high', 'low', 'close', 'ether-fi_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for ether-fi (ether-fi_btc): ['date', 'open', 'high', 'low', 'close', 'ether-fi_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for ether-fi (BTC): ['date', 'open', 'high', 'low', 'close', 'ether-fi_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  95%|█████████▌| 122/128 [04:42<00:10,  1.72s/it]

Initial columns after loading asset data for morpho: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for morpho: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for morpho: ['date', 'open', 'high', 'low', 'close', 'morpho_btc']
Columns after numeric conversion and dropna for morpho (close): ['date', 'open', 'high', 'low', 'close', 'morpho_btc']
Columns after calculating indicators for morpho (USD): ['date', 'open', 'high', 'low', 'close', 'morpho_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for morpho (morpho_btc): ['date', 'open', 'high', 'low', 'close', 'morpho_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for morpho (BTC): ['date', 'open', 'high', 'low', 'close', 'morpho_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']
Initial columns after loading asset data for guild-of-guardians: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for guild-of-guardians: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for guild-of-guardians: ['date', 'open', 'high', 'low', 'close', 'guild-of-guardians_btc']
Columns after numeric conversion and dropna for guild-of-guardians (close): ['date', 'open', 'high', 'low', 'close', 'guild-of-guardians_btc']
Columns after calculating indicators for guild-of-guardians (USD): ['date', 'open', 'high', 'low', 'close', 'guild-of-guardians_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for guild-of-guardians (guild-of-guardians_btc): ['date', 'open', 'high', 'low', 'close', 'guild-of-guardians_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for guild-of-guardians (BTC): ['date', 'open', 'high', 'low', 'close', 'guild-of-guardians_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  96%|█████████▌| 123/128 [04:43<00:08,  1.70s/it]

Initial columns after loading asset data for aerodrome-finance: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for aerodrome-finance: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for aerodrome-finance: ['date', 'open', 'high', 'low', 'close', 'aerodrome-finance_btc']
Columns after numeric conversion and dropna for aerodrome-finance (close): ['date', 'open', 'high', 'low', 'close', 'aerodrome-finance_btc']
Columns after calculating indicators for aerodrome-finance (USD): ['date', 'open', 'high', 'low', 'close', 'aerodrome-finance_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for aerodrome-finance (aerodrome-finance_btc): ['date', 'open', 'high', 'low', 'close', 'aerodrome-finance_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for aerodrome-finance (BTC): ['date', 'open', 'high', 'low', 'close', 'aerodrome-finance_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  97%|█████████▋| 124/128 [04:44<00:05,  1.42s/it]

Initial columns after loading asset data for sushi: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for sushi: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for sushi: ['date', 'open', 'high', 'low', 'close', 'sushi_btc']
Columns after numeric conversion and dropna for sushi (close): ['date', 'open', 'high', 'low', 'close', 'sushi_btc']
Columns after calculating indicators for sushi (USD): ['date', 'open', 'high', 'low', 'close', 'sushi_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for sushi (sushi_btc): ['date', 'open', 'high', 'low', 'close', 'sushi_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for sushi (BTC): ['date', 'open', 'high', 'low', 'close', 'sushi_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  98%|█████████▊| 125/128 [04:46<00:05,  1.68s/it]

Initial columns after loading asset data for spell-token: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for spell-token: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for spell-token: ['date', 'open', 'high', 'low', 'close', 'spell-token_btc']
Columns after numeric conversion and dropna for spell-token (close): ['date', 'open', 'high', 'low', 'close', 'spell-token_btc']
Columns after calculating indicators for spell-token (USD): ['date', 'open', 'high', 'low', 'close', 'spell-token_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for spell-token (spell-token_btc): ['date', 'open', 'high', 'low', 'close', 'spell-token_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for spell-token (BTC): ['date', 'open', 'high', 'low', 'close', 'spell-token_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  98%|█████████▊| 126/128 [04:48<00:03,  1.76s/it]

Initial columns after loading asset data for uniswap: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for uniswap: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for uniswap: ['date', 'open', 'high', 'low', 'close', 'uniswap_btc']
Columns after numeric conversion and dropna for uniswap (close): ['date', 'open', 'high', 'low', 'close', 'uniswap_btc']
Columns after calculating indicators for uniswap (USD): ['date', 'open', 'high', 'low', 'close', 'uniswap_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for uniswap (uniswap_btc): ['date', 'open', 'high', 'low', 'close', 'uniswap_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for uniswap (BTC): ['date', 'open', 'high', 'low', 'close', 'uniswap_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets:  99%|█████████▉| 127/128 [04:51<00:01,  1.92s/it]

Initial columns after loading asset data for serum: ['date', 'open', 'high', 'low', 'close']
Bitcoin data columns: ['date', 'btc_close']
Columns after merge for serum: ['date', 'open', 'high', 'low', 'close', 'btc_close']
Columns after dropping 'btc_close' for serum: ['date', 'open', 'high', 'low', 'close', 'serum_btc']
Columns after numeric conversion and dropna for serum (close): ['date', 'open', 'high', 'low', 'close', 'serum_btc']
Columns after calculating indicators for serum (USD): ['date', 'open', 'high', 'low', 'close', 'serum_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365']
Columns after numeric conversion and dropna for serum (serum_btc): ['date', 'open', 'high', 'low', 'close', 'serum_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)']
Columns after calculating indicators for serum (BTC): ['date', 'open', 'high', 'low', 'close', 'serum_btc', 'SMA_USD_3', 'SMA_USD_5', 'SMA_USD_7', 'SMA_USD_14', 'SMA_USD_21', 'SMA_USD_30', 'SMA_USD_45', 'SMA_USD_63', 'SMA_USD_84', 'SMA_USD_100', 'SMA_USD_120', 'SMA_USD_150', 'SMA_USD_200', 'SMA_USD_252', 'SMA_USD_365', 'RoC_USD_3', 'RoC_USD_5', 'RoC_USD_7', 'RoC_USD_14', 'RoC_USD_21', 'RoC_USD_30', 'RoC_USD_45', 'RoC_USD_63', 'RoC_USD_84', 'RoC_USD_100', 'RoC_USD_120', 'RoC_USD_150', 'RoC_USD_200', 'RoC_USD_252', 'RoC_USD_365', 'Short Term (USD)', 'Medium Term (USD)', 'Long Term (USD)', 'Overall (USD)', 'SMA_BTC_3', 'SMA_BTC_5', 'SMA_BTC_7', 'SMA_BTC_14', 'SMA_BTC_21', 'SMA_BTC_30', 'SMA_BTC_45', 'SMA_BTC_63', 'SMA_BTC_84', 'SMA_BTC_100', 'SMA_BTC_120', 'SMA_BTC_150', 'SMA_BTC_200', 'SMA_BTC_252', 'SMA_BTC_365', 'RoC_BTC_3', 'RoC_BTC_5', 'RoC_BTC_7', 'RoC_BTC_14', 'RoC_BTC_21', 'RoC_BTC_30', 'RoC_BTC_45', 'RoC_BTC_63', 'RoC_BTC_84', 'RoC_BTC_100', 'RoC_BTC_120', 'RoC_BTC_150', 'RoC_BTC_200', 'RoC_BTC_252', 'RoC_BTC_365']

Analyzing assets: 100%|██████████| 128/128 [04:53<00:00,  2.29s/it]

Most Recent Trend Analysis Summary for Multiple Assets (as of March 11, 2025):
+----------+------------------------+-------------------------+-----------------------+---------------------+------------------------+-------------------------+-----------------------+---------------------+-------------+
|  Ticker  | Short Term Trend (USD) | Medium Term Trend (USD) | Long Term Trend (USD) | Overall Trend (USD) | Short Term Trend (BTC) | Medium Term Trend (BTC) | Long Term Trend (BTC) | Overall Trend (BTC) | Latest Date |
+----------+------------------------+-------------------------+-----------------------+---------------------+------------------------+-------------------------+-----------------------+---------------------+-------------+
|   BTC    |      Strong Bear       |       Strong Bear       |       Weak Bull       |      Weak Bear      |                        |                         |                       |                     | 2025-03-10  |
|   ILV    |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     | 2025-03-10  |
|   IMX    |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     | 2025-03-10  |
|   ACA    |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     | 2025-03-10  |
| VIRTUAL  |      Strong Bear       |       Strong Bear       |       Weak Bull       |      Weak Bear      |      Strong Bear       |       Strong Bear       |       Weak Bull       |      Weak Bear      | 2025-03-10  |
|  AIXBT   |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     | 2025-03-10  |
|   BCH    |      Strong Bull       |        Weak Bull        |       Weak Bear       |      Weak Bull      |      Strong Bull       |       Strong Bull       |      Strong Bear      |      Weak Bull      | 2025-03-10  |
|  SEILOR  |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |        Weak Bull        |      Strong Bear      |      Weak Bear      | 2025-03-10  |
|   MKR    |      Strong Bear       |        Weak Bull        |      Strong Bear      |      Weak Bear      |      Strong Bear       |       Strong Bull       |      Strong Bear      |      Weak Bear      | 2025-03-10  |
|   CRV    |      Strong Bear       |       Strong Bear       |       Weak Bull       |      Weak Bear      |      Strong Bear       |       Strong Bear       |        Neutral        |     Strong Bear     | 2025-03-10  |
|   MUBI   |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     | 2025-03-10  |
|  PRIME   |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     | 2025-03-10  |
|   ARB    |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     | 2025-03-10  |
|   AURY   |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bull       |        Weak Bull        |      Strong Bear      |      Weak Bull      | 2025-03-10  |
| FARTCOIN |      Strong Bear       |       Strong Bear       |       Weak Bear       |     Strong Bear     |      Strong Bear       |       Strong Bear       |       Weak Bull       |      Weak Bear      | 2025-03-10  |
|   RON    |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     | 2025-03-10  |
|  ALPHA   |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     | 2025-03-10  |
|   FXS    |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |       Weak Bull        |       Strong Bear       |      Strong Bear      |      Weak Bear      | 2025-03-10  |
|   POLY   |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |       Weak Bull        |       Strong Bear       |      Strong Bear      |      Weak Bear      | 2025-03-10  |
|   BAND   |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     | 2025-03-10  |
|   PAXG   |      Strong Bull       |       Strong Bull       |      Strong Bull      |     Strong Bull     |      Strong Bull       |       Strong Bull       |       Weak Bull       |     Strong Bull     | 2025-03-10  |
|   CNC    |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     | 2025-03-10  |
|  RENDER  |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     | 2025-03-10  |
|  PENDLE  |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     | 2025-03-10  |
|   JUP    |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     | 2025-03-10  |
|   MANA   |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |       Weak Bull        |       Strong Bear       |      Strong Bear      |      Weak Bear      | 2025-03-10  |
| ETHDYDX  |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     | 2025-03-10  |
|  TRIBE   |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     | 2025-03-10  |
|    ML    |      Strong Bull       |       Strong Bear       |      Strong Bear      |      Weak Bear      |      Strong Bull       |       Strong Bear       |      Strong Bear      |      Weak Bear      | 2025-03-10  |
|   SWM    |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     | 2025-03-10  |
|   FTM    |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bull       |      Strong Bear      |      Weak Bear      | 2025-03-10  |
|   PEPE   |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     | 2025-03-10  |
|  PRISMA  |       Weak Bull        |       Strong Bear       |       Weak Bear       |      Weak Bear      |      Strong Bull       |       Strong Bull       |       Weak Bear       |      Weak Bull      | 2025-03-10  |
|   DODO   |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     | 2025-03-10  |
|   TIA    |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |       Weak Bull        |        Weak Bull        |      Strong Bear      |      Weak Bull      | 2025-03-10  |
|   RGT    |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     | 2025-03-10  |
|   VELA   |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bull       |       Strong Bear       |      Strong Bear      |      Weak Bear      | 2025-03-10  |
|   PERP   |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     | 2025-03-10  |
|   SNX    |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |       Weak Bull        |        Weak Bull        |      Strong Bear      |      Weak Bull      | 2025-03-10  |
|    S     |      Strong Bear       |       Strong Bear       |        Neutral        |     Strong Bear     |      Strong Bear       |       Strong Bull       |        Neutral        |      Weak Bear      | 2025-03-10  |
|   RBW    |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     | 2025-03-10  |
|   ETH    |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |       Weak Bull        |       Strong Bear       |      Strong Bear      |      Weak Bear      | 2025-03-10  |
|  BOTTO   |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     | 2025-03-10  |
|   ATOM   |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     | 2025-03-10  |
|   TON    |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     | 2025-03-10  |
|   ETC    |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |        Weak Bull        |      Strong Bear      |      Weak Bear      | 2025-03-10  |
|   LINK   |      Strong Bear       |       Strong Bear       |        Neutral        |     Strong Bear     |      Strong Bear       |       Strong Bear       |       Weak Bear       |     Strong Bear     | 2025-03-10  |
|   DOT    |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |        Weak Bull        |      Strong Bear      |      Weak Bear      | 2025-03-10  |
|   ICP    |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     | 2025-03-10  |
|   TAO    |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     | 2025-03-10  |
|   GMX    |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     | 2025-03-10  |
|   NEON   |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     | 2025-03-10  |
|   GNS    |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |       Weak Bull        |       Strong Bull       |      Strong Bear      |      Weak Bull      | 2025-03-10  |
|   CRO    |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bull       |        Weak Bull        |      Strong Bear      |      Weak Bull      | 2025-03-10  |
|   XTZ    |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     | 2025-03-10  |
|   GALA   |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     | 2025-03-10  |
|   YGG    |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     | 2025-03-10  |
|  ALICE   |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     | 2025-03-10  |
|   NEAR   |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     | 2025-03-10  |
|   LDO    |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     | 2025-03-10  |
|   YFI    |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |       Weak Bull        |        Weak Bull        |      Strong Bear      |      Weak Bull      | 2025-03-10  |
|   USDT   |      Strong Bear       |       Strong Bear       |       Weak Bull       |      Weak Bear      |      Strong Bull       |       Strong Bull       |        Neutral        |      Weak Bull      | 2025-03-10  |
|   USDC   |      Strong Bear       |       Strong Bear       |       Weak Bear       |     Strong Bear     |      Strong Bull       |       Strong Bull       |        Neutral        |      Weak Bull      | 2025-03-10  |
|   FLOW   |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     | 2025-03-10  |
|   BAL    |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     | 2025-03-10  |
|   STX    |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     | 2025-03-10  |
|   EOS    |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     | 2025-03-10  |
|   AKT    |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     | 2025-03-10  |
|   ADA    |      Strong Bear       |       Strong Bear       |       Weak Bull       |      Weak Bear      |      Strong Bear       |        Weak Bull        |       Weak Bull       |      Weak Bull      | 2025-03-10  |
|   SOL    |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     | 2025-03-10  |
|   NTX    |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |        Weak Bull        |      Strong Bear      |      Weak Bear      | 2025-03-10  |
|   RAY    |      Strong Bear       |       Strong Bear       |       Weak Bear       |     Strong Bear     |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     | 2025-03-10  |
|  SMART   |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |       Weak Bull        |        Weak Bull        |      Strong Bear      |      Weak Bull      | 2025-03-10  |
|   SUI    |      Strong Bear       |       Strong Bear       |       Weak Bull       |      Weak Bear      |      Strong Bear       |       Strong Bear       |        Neutral        |     Strong Bear     | 2025-03-10  |
|   TUSD   |       Weak Bull        |       Strong Bear       |      Strong Bear      |      Weak Bear      |      Strong Bull       |       Strong Bull       |        Neutral        |      Weak Bull      | 2025-03-10  |
|   CAKE   |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     | 2025-03-10  |
|   RUNE   |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bull       |        Weak Bull        |      Strong Bear      |      Weak Bull      | 2025-03-10  |
|   DASH   |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |        Weak Bull        |      Strong Bear      |      Weak Bear      | 2025-03-10  |
|   LTC    |      Strong Bear       |       Strong Bear       |       Weak Bull       |      Weak Bear      |       Weak Bull        |       Strong Bull       |       Weak Bull       |     Strong Bull     | 2025-03-10  |
|   XRP    |      Strong Bear       |       Strong Bear       |      Strong Bull      |      Weak Bear      |      Strong Bear       |        Weak Bull        |      Strong Bull      |      Weak Bull      | 2025-03-10  |
|   GENE   |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bear       |       Weak Bear       |     Strong Bear     | 2025-03-10  |
|   AVAX   |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     | 2025-03-10  |
|   SAND   |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     | 2025-03-10  |
|   NMR    |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     | 2025-03-10  |
|   LSK    |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     | 2025-03-10  |
|   LUNA   |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     | 2025-03-10  |
|   SHDW   |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     |      Strong Bear       |       Strong Bear       |      Strong Bear      |     Strong Bear     | 2025-03-10  |

In [362]:
alt_trend = analyzer.asset_data.get('aave').get('classified_data')[['date', 'close' ,'open','Overall (BTC)', 'Overall (USD)', 'Short Term (BTC)', 'Short Term (USD)', 'Medium Term (BTC)', 'Medium Term (USD)', 'Long Term (BTC)', 'Long Term (USD)']]
alt_trend = alt_trend.rename(columns={'date': 'Date'})
alt_trend

,Date,close,open,Overall (BTC),Overall (USD),Short Term (BTC),Short Term (USD),Medium Term (BTC),Medium Term (USD),Long Term (BTC),Long Term (USD)
0,2020-10-04,56.16,54.12,Strong Bear,Strong Bear,Neutral,Neutral,Neutral,Neutral,Neutral,Neutral
1,2020-10-05,52.83,52.31,Strong Bear,Strong Bear,Neutral,Neutral,Neutral,Neutral,Neutral,Neutral
2,2020-10-06,52.73,52.90,Strong Bear,Strong Bear,Neutral,Neutral,Neutral,Neutral,Neutral,Neutral
3,2020-10-07,41.51,52.80,Strong Bear,Strong Bear,Strong Bear,Strong Bear,Neutral,Neutral,Neutral,Neutral
4,2020-10-08,40.23,41.42,Strong Bear,Strong Bear,Strong Bear,Strong Bear,Neutral,Neutral,Neutral,Neutral
...,...,...,...,...,...,...,...,...,...,...,...
1614,2025-03-06,221.90,205.94,Weak Bear,Weak Bear,Strong Bear,Strong Bear,Strong Bear,Strong Bear,Weak Bull,Weak Bull
1615,2025-03-07,208.97,221.45,Weak Bear,Weak Bear,Weak Bear,Weak Bear,Strong Bear,Strong Bear,Weak Bull,Weak Bull
1616,2025-03-08,197.11,208.59,Weak Bear,Weak Bear,Strong Bear,Strong Bear,Strong Bear,Strong Bear,Weak Bull,Weak Bull
1617,2025-03-09,195.70,196.92,Weak Bear,Weak Bear,Strong Bear,Strong Bear,Strong Bear,Strong Bear,Weak Bull,Weak Bull
1618,2025-03-10,178.25,195.65,Weak Bear,Weak Bear,Strong Bear,Strong Bear,Strong Bear,Strong Bear,Weak Bull,Weak Bull

In [363]:
btc_strategy = pd.read_csv('hmm_btc_strategy_10_03_2025.csv')[['Date','state', 'Close']]
btc_strategy.rename(columns={'state': 'btc_state', 'Close': 'btc_close'}, inplace=True)
btc_strategy

           Date btc_state  btc_close
0    2024-04-05      Flat    68542.0
1    2024-04-06      Long    67979.0
2    2024-04-07      Long    69001.0
3    2024-04-08      Long    69402.0
4    2024-04-09      Long    71624.0
..          ...       ...        ...
335  2025-03-06      Flat    90604.0
336  2025-03-07      Flat    90001.0
337  2025-03-08      Flat    86773.0
338  2025-03-09      Flat    86143.0
339  2025-03-10      Flat    80751.0

[340 rows x 3 columns]

In [364]:
# Convert the Date column in btc_strategy to datetime
btc_strategy['Date'] = pd.to_datetime(btc_strategy['Date'])

# Now merge the dataframes with matching date types
data = pd.merge(alt_trend, btc_strategy, on='Date', how='inner')
data #[data['Date'] > '2024-11-01'].head(60)

,Date,close,open,Overall (BTC),Overall (USD),Short Term (BTC),Short Term (USD),Medium Term (BTC),Medium Term (USD),Long Term (BTC),Long Term (USD),btc_state,btc_close
0,2024-04-05,116.37,114.61,Strong Bear,Weak Bear,Strong Bear,Strong Bear,Strong Bear,Weak Bear,Weak Bear,Strong Bull,Flat,68542.0
1,2024-04-06,114.05,116.35,Strong Bear,Weak Bear,Strong Bear,Strong Bear,Strong Bear,Strong Bear,Weak Bear,Strong Bull,Long,67979.0
2,2024-04-07,118.59,113.80,Strong Bear,Weak Bear,Strong Bear,Strong Bear,Strong Bear,Weak Bear,Weak Bear,Weak Bull,Long,69001.0
3,2024-04-08,122.84,118.54,Strong Bear,Weak Bear,Strong Bear,Strong Bear,Strong Bear,Strong Bear,Weak Bear,Strong Bull,Long,69402.0
4,2024-04-09,128.96,122.71,Strong Bear,Weak Bear,Weak Bear,Weak Bear,Strong Bear,Weak Bear,Weak Bear,Strong Bull,Long,71624.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
335,2025-03-06,221.90,205.94,Weak Bear,Weak Bear,Strong Bear,Strong Bear,Strong Bear,Strong Bear,Weak Bull,Weak Bull,Flat,90604.0
336,2025-03-07,208.97,221.45,Weak Bear,Weak Bear,Weak Bear,Weak Bear,Strong Bear,Strong Bear,Weak Bull,Weak Bull,Flat,90001.0
337,2025-03-08,197.11,208.59,Weak Bear,Weak Bear,Strong Bear,Strong Bear,Strong Bear,Strong Bear,Weak Bull,Weak Bull,Flat,86773.0
338,2025-03-09,195.70,196.92,Weak Bear,Weak Bear,Strong Bear,Strong Bear,Strong Bear,Strong Bear,Weak Bull,Weak Bull,Flat,86143.0
339,2025-03-10,178.25,195.65,Weak Bear,Weak Bear,Strong Bear,Strong Bear,Strong Bear,Strong Bear,Weak Bull,Weak Bull,Flat,80751.0

In [365]:
# Define the strategy combining alt trend signals and BTC HMM model
def combined_strategy_backtest(data, initial_investment=1000, risk_free_rate=0.0):
    """
    Hybrid trading strategy:
    - By default, follow the BTC HMM strategy (go long BTC when HMM says "Long")
    - When alt-BTC combined conditions are also met, split investment 50-50 between alt and BTC
    - Stay in cash when BTC HMM model doesn't signal "Long"
    
    Args:
        data: DataFrame with trend classifications, price data, and BTC state
        initial_investment: Initial portfolio value (default: $1000)
        risk_free_rate: Annual risk-free rate (default: 0.0)
    
    Returns:
        DataFrame with strategy signals and performance metrics
    """
    # Create a copy of the data to avoid modifying the original
    strategy_data = data.copy()
    
    # Create a BTC signal column (1 when HMM says Long, 0 otherwise)
    strategy_data['btc_signal'] = 0
    strategy_data.loc[strategy_data['btc_state'] == 'Long', 'btc_signal'] = 1
    
    # Generate signals based on our combined conditions for alt strategy
    strategy_conditions = (
        ((strategy_data['Short Term (USD)'].isin(['Weak Bull', 'Strong Bull'])) & 
        (strategy_data['Short Term (BTC)'].isin(['Weak Bull', 'Strong Bull'])) ) &
        (strategy_data['Long Term (USD)'].isin(['Weak Bull', 'Strong Bull'])) | 
        (strategy_data['Medium Term (USD)'].isin(['Weak Bull', 'Strong Bull'])) & 
        (strategy_data['btc_state'] == 'Long')
    )
    
    strategy_data['alt_signal'] = 0
    strategy_data.loc[strategy_conditions, 'alt_signal'] = 1
    
    # Calculate daily returns
    strategy_data['daily_return'] = strategy_data['close'].pct_change()
    strategy_data['btc_daily_return'] = strategy_data['btc_close'].pct_change()
    
    # Calculate strategy returns with a 1-day lag to avoid look-ahead bias
    # BTC strategy returns
    strategy_data['btc_strategy_return'] = strategy_data['btc_signal'].shift(1) * strategy_data['btc_daily_return']
    
    # Alt-only strategy returns
    strategy_data['alt_strategy_return'] = strategy_data['alt_signal'].shift(1) * strategy_data['daily_return']
    
    # Calculate hybrid strategy returns:
    # - When alt_signal is 1, allocate 50% to alt and 50% to BTC
    # - When alt_signal is 0 but btc_signal is 1, allocate 100% to BTC
    # - When both signals are 0, stay in cash (0% return)
    strategy_data['hybrid_return'] = 0.0
    
    # Case 1: When alt_signal is active, invest 50-50
    alt_signal_active = strategy_data['alt_signal'].shift(1) == 1
    strategy_data.loc[alt_signal_active, 'hybrid_return'] = (
        0.5 * strategy_data.loc[alt_signal_active, 'daily_return'] + 
        0.5 * strategy_data.loc[alt_signal_active, 'btc_daily_return']
    )
    
    # Case 2: When only BTC signal is active, invest 100% in BTC
    btc_only_active = (strategy_data['alt_signal'].shift(1) == 0) & (strategy_data['btc_signal'].shift(1) == 1)
    strategy_data.loc[btc_only_active, 'hybrid_return'] = strategy_data.loc[btc_only_active, 'btc_daily_return']
    
    # Calculate portfolio values
    strategy_data['buy_hold_value'] = initial_investment * (1 + strategy_data['daily_return']).cumprod()
    strategy_data['btc_value'] = initial_investment * (1 + strategy_data['btc_daily_return']).cumprod()
    strategy_data['btc_strategy_value'] = initial_investment * (1 + strategy_data['btc_strategy_return']).cumprod()
    strategy_data['alt_strategy_value'] = initial_investment * (1 + strategy_data['alt_strategy_return']).cumprod()
    strategy_data['hybrid_strategy_value'] = initial_investment * (1 + strategy_data['hybrid_return']).cumprod()
    
    # Correctly calculate drawdowns
    strategy_data['buy_hold_peak'] = strategy_data['buy_hold_value'].cummax()
    strategy_data['btc_peak'] = strategy_data['btc_value'].cummax()
    strategy_data['btc_strategy_peak'] = strategy_data['btc_strategy_value'].cummax()
    strategy_data['alt_strategy_peak'] = strategy_data['alt_strategy_value'].cummax()
    strategy_data['hybrid_strategy_peak'] = strategy_data['hybrid_strategy_value'].cummax()
    
    strategy_data['buy_hold_drawdown'] = (strategy_data['buy_hold_value'] - strategy_data['buy_hold_peak']) / strategy_data['buy_hold_peak']
    strategy_data['btc_drawdown'] = (strategy_data['btc_value'] - strategy_data['btc_peak']) / strategy_data['btc_peak']
    strategy_data['btc_strategy_drawdown'] = (strategy_data['btc_strategy_value'] - strategy_data['btc_strategy_peak']) / strategy_data['btc_strategy_peak']
    strategy_data['alt_strategy_drawdown'] = (strategy_data['alt_strategy_value'] - strategy_data['alt_strategy_peak']) / strategy_data['alt_strategy_peak']
    strategy_data['hybrid_strategy_drawdown'] = (strategy_data['hybrid_strategy_value'] - strategy_data['hybrid_strategy_peak']) / strategy_data['hybrid_strategy_peak']
    
    return strategy_data

# Run the backtest with initial investment of $1000
initial_investment = 1000
risk_free_rate = 0.0  # Assuming 0% risk-free rate for crypto
backtest_results = combined_strategy_backtest(data, initial_investment, risk_free_rate)

# Calculate Sharpe and Sortino ratios
def calculate_risk_metrics(returns, risk_free_rate=0.0):
    """Calculate Sharpe and Sortino ratios for a series of returns"""
    # Remove NaN values
    returns = returns.dropna()
    
    if len(returns) == 0 or returns.std() == 0:
        return 0, 0
    
    # Calculate excess returns (assuming daily risk-free rate)
    daily_rf_rate = (1 + risk_free_rate) ** (1/365) - 1
    excess_returns = returns - daily_rf_rate
    
    # Calculate Sharpe Ratio (annualized)
    sharpe_ratio = np.sqrt(365) * excess_returns.mean() / excess_returns.std()
    
    # Calculate Sortino Ratio (annualized)
    downside_returns = excess_returns[excess_returns < 0]
    sortino_ratio = np.sqrt(365) * excess_returns.mean() / downside_returns.std() if len(downside_returns) > 0 and downside_returns.std() > 0 else np.inf
    
    return sharpe_ratio, sortino_ratio

# Calculate risk metrics for all approaches
buy_hold_sharpe, buy_hold_sortino = calculate_risk_metrics(backtest_results['daily_return'].dropna(), risk_free_rate)
btc_sharpe, btc_sortino = calculate_risk_metrics(backtest_results['btc_daily_return'].dropna(), risk_free_rate)
btc_strategy_sharpe, btc_strategy_sortino = calculate_risk_metrics(backtest_results['btc_strategy_return'].dropna(), risk_free_rate)
alt_strategy_sharpe, alt_strategy_sortino = calculate_risk_metrics(backtest_results['alt_strategy_return'].dropna(), risk_free_rate)
hybrid_sharpe, hybrid_sortino = calculate_risk_metrics(backtest_results['hybrid_return'].dropna(), risk_free_rate)

# Visualize the strategy performance with portfolio values
import plotly.express as px

fig = px.line(backtest_results, x='Date', 
             y=['buy_hold_value', 'btc_value', 'btc_strategy_value', 'alt_strategy_value', 'hybrid_strategy_value'],
             title='Hybrid Strategy Backtest Performance',
             labels={'value': 'Portfolio Value ($)', 'variable': 'Strategy'},
             color_discrete_map={
                 'buy_hold_value': 'gray',
                 'btc_value': 'orange',
                 'btc_strategy_value': 'blue',
                 'alt_strategy_value': 'red',
                 'hybrid_strategy_value': 'green'
             })

fig.update_layout(
    xaxis_title='',
    yaxis_title='Portfolio Value ($)',
    template='plotly_white',
    height=600,
    width=1000,
    legend=dict(
        title=None,
        orientation='h',
        yanchor='bottom',
        y=1.02,
        xanchor='right',
        x=1
    )
)

# Update legend labels
fig.for_each_trace(lambda t: t.update(
    name={
        'buy_hold_value': 'Alt Buy & Hold',
        'btc_value': 'BTC Buy & Hold',
        'btc_strategy_value': 'BTC HMM Strategy',
        'alt_strategy_value': 'Alt-only Strategy',
        'hybrid_strategy_value': 'Hybrid Strategy (BTC/50-50)'
    }[t.name]
))

fig.show()

# Calculate percentage of time in market
total_days = len(backtest_results)
alt_invested_days = backtest_results['alt_signal'].sum()
btc_invested_days = backtest_results['btc_signal'].sum()
hybrid_both_days = ((backtest_results['alt_signal'] == 1) & (backtest_results['btc_signal'] == 1)).sum()
hybrid_btc_only_days = ((backtest_results['alt_signal'] == 0) & (backtest_results['btc_signal'] == 1)).sum()
hybrid_total_days = hybrid_both_days + hybrid_btc_only_days

alt_percent_invested = alt_invested_days / total_days * 100
btc_percent_invested = btc_invested_days / total_days * 100
hybrid_percent_invested = hybrid_total_days / total_days * 100
percent_5050_allocation = hybrid_both_days / hybrid_total_days * 100 if hybrid_total_days > 0 else 0

# Calculate total and annualized returns
days_in_market = (backtest_results['Date'].iloc[-1] - backtest_results['Date'].iloc[0]).days
annual_factor = 365 / days_in_market

final_buy_hold_value = backtest_results['buy_hold_value'].iloc[-1]
final_btc_value = backtest_results['btc_value'].iloc[-1]
final_btc_strategy_value = backtest_results['btc_strategy_value'].iloc[-1]
final_alt_strategy_value = backtest_results['alt_strategy_value'].iloc[-1]
final_hybrid_value = backtest_results['hybrid_strategy_value'].iloc[-1]

buy_hold_return = (final_buy_hold_value / initial_investment) - 1
btc_return = (final_btc_value / initial_investment) - 1
btc_strategy_return = (final_btc_strategy_value / initial_investment) - 1
alt_strategy_return = (final_alt_strategy_value / initial_investment) - 1
hybrid_return = (final_hybrid_value / initial_investment) - 1

annualized_buy_hold = (1 + buy_hold_return) ** annual_factor - 1
annualized_btc = (1 + btc_return) ** annual_factor - 1
annualized_btc_strategy = (1 + btc_strategy_return) ** annual_factor - 1
annualized_alt_strategy = (1 + alt_strategy_return) ** annual_factor - 1
annualized_hybrid = (1 + hybrid_return) ** annual_factor - 1

# Get max drawdowns
max_bh_drawdown = backtest_results['buy_hold_drawdown'].min()
max_btc_drawdown = backtest_results['btc_drawdown'].min()
max_btc_strategy_drawdown = backtest_results['btc_strategy_drawdown'].min()
max_alt_strategy_drawdown = backtest_results['alt_strategy_drawdown'].min()
max_hybrid_drawdown = backtest_results['hybrid_strategy_drawdown'].min()

# Calculate return/drawdown ratios
return_dd_bh = annualized_buy_hold / abs(max_bh_drawdown) if max_bh_drawdown != 0 else float('inf')
return_dd_btc = annualized_btc / abs(max_btc_drawdown) if max_btc_drawdown != 0 else float('inf')
return_dd_btc_strategy = annualized_btc_strategy / abs(max_btc_strategy_drawdown) if max_btc_strategy_drawdown != 0 else float('inf')
return_dd_alt_strategy = annualized_alt_strategy / abs(max_alt_strategy_drawdown) if max_alt_strategy_drawdown != 0 else float('inf')
return_dd_hybrid = annualized_hybrid / abs(max_hybrid_drawdown) if max_hybrid_drawdown != 0 else float('inf')

# Print performance summary
print(f"Hybrid Strategy Performance Summary:")
print(f"Period: {backtest_results['Date'].iloc[0].date()} to {backtest_results['Date'].iloc[-1].date()} ({days_in_market} days)")
print(f"Initial Investment: ${initial_investment:.2f}")
print(f"\nStrategy Allocation Details:")
print(f"BTC HMM Strategy - Time invested in market: {btc_percent_invested:.2f}%")
print(f"Alt-only Strategy - Time invested in market: {alt_percent_invested:.2f}%")
print(f"Hybrid Strategy - Time invested in market: {hybrid_percent_invested:.2f}%")
print(f"  - Of which, 50-50 allocation: {percent_5050_allocation:.2f}%")
print(f"  - Of which, 100% BTC allocation: {100-percent_5050_allocation:.2f}%")

print("\nTotal Returns:")
print(f"Alt Buy & Hold: ${final_buy_hold_value:.2f} (Total return: {buy_hold_return:.2%})")
print(f"BTC Buy & Hold: ${final_btc_value:.2f} (Total return: {btc_return:.2%})")
print(f"BTC HMM Strategy: ${final_btc_strategy_value:.2f} (Total return: {btc_strategy_return:.2%})")
print(f"Alt-only Strategy: ${final_alt_strategy_value:.2f} (Total return: {alt_strategy_return:.2%})")
print(f"Hybrid Strategy: ${final_hybrid_value:.2f} (Total return: {hybrid_return:.2%})")

print("\nAnnualized Returns:")
print(f"Alt Buy & Hold: {annualized_buy_hold:.2%}")
print(f"BTC Buy & Hold: {annualized_btc:.2%}")
print(f"BTC HMM Strategy: {annualized_btc_strategy:.2%}")
print(f"Alt-only Strategy: {annualized_alt_strategy:.2%}")
print(f"Hybrid Strategy: {annualized_hybrid:.2%}")

print("\nRisk Metrics:")
print(f"Max Drawdown - Alt Buy & Hold: {max_bh_drawdown:.2%}")
print(f"Max Drawdown - BTC Buy & Hold: {max_btc_drawdown:.2%}")
print(f"Max Drawdown - BTC HMM Strategy: {max_btc_strategy_drawdown:.2%}")
print(f"Max Drawdown - Alt-only Strategy: {max_alt_strategy_drawdown:.2%}")
print(f"Max Drawdown - Hybrid Strategy: {max_hybrid_drawdown:.2%}")

print("\nSharpe Ratio:")
print(f"Alt Buy & Hold: {buy_hold_sharpe:.2f}")
print(f"BTC Buy & Hold: {btc_sharpe:.2f}")
print(f"BTC HMM Strategy: {btc_strategy_sharpe:.2f}")
print(f"Alt-only Strategy: {alt_strategy_sharpe:.2f}")
print(f"Hybrid Strategy: {hybrid_sharpe:.2f}")

print("\nSortino Ratio:")
print(f"Alt Buy & Hold: {buy_hold_sortino:.2f}")
print(f"BTC Buy & Hold: {btc_sortino:.2f}")
print(f"BTC HMM Strategy: {btc_strategy_sortino:.2f}")
print(f"Alt-only Strategy: {alt_strategy_sortino:.2f}")
print(f"Hybrid Strategy: {hybrid_sortino:.2f}")

print("\nReturn/MaxDD Ratio:")
print(f"Alt Buy & Hold: {return_dd_bh:.2f}")
print(f"BTC Buy & Hold: {return_dd_btc:.2f}")
print(f"BTC HMM Strategy: {return_dd_btc_strategy:.2f}")
print(f"Alt-only Strategy: {return_dd_alt_strategy:.2f}")
print(f"Hybrid Strategy: {return_dd_hybrid:.2f}")

# Plot drawdowns to visualize risk reduction
fig_drawdown = px.line(backtest_results, x='Date', 
                      y=['buy_hold_drawdown', 'btc_drawdown', 'btc_strategy_drawdown', 'alt_strategy_drawdown', 'hybrid_strategy_drawdown'],
                      title='Drawdown Comparison',
                      labels={'value': 'Drawdown', 'variable': 'Strategy'},
                      color_discrete_map={
                          'buy_hold_drawdown': 'gray',
                          'btc_drawdown': 'orange',
                          'btc_strategy_drawdown': 'blue',
                          'alt_strategy_drawdown': 'red',
                          'hybrid_strategy_drawdown': 'green'
                      })

fig_drawdown.update_layout(
    xaxis_title='',
    yaxis_title='Drawdown',
    template='plotly_white',
    height=400,
    width=1000
)

# Update legend labels
fig_drawdown.for_each_trace(lambda t: t.update(
    name={
        'buy_hold_drawdown': 'Alt Buy & Hold',
        'btc_drawdown': 'BTC Buy & Hold',
        'btc_strategy_drawdown': 'BTC HMM Strategy',
        'alt_strategy_drawdown': 'Alt-only Strategy',
        'hybrid_strategy_drawdown': 'Hybrid Strategy (BTC/50-50)'
    }[t.name]
))

fig_drawdown.show()

Hybrid Strategy Performance Summary:
Period: 2024-04-05 to 2025-03-10 (339 days)
Initial Investment: $1000.00

Strategy Allocation Details:
BTC HMM Strategy - Time invested in market: 59.71%
Alt-only Strategy - Time invested in market: 31.18%
Hybrid Strategy - Time invested in market: 59.71%
  - Of which, 50-50 allocation: 44.33%
  - Of which, 100% BTC allocation: 55.67%

Total Returns:
Alt Buy & Hold: $1531.75 (Total return: 53.18%)
BTC Buy & Hold: $1178.12 (Total return: 17.81%)
BTC HMM Strategy: $1913.35 (Total return: 91.34%)
Alt-only Strategy: $1761.35 (Total return: 76.13%)
Hybrid Strategy: $2292.98 (Total return: 129.30%)

Annualized Returns:
Alt Buy & Hold: 58.27%
BTC Buy & Hold: 19.30%
BTC HMM Strategy: 101.10%
Alt-only Strategy: 83.95%
Hybrid Strategy: 144.37%

Risk Metrics:
Max Drawdown - Alt Buy & Hold: -53.52%
Max Drawdown - BTC Buy & Hold: -24.71%
Max Drawdown - BTC HMM Strategy: -12.52%
Max Drawdown - Alt-only Strategy: -31.95%
Max Drawdown - Hybrid Strategy: -15.64%

Sharpe Ratio:
Alt Buy & Hold: 0.95
BTC Buy & Hold: 0.60
BTC HMM Strategy: 2.08
Alt-only Strategy: 1.32
Hybrid Strategy: 2.31

Sortino Ratio:
Alt Buy & Hold: 1.65
BTC Buy & Hold: 0.98
BTC HMM Strategy: 3.05
Alt-only Strategy: 1.57
Hybrid Strategy: 3.61

Return/MaxDD Ratio:
Alt Buy & Hold: 1.09
BTC Buy & Hold: 0.78
BTC HMM Strategy: 8.07
Alt-only Strategy: 2.63
Hybrid Strategy: 9.23

In [51]:
analyzer = TrendAnalyzer(
    asset_ids=['bitcoin'],
    data_path='/Users/valter.rebelo/MissionControl/data/micro/candleData/',
    btc_data_path='/Users/valter.rebelo/MissionControl/data/micro/assetData/bitcoin.csv',
    use_btc_adjusted=False,
    verbose=False
)

In [ ]:
import plotly.express as px

# Define the trend order and color mapping
trend_order = ['Strong Bull', 'Weak Bull', 'Neutral', 'Weak Bear', 'Strong Bear']
color_map = {
    'Strong Bull': 'darkgreen',
    'Weak Bull': 'lightgreen',
    'Neutral': 'gray',
    'Weak Bear': 'orange',
    'Strong Bear': 'red'
}

# Create a scatter plot of Overall trend classification through time using plotly
fig = px.scatter(analyzer.classified_data, x='date', y='Overall', 
                 title='Overall Trend Classification Through Time',
                 color='Overall',
                 color_discrete_map=color_map,
                 category_orders={'Overall': trend_order})

fig.update_layout(
    xaxis_title='',
    yaxis_title='Trend Classification',
    template='plotly_white',
    height=600,
    width=1000,
    yaxis=dict(
        categoryorder='array',
        categoryarray=trend_order
    )
)

fig.update_traces(marker=dict(size=4))
fig.show()

In [ ]:
# Define a simple trading strategy based on trend classification
def trend_based_strategy(data):
    """
    Trading strategy that:
    - Goes long at market open if previous day's close was classified as 'weak bull' or 'strong bull'
    - Stays in cash otherwise
    
    Args:
        data: DataFrame with trend classifications and price data
    
    Returns:
        DataFrame with strategy signals and performance metrics
    """
    # Create a copy of the data to avoid modifying the original
    strategy_data = data.copy()
    
    # Create a signal column (1 for long, 0 for cash)
    strategy_data['signal'] = 0
    
    # Generate signals based on previous day's classification
    bullish_conditions = (strategy_data['Short Term'].shift(1).isin(['Weak Bull', 'Strong Bull']))

    #bearish_conditions = (strategy_data['Overall'].shift(1).isin(['Strong Bear']))
    strategy_data.loc[bullish_conditions, 'signal'] = 1

    #strategy_data.loc[bearish_conditions, 'signal'] = -1    
    # Calculate returns
    strategy_data['daily_return'] = strategy_data['close'].pct_change()
    # Calculate strategy returns (signal from previous day * today's return)
    strategy_data['strategy_return'] = strategy_data['signal'] * strategy_data['daily_return']
    
    # Calculate cumulative returns
    strategy_data['cumulative_return'] = (1 + strategy_data['daily_return']).cumprod() - 1
    strategy_data['strategy_cumulative_return'] = (1 + strategy_data['strategy_return']).cumprod() - 1
    
    return strategy_data

# Apply the strategy to our classified data
strategy_results = trend_based_strategy(analyzer.classified_data)

# Visualize the strategy performance
fig = px.line(strategy_results, x='date', y=['cumulative_return', 'strategy_cumulative_return'],
              title='Trend-Based Trading Strategy Performance',
              labels={'value': 'Cumulative Return', 'variable': 'Strategy'},
              color_discrete_map={
                  'cumulative_return': 'gray',
                  'strategy_cumulative_return': 'blue'
              })

fig.update_layout(
    xaxis_title='',
    yaxis_title='Cumulative Return',
    template='plotly_white',
    height=600,
    width=1000,
    legend=dict(
        title=None,
        orientation='h',
        yanchor='bottom',
        y=1.02,
        xanchor='right',
        x=1
    )
)

# Update legend labels
fig.for_each_trace(lambda t: t.update(name='Buy & Hold' if t.name == 'cumulative_return' else 'Trend Strategy'))

fig.show()

# Calculate performance metrics
total_days = len(strategy_results)
invested_days = strategy_results['signal'].sum()
percent_invested = invested_days / total_days * 100

# Calculate annualized returns
days_in_market = (strategy_results['date'].iloc[-1] - strategy_results['date'].iloc[0]).days
annual_factor = 365 / days_in_market
buy_hold_return = strategy_results['cumulative_return'].iloc[-1]
strategy_return = strategy_results['strategy_cumulative_return'].iloc[-1]
annualized_buy_hold = (1 + buy_hold_return) ** annual_factor - 1
annualized_strategy = (1 + strategy_return) ** annual_factor - 1

# Print performance summary
print(f"Strategy Performance Summary:")
print(f"Period: {strategy_results['date'].iloc[0].date()} to {strategy_results['date'].iloc[-1].date()} ({days_in_market} days)")
print(f"Time invested in market: {percent_invested:.2f}%")
print(f"Buy & Hold return: {buy_hold_return:.2%} (Annualized: {annualized_buy_hold:.2%})")
print(f"Strategy return: {strategy_return:.2%} (Annualized: {annualized_strategy:.2%})")
print(f"Outperformance: {strategy_return - buy_hold_return:.2%}")

In [31]:
df = pd.read_csv('/Users/valter.rebelo/MissionControl/data/micro/candleData/akash-network_candles.csv')

In [32]:
import ta 

df['sma_3'] = ta.trend.SMAIndicator(close=df['close'], window=3).sma_indicator()
df['sma_7'] = ta.trend.SMAIndicator(close=df['close'], window=7).sma_indicator()
df['sma_30'] = ta.trend.SMAIndicator(close=df['close'], window=30).sma_indicator()
df['sma_365'] = ta.trend.SMAIndicator(close=df['close'], window=365).sma_indicator()

# Price to MA ratios
df['price_sma3_ratio'] = df['close'] / df['sma_3']
df['price_sma7_ratio'] = df['close'] / df['sma_7']
df['price_sma30_ratio'] = df['close'] / df['sma_30']
df['price_sma365_ratio'] = df['close'] / df['sma_365']

df['sma_3_low'] = df['low'].rolling(window=3).min()
df['7day_low'] = df['low'].rolling(window=7).min()
df['14day_low'] = df['low'].rolling(window=14).min()
df['30day_low'] = df['low'].rolling(window=30).min()
    
df['sma_3_high'] = df['high'].rolling(window=3).max()
df['7day_high'] = df['high'].rolling(window=7).max()
df['14day_high'] = df['high'].rolling(window=14).max()
df['30day_high'] = df['high'].rolling(window=30).max()


df['support'] = (df['7day_low'] + df['14day_low'] + df['30day_low'] + df['sma_3_low']) / 4
df['resistance'] = (df['7day_high'] + df['14day_high'] + df['30day_high'] + df['sma_3_high']) / 4

df['support_relative'] = df['close'] / df['support']
df['resistance_relative'] = df['close'] / df['resistance']

In [ ]:
df[['resistance_relative','support_relative']].hist(bins=50)

In [ ]:
df[['price_sma30_ratio', 'price_sma365_ratio', 'price_sma3_ratio', 'price_sma7_ratio']].hist(bins=50)