In [1]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import plotly.graph_objects as go
from trend_analisys_rsi_markov import TrendAnalyzer
import warnings
from scripts.assetsRoster import carteira_AC, carteira_HB, others
warnings.filterwarnings('ignore')

In [2]:
asset_ids = [
    'bitcoin', 'ethereum', 'binancecoin', 'ripple', 'cardano',
    'solana', 'polkadot', 'avalanche-2', 'chainlink', 'uniswap',
    'heyanon'
]

In [3]:
data_path='/Users/valter.rebelo/MissionControl/data/micro/candleData/'
btc_data_path='/Users/valter.rebelo/MissionControl/data/micro/candleData/bitcoin_candles.csv'
ssr_data_path='/Users/valter.rebelo/MissionControl/data/onchainData/BTC_SSR.csv'

In [17]:
analyzer = TrendAnalyzer(
    asset_ids=set(carteira_HB+carteira_AC),
    data_path=data_path,
    btc_data_path=btc_data_path,
    ssr_data_path=ssr_data_path,
    use_btc_adjusted=True,
    verbose=True,
    lookback_days=180,
    trend_metrics_lookback=365,
    markov_model_name='20250325_144631'
)

2025-03-26 20:28:41,198 - INFO - Loaded Markov volatility model: 20250325_144631
2025-03-26 20:28:41,205 - INFO - Successfully loaded SSR data with 2353 rows.

Data loaded successfully: 4102 records
Training set: 3281 records
Test set: 821 records
Model metadata:
  Saved on: 2025-03-25
  Data range: 2014-01-01 to 2025-03-24
  Records: 4101 total, 3075 train, 1026 test
Model loaded from /Users/valter.rebelo/MissionControl/models/markov_volatility_model_20250325_144631.pkl

In [ ]:
btc_data = analyzer.asset_data.get('bitcoin').get('classified_data')
# Create a copy of the full date range
all_dates = btc_data[btc_data['date'] >= '2019-01-01'].copy()
# Create a mask for the condition
condition_mask = (#((all_dates['Short Term (BTC)'] == 'Strong Bull') | (all_dates['Short Term (BTC)'] == 'Weak Bull')) 
                 
#                 &

                 ((all_dates['Overall (USD)'] == 'Strong Bull') | (all_dates['Overall (USD)'] == 'Weak Bull'))
                 
                 &

                 ((all_dates['Short Term (USD)'] == 'Strong Bull')))

import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Create the plotly figure
fig = go.Figure()

# Add a base line trace with the complete price history (in red by default)
fig.add_trace(go.Scatter(
    x=all_dates['date'],
    y=all_dates['close'],
    mode='lines',
    name='Non-matching conditions',
    line=dict(color='red', width=2)
))

# Add green trace only for the matching conditions
# Create a copy with NaN values for non-matching points
matching_data = all_dates.copy()
matching_data.loc[~condition_mask, 'close'] = np.nan

fig.add_trace(go.Scatter(
    x=matching_data['date'],
    y=matching_data['close'],
    mode='lines',
    name='Matching conditions',
    line=dict(color='green', width=2),
    connectgaps=False
))

# Update layout
fig.update_layout(
    title='Classificação de Tendência: BTC',
    xaxis_title='Date',
    yaxis_title='Close Price (USD)',
    template='plotly_white',
    legend=dict(x=0.01, y=0.99),
    hovermode='x unified'
)

# Add grid
fig.update_xaxes(showgrid=True, gridwidth=1, gridcolor='lightgray')
fig.update_yaxes(showgrid=True, gridwidth=1, gridcolor='lightgray')

# Show the plot
fig.show()

# Make sure every date is classified in one of the two categories
total_points = len(all_dates)
matching_points = condition_mask.sum()
non_matching_points = (~condition_mask).sum()

# Verify that all points are classified
if matching_points + non_matching_points != total_points:
    print(f"Warning: {total_points - (matching_points + non_matching_points)} points were not classified")

In [ ]:
btc_data = analyzer.asset_data.get('ripple').get('classified_data')
# Create a copy of the full date range
all_dates = btc_data[btc_data['date'] >= '2019-01-01'].copy()
# Create a mask for the condition
condition_mask = (((all_dates['Short Term (BTC)'] == 'Strong Bull') | (all_dates['Short Term (BTC)'] == 'Weak Bull')) 
                 
#                 &

                # ((all_dates['Overall (BTC)'] == 'Strong Bull'))
                 
                 &

                 ((all_dates['Short Term (USD)'] == 'Strong Bull')))    

import numpy as np
import plotly.graph_objects as go

# Create two separate dataframes for plotting
matching_data = all_dates.copy()
non_matching_data = all_dates.copy()

# For matching conditions: keep only matching points, set others to NaN
matching_data.loc[~condition_mask, 'close'] = np.nan

# For non-matching conditions: keep only non-matching points, set others to NaN
non_matching_data.loc[condition_mask, 'close'] = np.nan

# Create plotly figure
fig = go.Figure()

# Add traces for matching and non-matching conditions
fig.add_trace(go.Scatter(
    x=matching_data['date'],
    y=matching_data['close'],
    mode='lines',
    name='Matching conditions',
    line=dict(color='green', width=2),
    connectgaps=False
))

fig.add_trace(go.Scatter(
    x=non_matching_data['date'],
    y=non_matching_data['close'],
    mode='lines',
    name='Non-matching conditions',
    line=dict(color='red', width=2),
    connectgaps=False
))

# Update layout
fig.update_layout(
    title='Classificação de Tendência: XRP',
    xaxis_title='Date',
    yaxis_title='Close Price (USD)',
    template='plotly_white',
    legend=dict(x=0.01, y=0.99),
    hovermode='x unified'
)

# Add grid
fig.update_xaxes(showgrid=True, gridwidth=1, gridcolor='lightgray')
fig.update_yaxes(showgrid=True, gridwidth=1, gridcolor='lightgray')

# Show the plot
fig.show()

# Make sure every date is classified in one of the two categories
total_points = len(all_dates)
matching_points = matching_data['close'].notna().sum()
non_matching_points = non_matching_data['close'].notna().sum()

# Verify that all points are classified
if matching_points + non_matching_points != total_points:
    print(f"Warning: {total_points - (matching_points + non_matching_points)} points were not classified")

In [18]:

# Analyze assets
analyzer.analyze_multiple_assets()

Analyzing assets (static):   0%|          | 0/48 [00:00<?, ?it/s]2025-03-26 20:28:43,528 - INFO - Successfully loaded data for multibit with 492 rows.
Analyzing assets (static):   2%|▏         | 1/48 [00:00<00:30,  1.54it/s]2025-03-26 20:28:44,166 - INFO - Successfully loaded data for uniswap with 1651 rows.
Analyzing assets (static):   4%|▍         | 2/48 [00:02<01:07,  1.46s/it]2025-03-26 20:28:46,191 - INFO - Successfully loaded data for gmx with 1290 rows.
Analyzing assets (static):   6%|▋         | 3/48 [00:04<01:19,  1.77s/it]2025-03-26 20:28:48,336 - INFO - Successfully loaded data for secret with 1637 rows.
Analyzing assets (static):   8%|▊         | 4/48 [00:06<01:22,  1.88s/it]2025-03-26 20:28:50,381 - INFO - Successfully loaded data for matic-network with 2161 rows.
Analyzing assets (static):  10%|█         | 5/48 [00:09<01:32,  2.15s/it]2025-03-26 20:28:53,018 - INFO - Successfully loaded data for thorchain with 2076 rows.
Analyzing assets (static):  12%|█▎        | 6/48 [00:12<01:35,  2.28s/it]2025-03-26 20:28:55,553 - INFO - Successfully loaded data for ethereum with 3519 rows.
Analyzing assets (static):  15%|█▍        | 7/48 [00:16<02:01,  2.95s/it]2025-03-26 20:28:59,897 - INFO - Successfully loaded data for the-sandbox with 1685 rows.
Analyzing assets (static):  17%|█▋        | 8/48 [00:18<01:50,  2.76s/it]2025-03-26 20:29:02,241 - INFO - Successfully loaded data for frax-share with 1556 rows.
Analyzing assets (static):  19%|█▉        | 9/48 [00:20<01:39,  2.55s/it]2025-03-26 20:29:04,338 - INFO - Successfully loaded data for solana with 1811 rows.
Analyzing assets (static):  21%|██        | 10/48 [00:23<01:35,  2.51s/it]2025-03-26 20:29:06,755 - INFO - Successfully loaded data for radiant-capital with 974 rows.
Analyzing assets (static):  23%|██▎       | 11/48 [00:24<01:19,  2.14s/it]2025-03-26 20:29:08,050 - INFO - Successfully loaded data for avalanche-2 with 1646 rows.
Analyzing assets (static):  25%|██▌       | 12/48 [00:26<01:17,  2.16s/it]2025-03-26 20:29:10,265 - INFO - Successfully loaded data for echelon-prime with 755 rows.
Analyzing assets (static):  27%|██▋       | 13/48 [00:27<01:03,  1.83s/it]2025-03-26 20:29:11,313 - INFO - Successfully loaded data for ondo-finance with 433 rows.
Analyzing assets (static):  29%|██▉       | 14/48 [00:28<00:49,  1.46s/it]2025-03-26 20:29:11,919 - INFO - Successfully loaded data for aerodrome-finance with 558 rows.
Analyzing assets (static):  31%|███▏      | 15/48 [00:29<00:41,  1.25s/it]2025-03-26 20:29:12,685 - INFO - Successfully loaded data for ethena with 358 rows.
Analyzing assets (static):  33%|███▎      | 16/48 [00:29<00:32,  1.02s/it]2025-03-26 20:29:13,184 - INFO - Successfully loaded data for ethervista with 206 rows.
Analyzing assets (static):  35%|███▌      | 17/48 [00:29<00:24,  1.24it/s]2025-03-26 20:29:13,484 - INFO - Successfully loaded data for chainlink with 2694 rows.
Analyzing assets (static):  38%|███▊      | 18/48 [00:33<00:48,  1.63s/it]2025-03-26 20:29:17,026 - INFO - Successfully loaded data for ether-fi with 373 rows.
Analyzing assets (static):  40%|███▉      | 19/48 [00:34<00:37,  1.29s/it]2025-03-26 20:29:17,528 - INFO - Successfully loaded data for havven with 2563 rows.
Analyzing assets (static):  42%|████▏     | 20/48 [00:37<00:53,  1.90s/it]2025-03-26 20:29:20,844 - INFO - Successfully loaded data for maker with 2653 rows.
Analyzing assets (static):  44%|████▍     | 21/48 [00:40<01:04,  2.39s/it]2025-03-26 20:29:24,393 - INFO - Successfully loaded data for yne with 93 rows.
Analyzing assets (static):  46%|████▌     | 22/48 [00:41<00:44,  1.73s/it]2025-03-26 20:29:24,571 - INFO - Successfully loaded data for virtual-protocol with 454 rows.
Analyzing assets (static):  48%|████▊     | 23/48 [00:42<00:38,  1.52s/it]2025-03-26 20:29:25,633 - INFO - Successfully loaded data for decentraland with 2706 rows.
Analyzing assets (static):  50%|█████     | 24/48 [00:45<00:52,  2.20s/it]2025-03-26 20:29:29,393 - INFO - Successfully loaded data for beam-2 with 517 rows.
Analyzing assets (static):  52%|█████▏    | 25/48 [00:46<00:40,  1.76s/it]2025-03-26 20:29:30,137 - INFO - Successfully loaded data for gala with 1652 rows.
Analyzing assets (static):  54%|█████▍    | 26/48 [00:48<00:42,  1.92s/it]2025-03-26 20:29:32,441 - INFO - Successfully loaded data for kujira with 1216 rows.
Analyzing assets (static):  56%|█████▋    | 27/48 [00:50<00:38,  1.82s/it]2025-03-26 20:29:34,029 - INFO - Successfully loaded data for helium with 1804 rows.
Analyzing assets (static):  58%|█████▊    | 28/48 [00:52<00:39,  1.97s/it]2025-03-26 20:29:36,329 - INFO - Successfully loaded data for render-token with 1745 rows.
Analyzing assets (static):  60%|██████    | 29/48 [00:55<00:38,  2.05s/it]2025-03-26 20:29:38,566 - INFO - Successfully loaded data for injective-protocol with 1617 rows.
Analyzing assets (static):  62%|██████▎   | 30/48 [00:57<00:37,  2.10s/it]2025-03-26 20:29:40,774 - INFO - Successfully loaded data for numeraire with 2813 rows.
Analyzing assets (static):  65%|██████▍   | 31/48 [01:00<00:42,  2.52s/it]2025-03-26 20:29:44,284 - INFO - Successfully loaded data for bitcoin with 4350 rows.
Analyzing assets (static):  67%|██████▋   | 32/48 [01:03<00:40,  2.56s/it]2025-03-26 20:29:46,924 - INFO - Successfully loaded data for cosmos with 2224 rows.
Analyzing assets (static):  69%|██████▉   | 33/48 [01:06<00:39,  2.65s/it]2025-03-26 20:29:49,787 - INFO - Successfully loaded data for curve-dao-token with 1685 rows.
Analyzing assets (static):  71%|███████   | 34/48 [01:08<00:34,  2.50s/it]2025-03-26 20:29:51,941 - INFO - Successfully loaded data for blockstack with 1980 rows.
Analyzing assets (static):  73%|███████▎  | 35/48 [01:10<00:32,  2.48s/it]2025-03-26 20:29:54,359 - INFO - Successfully loaded data for morpho with 126 rows.
Analyzing assets (static):  75%|███████▌  | 36/48 [01:11<00:21,  1.78s/it]2025-03-26 20:29:54,532 - INFO - Successfully loaded data for arbitrum with 734 rows.
Analyzing assets (static):  77%|███████▋  | 37/48 [01:11<00:16,  1.52s/it]2025-03-26 20:29:55,446 - INFO - Successfully loaded data for aave with 1635 rows.
Analyzing assets (static):  79%|███████▉  | 38/48 [01:13<00:16,  1.67s/it]2025-03-26 20:29:57,452 - INFO - Successfully loaded data for dydx with 1295 rows.
Analyzing assets (static):  81%|████████▏ | 39/48 [01:15<00:14,  1.65s/it]2025-03-26 20:29:59,045 - INFO - Successfully loaded data for pendle with 1428 rows.
Analyzing assets (static):  83%|████████▎ | 40/48 [01:17<00:13,  1.68s/it]2025-03-26 20:30:00,805 - INFO - Successfully loaded data for optimism with 1030 rows.
Analyzing assets (static):  85%|████████▌ | 41/48 [01:18<00:10,  1.56s/it]2025-03-26 20:30:02,072 - INFO - Successfully loaded data for near with 1624 rows.
Analyzing assets (static):  88%|████████▊ | 42/48 [01:20<00:10,  1.70s/it]2025-03-26 20:30:04,093 - INFO - Successfully loaded data for gains-network with 1240 rows.
Analyzing assets (static):  90%|████████▉ | 43/48 [01:22<00:08,  1.65s/it]2025-03-26 20:30:05,631 - INFO - Successfully loaded data for lido-dao with 1541 rows.
Analyzing assets (static):  92%|█████████▏| 44/48 [01:24<00:06,  1.73s/it]2025-03-26 20:30:07,540 - INFO - Successfully loaded data for akash-network with 1622 rows.
Analyzing assets (static):  94%|█████████▍| 45/48 [01:26<00:05,  1.82s/it]2025-03-26 20:30:09,562 - INFO - Successfully loaded data for flow with 1519 rows.
Analyzing assets (static):  96%|█████████▌| 46/48 [01:27<00:03,  1.83s/it]2025-03-26 20:30:11,422 - INFO - Successfully loaded data for immutable-x with 1237 rows.
Analyzing assets (static):  98%|█████████▊| 47/48 [01:29<00:01,  1.74s/it]2025-03-26 20:30:12,948 - INFO - Successfully loaded data for tether with 3682 rows.
Analyzing assets (static): 100%|██████████| 48/48 [01:34<00:00,  1.97s/it]
Computing lookback metrics: 100%|██████████| 48/48 [00:01<00:00, 26.04it/s]
2025-03-26 20:30:19,829 - INFO - Trend analysis completed for multiple assets.

,Ticker,Short Term Trend (USD),Medium Term Trend (USD),Long Term Trend (USD),Overall Trend (USD),Short Term Trend (BTC),Medium Term Trend (BTC),Long Term Trend (BTC),Overall Trend (BTC),Sharpe Ratio (USD),...,Current Trend Sortino (USD),Current Trend Mean Return (USD),Current Trend Median Return (USD),Current Trend Skew (USD),Current Trend Sharpe (BTC),Current Trend Sortino (BTC),Current Trend Mean Return (BTC),Current Trend Median Return (BTC),Current Trend Skew (BTC),Latest Date
0,MUBI,Strong Bull,Strong Bear,Strong Bear,Weak Bear,Weak Bull,Strong Bear,Strong Bear,Weak Bear,0.401802,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-25
1,UNI,Strong Bull,Strong Bear,Strong Bear,Weak Bear,Weak Bull,Strong Bear,Strong Bear,Weak Bear,0.697793,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-25
2,GMX,Strong Bear,Strong Bear,Strong Bear,Strong Bear,Strong Bear,Strong Bear,Strong Bear,Strong Bear,0.589390,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-25
3,SCRT,Strong Bull,Strong Bear,Weak Bear,Weak Bear,Strong Bull,Strong Bear,Strong Bear,Weak Bear,0.509310,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-25
4,MATIC,Strong Bull,Strong Bear,Strong Bear,Weak Bear,Strong Bull,Strong Bear,Strong Bear,Weak Bear,1.115569,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-25
5,RUNE,Strong Bull,Weak Bull,Strong Bear,Weak Bull,Strong Bear,Weak Bull,Strong Bear,Weak Bear,1.206054,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-25
6,ETH,Strong Bull,Strong Bear,Strong Bear,Weak Bear,Strong Bull,Strong Bear,Strong Bear,Weak Bear,1.178232,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-25
7,SAND,Strong Bull,Strong Bear,Weak Bear,Weak Bear,Strong Bull,Strong Bear,Strong Bear,Weak Bear,0.894484,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-25
8,FXS,Strong Bull,Strong Bull,Weak Bear,Weak Bull,Strong Bull,Strong Bull,Strong Bear,Weak Bull,0.573020,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-25
9,SOL,Strong Bull,Strong Bear,Strong Bear,Weak Bear,Strong Bull,Strong Bear,Strong Bear,Weak Bear,1.422233,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-25
10,RDNT,Strong Bull,Strong Bear,Strong Bear,Weak Bear,Strong Bear,Strong Bear,Strong Bear,Strong Bear,0.476295,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-25
11,AVAX,Strong Bull,Strong Bear,Strong Bear,Weak Bear,Strong Bull,Strong Bull,Strong Bear,Weak Bull,0.859828,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-25
12,PRIME,Weak Bull,Strong Bear,Strong Bear,Weak Bear,Weak Bull,Strong Bear,Strong Bear,Weak Bear,0.693306,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-25
13,ONDO,Strong Bull,Strong Bear,Weak Bear,Weak Bear,Strong Bull,Strong Bear,Strong Bear,Weak Bear,1.563810,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-25
14,AERO,Strong Bull,Strong Bear,Strong Bear,Weak Bear,Weak Bull,Strong Bear,Strong Bear,Weak Bear,1.544202,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-25
15,ENA,Strong Bull,Strong Bear,Weak Bear,Weak Bear,Strong Bull,Weak Bull,Strong Bear,Weak Bull,0.322345,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-25
16,VISTA,Strong Bull,Strong Bear,Strong Bear,Weak Bear,Strong Bull,Strong Bear,Strong Bear,Weak Bear,0.838850,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-25
17,LINK,Strong Bull,Strong Bear,Weak Bear,Weak Bear,Strong Bull,Strong Bear,Strong Bear,Weak Bear,1.068001,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-25
18,ETHFI,Strong Bull,Strong Bear,Strong Bear,Weak Bear,Weak Bull,Strong Bear,Strong Bear,Weak Bear,-0.359165,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-25
19,SNX,Strong Bull,Strong Bear,Strong Bear,Weak Bear,Strong Bull,Weak Bull,Strong Bear,Weak Bull,0.755276,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-25
20,MKR,Strong Bull,Strong Bear,Strong Bear,Weak Bear,Strong Bear,Weak Bull,Strong Bear,Weak Bear,0.584206,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-25
21,YNE,Strong Bull,Strong Bear,Strong Bear,Weak Bear,Strong Bull,Strong Bear,Strong Bear,Weak Bear,1.999455,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-25
22,VIRTUAL,Strong Bull,Strong Bear,Weak Bull,Weak Bull,Strong Bull,Strong Bear,Weak Bull,Weak Bull,2.453993,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-25
23,MANA,Strong Bull,Strong Bear,Strong Bear,Weak Bear,Strong Bull,Strong Bear,Strong Bear,Weak Bear,0.930698,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-25
24,BEAM,Strong Bull,Strong Bear,Strong Bear,Weak Bear,Strong Bull,Strong Bull,Strong Bear,Weak Bull,0.984350,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-25
25,GALA,Strong Bull,Strong Bear,Strong Bear,Weak Bear,Strong Bull,Strong Bear,Strong Bear,Weak Bear,1.074870,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-25
26,KUJI,Strong Bull,Strong Bear,Strong Bear,Weak Bear,Strong Bear,Strong Bear,Strong Bear,Strong Bear,0.604434,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-25
27,HNT,Strong Bull,Strong Bear,Strong Bear,Weak Bear,Strong Bull,Weak Bull,Strong Bear,Weak Bull,1.136553,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-25
28,RENDER,Strong Bull,Strong Bear,Strong Bear,Weak Bear,Strong Bull,Strong Bull,Strong Bear,Weak Bull,1.329224,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-25
29,INJ,Strong Bull,Strong Bear,Strong Bear,Weak Bear,Strong Bull,Strong Bear,Strong Bear,Weak Bear,1.099039,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-25
30,NMR,Strong Bear,Strong Bear,Strong Bear,Strong Bear,Strong Bear,Strong Bear,Strong Bear,Strong Bear,0.598267,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-25
31,BTC,Strong Bull,Strong Bear,Weak Bull,Weak Bull,None,None,None,None,1.109823,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-25
32,ATOM,Strong Bull,Weak Bull,Weak Bear,Weak Bull,Strong Bear,Strong Bull,Strong Bear,Weak Bear,0.675776,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-25
33,CRV,Strong Bull,Strong Bear,Weak Bear,Weak Bear,Strong Bull,Strong Bull,Weak Bull,Strong Bull,0.264482,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-25
34,STX,Strong Bull,Strong Bear,Strong Bear,Weak Bear,Strong Bull,Strong Bear,Strong Bear,Weak Bear,0.750256,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-25
35,MORPHO,Strong Bull,Strong Bear,Weak Bear,Weak Bear,Strong Bull,Strong Bear,Weak Bear,Weak Bear,1.182567,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-25
36,ARB,Strong Bull,Strong Bear,Strong Bear,Weak Bear,Strong Bull,Strong Bear,Strong Bear,Weak Bear,-0.223237,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-25
37,AAVE,Strong Bull,Strong Bear,Weak Bull,Weak Bull,Weak Bull,Strong Bear,Weak Bull,Weak Bull,0.805200,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-25
38,ETHDYDX,Strong Bull,Strong Bear,Strong Bear,Weak Bear,Strong Bull,Strong Bull,Strong Bear,Weak Bull,-0.064579,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-25
39,PENDLE,Strong Bull,Strong Bear,Strong Bear,Weak Bear,Strong Bull,Weak Bull,Strong Bear,Weak Bull,0.843296,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-25
40,OP,Strong Bull,Strong Bear,Strong Bear,Weak Bear,Weak Bull,Strong Bear,Strong Bear,Weak Bear,0.492935,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-25
41,NEAR,Strong Bull,Strong Bear,Strong Bear,Weak Bear,Strong Bull,Weak Bull,Strong Bear,Weak Bull,0.790769,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-25
42,GNS,Strong Bull,Strong Bull,Strong Bear,Weak Bull,Strong Bear,Strong Bull,Strong Bear,Weak Bear,0.652479,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-25
43,LDO,Strong Bull,Strong Bear,Weak Bear,Weak Bear,Strong Bull,Strong Bear,Strong Bear,Weak Bear,0.740576,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-25
44,AKT,Strong Bull,Strong Bear,Strong Bear,Weak Bear,Strong Bull,Strong Bear,Strong Bear,Weak Bear,0.832552,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-25
45,FLOW,Strong Bull,Strong Bear,Strong Bear,Weak Bear,Strong Bear,Strong Bear,Strong Bear,Strong Bear,-0.060594,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-25
46,IMX,Strong Bull,Weak Bull,Strong Bear,Weak Bull,Strong Bull,Weak Bull,Strong Bear,Weak Bull,0.117593,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-25
47,USDT,Strong Bull,Weak Bull,Weak Bull,Strong Bull,Strong Bear,Strong Bull,Weak Bear,Weak Bear,0.314900,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-25

In [131]:
start_date='2024-01-1'
end_date='2025-03-25'

# Create a BTC-only trend-following portfolio
analyzer.create_portfolio(
    portfolio_name='btc_trend_following',
    #usd_conditions={'Short Term (USD)': ['Weak Bull','Strong Bull']},
    btc_only=True,
    btc_trend_gating=None,
    rsi_conditions_usd=True,
    use_ssr_signal=True,
    use_volatility_filter=True,
    volatility_weight=1
)

# Then create an altcoin portfolio that follows the Bitcoin portfolio
analyzer.create_portfolio(
    portfolio_name='big_wins_i',
    btc_conditions={'Short Term (BTC)': ['Strong Bull'], 'Overall (BTC)': ['Strong Bull']},
    usd_conditions={'Short Term (USD)': ['Strong Bull']},
    rsi_conditions_usd=True,
    rsi_conditions_btc=True,
    use_btc_rsi_signal=False,
    btc_only=False,  # This is an altcoin portfolio
    follow_portfolio='btc_trend_following',
    use_ssr_signal=False,
    use_ssr_gate=False,
    use_volatility_filter=True,
    volatility_weight=1
)

# Then create an altcoin portfolio that follows the Bitcoin portfolio
# Then create an altcoin portfolio that follows the Bitcoin portfolio
analyzer.create_portfolio(
    portfolio_name='big_wins_ii',
    btc_conditions={'Short Term (BTC)': ['Weak Bull','Strong Bull'], 'Overall (BTC)': ['Strong Bull']},
    usd_conditions={'Short Term (USD)': ['Strong Bull']},
    rsi_conditions_usd=True,
    rsi_conditions_btc=True,
    use_btc_rsi_signal=True,
    btc_only=False,  # This is an altcoin portfolio
    follow_portfolio='btc_trend_following',
    use_ssr_signal=False,
    use_ssr_gate=False,
    use_volatility_filter=True,
    volatility_weight=1
)


# Then create an altcoin portfolio that follows the Bitcoin portfolio
analyzer.create_portfolio(
    portfolio_name='fat_tails',
    btc_conditions={'Short Term (BTC)': ['Strong Bull'], 'Overall (BTC)': ['Weak Bull','Strong Bull']},
    usd_conditions={'Short Term (USD)': ['Strong Bull']},
    rsi_conditions_usd=True,
    rsi_conditions_btc=True,
    use_btc_rsi_signal=True,
    btc_only=False,  # This is an altcoin portfolio
    follow_portfolio='btc_trend_following',
    use_ssr_signal=False,
    use_ssr_gate=False,
    use_volatility_filter=True,
    volatility_weight=1
)

# Then create an altcoin portfolio that follows the Bitcoin portfolio
analyzer.create_portfolio(
    portfolio_name='experiment_i',
    btc_conditions={'Short Term (BTC)': ['Weak Bull','Strong Bull'], 'Overall (BTC)': ['Strong Bull']},
    usd_conditions={'Short Term (USD)': ['Strong Bear','Strong Bull']},
    rsi_conditions_usd=True,
    rsi_conditions_btc=True,
    use_btc_rsi_signal=False,
    btc_only=False,  # This is an altcoin portfolio
    follow_portfolio='btc_trend_following',
    use_ssr_signal=False,
    use_ssr_gate=False,
    use_volatility_filter=True,
    volatility_weight=1
)


########################################################

# Backtest the altcoin portfolio
results_alt = analyzer.backtest_portfolio(
    portfolio_name='big_wins_i',
    start_date=start_date,
    end_date=end_date,
    initial_capital=10000,
    alt_cost=0.005,
    signal_threshold=75
)

results_alt = analyzer.backtest_portfolio(
    portfolio_name='experiment_i',
    start_date=start_date,
    end_date=end_date,
    initial_capital=10000,
    alt_cost=0.005,
    signal_threshold=75
)

# Backtest the BTC trend-following portfolio
results_btc = analyzer.backtest_portfolio(
    portfolio_name='btc_trend_following',
    start_date=start_date,
    end_date=end_date,
    initial_capital=10000,
    alt_cost=0.001,
    signal_threshold=50
)

2025-03-27 11:42:55,619 - WARNING - Portfolio btc_trend_following already exists. Overwriting.
2025-03-27 11:42:55,626 - INFO - Portfolio 'btc_trend_following' created with criteria: BTC gating=None, USD conditions=None, BTC conditions=None, RSI USD=True, RSI BTC=False, volatility filter=True, volatility weight=1, SSR signal=True, SSR gate=False, BTC RSI gate=False, BTC RSI signal=False, Follow portfolio=None, BTC only=True
2025-03-27 11:42:55,628 - WARNING - Portfolio big_wins_i already exists. Overwriting.
2025-03-27 11:42:55,632 - INFO - Portfolio 'big_wins_i' created with criteria: BTC gating=None, USD conditions={'Short Term (USD)': ['Strong Bull']}, BTC conditions={'Short Term (BTC)': ['Strong Bull'], 'Overall (BTC)': ['Strong Bull']}, RSI USD=True, RSI BTC=True, volatility filter=True, volatility weight=1, SSR signal=False, SSR gate=False, BTC RSI gate=False, BTC RSI signal=False, Follow portfolio=btc_trend_following, BTC only=False
2025-03-27 11:42:55,633 - WARNING - Portfolio big_wins_ii already exists. Overwriting.
2025-03-27 11:42:55,634 - INFO - Portfolio 'big_wins_ii' created with criteria: BTC gating=None, USD conditions={'Short Term (USD)': ['Strong Bull']}, BTC conditions={'Short Term (BTC)': ['Weak Bull', 'Strong Bull'], 'Overall (BTC)': ['Strong Bull']}, RSI USD=True, RSI BTC=True, volatility filter=True, volatility weight=1, SSR signal=False, SSR gate=False, BTC RSI gate=False, BTC RSI signal=True, Follow portfolio=btc_trend_following, BTC only=False
2025-03-27 11:42:55,635 - WARNING - Portfolio fat_tails already exists. Overwriting.
2025-03-27 11:42:55,636 - INFO - Portfolio 'fat_tails' created with criteria: BTC gating=None, USD conditions={'Short Term (USD)': ['Strong Bull']}, BTC conditions={'Short Term (BTC)': ['Strong Bull'], 'Overall (BTC)': ['Weak Bull', 'Strong Bull']}, RSI USD=True, RSI BTC=True, volatility filter=True, volatility weight=1, SSR signal=False, SSR gate=False, BTC RSI gate=False, BTC RSI signal=True, Follow portfolio=btc_trend_following, BTC only=False
2025-03-27 11:42:55,638 - WARNING - Portfolio experiment_i already exists. Overwriting.
2025-03-27 11:42:55,642 - INFO - Portfolio 'experiment_i' created with criteria: BTC gating=None, USD conditions={'Short Term (USD)': ['Strong Bear', 'Strong Bull']}, BTC conditions={'Short Term (BTC)': ['Weak Bull', 'Strong Bull'], 'Overall (BTC)': ['Strong Bull']}, RSI USD=True, RSI BTC=True, volatility filter=True, volatility weight=1, SSR signal=False, SSR gate=False, BTC RSI gate=False, BTC RSI signal=False, Follow portfolio=btc_trend_following, BTC only=False
2025-03-27 11:42:55,646 - INFO - Running backtest for followed portfolio 'btc_trend_following'
2025-03-27 11:42:55,679 - INFO - Entering BTC position on 2024-01-08 00:00:00: Cost = 10.00
2025-03-27 11:42:55,681 - INFO - Exiting BTC position on 2024-01-09 00:00:00: Cost = 9.99
2025-03-27 11:42:55,683 - INFO - Entering BTC position on 2024-01-10 00:00:00: Cost = 9.98
2025-03-27 11:42:55,688 - INFO - Exiting BTC position on 2024-01-13 00:00:00: Cost = 9.29
2025-03-27 11:42:55,692 - INFO - Entering BTC position on 2024-01-14 00:00:00: Cost = 9.28
2025-03-27 11:42:55,698 - INFO - Exiting BTC position on 2024-01-16 00:00:00: Cost = 9.24
2025-03-27 11:42:55,720 - INFO - Entering BTC position on 2024-01-30 00:00:00: Cost = 9.23
2025-03-27 11:42:55,766 - INFO - Exiting BTC position on 2024-02-27 00:00:00: Cost = 11.63
2025-03-27 11:42:55,770 - INFO - Entering BTC position on 2024-02-28 00:00:00: Cost = 11.62
2025-03-27 11:42:55,792 - INFO - Exiting BTC position on 2024-03-16 00:00:00: Cost = 14.18
2025-03-27 11:42:55,809 - INFO - Entering BTC position on 2024-03-27 00:00:00: Cost = 14.17
2025-03-27 11:42:55,821 - INFO - Exiting BTC position on 2024-04-03 00:00:00: Cost = 13.24
2025-03-27 11:42:55,852 - INFO - Entering BTC position on 2024-05-06 00:00:00: Cost = 13.23
2025-03-27 11:42:55,887 - INFO - Exiting BTC position on 2024-06-15 00:00:00: Cost = 13.65
2025-03-27 11:42:55,903 - INFO - Entering BTC position on 2024-07-03 00:00:00: Cost = 13.64
2025-03-27 11:42:55,905 - INFO - Exiting BTC position on 2024-07-04 00:00:00: Cost = 13.26
2025-03-27 11:42:55,914 - INFO - Entering BTC position on 2024-07-13 00:00:00: Cost = 13.25
2025-03-27 11:42:55,917 - INFO - Exiting BTC position on 2024-07-15 00:00:00: Cost = 13.96
2025-03-27 11:42:55,920 - INFO - Entering BTC position on 2024-07-17 00:00:00: Cost = 13.94
2025-03-27 11:42:55,937 - INFO - Exiting BTC position on 2024-08-03 00:00:00: Cost = 13.15
2025-03-27 11:42:55,959 - INFO - Entering BTC position on 2024-08-24 00:00:00: Cost = 13.14
2025-03-27 11:42:55,963 - INFO - Exiting BTC position on 2024-08-27 00:00:00: Cost = 12.20
2025-03-27 11:42:55,964 - INFO - Entering BTC position on 2024-08-28 00:00:00: Cost = 12.19
2025-03-27 11:42:55,966 - INFO - Exiting BTC position on 2024-08-29 00:00:00: Cost = 12.27
2025-03-27 11:42:55,972 - INFO - Entering BTC position on 2024-09-03 00:00:00: Cost = 12.26
2025-03-27 11:42:55,975 - INFO - Exiting BTC position on 2024-09-05 00:00:00: Cost = 11.98
2025-03-27 11:42:55,984 - INFO - Entering BTC position on 2024-09-12 00:00:00: Cost = 11.97
2025-03-27 11:42:56,038 - INFO - Exiting BTC position on 2024-11-06 00:00:00: Cost = 15.59
2025-03-27 11:42:56,040 - INFO - Entering BTC position on 2024-11-07 00:00:00: Cost = 15.57
2025-03-27 11:42:56,059 - INFO - Exiting BTC position on 2024-11-25 00:00:00: Cost = 19.08
2025-03-27 11:42:56,061 - INFO - Entering BTC position on 2024-11-26 00:00:00: Cost = 19.06
2025-03-27 11:42:56,081 - INFO - Exiting BTC position on 2024-12-18 00:00:00: Cost = 20.83
2025-03-27 11:42:56,088 - INFO - Entering BTC position on 2024-12-24 00:00:00: Cost = 20.81
2025-03-27 11:42:56,092 - INFO - Exiting BTC position on 2024-12-27 00:00:00: Cost = 19.91
2025-03-27 11:42:56,101 - INFO - Entering BTC position on 2025-01-05 00:00:00: Cost = 19.89
2025-03-27 11:42:56,105 - INFO - Exiting BTC position on 2025-01-08 00:00:00: Cost = 19.23
2025-03-27 11:42:56,107 - INFO - Entering BTC position on 2025-01-09 00:00:00: Cost = 19.21
2025-03-27 11:42:56,109 - INFO - Exiting BTC position on 2025-01-10 00:00:00: Cost = 19.72
2025-03-27 11:42:56,115 - INFO - Entering BTC position on 2025-01-16 00:00:00: Cost = 19.70
2025-03-27 11:42:56,132 - INFO - Exiting BTC position on 2025-02-02 00:00:00: Cost = 19.23
2025-03-27 11:42:56,135 - INFO - Entering BTC position on 2025-02-05 00:00:00: Cost = 19.21
2025-03-27 11:42:56,142 - INFO - Exiting BTC position on 2025-02-11 00:00:00: Cost = 19.09
2025-03-27 11:42:56,173 - INFO - Entering BTC position on 2025-03-15 00:00:00: Cost = 19.07
2025-03-27 11:42:56,208 - INFO - Using signals from BTC-only portfolio 'btc_trend_following'
2025-03-27 11:43:11,919 - INFO - Using signals from BTC-only portfolio 'btc_trend_following'
2025-03-27 11:43:26,593 - INFO - Entering BTC position on 2024-01-08 00:00:00: Cost = 10.00
2025-03-27 11:43:26,596 - INFO - Exiting BTC position on 2024-01-09 00:00:00: Cost = 9.99
2025-03-27 11:43:26,598 - INFO - Entering BTC position on 2024-01-10 00:00:00: Cost = 9.98
2025-03-27 11:43:26,601 - INFO - Exiting BTC position on 2024-01-13 00:00:00: Cost = 9.29
2025-03-27 11:43:26,603 - INFO - Entering BTC position on 2024-01-14 00:00:00: Cost = 9.28
2025-03-27 11:43:26,605 - INFO - Exiting BTC position on 2024-01-16 00:00:00: Cost = 9.24
2025-03-27 11:43:26,620 - INFO - Entering BTC position on 2024-01-30 00:00:00: Cost = 9.23
2025-03-27 11:43:26,661 - INFO - Exiting BTC position on 2024-02-27 00:00:00: Cost = 11.63
2025-03-27 11:43:26,669 - INFO - Entering BTC position on 2024-02-28 00:00:00: Cost = 11.62
2025-03-27 11:43:26,698 - INFO - Exiting BTC position on 2024-03-16 00:00:00: Cost = 14.18
2025-03-27 11:43:26,710 - INFO - Entering BTC position on 2024-03-27 00:00:00: Cost = 14.17
2025-03-27 11:43:26,720 - INFO - Exiting BTC position on 2024-04-03 00:00:00: Cost = 13.24
2025-03-27 11:43:26,767 - INFO - Entering BTC position on 2024-05-06 00:00:00: Cost = 13.23
2025-03-27 11:43:26,817 - INFO - Exiting BTC position on 2024-06-15 00:00:00: Cost = 13.65
2025-03-27 11:43:26,847 - INFO - Entering BTC position on 2024-07-03 00:00:00: Cost = 13.64
2025-03-27 11:43:26,850 - INFO - Exiting BTC position on 2024-07-04 00:00:00: Cost = 13.26
2025-03-27 11:43:26,865 - INFO - Entering BTC position on 2024-07-13 00:00:00: Cost = 13.25
2025-03-27 11:43:26,870 - INFO - Exiting BTC position on 2024-07-15 00:00:00: Cost = 13.96
2025-03-27 11:43:26,874 - INFO - Entering BTC position on 2024-07-17 00:00:00: Cost = 13.94
2025-03-27 11:43:26,894 - INFO - Exiting BTC position on 2024-08-03 00:00:00: Cost = 13.15
2025-03-27 11:43:26,915 - INFO - Entering BTC position on 2024-08-24 00:00:00: Cost = 13.14
2025-03-27 11:43:26,918 - INFO - Exiting BTC position on 2024-08-27 00:00:00: Cost = 12.20
2025-03-27 11:43:26,920 - INFO - Entering BTC position on 2024-08-28 00:00:00: Cost = 12.19
2025-03-27 11:43:26,921 - INFO - Exiting BTC position on 2024-08-29 00:00:00: Cost = 12.27
2025-03-27 11:43:26,926 - INFO - Entering BTC position on 2024-09-03 00:00:00: Cost = 12.26
2025-03-27 11:43:26,929 - INFO - Exiting BTC position on 2024-09-05 00:00:00: Cost = 11.98
2025-03-27 11:43:26,936 - INFO - Entering BTC position on 2024-09-12 00:00:00: Cost = 11.97
2025-03-27 11:43:26,986 - INFO - Exiting BTC position on 2024-11-06 00:00:00: Cost = 15.59
2025-03-27 11:43:26,988 - INFO - Entering BTC position on 2024-11-07 00:00:00: Cost = 15.57
2025-03-27 11:43:27,005 - INFO - Exiting BTC position on 2024-11-25 00:00:00: Cost = 19.08
2025-03-27 11:43:27,006 - INFO - Entering BTC position on 2024-11-26 00:00:00: Cost = 19.06
2025-03-27 11:43:27,026 - INFO - Exiting BTC position on 2024-12-18 00:00:00: Cost = 20.83
2025-03-27 11:43:27,033 - INFO - Entering BTC position on 2024-12-24 00:00:00: Cost = 20.81
2025-03-27 11:43:27,036 - INFO - Exiting BTC position on 2024-12-27 00:00:00: Cost = 19.91
2025-03-27 11:43:27,046 - INFO - Entering BTC position on 2025-01-05 00:00:00: Cost = 19.89
2025-03-27 11:43:27,049 - INFO - Exiting BTC position on 2025-01-08 00:00:00: Cost = 19.23
2025-03-27 11:43:27,051 - INFO - Entering BTC position on 2025-01-09 00:00:00: Cost = 19.21
2025-03-27 11:43:27,053 - INFO - Exiting BTC position on 2025-01-10 00:00:00: Cost = 19.72
2025-03-27 11:43:27,064 - INFO - Entering BTC position on 2025-01-16 00:00:00: Cost = 19.70
2025-03-27 11:43:27,082 - INFO - Exiting BTC position on 2025-02-02 00:00:00: Cost = 19.23
2025-03-27 11:43:27,085 - INFO - Entering BTC position on 2025-02-05 00:00:00: Cost = 19.21
2025-03-27 11:43:27,092 - INFO - Exiting BTC position on 2025-02-11 00:00:00: Cost = 19.09
2025-03-27 11:43:27,121 - INFO - Entering BTC position on 2025-03-15 00:00:00: Cost = 19.07

In [132]:


# Plot performance for a specific date range
fig = analyzer.plot_individual_asset_performance(
    portfolio_name='experiment_i',
    btc_trend_portfolio_name='btc_trend_following',
    start_date=start_date,
    end_date=end_date,
    initial_capital=10000,
    show_plot=False,
   # asset_filter=['SOL']
)

2025-03-27 11:43:27,146 - INFO - Recalculating backtest for portfolio 'experiment_i' from 2024-01-1 to 2025-03-25.
2025-03-27 11:43:27,167 - INFO - Using signals from BTC-only portfolio 'btc_trend_following'

2025-03-27 11:43:42,338 - INFO - Recalculating backtest for portfolio 'btc_trend_following' from 2024-01-1 to 2025-03-25.
2025-03-27 11:43:42,350 - INFO - Entering BTC position on 2024-01-08 00:00:00: Cost = 10.00
2025-03-27 11:43:42,353 - INFO - Exiting BTC position on 2024-01-09 00:00:00: Cost = 9.99
2025-03-27 11:43:42,354 - INFO - Entering BTC position on 2024-01-10 00:00:00: Cost = 9.98
2025-03-27 11:43:42,359 - INFO - Exiting BTC position on 2024-01-13 00:00:00: Cost = 9.29
2025-03-27 11:43:42,361 - INFO - Entering BTC position on 2024-01-14 00:00:00: Cost = 9.28
2025-03-27 11:43:42,364 - INFO - Exiting BTC position on 2024-01-16 00:00:00: Cost = 9.24
2025-03-27 11:43:42,379 - INFO - Entering BTC position on 2024-01-30 00:00:00: Cost = 9.23
2025-03-27 11:43:42,405 - INFO - Exiting BTC position on 2024-02-27 00:00:00: Cost = 11.63
2025-03-27 11:43:42,407 - INFO - Entering BTC position on 2024-02-28 00:00:00: Cost = 11.62
2025-03-27 11:43:42,424 - INFO - Exiting BTC position on 2024-03-16 00:00:00: Cost = 14.18
2025-03-27 11:43:42,435 - INFO - Entering BTC position on 2024-03-27 00:00:00: Cost = 14.17
2025-03-27 11:43:42,444 - INFO - Exiting BTC position on 2024-04-03 00:00:00: Cost = 13.24
2025-03-27 11:43:42,474 - INFO - Entering BTC position on 2024-05-06 00:00:00: Cost = 13.23
2025-03-27 11:43:42,510 - INFO - Exiting BTC position on 2024-06-15 00:00:00: Cost = 13.65
2025-03-27 11:43:42,529 - INFO - Entering BTC position on 2024-07-03 00:00:00: Cost = 13.64
2025-03-27 11:43:42,531 - INFO - Exiting BTC position on 2024-07-04 00:00:00: Cost = 13.26
2025-03-27 11:43:42,540 - INFO - Entering BTC position on 2024-07-13 00:00:00: Cost = 13.25
2025-03-27 11:43:42,544 - INFO - Exiting BTC position on 2024-07-15 00:00:00: Cost = 13.96
2025-03-27 11:43:42,546 - INFO - Entering BTC position on 2024-07-17 00:00:00: Cost = 13.94
2025-03-27 11:43:42,562 - INFO - Exiting BTC position on 2024-08-03 00:00:00: Cost = 13.15
2025-03-27 11:43:42,583 - INFO - Entering BTC position on 2024-08-24 00:00:00: Cost = 13.14
2025-03-27 11:43:42,587 - INFO - Exiting BTC position on 2024-08-27 00:00:00: Cost = 12.20
2025-03-27 11:43:42,588 - INFO - Entering BTC position on 2024-08-28 00:00:00: Cost = 12.19
2025-03-27 11:43:42,590 - INFO - Exiting BTC position on 2024-08-29 00:00:00: Cost = 12.27
2025-03-27 11:43:42,595 - INFO - Entering BTC position on 2024-09-03 00:00:00: Cost = 12.26
2025-03-27 11:43:42,598 - INFO - Exiting BTC position on 2024-09-05 00:00:00: Cost = 11.98
2025-03-27 11:43:42,604 - INFO - Entering BTC position on 2024-09-12 00:00:00: Cost = 11.97
2025-03-27 11:43:42,654 - INFO - Exiting BTC position on 2024-11-06 00:00:00: Cost = 15.59
2025-03-27 11:43:42,656 - INFO - Entering BTC position on 2024-11-07 00:00:00: Cost = 15.57
2025-03-27 11:43:42,673 - INFO - Exiting BTC position on 2024-11-25 00:00:00: Cost = 19.08
2025-03-27 11:43:42,674 - INFO - Entering BTC position on 2024-11-26 00:00:00: Cost = 19.06
2025-03-27 11:43:42,697 - INFO - Exiting BTC position on 2024-12-18 00:00:00: Cost = 20.83
2025-03-27 11:43:42,703 - INFO - Entering BTC position on 2024-12-24 00:00:00: Cost = 20.81
2025-03-27 11:43:42,707 - INFO - Exiting BTC position on 2024-12-27 00:00:00: Cost = 19.91
2025-03-27 11:43:42,716 - INFO - Entering BTC position on 2025-01-05 00:00:00: Cost = 19.89
2025-03-27 11:43:42,720 - INFO - Exiting BTC position on 2025-01-08 00:00:00: Cost = 19.23
2025-03-27 11:43:42,722 - INFO - Entering BTC position on 2025-01-09 00:00:00: Cost = 19.21
2025-03-27 11:43:42,723 - INFO - Exiting BTC position on 2025-01-10 00:00:00: Cost = 19.72
2025-03-27 11:43:42,729 - INFO - Entering BTC position on 2025-01-16 00:00:00: Cost = 19.70
2025-03-27 11:43:42,747 - INFO - Exiting BTC position on 2025-02-02 00:00:00: Cost = 19.23
2025-03-27 11:43:42,750 - INFO - Entering BTC position on 2025-02-05 00:00:00: Cost = 19.21
2025-03-27 11:43:42,756 - INFO - Exiting BTC position on 2025-02-11 00:00:00: Cost = 19.09
2025-03-27 11:43:42,786 - INFO - Entering BTC position on 2025-03-15 00:00:00: Cost = 19.07

Performance Metrics:
BTC Buy & Hold: Return = 98.15%, Max Drawdown = -26.23%
BTC Trend (btc_trend_following): Return = 99.00%, Max Drawdown = -19.76%

Individual Asset Performance:

|         | Total Return   | Max Drawdown   |   Sharpe Ratio |   Sortino Ratio |   Number of Trades | Win Rate   | Avg Win   | Avg Loss   |   Avg Holding Days | Total Costs   | First Trade         | Last Trade          |   Trading Days |
|:--------|:---------------|:---------------|---------------:|----------------:|-------------------:|:-----------|:----------|:-----------|-------------------:|:--------------|:--------------------|:--------------------|---------------:|
| VIRTUAL | 10685.58%      | -63.81%        |           7.77 |           22.45 |                 19 | 42.11%     | 197.48%   | -11.66%    |                7.5 | $99,765.09    | 2024-02-06 00:00:00 | 2025-01-19 00:00:00 |            142 |
| AERO    | 368.20%        | -63.30%        |           4.45 |           13.21 |                 16 | 37.50%     | 57.97%    | -6.81%     |                8.2 | $4,353.51     | 2024-01-07 00:00:00 | 2024-12-25 00:00:00 |            132 |
| VISTA   | 108.33%        | -76.02%        |           4.14 |           17.18 |                 10 | 40.00%     | 95.59%    | -15.64%    |                3.9 | $3,220.43     | 2024-10-26 00:00:00 | 2025-01-18 00:00:00 |             39 |
| CRV     | 105.92%        | -40.33%        |           6.91 |           18.44 |                 13 | 38.46%     | 27.27%    | -4.69%     |                4.6 | $1,537.60     | 2024-02-24 00:00:00 | 2025-03-25 00:00:00 |             61 |
| ENA     | 69.25%         | -47.04%        |           4.56 |           14.64 |                 14 | 57.14%     | 17.04%    | -10.18%    |                4.6 | $2,248.86     | 2024-09-25 00:00:00 | 2025-01-06 00:00:00 |             65 |
| UNI     | 64.60%         | -39.75%        |           4.1  |           10.98 |                 22 | 40.91%     | 13.13%    | -4.09%     |                4.2 | $2,676.98     | 2024-01-13 00:00:00 | 2024-12-24 00:00:00 |             92 |
| YNE     | 37.04%         | -58.86%        |           6.4  |           48.94 |                  2 | 100.00%    | 17.06%    | 0.00%      |                3   | $236.56       | 2025-01-20 00:00:00 | 2025-01-28 00:00:00 |              6 |
| ONDO    | 30.63%         | -43.53%        |           5.39 |           13.73 |                 21 | 28.57%     | 25.18%    | -6.11%     |                5.4 | $2,414.00     | 2024-02-15 00:00:00 | 2025-02-09 00:00:00 |            113 |
| LINK    | 26.90%         | -34.35%        |           3.58 |            8.58 |                 16 | 31.25%     | 21.14%    | -5.71%     |                6.5 | $1,951.73     | 2024-01-30 00:00:00 | 2025-01-31 00:00:00 |            104 |
| BEAM    | 25.55%         | -50.62%        |           6.35 |           15.83 |                 23 | 30.43%     | 21.26%    | -6.74%     |                4.3 | $2,750.98     | 2024-01-29 00:00:00 | 2025-03-25 00:00:00 |            100 |
| GALA    | 13.02%         | -54.46%        |           4.83 |           10.52 |                 17 | 35.29%     | 20.30%    | -8.13%     |                4.3 | $2,146.94     | 2024-02-23 00:00:00 | 2025-01-17 00:00:00 |             73 |
| IMX     | 10.44%         | -43.24%        |           2.79 |            4.88 |                 16 | 37.50%     | 15.60%    | -6.77%     |                5.9 | $2,013.38     | 2024-02-02 00:00:00 | 2024-12-16 00:00:00 |             95 |
| SNX     | 10.43%         | -24.91%        |           6.75 |           14.81 |                 10 | 50.00%     | 7.33%     | -4.68%     |                3.3 | $941.87       | 2024-02-25 00:00:00 | 2025-03-25 00:00:00 |             34 |
| ARB     | 9.05%          | -29.01%        |           3.48 |            5.39 |                  9 | 44.44%     | 10.59%    | -5.92%     |                4.2 | $982.81       | 2024-01-01 00:00:00 | 2024-12-11 00:00:00 |             39 |
| MKR     | 7.21%          | -28.52%        |           3.99 |            6.16 |                 16 | 43.75%     | 7.06%     | -4.32%     |                3.5 | $1,538.77     | 2024-01-10 00:00:00 | 2025-03-18 00:00:00 |             56 |
| ATOM    | 4.38%          | -23.90%        |           1.55 |            2.22 |                  9 | 22.22%     | 13.50%    | -3.32%     |                3.7 | $827.03       | 2024-05-11 00:00:00 | 2025-03-25 00:00:00 |             34 |
| SAND    | 3.71%          | -34.67%        |           2.36 |            4.81 |                 13 | 38.46%     | 18.89%    | -8.47%     |                3.5 | $1,406.73     | 2024-03-02 00:00:00 | 2025-01-18 00:00:00 |             46 |
| NEAR    | 1.18%          | -59.49%        |           2.61 |            6.33 |                 25 | 32.00%     | 13.82%    | -5.10%     |                3.8 | $2,801.79     | 2024-01-07 00:00:00 | 2024-12-14 00:00:00 |             95 |
| HNT     | -0.01%         | -33.08%        |           3.31 |            7.37 |                 21 | 57.14%     | 5.31%     | -6.36%     |                3.6 | $2,183.79     | 2024-01-07 00:00:00 | 2024-12-23 00:00:00 |             76 |
| MUBI    | -0.40%         | -50.79%        |           1.48 |            4.38 |                 14 | 35.71%     | 8.87%     | -4.53%     |                2.6 | $1,384.11     | 2024-01-07 00:00:00 | 2024-12-16 00:00:00 |             37 |
| RENDER  | -1.90%         | -65.37%        |           3.69 |            7.6  |                 27 | 40.74%     | 8.78%     | -5.74%     |                3.8 | $3,417.29     | 2024-01-01 00:00:00 | 2025-03-25 00:00:00 |            104 |
| MATIC   | -3.29%         | -21.12%        |           3.54 |            4.63 |                  7 | 42.86%     | 6.06%     | -5.00%     |                3.9 | $670.64       | 2024-01-01 00:00:00 | 2024-12-16 00:00:00 |             28 |
| RDNT    | -3.45%         | -30.46%        |           2.8  |            3.97 |                 11 | 45.45%     | 4.31%     | -3.89%     |                3.7 | $1,043.70     | 2024-01-07 00:00:00 | 2024-12-16 00:00:00 |             41 |
| ETH     | -4.99%         | -27.23%        |           3.82 |            7.78 |                 15 | 40.00%     | 2.92%     | -2.40%     |                4.2 | $1,493.40     | 2024-01-13 00:00:00 | 2024-12-16 00:00:00 |             63 |
| USDT    | -8.15%         | -8.15%         |           0.38 |            0.71 |                  8 | 0.00%      | 0.00%     | -1.06%     |                1.4 | $768.77       | 2024-02-07 00:00:00 | 2025-03-24 00:00:00 |             11 |
| ETHFI   | -9.01%         | -37.01%        |           1.57 |            2.59 |                 11 | 45.45%     | 9.69%     | -8.53%     |                4.9 | $1,106.88     | 2024-05-22 00:00:00 | 2024-12-16 00:00:00 |             54 |
| FLOW    | -10.69%        | -43.77%        |           5.15 |            7.12 |                 16 | 37.50%     | 9.35%     | -6.18%     |                3.6 | $1,528.99     | 2024-01-13 00:00:00 | 2024-12-16 00:00:00 |             57 |
| SOL     | -11.91%        | -40.48%        |           3.77 |            8.51 |                 28 | 28.57%     | 8.33%     | -3.82%     |                4.4 | $2,641.82     | 2024-01-01 00:00:00 | 2025-03-25 00:00:00 |            126 |
| MANA    | -13.00%        | -33.82%        |           1.18 |            1.57 |                 14 | 21.43%     | 14.40%    | -4.46%     |                3.8 | $1,303.40     | 2024-03-01 00:00:00 | 2025-01-17 00:00:00 |             53 |
| KUJI    | -14.02%        | -34.38%        |           3.42 |            6.97 |                  9 | 22.22%     | 17.14%    | -6.20%     |                3.7 | $802.64       | 2024-01-07 00:00:00 | 2024-12-16 00:00:00 |             33 |
| PENDLE  | -16.60%        | -55.62%        |           4.29 |           11.57 |                 21 | 23.81%     | 20.68%    | -6.69%     |                5.5 | $2,397.15     | 2024-01-07 00:00:00 | 2025-03-25 00:00:00 |            117 |
| NMR     | -18.06%        | -65.12%        |           2.54 |            4.73 |                 24 | 37.50%     | 8.24%     | -5.59%     |                3.6 | $2,893.38     | 2024-01-01 00:00:00 | 2024-12-16 00:00:00 |             88 |
| GMX     | -21.05%        | -36.18%        |           5.01 |           12.23 |                 14 | 35.71%     | 5.95%     | -5.56%     |                3.6 | $1,197.41     | 2024-01-10 00:00:00 | 2024-12-13 00:00:00 |             51 |
| GNS     | -22.21%        | -30.27%        |           2.08 |            2.56 |                 11 | 45.45%     | 1.62%     | -5.55%     |                4.5 | $955.95       | 2024-01-10 00:00:00 | 2025-03-25 00:00:00 |             51 |
| PRIME   | -22.53%        | -61.14%        |           4.45 |            9.79 |                 20 | 35.00%     | 17.04%    | -9.11%     |                4.7 | $2,596.63     | 2024-01-01 00:00:00 | 2025-01-20 00:00:00 |             94 |
| AAVE    | -23.44%        | -49.47%        |           5.23 |           12.24 |                 26 | 30.77%     | 11.30%    | -5.34%     |                3.4 | $2,005.86     | 2024-01-01 00:00:00 | 2025-01-17 00:00:00 |             90 |
| MORPHO  | -23.80%        | -37.76%        |          13.83 |            0    |                  6 | 33.33%     | 4.89%     | -8.65%     |                1.5 | $573.54       | 2024-12-24 00:00:00 | 2025-01-24 00:00:00 |              9 |
| SCRT    | -31.14%        | -73.20%        |           3.97 |           13.72 |                 14 | 57.14%     | 6.70%     | -13.03%    |                3.9 | $1,514.64     | 2024-01-07 00:00:00 | 2025-01-18 00:00:00 |             54 |
| AKT     | -31.64%        | -62.44%        |           2.09 |            5.66 |                 19 | 31.58%     | 13.29%    | -7.84%     |                5.1 | $2,031.20     | 2024-01-07 00:00:00 | 2024-12-14 00:00:00 |             96 |
| ETHDYDX | -36.26%        | -54.85%        |           2.87 |            5.9  |                 17 | 17.65%     | 12.87%    | -5.53%     |                2.5 | $1,188.81     | 2024-02-02 00:00:00 | 2025-03-25 00:00:00 |             43 |
| FXS     | -37.46%        | -49.55%        |           2.99 |            6.72 |                 17 | 23.53%     | 12.09%    | -6.76%     |                3.8 | $1,179.65     | 2024-01-13 00:00:00 | 2025-03-25 00:00:00 |             66 |
| STX     | -38.61%        | -66.58%        |           1.9  |            2.83 |                 23 | 30.43%     | 14.53%    | -7.93%     |                4.3 | $2,476.90     | 2024-01-01 00:00:00 | 2024-12-15 00:00:00 |            100 |
| OP      | -39.11%        | -49.69%        |           1.82 |            2.77 |                 18 | 27.78%     | 3.67%     | -5.02%     |                3.9 | $1,377.08     | 2024-01-01 00:00:00 | 2024-12-12 00:00:00 |             72 |
| AVAX    | -39.41%        | -53.14%        |           2.53 |            5.09 |                 19 | 15.79%     | 6.97%     | -4.57%     |                3.8 | $1,246.18     | 2024-02-03 00:00:00 | 2025-03-25 00:00:00 |             74 |
| INJ     | -39.96%        | -48.40%        |           0.5  |            0.86 |                 16 | 25.00%     | 7.00%     | -6.17%     |                3.9 | $1,447.80     | 2024-01-01 00:00:00 | 2025-01-18 00:00:00 |             64 |
| RUNE    | -45.45%        | -73.24%        |           5.11 |           13.64 |                 28 | 42.86%     | 4.94%     | -6.82%     |                3.7 | $2,413.10     | 2024-02-09 00:00:00 | 2025-03-20 00:00:00 |            104 |
| LDO     | -56.55%        | -65.81%        |           3.08 |            6.52 |                 20 | 25.00%     | 8.97%     | -7.82%     |                3.5 | $1,497.97     | 2024-01-01 00:00:00 | 2025-02-06 00:00:00 |             70 |

Detailed Trade History:

MUBI Trades:
|   trade_id | entry_date          | exit_date           |   holding_days |   entry_price |   exit_price | price_return   |   entry_value |   entry_cost |   exit_value |   exit_cost | trade_return   | is_open   |
|-----------:|:--------------------|:--------------------|---------------:|--------------:|-------------:|:---------------|--------------:|-------------:|-------------:|------------:|:---------------|:----------|
|          1 | 2024-01-07 00:00:00 | 2024-01-08 00:00:00 |              1 |     0.14131   |    0.169879  | 20.22%         |       9950    |     -50      |     11901.8  |    -59.8081 | 19.02%         | False     |
|          2 | 2024-03-09 00:00:00 | 2024-03-10 00:00:00 |              1 |     0.13048   |    0.124558  | -4.54%         |      11842.3  |     -59.509  |     11248.3  |    -56.5241 | -5.49%         | False     |
|          3 | 2024-03-12 00:00:00 | 2024-03-13 00:00:00 |              1 |     0.142367  |    0.137467  | -3.44%         |      11192.1  |     -56.2415 |     10752.8  |    -54.0342 | -4.40%         | False     |
|          4 | 2024-09-02 00:00:00 | 2024-09-04 00:00:00 |              2 |     0.0231805 |    0.0222314 | -4.09%         |      10699    |     -53.7641 |     10209.7  |    -51.305  | -5.05%         | False     |
|          5 | 2024-09-20 00:00:00 | 2024-09-25 00:00:00 |              5 |     0.0337519 |    0.0315725 | -6.46%         |      10158.6  |     -51.0485 |      9455.17 |    -47.5134 | -7.39%         | False     |
|          6 | 2024-09-27 00:00:00 | 2024-09-28 00:00:00 |              1 |     0.0351834 |    0.0337064 | -4.20%         |       9407.9  |     -47.2759 |      8967.9  |    -45.0648 | -5.15%         | False     |
|          7 | 2024-10-01 00:00:00 | 2024-10-06 00:00:00 |              5 |     0.0281685 |    0.0288573 | 2.45%          |       8923.06 |     -44.8395 |      9095.52 |    -45.7062 | 1.42%          | False     |
|          8 | 2024-10-07 00:00:00 | 2024-10-08 00:00:00 |              1 |     0.0294891 |    0.0285854 | -3.06%         |       9050.05 |     -45.4776 |      8728.85 |    -43.8636 | -4.03%         | False     |
|          9 | 2024-10-09 00:00:00 | 2024-10-10 00:00:00 |              1 |     0.026721  |    0.0288659 | 8.03%          |       8685.2  |     -43.6442 |      9335.47 |    -46.9119 | 6.95%          | False     |
|         10 | 2024-10-11 00:00:00 | 2024-10-17 00:00:00 |              6 |     0.030378  |    0.0300657 | -1.03%         |       9288.79 |     -46.6773 |      9147.35 |    -45.9666 | -2.02%         | False     |
|         11 | 2024-11-30 00:00:00 | 2024-12-08 00:00:00 |              8 |     0.0430886 |    0.043389  | 0.70%          |       9101.61 |     -45.7367 |      9119.26 |    -45.8254 | -0.31%         | False     |
|         12 | 2024-12-10 00:00:00 | 2024-12-13 00:00:00 |              3 |     0.0315711 |    0.0329262 | 4.29%          |       9073.66 |     -45.5963 |      9415.81 |    -47.3156 | 3.25%          | False     |
|         13 | 2024-12-14 00:00:00 | 2024-12-15 00:00:00 |              1 |     0.0300748 |    0.0345407 | 14.85%         |       9368.73 |     -47.079  |     10706.1  |    -53.7995 | 13.70%         | False     |
|         14 | 2024-12-16 00:00:00 | 2024-12-17 00:00:00 |              1 |     0.030939  |    0.0290729 | -6.03%         |      10652.6  |     -53.5305 |      9959.99 |    -50.0502 | -6.97%         | False     |

UNI Trades:
|   trade_id | entry_date          | exit_date           |   holding_days |   entry_price |   exit_price | price_return   |   entry_value |   entry_cost |   exit_value |   exit_cost | trade_return   | is_open   |
|-----------:|:--------------------|:--------------------|---------------:|--------------:|-------------:|:---------------|--------------:|-------------:|-------------:|------------:|:---------------|:----------|
|          1 | 2024-01-13 00:00:00 | 2024-01-14 00:00:00 |              1 |          6.64 |         6.32 | -4.82%         |       9950    |     -50      |      9423.13 |    -47.3524 | -5.77%         | False     |
|          2 | 2024-02-23 00:00:00 | 2024-02-26 00:00:00 |              3 |         11.32 |        10.58 | -6.54%         |       9376.01 |     -47.1156 |      8719.28 |    -43.8155 | -7.47%         | False     |
|          3 | 2024-02-27 00:00:00 | 2024-02-28 00:00:00 |              1 |         10.86 |        10.93 | 0.64%          |       8675.68 |     -43.5964 |      8687.94 |    -43.658  | -0.36%         | False     |
|          4 | 2024-02-29 00:00:00 | 2024-03-12 00:00:00 |             12 |         11.15 |        14.06 | 26.10%         |       8644.51 |     -43.4397 |     10846.1  |    -54.503  | 24.84%         | False     |
|          5 | 2024-03-13 00:00:00 | 2024-03-15 00:00:00 |              2 |         14.2  |        13.03 | -8.24%         |      10791.9  |     -54.2305 |      9853.17 |    -49.5134 | -9.15%         | False     |
|          6 | 2024-03-30 00:00:00 | 2024-04-01 00:00:00 |              2 |         12.62 |        12.45 | -1.35%         |       9803.9  |     -49.2658 |      9623.48 |    -48.3592 | -2.33%         | False     |
|          7 | 2024-05-21 00:00:00 | 2024-05-30 00:00:00 |              9 |          9.64 |        10.76 | 11.62%         |       9575.36 |     -48.1174 |     10634.4  |    -53.4393 | 10.50%         | False     |
|          8 | 2024-05-31 00:00:00 | 2024-06-08 00:00:00 |              8 |          9.98 |        10.05 | 0.70%          |      10581.2  |     -53.1721 |     10602.2  |    -53.2773 | -0.30%         | False     |
|          9 | 2024-06-09 00:00:00 | 2024-06-10 00:00:00 |              1 |          9.82 |        10.35 | 5.40%          |      10549.2  |     -53.0109 |     11062.9  |    -55.5926 | 4.35%          | False     |
|         10 | 2024-06-11 00:00:00 | 2024-06-12 00:00:00 |              1 |          8.98 |        10.07 | 12.14%         |      11007.6  |     -55.3147 |     12282    |    -61.7186 | 11.02%         | False     |
|         11 | 2024-06-13 00:00:00 | 2024-06-14 00:00:00 |              1 |         10.14 |        10.42 | 2.76%          |      12220.6  |     -61.4101 |     12495.3  |    -62.7903 | 1.74%          | False     |
|         12 | 2024-09-03 00:00:00 | 2024-09-04 00:00:00 |              1 |          6.05 |         6.44 | 6.45%          |      12432.8  |     -62.4763 |     13168.1  |    -66.1712 | 5.38%          | False     |
|         13 | 2024-09-11 00:00:00 | 2024-09-14 00:00:00 |              3 |          6.76 |         6.67 | -1.33%         |      13102.2  |     -65.8403 |     12863.2  |    -64.6389 | -2.32%         | False     |
|         14 | 2024-09-16 00:00:00 | 2024-09-17 00:00:00 |              1 |          6.41 |         6.78 | 5.77%          |      12798.8  |     -64.3158 |     13469.9  |    -67.6881 | 4.72%          | False     |
|         15 | 2024-09-24 00:00:00 | 2024-10-02 00:00:00 |              8 |          6.93 |         6.68 | -3.61%         |      13402.6  |     -67.3496 |     12854.5  |    -64.5954 | -4.57%         | False     |
|         16 | 2024-10-09 00:00:00 | 2024-10-15 00:00:00 |              6 |          7.28 |         7.83 | 7.55%          |      12790.2  |     -64.2724 |     13687.7  |    -68.7825 | 6.48%          | False     |
|         17 | 2024-10-17 00:00:00 | 2024-10-25 00:00:00 |              8 |          7.34 |         7.36 | 0.27%          |      13619.3  |     -68.4386 |     13588.1  |    -68.282  | -0.73%         | False     |
|         18 | 2024-10-30 00:00:00 | 2024-10-31 00:00:00 |              1 |          8.13 |         7.6  | -6.52%         |      13520.2  |     -67.9405 |     12575.6  |    -63.1939 | -7.45%         | False     |
|         19 | 2024-11-01 00:00:00 | 2024-11-02 00:00:00 |              1 |          7.56 |         7.38 | -2.38%         |      12512.7  |     -62.8779 |     12153.7  |    -61.0739 | -3.35%         | False     |
|         20 | 2024-11-25 00:00:00 | 2024-12-14 00:00:00 |             19 |         11.13 |        16.77 | 50.67%         |      12092.9  |     -60.7686 |     18129.8  |    -91.1045 | 49.17%         | False     |

In [124]:
# Plot performance for a specific date range
fig = analyzer.plot_individual_asset_performance(
    portfolio_name='big_wins_i',
    btc_trend_portfolio_name='btc_trend_following',
    start_date=start_date,
    end_date=end_date,
    initial_capital=10000,
    show_plot=False,
   # asset_filter=['SOL']
)

2025-03-27 10:50:11,003 - INFO - Recalculating backtest for portfolio 'big_wins_i' from 2024-01-1 to 2025-03-25.
2025-03-27 10:50:11,102 - INFO - Using signals from BTC-only portfolio 'btc_trend_following'
2025-03-27 10:50:27,068 - INFO - Recalculating backtest for portfolio 'btc_trend_following' from 2024-01-1 to 2025-03-25.
2025-03-27 10:50:27,090 - INFO - Entering BTC position on 2024-01-08 00:00:00: Cost = 10.00
2025-03-27 10:50:27,092 - INFO - Exiting BTC position on 2024-01-09 00:00:00: Cost = 9.99
2025-03-27 10:50:27,094 - INFO - Entering BTC position on 2024-01-10 00:00:00: Cost = 9.98
2025-03-27 10:50:27,100 - INFO - Exiting BTC position on 2024-01-13 00:00:00: Cost = 9.29
2025-03-27 10:50:27,102 - INFO - Entering BTC position on 2024-01-14 00:00:00: Cost = 9.28
2025-03-27 10:50:27,107 - INFO - Exiting BTC position on 2024-01-16 00:00:00: Cost = 9.24
2025-03-27 10:50:27,126 - INFO - Entering BTC position on 2024-01-30 00:00:00: Cost = 9.23
2025-03-27 10:50:27,157 - INFO - Exiting BTC position on 2024-02-27 00:00:00: Cost = 11.63
2025-03-27 10:50:27,159 - INFO - Entering BTC position on 2024-02-28 00:00:00: Cost = 11.62
2025-03-27 10:50:27,176 - INFO - Exiting BTC position on 2024-03-16 00:00:00: Cost = 14.18
2025-03-27 10:50:27,186 - INFO - Entering BTC position on 2024-03-27 00:00:00: Cost = 14.17
2025-03-27 10:50:27,194 - INFO - Exiting BTC position on 2024-04-03 00:00:00: Cost = 13.24
2025-03-27 10:50:27,223 - INFO - Entering BTC position on 2024-05-06 00:00:00: Cost = 13.23
2025-03-27 10:50:27,259 - INFO - Exiting BTC position on 2024-06-15 00:00:00: Cost = 13.65
2025-03-27 10:50:27,276 - INFO - Entering BTC position on 2024-07-03 00:00:00: Cost = 13.64
2025-03-27 10:50:27,278 - INFO - Exiting BTC position on 2024-07-04 00:00:00: Cost = 13.26
2025-03-27 10:50:27,288 - INFO - Entering BTC position on 2024-07-13 00:00:00: Cost = 13.25
2025-03-27 10:50:27,291 - INFO - Exiting BTC position on 2024-07-15 00:00:00: Cost = 13.96
2025-03-27 10:50:27,295 - INFO - Entering BTC position on 2024-07-17 00:00:00: Cost = 13.94
2025-03-27 10:50:27,315 - INFO - Exiting BTC position on 2024-08-03 00:00:00: Cost = 13.15
2025-03-27 10:50:27,342 - INFO - Entering BTC position on 2024-08-24 00:00:00: Cost = 13.14
2025-03-27 10:50:27,347 - INFO - Exiting BTC position on 2024-08-27 00:00:00: Cost = 12.20
2025-03-27 10:50:27,350 - INFO - Entering BTC position on 2024-08-28 00:00:00: Cost = 12.19
2025-03-27 10:50:27,352 - INFO - Exiting BTC position on 2024-08-29 00:00:00: Cost = 12.27
2025-03-27 10:50:27,360 - INFO - Entering BTC position on 2024-09-03 00:00:00: Cost = 12.26
2025-03-27 10:50:27,363 - INFO - Exiting BTC position on 2024-09-05 00:00:00: Cost = 11.98
2025-03-27 10:50:27,371 - INFO - Entering BTC position on 2024-09-12 00:00:00: Cost = 11.97
2025-03-27 10:50:27,431 - INFO - Exiting BTC position on 2024-11-06 00:00:00: Cost = 15.59
2025-03-27 10:50:27,433 - INFO - Entering BTC position on 2024-11-07 00:00:00: Cost = 15.57
2025-03-27 10:50:27,451 - INFO - Exiting BTC position on 2024-11-25 00:00:00: Cost = 19.08
2025-03-27 10:50:27,453 - INFO - Entering BTC position on 2024-11-26 00:00:00: Cost = 19.06
2025-03-27 10:50:27,475 - INFO - Exiting BTC position on 2024-12-18 00:00:00: Cost = 20.83
2025-03-27 10:50:27,482 - INFO - Entering BTC position on 2024-12-24 00:00:00: Cost = 20.81
2025-03-27 10:50:27,486 - INFO - Exiting BTC position on 2024-12-27 00:00:00: Cost = 19.91
2025-03-27 10:50:27,496 - INFO - Entering BTC position on 2025-01-05 00:00:00: Cost = 19.89
2025-03-27 10:50:27,499 - INFO - Exiting BTC position on 2025-01-08 00:00:00: Cost = 19.23
2025-03-27 10:50:27,501 - INFO - Entering BTC position on 2025-01-09 00:00:00: Cost = 19.21
2025-03-27 10:50:27,503 - INFO - Exiting BTC position on 2025-01-10 00:00:00: Cost = 19.72
2025-03-27 10:50:27,510 - INFO - Entering BTC position on 2025-01-16 00:00:00: Cost = 19.70
2025-03-27 10:50:27,527 - INFO - Exiting BTC position on 2025-02-02 00:00:00: Cost = 19.23
2025-03-27 10:50:27,531 - INFO - Entering BTC position on 2025-02-05 00:00:00: Cost = 19.21
2025-03-27 10:50:27,538 - INFO - Exiting BTC position on 2025-02-11 00:00:00: Cost = 19.09
2025-03-27 10:50:27,576 - INFO - Entering BTC position on 2025-03-15 00:00:00: Cost = 19.07

Performance Metrics:
BTC Buy & Hold: Return = 98.15%, Max Drawdown = -26.23%
BTC Trend (btc_trend_following): Return = 99.00%, Max Drawdown = -19.76%

Individual Asset Performance:

|         | Total Return   | Max Drawdown   |   Sharpe Ratio |   Sortino Ratio |   Number of Trades | Win Rate   | Avg Win   | Avg Loss   |   Avg Holding Days | Total Costs   | First Trade         | Last Trade          |   Trading Days |
|:--------|:---------------|:---------------|---------------:|----------------:|-------------------:|:-----------|:----------|:-----------|-------------------:|:--------------|:--------------------|:--------------------|---------------:|
| VIRTUAL | 3636.93%       | -68.94%        |          10.77 |           28.59 |                 19 | 36.84%     | 192.57%   | -13.10%    |                6.2 | $36,822.64    | 2024-02-06 00:00:00 | 2025-01-17 00:00:00 |            118 |
| AERO    | 404.81%        | -64.89%        |           5.88 |           16.88 |                 17 | 41.18%     | 41.45%    | -6.20%     |                5.6 | $4,096.18     | 2024-01-29 00:00:00 | 2024-12-12 00:00:00 |             96 |
| VISTA   | 148.10%        | -70.01%        |           8.23 |           55.95 |                  6 | 16.67%     | 354.07%   | -11.22%    |                3.3 | $1,978.62     | 2024-10-26 00:00:00 | 2025-01-06 00:00:00 |             20 |
| BEAM    | 93.08%         | -28.16%        |          10.3  |           28.29 |                 18 | 38.89%     | 19.30%    | -5.20%     |                4.4 | $2,527.10     | 2024-01-29 00:00:00 | 2025-03-25 00:00:00 |             80 |
| CRV     | 85.33%         | -35.91%        |           9.21 |           37.41 |                 14 | 35.71%     | 27.28%    | -5.39%     |                3.5 | $1,925.18     | 2024-02-24 00:00:00 | 2025-03-25 00:00:00 |             50 |
| GALA    | 61.48%         | -41.04%        |           7.66 |           26.45 |                 14 | 42.86%     | 19.76%    | -6.77%     |                4   | $2,026.68     | 2024-02-23 00:00:00 | 2025-01-17 00:00:00 |             56 |
| ONDO    | 42.01%         | -39.03%        |           8.02 |           20.59 |                 21 | 38.10%     | 16.28%    | -5.91%     |                4.1 | $2,583.15     | 2024-02-15 00:00:00 | 2025-02-07 00:00:00 |             87 |
| SAND    | 29.75%         | -29.51%        |           3.93 |            7.41 |                 10 | 40.00%     | 21.28%    | -6.50%     |                3.8 | $1,055.21     | 2024-03-02 00:00:00 | 2025-01-18 00:00:00 |             38 |
| UNI     | 26.71%         | -41.48%        |           5.99 |           19.12 |                 17 | 35.29%     | 15.69%    | -5.11%     |                4.1 | $1,683.03     | 2024-01-13 00:00:00 | 2024-12-12 00:00:00 |             69 |
| SNX     | 21.73%         | -24.32%        |          10.4  |           52.6  |                  9 | 44.44%     | 7.76%     | -1.92%     |                3.1 | $904.73       | 2024-02-25 00:00:00 | 2025-03-25 00:00:00 |             29 |
| RENDER  | 21.12%         | -54.82%        |           6.87 |           14.61 |                 19 | 42.11%     | 10.13%    | -5.23%     |                4   | $2,530.07     | 2024-01-31 00:00:00 | 2025-03-25 00:00:00 |             77 |
| SCRT    | 18.85%         | -52.88%        |           6.47 |           26.65 |                 12 | 58.33%     | 7.78%     | -6.49%     |                3.1 | $1,337.35     | 2024-02-20 00:00:00 | 2025-01-17 00:00:00 |             37 |
| ENA     | 18.20%         | -47.63%        |           8.66 |           37.37 |                 11 | 45.45%     | 15.66%    | -8.68%     |                4.3 | $1,491.39     | 2024-09-25 00:00:00 | 2025-01-06 00:00:00 |             47 |
| LINK    | 14.38%         | -43.13%        |           6.09 |           25.23 |                 15 | 33.33%     | 14.85%    | -5.21%     |                5   | $2,030.04     | 2024-01-30 00:00:00 | 2025-01-31 00:00:00 |             75 |
| IMX     | 10.59%         | -44.10%        |           8.92 |           31.77 |                 12 | 25.00%     | 22.59%    | -5.30%     |                5.2 | $1,379.22     | 2024-02-02 00:00:00 | 2024-12-06 00:00:00 |             63 |
| PENDLE  | 8.05%          | -45.24%        |           8.37 |           30.03 |                 17 | 35.29%     | 9.90%     | -4.38%     |                4.8 | $1,965.90     | 2024-01-07 00:00:00 | 2025-03-25 00:00:00 |             82 |
| MANA    | 6.79%          | -24.41%        |           4.88 |            7.31 |                 10 | 20.00%     | 21.42%    | -3.72%     |                4.1 | $1,025.59     | 2024-03-01 00:00:00 | 2025-01-17 00:00:00 |             41 |
| RDNT    | 4.03%          | -26.20%        |           8.36 |           35.74 |                  8 | 62.50%     | 3.57%     | -4.31%     |                3.5 | $757.81       | 2024-01-13 00:00:00 | 2024-12-08 00:00:00 |             28 |
| ATOM    | 3.92%          | -17.68%        |           7.22 |           13.8  |                  7 | 28.57%     | 10.32%    | -3.59%     |                3.1 | $648.14       | 2024-09-29 00:00:00 | 2025-03-25 00:00:00 |             23 |
| ETH     | -0.53%         | -23.29%        |           5.5  |           13.48 |                 14 | 35.71%     | 3.30%     | -1.81%     |                3.8 | $1,435.62     | 2024-01-13 00:00:00 | 2024-12-16 00:00:00 |             53 |
| FLOW    | -1.75%         | -43.77%        |           8.87 |           21.04 |                 15 | 40.00%     | 8.66%     | -5.47%     |                3.3 | $1,431.15     | 2024-01-13 00:00:00 | 2024-12-08 00:00:00 |             50 |
| MATIC   | -3.78%         | -21.12%        |           6.97 |           14.47 |                  6 | 50.00%     | 3.74%     | -4.77%     |                3.8 | $567.58       | 2024-02-19 00:00:00 | 2024-12-08 00:00:00 |             23 |
| STX     | -4.51%         | -48.57%        |           7.29 |           14.12 |                 17 | 35.29%     | 11.62%    | -5.88%     |                3.8 | $2,290.40     | 2024-01-01 00:00:00 | 2024-12-15 00:00:00 |             66 |
| USDT    | -6.15%         | -6.15%         |           3.65 |            6.72 |                  6 | 0.00%      | 0.00%     | -1.05%     |                1.3 | $582.82       | 2024-02-07 00:00:00 | 2025-03-24 00:00:00 |              8 |
| MKR     | -7.09%         | -29.48%        |           7.67 |           14.87 |                 16 | 31.25%     | 7.87%     | -3.97%     |                2.8 | $1,474.38     | 2024-01-10 00:00:00 | 2025-03-18 00:00:00 |             44 |
| ETHFI   | -7.83%         | -27.82%        |           7.18 |           22.71 |                  8 | 37.50%     | 10.91%    | -7.42%     |                4.9 | $806.82       | 2024-05-22 00:00:00 | 2024-12-16 00:00:00 |             39 |
| KUJI    | -7.90%         | -33.17%        |          10.33 |           13.78 |                  8 | 12.50%     | 29.47%    | -4.72%     |                2.5 | $709.11       | 2024-10-12 00:00:00 | 2024-12-15 00:00:00 |             20 |
| SOL     | -9.54%         | -35.80%        |           7.35 |           19.29 |                 24 | 33.33%     | 6.34%     | -3.72%     |                3.8 | $2,098.74     | 2024-01-10 00:00:00 | 2025-03-25 00:00:00 |             92 |
| MORPHO  | -12.14%        | -28.24%        |          16.9  |            0    |                  4 | 50.00%     | 4.89%     | -10.59%    |                1.8 | $404.39       | 2024-12-24 00:00:00 | 2025-01-18 00:00:00 |              7 |
| PRIME   | -12.85%        | -49.85%        |           9.27 |           26.25 |                 17 | 35.29%     | 11.92%    | -6.88%     |                3.8 | $2,040.08     | 2024-02-04 00:00:00 | 2025-01-17 00:00:00 |             65 |
| HNT     | -12.85%        | -35.68%        |           7.04 |           19.49 |                 10 | 40.00%     | 10.23%    | -8.11%     |                4.7 | $1,037.50     | 2024-01-09 00:00:00 | 2024-12-16 00:00:00 |             47 |
| GNS     | -13.78%        | -20.36%        |           7.06 |           13.14 |                  9 | 33.33%     | 0.63%     | -3.02%     |                4.4 | $800.03       | 2024-01-10 00:00:00 | 2025-03-25 00:00:00 |             41 |
| GMX     | -15.64%        | -31.81%        |           6.78 |           16.86 |                 13 | 38.46%     | 5.95%     | -5.46%     |                3.6 | $1,156.32     | 2024-01-10 00:00:00 | 2024-12-13 00:00:00 |             47 |
| ARB     | -16.66%        | -39.36%        |           7.17 |           17.66 |                  8 | 25.00%     | 5.47%     | -4.64%     |                4   | $701.08       | 2024-01-01 00:00:00 | 2024-12-08 00:00:00 |             33 |
| AAVE    | -16.69%        | -45.26%        |           8.55 |           26.11 |                 21 | 33.33%     | 13.38%    | -6.46%     |                3.4 | $1,714.90     | 2024-01-01 00:00:00 | 2025-01-17 00:00:00 |             73 |
| MUBI    | -22.12%        | -41.03%        |           6.04 |           20.09 |                  6 | 0.00%      | 0.00%     | -4.05%     |                3.8 | $518.48       | 2024-03-12 00:00:00 | 2024-12-07 00:00:00 |             23 |
| NMR     | -25.11%        | -58.15%        |           6.01 |           13.86 |                 16 | 25.00%     | 10.18%    | -5.32%     |                3.8 | $1,622.77     | 2024-01-01 00:00:00 | 2024-12-08 00:00:00 |             62 |
| ETHDYDX | -26.19%        | -50.38%        |           4.86 |            8.84 |                 13 | 15.38%     | 17.43%    | -5.42%     |                2.8 | $948.96       | 2024-02-02 00:00:00 | 2025-03-25 00:00:00 |             37 |
| NEAR    | -29.34%        | -67.02%        |           5.62 |           25.6  |                 18 | 33.33%     | 7.59%     | -6.14%     |                3.7 | $1,600.46     | 2024-01-13 00:00:00 | 2024-12-08 00:00:00 |             66 |
| FXS     | -31.34%        | -47.74%        |           7.13 |           29.14 |                 13 | 15.38%     | 19.63%    | -6.48%     |                4.1 | $888.43       | 2024-01-13 00:00:00 | 2025-03-25 00:00:00 |             54 |
| AVAX    | -41.25%        | -50.69%        |           5.45 |           18.1  |                 20 | 15.00%     | 8.73%     | -4.69%     |                2.6 | $1,402.36     | 2024-02-03 00:00:00 | 2025-03-25 00:00:00 |             53 |
| AKT     | -43.23%        | -65.93%        |           6.19 |           28.98 |                 20 | 25.00%     | 12.89%    | -7.24%     |                3.5 | $1,834.13     | 2024-01-07 00:00:00 | 2024-12-08 00:00:00 |             69 |
| INJ     | -46.86%        | -47.77%        |           4.49 |           10.46 |                 12 | 25.00%     | 2.80%     | -7.56%     |                4.1 | $912.59       | 2024-01-10 00:00:00 | 2025-01-18 00:00:00 |             49 |
| RUNE    | -47.01%        | -74.00%        |           9.05 |           30.12 |                 25 | 28.00%     | 6.72%     | -5.63%     |                3.1 | $2,316.38     | 2024-02-09 00:00:00 | 2025-03-20 00:00:00 |             78 |
| OP      | -49.98%        | -54.65%        |           7.64 |           16.27 |                 14 | 7.14%      | 2.08%     | -5.29%     |                3.7 | $996.10       | 2024-01-10 00:00:00 | 2024-12-12 00:00:00 |             52 |
| LDO     | -55.99%        | -65.37%        |           7.2  |           27.59 |                 17 | 17.65%     | 7.09%     | -7.00%     |                3   | $1,344.42     | 2024-01-01 00:00:00 | 2025-01-31 00:00:00 |             52 |

Detailed Trade History:

MUBI Trades:
|   trade_id | entry_date          | exit_date           |   holding_days |   entry_price |   exit_price | price_return   |   entry_value |   entry_cost |   exit_value |   exit_cost | trade_return   | is_open   |
|-----------:|:--------------------|:--------------------|---------------:|--------------:|-------------:|:---------------|--------------:|-------------:|-------------:|------------:|:---------------|:----------|
|          1 | 2024-03-12 00:00:00 | 2024-03-13 00:00:00 |              1 |     0.142367  |    0.137467  | -3.44%         |       9950    |     -50      |      9559.5  |    -48.0377 | -4.40%         | False     |
|          2 | 2024-09-02 00:00:00 | 2024-09-04 00:00:00 |              2 |     0.0231805 |    0.0222314 | -4.09%         |       9511.7  |     -47.7975 |      9076.66 |    -45.6114 | -5.05%         | False     |
|          3 | 2024-09-20 00:00:00 | 2024-09-25 00:00:00 |              5 |     0.0337519 |    0.0315725 | -6.46%         |       9031.28 |     -45.3833 |      8405.87 |    -42.2406 | -7.39%         | False     |
|          4 | 2024-09-27 00:00:00 | 2024-09-28 00:00:00 |              1 |     0.0351834 |    0.0337064 | -4.20%         |       8363.84 |     -42.0294 |      7972.67 |    -40.0637 | -5.15%         | False     |
|          5 | 2024-10-11 00:00:00 | 2024-10-17 00:00:00 |              6 |     0.030378  |    0.0300657 | -1.03%         |       7932.81 |     -39.8633 |      7812.01 |    -39.2564 | -2.02%         | False     |
|          6 | 2024-11-30 00:00:00 | 2024-12-08 00:00:00 |              8 |     0.0430886 |    0.043389  | 0.70%          |       7772.95 |     -39.0601 |      7788.02 |    -39.1358 | -0.31%         | False     |

UNI Trades:
|   trade_id | entry_date          | exit_date           |   holding_days |   entry_price |   exit_price | price_return   |   entry_value |   entry_cost |   exit_value |   exit_cost | trade_return   | is_open   |
|-----------:|:--------------------|:--------------------|---------------:|--------------:|-------------:|:---------------|--------------:|-------------:|-------------:|------------:|:---------------|:----------|
|          1 | 2024-01-13 00:00:00 | 2024-01-14 00:00:00 |              1 |          6.64 |         6.32 | -4.82%         |       9950    |     -50      |      9423.13 |    -47.3524 | -5.77%         | False     |
|          2 | 2024-02-23 00:00:00 | 2024-02-26 00:00:00 |              3 |         11.32 |        10.58 | -6.54%         |       9376.01 |     -47.1156 |      8719.28 |    -43.8155 | -7.47%         | False     |
|          3 | 2024-02-27 00:00:00 | 2024-02-28 00:00:00 |              1 |         10.86 |        10.93 | 0.64%          |       8675.68 |     -43.5964 |      8687.94 |    -43.658  | -0.36%         | False     |
|          4 | 2024-02-29 00:00:00 | 2024-03-04 00:00:00 |              4 |         11.15 |        12.39 | 11.12%         |       8644.51 |     -43.4397 |      9557.84 |    -48.0293 | 10.01%         | False     |
|          5 | 2024-03-05 00:00:00 | 2024-03-11 00:00:00 |              6 |         13.02 |        14.47 | 11.14%         |       9510.05 |     -47.7892 |     10516.3  |    -52.8458 | 10.03%         | False     |
|          6 | 2024-03-31 00:00:00 | 2024-04-01 00:00:00 |              1 |         12.94 |        12.45 | -3.79%         |      10463.7  |     -52.5815 |     10017.2  |    -50.3375 | -4.75%         | False     |
|          7 | 2024-05-21 00:00:00 | 2024-05-30 00:00:00 |              9 |          9.64 |        10.76 | 11.62%         |       9967.07 |     -50.0858 |     11069.4  |    -55.6254 | 10.50%         | False     |
|          8 | 2024-06-04 00:00:00 | 2024-06-07 00:00:00 |              3 |         11.44 |         9.82 | -14.16%        |      11014.1  |     -55.3472 |      9407.14 |    -47.2721 | -15.02%        | False     |
|          9 | 2024-09-03 00:00:00 | 2024-09-04 00:00:00 |              1 |          6.05 |         6.44 | 6.45%          |       9360.1  |     -47.0357 |      9913.67 |    -49.8174 | 5.38%          | False     |
|         10 | 2024-09-11 00:00:00 | 2024-09-14 00:00:00 |              3 |          6.76 |         6.67 | -1.33%         |       9864.1  |     -49.5683 |      9684.11 |    -48.6639 | -2.32%         | False     |
|         11 | 2024-09-24 00:00:00 | 2024-10-01 00:00:00 |              7 |          6.93 |         6.89 | -0.58%         |       9635.69 |     -48.4205 |      9532.17 |    -47.9003 | -1.57%         | False     |
|         12 | 2024-10-09 00:00:00 | 2024-10-15 00:00:00 |              6 |          7.28 |         7.83 | 7.55%          |       9484.51 |     -47.6608 |     10150.1  |    -51.0053 | 6.48%          | False     |
|         13 | 2024-10-20 00:00:00 | 2024-10-25 00:00:00 |              5 |          7.75 |         7.36 | -5.03%         |      10099.3  |     -50.7503 |      9543.12 |    -47.9554 | -5.98%         | False     |
|         14 | 2024-10-30 00:00:00 | 2024-10-31 00:00:00 |              1 |          8.13 |         7.6  | -6.52%         |       9495.41 |     -47.7156 |      8832.01 |    -44.382  | -7.45%         | False     |
|         15 | 2024-11-01 00:00:00 | 2024-11-02 00:00:00 |              1 |          7.56 |         7.38 | -2.38%         |       8787.85 |     -44.1601 |      8535.73 |    -42.8931 | -3.35%         | False     |
|         16 | 2024-11-25 00:00:00 | 2024-12-11 00:00:00 |             16 |         11.13 |        17.06 | 53.28%         |       8493.05 |     -42.6786 |     12953    |    -65.0905 | 51.75%         | False     |
|         17 | 2024-12-12 00:00:00 | 2024-12-13 00:00:00 |              1 |         17.63 |        17.42 | -1.19%         |      12888.2  |     -64.765  |     12671    |    -63.6736 | -2.18%         | False     |

GMX Trades:
|   trade_id | entry_date          | exit_date           |   holding_days |   entry_price |   exit_price | price_return   |   entry_value |   entry_cost |   exit_value |   exit_cost | trade_return   | is_open   |
|-----------:|:--------------------|:--------------------|---------------:|--------------:|-------------:|:---------------|--------------:|-------------:|-------------:|------------:|:---------------|:----------|
|          1 | 2024-01-10 00:00:00 | 2024-01-11 00:00:00 |              1 |         55.43 |        55.83 | 0.72%          |       9950    |     -50      |      9971.69 |    -50.109  | -0.28%         | False     |
|          2 | 2024-05-11 00:00:00 | 2024-05-14 00:00:00 |              3 |         28.92 |        27.32 | -5.53%         |       9921.83 |     -49.8585 |      9326.04 |    -46.8645 | -6.47%         | False     |
|          3 | 2024-05-16 00:00:00 | 2024-05-18 00:00:00 |              2 |         30.3  |        29.45 | -2.81%         |       9279.41 |     -46.6302 |      8974.01 |    -45.0955 | -3.77%         | False     |
|          4 | 2024-05-21 00:00:00 | 2024-05-27 00:00:00 |              6 |         33.2  |        31.77 | -4.31%         |       8929.14 |     -44.87   |      8501.81 |    -42.7227 | -5.26%         | False     |
|          5 | 2024-05-28 00:00:00 | 2024-06-10 00:00:00 |             13 |         34.37 |        37.43 | 8.90%          |       8459.31 |     -42.5091 |      9166.38 |    -46.0622 | 7.82%          | False     |
|          6 | 2024-07-19 00:00:00 | 2024-07-24 00:00:00 |              5 |         29.08 |        29.46 | 1.31%          |       9120.55 |     -45.8319 |      9193.54 |    -46.1987 | 0.30%          | False     |
|          7 | 2024-08-24 00:00:00 | 2024-08-26 00:00:00 |              2 |         30.33 |        28.17 | -7.12%         |       9147.57 |     -45.9677 |      8453.63 |    -42.4805 | -8.05%         | False     |
|          8 | 2024-09-02 00:00:00 | 2024-09-03 00:00:00 |              1 |         26.04 |        25.06 | -3.76%         |       8411.36 |     -42.2681 |      8054.33 |    -40.474  | -4.72%         | False     |
|          9 | 2024-11-23 00:00:00 | 2024-11-24 00:00:00 |              1 |         31.34 |        32.02 | 2.17%          |       8014.06 |     -40.2716 |      8147    |    -40.9397 | 1.15%          | False     |
|         10 | 2024-11-25 00:00:00 | 2024-11-26 00:00:00 |              1 |         31.84 |        31    | -2.64%         |       8106.27 |     -40.735  |      7852.95 |    -39.462  | -3.61%         | False     |

In [ ]:
def get_signals_for_period(start_date, end_date, assets='all'):
    results_df = analyzer.get_portfolio_details(portfolio_name='altcoins_trend_following_btc').get('backtest_results').get('signals_df')
    
    # Filter by date range
    signals = results_df[(results_df.index >= start_date) & (results_df.index <= end_date)]
    
    # Filter by assets if specified
    if assets != 'all':
        if isinstance(assets, str):
            assets = [assets]
        signals = signals[signals['asset'].isin(assets)]
        
    return signals

# Example usage:
start_date = '2024-7-31'
end_date = '2025-3-25' 

assets = ['ETH']  # or 'all' for all assets
#assets = 'all'
signals = get_signals_for_period(start_date, end_date, assets)
signals[(signals['followed_portfolio_signal'] == 1) & (signals['final_decision'] == 0)]

In [ ]:
assets_held = analyzer.get_portfolio_details(portfolio_name='btc_gated_rsi_vol_momentum').get('backtest_results').get('results_df')
assets_held

import matplotlib.pyplot as plt

# Get the results dataframe

# Create the plot
plt.figure(figsize=(14, 6))

# Plot the assets held line
plt.plot(assets_held.index, assets_held['Assets_Held'], 'b-')

# Add vertical lines for each month
for date in assets_held.index[assets_held.index.is_month_start]:
    plt.axvline(x=date, color='gray', alpha=0.3, linestyle='--')

plt.title('Assets Held Over Time')
plt.ylabel('Number of Assets')
plt.grid(True, alpha=0.3)
plt.xticks(rotation=45)
plt.tight_layout()

In [ ]:
test_criteria = [{'Short Term (USD)': ['Strong Bull'],
                  'Short Term (BTC)': ['Strong Bull'],
                  'Overall (BTC)': ['Strong Bull']},
                  
                 {'Short Term (BTC)': ['Strong Bull'],
                  'Short Term (USD)': ['Weak Bull', 'Strong Bull']}]

In [ ]:
btc_data = analyzer.asset_data['maker'].get('classified_data')[['date', 'Short Term (USD)', 'Overall (USD)', 'RSI_Signal_close']]
btc_data[btc_data['date'] == data]

In [33]:
results_df = analyzer.get_portfolio_details(portfolio_name='altcoins_trend_following_btc').get('backtest_results')
results_df

{'results_df': Empty DataFrame
 Columns: []
 Index: [2024-01-01 00:00:00, 2024-01-02 00:00:00, 2024-01-03 00:00:00, 2024-01-04 00:00:00, 2024-01-05 00:00:00, 2024-01-06 00:00:00, 2024-01-07 00:00:00, 2024-01-08 00:00:00, 2024-01-09 00:00:00, 2024-01-10 00:00:00, 2024-01-11 00:00:00, 2024-01-12 00:00:00, 2024-01-13 00:00:00, 2024-01-14 00:00:00, 2024-01-15 00:00:00, 2024-01-16 00:00:00, 2024-01-17 00:00:00, 2024-01-18 00:00:00, 2024-01-19 00:00:00, 2024-01-20 00:00:00, 2024-01-21 00:00:00, 2024-01-22 00:00:00, 2024-01-23 00:00:00, 2024-01-24 00:00:00, 2024-01-25 00:00:00, 2024-01-26 00:00:00, 2024-01-27 00:00:00, 2024-01-28 00:00:00, 2024-01-29 00:00:00, 2024-01-30 00:00:00, 2024-01-31 00:00:00, 2024-02-01 00:00:00, 2024-02-02 00:00:00, 2024-02-03 00:00:00, 2024-02-04 00:00:00, 2024-02-05 00:00:00, 2024-02-06 00:00:00, 2024-02-07 00:00:00, 2024-02-08 00:00:00, 2024-02-09 00:00:00, 2024-02-10 00:00:00, 2024-02-11 00:00:00, 2024-02-12 00:00:00, 2024-02-13 00:00:00, 2024-02-14 00:00:00, 2024-02-15 00:00:00, 2024-02-16 00:00:00, 2024-02-17 00:00:00, 2024-02-18 00:00:00, 2024-02-19 00:00:00, 2024-02-20 00:00:00, 2024-02-21 00:00:00, 2024-02-22 00:00:00, 2024-02-23 00:00:00, 2024-02-24 00:00:00, 2024-02-25 00:00:00, 2024-02-26 00:00:00, 2024-02-27 00:00:00, 2024-02-28 00:00:00, 2024-02-29 00:00:00, 2024-03-01 00:00:00, 2024-03-02 00:00:00, 2024-03-03 00:00:00, 2024-03-04 00:00:00, 2024-03-05 00:00:00, 2024-03-06 00:00:00, 2024-03-07 00:00:00, 2024-03-08 00:00:00, 2024-03-09 00:00:00, 2024-03-10 00:00:00, 2024-03-11 00:00:00, 2024-03-12 00:00:00, 2024-03-13 00:00:00, 2024-03-14 00:00:00, 2024-03-15 00:00:00, 2024-03-16 00:00:00, 2024-03-17 00:00:00, 2024-03-18 00:00:00, 2024-03-19 00:00:00, 2024-03-20 00:00:00, 2024-03-21 00:00:00, 2024-03-22 00:00:00, 2024-03-23 00:00:00, 2024-03-24 00:00:00, 2024-03-25 00:00:00, 2024-03-26 00:00:00, 2024-03-27 00:00:00, 2024-03-28 00:00:00, 2024-03-29 00:00:00, 2024-03-30 00:00:00, 2024-03-31 00:00:00, 2024-04-01 00:00:00, 2024-04-02 00:00:00, 2024-04-03 00:00:00, 2024-04-04 00:00:00, 2024-04-05 00:00:00, 2024-04-06 00:00:00, 2024-04-07 00:00:00, 2024-04-08 00:00:00, 2024-04-09 00:00:00, ...]

 [450 rows x 0 columns],
 'signals_df':             asset  usd_trend_signal  btc_trend_signal  rsi_usd_signal  \
 date
 2024-01-01   MUBI                -1                -1               1
 2024-01-01    UNI                 1                -1               1
 2024-01-01    GMX                 1                -1               1
 2024-01-01   SCRT                -1                -1               1
 2024-01-01  MATIC                 1                -1               1
 ...           ...               ...               ...             ...
 2025-03-25    LDO                 1                -1              -1
 2025-03-25    AKT                 1                -1              -1
 2025-03-25   FLOW                 1                -1              -1
 2025-03-25    IMX                 1                -1              -1
 2025-03-25   USDT                 1                -1               1

             rsi_btc_signal  volatility_signal ssr_signal ssr_gate btc_gate  \
 date
 2024-01-01               1                 -1       None     None     None
 2024-01-01               1                 -1       None     None     None
 2024-01-01               1                 -1       None     None     None
 2024-01-01               1                 -1       None     None     None
 2024-01-01               1                 -1       None     None     None
 ...                    ...                ...        ...      ...      ...
 2025-03-25              -1                  1       None     None     None
 2025-03-25              -1                  1       None     None     None
 2025-03-25              -1                  1       None     None     None
 2025-03-25              -1                  1       None     None     None
 2025-03-25              -1                  1       None     None     None

            btc_rsi_gate btc_rsi_signal  followed_portfolio_signal  \
 date
 2024-01-01         None           None                        NaN
 2024-01-01         None           None                        NaN
 2024-01-01         None           None                        NaN
 2024-01-01         None           None                        NaN
 2024-01-01         None           None                        NaN
 ...                 ...            ...                        ...
 2025-03-25         None           None                        1.0
 2025-03-25         None           None                        1.0
 2025-03-25         None           None                        1.0
 2025-03-25         None           None                        1.0
 2025-03-25         None           None                        1.0

             combined_signal  final_decision
 date
 2024-01-01             40.0               0
 2024-01-01             60.0               0
 2024-01-01             60.0               0
 2024-01-01             40.0               0
 2024-01-01             60.0               0
 ...                     ...             ...
 2025-03-25             40.0               0
 2025-03-25             40.0               0
 2025-03-25             40.0               0
 2025-03-25             40.0               0
 2025-03-25             60.0               0

 [20039 rows x 14 columns],
 'metrics': {'total_return': 0,
  'max_drawdown': 0,
  'initial_capital': 10000,
  'final_value': 10000,
  'sharpe_ratio': 0,
  'sortino_ratio': 0}}

In [35]:
signals_btc = analyzer.get_portfolio_details(portfolio_name='alt_short_momentum_low_vol').get('backtest_results').get('results_df')
signals_btc.head(60)

Empty DataFrame
Columns: []
Index: [2024-01-01 00:00:00, 2024-01-02 00:00:00, 2024-01-03 00:00:00, 2024-01-04 00:00:00, 2024-01-05 00:00:00, 2024-01-06 00:00:00, 2024-01-07 00:00:00, 2024-01-08 00:00:00, 2024-01-09 00:00:00, 2024-01-10 00:00:00, 2024-01-11 00:00:00, 2024-01-12 00:00:00, 2024-01-13 00:00:00, 2024-01-14 00:00:00, 2024-01-15 00:00:00, 2024-01-16 00:00:00, 2024-01-17 00:00:00, 2024-01-18 00:00:00, 2024-01-19 00:00:00, 2024-01-20 00:00:00, 2024-01-21 00:00:00, 2024-01-22 00:00:00, 2024-01-23 00:00:00, 2024-01-24 00:00:00, 2024-01-25 00:00:00, 2024-01-26 00:00:00, 2024-01-27 00:00:00, 2024-01-28 00:00:00, 2024-01-29 00:00:00, 2024-01-30 00:00:00, 2024-01-31 00:00:00, 2024-02-01 00:00:00, 2024-02-02 00:00:00, 2024-02-03 00:00:00, 2024-02-04 00:00:00, 2024-02-05 00:00:00, 2024-02-06 00:00:00, 2024-02-07 00:00:00, 2024-02-08 00:00:00, 2024-02-09 00:00:00, 2024-02-10 00:00:00, 2024-02-11 00:00:00, 2024-02-12 00:00:00, 2024-02-13 00:00:00, 2024-02-14 00:00:00, 2024-02-15 00:00:00, 2024-02-16 00:00:00, 2024-02-17 00:00:00, 2024-02-18 00:00:00, 2024-02-19 00:00:00, 2024-02-20 00:00:00, 2024-02-21 00:00:00, 2024-02-22 00:00:00, 2024-02-23 00:00:00, 2024-02-24 00:00:00, 2024-02-25 00:00:00, 2024-02-26 00:00:00, 2024-02-27 00:00:00, 2024-02-28 00:00:00, 2024-02-29 00:00:00]

In [ ]:
analyzer.asset_data.get('maker')