In [1]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import plotly.graph_objects as go
from trend_analisys_rsi_markov import TrendAnalyzer
import warnings
from scripts.assetsRoster import carteira_AC, carteira_HB, others, carteira_EXC
warnings.filterwarnings('ignore')

In [2]:
asset_ids = [
    'bitcoin', 'ethereum', 'binancecoin', 'ripple', 'cardano',
    'solana', 'polkadot'
]

In [3]:
data_path='/Users/valter.rebelo/MissionControl/data/micro/candleData/'
btc_data_path='/Users/valter.rebelo/MissionControl/data/micro/candleData/bitcoin_candles.csv'
ssr_data_path='/Users/valter.rebelo/MissionControl/data/onchainData/BTC_SSR.csv'

In [8]:
analyzer = TrendAnalyzer(
    asset_ids=['bitcoin', 'ethereum'],
    data_path=data_path,
    btc_data_path=btc_data_path,
    ssr_data_path=ssr_data_path,
    use_btc_adjusted=True,
    verbose=True,
    lookback_days=180,
    trend_metrics_lookback=365,
    markov_model_name='20250325_144631'
)

2025-04-01 15:35:37,139 - INFO - Loaded Markov volatility model: 20250325_144631
2025-04-01 15:35:37,143 - INFO - Successfully loaded SSR data with 2353 rows.

Data loaded successfully: 4107 records
Training set: 3285 records
Test set: 822 records
Model metadata:
  Saved on: 2025-03-25
  Data range: 2014-01-01 to 2025-03-24
  Records: 4101 total, 3075 train, 1026 test
Model loaded from /Users/valter.rebelo/MissionControl/models/markov_volatility_model_20250325_144631.pkl

In [9]:

# Analyze assets
analyzer.analyze_multiple_assets()

Analyzing assets (static):   0%|          | 0/2 [00:00<?, ?it/s]2025-04-01 15:35:37,447 - INFO - Successfully loaded data for bitcoin with 4355 rows.
Analyzing assets (static):  50%|█████     | 1/2 [00:02<00:02,  2.68s/it]2025-04-01 15:35:40,136 - INFO - Successfully loaded data for ethereum with 3524 rows.
Analyzing assets (static): 100%|██████████| 2/2 [00:07<00:00,  3.58s/it]
Computing lookback metrics: 100%|██████████| 2/2 [00:00<00:00, 28.01it/s]
2025-04-01 15:35:44,682 - INFO - Trend analysis completed for multiple assets.

,Ticker,Short Term Trend (USD),Medium Term Trend (USD),Long Term Trend (USD),Overall Trend (USD),Short Term Trend (BTC),Medium Term Trend (BTC),Long Term Trend (BTC),Overall Trend (BTC),Sharpe Ratio (USD),...,Current Trend Sortino (USD),Current Trend Mean Return (USD),Current Trend Median Return (USD),Current Trend Skew (USD),Current Trend Sharpe (BTC),Current Trend Sortino (BTC),Current Trend Mean Return (BTC),Current Trend Median Return (BTC),Current Trend Skew (BTC),Latest Date
0,BTC,Strong Bear,Strong Bear,Weak Bull,Weak Bear,None,None,None,None,1.102142,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-30
1,ETH,Strong Bear,Strong Bear,Strong Bear,Strong Bear,Strong Bear,Strong Bear,Strong Bear,Strong Bear,1.164017,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-03-30

In [ ]:
analyzer.asset_data.get('ethereum').get('trend_metrics')

In [17]:
start_date='2024-01-1'
end_date='2025-03-30'

# Create a BTC-only trend-following portfolio
analyzer.create_portfolio(
    portfolio_name='btc_trend_following',
    usd_conditions={'Short Term (USD)': ['Weak Bull','Strong Bull']},
    btc_only=True,
    btc_trend_gating=None,
    rsi_conditions_usd=True,
    use_ssr_signal=True,
    use_volatility_filter=True,
    volatility_weight=1
)

# Then create an altcoin portfolio that follows the Bitcoin portfolio
analyzer.create_portfolio(
    portfolio_name='big_wins_i',
    btc_conditions={'Short Term (BTC)': ['Strong Bull'], 'Overall (BTC)': ['Strong Bull']},
    usd_conditions={'Short Term (USD)': ['Strong Bull']},
    rsi_conditions_usd=True,
    rsi_conditions_btc=True,
    use_btc_rsi_signal=False,
    btc_only=False,  # This is an altcoin portfolio
    follow_portfolio='btc_trend_following',
    use_ssr_signal=False,
    use_ssr_gate=False,
    use_volatility_filter=True,
    volatility_weight=1
)

# Then create an altcoin portfolio that follows the Bitcoin portfolio
# Then create an altcoin portfolio that follows the Bitcoin portfolio
analyzer.create_portfolio(
    portfolio_name='big_wins_ii',
    btc_conditions={'Short Term (BTC)': ['Weak Bull','Strong Bull'], 'Overall (BTC)': ['Strong Bull']},
    usd_conditions={'Short Term (USD)': ['Strong Bull']},
    rsi_conditions_usd=True,
    rsi_conditions_btc=True,
    use_btc_rsi_signal=True,
    btc_only=False,  # This is an altcoin portfolio
    follow_portfolio='btc_trend_following',
    use_ssr_signal=False,
    use_ssr_gate=False,
    use_volatility_filter=True,
    volatility_weight=1
)


# Then create an altcoin portfolio that follows the Bitcoin portfolio
analyzer.create_portfolio(
    portfolio_name='fat_tails',
    btc_conditions={'Short Term (BTC)': ['Strong Bull'], 'Overall (BTC)': ['Weak Bull','Strong Bull']},
    usd_conditions={'Short Term (USD)': ['Strong Bull']},
    rsi_conditions_usd=True,
    rsi_conditions_btc=True,
    use_btc_rsi_signal=True,
    btc_only=False,  # This is an altcoin portfolio
    follow_portfolio='btc_trend_following',
    use_ssr_signal=False,
    use_ssr_gate=False,
    use_volatility_filter=True,
    volatility_weight=1
)

# Then create an altcoin portfolio that follows the Bitcoin portfolio
analyzer.create_portfolio(
    portfolio_name='experiment_i',
    btc_conditions={'Short Term (BTC)': ['Weak Bull','Strong Bull'], 'Overall (BTC)': ['Strong Bull']},
    usd_conditions={'Short Term (USD)': ['Strong Bear','Strong Bull']},
    rsi_conditions_usd=True,
    rsi_conditions_btc=True,
    use_btc_rsi_signal=False,
    btc_only=False,  # This is an altcoin portfolio
    follow_portfolio='btc_trend_following',
    use_ssr_signal=False,
    use_ssr_gate=False,
    use_volatility_filter=True,
    volatility_weight=1
)


########################################################

# Backtest the altcoin portfolio
results_alt = analyzer.backtest_portfolio(
    portfolio_name='big_wins_i',
    start_date=start_date,
    end_date=end_date,
    initial_capital=10000,
    alt_cost=0.005,
    signal_threshold=100
)

results_alt = analyzer.backtest_portfolio(
    portfolio_name='experiment_i',
    start_date=start_date,
    end_date=end_date,
    initial_capital=10000,
    alt_cost=0.005,
    signal_threshold=80
)

# Backtest the BTC trend-following portfolio
results_btc = analyzer.backtest_portfolio(
    portfolio_name='btc_trend_following',
    start_date=start_date,
    end_date=end_date,
    initial_capital=10000,
    alt_cost=0.001,
    signal_threshold=50
)

2025-04-01 15:42:10,878 - WARNING - Portfolio btc_trend_following already exists. Overwriting.
2025-04-01 15:42:10,882 - INFO - Portfolio 'btc_trend_following' created with criteria: BTC gating=None, USD conditions={'Short Term (USD)': ['Weak Bull', 'Strong Bull']}, BTC conditions=None, RSI USD=True, RSI BTC=False, volatility filter=True, volatility weight=1, SSR signal=True, SSR gate=False, BTC RSI gate=False, BTC RSI signal=False, Follow portfolio=None, BTC only=True
2025-04-01 15:42:10,883 - WARNING - Portfolio big_wins_i already exists. Overwriting.
2025-04-01 15:42:10,884 - INFO - Portfolio 'big_wins_i' created with criteria: BTC gating=None, USD conditions={'Short Term (USD)': ['Strong Bull']}, BTC conditions={'Short Term (BTC)': ['Strong Bull'], 'Overall (BTC)': ['Strong Bull']}, RSI USD=True, RSI BTC=True, volatility filter=True, volatility weight=1, SSR signal=False, SSR gate=False, BTC RSI gate=False, BTC RSI signal=False, Follow portfolio=btc_trend_following, BTC only=False
2025-04-01 15:42:10,885 - WARNING - Portfolio big_wins_ii already exists. Overwriting.
2025-04-01 15:42:10,885 - INFO - Portfolio 'big_wins_ii' created with criteria: BTC gating=None, USD conditions={'Short Term (USD)': ['Strong Bull']}, BTC conditions={'Short Term (BTC)': ['Weak Bull', 'Strong Bull'], 'Overall (BTC)': ['Strong Bull']}, RSI USD=True, RSI BTC=True, volatility filter=True, volatility weight=1, SSR signal=False, SSR gate=False, BTC RSI gate=False, BTC RSI signal=True, Follow portfolio=btc_trend_following, BTC only=False
2025-04-01 15:42:10,886 - WARNING - Portfolio fat_tails already exists. Overwriting.
2025-04-01 15:42:10,886 - INFO - Portfolio 'fat_tails' created with criteria: BTC gating=None, USD conditions={'Short Term (USD)': ['Strong Bull']}, BTC conditions={'Short Term (BTC)': ['Strong Bull'], 'Overall (BTC)': ['Weak Bull', 'Strong Bull']}, RSI USD=True, RSI BTC=True, volatility filter=True, volatility weight=1, SSR signal=False, SSR gate=False, BTC RSI gate=False, BTC RSI signal=True, Follow portfolio=btc_trend_following, BTC only=False
2025-04-01 15:42:10,886 - WARNING - Portfolio experiment_i already exists. Overwriting.
2025-04-01 15:42:10,887 - INFO - Portfolio 'experiment_i' created with criteria: BTC gating=None, USD conditions={'Short Term (USD)': ['Strong Bear', 'Strong Bull']}, BTC conditions={'Short Term (BTC)': ['Weak Bull', 'Strong Bull'], 'Overall (BTC)': ['Strong Bull']}, RSI USD=True, RSI BTC=True, volatility filter=True, volatility weight=1, SSR signal=False, SSR gate=False, BTC RSI gate=False, BTC RSI signal=False, Follow portfolio=btc_trend_following, BTC only=False
2025-04-01 15:42:10,898 - INFO - Running backtest for followed portfolio 'btc_trend_following'
2025-04-01 15:42:10,941 - INFO - Entering BTC position on 2024-01-08 00:00:00: Cost = 10.00
2025-04-01 15:42:10,943 - INFO - Exiting BTC position on 2024-01-09 00:00:00: Cost = 9.99
2025-04-01 15:42:10,945 - INFO - Entering BTC position on 2024-01-10 00:00:00: Cost = 9.98
2025-04-01 15:42:10,949 - INFO - Exiting BTC position on 2024-01-13 00:00:00: Cost = 9.29
2025-04-01 15:42:10,951 - INFO - Entering BTC position on 2024-01-14 00:00:00: Cost = 9.28
2025-04-01 15:42:10,954 - INFO - Exiting BTC position on 2024-01-16 00:00:00: Cost = 9.24
2025-04-01 15:42:10,964 - INFO - Entering BTC position on 2024-01-30 00:00:00: Cost = 9.23
2025-04-01 15:42:10,982 - INFO - Exiting BTC position on 2024-02-27 00:00:00: Cost = 11.63
2025-04-01 15:42:10,984 - INFO - Entering BTC position on 2024-02-28 00:00:00: Cost = 11.62
2025-04-01 15:42:10,996 - INFO - Exiting BTC position on 2024-03-16 00:00:00: Cost = 14.18
2025-04-01 15:42:11,004 - INFO - Entering BTC position on 2024-03-27 00:00:00: Cost = 14.17
2025-04-01 15:42:11,010 - INFO - Exiting BTC position on 2024-04-03 00:00:00: Cost = 13.24
2025-04-01 15:42:11,030 - INFO - Entering BTC position on 2024-05-06 00:00:00: Cost = 13.23
2025-04-01 15:42:11,058 - INFO - Exiting BTC position on 2024-06-15 00:00:00: Cost = 13.65
2025-04-01 15:42:11,073 - INFO - Entering BTC position on 2024-07-03 00:00:00: Cost = 13.64
2025-04-01 15:42:11,075 - INFO - Exiting BTC position on 2024-07-04 00:00:00: Cost = 13.26
2025-04-01 15:42:11,082 - INFO - Entering BTC position on 2024-07-13 00:00:00: Cost = 13.25
2025-04-01 15:42:11,085 - INFO - Exiting BTC position on 2024-07-15 00:00:00: Cost = 13.96
2025-04-01 15:42:11,088 - INFO - Entering BTC position on 2024-07-17 00:00:00: Cost = 13.94
2025-04-01 15:42:11,102 - INFO - Exiting BTC position on 2024-08-03 00:00:00: Cost = 13.15
2025-04-01 15:42:11,120 - INFO - Entering BTC position on 2024-08-24 00:00:00: Cost = 13.14
2025-04-01 15:42:11,124 - INFO - Exiting BTC position on 2024-08-27 00:00:00: Cost = 12.20
2025-04-01 15:42:11,125 - INFO - Entering BTC position on 2024-08-28 00:00:00: Cost = 12.19
2025-04-01 15:42:11,127 - INFO - Exiting BTC position on 2024-08-29 00:00:00: Cost = 12.27
2025-04-01 15:42:11,132 - INFO - Entering BTC position on 2024-09-03 00:00:00: Cost = 12.26
2025-04-01 15:42:11,135 - INFO - Exiting BTC position on 2024-09-05 00:00:00: Cost = 11.98
2025-04-01 15:42:11,141 - INFO - Entering BTC position on 2024-09-12 00:00:00: Cost = 11.97
2025-04-01 15:42:11,184 - INFO - Exiting BTC position on 2024-11-06 00:00:00: Cost = 15.59
2025-04-01 15:42:11,186 - INFO - Entering BTC position on 2024-11-07 00:00:00: Cost = 15.57
2025-04-01 15:42:11,198 - INFO - Exiting BTC position on 2024-11-25 00:00:00: Cost = 19.08
2025-04-01 15:42:11,201 - INFO - Entering BTC position on 2024-11-26 00:00:00: Cost = 19.06
2025-04-01 15:42:11,219 - INFO - Exiting BTC position on 2024-12-18 00:00:00: Cost = 20.83
2025-04-01 15:42:11,225 - INFO - Entering BTC position on 2024-12-24 00:00:00: Cost = 20.81
2025-04-01 15:42:11,228 - INFO - Exiting BTC position on 2024-12-27 00:00:00: Cost = 19.91
2025-04-01 15:42:11,236 - INFO - Entering BTC position on 2025-01-05 00:00:00: Cost = 19.89
2025-04-01 15:42:11,239 - INFO - Exiting BTC position on 2025-01-08 00:00:00: Cost = 19.23
2025-04-01 15:42:11,240 - INFO - Entering BTC position on 2025-01-09 00:00:00: Cost = 19.21
2025-04-01 15:42:11,242 - INFO - Exiting BTC position on 2025-01-10 00:00:00: Cost = 19.72
2025-04-01 15:42:11,247 - INFO - Entering BTC position on 2025-01-16 00:00:00: Cost = 19.70
2025-04-01 15:42:11,262 - INFO - Exiting BTC position on 2025-02-02 00:00:00: Cost = 19.23
2025-04-01 15:42:11,266 - INFO - Entering BTC position on 2025-02-05 00:00:00: Cost = 19.21
2025-04-01 15:42:11,271 - INFO - Exiting BTC position on 2025-02-11 00:00:00: Cost = 19.09
2025-04-01 15:42:11,299 - INFO - Entering BTC position on 2025-03-15 00:00:00: Cost = 19.07
2025-04-01 15:42:11,323 - INFO - Using signals from BTC-only portfolio 'btc_trend_following'
2025-04-01 15:42:11,807 - INFO - Using signals from BTC-only portfolio 'btc_trend_following'
2025-04-01 15:42:12,127 - INFO - Entering BTC position on 2024-01-08 00:00:00: Cost = 10.00
2025-04-01 15:42:12,129 - INFO - Exiting BTC position on 2024-01-09 00:00:00: Cost = 9.99
2025-04-01 15:42:12,131 - INFO - Entering BTC position on 2024-01-10 00:00:00: Cost = 9.98
2025-04-01 15:42:12,134 - INFO - Exiting BTC position on 2024-01-13 00:00:00: Cost = 9.29
2025-04-01 15:42:12,135 - INFO - Entering BTC position on 2024-01-14 00:00:00: Cost = 9.28
2025-04-01 15:42:12,139 - INFO - Exiting BTC position on 2024-01-16 00:00:00: Cost = 9.24
2025-04-01 15:42:12,149 - INFO - Entering BTC position on 2024-01-30 00:00:00: Cost = 9.23
2025-04-01 15:42:12,168 - INFO - Exiting BTC position on 2024-02-27 00:00:00: Cost = 11.63
2025-04-01 15:42:12,169 - INFO - Entering BTC position on 2024-02-28 00:00:00: Cost = 11.62
2025-04-01 15:42:12,181 - INFO - Exiting BTC position on 2024-03-16 00:00:00: Cost = 14.18
2025-04-01 15:42:12,189 - INFO - Entering BTC position on 2024-03-27 00:00:00: Cost = 14.17
2025-04-01 15:42:12,195 - INFO - Exiting BTC position on 2024-04-03 00:00:00: Cost = 13.24
2025-04-01 15:42:12,217 - INFO - Entering BTC position on 2024-05-06 00:00:00: Cost = 13.23
2025-04-01 15:42:12,244 - INFO - Exiting BTC position on 2024-06-15 00:00:00: Cost = 13.65
2025-04-01 15:42:12,256 - INFO - Entering BTC position on 2024-07-03 00:00:00: Cost = 13.64
2025-04-01 15:42:12,258 - INFO - Exiting BTC position on 2024-07-04 00:00:00: Cost = 13.26
2025-04-01 15:42:12,264 - INFO - Entering BTC position on 2024-07-13 00:00:00: Cost = 13.25
2025-04-01 15:42:12,267 - INFO - Exiting BTC position on 2024-07-15 00:00:00: Cost = 13.96
2025-04-01 15:42:12,269 - INFO - Entering BTC position on 2024-07-17 00:00:00: Cost = 13.94
2025-04-01 15:42:12,282 - INFO - Exiting BTC position on 2024-08-03 00:00:00: Cost = 13.15
2025-04-01 15:42:12,302 - INFO - Entering BTC position on 2024-08-24 00:00:00: Cost = 13.14
2025-04-01 15:42:12,305 - INFO - Exiting BTC position on 2024-08-27 00:00:00: Cost = 12.20
2025-04-01 15:42:12,307 - INFO - Entering BTC position on 2024-08-28 00:00:00: Cost = 12.19
2025-04-01 15:42:12,308 - INFO - Exiting BTC position on 2024-08-29 00:00:00: Cost = 12.27
2025-04-01 15:42:12,314 - INFO - Entering BTC position on 2024-09-03 00:00:00: Cost = 12.26
2025-04-01 15:42:12,317 - INFO - Exiting BTC position on 2024-09-05 00:00:00: Cost = 11.98
2025-04-01 15:42:12,324 - INFO - Entering BTC position on 2024-09-12 00:00:00: Cost = 11.97
2025-04-01 15:42:12,372 - INFO - Exiting BTC position on 2024-11-06 00:00:00: Cost = 15.59
2025-04-01 15:42:12,373 - INFO - Entering BTC position on 2024-11-07 00:00:00: Cost = 15.57
2025-04-01 15:42:12,388 - INFO - Exiting BTC position on 2024-11-25 00:00:00: Cost = 19.08
2025-04-01 15:42:12,389 - INFO - Entering BTC position on 2024-11-26 00:00:00: Cost = 19.06
2025-04-01 15:42:12,407 - INFO - Exiting BTC position on 2024-12-18 00:00:00: Cost = 20.83
2025-04-01 15:42:12,412 - INFO - Entering BTC position on 2024-12-24 00:00:00: Cost = 20.81
2025-04-01 15:42:12,415 - INFO - Exiting BTC position on 2024-12-27 00:00:00: Cost = 19.91
2025-04-01 15:42:12,424 - INFO - Entering BTC position on 2025-01-05 00:00:00: Cost = 19.89
2025-04-01 15:42:12,427 - INFO - Exiting BTC position on 2025-01-08 00:00:00: Cost = 19.23
2025-04-01 15:42:12,428 - INFO - Entering BTC position on 2025-01-09 00:00:00: Cost = 19.21
2025-04-01 15:42:12,430 - INFO - Exiting BTC position on 2025-01-10 00:00:00: Cost = 19.72
2025-04-01 15:42:12,435 - INFO - Entering BTC position on 2025-01-16 00:00:00: Cost = 19.70
2025-04-01 15:42:12,447 - INFO - Exiting BTC position on 2025-02-02 00:00:00: Cost = 19.23
2025-04-01 15:42:12,450 - INFO - Entering BTC position on 2025-02-05 00:00:00: Cost = 19.21
2025-04-01 15:42:12,456 - INFO - Exiting BTC position on 2025-02-11 00:00:00: Cost = 19.09
2025-04-01 15:42:12,480 - INFO - Entering BTC position on 2025-03-15 00:00:00: Cost = 19.07

In [18]:


# Plot performance for a specific date range
fig = analyzer.plot_individual_asset_performance(
    portfolio_name='big_wins_i',
    btc_trend_portfolio_name='btc_trend_following',
    start_date=start_date,
    end_date=end_date,
    initial_capital=10000,
    show_plot=True,
   #asset_filter=['SOL']
)

2025-04-01 15:42:12,499 - INFO - Recalculating backtest for portfolio 'big_wins_i' from 2024-01-1 to 2025-03-30.
2025-04-01 15:42:12,510 - INFO - Using signals from BTC-only portfolio 'btc_trend_following'
2025-04-01 15:42:12,864 - INFO - Recalculating backtest for portfolio 'btc_trend_following' from 2024-01-1 to 2025-03-30.
2025-04-01 15:42:12,872 - INFO - Entering BTC position on 2024-01-08 00:00:00: Cost = 10.00
2025-04-01 15:42:12,874 - INFO - Exiting BTC position on 2024-01-09 00:00:00: Cost = 9.99
2025-04-01 15:42:12,875 - INFO - Entering BTC position on 2024-01-10 00:00:00: Cost = 9.98
2025-04-01 15:42:12,879 - INFO - Exiting BTC position on 2024-01-13 00:00:00: Cost = 9.29
2025-04-01 15:42:12,880 - INFO - Entering BTC position on 2024-01-14 00:00:00: Cost = 9.28
2025-04-01 15:42:12,883 - INFO - Exiting BTC position on 2024-01-16 00:00:00: Cost = 9.24
2025-04-01 15:42:12,893 - INFO - Entering BTC position on 2024-01-30 00:00:00: Cost = 9.23
2025-04-01 15:42:12,914 - INFO - Exiting BTC position on 2024-02-27 00:00:00: Cost = 11.63
2025-04-01 15:42:12,916 - INFO - Entering BTC position on 2024-02-28 00:00:00: Cost = 11.62
2025-04-01 15:42:12,929 - INFO - Exiting BTC position on 2024-03-16 00:00:00: Cost = 14.18
2025-04-01 15:42:12,938 - INFO - Entering BTC position on 2024-03-27 00:00:00: Cost = 14.17
2025-04-01 15:42:12,944 - INFO - Exiting BTC position on 2024-04-03 00:00:00: Cost = 13.24
2025-04-01 15:42:12,968 - INFO - Entering BTC position on 2024-05-06 00:00:00: Cost = 13.23
2025-04-01 15:42:12,998 - INFO - Exiting BTC position on 2024-06-15 00:00:00: Cost = 13.65
2025-04-01 15:42:13,011 - INFO - Entering BTC position on 2024-07-03 00:00:00: Cost = 13.64
2025-04-01 15:42:13,012 - INFO - Exiting BTC position on 2024-07-04 00:00:00: Cost = 13.26
2025-04-01 15:42:13,019 - INFO - Entering BTC position on 2024-07-13 00:00:00: Cost = 13.25
2025-04-01 15:42:13,022 - INFO - Exiting BTC position on 2024-07-15 00:00:00: Cost = 13.96
2025-04-01 15:42:13,026 - INFO - Entering BTC position on 2024-07-17 00:00:00: Cost = 13.94
2025-04-01 15:42:13,040 - INFO - Exiting BTC position on 2024-08-03 00:00:00: Cost = 13.15
2025-04-01 15:42:13,058 - INFO - Entering BTC position on 2024-08-24 00:00:00: Cost = 13.14
2025-04-01 15:42:13,061 - INFO - Exiting BTC position on 2024-08-27 00:00:00: Cost = 12.20
2025-04-01 15:42:13,062 - INFO - Entering BTC position on 2024-08-28 00:00:00: Cost = 12.19
2025-04-01 15:42:13,064 - INFO - Exiting BTC position on 2024-08-29 00:00:00: Cost = 12.27
2025-04-01 15:42:13,068 - INFO - Entering BTC position on 2024-09-03 00:00:00: Cost = 12.26
2025-04-01 15:42:13,071 - INFO - Exiting BTC position on 2024-09-05 00:00:00: Cost = 11.98
2025-04-01 15:42:13,078 - INFO - Entering BTC position on 2024-09-12 00:00:00: Cost = 11.97
2025-04-01 15:42:13,118 - INFO - Exiting BTC position on 2024-11-06 00:00:00: Cost = 15.59
2025-04-01 15:42:13,120 - INFO - Entering BTC position on 2024-11-07 00:00:00: Cost = 15.57
2025-04-01 15:42:13,135 - INFO - Exiting BTC position on 2024-11-25 00:00:00: Cost = 19.08
2025-04-01 15:42:13,137 - INFO - Entering BTC position on 2024-11-26 00:00:00: Cost = 19.06
2025-04-01 15:42:13,156 - INFO - Exiting BTC position on 2024-12-18 00:00:00: Cost = 20.83
2025-04-01 15:42:13,162 - INFO - Entering BTC position on 2024-12-24 00:00:00: Cost = 20.81
2025-04-01 15:42:13,166 - INFO - Exiting BTC position on 2024-12-27 00:00:00: Cost = 19.91
2025-04-01 15:42:13,175 - INFO - Entering BTC position on 2025-01-05 00:00:00: Cost = 19.89
2025-04-01 15:42:13,178 - INFO - Exiting BTC position on 2025-01-08 00:00:00: Cost = 19.23
2025-04-01 15:42:13,180 - INFO - Entering BTC position on 2025-01-09 00:00:00: Cost = 19.21
2025-04-01 15:42:13,181 - INFO - Exiting BTC position on 2025-01-10 00:00:00: Cost = 19.72
2025-04-01 15:42:13,187 - INFO - Entering BTC position on 2025-01-16 00:00:00: Cost = 19.70
2025-04-01 15:42:13,201 - INFO - Exiting BTC position on 2025-02-02 00:00:00: Cost = 19.23
2025-04-01 15:42:13,205 - INFO - Entering BTC position on 2025-02-05 00:00:00: Cost = 19.21
2025-04-01 15:42:13,212 - INFO - Exiting BTC position on 2025-02-11 00:00:00: Cost = 19.09
2025-04-01 15:42:13,235 - INFO - Entering BTC position on 2025-03-15 00:00:00: Cost = 19.07

Performance Metrics:
BTC Buy & Hold: Return = 86.46%, Max Drawdown = -26.23%
BTC Trend (btc_trend_following): Return = 87.26%, Max Drawdown = -19.76%

Individual Asset Performance:

|     | Total Return   | Max Drawdown   |   Sharpe Ratio |   Sortino Ratio |   Number of Trades | Win Rate   | Avg Win   | Avg Loss   |   Avg Holding Days | Total Costs   | First Trade         | Last Trade          |   Trading Days |
|:----|:---------------|:---------------|---------------:|----------------:|-------------------:|:-----------|:----------|:-----------|-------------------:|:--------------|:--------------------|:--------------------|---------------:|
| ETH | -0.53%         | -23.29%        |            5.5 |           13.48 |                 14 | 35.71%     | 3.30%     | -1.81%     |                3.8 | $1,435.62     | 2024-01-13 00:00:00 | 2024-12-16 00:00:00 |             53 |

Detailed Trade History:

ETH Trades:
|   trade_id | entry_date          | exit_date           |   holding_days |   entry_price |   exit_price | price_return   |   entry_value |   entry_cost |   exit_value |   exit_cost | trade_return   | is_open   |
|-----------:|:--------------------|:--------------------|---------------:|--------------:|-------------:|:---------------|--------------:|-------------:|-------------:|------------:|:---------------|:----------|
|          1 | 2024-01-13 00:00:00 | 2024-01-15 00:00:00 |              2 |       2575.92 |      2515.32 | -2.35%         |       9950    |     -50      |      9667.34 |    -48.5796 | -3.33%         | False     |
|          2 | 2024-01-31 00:00:00 | 2024-02-01 00:00:00 |              1 |       2282.49 |      2301.74 | 0.84%          |       9619    |     -48.3367 |      9651.63 |    -48.5006 | -0.16%         | False     |
|          3 | 2024-02-21 00:00:00 | 2024-02-26 00:00:00 |              5 |       2977.08 |      3173.63 | 6.60%          |       9603.37 |     -48.2581 |     10186.2  |    -51.187  | 5.54%          | False     |
|          4 | 2024-02-29 00:00:00 | 2024-03-04 00:00:00 |              4 |       3347.69 |      3634.31 | 8.56%          |      10135.3  |     -50.931  |     10948    |    -55.0152 | 7.48%          | False     |
|          5 | 2024-03-06 00:00:00 | 2024-03-14 00:00:00 |              8 |       3822.37 |      3879.04 | 1.48%          |      10893.3  |     -54.7401 |     10999.5  |    -55.2739 | 0.47%          | False     |
|          6 | 2024-05-21 00:00:00 | 2024-05-30 00:00:00 |              9 |       3792.49 |      3748.64 | -1.16%         |      10944.5  |     -54.9975 |     10763.9  |    -54.0898 | -2.14%         | False     |
|          7 | 2024-06-01 00:00:00 | 2024-06-02 00:00:00 |              1 |       3813.45 |      3780.71 | -0.86%         |      10710.1  |     -53.8194 |     10565    |    -53.0905 | -1.85%         | False     |
|          8 | 2024-06-03 00:00:00 | 2024-06-07 00:00:00 |              4 |       3766.64 |      3679.38 | -2.32%         |      10512.2  |     -52.8251 |     10217.3  |    -51.3433 | -3.29%         | False     |
|          9 | 2024-07-12 00:00:00 | 2024-07-13 00:00:00 |              1 |       3132.98 |      3173.5  | 1.29%          |      10166.2  |     -51.0866 |     10246.2  |    -51.4886 | 0.28%          | False     |
|         10 | 2024-10-15 00:00:00 | 2024-10-17 00:00:00 |              2 |       2602.08 |      2603.12 | 0.04%          |      10195    |     -51.2311 |     10148.1  |    -50.9953 | -0.96%         | False     |
|         11 | 2024-11-25 00:00:00 | 2024-11-26 00:00:00 |              1 |       3417.29 |      3325.64 | -2.68%         |      10097.3  |     -50.7404 |      9777.39 |    -49.1326 | -3.65%         | False     |
|         12 | 2024-11-28 00:00:00 | 2024-12-09 00:00:00 |             11 |       3579.24 |      3713.31 | 3.75%          |       9728.51 |     -48.887  |     10042.4  |    -50.4646 | 2.71%          | False     |
|         13 | 2024-12-12 00:00:00 | 2024-12-13 00:00:00 |              1 |       3878.85 |      3907.43 | 0.74%          |       9992.24 |     -50.2122 |     10015.5  |    -50.3293 | -0.27%         | False     |
|         14 | 2024-12-14 00:00:00 | 2024-12-17 00:00:00 |              3 |       3867    |      3879.41 | 0.32%          |       9965.45 |     -50.0777 |      9947.45 |    -49.9872 | -0.68%         | False     |

In [12]:
results_btc.get('metrics')

{'total_return': 0.872596158079114,
 'max_drawdown': -0.19761513866009545,
 'initial_capital': 10000,
 'final_value': 18725.96158079114,
 'sharpe_ratio': 1.5375535760838357,
 'sortino_ratio': 2.0642516198562553}

In [23]:
data = results_btc.get('signals_df')
data[data.index >= '2024-09-10'].head(15)

,asset,usd_trend_signal,btc_trend_signal,rsi_usd_signal,rsi_btc_signal,volatility_signal,ssr_signal,ssr_gate,btc_gate,btc_rsi_gate,btc_rsi_signal,followed_portfolio_signal,combined_signal,final_decision
date,,,,,,,,,,,,,,
2024-09-10,BTC,1,None,-1,None,1,-1,None,None,None,None,None,0,0
2024-09-11,BTC,1,None,-1,None,1,1,None,None,None,None,None,2,1
2024-09-12,BTC,1,None,1,None,1,1,None,None,None,None,None,4,1
2024-09-13,BTC,1,None,1,None,1,1,None,None,None,None,None,4,1
2024-09-14,BTC,1,None,1,None,1,1,None,None,None,None,None,4,1
2024-09-15,BTC,1,None,-1,None,1,1,None,None,None,None,None,2,1
2024-09-16,BTC,1,None,-1,None,1,1,None,None,None,None,None,2,1
2024-09-17,BTC,1,None,-1,None,1,1,None,None,None,None,None,2,1
2024-09-18,BTC,1,None,1,None,1,1,None,None,None,None,None,4,1
2024-09-19,BTC,1,None,-1,None,1,1,None,None,None,None,None,2,1
2024-09-20,BTC,1,None,-1,None,1,1,None,None,None,None,None,2,1
2024-09-21,BTC,1,None,-1,None,1,1,None,None,None,None,None,2,1
2024-09-22,BTC,1,None,1,None,1,1,None,None,None,None,None,4,1
2024-09-23,BTC,1,None,1,None,1,1,None,None,None,None,None,4,1
2024-09-24,BTC,1,None,1,None,1,1,None,None,None,None,None,4,1

In [ ]:
# Plot performance for a specific date range
fig = analyzer.plot_individual_asset_performance(
    portfolio_name='big_wins_i',
    btc_trend_portfolio_name='btc_trend_following',
    start_date=start_date,
    end_date=end_date,
    initial_capital=10000,
    show_plot=False,
   # asset_filter=['SOL']
)

In [ ]:
analyzer.asset_data['ethereum'].get('classified_data')

In [13]:
def analyze_signal_vs_returns(analyzer, portfolio_name='big_wins_i', asset_to_analyze='ETH', forward_days=5, start_date='2020-01-01'):
    """
    Analyze the relationship between trading signals and forward returns for a specific asset.
    
    Parameters:
    -----------
    analyzer : object
        The analyzer object with portfolio data
    portfolio_name : str
        Name of the portfolio to analyze
    asset_to_analyze : str
        Asset symbol to analyze (e.g., 'ETH', 'BTC')
    forward_days : int
        Number of days for forward returns (1, 5, or 7)
    start_date : str
        Start date for the analysis in 'YYYY-MM-DD' format
        
    Returns:
    --------
    fig : matplotlib.figure.Figure
        The figure containing the plots
    """
    # Get the signals dataframe
    results_df = analyzer.get_portfolio_details(portfolio_name=portfolio_name).get('backtest_results').get('signals_df')

    # Asset name mapping
    asset_name_map = {
        'ETH': 'ethereum',
        'BTC': 'bitcoin',
        'BNB': 'binancecoin',
        'XRP': 'ripple',
        'ADA': 'cardano',
        'SOL': 'solana',
        'DOGE': 'dogecoin',
        'DOT': 'polkadot',
        'AVAX': 'avalanche-2',
        'LINK': 'chainlink',
        'MATIC': 'matic-network'
    }

    # Filter signals for the chosen asset
    if results_df is not None and not results_df.empty:
        asset_data = results_df[results_df['asset'] == asset_to_analyze].copy()
        
        # Try to get price data from analyzer using the correct mapping
        try:
            asset_key = asset_name_map.get(asset_to_analyze, asset_to_analyze.lower())
            if asset_key in analyzer.asset_data and analyzer.asset_data[asset_key] is not None:
                # Get raw price data
                asset_price_data = analyzer.asset_data[asset_key].get('raw_data')
                
                if asset_price_data is not None:
                    # Calculate forward returns for the specified period
                    asset_price_data = asset_price_data.copy()
                    asset_price_data['daily_return'] = asset_price_data['close'].pct_change() * 100  # Convert to percentage
                    
                    # Calculate forward returns (1-day, 5-day, 7-day)
                    for days in [1, 3, 5, 7, 14]:
                        asset_price_data[f'forward_{days}d_return'] = asset_price_data['close'].shift(-days) / asset_price_data['close'] - 1
                        asset_price_data[f'forward_{days}d_return'] = asset_price_data[f'forward_{days}d_return'] * 100  # Convert to percentage
                    
                    # Merge signals with returns
                    asset_data = asset_data.reset_index()
                    asset_data['date'] = pd.to_datetime(asset_data['date'])
                    asset_price_data['date'] = pd.to_datetime(asset_price_data['date'])
                    
                    merged_data = asset_data.merge(
                        asset_price_data[['date', 'daily_return'] + [f'forward_{days}d_return' for days in [1, 3, 5, 7, 14]]], 
                        on='date', 
                        how='left'
                    ).set_index('date')
                else:
                    asset_data['daily_return'] = 0
                    for days in [1, 3, 5, 7, 14]:
                        asset_data[f'forward_{days}d_return'] = 0
                    merged_data = asset_data
            else:
                asset_data['daily_return'] = 0
                for days in [1, 3, 5, 7, 14]:
                    asset_data[f'forward_{days}d_return'] = 0
                merged_data = asset_data
        except Exception as e:
            asset_data['daily_return'] = 0
            for days in [1, 3, 5, 7, 14]:
                asset_data[f'forward_{days}d_return'] = 0
            merged_data = asset_data
        
        # Create violin plots for each signal type vs returns
        import matplotlib.pyplot as plt
        import seaborn as sns

        merged_data = merged_data[merged_data.index >= start_date]
        
        # Define signal columns to plot
        signal_columns = [
            'usd_trend_signal', 'btc_trend_signal', 'rsi_usd_signal',
            'rsi_btc_signal', 'volatility_signal', 'combined_signal', 'final_decision'
        ]
        
        # Filter to only include columns that exist in the data
        signal_columns = [col for col in signal_columns if col in merged_data.columns]
        
        # Set up the figure with a clean style
        plt.style.use('seaborn-v0_8-whitegrid')
        
        # Create a single figure with subplots
        fig, axes = plt.subplots(2, 3, figsize=(18, 12), constrained_layout=True)
        axes = axes.flatten()
        
        # Select the return column based on forward_days
        return_column = f'forward_{forward_days}d_return'
        
        # Create violin plots
        for i, signal in enumerate(signal_columns):
            if i < len(axes):
                # Filter out None and NaN values
                plot_data = merged_data[merged_data[signal].notna() & merged_data[return_column].notna()].copy()
                
                # Convert signal to numeric if possible
                try:
                    plot_data[signal] = pd.to_numeric(plot_data[signal])
                except:
                    pass
                
                # Create violin plot
                sns.violinplot(
                    data=plot_data, 
                    x=signal, 
                    y=return_column,
                    ax=axes[i],
                    inner='quartile',  # Show quartiles inside violin
                    palette='viridis'
                )
                
                # Add individual points for better visualization
                sns.stripplot(
                    data=plot_data, 
                    x=signal, 
                    y=return_column,
                    ax=axes[i],
                    color='black',
                    alpha=0.3,
                    size=2,
                    jitter=True
                )
                
                # Improve aesthetics
                axes[i].set_title(f'{signal} vs {forward_days}-Day Forward Return for {asset_to_analyze}', fontsize=12, fontweight='bold')
                axes[i].axhline(y=0, color='r', linestyle='--', alpha=0.5)
                axes[i].set_xlabel(signal, fontsize=10)
                axes[i].set_ylabel(f'{forward_days}-Day Forward Return (%)', fontsize=10)
                
                # Rotate x-axis labels if there are many unique values
                if len(plot_data[signal].unique()) > 5:
                    axes[i].tick_params(axis='x', rotation=45)
        
        # Hide any unused subplots
        for j in range(len(signal_columns), len(axes)):
            axes[j].set_visible(False)
        
        # Add a title to the entire figure
        fig.suptitle(f'Signal vs {forward_days}-Day Forward Return Analysis for {asset_to_analyze}', fontsize=16, fontweight='bold', y=1.02)
        
        plt.tight_layout()
        return fig
    
    return None

# Example usage:
# fig = analyze_signal_vs_returns(analyzer, portfolio_name='big_wins_i', asset_to_analyze='ETH', forward_days=5)
# plt.show()

In [ ]:
fig_link = analyze_signal_vs_returns(analyzer, portfolio_name='big_wins_i', asset_to_analyze='LINK', forward_days=3, start_date='2020-01-01')
fig_sol = analyze_signal_vs_returns(analyzer, portfolio_name='big_wins_i', asset_to_analyze='SOL', forward_days=3, start_date='2020-01-01')
fig_eth = analyze_signal_vs_returns(analyzer, portfolio_name='big_wins_i', asset_to_analyze='ETH', forward_days=3, start_date='2020-01-01')
fig_ada = analyze_signal_vs_returns(analyzer, portfolio_name='big_wins_i', asset_to_analyze='ADA', forward_days=3, start_date='2020-01-01')
fig_matic = analyze_signal_vs_returns(analyzer, portfolio_name='big_wins_i', asset_to_analyze='MATIC', forward_days=3, start_date='2020-01-01')
fig_avax = analyze_signal_vs_returns(analyzer, portfolio_name='big_wins_i', asset_to_analyze='AVAX', forward_days=3, start_date='2020-01-01')
fig_bnb = analyze_signal_vs_returns(analyzer, portfolio_name='big_wins_i', asset_to_analyze='BNB', forward_days=3, start_date='2020-01-01')

In [ ]:
def get_signals_for_period(start_date, end_date, assets='all'):
    results_df = analyzer.get_portfolio_details(portfolio_name='altcoins_trend_following_btc').get('backtest_results').get('signals_df')
    
    # Filter by date range
    signals = results_df[(results_df.index >= start_date) & (results_df.index <= end_date)]
    
    # Filter by assets if specified
    if assets != 'all':
        if isinstance(assets, str):
            assets = [assets]
        signals = signals[signals['asset'].isin(assets)]
        
    return signals

# Example usage:
start_date = '2024-7-31'
end_date = '2025-3-25' 

assets = ['ETH']  # or 'all' for all assets
#assets = 'all'
signals = get_signals_for_period(start_date, end_date, assets)
signals[(signals['followed_portfolio_signal'] == 1) & (signals['final_decision'] == 0)]

In [ ]:
assets_held = analyzer.get_portfolio_details(portfolio_name='btc_gated_rsi_vol_momentum').get('backtest_results').get('results_df')
assets_held

import matplotlib.pyplot as plt

# Get the results dataframe

# Create the plot
plt.figure(figsize=(14, 6))

# Plot the assets held line
plt.plot(assets_held.index, assets_held['Assets_Held'], 'b-')

# Add vertical lines for each month
for date in assets_held.index[assets_held.index.is_month_start]:
    plt.axvline(x=date, color='gray', alpha=0.3, linestyle='--')

plt.title('Assets Held Over Time')
plt.ylabel('Number of Assets')
plt.grid(True, alpha=0.3)
plt.xticks(rotation=45)
plt.tight_layout()

In [ ]:
test_criteria = [{'Short Term (USD)': ['Strong Bull'],
                  'Short Term (BTC)': ['Strong Bull'],
                  'Overall (BTC)': ['Strong Bull']},
                  
                 {'Short Term (BTC)': ['Strong Bull'],
                  'Short Term (USD)': ['Weak Bull', 'Strong Bull']}]

In [ ]:
btc_data = analyzer.asset_data['maker'].get('classified_data')[['date', 'Short Term (USD)', 'Overall (USD)', 'RSI_Signal_close']]
btc_data[btc_data['date'] == data]

In [ ]:
results_df = analyzer.get_portfolio_details(portfolio_name='altcoins_trend_following_btc').get('backtest_results')
results_df

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.gridspec import GridSpec

# Define the assets we want to analyze
assets = {
    'BTC': 'bitcoin',
    'ETH': 'ethereum', 
    'SOL': 'solana',
    'BNB': 'binancecoin',
    'LINK': 'chainlink',
    'AVAX': 'avalanche-2'
}

# Function to plot the relationship between trend signals and forward returns
def plot_trend_signal_returns(asset_name, forward_days=7):
    # Get the data for the selected asset
    asset_data = analyzer.asset_data[asset_name].get('classified_data').copy()
    
    # Calculate forward returns
    asset_data[f'forward_returns_{forward_days}d'] = asset_data['returns_usd'].rolling(window=forward_days).sum().shift(-forward_days)
    
    # Drop NaN values
    asset_data = asset_data.dropna(subset=[f'forward_returns_{forward_days}d'])
    
    # Define the trend signals to analyze
    trend_signals = ['Short Term (USD)', 'Medium Term (USD)', 'Overall (USD)', 
                     'Short Term (BTC)', 'Medium Term (BTC)', 'Overall (BTC)']
    
    # Create a figure with subplots for each trend signal
    fig = plt.figure(figsize=(20, 30))
    gs = GridSpec(len(trend_signals), 1, figure=fig)
    
    # Plot each trend signal
    for i, signal in enumerate(trend_signals):
        if signal in asset_data.columns:
            ax = fig.add_subplot(gs[i, 0])
            
            # Create violin plot
            sns.violinplot(x=signal, y=f'forward_returns_{forward_days}d', data=asset_data, 
                          palette='coolwarm', inner='quartile', ax=ax, alpha=0.7)
            
            # Add swarm plot with reduced size and transparency
            sns.swarmplot(x=signal, y=f'forward_returns_{forward_days}d', data=asset_data, 
                         color='black', size=2, alpha=0.1, ax=ax)
            
            # Add a horizontal line at y=0
            ax.axhline(y=0, color='gray', linestyle='--', alpha=0.7)
            
            # Set title and labels
            ax.set_title(f'{signal} vs {forward_days}-Day Forward Returns for {asset_name}', fontsize=14)
            ax.set_ylabel(f'{forward_days}-Day Forward Returns', fontsize=12)
            ax.set_xlabel(signal, fontsize=12)
            
            # Rotate x-axis labels for better readability
            plt.setp(ax.get_xticklabels(), rotation=45, ha='right')
    
    plt.tight_layout()
    plt.subplots_adjust(hspace=0.3)
    return fig

In [ ]:
plot_trend_signal_returns('solana', forward_days=7)

In [ ]:
import pandas as pd
import plotly.graph_objects as go
import numpy as np

# Get returns data for all assets
assets = {
    'BTC': 'bitcoin',
    'ETH': 'ethereum', 
    'SOL': 'solana',
    'BNB': 'binancecoin',
    'LINK': 'chainlink',
    'AVAX': 'avalanche-2'
}

# Create dataframe with returns for all assets
returns_df = pd.DataFrame()
for symbol, name in assets.items():
    data = analyzer.asset_data.get(name).get('classified_data')[['date','returns_usd']]
    data.set_index('date', inplace=True)
    returns_df[symbol] = data['returns_usd']

returns_df.dropna(inplace=True)

# Calculate rolling correlations against BTC
window_size = 14  # Using a 30-day window for better visualization
corr_df = pd.DataFrame(index=returns_df.index)

for col in returns_df.columns:
    if col != 'BTC':
        # Calculate rolling correlation between this asset and BTC
        corr = returns_df['BTC'].rolling(window=window_size).corr(returns_df[col])
        corr_df[col] = corr

# Drop NaN values (first window_size-1 rows will be NaN)
corr_df.dropna(inplace=True)

# Create the heatmap using plotly
asset_list = [col for col in corr_df.columns]
dates = corr_df.index

# Create the heatmap
fig = go.Figure(data=go.Heatmap(
    z=corr_df.values.T,  # Transpose to get assets on y-axis
    x=dates,
    y=asset_list,
    colorscale='RdBu_r',  # Red-Blue diverging colorscale
    zmid=0,  # Center the colorscale at 0
    zmin=-1,
    zmax=1,
    colorbar=dict(
        title=f"{window_size}-day Rolling Correlation with BTC",
        titleside="right"
    )
))

# Update layout
fig.update_layout(
    title=f"Rolling {window_size}-day Correlation of Assets with BTC",
    xaxis_title="Date",
    yaxis_title="Asset",
    height=600,
    width=1000,
    yaxis=dict(
        tickmode='array',
        tickvals=asset_list
    ),
    xaxis=dict(
        rangeslider=dict(visible=True),
        type='date'
    ),
    annotations=[
        dict(
            x=0.5,
            y=-0.15,
            xref="paper",
            yref="paper",
            text="Blue = negative correlation, Red = positive correlation with BTC",
            showarrow=False,
            font=dict(size=12)
        )
    ]
)

# Show the figure
fig.show()