In [18]:
# Simple, clean approach with the unified interface
from soros_system.core.portfolio_analyzer import PortfolioAnalyzer
from scripts.assetsRoster import carteira_AC, carteira_HB, others, carteira_EXC, carteira_LC
import warnings

warnings.filterwarnings('ignore')

#assets = carteira_AC
assets = set(carteira_AC+carteira_HB+carteira_EXC+carteira_LC+others)
#assets=['bitcoin', 'ethereum', 'solana', 'dogecoin', 'chainlink', 'pendle']
#assets = ['bitcoin','dogecoin', 'pepe', 'spx', 'floki', 'fartcoin', 'bertram-the-pomeranian', 'fwog', 'neiro-3',
#          'evan-2', 'mubarak', 'baby-doge-coin', 'chill-guy', 'book-of-meme', 'slerf', 'shiba-inu', 
#          'official-trump', 'dogwifcoin', 'mog-coin', 'new-xai-gork', 'grok-2', 'bonk', 'goatseus-maximus',
#          'alchemist-ai', 'harrypotterobamasonic10in', 'kekius-maximus', 'aixbt', 'ava-ai', 'tokenbot-2',
#          'arbdoge-ai', 'based-brett', 'dog-go-to-the-moon-rune', 'siren-2', 'apu-s-club', 'turbo', 
#          'cat-in-a-dogs-world', 'snek', 'ai16z']`


analyzer = PortfolioAnalyzer( 
    data_dir='/Users/valter.rebelo/MissionControl/data',
    data_path='/Users/valter.rebelo/MissionControl/data/micro/candleData/',
    btc_data_path='/Users/valter.rebelo/MissionControl/data/micro/candleData/bitcoin_candles.csv',
    ssr_data_path='/Users/valter.rebelo/MissionControl/data/onchainData/BTC_SSR.csv',
    market_data_path='/Users/valter.rebelo/MissionControl/data/micro/assetData/',
    asset_ids=assets

)

# Load assets - the analyzer handles paths internally

analyzer.load_data(assets=assets, start_date='2014-01-01', end_date='2025-12-31')

INFO: Created portfolios directory: portfolios

Loading assets:   0%|          | 0/218 [00:00<?, ?it/s]

INFO: Successfully loaded data for neiro-3 with 362 rows.
INFO: Successfully loaded data for dogwifcoin with 594 rows.
INFO: Successfully loaded data for tezos with 2585 rows.
INFO: Loaded data for neiro-3 with 362 rows

Loading assets:   0%|          | 1/218 [00:01<04:49,  1.33s/it]

INFO: Loaded data for dogwifcoin with 594 rows
INFO: Loaded data for tezos with 2585 rows
INFO: Successfully loaded data for quant-network with 2587 rows.
INFO: Loaded data for quant-network with 2587 rows
INFO: Successfully loaded data for axie-infinity with 1728 rows.
INFO: Loaded data for axie-infinity with 1728 rows
INFO: Successfully loaded data for fartcoin with 282 rows.
INFO: Loaded data for fartcoin with 282 rows

Loading assets:   3%|▎         | 6/218 [00:01<00:39,  5.34it/s]

INFO: Successfully loaded data for moonwell-artemis with 1132 rows.
INFO: Loaded data for moonwell-artemis with 1132 rows
INFO: Successfully loaded data for dodo with 1763 rows.
INFO: Successfully loaded data for heyanon with 214 rows.
INFO: Successfully loaded data for grok-2 with 630 rows.
INFO: Successfully loaded data for hyperliquid with 243 rows.
INFO: Loaded data for dodo with 1763 rows
INFO: Loaded data for heyanon with 214 rows

Loading assets:   4%|▍         | 9/218 [00:01<00:30,  6.94it/s]

INFO: Loaded data for grok-2 with 630 rows
INFO: Loaded data for hyperliquid with 243 rows
INFO: Successfully loaded data for coredaoorg with 902 rows.
INFO: Loaded data for coredaoorg with 902 rows
INFO: Successfully loaded data for optimism with 1155 rows.
INFO: Loaded data for optimism with 1155 rows
INFO: Successfully loaded data for yearn-finance with 1837 rows.
INFO: Loaded data for yearn-finance with 1837 rows

Loading assets:   6%|▋         | 14/218 [00:01<00:17, 11.53it/s]

INFO: Successfully loaded data for aixbt with 253 rows.
INFO: Loaded data for aixbt with 253 rows
INFO: Successfully loaded data for illuvium with 1581 rows.
INFO: Loaded data for illuvium with 1581 rows
INFO: Successfully loaded data for alchemist-ai with 240 rows.
INFO: Loaded data for alchemist-ai with 240 rows

Loading assets:   8%|▊         | 17/218 [00:01<00:14, 13.81it/s]

INFO: Successfully loaded data for ondo-finance with 558 rows.
INFO: Loaded data for ondo-finance with 558 rows
INFO: Successfully loaded data for havven with 2688 rows.
INFO: Loaded data for havven with 2688 rows
INFO: Successfully loaded data for fetch-ai with 2343 rows.
INFO: Successfully loaded data for ronin with 1279 rows.
INFO: Loaded data for fetch-ai with 2343 rows

Loading assets:   9%|▉         | 20/218 [00:02<00:27,  7.21it/s]

INFO: Loaded data for ronin with 1279 rows
INFO: Successfully loaded data for dusk-network with 2215 rows.
INFO: Loaded data for dusk-network with 2215 rows
INFO: Successfully loaded data for omisego with 2935 rows.

Loading assets:  10%|█         | 22/218 [00:03<00:25,  7.60it/s]

INFO: Loaded data for omisego with 2935 rows
INFO: Successfully loaded data for acala with 1281 rows.
INFO: Successfully loaded data for band-protocol with 2141 rows.
INFO: Successfully loaded data for gala with 1777 rows.
INFO: Loaded data for acala with 1281 rows
INFO: Loaded data for band-protocol with 2141 rows

Loading assets:  11%|█▏        | 25/218 [00:03<00:20,  9.43it/s]

INFO: Loaded data for gala with 1777 rows
INFO: Successfully loaded data for bitcoin with 4475 rows.
INFO: Loaded data for bitcoin with 4475 rows

Loading assets:  12%|█▏        | 27/218 [00:03<00:21,  8.94it/s]

INFO: Successfully loaded data for multibit with 617 rows.
INFO: Loaded data for multibit with 617 rows
INFO: Successfully loaded data for stellar with 4010 rows.
INFO: Loaded data for stellar with 4010 rows

Loading assets:  13%|█▎        | 29/218 [00:03<00:19,  9.85it/s]

INFO: Successfully loaded data for uniswap with 1776 rows.
INFO: Loaded data for uniswap with 1776 rows
INFO: Successfully loaded data for apu-s-club with 503 rows.
INFO: Loaded data for apu-s-club with 503 rows

Loading assets:  14%|█▍        | 31/218 [00:03<00:17, 10.71it/s]

INFO: Successfully loaded data for the-sandbox with 1810 rows.
INFO: Loaded data for the-sandbox with 1810 rows
INFO: Successfully loaded data for aethir with 412 rows.
INFO: Loaded data for aethir with 412 rows

Loading assets:  15%|█▌        | 33/218 [00:03<00:15, 11.75it/s]

INFO: Successfully loaded data for turbo with 817 rows.
INFO: Loaded data for turbo with 817 rows
INFO: Successfully loaded data for pendle with 1553 rows.
INFO: Loaded data for pendle with 1553 rows

Loading assets:  16%|█▌        | 35/218 [00:04<00:16, 10.78it/s]

INFO: Successfully loaded data for equilibria-finance with 783 rows.
INFO: Successfully loaded data for polymath with 2727 rows.
INFO: Loaded data for equilibria-finance with 783 rows
INFO: Loaded data for polymath with 2727 rows

Loading assets:  17%|█▋        | 37/218 [00:04<00:16, 11.29it/s]

INFO: Successfully loaded data for crypto-com-chain with 2401 rows.
INFO: Loaded data for crypto-com-chain with 2401 rows
INFO: Successfully loaded data for gmx with 1415 rows.
INFO: Loaded data for gmx with 1415 rows
INFO: Successfully loaded data for zcash with 3195 rows.
INFO: Loaded data for zcash with 3195 rows
INFO: Successfully loaded data for rainbow-token-2 with 1228 rows.
INFO: Loaded data for rainbow-token-2 with 1228 rows

Loading assets:  19%|█▉        | 41/218 [00:04<00:11, 15.88it/s]

INFO: Successfully loaded data for aave with 1760 rows.
INFO: Loaded data for aave with 1760 rows
INFO: Successfully loaded data for wrapped-nxm with 1828 rows.
INFO: Loaded data for wrapped-nxm with 1828 rows

Loading assets:  20%|█▉        | 43/218 [00:04<00:12, 13.82it/s]

INFO: Successfully loaded data for axelar with 1036 rows.
INFO: Loaded data for axelar with 1036 rows
INFO: Successfully loaded data for binancecoin with 2873 rows.
INFO: Loaded data for binancecoin with 2873 rows

Loading assets:  21%|██        | 45/218 [00:04<00:13, 12.82it/s]

INFO: Successfully loaded data for harrypotterobamasonic10in with 806 rows.
INFO: Successfully loaded data for ethena with 483 rows.
INFO: Loaded data for harrypotterobamasonic10in with 806 rows
INFO: Loaded data for ethena with 483 rows
INFO: Successfully loaded data for sui with 818 rows.
INFO: Loaded data for sui with 818 rows
INFO: Successfully loaded data for prisma-governance-token with 635 rows.
INFO: Loaded data for prisma-governance-token with 635 rows

Loading assets:  22%|██▏       | 49/218 [00:04<00:09, 17.84it/s]

INFO: Successfully loaded data for beam-2 with 642 rows.
INFO: Loaded data for beam-2 with 642 rows
INFO: Successfully loaded data for rari-governance-token with 1745 rows.
INFO: Loaded data for rari-governance-token with 1745 rows
INFO: Successfully loaded data for kamino with 455 rows.
INFO: Loaded data for kamino with 455 rows
INFO: Successfully loaded data for dog-go-to-the-moon-rune with 459 rows.

Loading assets:  24%|██▍       | 52/218 [00:05<00:11, 14.99it/s]

INFO: Successfully loaded data for zebec-network with 470 rows.
INFO: Loaded data for dog-go-to-the-moon-rune with 459 rows
INFO: Loaded data for zebec-network with 470 rows
INFO: Successfully loaded data for cat-in-a-dogs-world with 490 rows.
INFO: Loaded data for cat-in-a-dogs-world with 490 rows
INFO: Successfully loaded data for aurory with 1374 rows.

Loading assets:  25%|██▌       | 55/218 [00:05<00:09, 16.93it/s]

INFO: Loaded data for aurory with 1374 rows
INFO: Successfully loaded data for dogecoin with 4244 rows.
INFO: Loaded data for dogecoin with 4244 rows
INFO: Successfully loaded data for kekius-maximus with 226 rows.
INFO: Loaded data for kekius-maximus with 226 rows

Loading assets:  27%|██▋       | 58/218 [00:05<00:10, 15.96it/s]

INFO: Successfully loaded data for secret with 1762 rows.
INFO: Loaded data for secret with 1762 rows
INFO: Successfully loaded data for zeus-network with 480 rows.
INFO: Loaded data for zeus-network with 480 rows
INFO: Successfully loaded data for jasmycoin with 1526 rows.

Loading assets:  28%|██▊       | 60/218 [00:05<00:09, 15.82it/s]

INFO: Loaded data for jasmycoin with 1526 rows
INFO: Successfully loaded data for kyber-network-crystal with 1559 rows.
INFO: Loaded data for kyber-network-crystal with 1559 rows
INFO: Successfully loaded data for fantom with 2465 rows.
INFO: Loaded data for fantom with 2465 rows
INFO: Successfully loaded data for helium with 1929 rows.
INFO: Loaded data for helium with 1929 rows

Loading assets:  29%|██▉       | 64/218 [00:05<00:09, 16.02it/s]

INFO: Successfully loaded data for dash with 4183 rows.
INFO: Loaded data for dash with 4183 rows
INFO: Successfully loaded data for ether-fi with 498 rows.
INFO: Loaded data for ether-fi with 498 rows

Loading assets:  30%|███       | 66/218 [00:06<00:15,  9.60it/s]

INFO: Successfully loaded data for my-neighbor-alice with 1597 rows.
INFO: Loaded data for my-neighbor-alice with 1597 rows
INFO: Successfully loaded data for pancakeswap-token with 1764 rows.
INFO: Loaded data for pancakeswap-token with 1764 rows
INFO: Successfully loaded data for alpha-finance with 1753 rows.
INFO: Loaded data for alpha-finance with 1753 rows

Loading assets:  32%|███▏      | 69/218 [00:06<00:12, 11.51it/s]

INFO: Successfully loaded data for bubblemaps with 140 rows.
INFO: Loaded data for bubblemaps with 140 rows
INFO: Successfully loaded data for flow with 1644 rows.
INFO: Successfully loaded data for book-of-meme with 502 rows.
INFO: Loaded data for flow with 1644 rows

Loading assets:  33%|███▎      | 71/218 [00:06<00:12, 11.80it/s]

INFO: Loaded data for book-of-meme with 502 rows
INFO: Successfully loaded data for balancer with 1862 rows.
INFO: Loaded data for balancer with 1862 rows
INFO: Successfully loaded data for pudgy-penguins with 224 rows.
INFO: Loaded data for pudgy-penguins with 224 rows

Loading assets:  34%|███▍      | 74/218 [00:06<00:09, 14.48it/s]

INFO: Successfully loaded data for render-token with 1870 rows.
INFO: Loaded data for render-token with 1870 rows
INFO: Successfully loaded data for cosmos with 2349 rows.
INFO: Loaded data for cosmos with 2349 rows
INFO: Successfully loaded data for vela-token with 907 rows.
INFO: Loaded data for vela-token with 907 rows
INFO: Successfully loaded data for decentraland with 2831 rows.
INFO: Successfully loaded data for dydx with 1420 rows.
INFO: Loaded data for decentraland with 2831 rows
INFO: Loaded data for dydx with 1420 rows

Loading assets:  36%|███▌      | 78/218 [00:07<00:08, 16.88it/s]

INFO: Successfully loaded data for ava-ai with 250 rows.
INFO: Loaded data for ava-ai with 250 rows
INFO: Successfully loaded data for yield-guild-games with 1462 rows.
INFO: Loaded data for yield-guild-games with 1462 rows
INFO: Successfully loaded data for anzen-finance with 232 rows.
INFO: Loaded data for anzen-finance with 232 rows
INFO: Successfully loaded data for terra-luna-2 with 1158 rows.
INFO: Successfully loaded data for chill-guy with 253 rows.
INFO: Loaded data for terra-luna-2 with 1158 rows
INFO: Loaded data for chill-guy with 253 rows

Loading assets:  38%|███▊      | 83/218 [00:07<00:06, 20.08it/s]

INFO: Successfully loaded data for grass with 274 rows.
INFO: Loaded data for grass with 274 rows
INFO: Successfully loaded data for tron with 2819 rows.
INFO: Loaded data for tron with 2819 rows

Loading assets:  39%|███▉      | 86/218 [00:07<00:06, 21.83it/s]

INFO: Successfully loaded data for bertram-the-pomeranian with 259 rows.
INFO: Loaded data for bertram-the-pomeranian with 259 rows
INFO: Successfully loaded data for worldcoin-wld with 736 rows.
INFO: Loaded data for worldcoin-wld with 736 rows
INFO: Successfully loaded data for bitcoin-cash with 2918 rows.
INFO: Loaded data for bitcoin-cash with 2918 rows

Loading assets:  41%|████      | 89/218 [00:07<00:06, 20.98it/s]

INFO: Successfully loaded data for polkadot with 1805 rows.
INFO: Successfully loaded data for lisk with 3401 rows.
INFO: Loaded data for polkadot with 1805 rows
INFO: Successfully loaded data for aioz-network with 1578 rows.
INFO: Loaded data for lisk with 3401 rows
INFO: Loaded data for aioz-network with 1578 rows

Loading assets:  42%|████▏     | 92/218 [00:07<00:06, 20.76it/s]

INFO: Successfully loaded data for serum with 1813 rows.
INFO: Loaded data for serum with 1813 rows
INFO: Successfully loaded data for spx6900 with 701 rows.
INFO: Loaded data for spx6900 with 701 rows
INFO: Successfully loaded data for chainlink with 2819 rows.
INFO: Loaded data for chainlink with 2819 rows
INFO: Successfully loaded data for arweave with 2098 rows.
INFO: Successfully loaded data for mamo with 69 rows.
INFO: Loaded data for arweave with 2098 rows
INFO: Loaded data for mamo with 69 rows

Loading assets:  44%|████▍     | 97/218 [00:07<00:05, 23.64it/s]

INFO: Successfully loaded data for nunet with 1339 rows.
INFO: Loaded data for nunet with 1339 rows
INFO: Successfully loaded data for bittensor with 879 rows.
INFO: Successfully loaded data for lido-dao with 1666 rows.
INFO: Successfully loaded data for cookie with 411 rows.
INFO: Loaded data for bittensor with 879 rows
INFO: Loaded data for lido-dao with 1666 rows

Loading assets:  46%|████▌     | 100/218 [00:07<00:05, 22.88it/s]

INFO: Successfully loaded data for genesysgo-shadow with 1301 rows.
INFO: Loaded data for cookie with 411 rows
INFO: Loaded data for genesysgo-shadow with 1301 rows
INFO: Successfully loaded data for baby-doge-coin with 1511 rows.
INFO: Loaded data for baby-doge-coin with 1511 rows
INFO: Successfully loaded data for badger-dao with 1698 rows.
INFO: Loaded data for badger-dao with 1698 rows

Loading assets:  48%|████▊     | 105/218 [00:08<00:03, 28.69it/s]

INFO: Successfully loaded data for siren-2 with 160 rows.
INFO: Loaded data for siren-2 with 160 rows
INFO: Successfully loaded data for eigenlayer with 301 rows.
INFO: Successfully loaded data for kryptonite with 715 rows.
INFO: Loaded data for eigenlayer with 301 rows
INFO: Loaded data for kryptonite with 715 rows
INFO: Successfully loaded data for pepe with 833 rows.
INFO: Successfully loaded data for conic-finance with 1016 rows.
INFO: Loaded data for pepe with 833 rows

Loading assets:  50%|█████     | 109/218 [00:08<00:08, 13.24it/s]

INFO: Loaded data for conic-finance with 1016 rows
INFO: Successfully loaded data for thorchain with 2201 rows.
INFO: Successfully loaded data for raydium with 1619 rows.
INFO: Loaded data for thorchain with 2201 rows
INFO: Loaded data for raydium with 1619 rows
INFO: Successfully loaded data for compound-governance-token with 1869 rows.
INFO: Loaded data for compound-governance-token with 1869 rows
INFO: Successfully loaded data for the-open-network with 1432 rows.
INFO: Loaded data for the-open-network with 1432 rows

Loading assets:  52%|█████▏    | 114/218 [00:08<00:06, 16.57it/s]

INFO: Successfully loaded data for immutable-x with 1362 rows.
INFO: Loaded data for immutable-x with 1362 rows
INFO: Successfully loaded data for clearpool with 1370 rows.
INFO: Loaded data for clearpool with 1370 rows
INFO: Successfully loaded data for wibx with 1929 rows.
INFO: Successfully loaded data for sei-network with 714 rows.
INFO: Loaded data for wibx with 1929 rows
INFO: Successfully loaded data for metacade with 840 rows.

Loading assets:  54%|█████▎    | 117/218 [00:08<00:05, 17.22it/s]

INFO: Successfully loaded data for prometeus with 2223 rows.
INFO: Loaded data for sei-network with 714 rows
INFO: Loaded data for metacade with 840 rows
INFO: Loaded data for prometeus with 2223 rows
INFO: Successfully loaded data for guild-of-guardians with 1315 rows.
INFO: Loaded data for guild-of-guardians with 1315 rows

Loading assets:  56%|█████▌    | 121/218 [00:09<00:05, 19.28it/s]

INFO: Successfully loaded data for sturdy with 523 rows.
INFO: Loaded data for sturdy with 523 rows
INFO: Successfully loaded data for echelon-prime with 880 rows.
INFO: Loaded data for echelon-prime with 880 rows
INFO: Successfully loaded data for tether with 3807 rows.
INFO: Successfully loaded data for celestia with 637 rows.
INFO: Successfully loaded data for usd-coin with 2490 rows.
INFO: Loaded data for tether with 3807 rows
INFO: Loaded data for celestia with 637 rows

Loading assets:  57%|█████▋    | 124/218 [00:09<00:05, 18.15it/s]

INFO: Loaded data for usd-coin with 2490 rows
INFO: Successfully loaded data for arpa with 2254 rows.
INFO: Loaded data for arpa with 2254 rows
INFO: Successfully loaded data for ai16z with 275 rows.
INFO: Loaded data for ai16z with 275 rows
INFO: Successfully loaded data for power-ledger with 2820 rows.
INFO: Loaded data for power-ledger with 2820 rows

Loading assets:  59%|█████▉    | 129/218 [00:09<00:04, 20.31it/s]

INFO: Successfully loaded data for deep with 288 rows.
INFO: Successfully loaded data for arbitrum with 859 rows.
INFO: Loaded data for deep with 288 rows
INFO: Loaded data for arbitrum with 859 rows
INFO: Successfully loaded data for tribe-2 with 1578 rows.
INFO: Loaded data for tribe-2 with 1578 rows

Loading assets:  61%|██████    | 132/218 [00:09<00:03, 21.78it/s]

INFO: Successfully loaded data for virtual-protocol with 579 rows.
INFO: Loaded data for virtual-protocol with 579 rows
INFO: Successfully loaded data for smartcash with 2882 rows.
INFO: Loaded data for smartcash with 2882 rows
INFO: Successfully loaded data for tokenbot-2 with 261 rows.
INFO: Loaded data for tokenbot-2 with 261 rows

Loading assets:  62%|██████▏   | 135/218 [00:09<00:03, 23.40it/s]

INFO: Successfully loaded data for ethervista with 331 rows.
INFO: Loaded data for ethervista with 331 rows
INFO: Successfully loaded data for orbit-3 with 233 rows.
INFO: Loaded data for orbit-3 with 233 rows
INFO: Successfully loaded data for kujira with 1341 rows.
INFO: Loaded data for kujira with 1341 rows

Loading assets:  63%|██████▎   | 138/218 [00:09<00:03, 23.61it/s]

INFO: Successfully loaded data for griffain with 235 rows.
INFO: Successfully loaded data for ethereum with 3644 rows.
INFO: Loaded data for griffain with 235 rows
INFO: Loaded data for ethereum with 3644 rows
INFO: Successfully loaded data for kaspa with 1161 rows.
INFO: Loaded data for kaspa with 1161 rows
INFO: Successfully loaded data for new-xai-gork with 88 rows.
INFO: Loaded data for new-xai-gork with 88 rows
INFO: Successfully loaded data for audius with 1740 rows.
INFO: Loaded data for audius with 1740 rows
INFO: Successfully loaded data for arkham with 742 rows.

Loading assets:  66%|██████▌   | 143/218 [00:10<00:02, 26.30it/s]

INFO: Loaded data for arkham with 742 rows
INFO: Successfully loaded data for blockstack with 2105 rows.
INFO: Loaded data for blockstack with 2105 rows
INFO: Successfully loaded data for useless-3 with 79 rows.
INFO: Loaded data for useless-3 with 79 rows
INFO: Successfully loaded data for yne with 218 rows.

Loading assets:  67%|██████▋   | 146/218 [00:10<00:04, 16.64it/s]

INFO: Loaded data for yne with 218 rows
INFO: Successfully loaded data for evan-2 with 249 rows.
INFO: Loaded data for evan-2 with 249 rows
INFO: Successfully loaded data for botto with 1389 rows.
INFO: Loaded data for botto with 1389 rows

Loading assets:  68%|██████▊   | 149/218 [00:10<00:03, 18.33it/s]

INFO: Successfully loaded data for maker with 2778 rows.
INFO: Loaded data for maker with 2778 rows
INFO: Successfully loaded data for spell-token with 1523 rows.
INFO: Loaded data for spell-token with 1523 rows
INFO: Successfully loaded data for venice-token with 183 rows.
INFO: Loaded data for venice-token with 183 rows

Loading assets:  70%|██████▉   | 152/218 [00:10<00:03, 19.90it/s]

INFO: Successfully loaded data for instadapp with 1504 rows.
INFO: Loaded data for instadapp with 1504 rows
INFO: Successfully loaded data for sushi with 1796 rows.
INFO: Loaded data for sushi with 1796 rows
INFO: Successfully loaded data for akash-network with 1747 rows.
INFO: Loaded data for akash-network with 1747 rows

Loading assets:  71%|███████   | 155/218 [00:10<00:03, 20.30it/s]

INFO: Successfully loaded data for eos with 2942 rows.
INFO: Loaded data for eos with 2942 rows
INFO: Successfully loaded data for story-2 with 166 rows.
INFO: Loaded data for story-2 with 166 rows
INFO: Successfully loaded data for verasity with 1620 rows.
INFO: Loaded data for verasity with 1620 rows
INFO: Successfully loaded data for arbdoge-ai with 833 rows.
INFO: Loaded data for arbdoge-ai with 833 rows

Loading assets:  73%|███████▎  | 159/218 [00:10<00:02, 24.48it/s]

INFO: Successfully loaded data for gains-network with 1365 rows.
INFO: Loaded data for gains-network with 1365 rows
INFO: Successfully loaded data for bonk with 943 rows.
INFO: Loaded data for bonk with 943 rows
INFO: Successfully loaded data for numeraire with 2938 rows.
INFO: Loaded data for numeraire with 2938 rows

Loading assets:  74%|███████▍  | 162/218 [00:11<00:02, 24.09it/s]

INFO: Successfully loaded data for sonic-3 with 206 rows.
INFO: Loaded data for sonic-3 with 206 rows
INFO: Successfully loaded data for plume with 189 rows.
INFO: Loaded data for plume with 189 rows
INFO: Successfully loaded data for jupiter-exchange-solana with 545 rows.
INFO: Loaded data for jupiter-exchange-solana with 545 rows
INFO: Successfully loaded data for star-atlas-dao with 1426 rows.
INFO: Loaded data for star-atlas-dao with 1426 rows

Loading assets:  76%|███████▌  | 166/218 [00:11<00:02, 25.57it/s]

INFO: Successfully loaded data for hedera-hashgraph with 2142 rows.
INFO: Loaded data for hedera-hashgraph with 2142 rows
INFO: Successfully loaded data for solayer with 168 rows.
INFO: Loaded data for solayer with 168 rows
INFO: Successfully loaded data for aerodrome-finance with 683 rows.
INFO: Loaded data for aerodrome-finance with 683 rows
INFO: Successfully loaded data for fwog with 364 rows.
INFO: Loaded data for fwog with 364 rows

Loading assets:  78%|███████▊  | 170/218 [00:11<00:01, 28.50it/s]

INFO: Successfully loaded data for perpetual-protocol with 1784 rows.
INFO: Loaded data for perpetual-protocol with 1784 rows
INFO: Successfully loaded data for chex-token with 2001 rows.
INFO: Loaded data for chex-token with 2001 rows
INFO: Successfully loaded data for matic-network with 2286 rows.
INFO: Loaded data for matic-network with 2286 rows
INFO: Successfully loaded data for alchemy-pay with 1785 rows.
INFO: Loaded data for alchemy-pay with 1785 rows

Loading assets:  80%|███████▉  | 174/218 [00:11<00:01, 28.69it/s]

INFO: Successfully loaded data for official-trump with 192 rows.
INFO: Loaded data for official-trump with 192 rows
INFO: Successfully loaded data for popcat with 588 rows.
INFO: Successfully loaded data for shiba-inu with 1809 rows.
INFO: Loaded data for popcat with 588 rows
INFO: Loaded data for shiba-inu with 1809 rows
INFO: Successfully loaded data for internet-computer with 1541 rows.
INFO: Loaded data for internet-computer with 1541 rows

Loading assets:  82%|████████▏ | 178/218 [00:11<00:01, 29.47it/s]

INFO: Successfully loaded data for mog-coin with 739 rows.
INFO: Loaded data for mog-coin with 739 rows
INFO: Successfully loaded data for snek with 799 rows.
INFO: Loaded data for snek with 799 rows
INFO: Successfully loaded data for morpho with 251 rows.
INFO: Loaded data for morpho with 251 rows
INFO: Successfully loaded data for euler with 1131 rows.
INFO: Loaded data for euler with 1131 rows

Loading assets:  83%|████████▎ | 182/218 [00:11<00:01, 27.22it/s]

INFO: Successfully loaded data for near with 1749 rows.
INFO: Successfully loaded data for litecoin with 4475 rows.
INFO: Loaded data for near with 1749 rows
INFO: Loaded data for litecoin with 4475 rows
INFO: Successfully loaded data for injective-protocol with 1742 rows.
INFO: Successfully loaded data for radiant-capital with 1099 rows.
INFO: Loaded data for injective-protocol with 1742 rows
INFO: Loaded data for radiant-capital with 1099 rows

Loading assets:  85%|████████▍ | 185/218 [00:11<00:01, 21.99it/s]

INFO: Successfully loaded data for hypercycle with 812 rows.
INFO: Loaded data for hypercycle with 812 rows

Loading assets:  86%|████████▌ | 188/218 [00:12<00:01, 19.56it/s]

INFO: Successfully loaded data for mubarak with 135 rows.
INFO: Loaded data for mubarak with 135 rows
INFO: Successfully loaded data for floki with 1492 rows.
INFO: Loaded data for floki with 1492 rows
INFO: Successfully loaded data for swarm with 3407 rows.
INFO: Loaded data for swarm with 3407 rows
INFO: Successfully loaded data for curve-dao-token with 1810 rows.
INFO: Loaded data for curve-dao-token with 1810 rows

Loading assets:  88%|████████▊ | 192/218 [00:12<00:01, 20.30it/s]

INFO: Successfully loaded data for gigachad-2 with 554 rows.
INFO: Loaded data for gigachad-2 with 554 rows
INFO: Successfully loaded data for mintlayer with 857 rows.
INFO: Loaded data for mintlayer with 857 rows
INFO: Successfully loaded data for ripple with 4377 rows.
INFO: Loaded data for ripple with 4377 rows

Loading assets:  89%|████████▉ | 195/218 [00:12<00:01, 21.27it/s]

INFO: Successfully loaded data for syrup with 258 rows.
INFO: Loaded data for syrup with 258 rows
INFO: Successfully loaded data for liquity with 1576 rows.
INFO: Successfully loaded data for ethereum-classic with 3292 rows.
INFO: Loaded data for liquity with 1576 rows
INFO: Loaded data for ethereum-classic with 3292 rows
INFO: Successfully loaded data for goatseus-maximus with 289 rows.
INFO: Loaded data for goatseus-maximus with 289 rows

Loading assets:  91%|█████████▏| 199/218 [00:12<00:00, 23.21it/s]

INFO: Successfully loaded data for slerf with 498 rows.
INFO: Loaded data for slerf with 498 rows
INFO: Successfully loaded data for true-usd with 2686 rows.
INFO: Loaded data for true-usd with 2686 rows
INFO: Successfully loaded data for avalanche-2 with 1771 rows.
INFO: Successfully loaded data for myria with 845 rows.
INFO: Loaded data for avalanche-2 with 1771 rows
INFO: Loaded data for myria with 845 rows

Loading assets:  93%|█████████▎| 202/218 [00:12<00:00, 21.80it/s]

INFO: Successfully loaded data for y with 484 rows.
INFO: Successfully loaded data for pax-gold with 2144 rows.
INFO: Loaded data for y with 484 rows
INFO: Loaded data for pax-gold with 2144 rows
INFO: Successfully loaded data for mantra-dao with 1806 rows.
INFO: Successfully loaded data for monero with 4087 rows.
INFO: Loaded data for mantra-dao with 1806 rows
INFO: Loaded data for monero with 4087 rows

Loading assets:  94%|█████████▍| 206/218 [00:12<00:00, 24.07it/s]

INFO: Successfully loaded data for paal-ai with 764 rows.
INFO: Loaded data for paal-ai with 764 rows
INFO: Successfully loaded data for constitutiondao with 1348 rows.
INFO: Successfully loaded data for cardano with 2841 rows.
INFO: Loaded data for constitutiondao with 1348 rows
INFO: Loaded data for cardano with 2841 rows

Loading assets:  97%|█████████▋| 211/218 [00:13<00:00,  9.24it/s]

INFO: Successfully loaded data for lagrange with 55 rows.
INFO: Successfully loaded data for based-brett with 516 rows.
INFO: Loaded data for lagrange with 55 rows
INFO: Loaded data for based-brett with 516 rows

Loading assets:  98%|█████████▊| 213/218 [00:14<00:00,  9.26it/s]

INFO: Successfully loaded data for genopets with 1349 rows.
INFO: Successfully loaded data for solana with 1936 rows.
INFO: Loaded data for genopets with 1349 rows
INFO: Loaded data for solana with 1936 rows

Loading assets:  99%|█████████▊| 215/218 [00:14<00:00, 10.27it/s]

INFO: Successfully loaded data for neon with 742 rows.
INFO: Loaded data for neon with 742 rows
INFO: Successfully loaded data for kaito with 159 rows.
INFO: Loaded data for kaito with 159 rows
INFO: Successfully loaded data for frax-share with 1681 rows.
INFO: Loaded data for frax-share with 1681 rows

Loading assets: 100%|██████████| 218/218 [00:14<00:00, 15.23it/s]
Loading assets: 100%|██████████| 218/218 [00:00<00:00, 510529.47it/s]

{'venice-token': AssetData(asset_id='venice-token', price_data_length=183, signals=[], backtests=[]),
 'dydx': AssetData(asset_id='dydx', price_data_length=1420, signals=[], backtests=[]),
 'grass': AssetData(asset_id='grass', price_data_length=274, signals=[], backtests=[]),
 'eigenlayer': AssetData(asset_id='eigenlayer', price_data_length=301, signals=[], backtests=[]),
 'gmx': AssetData(asset_id='gmx', price_data_length=1415, signals=[], backtests=[]),
 'optimism': AssetData(asset_id='optimism', price_data_length=1155, signals=[], backtests=[]),
 'new-xai-gork': AssetData(asset_id='new-xai-gork', price_data_length=88, signals=[], backtests=[]),
 'compound-governance-token': AssetData(asset_id='compound-governance-token', price_data_length=1869, signals=[], backtests=[]),
 'bitcoin-cash': AssetData(asset_id='bitcoin-cash', price_data_length=2918, signals=[], backtests=[]),
 'vela-token': AssetData(asset_id='vela-token', price_data_length=907, signals=[], backtests=[]),
 'ethereum': AssetData(asset_id='ethereum', price_data_length=3644, signals=[], backtests=[]),
 'moonwell-artemis': AssetData(asset_id='moonwell-artemis', price_data_length=1132, signals=[], backtests=[]),
 'pepe': AssetData(asset_id='pepe', price_data_length=833, signals=[], backtests=[]),
 'zebec-network': AssetData(asset_id='zebec-network', price_data_length=470, signals=[], backtests=[]),
 'binancecoin': AssetData(asset_id='binancecoin', price_data_length=2873, signals=[], backtests=[]),
 'acala': AssetData(asset_id='acala', price_data_length=1281, signals=[], backtests=[]),
 'hyperliquid': AssetData(asset_id='hyperliquid', price_data_length=243, signals=[], backtests=[]),
 'tezos': AssetData(asset_id='tezos', price_data_length=2585, signals=[], backtests=[]),
 'bertram-the-pomeranian': AssetData(asset_id='bertram-the-pomeranian', price_data_length=259, signals=[], backtests=[]),
 'fantom': AssetData(asset_id='fantom', price_data_length=2465, signals=[], backtests=[]),
 'illuvium': AssetData(asset_id='illuvium', price_data_length=1581, signals=[], backtests=[]),
 'aioz-network': AssetData(asset_id='aioz-network', price_data_length=1578, signals=[], backtests=[]),
 'shiba-inu': AssetData(asset_id='shiba-inu', price_data_length=1809, signals=[], backtests=[]),
 'neiro-3': AssetData(asset_id='neiro-3', price_data_length=362, signals=[], backtests=[]),
 'equilibria-finance': AssetData(asset_id='equilibria-finance', price_data_length=783, signals=[], backtests=[]),
 'avalanche-2': AssetData(asset_id='avalanche-2', price_data_length=1771, signals=[], backtests=[]),
 'sonic-3': AssetData(asset_id='sonic-3', price_data_length=206, signals=[], backtests=[]),
 'radiant-capital': AssetData(asset_id='radiant-capital', price_data_length=1099, signals=[], backtests=[]),
 'ethereum-classic': AssetData(asset_id='ethereum-classic', price_data_length=3292, signals=[], backtests=[]),
 'official-trump': AssetData(asset_id='official-trump', price_data_length=192, signals=[], backtests=[]),
 'worldcoin-wld': AssetData(asset_id='worldcoin-wld', price_data_length=736, signals=[], backtests=[]),
 'pancakeswap-token': AssetData(asset_id='pancakeswap-token', price_data_length=1764, signals=[], backtests=[]),
 'true-usd': AssetData(asset_id='true-usd', price_data_length=2686, signals=[], backtests=[]),
 'badger-dao': AssetData(asset_id='badger-dao', price_data_length=1698, signals=[], backtests=[]),
 'dash': AssetData(asset_id='dash', price_data_length=4183, signals=[], backtests=[]),
 'tokenbot-2': AssetData(asset_id='tokenbot-2', price_data_length=261, signals=[], backtests=[]),
 'mog-coin': AssetData(asset_id='mog-coin', price_data_length=739, signals=[], backtests=[]),
 'chex-token': AssetData(asset_id='chex-token', price_data_length=2001, signals=[], backtests=[]),
 'instadapp': AssetData(asset_id='instadapp', price_data_length=1504, signals=[], backtests=[]),
 'flow': AssetData(asset_id='flow', price_data_length=1644, signals=[], backtests=[]),
 'smartcash': AssetData(asset_id='smartcash', price_data_length=2882, signals=[], backtests=[]),
 'beam-2': AssetData(asset_id='beam-2', price_data_length=642, signals=[], backtests=[]),
 'prisma-governance-token': AssetData(asset_id='prisma-governance-token', price_data_length=635, signals=[], backtests=[]),
 'polymath': AssetData(asset_id='polymath', price_data_length=2727, signals=[], backtests=[]),
 'spell-token': AssetData(asset_id='spell-token', price_data_length=1523, signals=[], backtests=[]),
 'injective-protocol': AssetData(asset_id='injective-protocol', price_data_length=1742, signals=[], backtests=[]),
 'maker': AssetData(asset_id='maker', price_data_length=2778, signals=[], backtests=[]),
 'verasity': AssetData(asset_id='verasity', price_data_length=1620, signals=[], backtests=[]),
 'conic-finance': AssetData(asset_id='conic-finance', price_data_length=1016, signals=[], backtests=[]),
 'ether-fi': AssetData(asset_id='ether-fi', price_data_length=498, signals=[], backtests=[]),
 'hypercycle': AssetData(asset_id='hypercycle', price_data_length=812, signals=[], backtests=[]),
 'zeus-network': AssetData(asset_id='zeus-network', price_data_length=480, signals=[], backtests=[]),
 'story-2': AssetData(asset_id='story-2', price_data_length=166, signals=[], backtests=[]),
 'heyanon': AssetData(asset_id='heyanon', price_data_length=214, signals=[], backtests=[]),
 'based-brett': AssetData(asset_id='based-brett', price_data_length=516, signals=[], backtests=[]),
 'matic-network': AssetData(asset_id='matic-network', price_data_length=2286, signals=[], backtests=[]),
 'tether': AssetData(asset_id='tether', price_data_length=3807, signals=[], backtests=[]),
 'band-protocol': AssetData(asset_id='band-protocol', price_data_length=2141, signals=[], backtests=[]),
 'genopets': AssetData(asset_id='genopets', price_data_length=1349, signals=[], backtests=[]),
 'griffain': AssetData(asset_id='griffain', price_data_length=235, signals=[], backtests=[]),
 'cosmos': AssetData(asset_id='cosmos', price_data_length=2349, signals=[], backtests=[]),
 'axelar': AssetData(asset_id='axelar', price_data_length=1036, signals=[], backtests=[]),
 'swarm': AssetData(asset_id='swarm', price_data_length=3407, signals=[], backtests=[]),
 'kaspa': AssetData(asset_id='kaspa', price_data_length=1161, signals=[], backtests=[]),
 'arpa': AssetData(asset_id='arpa', price_data_length=2254, signals=[], backtests=[]),
 'polkadot': AssetData(asset_id='polkadot', price_data_length=1805, signals=[], backtests=[]),
 'crypto-com-chain': AssetData(asset_id='crypto-com-chain', price_data_length=2401, signals=[], backtests=[]),
 'y': AssetData(asset_id='y', price_data_length=484, signals=[], backtests=[]),
 'yne': AssetData(asset_id='yne', price_data_length=218, signals=[], backtests=[]),
 'siren-2': AssetData(asset_id='siren-2', price_data_length=160, signals=[], backtests=[]),
 'yearn-finance': AssetData(asset_id='yearn-finance', price_data_length=1837, signals=[], backtests=[]),
 'cow-protocol': AssetData(asset_id='cow-protocol', price_data_length=1215, signals=[], backtests=[]),
 'morpho': AssetData(asset_id='morpho', price_data_length=251, signals=[], backtests=[]),
 'eos': AssetData(asset_id='eos', price_data_length=2942, signals=[], backtests=[]),
 'alpha-finance': AssetData(asset_id='alpha-finance', price_data_length=1753, signals=[], backtests=[]),
 'lisk': AssetData(asset_id='lisk', price_data_length=3401, signals=[], backtests=[]),
 'lido-dao': AssetData(asset_id='lido-dao', price_data_length=1666, signals=[], backtests=[]),
 'grok-2': AssetData(asset_id='grok-2', price_data_length=630, signals=[], backtests=[]),
 'fwog': AssetData(asset_id='fwog', price_data_length=364, signals=[], backtests=[]),
 'orbit-3': AssetData(asset_id='orbit-3', price_data_length=233, signals=[], backtests=[]),
 'pendle': AssetData(asset_id='pendle', price_data_length=1553, signals=[], backtests=[]),
 'neon': AssetData(asset_id='neon', price_data_length=742, signals=[], backtests=[]),
 'myria': AssetData(asset_id='myria', price_data_length=845, signals=[], backtests=[]),
 'immutable-x': AssetData(asset_id='immutable-x', price_data_length=1362, signals=[], backtests=[]),
 'alchemist-ai': AssetData(asset_id='alchemist-ai', price_data_length=240, signals=[], backtests=[]),
 'render-token': AssetData(asset_id='render-token', price_data_length=1870, signals=[], backtests=[]),
 'secret': AssetData(asset_id='secret', price_data_length=1762, signals=[], backtests=[]),
 'goatseus-maximus': AssetData(asset_id='goatseus-maximus', price_data_length=289, signals=[], backtests=[]),
 'gains-network': AssetData(asset_id='gains-network', price_data_length=1365, signals=[], backtests=[]),
 'anzen-finance': AssetData(asset_id='anzen-finance', price_data_length=232, signals=[], backtests=[]),
 'hedera-hashgraph': AssetData(asset_id='hedera-hashgraph', price_data_length=2142, signals=[], backtests=[]),
 'spx6900': AssetData(asset_id='spx6900', price_data_length=701, signals=[], backtests=[]),
 'mantra-dao': AssetData(asset_id='mantra-dao', price_data_length=1806, signals=[], backtests=[]),
 'omisego': AssetData(asset_id='omisego', price_data_length=2935, signals=[], backtests=[]),
 'star-atlas-dao': AssetData(asset_id='star-atlas-dao', price_data_length=1426, signals=[], backtests=[]),
 'metacade': AssetData(asset_id='metacade', price_data_length=840, signals=[], backtests=[]),
 'wrapped-nxm': AssetData(asset_id='wrapped-nxm', price_data_length=1828, signals=[], backtests=[]),
 'internet-computer': AssetData(asset_id='internet-computer', price_data_length=1541, signals=[], backtests=[]),
 'aurory': AssetData(asset_id='aurory', price_data_length=1374, signals=[], backtests=[]),
 'aethir': AssetData(asset_id='aethir', price_data_length=412, signals=[], backtests=[]),
 'perpetual-protocol': AssetData(asset_id='perpetual-protocol', price_data_length=1784, signals=[], backtests=[]),
 'aerodrome-finance': AssetData(asset_id='aerodrome-finance', price_data_length=683, signals=[], backtests=[]),
 'useless-3': AssetData(asset_id='useless-3', price_data_length=79, signals=[], backtests=[]),
 'guild-of-guardians': AssetData(asset_id='guild-of-guardians', price_data_length=1315, signals=[], backtests=[]),
 'book-of-meme': AssetData(asset_id='book-of-meme', price_data_length=502, signals=[], backtests=[]),
 'dodo': AssetData(asset_id='dodo', price_data_length=1763, signals=[], backtests=[]),
 'curve-dao-token': AssetData(asset_id='curve-dao-token', price_data_length=1810, signals=[], backtests=[]),
 'cookie': AssetData(asset_id='cookie', price_data_length=411, signals=[], backtests=[]),
 'coredaoorg': AssetData(asset_id='coredaoorg', price_data_length=902, signals=[], backtests=[]),
 'solana': AssetData(asset_id='solana', price_data_length=1936, signals=[], backtests=[]),
 'snek': AssetData(asset_id='snek', price_data_length=799, signals=[], backtests=[]),
 'kyber-network-crystal': AssetData(asset_id='kyber-network-crystal', price_data_length=1559, signals=[], backtests=[]),
 'nunet': AssetData(asset_id='nunet', price_data_length=1339, signals=[], backtests=[]),
 'gala': AssetData(asset_id='gala', price_data_length=1777, signals=[], backtests=[]),
 'litecoin': AssetData(asset_id='litecoin', price_data_length=4475, signals=[], backtests=[]),
 'sturdy': AssetData(asset_id='sturdy', price_data_length=523, signals=[], backtests=[]),
 'my-neighbor-alice': AssetData(asset_id='my-neighbor-alice', price_data_length=1597, signals=[], backtests=[]),
 'havven': AssetData(asset_id='havven', price_data_length=2688, signals=[], backtests=[]),
 'arbdoge-ai': AssetData(asset_id='arbdoge-ai', price_data_length=833, signals=[], backtests=[]),
 'clearpool': AssetData(asset_id='clearpool', price_data_length=1370, signals=[], backtests=[]),
 'mubarak': AssetData(asset_id='mubarak', price_data_length=135, signals=[], backtests=[]),
 'kryptonite': AssetData(asset_id='kryptonite', price_data_length=715, signals=[], backtests=[]),
 'fartcoin': AssetData(asset_id='fartcoin', price_data_length=282, signals=[], backtests=[]),
 'bonk': AssetData(asset_id='bonk', price_data_length=943, signals=[], backtests=[]),
 'wibx': AssetData(asset_id='wibx', price_data_length=1929, signals=[], backtests=[]),
 'chainlink': AssetData(asset_id='chainlink', price_data_length=2819, signals=[], backtests=[]),
 'jasmycoin': AssetData(asset_id='jasmycoin', price_data_length=1526, signals=[], backtests=[]),
 'gigachad-2': AssetData(asset_id='gigachad-2', price_data_length=554, signals=[], backtests=[]),
 'evan-2': AssetData(asset_id='evan-2', price_data_length=249, signals=[], backtests=[]),
 'lofi-2': AssetData(asset_id='lofi-2', price_data_length=243, signals=[], backtests=[]),
 'terra-luna-2': AssetData(asset_id='terra-luna-2', price_data_length=1158, signals=[], backtests=[]),
 'dogecoin': AssetData(asset_id='dogecoin', price_data_length=4244, signals=[], backtests=[]),
 'ai16z': AssetData(asset_id='ai16z', price_data_length=275, signals=[], backtests=[]),
 'decentraland': AssetData(asset_id='decentraland', price_data_length=2831, signals=[], backtests=[]),
 'uniswap': AssetData(asset_id='uniswap', price_data_length=1776, signals=[], backtests=[]),
 'the-open-network': AssetData(asset_id='the-open-network', price_data_length=1432, signals=[], backtests=[]),
 'turbo': AssetData(asset_id='turbo', price_data_length=817, signals=[], backtests=[]),
 'apu-s-club': AssetData(asset_id='apu-s-club', price_data_length=503, signals=[], backtests=[]),
 'genesysgo-shadow': AssetData(asset_id='genesysgo-shadow', price_data_length=1301, signals=[], backtests=[]),
 'ava-ai': AssetData(asset_id='ava-ai', price_data_length=250, signals=[], backtests=[]),
 'bubblemaps': AssetData(asset_id='bubblemaps', price_data_length=140, signals=[], backtests=[]),
 'cat-in-a-dogs-world': AssetData(asset_id='cat-in-a-dogs-world', price_data_length=490, signals=[], backtests=[]),
 'monero': AssetData(asset_id='monero', price_data_length=4087, signals=[], backtests=[]),
 'aave': AssetData(asset_id='aave', price_data_length=1760, signals=[], backtests=[]),
 'akash-network': AssetData(asset_id='akash-network', price_data_length=1747, signals=[], backtests=[]),
 'yield-guild-games': AssetData(asset_id='yield-guild-games', price_data_length=1462, signals=[], backtests=[]),
 'sei-network': AssetData(asset_id='sei-network', price_data_length=714, signals=[], backtests=[]),
 'ondo-finance': AssetData(asset_id='ondo-finance', price_data_length=558, signals=[], backtests=[]),
 'solayer': AssetData(asset_id='solayer', price_data_length=168, signals=[], backtests=[]),
 'mintlayer': AssetData(asset_id='mintlayer', price_data_length=857, signals=[], backtests=[]),
 'celestia': AssetData(asset_id='celestia', price_data_length=637, signals=[], backtests=[]),
 'kaito': AssetData(asset_id='kaito', price_data_length=159, signals=[], backtests=[]),
 'thorchain': AssetData(asset_id='thorchain', price_data_length=2201, signals=[], backtests=[]),
 'alchemy-pay': AssetData(asset_id='alchemy-pay', price_data_length=1785, signals=[], backtests=[]),
 'helium': AssetData(asset_id='helium', price_data_length=1929, signals=[], backtests=[]),
 'cardano': AssetData(asset_id='cardano', price_data_length=2841, signals=[], backtests=[]),
 'power-ledger': AssetData(asset_id='power-ledger', price_data_length=2820, signals=[], backtests=[]),
 'bitcoin': AssetData(asset_id='bitcoin', price_data_length=4475, signals=[], backtests=[]),
 'axie-infinity': AssetData(asset_id='axie-infinity', price_data_length=1728, signals=[], backtests=[]),
 'near': AssetData(asset_id='near', price_data_length=1749, signals=[], backtests=[]),
 'deep': AssetData(asset_id='deep', price_data_length=288, signals=[], backtests=[]),
 'fetch-ai': AssetData(asset_id='fetch-ai', price_data_length=2343, signals=[], backtests=[]),
 'osaka-protocol': AssetData(asset_id='osaka-protocol', price_data_length=749, signals=[], backtests=[]),
 'floki': AssetData(asset_id='floki', price_data_length=1492, signals=[], backtests=[]),
 'rari-governance-token': AssetData(asset_id='rari-governance-token', price_data_length=1745, signals=[], backtests=[]),
 'blockstack': AssetData(asset_id='blockstack', price_data_length=2105, signals=[], backtests=[]),
 'the-sandbox': AssetData(asset_id='the-sandbox', price_data_length=1810, signals=[], backtests=[]),
 'slerf': AssetData(asset_id='slerf', price_data_length=498, signals=[], backtests=[]),
 'sui': AssetData(asset_id='sui', price_data_length=818, signals=[], backtests=[]),
 'mamo': AssetData(asset_id='mamo', price_data_length=69, signals=[], backtests=[]),
 'chill-guy': AssetData(asset_id='chill-guy', price_data_length=253, signals=[], backtests=[]),
 'plume': AssetData(asset_id='plume', price_data_length=189, signals=[], backtests=[]),
 'balancer': AssetData(asset_id='balancer', price_data_length=1862, signals=[], backtests=[]),
 'lagrange': AssetData(asset_id='lagrange', price_data_length=55, signals=[], backtests=[]),
 'pudgy-penguins': AssetData(asset_id='pudgy-penguins', price_data_length=224, signals=[], backtests=[]),
 'ethena': AssetData(asset_id='ethena', price_data_length=483, signals=[], backtests=[]),
 'ronin': AssetData(asset_id='ronin', price_data_length=1279, signals=[], backtests=[]),
 'sushi': AssetData(asset_id='sushi', price_data_length=1796, signals=[], backtests=[]),
 'ethervista': AssetData(asset_id='ethervista', price_data_length=331, signals=[], backtests=[]),
 'serum': AssetData(asset_id='serum', price_data_length=1813, signals=[], backtests=[]),
 'rainbow-token-2': AssetData(asset_id='rainbow-token-2', price_data_length=1228, signals=[], backtests=[]),
 'ripple': AssetData(asset_id='ripple', price_data_length=4377, signals=[], backtests=[]),
 'arweave': AssetData(asset_id='arweave', price_data_length=2098, signals=[], backtests=[]),
 'numeraire': AssetData(asset_id='numeraire', price_data_length=2938, signals=[], backtests=[]),
 'quant-network': AssetData(asset_id='quant-network', price_data_length=2587, signals=[], backtests=[]),
 'pax-gold': AssetData(asset_id='pax-gold', price_data_length=2144, signals=[], backtests=[]),
 'popcat': AssetData(asset_id='popcat', price_data_length=588, signals=[], backtests=[]),
 'kujira': AssetData(asset_id='kujira', price_data_length=1341, signals=[], backtests=[]),
 'tribe-2': AssetData(asset_id='tribe-2', price_data_length=1578, signals=[], backtests=[]),
 'bittensor': AssetData(asset_id='bittensor', price_data_length=879, signals=[], backtests=[]),
 'usd-coin': AssetData(asset_id='usd-coin', price_data_length=2490, signals=[], backtests=[]),
 'dusk-network': AssetData(asset_id='dusk-network', price_data_length=2215, signals=[], backtests=[]),
 'arkham': AssetData(asset_id='arkham', price_data_length=742, signals=[], backtests=[]),
 'dog-go-to-the-moon-rune': AssetData(asset_id='dog-go-to-the-moon-rune', price_data_length=459, signals=[], backtests=[]),
 'jupiter-exchange-solana': AssetData(asset_id='jupiter-exchange-solana', price_data_length=545, signals=[], backtests=[]),
 'tron': AssetData(asset_id='tron', price_data_length=2819, signals=[], backtests=[]),
 'audius': AssetData(asset_id='audius', price_data_length=1740, signals=[], backtests=[]),
 'constitutiondao': AssetData(asset_id='constitutiondao', price_data_length=1348, signals=[], backtests=[]),
 'stellar': AssetData(asset_id='stellar', price_data_length=4010, signals=[], backtests=[]),
 'arbitrum': AssetData(asset_id='arbitrum', price_data_length=859, signals=[], backtests=[]),
 'dogwifcoin': AssetData(asset_id='dogwifcoin', price_data_length=594, signals=[], backtests=[]),
 'syrup': AssetData(asset_id='syrup', price_data_length=258, signals=[], backtests=[]),
 'botto': AssetData(asset_id='botto', price_data_length=1389, signals=[], backtests=[]),
 'kekius-maximus': AssetData(asset_id='kekius-maximus', price_data_length=226, signals=[], backtests=[]),
 'zcash': AssetData(asset_id='zcash', price_data_length=3195, signals=[], backtests=[]),

In [19]:
# Register specific signals by their exact names
signals = analyzer.register_signals_parallel(
    asset_ids=assets, 
    calculate_values=True,
    specific_signals=[
                      "DonchianEnsembleUSD", "DonchianEnsembleBTC",
                      "RSI_Bullish_USD", "RSI_Bullish_BTC"]
)
signals

INFO: Using 4 specific signals provided by user
INFO: Registering 4 new signals for axie-infinity
INFO: Registering 4 new signals for tezos
INFO: Registering 4 new signals for neiro-3
INFO: Registering 4 new signals for coredaoorg

Registering signals group 1/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 4 new signals for heyanon
INFO: Adapted windows for data length 362: [5, 10, 15, 30, 45, 75]
INFO: Calculated initial values for DonchianEnsembleUSD on heyanon: 214 points
INFO: Calculated initial values for DonchianEnsembleUSD on neiro-3: 362 points
INFO: Calculated initial values for DonchianEnsembleBTC on heyanon: 214 points
INFO: Calculated initial values for RSI_Bullish_USD on heyanon: 214 points
INFO: Calculated initial values for DonchianEnsembleUSD on coredaoorg: 902 points
INFO: Calculated initial values for RSI_Bullish_BTC on heyanon: 214 points
INFO: Completed signal registration for heyanon in 3.07 seconds
INFO: Calculated initial values for DonchianEnsembleBTC on neiro-3: 362 points

Registering signals group 1/44:  20%|██        | 1/5 [00:03<00:12,  3.04s/it]

INFO: Calculated initial values for DonchianEnsembleUSD on axie-infinity: 1728 points
INFO: Calculated initial values for RSI_Bullish_USD on neiro-3: 362 points
INFO: Calculated initial values for RSI_Bullish_BTC on neiro-3: 362 points
INFO: Completed signal registration for neiro-3 in 4.40 seconds

Registering signals group 1/44:  40%|████      | 2/5 [00:04<00:05,  1.96s/it]

INFO: Calculated initial values for DonchianEnsembleUSD on tezos: 2585 points
INFO: Calculated initial values for DonchianEnsembleBTC on coredaoorg: 902 points
INFO: Calculated initial values for RSI_Bullish_USD on coredaoorg: 902 points
INFO: Calculated initial values for RSI_Bullish_BTC on coredaoorg: 902 points
INFO: Completed signal registration for coredaoorg in 9.11 seconds

Registering signals group 1/44:  60%|██████    | 3/5 [00:09<00:06,  3.25s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on axie-infinity: 1728 points
INFO: Calculated initial values for RSI_Bullish_USD on axie-infinity: 1728 points
INFO: Calculated initial values for RSI_Bullish_BTC on axie-infinity: 1728 points
INFO: Completed signal registration for axie-infinity in 16.20 seconds

Registering signals group 1/44:  80%|████████  | 4/5 [00:15<00:04,  4.70s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on tezos: 2585 points
INFO: Calculated initial values for RSI_Bullish_USD on tezos: 2585 points
INFO: Calculated initial values for RSI_Bullish_BTC on tezos: 2585 points
INFO: Completed signal registration for tezos in 19.16 seconds

Registering signals group 1/44: 100%|██████████| 5/5 [00:18<00:00,  3.77s/it]

INFO: Registering 4 new signals for dogwifcoin
INFO: Registering 4 new signals for quant-network
INFO: Adapted windows for data length 594: [4, 8, 16, 24, 49, 74, 123]
INFO: Registering 4 new signals for fartcoin

Registering signals group 2/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 4 new signals for dodo
INFO: Registering 4 new signals for grok-2
INFO: Adapted windows for data length 282: [3, 7, 11, 23, 35, 58]
INFO: Adapted windows for data length 630: [4, 8, 17, 26, 52, 78, 131]
INFO: Calculated initial values for DonchianEnsembleUSD on dogwifcoin: 594 points
INFO: Calculated initial values for DonchianEnsembleUSD on fartcoin: 282 points
INFO: Calculated initial values for DonchianEnsembleUSD on grok-2: 630 points
INFO: Calculated initial values for DonchianEnsembleBTC on fartcoin: 282 points
INFO: Calculated initial values for DonchianEnsembleBTC on dogwifcoin: 594 points
INFO: Calculated initial values for RSI_Bullish_USD on fartcoin: 282 points
INFO: Calculated initial values for RSI_Bullish_BTC on fartcoin: 282 points
INFO: Completed signal registration for fartcoin in 4.39 seconds

Registering signals group 2/44:  20%|██        | 1/5 [00:04<00:17,  4.28s/it]

INFO: Calculated initial values for DonchianEnsembleUSD on dodo: 1763 points
INFO: Calculated initial values for DonchianEnsembleBTC on grok-2: 630 points
INFO: Calculated initial values for RSI_Bullish_USD on dogwifcoin: 594 points
INFO: Calculated initial values for RSI_Bullish_BTC on dogwifcoin: 594 points
INFO: Completed signal registration for dogwifcoin in 5.81 seconds

Registering signals group 2/44:  40%|████      | 2/5 [00:05<00:07,  2.58s/it]

INFO: Calculated initial values for DonchianEnsembleUSD on quant-network: 2587 points
INFO: Calculated initial values for RSI_Bullish_USD on grok-2: 630 points
INFO: Calculated initial values for RSI_Bullish_BTC on grok-2: 630 points
INFO: Completed signal registration for grok-2 in 6.61 seconds

Registering signals group 2/44:  60%|██████    | 3/5 [00:06<00:03,  1.78s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on dodo: 1763 points
INFO: Calculated initial values for RSI_Bullish_USD on dodo: 1763 points
INFO: Calculated initial values for RSI_Bullish_BTC on dodo: 1763 points
INFO: Calculated initial values for DonchianEnsembleBTC on quant-network: 2587 points
INFO: Completed signal registration for dodo in 12.22 seconds

Registering signals group 2/44:  80%|████████  | 4/5 [00:12<00:03,  3.26s/it]

INFO: Calculated initial values for RSI_Bullish_USD on quant-network: 2587 points
INFO: Calculated initial values for RSI_Bullish_BTC on quant-network: 2587 points
INFO: Completed signal registration for quant-network in 15.31 seconds

Registering signals group 2/44: 100%|██████████| 5/5 [00:15<00:00,  3.01s/it]

INFO: Registering 4 new signals for moonwell-artemis
INFO: Registering 4 new signals for hyperliquid
INFO: Registering 4 new signals for optimism
INFO: Registering 4 new signals for yearn-finance

Registering signals group 3/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 4 new signals for aixbt
INFO: Adapted windows for data length 253: [3, 7, 10, 21, 31, 52]
INFO: Calculated initial values for DonchianEnsembleUSD on hyperliquid: 243 points
INFO: Calculated initial values for DonchianEnsembleUSD on aixbt: 253 points
INFO: Calculated initial values for DonchianEnsembleBTC on hyperliquid: 243 points
INFO: Calculated initial values for DonchianEnsembleBTC on aixbt: 253 points
INFO: Calculated initial values for RSI_Bullish_USD on hyperliquid: 243 points
INFO: Calculated initial values for RSI_Bullish_BTC on hyperliquid: 243 points
INFO: Completed signal registration for hyperliquid in 5.09 seconds

Registering signals group 3/44:  20%|██        | 1/5 [00:04<00:19,  4.76s/it]

INFO: Calculated initial values for RSI_Bullish_USD on aixbt: 253 points
INFO: Calculated initial values for DonchianEnsembleUSD on moonwell-artemis: 1132 points
INFO: Calculated initial values for RSI_Bullish_BTC on aixbt: 253 points
INFO: Completed signal registration for aixbt in 5.84 seconds
INFO: Calculated initial values for DonchianEnsembleUSD on optimism: 1155 points

Registering signals group 3/44:  40%|████      | 2/5 [00:05<00:07,  2.42s/it]

INFO: Calculated initial values for DonchianEnsembleUSD on yearn-finance: 1837 points
INFO: Calculated initial values for DonchianEnsembleBTC on moonwell-artemis: 1132 points
INFO: Calculated initial values for DonchianEnsembleBTC on optimism: 1155 points
INFO: Calculated initial values for RSI_Bullish_USD on moonwell-artemis: 1132 points
INFO: Calculated initial values for RSI_Bullish_USD on optimism: 1155 points
INFO: Calculated initial values for RSI_Bullish_BTC on moonwell-artemis: 1132 points
INFO: Calculated initial values for RSI_Bullish_BTC on optimism: 1155 points
INFO: Completed signal registration for moonwell-artemis in 12.95 seconds

Registering signals group 3/44:  60%|██████    | 3/5 [00:12<00:09,  4.52s/it]

INFO: Completed signal registration for optimism in 13.04 seconds
INFO: Calculated initial values for DonchianEnsembleBTC on yearn-finance: 1837 points
INFO: Calculated initial values for RSI_Bullish_USD on yearn-finance: 1837 points
INFO: Calculated initial values for RSI_Bullish_BTC on yearn-finance: 1837 points
INFO: Completed signal registration for yearn-finance in 14.55 seconds

Registering signals group 3/44: 100%|██████████| 5/5 [00:14<00:00,  2.82s/it]

INFO: Registering 4 new signals for illuvium
INFO: Registering 4 new signals for ondo-finance
INFO: Registering 4 new signals for dusk-network
INFO: Registering 4 new signals for alchemist-ai

Registering signals group 4/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 4 new signals for havven
INFO: Adapted windows for data length 558: [3, 7, 15, 23, 46, 69, 116]
INFO: Adapted windows for data length 240: [3, 6, 10, 20, 30, 50]
INFO: Calculated initial values for DonchianEnsembleUSD on alchemist-ai: 240 points
INFO: Calculated initial values for DonchianEnsembleUSD on ondo-finance: 558 points
INFO: Calculated initial values for DonchianEnsembleBTC on alchemist-ai: 240 points
INFO: Calculated initial values for DonchianEnsembleUSD on illuvium: 1581 points
INFO: Calculated initial values for RSI_Bullish_USD on alchemist-ai: 240 points
INFO: Calculated initial values for RSI_Bullish_BTC on alchemist-ai: 240 points
INFO: Completed signal registration for alchemist-ai in 3.53 seconds
INFO: Calculated initial values for DonchianEnsembleBTC on ondo-finance: 558 points

Registering signals group 4/44:  20%|██        | 1/5 [00:03<00:14,  3.52s/it]

INFO: Calculated initial values for DonchianEnsembleUSD on dusk-network: 2215 points
INFO: Calculated initial values for RSI_Bullish_USD on ondo-finance: 558 points
INFO: Calculated initial values for RSI_Bullish_BTC on ondo-finance: 558 points
INFO: Completed signal registration for ondo-finance in 5.90 seconds

Registering signals group 4/44:  40%|████      | 2/5 [00:05<00:08,  2.81s/it]

INFO: Calculated initial values for DonchianEnsembleUSD on havven: 2688 points
INFO: Calculated initial values for DonchianEnsembleBTC on illuvium: 1581 points
INFO: Calculated initial values for RSI_Bullish_USD on illuvium: 1581 points
INFO: Calculated initial values for RSI_Bullish_BTC on illuvium: 1581 points
INFO: Calculated initial values for DonchianEnsembleBTC on dusk-network: 2215 points
INFO: Completed signal registration for illuvium in 12.05 seconds

Registering signals group 4/44:  60%|██████    | 3/5 [00:11<00:08,  4.27s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on havven: 2688 points
INFO: Calculated initial values for RSI_Bullish_USD on dusk-network: 2215 points
INFO: Calculated initial values for RSI_Bullish_BTC on dusk-network: 2215 points
INFO: Completed signal registration for dusk-network in 15.34 seconds

Registering signals group 4/44:  80%|████████  | 4/5 [00:15<00:03,  3.89s/it]

INFO: Calculated initial values for RSI_Bullish_USD on havven: 2688 points
INFO: Calculated initial values for RSI_Bullish_BTC on havven: 2688 points
INFO: Completed signal registration for havven in 16.20 seconds

Registering signals group 4/44: 100%|██████████| 5/5 [00:15<00:00,  3.19s/it]

INFO: Registering 4 new signals for fetch-ai
INFO: Registering 4 new signals for ronin
INFO: Registering 4 new signals for omisego

Registering signals group 5/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 4 new signals for acala
INFO: Registering 4 new signals for band-protocol
INFO: Calculated initial values for DonchianEnsembleUSD on ronin: 1279 points
INFO: Calculated initial values for DonchianEnsembleUSD on acala: 1281 points
INFO: Calculated initial values for DonchianEnsembleUSD on fetch-ai: 2343 points
INFO: Calculated initial values for DonchianEnsembleUSD on band-protocol: 2141 points
INFO: Calculated initial values for DonchianEnsembleUSD on omisego: 2935 points
INFO: Calculated initial values for DonchianEnsembleBTC on ronin: 1279 points
INFO: Calculated initial values for DonchianEnsembleBTC on acala: 1281 points
INFO: Calculated initial values for RSI_Bullish_USD on ronin: 1279 points
INFO: Calculated initial values for RSI_Bullish_USD on acala: 1281 points
INFO: Calculated initial values for RSI_Bullish_BTC on ronin: 1279 points
INFO: Calculated initial values for RSI_Bullish_BTC on acala: 1281 points
INFO: Completed signal registration for ronin in 15.37 seconds

Registering signals group 5/44:  20%|██        | 1/5 [00:15<01:01, 15.30s/it]

INFO: Completed signal registration for acala in 15.78 seconds

Registering signals group 5/44:  40%|████      | 2/5 [00:15<00:19,  6.53s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on band-protocol: 2141 points
INFO: Calculated initial values for DonchianEnsembleBTC on fetch-ai: 2343 points
INFO: Calculated initial values for DonchianEnsembleBTC on omisego: 2935 points
INFO: Calculated initial values for RSI_Bullish_USD on band-protocol: 2141 points
INFO: Calculated initial values for RSI_Bullish_USD on fetch-ai: 2343 points
INFO: Calculated initial values for RSI_Bullish_BTC on band-protocol: 2141 points
INFO: Completed signal registration for band-protocol in 21.10 seconds
INFO: Calculated initial values for RSI_Bullish_BTC on fetch-ai: 2343 points

Registering signals group 5/44:  60%|██████    | 3/5 [00:20<00:11,  5.90s/it]

INFO: Completed signal registration for fetch-ai in 21.43 seconds

Registering signals group 5/44:  80%|████████  | 4/5 [00:21<00:03,  3.71s/it]

INFO: Calculated initial values for RSI_Bullish_USD on omisego: 2935 points
INFO: Calculated initial values for RSI_Bullish_BTC on omisego: 2935 points
INFO: Completed signal registration for omisego in 22.62 seconds

Registering signals group 5/44: 100%|██████████| 5/5 [00:22<00:00,  4.46s/it]

INFO: Registering 4 new signals for gala
INFO: Registering 4 new signals for bitcoin

INFO: Registering 4 new signals for multibit

Registering signals group 6/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 4 new signals for stellar
INFO: Registering 4 new signals for uniswap
INFO: Adapted windows for data length 617: [4, 8, 17, 25, 51, 77, 128]
INFO: Calculated initial values for DonchianEnsembleUSD on multibit: 617 points
INFO: Calculated initial values for DonchianEnsembleUSD on gala: 1777 points
INFO: Calculated initial values for DonchianEnsembleUSD on uniswap: 1776 points
INFO: Calculated initial values for DonchianEnsembleBTC on multibit: 617 points
INFO: Calculated initial values for RSI_Bullish_USD on multibit: 617 points
INFO: Calculated initial values for RSI_Bullish_BTC on multibit: 617 points
INFO: Completed signal registration for multibit in 8.49 seconds

Registering signals group 6/44:  20%|██        | 1/5 [00:08<00:33,  8.42s/it]

INFO: Calculated initial values for DonchianEnsembleUSD on stellar: 4010 points
INFO: Calculated initial values for DonchianEnsembleUSD on bitcoin: 4475 points
INFO: Calculated initial values for DonchianEnsembleBTC on gala: 1777 points
INFO: Calculated initial values for DonchianEnsembleBTC on uniswap: 1776 points
INFO: Calculated initial values for RSI_Bullish_USD on gala: 1777 points
INFO: Calculated initial values for RSI_Bullish_USD on uniswap: 1776 points
INFO: Calculated initial values for RSI_Bullish_BTC on gala: 1777 points
INFO: Completed signal registration for gala in 17.83 seconds

Registering signals group 6/44:  40%|████      | 2/5 [00:17<00:26,  8.92s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on uniswap: 1776 points
INFO: Completed signal registration for uniswap in 18.39 seconds

Registering signals group 6/44:  60%|██████    | 3/5 [00:18<00:10,  5.10s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on bitcoin: 4475 points
INFO: Calculated initial values for RSI_Bullish_USD on bitcoin: 4475 points
INFO: Calculated initial values for RSI_Bullish_BTC on bitcoin: 4475 points
INFO: Completed signal registration for bitcoin in 20.05 seconds

Registering signals group 6/44:  80%|████████  | 4/5 [00:19<00:03,  3.71s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on stellar: 4010 points
INFO: Calculated initial values for RSI_Bullish_USD on stellar: 4010 points
INFO: Calculated initial values for RSI_Bullish_BTC on stellar: 4010 points
INFO: Completed signal registration for stellar in 23.77 seconds

Registering signals group 6/44: 100%|██████████| 5/5 [00:23<00:00,  4.69s/it]

INFO: Registering 4 new signals for apu-s-club

INFO: Registering 4 new signals for the-sandbox

Registering signals group 7/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 4 new signals for turbo
INFO: Registering 4 new signals for aethir
INFO: Registering 4 new signals for pendle
INFO: Adapted windows for data length 503: [3, 6, 13, 20, 41, 62, 104]
INFO: Adapted windows for data length 412: [5, 11, 17, 34, 51, 85]
INFO: Calculated initial values for DonchianEnsembleUSD on aethir: 412 points
INFO: Calculated initial values for DonchianEnsembleUSD on apu-s-club: 503 points
INFO: Calculated initial values for DonchianEnsembleUSD on turbo: 817 points
INFO: Calculated initial values for DonchianEnsembleBTC on aethir: 412 points
INFO: Calculated initial values for DonchianEnsembleBTC on apu-s-club: 503 points
INFO: Calculated initial values for RSI_Bullish_USD on aethir: 412 points
INFO: Calculated initial values for DonchianEnsembleUSD on the-sandbox: 1810 points
INFO: Calculated initial values for DonchianEnsembleUSD on pendle: 1553 points
INFO: Calculated initial values for RSI_Bullish_BTC on aethir: 412 points
INFO: Calculated initial values for RSI_Bullish_USD on apu-s-club: 503 points
INFO: Completed signal registration for aethir in 4.56 seconds
INFO: Calculated initial values for DonchianEnsembleBTC on turbo: 817 points

Registering signals group 7/44:  20%|██        | 1/5 [00:04<00:19,  4.93s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on apu-s-club: 503 points
INFO: Completed signal registration for apu-s-club in 5.40 seconds

Registering signals group 7/44:  40%|████      | 2/5 [00:05<00:07,  2.39s/it]

INFO: Calculated initial values for RSI_Bullish_USD on turbo: 817 points
INFO: Calculated initial values for RSI_Bullish_BTC on turbo: 817 points
INFO: Completed signal registration for turbo in 7.03 seconds

Registering signals group 7/44:  60%|██████    | 3/5 [00:07<00:04,  2.00s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on pendle: 1553 points
INFO: Calculated initial values for DonchianEnsembleBTC on the-sandbox: 1810 points
INFO: Calculated initial values for RSI_Bullish_USD on pendle: 1553 points
INFO: Calculated initial values for RSI_Bullish_USD on the-sandbox: 1810 points
INFO: Calculated initial values for RSI_Bullish_BTC on pendle: 1553 points
INFO: Completed signal registration for pendle in 10.50 seconds

Registering signals group 7/44:  80%|████████  | 4/5 [00:10<00:02,  2.55s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on the-sandbox: 1810 points
INFO: Completed signal registration for the-sandbox in 10.62 seconds

Registering signals group 7/44: 100%|██████████| 5/5 [00:10<00:00,  2.12s/it]

INFO: Registering 4 new signals for crypto-com-chain
INFO: Registering 4 new signals for polymath
INFO: Registering 4 new signals for equilibria-finance

Registering signals group 8/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 4 new signals for gmx
INFO: Registering 4 new signals for zcash
INFO: Calculated initial values for DonchianEnsembleUSD on equilibria-finance: 783 points
INFO: Calculated initial values for DonchianEnsembleUSD on gmx: 1415 points
INFO: Calculated initial values for DonchianEnsembleBTC on equilibria-finance: 783 points
INFO: Calculated initial values for DonchianEnsembleUSD on crypto-com-chain: 2401 points
INFO: Calculated initial values for DonchianEnsembleUSD on polymath: 2727 points
INFO: Calculated initial values for RSI_Bullish_USD on equilibria-finance: 783 points
INFO: Calculated initial values for RSI_Bullish_BTC on equilibria-finance: 783 points
INFO: Calculated initial values for DonchianEnsembleUSD on zcash: 3195 points
INFO: Completed signal registration for equilibria-finance in 9.64 seconds

Registering signals group 8/44:  20%|██        | 1/5 [00:09<00:37,  9.34s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on gmx: 1415 points
INFO: Calculated initial values for RSI_Bullish_USD on gmx: 1415 points
INFO: Calculated initial values for RSI_Bullish_BTC on gmx: 1415 points
INFO: Completed signal registration for gmx in 16.12 seconds

Registering signals group 8/44:  40%|████      | 2/5 [00:15<00:22,  7.64s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on crypto-com-chain: 2401 points
INFO: Calculated initial values for DonchianEnsembleBTC on polymath: 2727 points
INFO: Calculated initial values for RSI_Bullish_USD on crypto-com-chain: 2401 points
INFO: Calculated initial values for DonchianEnsembleBTC on zcash: 3195 points
INFO: Calculated initial values for RSI_Bullish_BTC on crypto-com-chain: 2401 points
INFO: Completed signal registration for crypto-com-chain in 21.74 seconds

Registering signals group 8/44:  60%|██████    | 3/5 [00:21<00:13,  6.71s/it]

INFO: Calculated initial values for RSI_Bullish_USD on polymath: 2727 points
INFO: Calculated initial values for RSI_Bullish_BTC on polymath: 2727 points
INFO: Completed signal registration for polymath in 22.81 seconds

Registering signals group 8/44:  80%|████████  | 4/5 [00:22<00:04,  4.49s/it]

INFO: Calculated initial values for RSI_Bullish_USD on zcash: 3195 points
INFO: Calculated initial values for RSI_Bullish_BTC on zcash: 3195 points
INFO: Completed signal registration for zcash in 23.85 seconds

Registering signals group 8/44: 100%|██████████| 5/5 [00:23<00:00,  4.69s/it]

INFO: Registering 4 new signals for rainbow-token-2

INFO: Registering 4 new signals for aave
INFO: Registering 4 new signals for wrapped-nxm
INFO: Registering 4 new signals for axelar

Registering signals group 9/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 4 new signals for binancecoin
INFO: Calculated initial values for DonchianEnsembleUSD on rainbow-token-2: 1228 points
INFO: Calculated initial values for DonchianEnsembleUSD on axelar: 1036 points
INFO: Calculated initial values for DonchianEnsembleUSD on aave: 1760 points
INFO: Calculated initial values for DonchianEnsembleUSD on wrapped-nxm: 1828 points
INFO: Calculated initial values for DonchianEnsembleUSD on binancecoin: 2873 points
INFO: Calculated initial values for DonchianEnsembleBTC on rainbow-token-2: 1228 points
INFO: Calculated initial values for DonchianEnsembleBTC on axelar: 1036 points
INFO: Calculated initial values for RSI_Bullish_USD on axelar: 1036 points
INFO: Calculated initial values for RSI_Bullish_BTC on axelar: 1036 points
INFO: Completed signal registration for axelar in 12.98 seconds
INFO: Calculated initial values for DonchianEnsembleBTC on aave: 1760 points

Registering signals group 9/44:  20%|██        | 1/5 [00:12<00:49, 12.49s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on wrapped-nxm: 1828 points
INFO: Calculated initial values for RSI_Bullish_USD on rainbow-token-2: 1228 points
INFO: Calculated initial values for RSI_Bullish_USD on aave: 1760 points
INFO: Calculated initial values for RSI_Bullish_USD on wrapped-nxm: 1828 points
INFO: Calculated initial values for RSI_Bullish_BTC on aave: 1760 points
INFO: Calculated initial values for RSI_Bullish_BTC on wrapped-nxm: 1828 points
INFO: Completed signal registration for aave in 17.23 seconds

Registering signals group 9/44:  40%|████      | 2/5 [00:16<00:22,  7.66s/it]

INFO: Completed signal registration for wrapped-nxm in 17.44 seconds

Registering signals group 9/44:  60%|██████    | 3/5 [00:16<00:08,  4.25s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on rainbow-token-2: 1228 points
INFO: Calculated initial values for DonchianEnsembleBTC on binancecoin: 2873 points
INFO: Completed signal registration for rainbow-token-2 in 17.80 seconds

Registering signals group 9/44:  80%|████████  | 4/5 [00:17<00:02,  2.71s/it]

INFO: Calculated initial values for RSI_Bullish_USD on binancecoin: 2873 points
INFO: Calculated initial values for RSI_Bullish_BTC on binancecoin: 2873 points
INFO: Completed signal registration for binancecoin in 19.80 seconds

Registering signals group 9/44: 100%|██████████| 5/5 [00:19<00:00,  3.85s/it]

INFO: Registering 4 new signals for ethena
INFO: Registering 4 new signals for harrypotterobamasonic10in

INFO: Registering 4 new signals for sui
INFO: Adapted windows for data length 483: [3, 6, 13, 20, 40, 60, 100]
INFO: Registering 4 new signals for prisma-governance-token

Registering signals group 10/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 4 new signals for beam-2
INFO: Adapted windows for data length 635: [4, 8, 17, 26, 52, 79, 132]
INFO: Adapted windows for data length 642: [4, 8, 17, 26, 53, 80, 133]
INFO: Calculated initial values for DonchianEnsembleUSD on ethena: 483 points
INFO: Calculated initial values for DonchianEnsembleUSD on harrypotterobamasonic10in: 806 points
INFO: Calculated initial values for DonchianEnsembleUSD on sui: 818 points
INFO: Calculated initial values for DonchianEnsembleUSD on prisma-governance-token: 635 points
INFO: Calculated initial values for DonchianEnsembleUSD on beam-2: 642 points
INFO: Calculated initial values for DonchianEnsembleBTC on ethena: 483 points
INFO: Calculated initial values for RSI_Bullish_USD on ethena: 483 points
INFO: Calculated initial values for RSI_Bullish_BTC on ethena: 483 points
INFO: Completed signal registration for ethena in 4.37 seconds
INFO: Calculated initial values for DonchianEnsembleBTC on prisma-governance-token: 635 points

Registering signals group 10/44:  20%|██        | 1/5 [00:04<00:16,  4.09s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on beam-2: 642 points
INFO: Calculated initial values for DonchianEnsembleBTC on harrypotterobamasonic10in: 806 points
INFO: Calculated initial values for DonchianEnsembleBTC on sui: 818 points
INFO: Calculated initial values for RSI_Bullish_USD on prisma-governance-token: 635 points
INFO: Calculated initial values for RSI_Bullish_BTC on prisma-governance-token: 635 points
INFO: Calculated initial values for RSI_Bullish_USD on beam-2: 642 points
INFO: Completed signal registration for prisma-governance-token in 6.18 seconds

Registering signals group 10/44:  40%|████      | 2/5 [00:05<00:08,  2.70s/it]

INFO: Calculated initial values for RSI_Bullish_USD on harrypotterobamasonic10in: 806 points
INFO: Calculated initial values for RSI_Bullish_USD on sui: 818 points
INFO: Calculated initial values for RSI_Bullish_BTC on beam-2: 642 points
INFO: Calculated initial values for RSI_Bullish_BTC on harrypotterobamasonic10in: 806 points
INFO: Completed signal registration for beam-2 in 6.46 seconds
INFO: Calculated initial values for RSI_Bullish_BTC on sui: 818 points

Registering signals group 10/44:  60%|██████    | 3/5 [00:06<00:03,  1.57s/it]

INFO: Completed signal registration for harrypotterobamasonic10in in 6.49 seconds
INFO: Completed signal registration for sui in 6.52 seconds

Registering signals group 10/44: 100%|██████████| 5/5 [00:06<00:00,  1.21s/it]

INFO: Registering 4 new signals for rari-governance-token
INFO: Registering 4 new signals for kamino
INFO: Registering 4 new signals for zebec-network

Registering signals group 11/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 4 new signals for dog-go-to-the-moon-rune
INFO: Registering 4 new signals for cat-in-a-dogs-world
INFO: Adapted windows for data length 470: [3, 6, 13, 19, 39, 58, 97]
INFO: Adapted windows for data length 459: [3, 6, 12, 19, 38, 57, 95]
INFO: Adapted windows for data length 490: [3, 6, 13, 20, 40, 61, 102]
INFO: Calculated initial values for DonchianEnsembleUSD on kamino: 455 points
INFO: Calculated initial values for DonchianEnsembleUSD on zebec-network: 470 points
INFO: Calculated initial values for DonchianEnsembleUSD on dog-go-to-the-moon-rune: 459 points
INFO: Calculated initial values for DonchianEnsembleUSD on cat-in-a-dogs-world: 490 points
INFO: Calculated initial values for DonchianEnsembleBTC on kamino: 455 points
INFO: Calculated initial values for DonchianEnsembleBTC on zebec-network: 470 points
INFO: Calculated initial values for DonchianEnsembleUSD on rari-governance-token: 1745 points
INFO: Calculated initial values for DonchianEnsembleBTC on cat-in-a-dogs-world: 490 points
INFO: Calculated initial values for DonchianEnsembleBTC on dog-go-to-the-moon-rune: 459 points
INFO: Calculated initial values for RSI_Bullish_USD on kamino: 455 points
INFO: Calculated initial values for RSI_Bullish_USD on zebec-network: 470 points
INFO: Calculated initial values for RSI_Bullish_BTC on kamino: 455 points
INFO: Calculated initial values for RSI_Bullish_USD on cat-in-a-dogs-world: 490 points
INFO: Calculated initial values for RSI_Bullish_BTC on zebec-network: 470 points
INFO: Calculated initial values for RSI_Bullish_USD on dog-go-to-the-moon-rune: 459 points
INFO: Completed signal registration for kamino in 4.68 seconds
INFO: Calculated initial values for RSI_Bullish_BTC on cat-in-a-dogs-world: 490 points

Registering signals group 11/44:  20%|██        | 1/5 [00:04<00:19,  4.78s/it]

INFO: Completed signal registration for zebec-network in 4.89 seconds
INFO: Calculated initial values for RSI_Bullish_BTC on dog-go-to-the-moon-rune: 459 points

Registering signals group 11/44:  40%|████      | 2/5 [00:04<00:06,  2.10s/it]

INFO: Completed signal registration for cat-in-a-dogs-world in 5.05 seconds
INFO: Completed signal registration for dog-go-to-the-moon-rune in 5.25 seconds

Registering signals group 11/44:  60%|██████    | 3/5 [00:05<00:02,  1.22s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on rari-governance-token: 1745 points
INFO: Calculated initial values for RSI_Bullish_USD on rari-governance-token: 1745 points
INFO: Calculated initial values for RSI_Bullish_BTC on rari-governance-token: 1745 points
INFO: Completed signal registration for rari-governance-token in 7.51 seconds

Registering signals group 11/44: 100%|██████████| 5/5 [00:07<00:00,  1.46s/it]

INFO: Registering 4 new signals for dogecoin
INFO: Registering 4 new signals for aurory
INFO: Registering 4 new signals for kekius-maximus

Registering signals group 12/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 4 new signals for secret
INFO: Registering 4 new signals for zeus-network
INFO: Adapted windows for data length 226: [3, 6, 9, 18, 28, 47]
INFO: Calculated initial values for DonchianEnsembleUSD on kekius-maximus: 226 points
INFO: Calculated initial values for DonchianEnsembleUSD on zeus-network: 480 points
INFO: Calculated initial values for DonchianEnsembleBTC on kekius-maximus: 226 points
INFO: Calculated initial values for RSI_Bullish_USD on kekius-maximus: 226 points
INFO: Calculated initial values for RSI_Bullish_BTC on kekius-maximus: 226 points
INFO: Calculated initial values for DonchianEnsembleUSD on aurory: 1374 points
INFO: Completed signal registration for kekius-maximus in 2.87 seconds

Registering signals group 12/44:  20%|██        | 1/5 [00:02<00:11,  2.95s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on zeus-network: 480 points
INFO: Calculated initial values for DonchianEnsembleUSD on secret: 1762 points
INFO: Calculated initial values for RSI_Bullish_USD on zeus-network: 480 points
INFO: Calculated initial values for RSI_Bullish_BTC on zeus-network: 480 points
INFO: Completed signal registration for zeus-network in 4.71 seconds

Registering signals group 12/44:  40%|████      | 2/5 [00:04<00:06,  2.18s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on aurory: 1374 points
INFO: Calculated initial values for DonchianEnsembleUSD on dogecoin: 4244 points
INFO: Calculated initial values for DonchianEnsembleBTC on secret: 1762 points
INFO: Calculated initial values for RSI_Bullish_USD on aurory: 1374 points
INFO: Calculated initial values for RSI_Bullish_BTC on aurory: 1374 points
INFO: Completed signal registration for aurory in 10.76 seconds

Registering signals group 12/44:  60%|██████    | 3/5 [00:10<00:07,  3.92s/it]

INFO: Calculated initial values for RSI_Bullish_USD on secret: 1762 points
INFO: Calculated initial values for RSI_Bullish_BTC on secret: 1762 points
INFO: Completed signal registration for secret in 12.87 seconds

Registering signals group 12/44:  80%|████████  | 4/5 [00:12<00:03,  3.18s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on dogecoin: 4244 points
INFO: Calculated initial values for RSI_Bullish_USD on dogecoin: 4244 points
INFO: Calculated initial values for RSI_Bullish_BTC on dogecoin: 4244 points
INFO: Completed signal registration for dogecoin in 18.16 seconds

Registering signals group 12/44: 100%|██████████| 5/5 [00:17<00:00,  3.56s/it]

INFO: Registering 4 new signals for jasmycoin
INFO: Registering 4 new signals for kyber-network-crystal

INFO: Registering 4 new signals for fantom
INFO: Registering 4 new signals for ether-fi

Registering signals group 13/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 4 new signals for helium
INFO: Calculated initial values for DonchianEnsembleUSD on ether-fi: 498 points
INFO: Calculated initial values for DonchianEnsembleUSD on jasmycoin: 1526 points
INFO: Calculated initial values for DonchianEnsembleBTC on ether-fi: 498 points
INFO: Calculated initial values for DonchianEnsembleUSD on kyber-network-crystal: 1559 points
INFO: Calculated initial values for RSI_Bullish_USD on ether-fi: 498 points
INFO: Calculated initial values for RSI_Bullish_BTC on ether-fi: 498 points
INFO: Completed signal registration for ether-fi in 5.49 seconds
INFO: Calculated initial values for DonchianEnsembleUSD on helium: 1929 points

Registering signals group 13/44:  20%|██        | 1/5 [00:05<00:21,  5.33s/it]

INFO: Calculated initial values for DonchianEnsembleUSD on fantom: 2465 points
INFO: Calculated initial values for DonchianEnsembleBTC on jasmycoin: 1526 points
INFO: Calculated initial values for DonchianEnsembleBTC on kyber-network-crystal: 1559 points
INFO: Calculated initial values for RSI_Bullish_USD on jasmycoin: 1526 points
INFO: Calculated initial values for DonchianEnsembleBTC on helium: 1929 points
INFO: Calculated initial values for RSI_Bullish_USD on kyber-network-crystal: 1559 points
INFO: Calculated initial values for RSI_Bullish_BTC on jasmycoin: 1526 points
INFO: Completed signal registration for jasmycoin in 15.06 seconds
INFO: Calculated initial values for RSI_Bullish_BTC on kyber-network-crystal: 1559 points

Registering signals group 13/44:  40%|████      | 2/5 [00:14<00:23,  7.79s/it]

INFO: Completed signal registration for kyber-network-crystal in 15.55 seconds

Registering signals group 13/44:  60%|██████    | 3/5 [00:15<00:08,  4.44s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on fantom: 2465 points
INFO: Calculated initial values for RSI_Bullish_USD on helium: 1929 points
INFO: Calculated initial values for RSI_Bullish_BTC on helium: 1929 points
INFO: Completed signal registration for helium in 17.28 seconds

Registering signals group 13/44:  80%|████████  | 4/5 [00:16<00:03,  3.35s/it]

INFO: Calculated initial values for RSI_Bullish_USD on fantom: 2465 points
INFO: Calculated initial values for RSI_Bullish_BTC on fantom: 2465 points
INFO: Completed signal registration for fantom in 18.16 seconds

Registering signals group 13/44: 100%|██████████| 5/5 [00:17<00:00,  3.55s/it]

INFO: Registering 4 new signals for dash
INFO: Registering 4 new signals for pancakeswap-token
INFO: Registering 4 new signals for alpha-finance

Registering signals group 14/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 4 new signals for my-neighbor-alice
INFO: Registering 4 new signals for bubblemaps
INFO: Adapted windows for data length 140: [3, 5, 11, 17, 29]
INFO: Calculated initial values for DonchianEnsembleUSD on bubblemaps: 140 points
INFO: Calculated initial values for DonchianEnsembleBTC on bubblemaps: 140 points
INFO: Calculated initial values for RSI_Bullish_USD on bubblemaps: 140 points
INFO: Calculated initial values for RSI_Bullish_BTC on bubblemaps: 140 points
INFO: Completed signal registration for bubblemaps in 2.82 seconds

Registering signals group 14/44:  20%|██        | 1/5 [00:02<00:11,  2.83s/it]

INFO: Calculated initial values for DonchianEnsembleUSD on pancakeswap-token: 1764 points
INFO: Calculated initial values for DonchianEnsembleUSD on my-neighbor-alice: 1597 points
INFO: Calculated initial values for DonchianEnsembleUSD on alpha-finance: 1753 points
INFO: Calculated initial values for DonchianEnsembleUSD on dash: 4183 points
INFO: Calculated initial values for DonchianEnsembleBTC on my-neighbor-alice: 1597 points
INFO: Calculated initial values for DonchianEnsembleBTC on pancakeswap-token: 1764 points
INFO: Calculated initial values for DonchianEnsembleBTC on alpha-finance: 1753 points
INFO: Calculated initial values for RSI_Bullish_USD on my-neighbor-alice: 1597 points
INFO: Calculated initial values for RSI_Bullish_USD on pancakeswap-token: 1764 points
INFO: Calculated initial values for RSI_Bullish_BTC on my-neighbor-alice: 1597 points
INFO: Calculated initial values for RSI_Bullish_USD on alpha-finance: 1753 points
INFO: Completed signal registration for my-neighbor-alice in 15.76 seconds

Registering signals group 14/44:  40%|████      | 2/5 [00:15<00:25,  8.61s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on pancakeswap-token: 1764 points
INFO: Completed signal registration for pancakeswap-token in 16.12 seconds
INFO: Calculated initial values for RSI_Bullish_BTC on alpha-finance: 1753 points

Registering signals group 14/44:  60%|██████    | 3/5 [00:15<00:09,  4.87s/it]

INFO: Completed signal registration for alpha-finance in 16.41 seconds

Registering signals group 14/44:  80%|████████  | 4/5 [00:16<00:03,  3.03s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on dash: 4183 points
INFO: Calculated initial values for RSI_Bullish_USD on dash: 4183 points
INFO: Calculated initial values for RSI_Bullish_BTC on dash: 4183 points
INFO: Completed signal registration for dash in 21.48 seconds

Registering signals group 14/44: 100%|██████████| 5/5 [00:21<00:00,  4.23s/it]

INFO: Registering 4 new signals for flow
INFO: Registering 4 new signals for book-of-meme
INFO: Registering 4 new signals for balancer

Registering signals group 15/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 4 new signals for render-token
INFO: Registering 4 new signals for pudgy-penguins
INFO: Adapted windows for data length 502: [3, 6, 13, 20, 41, 62, 104]
INFO: Adapted windows for data length 224: [3, 6, 9, 18, 28, 46]
INFO: Calculated initial values for DonchianEnsembleUSD on pudgy-penguins: 224 points
INFO: Calculated initial values for DonchianEnsembleUSD on book-of-meme: 502 points
INFO: Calculated initial values for DonchianEnsembleBTC on pudgy-penguins: 224 points
INFO: Calculated initial values for RSI_Bullish_USD on pudgy-penguins: 224 points
INFO: Calculated initial values for DonchianEnsembleUSD on flow: 1644 points
INFO: Calculated initial values for RSI_Bullish_BTC on pudgy-penguins: 224 points
INFO: Completed signal registration for pudgy-penguins in 3.62 seconds
INFO: Calculated initial values for DonchianEnsembleBTC on book-of-meme: 502 points

Registering signals group 15/44:  20%|██        | 1/5 [00:03<00:14,  3.53s/it]

INFO: Calculated initial values for DonchianEnsembleUSD on balancer: 1862 points
INFO: Calculated initial values for DonchianEnsembleUSD on render-token: 1870 points
INFO: Calculated initial values for RSI_Bullish_USD on book-of-meme: 502 points
INFO: Calculated initial values for RSI_Bullish_BTC on book-of-meme: 502 points
INFO: Completed signal registration for book-of-meme in 5.36 seconds

Registering signals group 15/44:  40%|████      | 2/5 [00:05<00:07,  2.51s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on flow: 1644 points
INFO: Calculated initial values for DonchianEnsembleBTC on balancer: 1862 points
INFO: Calculated initial values for DonchianEnsembleBTC on render-token: 1870 points
INFO: Calculated initial values for RSI_Bullish_USD on flow: 1644 points
INFO: Calculated initial values for RSI_Bullish_BTC on flow: 1644 points
INFO: Completed signal registration for flow in 12.59 seconds

Registering signals group 15/44:  60%|██████    | 3/5 [00:12<00:09,  4.65s/it]

INFO: Calculated initial values for RSI_Bullish_USD on balancer: 1862 points
INFO: Calculated initial values for RSI_Bullish_USD on render-token: 1870 points
INFO: Calculated initial values for RSI_Bullish_BTC on balancer: 1862 points
INFO: Calculated initial values for RSI_Bullish_BTC on render-token: 1870 points
INFO: Completed signal registration for balancer in 13.79 seconds

Registering signals group 15/44:  80%|████████  | 4/5 [00:13<00:03,  3.22s/it]

INFO: Completed signal registration for render-token in 13.86 seconds

Registering signals group 15/44: 100%|██████████| 5/5 [00:13<00:00,  2.72s/it]

INFO: Registering 4 new signals for vela-token
INFO: Registering 4 new signals for cosmos
INFO: Registering 4 new signals for dydx
INFO: Registering 4 new signals for decentraland
INFO: Registering 4 new signals for yield-guild-games

Registering signals group 16/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Calculated initial values for DonchianEnsembleUSD on vela-token: 907 points
INFO: Calculated initial values for DonchianEnsembleUSD on dydx: 1420 points
INFO: Calculated initial values for DonchianEnsembleUSD on yield-guild-games: 1462 points
INFO: Calculated initial values for DonchianEnsembleUSD on cosmos: 2349 points
INFO: Calculated initial values for DonchianEnsembleBTC on vela-token: 907 points
INFO: Calculated initial values for DonchianEnsembleUSD on decentraland: 2831 points
INFO: Calculated initial values for DonchianEnsembleBTC on dydx: 1420 points
INFO: Calculated initial values for DonchianEnsembleBTC on yield-guild-games: 1462 points
INFO: Calculated initial values for RSI_Bullish_USD on vela-token: 907 points
INFO: Calculated initial values for RSI_Bullish_USD on dydx: 1420 points
INFO: Calculated initial values for RSI_Bullish_BTC on dydx: 1420 points
INFO: Calculated initial values for RSI_Bullish_USD on yield-guild-games: 1462 points
INFO: Completed signal registration for dydx in 15.05 seconds

Registering signals group 16/44:  20%|██        | 1/5 [00:14<00:58, 14.62s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on yield-guild-games: 1462 points
INFO: Calculated initial values for DonchianEnsembleBTC on cosmos: 2349 points
INFO: Completed signal registration for yield-guild-games in 15.94 seconds

Registering signals group 16/44:  40%|████      | 2/5 [00:15<00:19,  6.61s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on vela-token: 907 points
INFO: Completed signal registration for vela-token in 17.16 seconds

Registering signals group 16/44:  60%|██████    | 3/5 [00:16<00:08,  4.09s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on decentraland: 2831 points
INFO: Calculated initial values for RSI_Bullish_USD on cosmos: 2349 points
INFO: Calculated initial values for RSI_Bullish_BTC on cosmos: 2349 points
INFO: Completed signal registration for cosmos in 19.77 seconds

Registering signals group 16/44:  80%|████████  | 4/5 [00:19<00:03,  3.51s/it]

INFO: Calculated initial values for RSI_Bullish_USD on decentraland: 2831 points
INFO: Calculated initial values for RSI_Bullish_BTC on decentraland: 2831 points
INFO: Completed signal registration for decentraland in 20.57 seconds

Registering signals group 16/44: 100%|██████████| 5/5 [00:20<00:00,  4.01s/it]

INFO: Registering 4 new signals for anzen-finance

INFO: Registering 4 new signals for ava-ai

Registering signals group 17/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 4 new signals for terra-luna-2
INFO: Registering 4 new signals for chill-guy
INFO: Registering 4 new signals for tron
INFO: Adapted windows for data length 232: [3, 6, 9, 19, 29, 48]
INFO: Adapted windows for data length 250: [3, 6, 10, 20, 31, 52]
INFO: Calculated initial values for DonchianEnsembleUSD on chill-guy: 253 points
INFO: Calculated initial values for DonchianEnsembleUSD on anzen-finance: 232 points
INFO: Calculated initial values for DonchianEnsembleUSD on ava-ai: 250 points
INFO: Calculated initial values for DonchianEnsembleBTC on anzen-finance: 232 points
INFO: Calculated initial values for DonchianEnsembleBTC on chill-guy: 253 points
INFO: Calculated initial values for DonchianEnsembleBTC on ava-ai: 250 points
INFO: Calculated initial values for RSI_Bullish_USD on anzen-finance: 232 points
INFO: Calculated initial values for DonchianEnsembleUSD on terra-luna-2: 1158 points
INFO: Calculated initial values for RSI_Bullish_USD on chill-guy: 253 points
INFO: Calculated initial values for RSI_Bullish_BTC on anzen-finance: 232 points
INFO: Calculated initial values for RSI_Bullish_USD on ava-ai: 250 points
INFO: Calculated initial values for RSI_Bullish_BTC on chill-guy: 253 points
INFO: Completed signal registration for anzen-finance in 2.72 seconds
INFO: Calculated initial values for RSI_Bullish_BTC on ava-ai: 250 points

Registering signals group 17/44:  20%|██        | 1/5 [00:03<00:12,  3.11s/it]

INFO: Completed signal registration for chill-guy in 2.98 seconds
INFO: Completed signal registration for ava-ai in 3.30 seconds

Registering signals group 17/44:  60%|██████    | 3/5 [00:03<00:01,  1.11it/s]

INFO: Calculated initial values for DonchianEnsembleUSD on tron: 2819 points
INFO: Calculated initial values for DonchianEnsembleBTC on terra-luna-2: 1158 points
INFO: Calculated initial values for RSI_Bullish_USD on terra-luna-2: 1158 points
INFO: Calculated initial values for RSI_Bullish_BTC on terra-luna-2: 1158 points
INFO: Completed signal registration for terra-luna-2 in 6.41 seconds

Registering signals group 17/44:  80%|████████  | 4/5 [00:06<00:01,  1.64s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on tron: 2819 points
INFO: Calculated initial values for RSI_Bullish_USD on tron: 2819 points
INFO: Calculated initial values for RSI_Bullish_BTC on tron: 2819 points
INFO: Completed signal registration for tron in 10.16 seconds

Registering signals group 17/44: 100%|██████████| 5/5 [00:10<00:00,  2.03s/it]

INFO: Registering 4 new signals for grass

INFO: Registering 4 new signals for worldcoin-wld
INFO: Registering 4 new signals for bertram-the-pomeranian
INFO: Adapted windows for data length 274: [3, 7, 11, 22, 34, 57]

Registering signals group 18/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 4 new signals for bitcoin-cash
INFO: Registering 4 new signals for polkadot
INFO: Adapted windows for data length 259: [3, 7, 10, 21, 32, 53]
INFO: Calculated initial values for DonchianEnsembleUSD on grass: 274 points
INFO: Calculated initial values for DonchianEnsembleUSD on worldcoin-wld: 736 points
INFO: Calculated initial values for DonchianEnsembleUSD on bertram-the-pomeranian: 259 points
INFO: Calculated initial values for DonchianEnsembleBTC on grass: 274 points
INFO: Calculated initial values for DonchianEnsembleBTC on bertram-the-pomeranian: 259 points
INFO: Calculated initial values for RSI_Bullish_USD on grass: 274 points
INFO: Calculated initial values for RSI_Bullish_USD on bertram-the-pomeranian: 259 points
INFO: Calculated initial values for RSI_Bullish_BTC on grass: 274 points
INFO: Calculated initial values for RSI_Bullish_BTC on bertram-the-pomeranian: 259 points
INFO: Completed signal registration for grass in 3.32 seconds
INFO: Completed signal registration for bertram-the-pomeranian in 3.51 seconds

Registering signals group 18/44:  40%|████      | 2/5 [00:03<00:04,  1.53s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on worldcoin-wld: 736 points
INFO: Calculated initial values for DonchianEnsembleUSD on polkadot: 1805 points
INFO: Calculated initial values for RSI_Bullish_USD on worldcoin-wld: 736 points
INFO: Calculated initial values for DonchianEnsembleUSD on bitcoin-cash: 2918 points
INFO: Calculated initial values for RSI_Bullish_BTC on worldcoin-wld: 736 points
INFO: Completed signal registration for worldcoin-wld in 6.00 seconds

Registering signals group 18/44:  60%|██████    | 3/5 [00:05<00:03,  1.87s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on polkadot: 1805 points
INFO: Calculated initial values for RSI_Bullish_USD on polkadot: 1805 points
INFO: Calculated initial values for RSI_Bullish_BTC on polkadot: 1805 points
INFO: Completed signal registration for polkadot in 11.83 seconds

Registering signals group 18/44:  80%|████████  | 4/5 [00:11<00:03,  3.38s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on bitcoin-cash: 2918 points
INFO: Calculated initial values for RSI_Bullish_USD on bitcoin-cash: 2918 points
INFO: Calculated initial values for RSI_Bullish_BTC on bitcoin-cash: 2918 points
INFO: Completed signal registration for bitcoin-cash in 14.03 seconds

Registering signals group 18/44: 100%|██████████| 5/5 [00:13<00:00,  2.75s/it]

INFO: Registering 4 new signals for lisk
INFO: Registering 4 new signals for aioz-network
INFO: Registering 4 new signals for serum
INFO: Registering 4 new signals for spx6900
INFO: Registering 4 new signals for chainlink

Registering signals group 19/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Adapted windows for data length 701: [4, 9, 19, 29, 58, 87, 146]
INFO: Calculated initial values for DonchianEnsembleUSD on spx6900: 701 points
INFO: Calculated initial values for DonchianEnsembleUSD on aioz-network: 1578 points
INFO: Calculated initial values for DonchianEnsembleUSD on serum: 1813 points
INFO: Calculated initial values for DonchianEnsembleBTC on spx6900: 701 points
INFO: Calculated initial values for RSI_Bullish_USD on spx6900: 701 points
INFO: Calculated initial values for DonchianEnsembleUSD on chainlink: 2819 points
INFO: Calculated initial values for RSI_Bullish_BTC on spx6900: 701 points
INFO: Completed signal registration for spx6900 in 8.89 seconds

Registering signals group 19/44:  20%|██        | 1/5 [00:08<00:34,  8.62s/it]

INFO: Calculated initial values for DonchianEnsembleUSD on lisk: 3401 points
INFO: Calculated initial values for DonchianEnsembleBTC on aioz-network: 1578 points
INFO: Calculated initial values for DonchianEnsembleBTC on serum: 1813 points
INFO: Calculated initial values for RSI_Bullish_USD on aioz-network: 1578 points
INFO: Calculated initial values for RSI_Bullish_BTC on aioz-network: 1578 points
INFO: Completed signal registration for aioz-network in 16.86 seconds

Registering signals group 19/44:  40%|████      | 2/5 [00:16<00:24,  8.20s/it]

INFO: Calculated initial values for RSI_Bullish_USD on serum: 1813 points
INFO: Calculated initial values for RSI_Bullish_BTC on serum: 1813 points
INFO: Completed signal registration for serum in 19.25 seconds

Registering signals group 19/44:  60%|██████    | 3/5 [00:18<00:11,  5.52s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on chainlink: 2819 points
INFO: Calculated initial values for DonchianEnsembleBTC on lisk: 3401 points
INFO: Calculated initial values for RSI_Bullish_USD on chainlink: 2819 points
INFO: Calculated initial values for RSI_Bullish_BTC on chainlink: 2819 points
INFO: Completed signal registration for chainlink in 23.79 seconds

Registering signals group 19/44:  80%|████████  | 4/5 [00:23<00:05,  5.10s/it]

INFO: Calculated initial values for RSI_Bullish_USD on lisk: 3401 points
INFO: Calculated initial values for RSI_Bullish_BTC on lisk: 3401 points
INFO: Completed signal registration for lisk in 24.57 seconds

Registering signals group 19/44: 100%|██████████| 5/5 [00:24<00:00,  4.80s/it]

INFO: Registering 4 new signals for lofi-2
INFO: Registering 4 new signals for arweave
INFO: Registering 4 new signals for mamo

Registering signals group 20/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 4 new signals for nunet
INFO: Registering 4 new signals for lido-dao
INFO: Adapted windows for data length 69: [5, 8, 14, 23]
INFO: Asset mamo: Using 4 windows with threshold 3
INFO: Completed signal registration for lofi-2 in 0.89 seconds

Registering signals group 20/44:  20%|██        | 1/5 [00:00<00:03,  1.12it/s]

INFO: Calculated initial values for DonchianEnsembleUSD on mamo: 69 points
INFO: Calculated initial values for DonchianEnsembleBTC on mamo: 69 points
INFO: Calculated initial values for RSI_Bullish_USD on mamo: 69 points
INFO: Calculated initial values for RSI_Bullish_BTC on mamo: 69 points
INFO: Completed signal registration for mamo in 1.94 seconds

Registering signals group 20/44:  40%|████      | 2/5 [00:01<00:02,  1.04it/s]

INFO: Calculated initial values for DonchianEnsembleUSD on nunet: 1339 points
INFO: Calculated initial values for DonchianEnsembleUSD on lido-dao: 1666 points
INFO: Calculated initial values for DonchianEnsembleUSD on arweave: 2098 points
INFO: Calculated initial values for DonchianEnsembleBTC on nunet: 1339 points
INFO: Calculated initial values for DonchianEnsembleBTC on lido-dao: 1666 points
INFO: Calculated initial values for RSI_Bullish_USD on nunet: 1339 points
INFO: Calculated initial values for RSI_Bullish_BTC on nunet: 1339 points
INFO: Completed signal registration for nunet in 9.79 seconds
INFO: Calculated initial values for DonchianEnsembleBTC on arweave: 2098 points

Registering signals group 20/44:  60%|██████    | 3/5 [00:09<00:08,  4.06s/it]

INFO: Calculated initial values for RSI_Bullish_USD on lido-dao: 1666 points
INFO: Calculated initial values for RSI_Bullish_BTC on lido-dao: 1666 points
INFO: Completed signal registration for lido-dao in 11.02 seconds

Registering signals group 20/44:  80%|████████  | 4/5 [00:10<00:02,  2.92s/it]

INFO: Calculated initial values for RSI_Bullish_USD on arweave: 2098 points
INFO: Calculated initial values for RSI_Bullish_BTC on arweave: 2098 points
INFO: Completed signal registration for arweave in 11.75 seconds

Registering signals group 20/44: 100%|██████████| 5/5 [00:11<00:00,  2.30s/it]

INFO: Registering 4 new signals for genesysgo-shadow
INFO: Registering 4 new signals for cookie
INFO: Registering 4 new signals for bittensor
INFO: Registering 4 new signals for baby-doge-coin

Registering signals group 21/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 4 new signals for badger-dao
INFO: Adapted windows for data length 411: [5, 11, 17, 34, 51, 85]
INFO: Calculated initial values for DonchianEnsembleUSD on cookie: 411 points
INFO: Calculated initial values for DonchianEnsembleUSD on bittensor: 879 points
INFO: Calculated initial values for DonchianEnsembleBTC on cookie: 411 points
INFO: Calculated initial values for DonchianEnsembleUSD on genesysgo-shadow: 1301 points
INFO: Calculated initial values for RSI_Bullish_USD on cookie: 411 points
INFO: Calculated initial values for RSI_Bullish_BTC on cookie: 411 points
INFO: Completed signal registration for cookie in 4.36 seconds

Registering signals group 21/44:  20%|██        | 1/5 [00:04<00:16,  4.24s/it]

INFO: Calculated initial values for DonchianEnsembleUSD on baby-doge-coin: 1511 points
INFO: Calculated initial values for DonchianEnsembleUSD on badger-dao: 1698 points
INFO: Calculated initial values for DonchianEnsembleBTC on bittensor: 879 points
INFO: Calculated initial values for RSI_Bullish_USD on bittensor: 879 points
INFO: Calculated initial values for DonchianEnsembleBTC on genesysgo-shadow: 1301 points
INFO: Calculated initial values for RSI_Bullish_BTC on bittensor: 879 points
INFO: Completed signal registration for bittensor in 9.59 seconds

Registering signals group 21/44:  40%|████      | 2/5 [00:09<00:14,  4.78s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on baby-doge-coin: 1511 points
INFO: Calculated initial values for RSI_Bullish_USD on genesysgo-shadow: 1301 points
INFO: Calculated initial values for DonchianEnsembleBTC on badger-dao: 1698 points
INFO: Calculated initial values for RSI_Bullish_BTC on genesysgo-shadow: 1301 points
INFO: Completed signal registration for genesysgo-shadow in 12.18 seconds

Registering signals group 21/44:  60%|██████    | 3/5 [00:12<00:07,  3.81s/it]

INFO: Calculated initial values for RSI_Bullish_USD on baby-doge-coin: 1511 points
INFO: Calculated initial values for RSI_Bullish_BTC on baby-doge-coin: 1511 points
INFO: Completed signal registration for baby-doge-coin in 13.09 seconds

Registering signals group 21/44:  80%|████████  | 4/5 [00:12<00:02,  2.63s/it]

INFO: Calculated initial values for RSI_Bullish_USD on badger-dao: 1698 points
INFO: Calculated initial values for RSI_Bullish_BTC on badger-dao: 1698 points
INFO: Completed signal registration for badger-dao in 13.39 seconds

Registering signals group 21/44: 100%|██████████| 5/5 [00:13<00:00,  2.62s/it]

INFO: Registering 4 new signals for siren-2
INFO: Registering 4 new signals for kryptonite
INFO: Registering 4 new signals for pepe
INFO: Adapted windows for data length 160: [4, 6, 13, 20, 33]

Registering signals group 22/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 4 new signals for eigenlayer
INFO: Registering 4 new signals for thorchain
INFO: Adapted windows for data length 715: [4, 9, 19, 29, 59, 89, 148]
INFO: Calculated initial values for DonchianEnsembleUSD on siren-2: 160 points
INFO: Adapted windows for data length 301: [4, 8, 12, 25, 37, 62]
INFO: Calculated initial values for DonchianEnsembleUSD on pepe: 833 points
INFO: Calculated initial values for DonchianEnsembleBTC on siren-2: 160 points
INFO: Calculated initial values for DonchianEnsembleUSD on eigenlayer: 301 points
INFO: Calculated initial values for DonchianEnsembleUSD on kryptonite: 715 points
INFO: Calculated initial values for RSI_Bullish_USD on siren-2: 160 points
INFO: Calculated initial values for RSI_Bullish_BTC on siren-2: 160 points
INFO: Completed signal registration for siren-2 in 2.11 seconds

Registering signals group 22/44:  20%|██        | 1/5 [00:02<00:08,  2.16s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on eigenlayer: 301 points
INFO: Calculated initial values for RSI_Bullish_USD on eigenlayer: 301 points
INFO: Calculated initial values for RSI_Bullish_BTC on eigenlayer: 301 points
INFO: Completed signal registration for eigenlayer in 3.49 seconds

Registering signals group 22/44:  40%|████      | 2/5 [00:03<00:05,  1.74s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on kryptonite: 715 points
INFO: Calculated initial values for DonchianEnsembleBTC on pepe: 833 points
INFO: Calculated initial values for DonchianEnsembleUSD on thorchain: 2201 points
INFO: Calculated initial values for RSI_Bullish_USD on kryptonite: 715 points
INFO: Calculated initial values for RSI_Bullish_BTC on kryptonite: 715 points
INFO: Calculated initial values for RSI_Bullish_USD on pepe: 833 points
INFO: Completed signal registration for kryptonite in 5.93 seconds

Registering signals group 22/44:  60%|██████    | 3/5 [00:05<00:03,  2.00s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on pepe: 833 points
INFO: Completed signal registration for pepe in 6.20 seconds

Registering signals group 22/44:  80%|████████  | 4/5 [00:06<00:01,  1.27s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on thorchain: 2201 points
INFO: Calculated initial values for RSI_Bullish_USD on thorchain: 2201 points
INFO: Calculated initial values for RSI_Bullish_BTC on thorchain: 2201 points
INFO: Completed signal registration for thorchain in 9.64 seconds

Registering signals group 22/44: 100%|██████████| 5/5 [00:09<00:00,  1.90s/it]

INFO: Registering 4 new signals for conic-finance
INFO: Registering 4 new signals for compound-governance-token
INFO: Registering 4 new signals for raydium
INFO: Registering 4 new signals for immutable-x

Registering signals group 23/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 4 new signals for the-open-network
INFO: Calculated initial values for DonchianEnsembleUSD on conic-finance: 1016 points
INFO: Calculated initial values for DonchianEnsembleUSD on immutable-x: 1362 points
INFO: Calculated initial values for DonchianEnsembleUSD on raydium: 1619 points
INFO: Calculated initial values for DonchianEnsembleUSD on the-open-network: 1432 points
INFO: Calculated initial values for DonchianEnsembleUSD on compound-governance-token: 1869 points
INFO: Calculated initial values for DonchianEnsembleBTC on conic-finance: 1016 points
INFO: Calculated initial values for DonchianEnsembleBTC on immutable-x: 1362 points
INFO: Calculated initial values for DonchianEnsembleBTC on the-open-network: 1432 points
INFO: Calculated initial values for DonchianEnsembleBTC on raydium: 1619 points
INFO: Calculated initial values for RSI_Bullish_USD on conic-finance: 1016 points
INFO: Calculated initial values for DonchianEnsembleBTC on compound-governance-token: 1869 points
INFO: Calculated initial values for RSI_Bullish_BTC on conic-finance: 1016 points
INFO: Calculated initial values for RSI_Bullish_USD on immutable-x: 1362 points
INFO: Calculated initial values for RSI_Bullish_USD on the-open-network: 1432 points
INFO: Completed signal registration for conic-finance in 16.81 seconds

Registering signals group 23/44:  20%|██        | 1/5 [00:16<01:05, 16.39s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on immutable-x: 1362 points
INFO: Calculated initial values for RSI_Bullish_USD on raydium: 1619 points
INFO: Calculated initial values for RSI_Bullish_BTC on the-open-network: 1432 points
INFO: Completed signal registration for immutable-x in 17.40 seconds

Registering signals group 23/44:  40%|████      | 2/5 [00:16<00:21,  7.02s/it]

INFO: Completed signal registration for the-open-network in 17.59 seconds

Registering signals group 23/44:  60%|██████    | 3/5 [00:17<00:07,  3.93s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on raydium: 1619 points
INFO: Completed signal registration for raydium in 18.05 seconds

Registering signals group 23/44:  80%|████████  | 4/5 [00:17<00:02,  2.52s/it]

INFO: Calculated initial values for RSI_Bullish_USD on compound-governance-token: 1869 points
INFO: Calculated initial values for RSI_Bullish_BTC on compound-governance-token: 1869 points
INFO: Completed signal registration for compound-governance-token in 18.36 seconds

Registering signals group 23/44: 100%|██████████| 5/5 [00:17<00:00,  3.55s/it]

INFO: Registering 4 new signals for metacade
INFO: Registering 4 new signals for clearpool
INFO: Registering 4 new signals for prometeus

Registering signals group 24/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 4 new signals for wibx
INFO: Registering 4 new signals for sei-network
INFO: Adapted windows for data length 714: [4, 9, 19, 29, 59, 89, 148]
INFO: Calculated initial values for DonchianEnsembleUSD on metacade: 840 points
INFO: Calculated initial values for DonchianEnsembleUSD on sei-network: 714 points
INFO: Calculated initial values for DonchianEnsembleUSD on clearpool: 1370 points
INFO: Calculated initial values for DonchianEnsembleBTC on sei-network: 714 points
INFO: Calculated initial values for DonchianEnsembleUSD on wibx: 1929 points
INFO: Calculated initial values for DonchianEnsembleUSD on prometeus: 2223 points
INFO: Calculated initial values for DonchianEnsembleBTC on metacade: 840 points
INFO: Calculated initial values for RSI_Bullish_USD on sei-network: 714 points
INFO: Calculated initial values for RSI_Bullish_BTC on sei-network: 714 points
INFO: Calculated initial values for RSI_Bullish_USD on metacade: 840 points
INFO: Completed signal registration for sei-network in 10.04 seconds

Registering signals group 24/44:  20%|██        | 1/5 [00:10<00:40, 10.10s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on metacade: 840 points
INFO: Completed signal registration for metacade in 11.19 seconds

Registering signals group 24/44:  40%|████      | 2/5 [00:11<00:14,  4.78s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on clearpool: 1370 points
INFO: Calculated initial values for RSI_Bullish_USD on clearpool: 1370 points
INFO: Calculated initial values for DonchianEnsembleBTC on wibx: 1929 points
INFO: Calculated initial values for RSI_Bullish_BTC on clearpool: 1370 points
INFO: Completed signal registration for clearpool in 15.68 seconds

Registering signals group 24/44:  60%|██████    | 3/5 [00:15<00:09,  4.68s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on prometeus: 2223 points
INFO: Calculated initial values for RSI_Bullish_USD on wibx: 1929 points
INFO: Calculated initial values for RSI_Bullish_BTC on wibx: 1929 points
INFO: Completed signal registration for wibx in 17.97 seconds

Registering signals group 24/44:  80%|████████  | 4/5 [00:17<00:03,  3.72s/it]

INFO: Calculated initial values for RSI_Bullish_USD on prometeus: 2223 points
INFO: Calculated initial values for RSI_Bullish_BTC on prometeus: 2223 points
INFO: Completed signal registration for prometeus in 18.60 seconds

Registering signals group 24/44: 100%|██████████| 5/5 [00:18<00:00,  3.70s/it]

INFO: Registering 4 new signals for guild-of-guardians
INFO: Registering 4 new signals for sturdy
INFO: Registering 4 new signals for tether

Registering signals group 25/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 4 new signals for echelon-prime
INFO: Registering 4 new signals for usd-coin
INFO: Adapted windows for data length 523: [3, 7, 14, 21, 43, 65, 108]
INFO: Calculated initial values for DonchianEnsembleUSD on sturdy: 523 points
INFO: Calculated initial values for DonchianEnsembleUSD on echelon-prime: 880 points
INFO: Calculated initial values for DonchianEnsembleUSD on guild-of-guardians: 1315 points
INFO: Calculated initial values for DonchianEnsembleBTC on sturdy: 523 points
INFO: Calculated initial values for RSI_Bullish_USD on sturdy: 523 points
INFO: Calculated initial values for RSI_Bullish_BTC on sturdy: 523 points
INFO: Completed signal registration for sturdy in 12.83 seconds

Registering signals group 25/44:  20%|██        | 1/5 [00:13<00:52, 13.06s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on echelon-prime: 880 points
INFO: Calculated initial values for DonchianEnsembleUSD on usd-coin: 2490 points
INFO: Calculated initial values for DonchianEnsembleBTC on guild-of-guardians: 1315 points
INFO: Calculated initial values for RSI_Bullish_USD on echelon-prime: 880 points
INFO: Calculated initial values for DonchianEnsembleUSD on tether: 3807 points
INFO: Calculated initial values for RSI_Bullish_BTC on echelon-prime: 880 points
INFO: Completed signal registration for echelon-prime in 20.82 seconds

Registering signals group 25/44:  40%|████      | 2/5 [00:20<00:30, 10.02s/it]

INFO: Calculated initial values for RSI_Bullish_USD on guild-of-guardians: 1315 points
INFO: Calculated initial values for RSI_Bullish_BTC on guild-of-guardians: 1315 points
INFO: Completed signal registration for guild-of-guardians in 24.27 seconds

Registering signals group 25/44:  60%|██████    | 3/5 [00:24<00:13,  6.99s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on usd-coin: 2490 points
INFO: Calculated initial values for RSI_Bullish_USD on usd-coin: 2490 points
INFO: Calculated initial values for RSI_Bullish_BTC on usd-coin: 2490 points
INFO: Calculated initial values for DonchianEnsembleBTC on tether: 3807 points
INFO: Completed signal registration for usd-coin in 31.31 seconds

Registering signals group 25/44:  80%|████████  | 4/5 [00:31<00:06,  6.96s/it]

INFO: Calculated initial values for RSI_Bullish_USD on tether: 3807 points
INFO: Calculated initial values for RSI_Bullish_BTC on tether: 3807 points
INFO: Completed signal registration for tether in 34.47 seconds

Registering signals group 25/44: 100%|██████████| 5/5 [00:34<00:00,  6.87s/it]

INFO: Registering 4 new signals for arpa
INFO: Registering 4 new signals for celestia

Registering signals group 26/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 4 new signals for spell-token
INFO: Registering 4 new signals for ai16z
INFO: Registering 4 new signals for arbitrum
INFO: Adapted windows for data length 637: [4, 8, 17, 26, 53, 79, 132]
INFO: Adapted windows for data length 275: [3, 7, 11, 22, 34, 57]
INFO: Calculated initial values for DonchianEnsembleUSD on ai16z: 275 points
INFO: Calculated initial values for DonchianEnsembleUSD on celestia: 637 points
INFO: Calculated initial values for DonchianEnsembleBTC on ai16z: 275 points
INFO: Calculated initial values for DonchianEnsembleUSD on arbitrum: 859 points
INFO: Calculated initial values for RSI_Bullish_USD on ai16z: 275 points
INFO: Calculated initial values for RSI_Bullish_BTC on ai16z: 275 points
INFO: Calculated initial values for DonchianEnsembleUSD on spell-token: 1523 points
INFO: Completed signal registration for ai16z in 3.59 seconds

Registering signals group 26/44:  20%|██        | 1/5 [00:03<00:15,  3.90s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on celestia: 637 points
INFO: Calculated initial values for DonchianEnsembleUSD on arpa: 2254 points
INFO: Calculated initial values for RSI_Bullish_USD on celestia: 637 points
INFO: Calculated initial values for DonchianEnsembleBTC on arbitrum: 859 points
INFO: Calculated initial values for RSI_Bullish_BTC on celestia: 637 points
INFO: Completed signal registration for celestia in 6.46 seconds

Registering signals group 26/44:  40%|████      | 2/5 [00:06<00:09,  3.14s/it]

INFO: Calculated initial values for RSI_Bullish_USD on arbitrum: 859 points
INFO: Calculated initial values for RSI_Bullish_BTC on arbitrum: 859 points
INFO: Completed signal registration for arbitrum in 8.45 seconds

Registering signals group 26/44:  60%|██████    | 3/5 [00:08<00:05,  2.57s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on spell-token: 1523 points
INFO: Calculated initial values for RSI_Bullish_USD on spell-token: 1523 points
INFO: Calculated initial values for RSI_Bullish_BTC on spell-token: 1523 points
INFO: Calculated initial values for DonchianEnsembleBTC on arpa: 2254 points
INFO: Completed signal registration for spell-token in 11.40 seconds

Registering signals group 26/44:  80%|████████  | 4/5 [00:11<00:02,  2.72s/it]

INFO: Calculated initial values for RSI_Bullish_USD on arpa: 2254 points
INFO: Calculated initial values for RSI_Bullish_BTC on arpa: 2254 points
INFO: Completed signal registration for arpa in 13.08 seconds

Registering signals group 26/44: 100%|██████████| 5/5 [00:12<00:00,  2.59s/it]

INFO: Registering 4 new signals for deep
INFO: Registering 4 new signals for power-ledger
INFO: Registering 4 new signals for tribe-2
INFO: Adapted windows for data length 288: [4, 8, 12, 24, 36, 60]

Registering signals group 27/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 4 new signals for virtual-protocol
INFO: Registering 4 new signals for smartcash
INFO: Adapted windows for data length 579: [4, 8, 16, 24, 48, 72, 120]
INFO: Calculated initial values for DonchianEnsembleUSD on deep: 288 points
INFO: Calculated initial values for DonchianEnsembleUSD on virtual-protocol: 579 points
INFO: Calculated initial values for DonchianEnsembleBTC on deep: 288 points
INFO: Calculated initial values for RSI_Bullish_USD on deep: 288 points
INFO: Calculated initial values for RSI_Bullish_BTC on deep: 288 points
INFO: Completed signal registration for deep in 7.40 seconds

Registering signals group 27/44:  20%|██        | 1/5 [00:07<00:29,  7.27s/it]

INFO: Calculated initial values for DonchianEnsembleUSD on tribe-2: 1578 points
INFO: Calculated initial values for DonchianEnsembleBTC on virtual-protocol: 579 points
INFO: Calculated initial values for RSI_Bullish_USD on virtual-protocol: 579 points
INFO: Calculated initial values for RSI_Bullish_BTC on virtual-protocol: 579 points
INFO: Calculated initial values for DonchianEnsembleUSD on power-ledger: 2820 points
INFO: Completed signal registration for virtual-protocol in 10.52 seconds

Registering signals group 27/44:  40%|████      | 2/5 [00:10<00:14,  4.84s/it]

INFO: Calculated initial values for DonchianEnsembleUSD on smartcash: 2882 points
INFO: Calculated initial values for DonchianEnsembleBTC on tribe-2: 1578 points
INFO: Calculated initial values for RSI_Bullish_USD on tribe-2: 1578 points
INFO: Calculated initial values for RSI_Bullish_BTC on tribe-2: 1578 points
INFO: Completed signal registration for tribe-2 in 17.79 seconds

Registering signals group 27/44:  60%|██████    | 3/5 [00:17<00:11,  5.87s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on power-ledger: 2820 points
INFO: Calculated initial values for DonchianEnsembleBTC on smartcash: 2882 points
INFO: Calculated initial values for RSI_Bullish_USD on power-ledger: 2820 points
INFO: Calculated initial values for RSI_Bullish_USD on smartcash: 2882 points
INFO: Calculated initial values for RSI_Bullish_BTC on power-ledger: 2820 points
INFO: Completed signal registration for power-ledger in 23.07 seconds

Registering signals group 27/44:  80%|████████  | 4/5 [00:22<00:05,  5.62s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on smartcash: 2882 points
INFO: Completed signal registration for smartcash in 23.30 seconds

Registering signals group 27/44: 100%|██████████| 5/5 [00:22<00:00,  4.59s/it]

INFO: Registering 4 new signals for tokenbot-2
INFO: Registering 4 new signals for ethervista

Registering signals group 28/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Adapted windows for data length 261: [3, 7, 10, 21, 32, 54]
INFO: Registering 4 new signals for kujira
INFO: Registering 4 new signals for orbit-3
INFO: Registering 4 new signals for ethereum
INFO: Adapted windows for data length 331: [4, 9, 13, 27, 41, 68]
INFO: Calculated initial values for DonchianEnsembleUSD on tokenbot-2: 261 points
INFO: Adapted windows for data length 233: [3, 6, 9, 19, 29, 48]
INFO: Calculated initial values for DonchianEnsembleUSD on ethervista: 331 points
INFO: Calculated initial values for DonchianEnsembleUSD on orbit-3: 233 points
INFO: Calculated initial values for DonchianEnsembleBTC on tokenbot-2: 261 points
INFO: Calculated initial values for DonchianEnsembleBTC on ethervista: 331 points
INFO: Calculated initial values for RSI_Bullish_USD on tokenbot-2: 261 points
INFO: Calculated initial values for DonchianEnsembleBTC on orbit-3: 233 points
INFO: Calculated initial values for RSI_Bullish_BTC on tokenbot-2: 261 points
INFO: Calculated initial values for DonchianEnsembleUSD on kujira: 1341 points
INFO: Calculated initial values for RSI_Bullish_USD on ethervista: 331 points
INFO: Completed signal registration for tokenbot-2 in 2.47 seconds

Registering signals group 28/44:  20%|██        | 1/5 [00:02<00:11,  2.82s/it]

INFO: Calculated initial values for RSI_Bullish_USD on orbit-3: 233 points
INFO: Calculated initial values for RSI_Bullish_BTC on ethervista: 331 points
INFO: Calculated initial values for RSI_Bullish_BTC on orbit-3: 233 points
INFO: Completed signal registration for ethervista in 3.16 seconds

Registering signals group 28/44:  40%|████      | 2/5 [00:03<00:04,  1.43s/it]

INFO: Completed signal registration for orbit-3 in 3.22 seconds

Registering signals group 28/44:  60%|██████    | 3/5 [00:03<00:01,  1.14it/s]

INFO: Calculated initial values for DonchianEnsembleUSD on ethereum: 3644 points
INFO: Calculated initial values for DonchianEnsembleBTC on kujira: 1341 points
INFO: Calculated initial values for RSI_Bullish_USD on kujira: 1341 points
INFO: Calculated initial values for RSI_Bullish_BTC on kujira: 1341 points
INFO: Completed signal registration for kujira in 7.66 seconds

Registering signals group 28/44:  80%|████████  | 4/5 [00:07<00:02,  2.21s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on ethereum: 3644 points
INFO: Calculated initial values for RSI_Bullish_USD on ethereum: 3644 points
INFO: Calculated initial values for RSI_Bullish_BTC on ethereum: 3644 points
INFO: Completed signal registration for ethereum in 12.97 seconds

Registering signals group 28/44: 100%|██████████| 5/5 [00:12<00:00,  2.59s/it]

INFO: Registering 4 new signals for griffain
INFO: Registering 4 new signals for kaspa
INFO: Registering 4 new signals for new-xai-gork
INFO: Registering 4 new signals for audius

Registering signals group 29/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Adapted windows for data length 235: [3, 6, 9, 19, 29, 48]
INFO: Registering 4 new signals for arkham
INFO: Adapted windows for data length 88: [3, 7, 11, 18]
INFO: Calculated initial values for DonchianEnsembleUSD on griffain: 235 points
INFO: Calculated initial values for DonchianEnsembleUSD on new-xai-gork: 88 points
INFO: Calculated initial values for DonchianEnsembleBTC on new-xai-gork: 88 points
INFO: Calculated initial values for RSI_Bullish_USD on new-xai-gork: 88 points
INFO: Calculated initial values for DonchianEnsembleBTC on griffain: 235 points
INFO: Calculated initial values for RSI_Bullish_BTC on new-xai-gork: 88 points
INFO: Calculated initial values for DonchianEnsembleUSD on kaspa: 1161 points
INFO: Completed signal registration for new-xai-gork in 1.86 seconds

Registering signals group 29/44:  20%|██        | 1/5 [00:01<00:07,  1.76s/it]

INFO: Calculated initial values for DonchianEnsembleUSD on arkham: 742 points
INFO: Calculated initial values for RSI_Bullish_USD on griffain: 235 points
INFO: Calculated initial values for RSI_Bullish_BTC on griffain: 235 points
INFO: Completed signal registration for griffain in 2.73 seconds
INFO: Calculated initial values for DonchianEnsembleUSD on audius: 1740 points

Registering signals group 29/44:  40%|████      | 2/5 [00:02<00:03,  1.24s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on arkham: 742 points
INFO: Calculated initial values for DonchianEnsembleBTC on kaspa: 1161 points
INFO: Calculated initial values for RSI_Bullish_USD on arkham: 742 points
INFO: Calculated initial values for RSI_Bullish_BTC on arkham: 742 points
INFO: Completed signal registration for arkham in 6.36 seconds

Registering signals group 29/44:  60%|██████    | 3/5 [00:06<00:04,  2.34s/it]

INFO: Calculated initial values for RSI_Bullish_USD on kaspa: 1161 points
INFO: Calculated initial values for RSI_Bullish_BTC on kaspa: 1161 points
INFO: Calculated initial values for DonchianEnsembleBTC on audius: 1740 points
INFO: Completed signal registration for kaspa in 7.31 seconds

Registering signals group 29/44:  80%|████████  | 4/5 [00:07<00:01,  1.76s/it]

INFO: Calculated initial values for RSI_Bullish_USD on audius: 1740 points
INFO: Calculated initial values for RSI_Bullish_BTC on audius: 1740 points
INFO: Completed signal registration for audius in 8.48 seconds

Registering signals group 29/44: 100%|██████████| 5/5 [00:08<00:00,  1.65s/it]

INFO: Registering 4 new signals for useless-3
INFO: Registering 4 new signals for blockstack
INFO: Registering 4 new signals for yne
INFO: Registering 4 new signals for evan-2

Registering signals group 30/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Adapted windows for data length 79: [3, 6, 9, 16]
INFO: Registering 4 new signals for botto
INFO: Adapted windows for data length 218: [3, 6, 9, 18, 27, 45]
INFO: Calculated initial values for DonchianEnsembleUSD on evan-2: 249 points
INFO: Calculated initial values for DonchianEnsembleUSD on useless-3: 79 points
INFO: Asset yne: Using 6 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleBTC on useless-3: 79 points
INFO: Calculated initial values for DonchianEnsembleUSD on yne: 218 points
INFO: Calculated initial values for RSI_Bullish_USD on useless-3: 79 points
INFO: Calculated initial values for DonchianEnsembleBTC on evan-2: 249 points
INFO: Calculated initial values for RSI_Bullish_BTC on useless-3: 79 points
INFO: Completed signal registration for useless-3 in 2.05 seconds
INFO: Calculated initial values for DonchianEnsembleBTC on yne: 218 points

Registering signals group 30/44:  20%|██        | 1/5 [00:02<00:08,  2.08s/it]

INFO: Calculated initial values for RSI_Bullish_USD on evan-2: 249 points
INFO: Calculated initial values for RSI_Bullish_USD on yne: 218 points
INFO: Calculated initial values for RSI_Bullish_BTC on evan-2: 249 points
INFO: Calculated initial values for RSI_Bullish_BTC on yne: 218 points
INFO: Calculated initial values for DonchianEnsembleUSD on botto: 1389 points
INFO: Completed signal registration for evan-2 in 2.85 seconds
INFO: Completed signal registration for yne in 2.90 seconds

Registering signals group 30/44:  40%|████      | 2/5 [00:02<00:03,  1.28s/it]

INFO: Calculated initial values for DonchianEnsembleUSD on blockstack: 2105 points
INFO: Calculated initial values for DonchianEnsembleBTC on botto: 1389 points
INFO: Calculated initial values for RSI_Bullish_USD on botto: 1389 points
INFO: Calculated initial values for DonchianEnsembleBTC on blockstack: 2105 points
INFO: Calculated initial values for RSI_Bullish_BTC on botto: 1389 points
INFO: Completed signal registration for botto in 7.69 seconds

Registering signals group 30/44:  80%|████████  | 4/5 [00:07<00:01,  1.98s/it]

INFO: Calculated initial values for RSI_Bullish_USD on blockstack: 2105 points
INFO: Calculated initial values for RSI_Bullish_BTC on blockstack: 2105 points
INFO: Completed signal registration for blockstack in 8.93 seconds

Registering signals group 30/44: 100%|██████████| 5/5 [00:08<00:00,  1.75s/it]

INFO: Registering 4 new signals for maker
INFO: Registering 4 new signals for instadapp
INFO: Registering 4 new signals for venice-token

Registering signals group 31/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 4 new signals for sushi
INFO: Registering 4 new signals for akash-network
INFO: Adapted windows for data length 183: [5, 7, 15, 22, 38]
INFO: Calculated initial values for DonchianEnsembleUSD on venice-token: 183 points
INFO: Calculated initial values for DonchianEnsembleBTC on venice-token: 183 points
INFO: Calculated initial values for RSI_Bullish_USD on venice-token: 183 points
INFO: Calculated initial values for RSI_Bullish_BTC on venice-token: 183 points
INFO: Completed signal registration for venice-token in 3.06 seconds

Registering signals group 31/44:  20%|██        | 1/5 [00:03<00:12,  3.06s/it]

INFO: Calculated initial values for DonchianEnsembleUSD on instadapp: 1504 points
INFO: Calculated initial values for DonchianEnsembleUSD on sushi: 1796 points
INFO: Calculated initial values for DonchianEnsembleUSD on akash-network: 1747 points
INFO: Calculated initial values for DonchianEnsembleUSD on maker: 2778 points
INFO: Calculated initial values for DonchianEnsembleBTC on instadapp: 1504 points
INFO: Calculated initial values for DonchianEnsembleBTC on sushi: 1796 points
INFO: Calculated initial values for DonchianEnsembleBTC on akash-network: 1747 points
INFO: Calculated initial values for RSI_Bullish_USD on instadapp: 1504 points
INFO: Calculated initial values for RSI_Bullish_BTC on instadapp: 1504 points
INFO: Completed signal registration for instadapp in 14.97 seconds

Registering signals group 31/44:  40%|████      | 2/5 [00:14<00:24,  8.25s/it]

INFO: Calculated initial values for RSI_Bullish_USD on sushi: 1796 points
INFO: Calculated initial values for RSI_Bullish_USD on akash-network: 1747 points
INFO: Calculated initial values for DonchianEnsembleBTC on maker: 2778 points
INFO: Calculated initial values for RSI_Bullish_BTC on sushi: 1796 points
INFO: Calculated initial values for RSI_Bullish_BTC on akash-network: 1747 points
INFO: Completed signal registration for sushi in 16.63 seconds
INFO: Completed signal registration for akash-network in 16.75 seconds

Registering signals group 31/44:  80%|████████  | 4/5 [00:16<00:03,  3.19s/it]

INFO: Calculated initial values for RSI_Bullish_USD on maker: 2778 points
INFO: Calculated initial values for RSI_Bullish_BTC on maker: 2778 points
INFO: Completed signal registration for maker in 18.56 seconds

Registering signals group 31/44: 100%|██████████| 5/5 [00:18<00:00,  3.66s/it]

INFO: Registering 4 new signals for eos
INFO: Registering 4 new signals for verasity

Registering signals group 32/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 4 new signals for story-2
INFO: Registering 4 new signals for gains-network
INFO: Registering 4 new signals for arbdoge-ai
INFO: Adapted windows for data length 166: [4, 6, 13, 20, 34]
INFO: Calculated initial values for DonchianEnsembleUSD on story-2: 166 points
INFO: Calculated initial values for DonchianEnsembleBTC on story-2: 166 points
INFO: Calculated initial values for RSI_Bullish_USD on story-2: 166 points
INFO: Calculated initial values for RSI_Bullish_BTC on story-2: 166 points
INFO: Calculated initial values for DonchianEnsembleUSD on arbdoge-ai: 833 points
INFO: Completed signal registration for story-2 in 2.89 seconds

Registering signals group 32/44:  20%|██        | 1/5 [00:02<00:11,  2.90s/it]

INFO: Calculated initial values for DonchianEnsembleUSD on gains-network: 1365 points
INFO: Calculated initial values for DonchianEnsembleUSD on verasity: 1620 points
INFO: Calculated initial values for DonchianEnsembleUSD on eos: 2942 points
INFO: Calculated initial values for DonchianEnsembleBTC on arbdoge-ai: 833 points
INFO: Calculated initial values for RSI_Bullish_USD on arbdoge-ai: 833 points
INFO: Calculated initial values for RSI_Bullish_BTC on arbdoge-ai: 833 points
INFO: Calculated initial values for DonchianEnsembleBTC on gains-network: 1365 points
INFO: Completed signal registration for arbdoge-ai in 8.77 seconds

Registering signals group 32/44:  40%|████      | 2/5 [00:08<00:13,  4.63s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on verasity: 1620 points
INFO: Calculated initial values for RSI_Bullish_USD on gains-network: 1365 points
INFO: Calculated initial values for RSI_Bullish_BTC on gains-network: 1365 points
INFO: Completed signal registration for gains-network in 11.81 seconds
INFO: Calculated initial values for RSI_Bullish_USD on verasity: 1620 points

Registering signals group 32/44:  60%|██████    | 3/5 [00:11<00:07,  3.84s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on verasity: 1620 points
INFO: Completed signal registration for verasity in 12.44 seconds

Registering signals group 32/44:  80%|████████  | 4/5 [00:12<00:02,  2.58s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on eos: 2942 points
INFO: Calculated initial values for RSI_Bullish_USD on eos: 2942 points
INFO: Calculated initial values for RSI_Bullish_BTC on eos: 2942 points
INFO: Completed signal registration for eos in 15.22 seconds

Registering signals group 32/44: 100%|██████████| 5/5 [00:14<00:00,  2.99s/it]

INFO: Registering 4 new signals for bonk
INFO: Registering 4 new signals for numeraire
INFO: Registering 4 new signals for plume

Registering signals group 33/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 4 new signals for sonic-3
INFO: Registering 4 new signals for jupiter-exchange-solana
INFO: Adapted windows for data length 189: [5, 7, 15, 23, 39]
INFO: Adapted windows for data length 206: [5, 8, 17, 25, 42]
INFO: Adapted windows for data length 545: [3, 7, 15, 22, 45, 68, 113]
INFO: Calculated initial values for DonchianEnsembleUSD on plume: 189 points
INFO: Calculated initial values for DonchianEnsembleUSD on sonic-3: 206 points
INFO: Calculated initial values for DonchianEnsembleUSD on bonk: 943 points
INFO: Calculated initial values for DonchianEnsembleBTC on plume: 189 points
INFO: Calculated initial values for DonchianEnsembleUSD on jupiter-exchange-solana: 545 points
INFO: Calculated initial values for DonchianEnsembleBTC on sonic-3: 206 points
INFO: Calculated initial values for RSI_Bullish_USD on plume: 189 points
INFO: Calculated initial values for RSI_Bullish_BTC on plume: 189 points
INFO: Calculated initial values for RSI_Bullish_USD on sonic-3: 206 points
INFO: Completed signal registration for plume in 2.37 seconds

Registering signals group 33/44:  20%|██        | 1/5 [00:02<00:09,  2.41s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on sonic-3: 206 points
INFO: Completed signal registration for sonic-3 in 2.80 seconds

Registering signals group 33/44:  40%|████      | 2/5 [00:02<00:03,  1.22s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on jupiter-exchange-solana: 545 points
INFO: Calculated initial values for DonchianEnsembleBTC on bonk: 943 points
INFO: Calculated initial values for RSI_Bullish_USD on jupiter-exchange-solana: 545 points
INFO: Calculated initial values for RSI_Bullish_BTC on jupiter-exchange-solana: 545 points
INFO: Calculated initial values for DonchianEnsembleUSD on numeraire: 2938 points
INFO: Completed signal registration for jupiter-exchange-solana in 4.51 seconds

Registering signals group 33/44:  60%|██████    | 3/5 [00:04<00:02,  1.40s/it]

INFO: Calculated initial values for RSI_Bullish_USD on bonk: 943 points
INFO: Calculated initial values for RSI_Bullish_BTC on bonk: 943 points
INFO: Completed signal registration for bonk in 5.50 seconds

Registering signals group 33/44:  80%|████████  | 4/5 [00:05<00:01,  1.21s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on numeraire: 2938 points
INFO: Calculated initial values for RSI_Bullish_USD on numeraire: 2938 points
INFO: Calculated initial values for RSI_Bullish_BTC on numeraire: 2938 points
INFO: Completed signal registration for numeraire in 10.52 seconds

Registering signals group 33/44: 100%|██████████| 5/5 [00:10<00:00,  2.05s/it]

INFO: Registering 4 new signals for star-atlas-dao
INFO: Registering 4 new signals for hedera-hashgraph
INFO: Registering 4 new signals for solayer

Registering signals group 34/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 4 new signals for aerodrome-finance
INFO: Registering 4 new signals for perpetual-protocol
INFO: Adapted windows for data length 168: [4, 7, 14, 21, 35]
INFO: Adapted windows for data length 683: [4, 9, 18, 28, 56, 85, 142]
INFO: Calculated initial values for DonchianEnsembleUSD on solayer: 168 points
INFO: Calculated initial values for DonchianEnsembleBTC on solayer: 168 points
INFO: Calculated initial values for RSI_Bullish_USD on solayer: 168 points
INFO: Calculated initial values for DonchianEnsembleUSD on aerodrome-finance: 683 points
INFO: Calculated initial values for RSI_Bullish_BTC on solayer: 168 points
INFO: Calculated initial values for DonchianEnsembleUSD on star-atlas-dao: 1426 points
INFO: Completed signal registration for solayer in 2.89 seconds

Registering signals group 34/44:  20%|██        | 1/5 [00:03<00:12,  3.11s/it]

INFO: Calculated initial values for DonchianEnsembleUSD on hedera-hashgraph: 2142 points
INFO: Calculated initial values for DonchianEnsembleUSD on perpetual-protocol: 1784 points
INFO: Calculated initial values for DonchianEnsembleBTC on aerodrome-finance: 683 points
INFO: Calculated initial values for RSI_Bullish_USD on aerodrome-finance: 683 points
INFO: Calculated initial values for RSI_Bullish_BTC on aerodrome-finance: 683 points
INFO: Completed signal registration for aerodrome-finance in 7.54 seconds

Registering signals group 34/44:  40%|████      | 2/5 [00:07<00:11,  3.83s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on star-atlas-dao: 1426 points
INFO: Calculated initial values for DonchianEnsembleBTC on perpetual-protocol: 1784 points
INFO: Calculated initial values for RSI_Bullish_USD on star-atlas-dao: 1426 points
INFO: Calculated initial values for DonchianEnsembleBTC on hedera-hashgraph: 2142 points
INFO: Calculated initial values for RSI_Bullish_BTC on star-atlas-dao: 1426 points
INFO: Completed signal registration for star-atlas-dao in 12.40 seconds

Registering signals group 34/44:  60%|██████    | 3/5 [00:12<00:08,  4.31s/it]

INFO: Calculated initial values for RSI_Bullish_USD on perpetual-protocol: 1784 points
INFO: Calculated initial values for RSI_Bullish_BTC on perpetual-protocol: 1784 points
INFO: Completed signal registration for perpetual-protocol in 14.10 seconds
INFO: Calculated initial values for RSI_Bullish_USD on hedera-hashgraph: 2142 points

Registering signals group 34/44:  80%|████████  | 4/5 [00:13<00:03,  3.21s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on hedera-hashgraph: 2142 points
INFO: Completed signal registration for hedera-hashgraph in 14.31 seconds

Registering signals group 34/44: 100%|██████████| 5/5 [00:14<00:00,  2.81s/it]

INFO: Registering 4 new signals for fwog
INFO: Registering 4 new signals for chex-token

Registering signals group 35/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 4 new signals for official-trump
INFO: Registering 4 new signals for matic-network
INFO: Registering 4 new signals for alchemy-pay
INFO: Adapted windows for data length 364: [5, 10, 15, 30, 45, 75]
INFO: Adapted windows for data length 192: [5, 8, 16, 24, 40]
INFO: Calculated initial values for DonchianEnsembleUSD on official-trump: 192 points
INFO: Calculated initial values for DonchianEnsembleUSD on fwog: 364 points
INFO: Calculated initial values for DonchianEnsembleBTC on official-trump: 192 points
INFO: Calculated initial values for RSI_Bullish_USD on official-trump: 192 points
INFO: Calculated initial values for RSI_Bullish_BTC on official-trump: 192 points
INFO: Completed signal registration for official-trump in 2.69 seconds
INFO: Calculated initial values for DonchianEnsembleBTC on fwog: 364 points

Registering signals group 35/44:  20%|██        | 1/5 [00:03<00:12,  3.00s/it]

INFO: Calculated initial values for RSI_Bullish_USD on fwog: 364 points
INFO: Calculated initial values for DonchianEnsembleUSD on chex-token: 2001 points
INFO: Calculated initial values for RSI_Bullish_BTC on fwog: 364 points
INFO: Completed signal registration for fwog in 4.12 seconds

Registering signals group 35/44:  40%|████      | 2/5 [00:04<00:05,  1.91s/it]

INFO: Calculated initial values for DonchianEnsembleUSD on alchemy-pay: 1785 points
INFO: Calculated initial values for DonchianEnsembleUSD on matic-network: 2286 points
INFO: Calculated initial values for DonchianEnsembleBTC on alchemy-pay: 1785 points
INFO: Calculated initial values for DonchianEnsembleBTC on chex-token: 2001 points
INFO: Calculated initial values for DonchianEnsembleBTC on matic-network: 2286 points
INFO: Calculated initial values for RSI_Bullish_USD on alchemy-pay: 1785 points
INFO: Calculated initial values for RSI_Bullish_USD on chex-token: 2001 points
INFO: Calculated initial values for RSI_Bullish_BTC on alchemy-pay: 1785 points
INFO: Completed signal registration for alchemy-pay in 14.13 seconds
INFO: Calculated initial values for RSI_Bullish_BTC on chex-token: 2001 points

Registering signals group 35/44:  60%|██████    | 3/5 [00:14<00:11,  5.61s/it]

INFO: Completed signal registration for chex-token in 14.45 seconds

Registering signals group 35/44:  80%|████████  | 4/5 [00:14<00:03,  3.51s/it]

INFO: Calculated initial values for RSI_Bullish_USD on matic-network: 2286 points
INFO: Calculated initial values for RSI_Bullish_BTC on matic-network: 2286 points
INFO: Completed signal registration for matic-network in 14.97 seconds

Registering signals group 35/44: 100%|██████████| 5/5 [00:14<00:00,  2.98s/it]

INFO: Registering 4 new signals for popcat
INFO: Registering 4 new signals for shiba-inu
INFO: Registering 4 new signals for internet-computer

Registering signals group 36/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 4 new signals for snek
INFO: Adapted windows for data length 588: [4, 8, 16, 24, 49, 73, 122]
INFO: Registering 4 new signals for mog-coin
INFO: Calculated initial values for DonchianEnsembleUSD on popcat: 588 points
INFO: Calculated initial values for DonchianEnsembleUSD on snek: 799 points
INFO: Calculated initial values for DonchianEnsembleUSD on mog-coin: 739 points
INFO: Calculated initial values for DonchianEnsembleUSD on internet-computer: 1541 points
INFO: Calculated initial values for DonchianEnsembleUSD on shiba-inu: 1809 points
INFO: Calculated initial values for DonchianEnsembleBTC on popcat: 588 points
INFO: Calculated initial values for RSI_Bullish_USD on popcat: 588 points
INFO: Calculated initial values for DonchianEnsembleBTC on mog-coin: 739 points
INFO: Calculated initial values for DonchianEnsembleBTC on snek: 799 points
INFO: Calculated initial values for RSI_Bullish_BTC on popcat: 588 points
INFO: Completed signal registration for popcat in 6.88 seconds

Registering signals group 36/44:  20%|██        | 1/5 [00:07<00:28,  7.05s/it]

INFO: Calculated initial values for RSI_Bullish_USD on mog-coin: 739 points
INFO: Calculated initial values for RSI_Bullish_BTC on mog-coin: 739 points
INFO: Calculated initial values for RSI_Bullish_USD on snek: 799 points
INFO: Completed signal registration for mog-coin in 8.31 seconds

Registering signals group 36/44:  40%|████      | 2/5 [00:08<00:10,  3.62s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on snek: 799 points
INFO: Completed signal registration for snek in 8.80 seconds

Registering signals group 36/44:  60%|██████    | 3/5 [00:08<00:04,  2.16s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on internet-computer: 1541 points
INFO: Calculated initial values for DonchianEnsembleBTC on shiba-inu: 1809 points
INFO: Calculated initial values for RSI_Bullish_USD on internet-computer: 1541 points
INFO: Calculated initial values for RSI_Bullish_BTC on internet-computer: 1541 points
INFO: Completed signal registration for internet-computer in 12.29 seconds

Registering signals group 36/44:  80%|████████  | 4/5 [00:12<00:02,  2.66s/it]

INFO: Calculated initial values for RSI_Bullish_USD on shiba-inu: 1809 points
INFO: Calculated initial values for RSI_Bullish_BTC on shiba-inu: 1809 points
INFO: Completed signal registration for shiba-inu in 12.59 seconds

Registering signals group 36/44: 100%|██████████| 5/5 [00:12<00:00,  2.48s/it]

INFO: Registering 4 new signals for morpho
INFO: Registering 4 new signals for euler
INFO: Registering 4 new signals for litecoin
INFO: Registering 4 new signals for near
INFO: Adapted windows for data length 251: [3, 6, 10, 20, 31, 52]

Registering signals group 37/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 4 new signals for radiant-capital
INFO: Calculated initial values for DonchianEnsembleUSD on morpho: 251 points
INFO: Calculated initial values for DonchianEnsembleBTC on morpho: 251 points
INFO: Calculated initial values for RSI_Bullish_USD on morpho: 251 points
INFO: Calculated initial values for DonchianEnsembleUSD on euler: 1131 points
INFO: Calculated initial values for RSI_Bullish_BTC on morpho: 251 points
INFO: Completed signal registration for morpho in 3.38 seconds

Registering signals group 37/44:  20%|██        | 1/5 [00:03<00:12,  3.11s/it]

INFO: Calculated initial values for DonchianEnsembleUSD on radiant-capital: 1099 points
INFO: Calculated initial values for DonchianEnsembleUSD on near: 1749 points
INFO: Calculated initial values for DonchianEnsembleBTC on euler: 1131 points
INFO: Calculated initial values for DonchianEnsembleBTC on radiant-capital: 1099 points
INFO: Calculated initial values for RSI_Bullish_USD on euler: 1131 points
INFO: Calculated initial values for DonchianEnsembleUSD on litecoin: 4475 points
INFO: Calculated initial values for RSI_Bullish_BTC on euler: 1131 points
INFO: Calculated initial values for RSI_Bullish_USD on radiant-capital: 1099 points
INFO: Completed signal registration for euler in 13.83 seconds

Registering signals group 37/44:  40%|████      | 2/5 [00:13<00:22,  7.45s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on radiant-capital: 1099 points
INFO: Calculated initial values for DonchianEnsembleBTC on near: 1749 points
INFO: Completed signal registration for radiant-capital in 14.39 seconds

Registering signals group 37/44:  60%|██████    | 3/5 [00:14<00:08,  4.23s/it]

INFO: Calculated initial values for RSI_Bullish_USD on near: 1749 points
INFO: Calculated initial values for RSI_Bullish_BTC on near: 1749 points
INFO: Completed signal registration for near in 17.01 seconds

Registering signals group 37/44:  80%|████████  | 4/5 [00:16<00:03,  3.61s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on litecoin: 4475 points
INFO: Calculated initial values for RSI_Bullish_USD on litecoin: 4475 points
INFO: Calculated initial values for RSI_Bullish_BTC on litecoin: 4475 points
INFO: Completed signal registration for litecoin in 23.27 seconds

Registering signals group 37/44: 100%|██████████| 5/5 [00:22<00:00,  4.57s/it]

INFO: Registering 4 new signals for injective-protocol
INFO: Registering 4 new signals for cow-protocol
INFO: Registering 4 new signals for hypercycle

Registering signals group 38/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 4 new signals for floki
INFO: Registering 4 new signals for swarm
INFO: Calculated initial values for DonchianEnsembleUSD on hypercycle: 812 points
INFO: Calculated initial values for DonchianEnsembleUSD on injective-protocol: 1742 points
INFO: Calculated initial values for DonchianEnsembleUSD on floki: 1492 points
INFO: Calculated initial values for DonchianEnsembleBTC on hypercycle: 812 points
INFO: Calculated initial values for RSI_Bullish_USD on hypercycle: 812 points
INFO: Calculated initial values for RSI_Bullish_BTC on hypercycle: 812 points
INFO: Calculated initial values for DonchianEnsembleUSD on swarm: 3407 points
INFO: Completed signal registration for hypercycle in 10.03 seconds

Registering signals group 38/44:  20%|██        | 1/5 [00:10<00:40, 10.16s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on floki: 1492 points
INFO: Completed signal registration for cow-protocol in 12.44 seconds
INFO: Calculated initial values for DonchianEnsembleBTC on injective-protocol: 1742 points

Registering signals group 38/44:  40%|████      | 2/5 [00:12<00:16,  5.48s/it]

INFO: Calculated initial values for RSI_Bullish_USD on floki: 1492 points
INFO: Calculated initial values for RSI_Bullish_BTC on floki: 1492 points
INFO: Completed signal registration for floki in 15.24 seconds

Registering signals group 38/44:  60%|██████    | 3/5 [00:15<00:08,  4.22s/it]

INFO: Calculated initial values for RSI_Bullish_USD on injective-protocol: 1742 points
INFO: Calculated initial values for RSI_Bullish_BTC on injective-protocol: 1742 points
INFO: Completed signal registration for injective-protocol in 15.85 seconds

Registering signals group 38/44:  80%|████████  | 4/5 [00:15<00:02,  2.80s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on swarm: 3407 points
INFO: Calculated initial values for RSI_Bullish_USD on swarm: 3407 points
INFO: Calculated initial values for RSI_Bullish_BTC on swarm: 3407 points
INFO: Completed signal registration for swarm in 20.01 seconds

Registering signals group 38/44: 100%|██████████| 5/5 [00:19<00:00,  3.95s/it]

INFO: Registering 4 new signals for mubarak
INFO: Registering 4 new signals for curve-dao-token
INFO: Adapted windows for data length 135: [3, 5, 11, 16, 28]
INFO: Registering 4 new signals for mintlayer
INFO: Registering 4 new signals for gigachad-2

Registering signals group 39/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 4 new signals for ripple
INFO: Calculated initial values for DonchianEnsembleUSD on mubarak: 135 points
INFO: Calculated initial values for DonchianEnsembleBTC on mubarak: 135 points
INFO: Calculated initial values for DonchianEnsembleUSD on gigachad-2: 554 points
INFO: Calculated initial values for RSI_Bullish_USD on mubarak: 135 points
INFO: Calculated initial values for RSI_Bullish_BTC on mubarak: 135 points
INFO: Calculated initial values for DonchianEnsembleUSD on mintlayer: 857 points
INFO: Completed signal registration for mubarak in 2.03 seconds

Registering signals group 39/44:  20%|██        | 1/5 [00:02<00:08,  2.07s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on gigachad-2: 554 points
INFO: Calculated initial values for DonchianEnsembleUSD on curve-dao-token: 1810 points
INFO: Calculated initial values for RSI_Bullish_USD on gigachad-2: 554 points
INFO: Calculated initial values for RSI_Bullish_BTC on gigachad-2: 554 points
INFO: Completed signal registration for gigachad-2 in 5.26 seconds

Registering signals group 39/44:  40%|████      | 2/5 [00:04<00:07,  2.57s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on mintlayer: 857 points
INFO: Calculated initial values for RSI_Bullish_USD on mintlayer: 857 points
INFO: Calculated initial values for RSI_Bullish_BTC on mintlayer: 857 points
INFO: Completed signal registration for mintlayer in 7.41 seconds

Registering signals group 39/44:  60%|██████    | 3/5 [00:07<00:04,  2.38s/it]

INFO: Calculated initial values for DonchianEnsembleUSD on ripple: 4377 points
INFO: Calculated initial values for DonchianEnsembleBTC on curve-dao-token: 1810 points
INFO: Calculated initial values for RSI_Bullish_USD on curve-dao-token: 1810 points
INFO: Calculated initial values for RSI_Bullish_BTC on curve-dao-token: 1810 points
INFO: Completed signal registration for curve-dao-token in 11.26 seconds

Registering signals group 39/44:  80%|████████  | 4/5 [00:10<00:02,  2.94s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on ripple: 4377 points
INFO: Calculated initial values for RSI_Bullish_USD on ripple: 4377 points
INFO: Calculated initial values for RSI_Bullish_BTC on ripple: 4377 points
INFO: Completed signal registration for ripple in 17.43 seconds

Registering signals group 39/44: 100%|██████████| 5/5 [00:17<00:00,  3.41s/it]

INFO: Registering 4 new signals for ethereum-classic
INFO: Registering 4 new signals for syrup

Registering signals group 40/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 4 new signals for liquity
INFO: Registering 4 new signals for goatseus-maximus
INFO: Registering 4 new signals for slerf
INFO: Adapted windows for data length 258: [3, 7, 10, 21, 32, 53]
INFO: Adapted windows for data length 289: [4, 8, 12, 24, 36, 60]
INFO: Calculated initial values for DonchianEnsembleUSD on syrup: 258 points
INFO: Calculated initial values for DonchianEnsembleUSD on slerf: 498 points
INFO: Calculated initial values for DonchianEnsembleUSD on goatseus-maximus: 289 points
INFO: Calculated initial values for DonchianEnsembleBTC on syrup: 258 points
INFO: Calculated initial values for RSI_Bullish_USD on syrup: 258 points
INFO: Calculated initial values for RSI_Bullish_BTC on syrup: 258 points
INFO: Calculated initial values for DonchianEnsembleBTC on goatseus-maximus: 289 points
INFO: Completed signal registration for syrup in 3.05 seconds

Registering signals group 40/44:  20%|██        | 1/5 [00:03<00:12,  3.22s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on slerf: 498 points
INFO: Calculated initial values for RSI_Bullish_USD on goatseus-maximus: 289 points
INFO: Calculated initial values for DonchianEnsembleUSD on liquity: 1576 points
INFO: Calculated initial values for RSI_Bullish_BTC on goatseus-maximus: 289 points
INFO: Completed signal registration for goatseus-maximus in 4.18 seconds
INFO: Calculated initial values for RSI_Bullish_USD on slerf: 498 points

Registering signals group 40/44:  40%|████      | 2/5 [00:04<00:05,  1.95s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on slerf: 498 points
INFO: Completed signal registration for slerf in 4.71 seconds

Registering signals group 40/44:  60%|██████    | 3/5 [00:04<00:02,  1.25s/it]

INFO: Calculated initial values for DonchianEnsembleUSD on ethereum-classic: 3292 points
INFO: Calculated initial values for DonchianEnsembleBTC on liquity: 1576 points
INFO: Calculated initial values for RSI_Bullish_USD on liquity: 1576 points
INFO: Calculated initial values for RSI_Bullish_BTC on liquity: 1576 points
INFO: Completed signal registration for liquity in 9.78 seconds

Registering signals group 40/44:  80%|████████  | 4/5 [00:09<00:02,  2.75s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on ethereum-classic: 3292 points
INFO: Calculated initial values for RSI_Bullish_USD on ethereum-classic: 3292 points
INFO: Calculated initial values for RSI_Bullish_BTC on ethereum-classic: 3292 points
INFO: Completed signal registration for ethereum-classic in 13.50 seconds

Registering signals group 40/44: 100%|██████████| 5/5 [00:13<00:00,  2.68s/it]

INFO: Registering 4 new signals for true-usd
INFO: Registering 4 new signals for myria
INFO: Registering 4 new signals for avalanche-2
INFO: Registering 4 new signals for pax-gold

Registering signals group 41/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 4 new signals for y
INFO: Adapted windows for data length 484: [3, 6, 13, 20, 40, 60, 100]
INFO: Calculated initial values for DonchianEnsembleUSD on y: 484 points
INFO: Calculated initial values for DonchianEnsembleUSD on myria: 845 points
INFO: Calculated initial values for DonchianEnsembleBTC on y: 484 points
INFO: Calculated initial values for DonchianEnsembleUSD on avalanche-2: 1771 points
INFO: Calculated initial values for RSI_Bullish_USD on y: 484 points
INFO: Calculated initial values for RSI_Bullish_BTC on y: 484 points
INFO: Completed signal registration for y in 6.00 seconds

Registering signals group 41/44:  20%|██        | 1/5 [00:05<00:22,  5.66s/it]

INFO: Calculated initial values for DonchianEnsembleUSD on true-usd: 2686 points
INFO: Calculated initial values for DonchianEnsembleUSD on pax-gold: 2144 points
INFO: Calculated initial values for DonchianEnsembleBTC on myria: 845 points
INFO: Calculated initial values for RSI_Bullish_USD on myria: 845 points
INFO: Calculated initial values for RSI_Bullish_BTC on myria: 845 points
INFO: Completed signal registration for myria in 9.70 seconds

Registering signals group 41/44:  40%|████      | 2/5 [00:09<00:13,  4.57s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on avalanche-2: 1771 points
INFO: Calculated initial values for DonchianEnsembleBTC on pax-gold: 2144 points
INFO: Calculated initial values for RSI_Bullish_USD on avalanche-2: 1771 points
INFO: Calculated initial values for RSI_Bullish_BTC on avalanche-2: 1771 points
INFO: Calculated initial values for DonchianEnsembleBTC on true-usd: 2686 points
INFO: Completed signal registration for avalanche-2 in 15.75 seconds

Registering signals group 41/44:  60%|██████    | 3/5 [00:15<00:10,  5.21s/it]

INFO: Calculated initial values for RSI_Bullish_USD on pax-gold: 2144 points
INFO: Calculated initial values for RSI_Bullish_BTC on pax-gold: 2144 points
INFO: Completed signal registration for pax-gold in 17.57 seconds

Registering signals group 41/44:  80%|████████  | 4/5 [00:17<00:03,  3.85s/it]

INFO: Calculated initial values for RSI_Bullish_USD on true-usd: 2686 points
INFO: Calculated initial values for RSI_Bullish_BTC on true-usd: 2686 points
INFO: Completed signal registration for true-usd in 18.33 seconds

Registering signals group 41/44: 100%|██████████| 5/5 [00:17<00:00,  3.58s/it]

INFO: Registering 4 new signals for monero
INFO: Registering 4 new signals for mantra-dao
INFO: Registering 4 new signals for paal-ai

Registering signals group 42/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 4 new signals for constitutiondao
INFO: Registering 4 new signals for cardano
INFO: Calculated initial values for DonchianEnsembleUSD on paal-ai: 764 points
INFO: Calculated initial values for DonchianEnsembleUSD on constitutiondao: 1348 points
INFO: Calculated initial values for DonchianEnsembleUSD on mantra-dao: 1806 points
INFO: Calculated initial values for DonchianEnsembleBTC on paal-ai: 764 points
INFO: Calculated initial values for DonchianEnsembleUSD on cardano: 2841 points
INFO: Calculated initial values for RSI_Bullish_USD on paal-ai: 764 points
INFO: Calculated initial values for RSI_Bullish_BTC on paal-ai: 764 points
INFO: Completed signal registration for paal-ai in 11.57 seconds

Registering signals group 42/44:  20%|██        | 1/5 [00:11<00:45, 11.33s/it]

INFO: Calculated initial values for DonchianEnsembleUSD on monero: 4087 points
INFO: Calculated initial values for DonchianEnsembleBTC on constitutiondao: 1348 points
INFO: Calculated initial values for DonchianEnsembleBTC on mantra-dao: 1806 points
INFO: Calculated initial values for RSI_Bullish_USD on constitutiondao: 1348 points
INFO: Calculated initial values for RSI_Bullish_BTC on constitutiondao: 1348 points
INFO: Completed signal registration for constitutiondao in 18.44 seconds

Registering signals group 42/44:  40%|████      | 2/5 [00:18<00:25,  8.65s/it]

INFO: Calculated initial values for RSI_Bullish_USD on mantra-dao: 1806 points
INFO: Calculated initial values for RSI_Bullish_BTC on mantra-dao: 1806 points
INFO: Completed signal registration for mantra-dao in 21.75 seconds

Registering signals group 42/44:  60%|██████    | 3/5 [00:21<00:12,  6.25s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on cardano: 2841 points
INFO: Calculated initial values for RSI_Bullish_USD on cardano: 2841 points
INFO: Calculated initial values for DonchianEnsembleBTC on monero: 4087 points
INFO: Calculated initial values for RSI_Bullish_BTC on cardano: 2841 points
INFO: Completed signal registration for cardano in 28.09 seconds

Registering signals group 42/44:  80%|████████  | 4/5 [00:27<00:06,  6.25s/it]

INFO: Calculated initial values for RSI_Bullish_USD on monero: 4087 points
INFO: Calculated initial values for RSI_Bullish_BTC on monero: 4087 points
INFO: Completed signal registration for monero in 31.08 seconds

Registering signals group 42/44: 100%|██████████| 5/5 [00:30<00:00,  6.14s/it]

INFO: Registering 4 new signals for based-brett
INFO: Registering 4 new signals for osaka-protocol
INFO: Registering 4 new signals for genopets

Registering signals group 43/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 4 new signals for solana
INFO: Adapted windows for data length 516: [3, 7, 14, 21, 43, 64, 107]
INFO: Registering 4 new signals for lagrange
INFO: Adapted windows for data length 55: [4, 6, 11]
INFO: Asset lagrange: Using 3 windows with threshold 2
INFO: Calculated initial values for DonchianEnsembleUSD on lagrange: 55 points
INFO: Calculated initial values for DonchianEnsembleBTC on lagrange: 55 points
INFO: Calculated initial values for DonchianEnsembleUSD on based-brett: 516 points
INFO: Calculated initial values for RSI_Bullish_USD on lagrange: 55 points
INFO: Calculated initial values for RSI_Bullish_BTC on lagrange: 55 points
INFO: Completed signal registration for lagrange in 2.38 seconds

Registering signals group 43/44:  20%|██        | 1/5 [00:02<00:10,  2.55s/it]

INFO: Calculated initial values for DonchianEnsembleUSD on genopets: 1349 points
INFO: Calculated initial values for DonchianEnsembleBTC on based-brett: 516 points
INFO: Calculated initial values for DonchianEnsembleUSD on solana: 1936 points
INFO: Calculated initial values for RSI_Bullish_USD on based-brett: 516 points
INFO: Calculated initial values for RSI_Bullish_BTC on based-brett: 516 points
INFO: Completed signal registration for based-brett in 6.72 seconds

Registering signals group 43/44:  40%|████      | 2/5 [00:06<00:10,  3.52s/it]

INFO: Completed signal registration for osaka-protocol in 7.63 seconds

Registering signals group 43/44:  60%|██████    | 3/5 [00:07<00:04,  2.28s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on genopets: 1349 points
INFO: Calculated initial values for RSI_Bullish_USD on genopets: 1349 points
INFO: Calculated initial values for RSI_Bullish_BTC on genopets: 1349 points
INFO: Calculated initial values for DonchianEnsembleBTC on solana: 1936 points
INFO: Completed signal registration for genopets in 11.03 seconds

Registering signals group 43/44:  80%|████████  | 4/5 [00:10<00:02,  2.71s/it]

INFO: Calculated initial values for RSI_Bullish_USD on solana: 1936 points
INFO: Calculated initial values for RSI_Bullish_BTC on solana: 1936 points
INFO: Completed signal registration for solana in 12.30 seconds

Registering signals group 43/44: 100%|██████████| 5/5 [00:12<00:00,  2.43s/it]

INFO: Registering 4 new signals for frax-share
INFO: Registering 4 new signals for kaito

Registering signals group 44/44:   0%|          | 0/3 [00:00<?, ?it/s]

INFO: Registering 4 new signals for neon
INFO: Adapted windows for data length 159: [4, 6, 13, 19, 33]
INFO: Calculated initial values for DonchianEnsembleUSD on kaito: 159 points
INFO: Calculated initial values for DonchianEnsembleBTC on kaito: 159 points
INFO: Calculated initial values for DonchianEnsembleUSD on neon: 742 points
INFO: Calculated initial values for RSI_Bullish_USD on kaito: 159 points
INFO: Calculated initial values for RSI_Bullish_BTC on kaito: 159 points
INFO: Completed signal registration for kaito in 1.50 seconds

Registering signals group 44/44:  33%|███▎      | 1/3 [00:01<00:02,  1.40s/it]

INFO: Calculated initial values for DonchianEnsembleUSD on frax-share: 1681 points
INFO: Calculated initial values for DonchianEnsembleBTC on neon: 742 points
INFO: Calculated initial values for RSI_Bullish_USD on neon: 742 points
INFO: Calculated initial values for RSI_Bullish_BTC on neon: 742 points
INFO: Completed signal registration for neon in 5.25 seconds

Registering signals group 44/44:  67%|██████▋   | 2/3 [00:05<00:02,  2.79s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on frax-share: 1681 points
INFO: Calculated initial values for RSI_Bullish_USD on frax-share: 1681 points
INFO: Calculated initial values for RSI_Bullish_BTC on frax-share: 1681 points
INFO: Completed signal registration for frax-share in 8.34 seconds

Registering signals group 44/44: 100%|██████████| 3/3 [00:08<00:00,  2.73s/it]

INFO: Registered a total of 872 signals across 218 assets

{'heyanon': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x31da1f790>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x31da1cfd0>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x31dc63350>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x30f6cc990>},
 'neiro-3': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x31da1cf10>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x314363510>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x31dc62910>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x31dca6810>},
 'coredaoorg': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x31da1f990>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x313f65cd0>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x31dd07690>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x31dc582d0>},
 'axie-infinity': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x31da1fa90>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x31da1f850>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x31dcf42d0>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x31dc62d50>},
 'tezos': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x31da1d910>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x31dca6210>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x31dc5a590>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x31dca5dd0>},
 'fartcoin': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x31dc62bd0>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x31dca4850>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x31dd07810>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x31dca6c90>},
 'dogwifcoin': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x16a20aad0>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x31dcf7a50>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x31da21250>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x31da14210>},
 'grok-2': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x31dca6190>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x31dd06cd0>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x31dc59a10>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x31dd046d0>},
 'dodo': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x31dca4c10>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x31dc61810>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x31dc5b590>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x31da3e290>},
 'quant-network': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x30f63f090>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x31dcbfe50>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x31da17c10>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x31dcbd1d0>},
 'hyperliquid': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x31dcbc490>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x31dcf5c50>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x31dc5a6d0>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x31d9ba250>},
 'aixbt': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x31dd049d0>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x31dc58690>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x31da23550>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x31dca9310>},
 'moonwell-artemis': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x31dcbd290>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x31dc59610>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x31dd06ed0>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x31da161d0>},
 'optimism': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x31dcbf590>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x16a1a5850>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x31dca4410>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x31d9f3450>},
 'yearn-finance': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x31da1f050>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x31dc5b8d0>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x31e20d3d0>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x31dcbd110>},
 'alchemist-ai': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x31e20cc90>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x31da3e850>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x31da3cfd0>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x31e20cc10>},
 'ondo-finance': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x31d9b8ad0>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x31dc5bed0>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x16a0ae9d0>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x16a11acd0>},
 'illuvium': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x31da15150>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x169fa2c50>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x16f6c6d50>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x31da1fd50>},
 'dusk-network': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x31dc61f50>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x31dcf4290>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x31dca7cd0>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x31dcab190>},
 'havven': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x16a0afb50>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x313fc2b50>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x169ffd350>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x31d9f2210>},
 'ronin': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x31dcaae50>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x30fb72710>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x31dcaaed0>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x31daef050>},
 'acala': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x16a0ae410>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x16f6c6790>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x31daec6d0>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x16a118ed0>},
 'band-protocol': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x31daef350>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x3163a4d90>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x16a0adb10>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x16a11bf10>},
 'fetch-ai': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x31dca4fd0>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x31dcab4d0>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x31da3e610>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x3138d1a50>},
 'omisego': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x31daeda90>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x169fa0c50>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x169f8ed10>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x31dca4cd0>},
 'multibit': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x31da16a50>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x31daede90>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x3138fa310>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x314294e10>},
 'gala': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x16f6c6750>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x30c1d73d0>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x30fafd550>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x3138dba90>},
 'uniswap': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x3138f1150>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x3138dab90>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x30c1d5bd0>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x16a0f5590>},
 'bitcoin': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x31e20f550>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x3138dac10>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x16a0f5450>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x3138eca50>},
 'stellar': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x31daecd10>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x31e20e1d0>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x31dcbeb10>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x16a0ad2d0>},
 'aethir': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x3138db8d0>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x31da15c50>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x3138f0d50>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x169fa2850>},
 'apu-s-club': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x3138eecd0>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x16f6c7e50>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x3167a66d0>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x31dca9b90>},
 'turbo': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x3138f0e90>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x30d50bd50>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x31da21790>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x3138ecb50>},
 'pendle': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x31daee550>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x31d9f3710>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x310169e50>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x169fa2b50>},
 'the-sandbox': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x31daf7a50>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x31d9ba950>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x31dc62290>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x31d9f1a50>},
 'equilibria-finance': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x3138f9d10>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x31e20da10>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x30fafd5d0>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x16fb33e90>},
 'gmx': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x16fb30c10>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x169f121d0>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x30d508650>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x30d049710>},
 'crypto-com-chain': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x3138ec490>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x31e20d950>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x3163ccd10>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x16fcc5650>},
 'polymath': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x16a0acc10>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x16a0f79d0>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x169f13590>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x31dcbd850>},
 'zcash': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x30c1d4e90>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x16a0ac150>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x16a0f4610>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x3138ef710>},
 'axelar': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x169defc50>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x30d048150>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x30d3f6e50>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x31daf6bd0>},
 'aave': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x31e159750>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x169def050>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x31e15b690>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x16a0f4d50>},
 'wrapped-nxm': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x30d508310>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x16a11ab10>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x169f12b10>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x16a01ea10>},
 'rainbow-token-2': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x13ecec810>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x31da1f810>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x16a0f4550>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x16ff3c350>},
 'binancecoin': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x16ff3c810>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x30c1c5ad0>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x31da1ff90>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x30c1c7c50>},
 'ethena': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x30d049790>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x30d50b390>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x31db4e590>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x16a01d250>},
 'prisma-governance-token': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x169d09350>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x3138e3e50>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x31db4dad0>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x30d508810>},
 'beam-2': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x31db4dc10>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x16a01cc50>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x30c52f1d0>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x3138e3410>},
 'harrypotterobamasonic10in': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x30c2bc550>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x30d50ac90>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x314254d50>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x31e158950>},
 'sui': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x169dee350>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x3145fad10>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x169d0b6d0>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x3138d1f50>},
 'kamino': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x169deea90>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x30c52e9d0>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x16a1999d0>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x30d535d50>},
 'zebec-network': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x16fe5b650>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x30c0aa550>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x16ff3c150>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x31dd92010>},
 'cat-in-a-dogs-world': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x31dd90250>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x3145f5d50>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x30c52f0d0>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x30c457c10>},
 'dog-go-to-the-moon-rune': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x31448a390>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x31daf7b10>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x3145f7610>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x30c52d390>},
 'rari-governance-token': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x16fe5bad0>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x30c2be2d0>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x31db4e1d0>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x31dd90cd0>},
 'kekius-maximus': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x31dd91310>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x169f129d0>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x31e05b210>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x31e158dd0>},
 'zeus-network': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x31e059210>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x16a0f74d0>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x16a01c5d0>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x169d086d0>},
 'aurory': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x314488250>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x31e05a4d0>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x30c52e750>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x16a05ea90>},
 'secret': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x31dd91050>,

In [20]:
# Select exactly which signals you want to use
usd_signals = [
   
    #'DonchianEnsembleUSD',
    'RSI_Bullish_USD',
    #'RSI_Ensemble_Signal_USD'
]
 
btc_signals = [
    #'RSI_Oversold_BTC',
    #'RSI_Bullish_BTC'
    #'BullRegimeSignalBTC'
    #'RSI_Ensemble_Signal_BTC'
]



# Run the backtest for all assets at once
results = analyzer.backtest_assets(
    asset_ids=assets,
    start_date="2023-1-1",
    end_date="2025-04-30",
    initial_capital=10000.0,
    btc_cost=0.001,  # Lower cost for Bitcoin
    alt_cost=0.005,  # Higher cost for altcoins
    usd_signals=usd_signals,
    btc_signals=btc_signals,
    use_btc_filter=True,
   # allow_short=True
)

In [ ]:
# Filter for results where strategy outperforms buy & hold, sorted by outperformance
outperformance_df = results['summary'].copy()
outperformance_df['Outperformance'] = outperformance_df['Total Return (%)'] - outperformance_df['Buy & Hold Return (%)']
# Filter for positive outperformance and positive total return
# Also exclude stablecoins like USDT, USDC, TUSD
filtered_df = outperformance_df[
    ((outperformance_df['Outperformance'] > 0) | 
    (outperformance_df['Total Return (%)'] > 0)) &
    (~outperformance_df.index.isin(['USDT', 'USDC', 'TUSD']))
]
filtered_df.sort_values('Outperformance', ascending=False)[:60]

In [21]:
# Filter out assets where buy & hold Sharpe ratio is larger than the strategy's Sharpe ratio
results['asset_results'].get('fartcoin')['trades']

[{'trade_id': 1,
  'asset': 'fartcoin',
  'entry_date': Timestamp('2024-11-18 00:00:00'),
  'exit_date': Timestamp('2025-01-28 00:00:00'),
  'holding_days': 71,
  'entry_price': 0.324341,
  'exit_price': 0.807749,
  'price_return': 1.4904313669872145,
  'entry_value': 9950.0,
  'entry_cost': 50.0,
  'exit_value': 24779.792101522784,
  'exit_cost': 123.89896050761392,
  'trade_return': 1.4779792101522786,
  'is_open': False},
 {'trade_id': 2,
  'asset': 'fartcoin',
  'entry_date': Timestamp('2025-03-24 00:00:00'),
  'exit_date': Timestamp('2025-04-30 00:00:00'),
  'holding_days': 37,
  'entry_price': 0.549486,
  'exit_price': 1.24,
  'price_return': 1.2566544006580695,
  'entry_value': 24532.613675310095,
  'entry_cost': 123.27946570507585,
  'exit_value': 55361.63061003286,
  'exit_cost': 276.8081530501643,
  'trade_return': 1.2453711286547788,
  'is_open': False}]

In [ ]:
# Get the results dataframe for Bitcoin
bitcoin_results = results['asset_results'].get('dogecoin')['results_df']

# Import plotly
import plotly.graph_objects as go

# Create a plotly figure
fig = go.Figure()

# Add traces for portfolio value and buy & hold value
fig.add_trace(
    go.Scatter(
        x=bitcoin_results.index,
        y=bitcoin_results['portfolio_value'],
        mode='lines',
        name='SOROS V1',
        line=dict(width=2, color='blue')
    )
)

fig.add_trace(
    go.Scatter(
        x=bitcoin_results.index,
        y=bitcoin_results['buy_hold_value'],
        mode='lines',
        name='Buy & Hold',
        line=dict(width=2, color='red')
    )
)

# Update layout
fig.update_layout(
    title='SOROS vs. Buy n Hold',
    xaxis_title='',
    yaxis_title='Valor da Carteira (USD)',
    legend=dict(x=0.01, y=0.99),
    hovermode='x unified',
    template='plotly_white'
)

# Show the figure
fig.show()

In [ ]:
results['asset_results'].get('dogecoin')['metrics_comparison']

In [ ]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

# Read the CSV file
etf = pd.read_csv('/Users/valter.rebelo/MissionControl/ETF flows - Sheet1.csv')

# Replace all '-' values with 0
etf = etf.replace('-', 0)

# Convert columns to numeric where possible
for col in etf.columns:
    if col != 'Date':  # Skip the Date column
        etf[col] = pd.to_numeric(etf[col], errors='coerce')

# Convert Date to datetime
etf['Date'] = pd.to_datetime(etf['Date'], format='%d %b %Y')
etf.set_index('Date', inplace=True)

# Get BTC price data
btc_data = analyzer.get_asset_data('bitcoin').price_data
btc_close = btc_data['close'].to_frame('BTC_Price')

# Merge ETF flows with BTC price data
merged_data = etf.join(btc_close, how='left')

# Resample to weekly data
# For ETF flows, sum the daily flows
# For BTC price, take the last price of the week
weekly_etf = etf.resample('W').sum()
weekly_btc = btc_close.resample('W').last()

# Calculate weekly BTC returns
weekly_btc['BTC_Return'] = weekly_btc['BTC_Price'].pct_change() * 100

# Merge weekly ETF flows with weekly BTC returns
weekly_data = weekly_etf.join(weekly_btc, how='left')

# Create a scatter plot with regression line
plt.figure(figsize=(10, 6))

# Get all data points except the two most recent ones
main_data = weekly_data.iloc[:-2]
# Get the most recent data point
most_recent = weekly_data.iloc[-1:]
# Get the second most recent data point
second_most_recent = weekly_data.iloc[-2:-1]

# Plot main data points
sns.regplot(x='Total', y='BTC_Return', data=main_data, 
            scatter_kws={'alpha':0.6, 'color':'blue'}, 
            line_kws={'color':'red'})

# Plot the most recent data point with a different color
plt.scatter(most_recent['Total'], most_recent['BTC_Return'], 
            color='green', s=100, alpha=0.8, label='Dado Mais Recente')

# Plot the second most recent data point with a different color
plt.scatter(second_most_recent['Total'], second_most_recent['BTC_Return'], 
            color='purple', s=100, alpha=0.8, label='Segundo Dado Mais Recente')

plt.title('Retornos do BTC e Fluxos de ETFs Semanais')
plt.xlabel('Fluxos de ETFs (Total)')
plt.ylabel('Retorno do BTC (%)')
plt.grid(True, alpha=0.3)
plt.legend()

# Calculate correlation and regression
correlation = weekly_data['Total'].corr(weekly_data['BTC_Return'])
slope, intercept, r_value, p_value, std_err = stats.linregress(
    weekly_data['Total'].dropna(), 
    weekly_data['BTC_Return'].dropna()
)

# Add correlation and regression stats to the plot
plt.annotate(f'Correlation: {correlation:.3f}\nR-squared: {r_value**2:.3f}\np-value: {p_value:.4f}', 
             xy=(0.05, 0.85), xycoords='axes fraction', 
             bbox=dict(boxstyle="round,pad=0.3", fc="white", ec="gray", alpha=0.8))

plt.tight_layout()
plt.show()

# Display the data
weekly_data

In [ ]:
results['formatted_summary']

In [ ]:
analyzer.get_asset_data('ethereum').get_price_data()

In [ ]:
import pandas as pd
df = pd.DataFrame(results['summary_data'])
df.set_index('asset_id', inplace=True)
df

In [4]:
asset_id = 'bitcoin'

In [22]:
import numpy as np
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots


# Get price data
asset_data = analyzer.get_asset_data(asset_id).price_data
close_prices = asset_data['close']

# Determine if we should show BTC charts based on asset_id
show_btc_charts = asset_id != 'bitcoin'

# Create subplots with appropriate number of rows
if show_btc_charts:
    # Show both USD and BTC charts (4 rows)
    fig = make_subplots(rows=4, cols=1, 
                        subplot_titles=("Donchian Breakout Model BTC", 
                                       "Donchian Breakout Model USD", 
                                       "RSI Bullish BTC",
                                       "RSI Bullish USD"),
                        vertical_spacing=0.1,
                        shared_xaxes=True)
    num_rows = 4
else:
    # Only show USD charts (2 rows)
    fig = make_subplots(rows=2, cols=1, 
                        subplot_titles=("Breakout Model", 
                                        "Momentum Model"),
                        vertical_spacing=0.1,
                        shared_xaxes=True)
    num_rows = 2

# Add background price line with low alpha to all charts
for i in range(1, num_rows + 1):
    fig.add_trace(go.Scatter(
        x=close_prices.index, 
        y=close_prices, 
        mode='lines', 
        name='Price',
        line=dict(color='gray', width=1),
        opacity=0.2,
        showlegend=False if i > 1 else True
    ), row=i, col=1)

# Current row tracker for USD-only mode
current_row = 1

# 1. Donchian Ensemble BTC (only if not bitcoin)
if show_btc_charts:
    values_btc = analyzer.get_asset_data(asset_id).get_signal('DonchianEnsembleBTC').values
    bull_btc = values_btc == 1
    bear_btc = values_btc == 0

    green_column_btc = pd.Series(np.nan, index=close_prices.index)
    red_column_btc = pd.Series(np.nan, index=close_prices.index)

    green_column_btc[bull_btc] = close_prices[bull_btc]
    red_column_btc[bear_btc] = close_prices[bear_btc]

    fig.add_trace(go.Scatter(
        x=green_column_btc.index, 
        y=green_column_btc, 
        mode='lines', 
        name='Bullish BTC (1)',
        line=dict(color='green')
    ), row=1, col=1)

    fig.add_trace(go.Scatter(
        x=red_column_btc.index, 
        y=red_column_btc, 
        mode='lines', 
        name='Bearish/Neutral BTC (0)',
        line=dict(color='red')
    ), row=1, col=1)
    
    current_row += 1

# 2. Donchian Ensemble USD
values_usd = analyzer.get_asset_data(asset_id).get_signal('DonchianEnsembleUSD').values
bull_usd = values_usd == 1
bear_usd = values_usd == 0

green_column_usd = pd.Series(np.nan, index=close_prices.index)
red_column_usd = pd.Series(np.nan, index=close_prices.index)

green_column_usd[bull_usd] = close_prices[bull_usd]
red_column_usd[bear_usd] = close_prices[bear_usd]

fig.add_trace(go.Scatter(
    x=green_column_usd.index, 
    y=green_column_usd, 
    mode='lines', 
    name='Apetite por Risco',
    line=dict(color='green'),
    showlegend=current_row == 1  # Only show in legend if it's the first row
), row=current_row, col=1)

fig.add_trace(go.Scatter(
    x=red_column_usd.index, 
    y=red_column_usd, 
    mode='lines', 
    name='Aversão por Risco',
    line=dict(color='red'),
    showlegend=current_row == 1  # Only show in legend if it's the first row
), row=current_row, col=1)

current_row += 1

# 3. RSI Bullish BTC (only if not bitcoin)
if show_btc_charts:
    rsi_bullish_btc = analyzer.get_asset_data(asset_id).get_signal('RSI_Bullish_BTC').values
    
    bull_rsi_btc = rsi_bullish_btc == 1
    not_bull_rsi_btc = ~bull_rsi_btc

    green_column_rsi_btc = pd.Series(np.nan, index=close_prices.index)
    red_column_rsi_btc = pd.Series(np.nan, index=close_prices.index)

    green_column_rsi_btc[bull_rsi_btc] = close_prices[bull_rsi_btc]
    red_column_rsi_btc[not_bull_rsi_btc] = close_prices[not_bull_rsi_btc]

    fig.add_trace(go.Scatter(
        x=green_column_rsi_btc.index, 
        y=green_column_rsi_btc, 
        mode='lines', 
        name='RSI Bullish BTC (1)',
        line=dict(color='green'),
        showlegend=True
    ), row=current_row, col=1)

    fig.add_trace(go.Scatter(
        x=red_column_rsi_btc.index, 
        y=red_column_rsi_btc, 
        mode='lines', 
        name='Not RSI Bullish BTC (0)',
        line=dict(color='red'),
        showlegend=True
    ), row=current_row, col=1)
    
    current_row += 1

# 4. RSI Bullish USD
rsi_bullish_usd = analyzer.get_asset_data(asset_id).get_signal('RSI_Bullish_USD').values

bull_rsi_usd = rsi_bullish_usd == 1
not_bull_rsi_usd = ~bull_rsi_usd

green_column_rsi_usd = pd.Series(np.nan, index=close_prices.index)
red_column_rsi_usd = pd.Series(np.nan, index=close_prices.index)

green_column_rsi_usd[bull_rsi_usd] = close_prices[bull_rsi_usd]
red_column_rsi_usd[not_bull_rsi_usd] = close_prices[not_bull_rsi_usd]

fig.add_trace(go.Scatter(
    x=green_column_rsi_usd.index, 
    y=green_column_rsi_usd, 
    mode='lines', 
    name='RSI Bullish USD (1)',
    line=dict(color='green'),
    showlegend=current_row == 3  # Only show in legend if it's the first row in USD-only mode
), row=current_row, col=1)

fig.add_trace(go.Scatter(
    x=red_column_rsi_usd.index, 
    y=red_column_rsi_usd, 
    mode='lines', 
    name='Not RSI Bullish USD (0)',
    line=dict(color='red'),
    showlegend=current_row == 3  # Only show in legend if it's the first row in USD-only mode
), row=current_row, col=1)

# Update layout
fig.update_layout(
    title=f'SOROS - {asset_id.capitalize()}',
    xaxis_title='',
    legend_title='Diagnóstico',
    height=800 if asset_id == 'bitcoin' else 1600,  # Adjust height based on number of charts
    width=1000,
    template='plotly_white'
)

# Update y-axis titles for all rows
for i in range(1, num_rows + 1):
    fig.update_yaxes(title_text="Preço (USD)", row=i, col=1)

# Show the plot
fig.show()

In [23]:
analyzer.get_asset_data('dogecoin')

AssetData(asset_id='dogecoin', price_data_length=4244, signals=[DonchianEnsembleUSD, DonchianEnsembleBTC, RSI_Bullish_USD, RSI_Bullish_BTC], backtests=[asset_id, results_df, trades, metrics_comparison, strategy_metrics, buy_hold_metrics, parameters])

In [24]:
results['asset_results'].get(asset_id)['metrics_comparison']

                       Strategy  Buy & Hold
Total Return           2.312530    4.671411
Max Drawdown          -0.344138   -0.281149
Sharpe Ratio           1.749578    2.260663
Sortino Ratio          2.335508    3.636959
Calmar Ratio           1.954119    3.937052
Win Rate               0.538462    0.000000
Annualized Volatility  0.384371    0.489635
Annualized Return      0.672487    1.106900
Accuracy               0.680000    0.498824
Precision              0.501859    0.505576
Recall                 0.985401    0.629630
F1 Score               0.665025    0.560825

In [26]:

import pandas as pd
def display_all_assets_signals_for_date(analyzer, date_str):
    """
    Display Donchian Ensemble, RSI, and Variance signals for all assets on a specific date
    
    Args:
        analyzer: PortfolioAnalyzer instance
        date_str: Date string in 'YYYY-MM-DD' format
    
    Returns:
        DataFrame with signal values for all assets on the specified date
    """
    # Convert date string to datetime
    date = pd.to_datetime(date_str)
    
    # List of signals to check
    signals_to_check = [
        #'DonchianEnsembleBTC',
        #'DonchianEnsembleUSD',
        'RSI_Bullish_BTC',
        'RSI_Bullish_USD',
        #'BullHighVarianceSignalBTC',
        #'BullHighVarianceSignalUSD',
        #'BullLowVarianceSignalBTC',
       # 'BullLowVarianceSignalUSD'
    ]
    
    # Get all asset IDs
    asset_ids = sorted(list(analyzer.assets.keys()))
    
    # Create empty DataFrame with assets as rows and signals as columns
    result_df = pd.DataFrame(index=asset_ids, columns=signals_to_check)
    
    # Fill the DataFrame with signal values
    for asset_id in asset_ids:
        asset_data = analyzer.get_asset_data(asset_id)
        if asset_data is None:
            continue
            
        for signal_name in signals_to_check:
            try:
                signal_data = asset_data.get_signal(signal_name)
                if signal_data is not None:
                    # Access the signal values directly
                    # SignalData objects typically have a 'values' attribute that is a pandas Series
                    if hasattr(signal_data, 'values') and isinstance(signal_data.values, pd.Series):
                        signal_series = signal_data.values
                        if date in signal_series.index:
                            result_df.loc[asset_id, signal_name] = signal_series.loc[date]
                        else:
                            result_df.loc[asset_id, signal_name] = None
                    else:
                        result_df.loc[asset_id, signal_name] = None
                else:
                    result_df.loc[asset_id, signal_name] = None
            except Exception as e:
                print(f"Error getting {signal_name} for {asset_id} on {date_str}: {e}")
                result_df.loc[asset_id, signal_name] = None
    
    # Replace NaN with None for cleaner display
    result_df = result_df.fillna("N/A")
    
    # Add a sum column that counts the number of active signals (value of 1)
    result_df['Signal_Sum'] = result_df.apply(
        lambda row: sum(1 for val in row if val == 1), 
        axis=1
    )

    result_df = result_df.sort_index()
    
    return result_df

# Example usage - replace with your desired date
date_to_check = "2025-5-11"   # Change to your desired date

signals_df = display_all_assets_signals_for_date(analyzer, date_to_check)
print(f"Signals for all assets on {date_to_check}:")
display(signals_df.tail(60))

Signals for all assets on 2025-5-11:

                        RSI_Bullish_BTC RSI_Bullish_USD  Signal_Sum
prisma-governance-token               0               1           1
prometeus                             0               0           0
pudgy-penguins                        1               1           2
quant-network                         1               1           2
radiant-capital                       1               1           2
rainbow-token-2                       0               0           0
rari-governance-token                 0               0           0
raydium                               1               1           2
render-token                          1               1           2
ripple                                0               1           1
ronin                                 0               1           1
secret                                1               1           2
sei-network                           1               1           2
serum                                 0               0           0
shiba-inu                             1               1           2
siren-2                               1               1           2
slerf                                 1               1           2
smartcash                             0               0           0
snek                                  1               1           2
solana                                1               1           2
solayer                               0               0           0
sonic-3                               0               1           1
spell-token                           0               1           1
spx6900                               1               1           2
star-atlas-dao                        1               1           2
stellar                               0               1           1
story-2                               0               1           1
sturdy                                1               1           2
sui                                   1               1           2
sushi                                 1               1           2
swarm                                 0               0           0
syrup                                 1               1           2
terra-luna-2                          1               1           2
tether                                0               1           1
tezos                                 0               1           1
the-open-network                      0               1           1
the-sandbox                           1               1           2
thorchain                             1               1           2
tokenbot-2                            0               0           0
tribe-2                               0               1           1
tron                                  0               1           1
true-usd                              0               1           1
turbo                                 1               1           2
uniswap                               1               1           2
usd-coin                              0               1           1
useless-3                             0               0           0
vela-token                            0               0           0
venice-token                          1               1           2
verasity                              1               1           2
virtual-protocol                      1               1           2
wibx                                  0               0           0
worldcoin-wld                         1               1           2
wrapped-nxm                           1               1           2
y                                     1               1           2
yearn-finance                         1               1           2
yield-guild-games                     1               1           2
yne                                   0               0           0
zcash                                 1               1           2
zebec-network                         1               1           2
zeus-network                          0               0           0

In [27]:
def plot_signal_sums_through_time(analyzer, start_date=None, end_date=None, min_market_cap=1000000000, max_market_cap=None):
    """
    Create an interactive plotly lollipop chart showing signal sums for all assets through time.
    Assets are on the Y-axis and dates on the X-axis.
    
    Args:
        analyzer: The PortfolioAnalyzer instance
        start_date: Optional start date string in format 'YYYY-MM-DD'. If None, uses earliest available date.
        end_date: Optional end date string in format 'YYYY-MM-DD'. If None, uses latest available date.
        min_market_cap: Minimum market capitalization in USD to include an asset
        max_market_cap: Maximum market capitalization in USD to include an asset
    
    Returns:
        DataFrame with signal sums over time
    """
    import plotly.graph_objects as go
    import pandas as pd
    from soros_system.data.data_loader import DataLoader
    
    # Get all asset IDs
    asset_ids = list(analyzer.assets.keys())
    
    # Exclude stablecoins
    excluded_assets = ['tether', 'usd-coin']
    asset_ids = [asset_id for asset_id in asset_ids if asset_id not in excluded_assets]
    
    # Create a data loader to get tickers
    data_loader = DataLoader(
        data_path=analyzer.data_path,
        btc_data_path=analyzer.btc_data_path,
        ssr_data_path=analyzer.ssr_data_path,
        market_data_path=analyzer.market_data_path,
        asset_ids=analyzer.asset_ids
    )
    
    # Create a mapping from asset_id to ticker
    ticker_mapping = {}
    for asset_id in asset_ids:
        ticker = data_loader.get_ticker_from_id(asset_id)
        ticker_mapping[asset_id] = ticker.upper() if ticker else asset_id.upper()
    
    # Create a dictionary to store market caps
    market_caps = {}
    
    # Filter assets by market cap if specified
    if min_market_cap > 0 or max_market_cap is not None:
        filtered_asset_ids = []
        for asset_id in asset_ids:
            asset_data = analyzer.get_asset_data(asset_id)
            if asset_data is not None:
                # Try different ways to access market cap
                market_cap = None
                
                # Try to get from metadata if available
                if hasattr(asset_data, 'metadata') and asset_data.metadata:
                    market_cap = asset_data.metadata.get('market_cap')
                
                # Try to get from asset_data directly
                if market_cap is None and hasattr(asset_data, 'market_cap'):
                    market_cap = asset_data.market_cap
                
                # Try to get from price_data if available
                if market_cap is None and hasattr(asset_data, 'price_data'):
                    if 'market_cap' in asset_data.price_data.columns:
                        # Use the most recent market cap value
                        market_cap = asset_data.price_data['market_cap'].iloc[-1]
                
                # Store market cap for later sorting
                market_caps[asset_id] = market_cap if market_cap is not None else 0
                
                # Debug print to see what we're working with
                ticker = ticker_mapping.get(asset_id, asset_id)
                print(f"Asset: {ticker}, Market Cap: {market_cap}")
                
                # Check if market cap meets criteria
                meets_min_criteria = market_cap is None or market_cap >= min_market_cap
                meets_max_criteria = max_market_cap is None or (market_cap is not None and market_cap <= max_market_cap)
                
                # Include asset if market cap meets criteria
                if meets_min_criteria and meets_max_criteria:
                    filtered_asset_ids.append(asset_id)
                    if market_cap is None:
                        print(f"Warning: No market cap data for {ticker}, including it anyway")
        
        asset_ids = filtered_asset_ids
        
        if not asset_ids:
            market_cap_msg = f"with market cap >= {min_market_cap}"
            if max_market_cap is not None:
                market_cap_msg += f" and <= {max_market_cap}"
            print(f"No assets found {market_cap_msg}")
            return pd.DataFrame()
    else:
        # If no market cap filtering, still collect market caps for sorting
        for asset_id in asset_ids:
            asset_data = analyzer.get_asset_data(asset_id)
            if asset_data is not None:
                market_cap = None
                
                if hasattr(asset_data, 'metadata') and asset_data.metadata:
                    market_cap = asset_data.metadata.get('market_cap')
                
                if market_cap is None and hasattr(asset_data, 'market_cap'):
                    market_cap = asset_data.market_cap
                
                if market_cap is None and hasattr(asset_data, 'price_data'):
                    if 'market_cap' in asset_data.price_data.columns:
                        market_cap = asset_data.price_data['market_cap'].iloc[-1]
                
                market_caps[asset_id] = market_cap if market_cap is not None else 0
    
    # Determine date range
    if start_date is None or end_date is None:
        # Find the common date range across assets
        min_dates = []
        max_dates = []
        for asset_id in asset_ids:
            asset_data = analyzer.get_asset_data(asset_id)
            if asset_data is not None and hasattr(asset_data, 'price_data') and len(asset_data.price_data) > 0:
                min_dates.append(asset_data.price_data.index[0])
                max_dates.append(asset_data.price_data.index[-1])
        
        if not min_dates or not max_dates:
            print("No data available for any assets")
            return
        
        if start_date is None:
            start_date = max(min_dates).strftime('%Y-%m-%d')
        if end_date is None:
            end_date = min(max_dates).strftime('%Y-%m-%d')
    
    # Convert to datetime objects
    start_dt = pd.to_datetime(start_date)
    end_dt = pd.to_datetime(end_date)
    
    # Generate a list of dates - daily intervals as requested
    date_range = pd.date_range(start=start_dt, end=end_dt, freq='D')
    date_strings = [date.strftime('%Y-%m-%d') for date in date_range]
    
    # Create a DataFrame to store signal sums for each asset and date
    signal_sums_over_time = pd.DataFrame(index=asset_ids)
    
    # Calculate signal sums for each date
    for date_str in date_strings:
        signals_df = display_all_assets_signals_for_date(analyzer, date_str)
        signal_sums_over_time[date_str] = signals_df['Signal_Sum']
    
    # Add market cap column for sorting
    signal_sums_over_time['market_cap'] = signal_sums_over_time.index.map(lambda x: market_caps.get(x, 0))
    
    # Sort by market cap in descending order
    signal_sums_over_time = signal_sums_over_time.sort_values(by='market_cap', ascending=True)
    
    # Calculate total signal sum (but don't include market_cap column)
    signal_sums_over_time['total_sum'] = signal_sums_over_time.drop(columns=['market_cap']).sum(axis=1)
    
    # Remove the sorting columns after sorting
    signal_sums_over_time = signal_sums_over_time.drop(columns=['market_cap', 'total_sum'])
    
    # Create a new DataFrame with tickers as index
    ticker_signal_sums = pd.DataFrame(index=[ticker_mapping[asset_id] for asset_id in signal_sums_over_time.index])
    for col in signal_sums_over_time.columns:
        ticker_signal_sums[col] = signal_sums_over_time[col].values
    
    # Create color mapping function based on signal sum (scaled from 0 to 2)
    def get_color(signal_sum):
        if signal_sum == 0:
            return 'rgb(180, 50, 50)'  # darker red
        elif signal_sum == 1:
            return 'rgb(220, 180, 50)'  # darker yellow
        else:  # 2 signals
            return 'rgb(50, 150, 50)'  # darker green
    
    # Create the figure
    fig = go.Figure()
    
    # Get all dates for x-axis
    all_dates = pd.to_datetime(ticker_signal_sums.columns)
    
    # Plot all points including zero values
    for ticker in ticker_signal_sums.index:
        ticker_data = ticker_signal_sums.loc[ticker]
        
        # Create lists to store data for this ticker
        x_dates = []
        y_tickers = []
        sizes = []
        colors = []
        hover_texts = []
        
        # Process each date point
        for date, sum_val in zip(all_dates, ticker_data):
            x_dates.append(date)
            y_tickers.append(ticker)
            sizes.append(10 + sum_val * 5)  # Size based on signal sum
            colors.append(get_color(sum_val))
            hover_texts.append(f"Date: {date.strftime('%Y-%m-%d')}<br>Ticker: {ticker}<br>Signal Sum: {sum_val}")
        
        # Add scatter plot (dots)
        fig.add_trace(go.Scatter(
            x=x_dates,
            y=y_tickers,
            mode='markers',
            marker=dict(
                size=sizes,
                color=colors,
                line=dict(width=1, color='rgba(0,0,0,0.5)')
            ),
            name=ticker,
            showlegend=False,
            hoverinfo='text',
            hovertext=hover_texts
        ))
    
    # Add a color legend
    for i, (sum_val, color_desc) in enumerate([
        (0, "0 signals (red)"),
        (1, "1 signal (yellow)"),
        (2, "2 signals (green)")
    ]):
        fig.add_trace(go.Scatter(
            x=[None],
            y=[None],
            mode='markers',
            marker=dict(size=10 + sum_val * 5, color=get_color(sum_val)),
            name=color_desc,
            showlegend=True
        ))
    
    # Update layout
    title_text = "Signal Sums for Assets Through Time (Ordered by Market Cap)"
    if min_market_cap > 0 or max_market_cap is not None:
        title_text += f" (Market Cap"
        if min_market_cap > 0:
            title_text += f" >= {min_market_cap:,} USD"
        if max_market_cap is not None:
            if min_market_cap > 0:
                title_text += " and"
            title_text += f" <= {max_market_cap:,} USD"
        title_text += ")"
        
    fig.update_layout(
        title=title_text,
        xaxis_title="Date",
        yaxis_title="Tickers",
        height=max(800, len(ticker_signal_sums) * 20),  # Dynamic height based on number of assets
        width=1200,  # Fixed width for better display
        yaxis=dict(
            categoryorder='array',
            categoryarray=ticker_signal_sums.index,  # Order by market cap (already sorted)
        ),
        xaxis=dict(
            type='date',
            tickformat='%Y-%m-%d',
            tickangle=45,
        ),
        legend_title="Signal Sum Legend",
        hovermode="closest",
        showlegend=True,
        margin=dict(l=150, r=50, t=50, b=100)  # Add margin for ticker names
    )
    
    fig.show()
    
    return ticker_signal_sums

# Example usage
signal_data_over_time = plot_signal_sums_through_time(
    analyzer, 
    start_date="2025-07-01",  # Change to your desired start date
    end_date="2025-07-28",    # Change to your desired end date
    min_market_cap = 500000000,
    max_market_cap = None

)

Asset: NEIRO, Market Cap: 181532662.20010304
Asset: WIF, Market Cap: 1026005745.8815233
Asset: XTZ, Market Cap: 903856631.5056698
Asset: QNT, Market Cap: 1769689177.115519
Asset: AXS, Market Cap: 407600466.9060052
Asset: FARTCOIN, Market Cap: 1151029971.4320624
Asset: WELL, Market Cap: 120279478.15100554
Asset: DODO, Market Cap: 44988918.22510788
Asset: ANON, Market Cap: 40598273.0988443
Asset: GROK, Market Cap: 14080333.175391454
Asset: HYPE, Market Cap: 14536642218.350927
Asset: CORE, Market Cap: 543158641.8724375
Asset: OP, Market Cap: 1320892357.492769
Asset: YFI, Market Cap: 184507729.3539382
Asset: AIXBT, Market Cap: 131991916.1672198
Asset: ILV, Market Cap: 139305235.9853321
Asset: ALCH, Market Cap: 114535023.71847089
Asset: ONDO, Market Cap: 3123185720.879831
Asset: SNX, Market Cap: 217041350.8612878
Asset: FET, Market Cap: 1863083657.432404
Asset: RON, Market Cap: 383219758.9293337
Asset: DUSK, Market Cap: 34590663.40495519
Asset: OMG, Market Cap: 26372662.87694254
Asset: ACA, Market Cap: 34123743.22744544
Asset: BAND, Market Cap: 118168159.51833794
Asset: GALA, Market Cap: 767202953.6250819
Asset: BTC, Market Cap: 2349472897426.4688
Asset: MUBI, Market Cap: 3873364.357761374
Asset: XLM, Market Cap: 13005989926.101576
Asset: UNI, Market Cap: 6254998536.511019
Asset: APU, Market Cap: 95958307.9380308
Asset: SAND, Market Cap: 726362800.0725337
Asset: ATH, Market Cap: 365949829.659769
Asset: TURBO, Market Cap: 336413043.0476581
Asset: PENDLE, Market Cap: 747399173.4155641
Asset: EQB, Market Cap: 17093436.196441583
Asset: POLY, Market Cap: 6961727.073686232
Asset: CRO, Market Cap: 4450256532.199344
Asset: GMX, Market Cap: 134685809.5417022
Asset: ZEC, Market Cap: 656860055.2206612
Asset: RBW, Market Cap: 335257.10322268395
Asset: AAVE, Market Cap: 4378512216.945635
Asset: WNXM, Market Cap: 52958465.22980387
Asset: AXL, Market Cap: 382689679.0410833
Asset: BNB, Market Cap: 114557221095.585
Asset: BITCOIN, Market Cap: 114202876.6544472
Asset: ENA, Market Cap: 4046578827.0501776
Asset: SUI, Market Cap: 13497413838.842676
Asset: PRISMA, Market Cap: 4410458.431682946
Asset: BEAM, Market Cap: 404678666.9020882
Asset: RGT, Market Cap: 1066826.540503244
Asset: KMNO, Market Cap: 137161932.51883712
Asset: DOG, Market Cap: 335710763.7003488
Asset: ZBCN, Market Cap: 384734835.02692217
Asset: MEW, Market Cap: 301620733.9049343
Asset: AURY, Market Cap: 8161912.572985003
Asset: DOGE, Market Cap: 33929150743.176254
Asset: KEKIUS, Market Cap: 24261685.74982183
Asset: SCRT, Market Cap: 58887310.85814223
Asset: ZEUS, Market Cap: 58545983.533077
Asset: JASMY, Market Cap: 791451991.3258688
Asset: KNC, Market Cap: 88143957.70915978
Asset: FTM, Market Cap: 0.0
Asset: HNT, Market Cap: 645031938.6980482
Asset: DASH, Market Cap: 268473705.11407936
Asset: ETHFI, Market Cap: 486171389.05447865
Asset: ALICE, Market Cap: 37338499.20778825
Asset: CAKE, Market Cap: 1011253622.8300486
Asset: ALPHA, Market Cap: 13333459.930432228
Asset: BMT, Market Cap: 21220609.2419864
Asset: FLOW, Market Cap: 628728854.0163182
Asset: BOME, Market Cap: 137667022.21761274
Asset: BAL, Market Cap: 86832969.32911296
Asset: PENGU, Market Cap: 2527069444.5635304
Asset: RENDER, Market Cap: 2100458792.8984768
Asset: ATOM, Market Cap: 2134458515.4865515
Asset: VELA, Market Cap: 26838.699872400608
Asset: MANA, Market Cap: 580254760.5307184
Asset: ETHDYDX, Market Cap: 25093747.07685508
Asset: AVA, Market Cap: 31066595.57737821
Asset: YGG, Market Cap: 90417722.84357458
Asset: ANZ, Market Cap: 982942.8313780472
Asset: LUNA, Market Cap: 113479626.75672588
Asset: CHILLGUY, Market Cap: 64413592.73040805
Asset: GRASS, Market Cap: 252081266.93175104
Asset: TRX, Market Cap: 30499796765.035946
Asset: BERT, Market Cap: 37806019.90794653
Asset: WLD, Market Cap: 2015894044.4312625
Asset: BCH, Market Cap: 11358267430.606838
Asset: DOT, Market Cap: 6012043908.88992
Asset: LSK, Market Cap: 89922635.01695704
Asset: AIOZ, Market Cap: 464481416.6679517
Asset: SRM, Market Cap: 5328914.147509225
Asset: SPX, Market Cap: 1991022751.0635695
Asset: LINK, Market Cap: 12250380481.805609
Asset: LOFI, Market Cap: 39280396.06653606
Asset: AR, Market Cap: 480847010.72266126
Asset: MAMO, Market Cap: 40147679.62847671
Asset: NTX, Market Cap: 11093343.064200245
Asset: TAO, Market Cap: 3832409867.40214
Asset: LDO, Market Cap: 960491481.8343718
Asset: COOKIE, Market Cap: 97356564.04432924
Asset: SHDW, Market Cap: 17454753.39126665
Asset: BABYDOGE, Market Cap: 240091099.32692188
Asset: BADGER, Market Cap: 21490629.262871936
Asset: SIREN, Market Cap: 41830781.649644166
Asset: EIGEN, Market Cap: 409873052.8655203
Asset: SEILOR, Market Cap: 333972.56057584507
Asset: PEPE, Market Cap: 4993819509.989407
Asset: CNC, Market Cap: 25736.638863323147
Asset: RUNE, Market Cap: 494521727.9754019
Asset: RAY, Market Cap: 831514162.2437254
Asset: COMP, Market Cap: 454019849.32453334
Asset: TON, Market Cap: 7900379163.536152
Asset: IMX, Market Cap: 1052405356.0905476
Asset: CPOOL, Market Cap: 115999775.25663944
Asset: WBX, Market Cap: 0.0
Asset: SEI, Market Cap: 1851034115.726559
Asset: MCADE, Market Cap: 35122105.80179593
Asset: PROM, Market Cap: 163623574.5685258
Asset: GOG, Market Cap: 9866206.066711836
Asset: STRDY, Market Cap: 3528383.6959547997
Asset: PRIME, Market Cap: 110337619.05177908
Asset: TIA, Market Cap: 1370772434.0573974
Asset: ARPA, Market Cap: 22779010.17041481
Asset: AI16Z, Market Cap: 157989886.45743182
Asset: POWR, Market Cap: 94544848.12453952
Asset: DEEP, Market Cap: 433960368.8258773
Asset: ARB, Market Cap: 2230147810.0302753
Asset: TRIBE, Market Cap: 238775203.85354668
Asset: VIRTUAL, Market Cap: 945528691.927735
Asset: SMART, Market Cap: 84364.55314467642
Asset: CLANKER, Market Cap: 45498072.53077051
Asset: VISTA, Market Cap: 6621576.234889238
Asset: GRIFT, Market Cap: 3374545.095552925
Asset: KUJI, Market Cap: 30629900.3171988
Asset: GRIFFAIN, Market Cap: 41656830.9307077
Asset: ETH, Market Cap: 457680388920.6686
Asset: KAS, Market Cap: 2560745173.119202
Asset: GORK, Market Cap: 9108270.8630277
Asset: AUDIO, Market Cap: 87216839.78085692
Asset: ARKM, Market Cap: 245479205.65034056
Asset: STX, Market Cap: 1253964351.995986
Asset: USELESS, Market Cap: 341870952.6020431
Asset: YNE, Market Cap: 4649782.48718024
Asset: EVAN, Market Cap: 806863.1193997391
Asset: BOTTO, Market Cap: 15104885.133073874
Asset: MKR, Market Cap: 0.0
Asset: SPELL, Market Cap: 83259270.87620701
Asset: VVV, Market Cap: 99094151.56520666
Asset: FLUID, Market Cap: 227376290.43995297
Asset: SUSHI, Market Cap: 164833711.71125242
Asset: AKT, Market Cap: 361803016.3758798
Asset: EOS, Market Cap: 364873580.1262315
Asset: IP, Market Cap: 1641893987.8430266
Asset: VRA, Market Cap: 131390528.95674872
Asset: AIDOGE, Market Cap: 19939067.77066502
Asset: GNS, Market Cap: 50763441.811415866
Asset: BONK, Market Cap: 2486217220.829813
Asset: NMR, Market Cap: 71547670.31345229
Asset: S, Market Cap: 1015878978.5178318
Asset: PLUME, Market Cap: 273763315.9892709
Asset: JUP, Market Cap: 1634244822.5973177
Asset: POLIS, Market Cap: 27891411.57365603
Asset: HBAR, Market Cap: 11506055262.570663
Asset: LAYER, Market Cap: 140375248.58665723
Asset: AERO, Market Cap: 735230609.4578794
Asset: FWOG, Market Cap: 41851525.5401519
Asset: PERP, Market Cap: 20627331.6057137
Asset: CHEX, Market Cap: 100205987.63842112
Asset: MATIC, Market Cap: 326523660.03033525
Asset: ACH, Market Cap: 110408891.66973609
Asset: TRUMP, Market Cap: 1939622820.7807877
Asset: POPCAT, Market Cap: 335812375.28984344
Asset: SHIB, Market Cap: 7845184231.694691
Asset: ICP, Market Cap: 2964498957.296376
Asset: MOG, Market Cap: 575078719.0874482
Asset: SNEK, Market Cap: 261586431.15766287
Asset: MORPHO, Market Cap: 563219087.9305423
Asset: EUL, Market Cap: 253117212.93705553
Asset: NEAR, Market Cap: 3396453263.7344065
Asset: LTC, Market Cap: 8267536475.978513
Asset: INJ, Market Cap: 1418540331.2865558
Asset: RDNT, Market Cap: 29505443.958891906
Asset: COW, Market Cap: 194019303.5296271
Asset: HYPC, Market Cap: 0.0
Asset: MUBARAK, Market Cap: 43022946.68102909
Asset: FLOKI, Market Cap: 1152202037.6168787
Asset: SWM, Market Cap: 341368.8180346269
Asset: CRV, Market Cap: 1396053189.0952234
Asset: GIGA, Market Cap: 183536834.4505576
Asset: ML, Market Cap: 6445943.825124099
Asset: XRP, Market Cap: 184768043390.20883
Asset: SYRUP, Market Cap: 593214606.1185858
Asset: LQTY, Market Cap: 104757732.25954132
Asset: ETC, Market Cap: 3343565233.388214
Asset: GOAT, Market Cap: 108954610.24536288
Asset: SLERF, Market Cap: 39215816.25528851
Asset: TUSD, Market Cap: 493451994.79049027
Asset: AVAX, Market Cap: 10604901553.70519
Asset: MYRIA, Market Cap: 29189317.491883267
Asset: YAI, Market Cap: 972689.7992982438
Asset: PAXG, Market Cap: 937143077.6281786
Asset: OM, Market Cap: 266742585.24516353
Asset: XMR, Market Cap: 5814996974.483188
Asset: PAAL, Market Cap: 101746769.62809844
Asset: PEOPLE, Market Cap: 103752469.13260208
Asset: ADA, Market Cap: 28621028508.355045
Asset: OSAK, Market Cap: 134617805.00715294
Asset: LA, Market Cap: 65167889.44165096
Asset: BRETT, Market Cap: 540466474.8105447
Asset: GENE, Market Cap: 3640418.14385017
Asset: SOL, Market Cap: 98532622033.55844
Asset: NEON, Market Cap: 24088955.57350441
Asset: KAITO, Market Cap: 308652830.370904
Asset: FRAX, Market Cap: 288749242.83368653
Error getting RSI_Bullish_BTC for vela-token on 2025-07-10: Incompatible indexer with Series
Error getting RSI_Bullish_USD for vela-token on 2025-07-10: Incompatible indexer with Series
Error getting RSI_Bullish_BTC for swarm on 2025-07-13: Incompatible indexer with Series
Error getting RSI_Bullish_USD for swarm on 2025-07-13: Incompatible indexer with Series
Error getting RSI_Bullish_BTC for swarm on 2025-07-15: Incompatible indexer with Series
Error getting RSI_Bullish_USD for swarm on 2025-07-15: Incompatible indexer with Series
Error getting RSI_Bullish_BTC for smartcash on 2025-07-21: Incompatible indexer with Series
Error getting RSI_Bullish_USD for smartcash on 2025-07-21: Incompatible indexer with Series
Error getting RSI_Bullish_BTC for conic-finance on 2025-07-24: Incompatible indexer with Series
Error getting RSI_Bullish_USD for conic-finance on 2025-07-24: Incompatible indexer with Series
Error getting RSI_Bullish_BTC for smartcash on 2025-07-27: Incompatible indexer with Series
Error getting RSI_Bullish_USD for smartcash on 2025-07-27: Incompatible indexer with Series

In [ ]:

btc = results['asset_results'].get('bitcoin')['results_df']
btc

In [ ]:
import pandas as pd
import numpy as np

def apply_triple_barrier_labeling(df, profit_factor=2, stop_factor=2, time_window=7, stdev_window=20, debug=False):
    """
    Apply triple barrier method labeling to a trading dataframe with the following rules:
    - Positive Label (+1): Upper barrier (profit target) is breached first
    - Negative Label (-1): Lower barrier (stop loss) is breached first
    - Neutral Label (0): Time barrier expires without hitting either barrier
    
    Parameters:
    -----------
    df : pandas.DataFrame
        The dataframe containing trading data
    profit_factor : float, default=2
        Multiplier for standard deviation to determine profit target
    stop_factor : float, default=2
        Multiplier for standard deviation to determine stop loss
    time_window : int, default=7
        Number of days to look forward for label determination
    stdev_window : int, default=20
        Window size for standard deviation calculation
    debug : bool, default=False
        Whether to print debugging information
        
    Returns:
    --------
    pandas.DataFrame
        The original dataframe with additional 'triple_barrier_label' column
    """
    # Make a copy of the dataframe to avoid modifying the original
    df_copy = df.copy()
    
    # Calculate rolling standard deviation
    df_copy['rolling_std'] = df_copy['close'].rolling(window=stdev_window).std()
    
    # Initialize the label column
    df_copy['triple_barrier_label'] = np.nan
    
    # Debugging counters
    if debug:
        skipped_beginning = 0
        skipped_end = 0
        processed = 0
        labels_positive = 0
        labels_negative = 0
        labels_neutral = 0
    
    # Find rows where position changes (actual trade entries)
    position_entries = []
    
    # Look for either:
    # 1. Where position changes from 0 to non-zero
    if 'position' in df_copy.columns:
        for i in range(1, len(df_copy)):
            if df_copy['position'].iloc[i-1] == 0 and df_copy['position'].iloc[i] != 0:
                position_entries.append(i)
    
    # 2. Or where trade_executed is True
    if 'trade_executed' in df_copy.columns:
        for i in range(len(df_copy)):
            if df_copy['trade_executed'].iloc[i] == True:
                if i not in position_entries:
                    position_entries.append(i)
    
    # 3. Or where final_decision_shifted is 1 (assuming this indicates a trade signal)
    for i in range(len(df_copy)):
        if not pd.isna(df_copy['final_decision_shifted'].iloc[i]) and df_copy['final_decision_shifted'].iloc[i] == 1:
            if i not in position_entries:
                position_entries.append(i)
    
    if debug:
        print(f"Found {len(position_entries)} potential trade entry points")
    
    # Loop through each identified trade entry
    for i in position_entries:
        # Skip if we're too close to the beginning or end of the dataframe
        if i < stdev_window:
            if debug: skipped_beginning += 1
            continue
            
        if i >= len(df_copy) - 1:
            if debug: skipped_end += 1
            continue
        
        # Calculate profit target and stop loss
        entry_price = df_copy['open'].iloc[i]
        std_dev = df_copy['rolling_std'].iloc[i-1]  # Using previous day's std for decision
        
        # Skip if std_dev is NaN or 0
        if pd.isna(std_dev) or std_dev == 0:
            if debug: print(f"Warning: Standard deviation is {std_dev} at index {i}")
            continue
        
        profit_target = entry_price + profit_factor * std_dev
        stop_loss = entry_price - stop_factor * std_dev
        
        # Look forward up to time_window days
        label = None
        exit_day = min(i+time_window, len(df_copy)-1)
        
        for forward_idx in range(i+1, exit_day+1):
            current_price = df_copy['close'].iloc[forward_idx]
            
            # Check if profit target is hit first
            if current_price >= profit_target:
                label = 1  # Positive label
                if debug: labels_positive += 1
                break
                
            # Check if stop loss is hit first
            if current_price <= stop_loss:
                label = -1  # Negative label
                if debug: labels_negative += 1
                break
        
        # If neither barrier is hit within the time window, assign neutral label
        if label is None:
            label = 0  # Neutral label - time barrier hit first
            if debug: labels_neutral += 1
        
        # Assign the label
        df_copy.loc[df_copy.index[i], 'triple_barrier_label'] = label
        
        if debug: processed += 1
    
    if debug:
        print(f"Skipped (beginning): {skipped_beginning}")
        print(f"Skipped (end): {skipped_end}")
        print(f"Processed entries: {processed}")
        print(f"Positive labels (+1): {labels_positive}")
        print(f"Negative labels (-1): {labels_negative}")
        print(f"Neutral labels (0): {labels_neutral}")
        print(f"Non-NaN labels: {df_copy['triple_barrier_label'].notna().sum()}")
    
    return df_copy

# Example usage:
labeled_df = apply_triple_barrier_labeling(btc)
labeled_df

In [ ]:
# Import plotly if not already imported
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Create a figure with two subplots stacked vertically
fig = make_subplots(rows=2, cols=1, shared_xaxes=True, vertical_spacing=0.1, 
                    subplot_titles=('BTC Price', 'Trading Signals'))

# Plot BTC price in the top subplot
fig.add_trace(
    go.Scatter(x=labeled_df.index, y=labeled_df['close'], name='BTC Price', line=dict(color='blue')),
    row=1, col=1
)

# Plot position and triple barrier label in the bottom subplot
fig.add_trace(
    go.Scatter(x=labeled_df.index, y=labeled_df['position'], name='Position', line=dict(color='green')),
    row=2, col=1
)
fig.add_trace(
    go.Scatter(x=labeled_df.index, y=labeled_df['triple_barrier_label'], name='Triple Barrier Label', 
               line=dict(color='red')),
    row=2, col=1
)

# Update layout
fig.update_layout(
    height=800, 
    width=1200,
    showlegend=True,
    legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1)
)

# Update y-axis labels
fig.update_yaxes(title_text="Price (USD)", row=1, col=1)
fig.update_yaxes(title_text="Signal Value", row=2, col=1)
fig.update_xaxes(title_text="Date", row=2, col=1)

# Add grid lines
fig.update_xaxes(showgrid=True, gridwidth=1, gridcolor='LightGrey')
fig.update_yaxes(showgrid=True, gridwidth=1, gridcolor='LightGrey')

# Show the figure
fig.show()

In [ ]:
def create_returns_df_from_signals(analyzer, signal_df, min_days=90, min_market_cap=1000000000, max_market_cap=None):
    """
    Create a DataFrame of returns for assets that have a signal sum >= 3
    and have at least the minimum number of days of price data.
    
    Args:
        analyzer: PortfolioAnalyzer instance
        signal_df: DataFrame with signal values and Signal_Sum column
        min_days: Minimum number of days of price data required (default: 365)
        min_market_cap: Minimum market capitalization in USD to include an asset (default: 0)
        max_market_cap: Maximum market capitalization in USD to include an asset (default: None)
    
    Returns:
        DataFrame with daily returns for qualifying assets
    """
    # Filter assets with signal sum >= 3
    # For bitcoin, we only require a signal sum of 2, for all other assets we require 3
    bitcoin_assets = signal_df[
        (signal_df.index == 'bitcoin') & (signal_df['Signal_Sum'] >= 2)
    ].index.tolist()
    other_assets = signal_df[
        (signal_df.index != 'bitcoin') & (signal_df['Signal_Sum'] >= 4)
    ].index.tolist()
    qualified_assets = bitcoin_assets + other_assets
    
    # Dictionary to store returns series
    returns_dict = {}
    
    # Process each qualified asset
    for asset_id in qualified_assets:
        asset_data = analyzer.get_asset_data(asset_id)
        
        # Skip if asset data is None
        if asset_data is None:
            continue
            
        # Check market cap if filtering is enabled
        if min_market_cap > 0 or max_market_cap is not None:
            market_cap = None
            
            # Try to get from metadata if available
            if hasattr(asset_data, 'metadata') and asset_data.metadata:
                market_cap = asset_data.metadata.get('market_cap')
            
            # Try to get from asset_data directly
            if market_cap is None and hasattr(asset_data, 'market_cap'):
                market_cap = asset_data.market_cap
            
            # Try to get from price_data if available
            if market_cap is None and hasattr(asset_data, 'price_data'):
                if 'market_cap' in asset_data.price_data.columns:
                    # Use the most recent market cap value
                    market_cap = asset_data.price_data['market_cap'].iloc[-1]
            
            # Skip if market cap doesn't meet criteria
            if market_cap is not None:
                if (min_market_cap > 0 and market_cap < min_market_cap) or \
                   (max_market_cap is not None and market_cap > max_market_cap):
                    print(f"Skipping {asset_id}: Market cap {market_cap} outside range [{min_market_cap}, {max_market_cap or 'inf'}]")
                    continue
            elif min_market_cap > 0:
                print(f"Skipping {asset_id}: No market cap data available")
                continue
            
        # Get price data
        try:
            price_data = asset_data.get_price_data()
            
            if price_data is None or len(price_data) < min_days:
                print(f"Skipping {asset_id}: Only has {len(price_data) if price_data is not None else 0} days of data (minimum required: {min_days})")
                continue
                
            if 'close' in price_data.columns:
                # Calculate daily returns
                returns = price_data['close'].pct_change().dropna()
                
                # Make sure the index is unique before adding to the dictionary
                if returns.index.is_unique:
                    returns_dict[asset_id] = returns
                else:
                    # Handle duplicate indices by keeping the first occurrence
                    print(f"Warning: {asset_id} has duplicate dates. Keeping first occurrence.")
                    returns = returns[~returns.index.duplicated(keep='first')]
                    returns_dict[asset_id] = returns
            else:
                print(f"Skipping {asset_id}: Price data missing 'close' column")
        except Exception as e:
            print(f"Error processing {asset_id}: {e}")
    
    # Create DataFrame from the dictionary
    if returns_dict:
        # Create an empty DataFrame with a unique index that spans all series
        all_dates = sorted(set().union(*[returns.index for returns in returns_dict.values()]))
        returns_df = pd.DataFrame(index=all_dates)
        
        # Add each series to the DataFrame
        for asset_id, returns in returns_dict.items():
            returns_df[asset_id] = returns
            
        print(f"Created returns DataFrame with {len(returns_df.columns)} assets")
        return returns_df
    else:
        print("No qualifying assets found")
        return pd.DataFrame()

# Example usage
# Get signals for a specific date
date_to_check = "2024-11-25"  # Change to your desired date
signals_df = display_all_assets_signals_for_date(analyzer, date_to_check)

# Create returns DataFrame for assets with signal sum >= 3
returns_df = create_returns_df_from_signals(analyzer, signals_df)

# Display the first few rows of the returns DataFrame
if not returns_df.empty:
    display(returns_df.tail())
    
    # Display basic statistics
    print(f"\nReturns DataFrame Shape: {returns_df.shape}")
    print(f"Date Range: {returns_df.index.min()} to {returns_df.index.max()}")

In [131]:
def hrp_portfolio(returns_df):
    """
    Compute HRP portfolio allocations for a DataFrame of asset returns.

    Args:
        returns_df (pd.DataFrame): DataFrame with dates as rows, assets as columns,
                                   and daily returns as values (e.g., shape: (n_days, n_assets)).

    Returns:
        pd.DataFrame: Portfolio weights for each asset (index: asset names, column: 'weights').
    """
    # Step 1: Compute the covariance matrix and convert to NumPy array
    cov_matrix = returns_df.cov().values  # Convert to NumPy array
    
    # Ensure positive definiteness
    min_eig = np.min(np.real(np.linalg.eigvals(cov_matrix)))
    if min_eig <= 0:
        cov_matrix += (abs(min_eig) + 1e-5) * np.eye(cov_matrix.shape[0])

    # Step 2: Compute the correlation-based distance matrix
    std = np.sqrt(np.diag(cov_matrix))
    std[std == 0] = 1e-10  # Prevent division by zero
    corr = cov_matrix / np.outer(std, std)
    corr = np.clip(corr, -1, 1)  # Clip to valid range
    np.fill_diagonal(corr, 1)    # Ensure diagonal is 1 (now works since corr is a NumPy array)
    corr = (corr + corr.T) / 2   # Force symmetry

    distance = np.sqrt(np.maximum(0.5 * (1 - corr), 0))
    np.fill_diagonal(distance, 0)  # Ensure diagonal is 0
    distance = (distance + distance.T) / 2  # Force symmetry

    # Step 3: Perform hierarchical clustering
    dist_condensed = squareform(distance)
    clusters = linkage(dist_condensed, method='single')

    # Step 4: Allocate weights using HRP
    assets = returns_df.columns
    n = len(assets)
    weights = pd.Series(1.0, index=assets)
    clusters_dict = {i: [i] for i in range(n)}

    for i in range(n - 1):
        cluster1 = clusters_dict[int(clusters[i, 0])]
        cluster2 = clusters_dict[int(clusters[i, 1])]
        
        # Compute cluster variances (convert to NumPy array for slicing)
        cov_matrix_df = returns_df.cov()  # Keep as DataFrame for iloc indexing
        cluster_cov1 = cov_matrix_df.iloc[cluster1, cluster1].values
        cluster_cov2 = cov_matrix_df.iloc[cluster2, cluster2].values
        w1 = np.ones(len(cluster1)) / len(cluster1)
        w2 = np.ones(len(cluster2)) / len(cluster2)
        var1 = max(w1.T @ cluster_cov1 @ w1, 1e-10)
        var2 = max(w2.T @ cluster_cov2 @ w2, 1e-10)
        
        # Allocate weights inversely proportional to variance
        weight1 = 1 / var1
        weight2 = 1 / var2
        alpha = weight1 / (weight1 + weight2)
        
        weights.iloc[cluster1] *= alpha
        weights.iloc[cluster2] *= (1 - alpha)
        
        # Update clusters
        new_cluster_id = n + i
        clusters_dict[new_cluster_id] = cluster1 + cluster2

    # Normalize weights
    weights = weights / weights.sum()
    return pd.DataFrame(weights, columns=['weights'])

In [ ]:
hrp_portfolio(returns_df).sort_values(by='weights', ascending=False).head(10)