In [1]:
# Simple, clean approach with the unified interface
from soros_system.core.portfolio_analyzer import PortfolioAnalyzer
from scripts.assetsRoster import carteira_AC, carteira_HB, others, carteira_EXC, carteira_LC
import warnings

warnings.filterwarnings('ignore')


#assets = carteira_AC
assets = set(carteira_AC+carteira_HB+carteira_EXC+carteira_LC+others)
#assets=['bitcoin', 'ethereum', 'solana', 'dogecoin', 'chainlink', 'pendle']
#assets = ['bitcoin','dogecoin', 'pepe', 'spx', 'floki', 'fartcoin'  , 'bertram-the-pomeranian', 'fwog', 'neiro-3',
#          'evan-2', 'mubarak', 'baby-doge-coin', 'chill-guy', 'book-of-meme', 'slerf', 'shiba-inu', 
#          'official-trump', 'dogwifcoin', 'mog-coin', 'new-xai-gork', 'grok-2', 'bonk', 'goatseus-maximus',
#          'alchemist-ai', 'harrypotterobamasonic10in', 'kekius-maximus', 'aixbt', 'ava-ai', 'tokenbot-2',
#          'arbdoge-ai', 'based-brett', 'dog-go-to-the-moon-rune', 'siren-2', 'apu-s-club', 'turbo', 
#          'cat-in-a-dogs-world', 'snek', 'ai16z']


analyzer = PortfolioAnalyzer( 
    data_dir='/Users/valter.rebelo/MissionControl/data',
    data_path='/Users/valter.rebelo/MissionControl/data/micro/candleData/',
    btc_data_path='/Users/valter.rebelo/MissionControl/data/micro/candleData/bitcoin_candles.csv',
    ssr_data_path='/Users/valter.rebelo/MissionControl/data/onchainData/BTC_SSR.csv',
    market_data_path='/Users/valter.rebelo/MissionControl/data/micro/assetData/',
    asset_ids=assets

)

# Load assets - the analyzer handles paths internally

analyzer.load_data(assets=assets, start_date='2014-01-01', end_date='2025-12-31')

INFO: Using 7 workers for parallel processing
INFO: Loading data for assets...
INFO: Converted assets to list with 220 items
INFO: Using parallel loading for 220 assets

Loading assets:   0%|          | 0/220 [00:00<?, ?it/s]

INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/cosmos_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/story-2_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/goatseus-maximus_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/cosmos.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/story-2.csv
INFO: Added market data for cosmos
INFO: Successfully loaded data for cosmos with 2467 rows.
INFO: Added market data for story-2
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/goatseus-maximus.csv
INFO: Loaded data for cosmos with 2467 rows
INFO: Successfully loaded data for story-2 with 284 rows.

Loading assets:   0%|          | 1/220 [00:01<04:35,  1.26s/it]

INFO: Loaded data for story-2 with 284 rows
INFO: Added market data for goatseus-maximus
INFO: Successfully loaded data for goatseus-maximus with 407 rows.
INFO: Loaded data for goatseus-maximus with 407 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/the-sandbox_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/tezos_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/genesysgo-shadow_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/mubarak_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/tezos.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/the-sandbox.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/genesysgo-shadow.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/mubarak.csv
INFO: Added market data for the-sandbox
INFO: Successfully loaded data for the-sandbox with 1928 rows.
INFO: Loaded data for the-sandbox with 1928 rows

Loading assets:   2%|▏         | 4/220 [00:01<01:05,  3.29it/s]

INFO: Added market data for tezos
INFO: Successfully loaded data for tezos with 2703 rows.
INFO: Added market data for genesysgo-shadow
INFO: Added market data for mubarak
INFO: Loaded data for tezos with 2703 rows
INFO: Successfully loaded data for genesysgo-shadow with 1419 rows.
INFO: Successfully loaded data for mubarak with 253 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/true-usd_candles.csv
INFO: Loaded data for genesysgo-shadow with 1419 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/alpha-finance_candles.csv
INFO: Loaded data for mubarak with 253 rows

Loading assets:   3%|▎         | 7/220 [00:01<00:34,  6.14it/s]

INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/near_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/true-usd.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/alpha-finance.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/near.csv
INFO: Added market data for true-usd
INFO: Successfully loaded data for true-usd with 2804 rows.
INFO: Loaded data for true-usd with 2804 rows
INFO: Added market data for alpha-finance
INFO: Added market data for near
INFO: Successfully loaded data for alpha-finance with 1871 rows.
INFO: Successfully loaded data for near with 1867 rows.
INFO: Loaded data for alpha-finance with 1871 rows
INFO: Loaded data for near with 1867 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/spx6900_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/crypto-com-chain_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/spx6900.csv
INFO: Added market data for spx6900
INFO: Successfully loaded data for spx6900 with 819 rows.
INFO: Loaded data for spx6900 with 819 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/crypto-com-chain.csv

Loading assets:   5%|▌         | 11/220 [00:01<00:20, 10.05it/s]

INFO: Added market data for crypto-com-chain
INFO: Successfully loaded data for crypto-com-chain with 2519 rows.
INFO: Loaded data for crypto-com-chain with 2519 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/sei-network_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/clearpool_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/matic-network_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/sei-network.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/fwog_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/clearpool.csv
INFO: Added market data for sei-network
INFO: Successfully loaded data for sei-network with 832 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/akash-network_candles.csv
INFO: Loaded data for sei-network with 832 rows

Loading assets:   6%|▌         | 13/220 [00:01<00:20,  9.93it/s]

INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/matic-network.csv
INFO: Added market data for clearpool
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/fwog.csv
INFO: Successfully loaded data for clearpool with 1488 rows.
INFO: Loaded data for clearpool with 1488 rows
INFO: Added market data for fwog
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/kekius-maximus_candles.csv
INFO: Successfully loaded data for fwog with 482 rows.
INFO: Added market data for matic-network
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/akash-network.csv
INFO: Loaded data for fwog with 482 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/ava-ai_candles.csv
INFO: Successfully loaded data for matic-network with 2409 rows.
INFO: Loaded data for matic-network with 2409 rows

Loading assets:   7%|▋         | 16/220 [00:02<00:15, 13.04it/s]

INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/kekius-maximus.csv
INFO: Added market data for akash-network
INFO: Successfully loaded data for akash-network with 1865 rows.
INFO: Loaded data for akash-network with 1865 rows
INFO: Added market data for kekius-maximus
INFO: Successfully loaded data for kekius-maximus with 344 rows.
INFO: Loaded data for kekius-maximus with 344 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/ava-ai.csv
INFO: Added market data for ava-ai
INFO: Successfully loaded data for ava-ai with 368 rows.
INFO: Loaded data for ava-ai with 368 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/ether-fi_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/cookie_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/ether-fi.csv
INFO: Added market data for ether-fi
INFO: Successfully loaded data for ether-fi with 616 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/cardano_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/frax-share_candles.csv
INFO: Loaded data for ether-fi with 616 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/cookie.csv

Loading assets:   9%|▉         | 20/220 [00:02<00:21,  9.43it/s]

INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/slerf_candles.csv
INFO: Added market data for cookie
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/lisk_candles.csv
INFO: Successfully loaded data for cookie with 529 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/frax-share.csv
INFO: Loaded data for cookie with 529 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/cardano.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/slerf.csv
INFO: Added market data for frax-share
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/arbitrum_candles.csv
INFO: Added market data for cardano
INFO: Successfully loaded data for cardano with 2959 rows.
INFO: Added market data for slerf
INFO: Successfully loaded data for frax-share with 1799 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/lisk.csv
INFO: Loaded data for cardano with 2959 rows

Loading assets:  10%|█         | 22/220 [00:02<00:19, 10.05it/s]

INFO: Successfully loaded data for slerf with 616 rows.
INFO: Loaded data for frax-share with 1799 rows
INFO: Loaded data for slerf with 616 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/arbitrum.csv
INFO: Added market data for lisk
INFO: Successfully loaded data for lisk with 3519 rows.
INFO: Loaded data for lisk with 3519 rows
INFO: Added market data for arbitrum
INFO: Successfully loaded data for arbitrum with 977 rows.
INFO: Loaded data for arbitrum with 977 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/pancakeswap-token_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/pancakeswap-token.csv
INFO: Added market data for pancakeswap-token
INFO: Successfully loaded data for pancakeswap-token with 1882 rows.
INFO: Loaded data for pancakeswap-token with 1882 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/yearn-finance_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/dogwifcoin_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/yearn-finance.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/chill-guy_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/optimism_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/dogwifcoin.csv
INFO: Added market data for yearn-finance
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/neon_candles.csv
INFO: Successfully loaded data for yearn-finance with 1955 rows.
INFO: Loaded data for yearn-finance with 1955 rows
INFO: Added market data for dogwifcoin

Loading assets:  13%|█▎        | 28/220 [00:03<00:13, 14.14it/s]

INFO: Successfully loaded data for dogwifcoin with 712 rows.
INFO: Loaded data for dogwifcoin with 712 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/optimism.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/chill-guy.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/venice-token_candles.csv
INFO: Added market data for optimism
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/neon.csv
INFO: Successfully loaded data for optimism with 1273 rows.
INFO: Added market data for chill-guy
INFO: Successfully loaded data for chill-guy with 371 rows.
INFO: Loaded data for optimism with 1273 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/balancer_candles.csv

Loading assets:  14%|█▎        | 30/220 [00:03<00:15, 12.49it/s]

INFO: Added market data for neon
INFO: Loaded data for chill-guy with 371 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/venice-token.csv
INFO: Successfully loaded data for neon with 860 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/mantra-dao_candles.csv
INFO: Loaded data for neon with 860 rows
INFO: Added market data for venice-token
INFO: Successfully loaded data for venice-token with 301 rows.
INFO: Loaded data for venice-token with 301 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/balancer.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/mantra-dao.csv
INFO: Added market data for balancer
INFO: Successfully loaded data for balancer with 1980 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/aioz-network_candles.csv
INFO: Loaded data for balancer with 1980 rows
INFO: Added market data for mantra-dao

Loading assets:  15%|█▌        | 34/220 [00:03<00:12, 15.39it/s]

INFO: Successfully loaded data for mantra-dao with 1924 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/jasmycoin_candles.csv
INFO: Loaded data for mantra-dao with 1924 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/aioz-network.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/helium_candles.csv
INFO: Added market data for aioz-network
INFO: Successfully loaded data for aioz-network with 1696 rows.
INFO: Loaded data for aioz-network with 1696 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/jasmycoin.csv

Loading assets:  16%|█▋        | 36/220 [00:03<00:11, 15.54it/s]

INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/helium.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/anzen-finance_candles.csv
INFO: Added market data for jasmycoin
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/stellar_candles.csv
INFO: Successfully loaded data for jasmycoin with 1644 rows.
INFO: Added market data for helium
INFO: Loaded data for jasmycoin with 1644 rows
INFO: Successfully loaded data for helium with 2047 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/anzen-finance.csv
INFO: Loaded data for helium with 2047 rows
INFO: Added market data for anzen-finance

Loading assets:  17%|█▋        | 38/220 [00:03<00:12, 14.42it/s]

INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/bitcoin_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/stellar.csv
INFO: Successfully loaded data for anzen-finance with 350 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/dogecoin_candles.csv
INFO: Loaded data for anzen-finance with 350 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/bitcoin.csv
INFO: Added market data for stellar
INFO: Successfully loaded data for stellar with 4128 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/dogecoin.csv
INFO: Loaded data for stellar with 4128 rows

Loading assets:  18%|█▊        | 40/220 [00:04<00:15, 11.91it/s]

INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/velvet_candles.csv
INFO: Added market data for bitcoin
INFO: Successfully loaded data for bitcoin with 4593 rows.
INFO: Loaded data for bitcoin with 4593 rows
INFO: Added market data for dogecoin
INFO: Successfully loaded data for dogecoin with 4362 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/velvet.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/botto_candles.csv
INFO: Loaded data for dogecoin with 4362 rows
INFO: Added market data for velvet
INFO: Successfully loaded data for velvet with 136 rows.
INFO: Loaded data for velvet with 136 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/verasity_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/botto.csv
INFO: Added market data for botto
INFO: Successfully loaded data for botto with 1507 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/verasity.csv
INFO: Loaded data for botto with 1507 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/kaspa_candles.csv

Loading assets:  20%|██        | 44/220 [00:04<00:11, 14.70it/s]

INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/arweave_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/kaito_candles.csv
INFO: Added market data for verasity
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/kaspa.csv
INFO: Successfully loaded data for verasity with 1738 rows.
INFO: Loaded data for verasity with 1738 rows
INFO: Added market data for kaspa
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/arweave.csv
INFO: Successfully loaded data for kaspa with 1279 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/kaito.csv
INFO: Loaded data for kaspa with 1279 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/neiro-3_candles.csv
INFO: Added market data for arweave
INFO: Added market data for kaito
INFO: Successfully loaded data for kaito with 277 rows.
INFO: Successfully loaded data for arweave with 2216 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/polymath_candles.csv
INFO: Loaded data for kaito with 277 rows
INFO: Loaded data for arweave with 2216 rows

Loading assets:  21%|██▏       | 47/220 [00:04<00:10, 16.43it/s]

INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/neiro-3.csv
INFO: Added market data for neiro-3
INFO: Successfully loaded data for neiro-3 with 480 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/polymath.csv
INFO: Loaded data for neiro-3 with 480 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/the-open-network_candles.csv
INFO: Added market data for polymath
INFO: Successfully loaded data for polymath with 2845 rows.
INFO: Loaded data for polymath with 2845 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/the-open-network.csv
INFO: Added market data for the-open-network
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/genopets_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/kyber-network-crystal_candles.csv
INFO: Successfully loaded data for the-open-network with 1550 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/alchemy-pay_candles.csv
INFO: Loaded data for the-open-network with 1550 rows

Loading assets:  23%|██▎       | 51/220 [00:04<00:11, 15.15it/s]

INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/kyber-network-crystal.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/genopets.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/alchemy-pay.csv
INFO: Added market data for genopets
INFO: Successfully loaded data for genopets with 1467 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/blockstack_candles.csv
INFO: Added market data for kyber-network-crystal
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/turbo_candles.csv
INFO: Loaded data for genopets with 1467 rows
INFO: Added market data for alchemy-pay
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/usd-coin_candles.csv
INFO: Successfully loaded data for kyber-network-crystal with 1677 rows.
INFO: Successfully loaded data for alchemy-pay with 1903 rows.
INFO: Loaded data for kyber-network-crystal with 1677 rows
INFO: Loaded data for alchemy-pay with 1903 rows

Loading assets:  24%|██▍       | 53/220 [00:04<00:10, 15.19it/s]

INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/blockstack.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/turbo.csv
INFO: Added market data for blockstack
INFO: Successfully loaded data for blockstack with 2223 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/usd-coin.csv
INFO: Added market data for turbo
INFO: Loaded data for blockstack with 2223 rows
INFO: Successfully loaded data for turbo with 935 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/paal-ai_candles.csv
INFO: Loaded data for turbo with 935 rows
INFO: Added market data for usd-coin
INFO: Successfully loaded data for usd-coin with 2608 rows.
INFO: Loaded data for usd-coin with 2608 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/paal-ai.csv
INFO: Added market data for paal-ai
INFO: Successfully loaded data for paal-ai with 882 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/based-brett_candles.csv
INFO: Loaded data for paal-ai with 882 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/badger-dao_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/based-brett.csv
INFO: Added market data for based-brett
INFO: Successfully loaded data for based-brett with 634 rows.
INFO: Loaded data for based-brett with 634 rows

Loading assets:  27%|██▋       | 59/220 [00:04<00:08, 19.03it/s]

INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/badger-dao.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/flow_candles.csv
INFO: Added market data for badger-dao
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/swarm_candles.csv
INFO: Successfully loaded data for badger-dao with 1816 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/flow.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/mog-coin_candles.csv
INFO: Loaded data for badger-dao with 1816 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/tokenbot-2_candles.csv
INFO: Added market data for flow
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/swarm.csv
INFO: Successfully loaded data for flow with 1762 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/mog-coin.csv
INFO: Loaded data for flow with 1762 rows

Loading assets:  28%|██▊       | 61/220 [00:05<00:10, 15.33it/s]

INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/bubblemaps_candles.csv
INFO: Added market data for swarm
INFO: Added market data for mog-coin
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/tokenbot-2.csv
INFO: Successfully loaded data for swarm with 3497 rows.
INFO: Successfully loaded data for mog-coin with 857 rows.
INFO: Loaded data for swarm with 3497 rows
INFO: Added market data for tokenbot-2
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/apu-s-club_candles.csv
INFO: Loaded data for mog-coin with 857 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/bubblemaps.csv
INFO: Successfully loaded data for tokenbot-2 with 379 rows.
INFO: Loaded data for tokenbot-2 with 379 rows
INFO: Added market data for bubblemaps
INFO: Successfully loaded data for bubblemaps with 258 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/apu-s-club.csv
INFO: Loaded data for bubblemaps with 258 rows

Loading assets:  30%|██▉       | 65/220 [00:05<00:08, 18.98it/s]

INFO: Added market data for apu-s-club
INFO: Successfully loaded data for apu-s-club with 621 rows.
INFO: Loaded data for apu-s-club with 621 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/pax-gold_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/pump-fun_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/pax-gold.csv
INFO: Added market data for pax-gold
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/zeus-network_candles.csv
INFO: Successfully loaded data for pax-gold with 2262 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/pump-fun.csv
INFO: Loaded data for pax-gold with 2262 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/injective-protocol_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/bonk_candles.csv
INFO: Added market data for pump-fun
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/zeus-network.csv
INFO: Successfully loaded data for pump-fun with 132 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/solana_candles.csv
INFO: Loaded data for pump-fun with 132 rows
INFO: Added market data for zeus-network

Loading assets:  31%|███       | 68/220 [00:05<00:09, 16.15it/s]

INFO: Successfully loaded data for zeus-network with 598 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/bonk.csv
INFO: Loaded data for zeus-network with 598 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/injective-protocol.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/dusk-network_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/solana.csv
INFO: Added market data for bonk
INFO: Added market data for injective-protocol
INFO: Successfully loaded data for injective-protocol with 1860 rows.
INFO: Added market data for solana
INFO: Successfully loaded data for bonk with 1061 rows.
INFO: Loaded data for injective-protocol with 1860 rows
INFO: Successfully loaded data for solana with 2054 rows.

Loading assets:  32%|███▏      | 70/220 [00:05<00:10, 14.80it/s]

INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/dusk-network.csv
INFO: Loaded data for bonk with 1061 rows
INFO: Loaded data for solana with 2054 rows
INFO: Added market data for dusk-network
INFO: Successfully loaded data for dusk-network with 2333 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/harrypotterobamasonic10in_candles.csv
INFO: Loaded data for dusk-network with 2333 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/ronin_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/harrypotterobamasonic10in.csv
INFO: Added market data for harrypotterobamasonic10in
INFO: Successfully loaded data for harrypotterobamasonic10in with 924 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/bio-protocol_candles.csv
INFO: Loaded data for harrypotterobamasonic10in with 924 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/ronin.csv

Loading assets:  34%|███▎      | 74/220 [00:05<00:08, 17.80it/s]

INFO: Added market data for ronin
INFO: Successfully loaded data for ronin with 1397 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/chex-token_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/bio-protocol.csv
INFO: Loaded data for ronin with 1397 rows
INFO: Added market data for bio-protocol
INFO: Successfully loaded data for bio-protocol with 324 rows.
INFO: Loaded data for bio-protocol with 324 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/gala_candles.csv

Loading assets:  35%|███▍      | 76/220 [00:06<00:08, 16.59it/s]

INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/band-protocol_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/chex-token.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/euler_candles.csv
INFO: Added market data for chex-token
INFO: Successfully loaded data for chex-token with 2119 rows.
INFO: Loaded data for chex-token with 2119 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/gala.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/band-protocol.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/morpho_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/beam-2_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/euler.csv
INFO: Added market data for band-protocol
INFO: Added market data for gala
INFO: Successfully loaded data for band-protocol with 2259 rows.
INFO: Successfully loaded data for gala with 1895 rows.
INFO: Added market data for euler
INFO: Loaded data for band-protocol with 2259 rows
INFO: Loaded data for gala with 1895 rows

Loading assets:  35%|███▌      | 78/220 [00:06<00:12, 11.18it/s]

INFO: Successfully loaded data for euler with 1249 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/beam-2.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/morpho.csv
INFO: Loaded data for euler with 1249 rows

Loading assets:  36%|███▋      | 80/220 [00:06<00:14,  9.65it/s]

INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/deep_candles.csv
INFO: Added market data for beam-2
INFO: Added market data for morpho
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/power-ledger_candles.csv
INFO: Successfully loaded data for beam-2 with 760 rows.
INFO: Successfully loaded data for morpho with 369 rows.
INFO: Loaded data for beam-2 with 760 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/deep.csv
INFO: Loaded data for morpho with 369 rows

Loading assets:  37%|███▋      | 82/220 [00:07<00:14,  9.24it/s]

INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/power-ledger.csv
INFO: Added market data for deep
INFO: Successfully loaded data for deep with 406 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/fantom_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/dash_candles.csv
INFO: Loaded data for deep with 406 rows
INFO: Added market data for power-ledger
INFO: Successfully loaded data for power-ledger with 2938 rows.
INFO: Loaded data for power-ledger with 2938 rows

Loading assets:  38%|███▊      | 84/220 [00:07<00:12, 10.46it/s]

INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/dodo_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/fantom.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/dash.csv
INFO: Added market data for fantom
INFO: Successfully loaded data for fantom with 2583 rows.
INFO: Loaded data for fantom with 2583 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/dodo.csv
INFO: Added market data for dash
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/rari-governance-token_candles.csv
INFO: Successfully loaded data for dash with 4301 rows.
INFO: Added market data for dodo
INFO: Successfully loaded data for dodo with 1881 rows.
INFO: Loaded data for dash with 4301 rows
INFO: Loaded data for dodo with 1881 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/rari-governance-token.csv

Loading assets:  39%|███▉      | 86/220 [00:07<00:12, 10.76it/s]

INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/secret_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/internet-computer_candles.csv
INFO: Added market data for rari-governance-token
INFO: Successfully loaded data for rari-governance-token with 1868 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/arkham_candles.csv
INFO: Loaded data for rari-governance-token with 1868 rows

Loading assets:  40%|████      | 88/220 [00:07<00:11, 11.45it/s]

INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/secret.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/internet-computer.csv
INFO: Added market data for internet-computer
INFO: Successfully loaded data for internet-computer with 1659 rows.
INFO: Added market data for secret
INFO: Successfully loaded data for secret with 1880 rows.
INFO: Loaded data for internet-computer with 1659 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/arkham.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/chainlink_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/numeraire_candles.csv
INFO: Loaded data for secret with 1880 rows

Loading assets:  41%|████      | 90/220 [00:08<00:21,  6.01it/s]

INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/aethir_candles.csv
INFO: Added market data for arkham
INFO: Successfully loaded data for arkham with 860 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/sturdy_candles.csv
INFO: Loaded data for arkham with 860 rows

Loading assets:  41%|████▏     | 91/220 [00:08<00:20,  6.15it/s]

INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/numeraire.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/chainlink.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/aethir.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/sturdy.csv
INFO: Added market data for numeraire
INFO: Successfully loaded data for numeraire with 3056 rows.
INFO: Added market data for aethir
INFO: Added market data for chainlink
INFO: Added market data for sturdy
INFO: Loaded data for numeraire with 3056 rows
INFO: Successfully loaded data for aethir with 530 rows.

Loading assets:  42%|████▏     | 92/220 [00:08<00:25,  4.97it/s]

INFO: Successfully loaded data for chainlink with 2937 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/dog-go-to-the-moon-rune_candles.csv
INFO: Successfully loaded data for sturdy with 641 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/pepe_candles.csv
INFO: Loaded data for aethir with 530 rows

Loading assets:  42%|████▏     | 93/220 [00:08<00:23,  5.41it/s]

INFO: Loaded data for chainlink with 2937 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/virtual-protocol_candles.csv
INFO: Loaded data for sturdy with 641 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/dog-go-to-the-moon-rune.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/pepe.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/virtual-protocol.csv
INFO: Added market data for dog-go-to-the-moon-rune
INFO: Successfully loaded data for dog-go-to-the-moon-rune with 577 rows.
INFO: Loaded data for dog-go-to-the-moon-rune with 577 rows

Loading assets:  44%|████▎     | 96/220 [00:08<00:13,  8.93it/s]

INFO: Added market data for pepe
INFO: Added market data for virtual-protocol
INFO: Successfully loaded data for pepe with 951 rows.
INFO: Successfully loaded data for virtual-protocol with 697 rows.
INFO: Loaded data for pepe with 951 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/aixbt_candles.csv
INFO: Loaded data for virtual-protocol with 697 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/pudgy-penguins_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/aixbt.csv
INFO: Added market data for aixbt
INFO: Successfully loaded data for aixbt with 371 rows.
INFO: Loaded data for aixbt with 371 rows

Loading assets:  45%|████▌     | 99/220 [00:09<00:14,  8.64it/s]

INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/pudgy-penguins.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/aurory_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/illuvium_candles.csv
INFO: Added market data for pudgy-penguins
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/tether_candles.csv
INFO: Successfully loaded data for pudgy-penguins with 342 rows.
INFO: Loaded data for pudgy-penguins with 342 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/illuvium.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/multibit_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/aurory.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/curve-dao-token_candles.csv
INFO: Added market data for illuvium
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/tether.csv
INFO: Successfully loaded data for illuvium with 1699 rows.
INFO: Added market data for aurory
INFO: Loaded data for illuvium with 1699 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/multibit.csv

Loading assets:  46%|████▌     | 101/220 [00:09<00:20,  5.78it/s]

INFO: Successfully loaded data for aurory with 1492 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/ethereum-classic_candles.csv
INFO: Added market data for tether
INFO: Loaded data for aurory with 1492 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/curve-dao-token.csv
INFO: Successfully loaded data for tether with 3925 rows.
INFO: Added market data for multibit
INFO: Loaded data for tether with 3925 rows
INFO: Successfully loaded data for multibit with 735 rows.
INFO: Added market data for curve-dao-token
INFO: Loaded data for multibit with 735 rows
INFO: Successfully loaded data for curve-dao-token with 1928 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/ethereum-classic.csv
INFO: Loaded data for curve-dao-token with 1928 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/tron_candles.csv
INFO: Added market data for ethereum-classic
INFO: Successfully loaded data for ethereum-classic with 3410 rows.
INFO: Loaded data for ethereum-classic with 3410 rows

Loading assets:  48%|████▊     | 106/220 [00:10<00:11, 10.09it/s]

INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/tron.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/hypercycle_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/orbit-3_candles.csv
INFO: Added market data for tron
INFO: Successfully loaded data for tron with 2937 rows.
INFO: Loaded data for tron with 2937 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/hypercycle.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/orbit-3.csv
INFO: Added market data for hypercycle
INFO: Successfully loaded data for hypercycle with 930 rows.
INFO: Loaded data for hypercycle with 930 rows
INFO: Added market data for orbit-3

Loading assets:  49%|████▉     | 108/220 [00:10<00:10, 11.15it/s]

INFO: Successfully loaded data for orbit-3 with 351 rows.
INFO: Loaded data for orbit-3 with 351 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/eigenlayer_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/metacade_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/axelar_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/eigenlayer.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/metacade.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/axelar.csv
INFO: Added market data for eigenlayer
INFO: Successfully loaded data for eigenlayer with 419 rows.
INFO: Loaded data for eigenlayer with 419 rows

Loading assets:  50%|█████     | 110/220 [00:10<00:09, 11.90it/s]

INFO: Added market data for axelar
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/celestia_candles.csv
INFO: Successfully loaded data for axelar with 1154 rows.
INFO: Added market data for metacade
INFO: Loaded data for axelar with 1154 rows
INFO: Successfully loaded data for metacade with 958 rows.
INFO: Loaded data for metacade with 958 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/celestia.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/worldcoin-wld_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/decentraland_candles.csv
INFO: Added market data for celestia
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/myria_candles.csv
INFO: Successfully loaded data for celestia with 755 rows.
INFO: Loaded data for celestia with 755 rows

Loading assets:  51%|█████▏    | 113/220 [00:10<00:08, 12.57it/s]

INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/worldcoin-wld.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/decentraland.csv
INFO: Added market data for worldcoin-wld
INFO: Successfully loaded data for worldcoin-wld with 854 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/myria.csv
INFO: Loaded data for worldcoin-wld with 854 rows
INFO: Added market data for decentraland
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/yield-guild-games_candles.csv
INFO: Successfully loaded data for decentraland with 2949 rows.
INFO: Added market data for myria
INFO: Loaded data for decentraland with 2949 rows

Loading assets:  52%|█████▏    | 115/220 [00:10<00:08, 12.18it/s]

INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/prisma-governance-token_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/evan-2_candles.csv
INFO: Successfully loaded data for myria with 963 rows.
INFO: Loaded data for myria with 963 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/yield-guild-games.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/evan-2.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/prisma-governance-token.csv
INFO: Added market data for yield-guild-games
INFO: Successfully loaded data for yield-guild-games with 1580 rows.
INFO: Loaded data for yield-guild-games with 1580 rows
INFO: Added market data for evan-2
INFO: Added market data for prisma-governance-token
INFO: Successfully loaded data for evan-2 with 367 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/audius_candles.csv
INFO: Successfully loaded data for prisma-governance-token with 753 rows.
INFO: Loaded data for evan-2 with 367 rows
INFO: Loaded data for prisma-governance-token with 753 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/audius.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/terra-luna-2_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/ai16z_candles.csv
INFO: Added market data for audius
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/moonwell-artemis_candles.csv
INFO: Successfully loaded data for audius with 1858 rows.
INFO: Loaded data for audius with 1858 rows

Loading assets:  55%|█████▍    | 120/220 [00:10<00:06, 16.15it/s]

INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/terra-luna-2.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/ai16z.csv
INFO: Added market data for ai16z
INFO: Successfully loaded data for ai16z with 393 rows.
INFO: Added market data for terra-luna-2
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/moonwell-artemis.csv
INFO: Loaded data for ai16z with 393 rows
INFO: Successfully loaded data for terra-luna-2 with 1276 rows.
INFO: Loaded data for terra-luna-2 with 1276 rows

Loading assets:  55%|█████▌    | 122/220 [00:10<00:06, 16.17it/s]

INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/my-neighbor-alice_candles.csv
INFO: Added market data for moonwell-artemis
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/raydium_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/uniswap_candles.csv
INFO: Successfully loaded data for moonwell-artemis with 1250 rows.
INFO: Loaded data for moonwell-artemis with 1250 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/my-neighbor-alice.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/raydium.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/uniswap.csv
INFO: Added market data for my-neighbor-alice
INFO: Added market data for raydium
INFO: Successfully loaded data for raydium with 1737 rows.
INFO: Successfully loaded data for my-neighbor-alice with 1715 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/sonic-3_candles.csv
INFO: Loaded data for raydium with 1737 rows

Loading assets:  56%|█████▋    | 124/220 [00:11<00:10,  8.85it/s]

INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/heyanon_candles.csv
INFO: Loaded data for my-neighbor-alice with 1715 rows
INFO: Added market data for uniswap
INFO: Successfully loaded data for uniswap with 1894 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/aave_candles.csv
INFO: Loaded data for uniswap with 1894 rows

Loading assets:  57%|█████▋    | 126/220 [00:11<00:09,  9.46it/s]

INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/sonic-3.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/instadapp_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/heyanon.csv
INFO: Added market data for sonic-3
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/aave.csv
INFO: Successfully loaded data for sonic-3 with 324 rows.
INFO: Added market data for heyanon
INFO: Loaded data for sonic-3 with 324 rows
INFO: Added market data for aave
INFO: Successfully loaded data for heyanon with 332 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/instadapp.csv
INFO: Successfully loaded data for aave with 1878 rows.
INFO: Loaded data for heyanon with 332 rows
INFO: Loaded data for aave with 1878 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/solayer_candles.csv

Loading assets:  58%|█████▊    | 128/220 [00:12<00:20,  4.47it/s]

INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/coredaoorg_candles.csv
INFO: Added market data for instadapp
INFO: Successfully loaded data for instadapp with 1622 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/guild-of-guardians_candles.csv
INFO: Loaded data for instadapp with 1622 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/solayer.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/coredaoorg.csv
INFO: Added market data for solayer
INFO: Successfully loaded data for solayer with 286 rows.
INFO: Added market data for coredaoorg
INFO: Loaded data for solayer with 286 rows
INFO: Successfully loaded data for coredaoorg with 1020 rows.

Loading assets:  60%|█████▉    | 131/220 [00:12<00:14,  6.27it/s]

INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/guild-of-guardians.csv
INFO: Loaded data for coredaoorg with 1020 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/official-trump_candles.csv
INFO: Added market data for guild-of-guardians
INFO: Successfully loaded data for guild-of-guardians with 1433 rows.
INFO: Loaded data for guild-of-guardians with 1433 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/gigachad-2_candles.csv

Loading assets:  60%|██████    | 133/220 [00:13<00:11,  7.36it/s]

INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/official-trump.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/monero_candles.csv
INFO: Added market data for official-trump
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/rainbow-token-2_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/gigachad-2.csv
INFO: Successfully loaded data for official-trump with 310 rows.
INFO: Loaded data for official-trump with 310 rows
INFO: Added market data for gigachad-2
INFO: Successfully loaded data for gigachad-2 with 672 rows.
INFO: Loaded data for gigachad-2 with 672 rows

Loading assets:  61%|██████▏   | 135/220 [00:13<00:10,  7.84it/s]

INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/rainbow-token-2.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/prometeus_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/monero.csv
INFO: Added market data for rainbow-token-2
INFO: Successfully loaded data for rainbow-token-2 with 1348 rows.
INFO: Loaded data for rainbow-token-2 with 1348 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/wibx_candles.csv
INFO: Added market data for monero
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/prometeus.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/echelon-prime_candles.csv
INFO: Successfully loaded data for monero with 4205 rows.
INFO: Loaded data for monero with 4205 rows

Loading assets:  62%|██████▏   | 137/220 [00:13<00:14,  5.80it/s]

INFO: Added market data for prometeus
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/wibx.csv
INFO: Successfully loaded data for prometeus with 2341 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/echelon-prime.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/gmx_candles.csv
INFO: Loaded data for prometeus with 2341 rows
INFO: Added market data for wibx
INFO: Successfully loaded data for wibx with 2047 rows.
INFO: Loaded data for wibx with 2047 rows

Loading assets:  63%|██████▎   | 139/220 [00:14<00:11,  7.01it/s]

INFO: Added market data for echelon-prime
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/plume_candles.csv
INFO: Successfully loaded data for echelon-prime with 998 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/gmx.csv
INFO: Loaded data for echelon-prime with 998 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/binancecoin_candles.csv
INFO: Added market data for gmx
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/plume.csv
INFO: Successfully loaded data for gmx with 1533 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/syrup_candles.csv
INFO: Loaded data for gmx with 1533 rows

Loading assets:  64%|██████▍   | 141/220 [00:14<00:09,  8.17it/s]

INFO: Added market data for plume
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/binancecoin.csv
INFO: Successfully loaded data for plume with 307 rows.
INFO: Loaded data for plume with 307 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/syrup.csv
INFO: Added market data for binancecoin
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/cat-in-a-dogs-world_candles.csv
INFO: Successfully loaded data for binancecoin with 2991 rows.
INFO: Loaded data for binancecoin with 2991 rows
INFO: Added market data for syrup
INFO: Successfully loaded data for syrup with 376 rows.
INFO: Loaded data for syrup with 376 rows

Loading assets:  65%|██████▌   | 144/220 [00:14<00:07, 10.81it/s]

INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/wrapped-nxm_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/star-atlas-dao_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/cat-in-a-dogs-world.csv
INFO: Added market data for cat-in-a-dogs-world
INFO: Successfully loaded data for cat-in-a-dogs-world with 608 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/wrapped-nxm.csv
INFO: Loaded data for cat-in-a-dogs-world with 608 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/star-atlas-dao.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/maker_candles.csv
INFO: Added market data for wrapped-nxm
INFO: Successfully loaded data for wrapped-nxm with 1946 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/perpetual-protocol_candles.csv
INFO: Loaded data for wrapped-nxm with 1946 rows

Loading assets:  66%|██████▋   | 146/220 [00:14<00:06, 11.66it/s]

INFO: Added market data for star-atlas-dao
INFO: Successfully loaded data for star-atlas-dao with 1544 rows.
INFO: Loaded data for star-atlas-dao with 1544 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/maker.csv
INFO: Added market data for maker
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/render-token_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/perpetual-protocol.csv
INFO: Successfully loaded data for maker with 2896 rows.
INFO: Loaded data for maker with 2896 rows

Loading assets:  67%|██████▋   | 148/220 [00:15<00:10,  6.61it/s]

INFO: Added market data for perpetual-protocol
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/zcash_candles.csv
INFO: Successfully loaded data for perpetual-protocol with 1902 rows.
INFO: Loaded data for perpetual-protocol with 1902 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/render-token.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/bitcoin-cash_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/axie-infinity_candles.csv
INFO: Added market data for render-token
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/arbdoge-ai_candles.csv
INFO: Successfully loaded data for render-token with 1988 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/bitcoin-cash.csv
INFO: Loaded data for render-token with 1988 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/zcash.csv

Loading assets:  68%|██████▊   | 150/220 [00:15<00:10,  6.63it/s]

INFO: Added market data for bitcoin-cash
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/arbdoge-ai.csv
INFO: Successfully loaded data for bitcoin-cash with 3036 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/axie-infinity.csv
INFO: Added market data for zcash
INFO: Loaded data for bitcoin-cash with 3036 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/lagrange_candles.csv
INFO: Successfully loaded data for zcash with 3313 rows.
INFO: Added market data for arbdoge-ai
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/yne_candles.csv
INFO: Added market data for axie-infinity
INFO: Loaded data for zcash with 3313 rows

Loading assets:  69%|██████▉   | 152/220 [00:15<00:08,  7.65it/s]

INFO: Successfully loaded data for arbdoge-ai with 951 rows.
INFO: Successfully loaded data for axie-infinity with 1846 rows.
INFO: Loaded data for arbdoge-ai with 951 rows
INFO: Loaded data for axie-infinity with 1846 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/yne.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/lagrange.csv
INFO: Added market data for yne
INFO: Added market data for lagrange
INFO: Successfully loaded data for yne with 336 rows.
INFO: Successfully loaded data for lagrange with 173 rows.
INFO: Loaded data for yne with 336 rows
INFO: Loaded data for lagrange with 173 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/constitutiondao_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/constitutiondao.csv
INFO: Added market data for constitutiondao
INFO: Successfully loaded data for constitutiondao with 1466 rows.
INFO: Loaded data for constitutiondao with 1466 rows

Loading assets:  71%|███████▏  | 157/220 [00:15<00:04, 12.70it/s]

INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/floki_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/snek_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/bigcoin-2_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/floki.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/snek.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/bigcoin-2.csv
INFO: Added market data for floki
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/vela-token_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/ripple_candles.csv
INFO: Added market data for snek
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/kamino_candles.csv
INFO: Successfully loaded data for floki with 1610 rows.
INFO: Added market data for bigcoin-2
INFO: Successfully loaded data for snek with 917 rows.
INFO: Loaded data for floki with 1610 rows
INFO: Successfully loaded data for bigcoin-2 with 222 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/equilibria-finance_candles.csv
INFO: Loaded data for snek with 917 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/vela-token.csv

Loading assets:  72%|███████▏  | 159/220 [00:16<00:08,  7.23it/s]

INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/ripple.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/kamino.csv
INFO: Loaded data for bigcoin-2 with 222 rows
INFO: Added market data for vela-token
INFO: Successfully loaded data for vela-token with 1023 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/equilibria-finance.csv
INFO: Loaded data for vela-token with 1023 rows
INFO: Added market data for kamino
INFO: Added market data for ripple
INFO: Successfully loaded data for ripple with 4495 rows.
INFO: Added market data for equilibria-finance
INFO: Successfully loaded data for kamino with 573 rows.
INFO: Loaded data for ripple with 4495 rows
INFO: Successfully loaded data for equilibria-finance with 901 rows.
INFO: Loaded data for kamino with 573 rows
INFO: Loaded data for equilibria-finance with 901 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/griffain_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/griffain.csv
INFO: Added market data for griffain
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/bittensor_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/mamo_candles.csv
INFO: Successfully loaded data for griffain with 353 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/eos_candles.csv
INFO: Loaded data for griffain with 353 rows

Loading assets:  75%|███████▌  | 165/220 [00:16<00:05, 10.39it/s]

INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/hyperliquid_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/bittensor.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/mamo.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/hyperliquid.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/pendle_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/eos.csv
INFO: Added market data for mamo
INFO: Added market data for bittensor
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/alchemist-ai_candles.csv
INFO: Successfully loaded data for mamo with 187 rows.
INFO: Added market data for hyperliquid
INFO: Successfully loaded data for bittensor with 997 rows.
INFO: Loaded data for mamo with 187 rows
INFO: Successfully loaded data for hyperliquid with 361 rows.
INFO: Loaded data for bittensor with 997 rows
INFO: Added market data for eos

Loading assets:  76%|███████▌  | 167/220 [00:17<00:10,  5.20it/s]

INFO: Successfully loaded data for eos with 3060 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/pendle.csv
INFO: Loaded data for hyperliquid with 361 rows
INFO: Loaded data for eos with 3060 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/alchemist-ai.csv

Loading assets:  77%|███████▋  | 169/220 [00:18<00:08,  5.83it/s]

INFO: Added market data for pendle
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/sui_candles.csv
INFO: Successfully loaded data for pendle with 1671 rows.
INFO: Added market data for alchemist-ai
INFO: Loaded data for pendle with 1671 rows
INFO: Successfully loaded data for alchemist-ai with 358 rows.
INFO: Loaded data for alchemist-ai with 358 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/sui.csv
INFO: Added market data for sui
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/dydx_candles.csv
INFO: Successfully loaded data for sui with 936 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/polkadot_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/smartcash_candles.csv
INFO: Loaded data for sui with 936 rows

Loading assets:  78%|███████▊  | 172/220 [00:18<00:07,  6.57it/s]

INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/dydx.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/sushi_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/polkadot.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/smartcash.csv
INFO: Added market data for dydx
INFO: Successfully loaded data for dydx with 1538 rows.
INFO: Added market data for polkadot
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/immutable-x_candles.csv
INFO: Loaded data for dydx with 1538 rows
INFO: Successfully loaded data for polkadot with 1923 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/sushi.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/y_candles.csv
INFO: Added market data for smartcash
INFO: Loaded data for polkadot with 1923 rows

Loading assets:  79%|███████▉  | 174/220 [00:19<00:08,  5.32it/s]

INFO: Successfully loaded data for smartcash with 2979 rows.
INFO: Added market data for sushi
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/grok-2_candles.csv
INFO: Loaded data for smartcash with 2979 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/immutable-x.csv
INFO: Successfully loaded data for sushi with 1914 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/y.csv
INFO: Loaded data for sushi with 1914 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/grok-2.csv
INFO: Added market data for immutable-x
INFO: Added market data for y
INFO: Successfully loaded data for y with 602 rows.
INFO: Added market data for grok-2
INFO: Successfully loaded data for immutable-x with 1480 rows.
INFO: Loaded data for y with 602 rows

Loading assets:  80%|████████  | 177/220 [00:19<00:08,  5.33it/s]

INFO: Successfully loaded data for grok-2 with 748 rows.
INFO: Loaded data for immutable-x with 1480 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/arpa_candles.csv
INFO: Loaded data for grok-2 with 748 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/ethervista_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/mintlayer_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/grass_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/ethervista.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/arpa.csv
INFO: Added market data for ethervista
INFO: Successfully loaded data for ethervista with 449 rows.
INFO: Loaded data for ethervista with 449 rows

Loading assets:  82%|████████▏ | 180/220 [00:19<00:06,  5.95it/s]

INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/grass.csv
INFO: Added market data for arpa
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/mintlayer.csv
INFO: Added market data for grass
INFO: Successfully loaded data for arpa with 2372 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/gains-network_candles.csv
INFO: Added market data for mintlayer
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/hedera-hashgraph_candles.csv
INFO: Successfully loaded data for grass with 392 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/havven_candles.csv
INFO: Loaded data for arpa with 2372 rows
INFO: Successfully loaded data for mintlayer with 975 rows.

Loading assets:  82%|████████▏ | 181/220 [00:20<00:07,  4.96it/s]

INFO: Loaded data for grass with 392 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/gains-network.csv

Loading assets:  83%|████████▎ | 182/220 [00:20<00:07,  5.22it/s]

INFO: Loaded data for mintlayer with 975 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/hedera-hashgraph.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/radiant-capital_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/havven.csv
INFO: Added market data for gains-network
INFO: Successfully loaded data for gains-network with 1483 rows.
INFO: Added market data for hedera-hashgraph
INFO: Successfully loaded data for hedera-hashgraph with 2260 rows.
INFO: Added market data for havven
INFO: Loaded data for gains-network with 1483 rows
INFO: Loaded data for hedera-hashgraph with 2260 rows

Loading assets:  84%|████████▎ | 184/220 [00:20<00:05,  6.67it/s]

INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/radiant-capital.csv
INFO: Successfully loaded data for havven with 2806 rows.
INFO: Loaded data for havven with 2806 rows
INFO: Added market data for radiant-capital
INFO: Successfully loaded data for radiant-capital with 1217 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/avalanche-2_candles.csv
INFO: Loaded data for radiant-capital with 1217 rows

Loading assets:  85%|████████▌ | 187/220 [00:21<00:04,  7.05it/s]

INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/avalanche-2.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/omisego_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/ethena_candles.csv
INFO: Added market data for avalanche-2
INFO: Successfully loaded data for avalanche-2 with 1889 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/fetch-ai_candles.csv
INFO: Loaded data for avalanche-2 with 1889 rows

Loading assets:  85%|████████▌ | 188/220 [00:21<00:06,  4.79it/s]

INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/ethena.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/nunet_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/omisego.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/bertram-the-pomeranian_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/baby-doge-coin_candles.csv
INFO: Added market data for ethena
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/fetch-ai.csv
INFO: Successfully loaded data for ethena with 601 rows.
INFO: Added market data for omisego
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/nunet.csv
INFO: Loaded data for ethena with 601 rows

Loading assets:  86%|████████▌ | 189/220 [00:22<00:11,  2.64it/s]

INFO: Successfully loaded data for omisego with 3053 rows.
INFO: Added market data for fetch-ai
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/bertram-the-pomeranian.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/baby-doge-coin.csv
INFO: Loaded data for omisego with 3053 rows
INFO: Added market data for nunet

Loading assets:  86%|████████▋ | 190/220 [00:22<00:09,  3.00it/s]

INFO: Successfully loaded data for nunet with 1457 rows.
INFO: Added market data for bertram-the-pomeranian
INFO: Successfully loaded data for fetch-ai with 2461 rows.
INFO: Added market data for baby-doge-coin
INFO: Successfully loaded data for baby-doge-coin with 1629 rows.
INFO: Loaded data for nunet with 1457 rows
INFO: Successfully loaded data for bertram-the-pomeranian with 377 rows.

Loading assets:  87%|████████▋ | 191/220 [00:23<00:08,  3.49it/s]

INFO: Loaded data for fetch-ai with 2461 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/liquity_candles.csv
INFO: Loaded data for baby-doge-coin with 1629 rows
INFO: Loaded data for bertram-the-pomeranian with 377 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/liquity.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/thorchain_candles.csv
INFO: Added market data for liquity
INFO: Successfully loaded data for liquity with 1694 rows.
INFO: Loaded data for liquity with 1694 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/thorchain.csv
INFO: Added market data for thorchain
INFO: Successfully loaded data for thorchain with 2319 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/lido-dao_candles.csv
INFO: Loaded data for thorchain with 2319 rows

Loading assets:  89%|████████▉ | 196/220 [00:23<00:02,  8.07it/s]

INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/litecoin_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/fartcoin_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/lido-dao.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/siren-2_candles.csv
INFO: Added market data for lido-dao
INFO: Successfully loaded data for lido-dao with 1784 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/fartcoin.csv
INFO: Loaded data for lido-dao with 1784 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/litecoin.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/acala_candles.csv
INFO: Added market data for fartcoin
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/siren-2.csv
INFO: Successfully loaded data for fartcoin with 400 rows.
INFO: Loaded data for fartcoin with 400 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/book-of-meme_candles.csv

Loading assets:  90%|█████████ | 198/220 [00:23<00:03,  6.31it/s]

INFO: Added market data for siren-2
INFO: Added market data for litecoin
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/jupiter-exchange-solana_candles.csv
INFO: Successfully loaded data for siren-2 with 278 rows.
INFO: Successfully loaded data for litecoin with 4593 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/acala.csv
INFO: Loaded data for siren-2 with 278 rows
INFO: Loaded data for litecoin with 4593 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/book-of-meme.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/jupiter-exchange-solana.csv
INFO: Added market data for acala
INFO: Successfully loaded data for acala with 1399 rows.
INFO: Loaded data for acala with 1399 rows
INFO: Added market data for jupiter-exchange-solana
INFO: Added market data for book-of-meme
INFO: Successfully loaded data for jupiter-exchange-solana with 663 rows.
INFO: Successfully loaded data for book-of-meme with 620 rows.
INFO: Loaded data for jupiter-exchange-solana with 663 rows
INFO: Loaded data for book-of-meme with 620 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/spell-token_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/spell-token.csv
INFO: Added market data for spell-token
INFO: Successfully loaded data for spell-token with 1641 rows.
INFO: Loaded data for spell-token with 1641 rows

Loading assets:  93%|█████████▎| 204/220 [00:23<00:01, 11.76it/s]

INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/useless-3_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/useless-3.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/new-xai-gork_candles.csv
INFO: Added market data for useless-3
INFO: Successfully loaded data for useless-3 with 197 rows.
INFO: Loaded data for useless-3 with 197 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/zebec-network_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/new-xai-gork.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/aerodrome-finance_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/kryptonite_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/ethereum_candles.csv
INFO: Added market data for new-xai-gork
INFO: Successfully loaded data for new-xai-gork with 206 rows.
INFO: Loaded data for new-xai-gork with 206 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/zebec-network.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/aerodrome-finance.csv
INFO: Added market data for zebec-network
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/kryptonite.csv
INFO: Successfully loaded data for zebec-network with 588 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/ethereum.csv
INFO: Added market data for aerodrome-finance
INFO: Loaded data for zebec-network with 588 rows
INFO: Added market data for kryptonite

Loading assets:  94%|█████████▍| 207/220 [00:24<00:01,  9.85it/s]

INFO: Successfully loaded data for aerodrome-finance with 801 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/tribe-2_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/serum_candles.csv
INFO: Successfully loaded data for kryptonite with 833 rows.
INFO: Loaded data for aerodrome-finance with 801 rows
INFO: Added market data for ethereum
INFO: Loaded data for kryptonite with 833 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/conic-finance_candles.csv
INFO: Successfully loaded data for ethereum with 3762 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/tribe-2.csv
INFO: Loaded data for ethereum with 3762 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/serum.csv
INFO: Added market data for tribe-2
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/conic-finance.csv
INFO: Successfully loaded data for tribe-2 with 1696 rows.
INFO: Added market data for serum
INFO: Loaded data for tribe-2 with 1696 rows
INFO: Successfully loaded data for serum with 1931 rows.
INFO: Loaded data for serum with 1931 rows
INFO: Added market data for conic-finance
INFO: Successfully loaded data for conic-finance with 1084 rows.
INFO: Loaded data for conic-finance with 1084 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/shiba-inu_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/popcat_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/shiba-inu.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/kujira_candles.csv
INFO: Added market data for shiba-inu
INFO: Successfully loaded data for shiba-inu with 1927 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/zksync_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/compound-governance-token_candles.csv
INFO: Loaded data for shiba-inu with 1927 rows

Loading assets:  97%|█████████▋| 214/220 [00:24<00:00, 13.52it/s]

INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/popcat.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/kujira.csv
INFO: Added market data for popcat
INFO: Successfully loaded data for popcat with 706 rows.
INFO: Loaded data for popcat with 706 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/ondo-finance_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/quant-network_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/zksync.csv
INFO: Added market data for kujira
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/compound-governance-token.csv
INFO: Successfully loaded data for kujira with 1459 rows.
INFO: Loaded data for kujira with 1459 rows
INFO: Added market data for zksync
INFO: Added market data for compound-governance-token
INFO: Successfully loaded data for zksync with 524 rows.
INFO: Successfully loaded data for compound-governance-token with 1987 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/ondo-finance.csv
INFO: Loaded data for zksync with 524 rows

Loading assets:  99%|█████████▊| 217/220 [00:24<00:00, 14.84it/s]

INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/quant-network.csv
INFO: Loaded data for compound-governance-token with 1987 rows
INFO: Added market data for ondo-finance
INFO: Successfully loaded data for ondo-finance with 676 rows.
INFO: Added market data for quant-network
INFO: Loaded data for ondo-finance with 676 rows
INFO: Successfully loaded data for quant-network with 2705 rows.
INFO: Loaded data for quant-network with 2705 rows

Loading assets: 100%|██████████| 220/220 [00:24<00:00,  8.91it/s]

INFO: Loaded data for 220 out of 220 assets

Loading assets: 100%|██████████| 220/220 [00:00<00:00, 383678.54it/s]

{'fetch-ai': AssetData(asset_id='fetch-ai', price_data_length=2461, signals=[], backtests=[]),
 'harrypotterobamasonic10in': AssetData(asset_id='harrypotterobamasonic10in', price_data_length=924, signals=[], backtests=[]),
 'quant-network': AssetData(asset_id='quant-network', price_data_length=2705, signals=[], backtests=[]),
 'gains-network': AssetData(asset_id='gains-network', price_data_length=1483, signals=[], backtests=[]),
 'floki': AssetData(asset_id='floki', price_data_length=1610, signals=[], backtests=[]),
 'turbo': AssetData(asset_id='turbo', price_data_length=935, signals=[], backtests=[]),
 'anzen-finance': AssetData(asset_id='anzen-finance', price_data_length=350, signals=[], backtests=[]),
 'equilibria-finance': AssetData(asset_id='equilibria-finance', price_data_length=901, signals=[], backtests=[]),
 'dusk-network': AssetData(asset_id='dusk-network', price_data_length=2333, signals=[], backtests=[]),
 'book-of-meme': AssetData(asset_id='book-of-meme', price_data_length=620, signals=[], backtests=[]),
 'snek': AssetData(asset_id='snek', price_data_length=917, signals=[], backtests=[]),
 'kaspa': AssetData(asset_id='kaspa', price_data_length=1279, signals=[], backtests=[]),
 'near': AssetData(asset_id='near', price_data_length=1867, signals=[], backtests=[]),
 'bonk': AssetData(asset_id='bonk', price_data_length=1061, signals=[], backtests=[]),
 'new-xai-gork': AssetData(asset_id='new-xai-gork', price_data_length=206, signals=[], backtests=[]),
 'omisego': AssetData(asset_id='omisego', price_data_length=3053, signals=[], backtests=[]),
 'render-token': AssetData(asset_id='render-token', price_data_length=1988, signals=[], backtests=[]),
 'optimism': AssetData(asset_id='optimism', price_data_length=1273, signals=[], backtests=[]),
 'true-usd': AssetData(asset_id='true-usd', price_data_length=2804, signals=[], backtests=[]),
 'lido-dao': AssetData(asset_id='lido-dao', price_data_length=1784, signals=[], backtests=[]),
 'crypto-com-chain': AssetData(asset_id='crypto-com-chain', price_data_length=2519, signals=[], backtests=[]),
 'binancecoin': AssetData(asset_id='binancecoin', price_data_length=2991, signals=[], backtests=[]),
 'secret': AssetData(asset_id='secret', price_data_length=1880, signals=[], backtests=[]),
 'bitcoin': AssetData(asset_id='bitcoin', price_data_length=4593, signals=[], backtests=[]),
 'alpha-finance': AssetData(asset_id='alpha-finance', price_data_length=1871, signals=[], backtests=[]),
 'band-protocol': AssetData(asset_id='band-protocol', price_data_length=2259, signals=[], backtests=[]),
 'mintlayer': AssetData(asset_id='mintlayer', price_data_length=975, signals=[], backtests=[]),
 'decentraland': AssetData(asset_id='decentraland', price_data_length=2949, signals=[], backtests=[]),
 'serum': AssetData(asset_id='serum', price_data_length=1931, signals=[], backtests=[]),
 'axie-infinity': AssetData(asset_id='axie-infinity', price_data_length=1846, signals=[], backtests=[]),
 'guild-of-guardians': AssetData(asset_id='guild-of-guardians', price_data_length=1433, signals=[], backtests=[]),
 'morpho': AssetData(asset_id='morpho', price_data_length=369, signals=[], backtests=[]),
 'gala': AssetData(asset_id='gala', price_data_length=1895, signals=[], backtests=[]),
 'wibx': AssetData(asset_id='wibx', price_data_length=2047, signals=[], backtests=[]),
 'numeraire': AssetData(asset_id='numeraire', price_data_length=3056, signals=[], backtests=[]),
 'ether-fi': AssetData(asset_id='ether-fi', price_data_length=616, signals=[], backtests=[]),
 'aixbt': AssetData(asset_id='aixbt', price_data_length=371, signals=[], backtests=[]),
 'kaito': AssetData(asset_id='kaito', price_data_length=277, signals=[], backtests=[]),
 'mog-coin': AssetData(asset_id='mog-coin', price_data_length=857, signals=[], backtests=[]),
 'hypercycle': AssetData(asset_id='hypercycle', price_data_length=930, signals=[], backtests=[]),
 'spx6900': AssetData(asset_id='spx6900', price_data_length=819, signals=[], backtests=[]),
 'ripple': AssetData(asset_id='ripple', price_data_length=4495, signals=[], backtests=[]),
 'nunet': AssetData(asset_id='nunet', price_data_length=1457, signals=[], backtests=[]),
 'based-brett': AssetData(asset_id='based-brett', price_data_length=634, signals=[], backtests=[]),
 'venice-token': AssetData(asset_id='venice-token', price_data_length=301, signals=[], backtests=[]),
 'spell-token': AssetData(asset_id='spell-token', price_data_length=1641, signals=[], backtests=[]),
 'kyber-network-crystal': AssetData(asset_id='kyber-network-crystal', price_data_length=1677, signals=[], backtests=[]),
 'frax-share': AssetData(asset_id='frax-share', price_data_length=1799, signals=[], backtests=[]),
 'tezos': AssetData(asset_id='tezos', price_data_length=2703, signals=[], backtests=[]),
 'bigcoin-2': AssetData(asset_id='bigcoin-2', price_data_length=222, signals=[], backtests=[]),
 'polymath': AssetData(asset_id='polymath', price_data_length=2845, signals=[], backtests=[]),
 'aethir': AssetData(asset_id='aethir', price_data_length=530, signals=[], backtests=[]),
 'popcat': AssetData(asset_id='popcat', price_data_length=706, signals=[], backtests=[]),
 'tron': AssetData(asset_id='tron', price_data_length=2937, signals=[], backtests=[]),
 'aioz-network': AssetData(asset_id='aioz-network', price_data_length=1696, signals=[], backtests=[]),
 'fwog': AssetData(asset_id='fwog', price_data_length=482, signals=[], backtests=[]),
 'sushi': AssetData(asset_id='sushi', price_data_length=1914, signals=[], backtests=[]),
 'sei-network': AssetData(asset_id='sei-network', price_data_length=832, signals=[], backtests=[]),
 'gmx': AssetData(asset_id='gmx', price_data_length=1533, signals=[], backtests=[]),
 'compound-governance-token': AssetData(asset_id='compound-governance-token', price_data_length=1987, signals=[], backtests=[]),
 'thorchain': AssetData(asset_id='thorchain', price_data_length=2319, signals=[], backtests=[]),
 'goatseus-maximus': AssetData(asset_id='goatseus-maximus', price_data_length=407, signals=[], backtests=[]),
 'avalanche-2': AssetData(asset_id='avalanche-2', price_data_length=1889, signals=[], backtests=[]),
 'smartcash': AssetData(asset_id='smartcash', price_data_length=2979, signals=[], backtests=[]),
 'syrup': AssetData(asset_id='syrup', price_data_length=376, signals=[], backtests=[]),
 'celestia': AssetData(asset_id='celestia', price_data_length=755, signals=[], backtests=[]),
 'dydx': AssetData(asset_id='dydx', price_data_length=1538, signals=[], backtests=[]),
 'internet-computer': AssetData(asset_id='internet-computer', price_data_length=1659, signals=[], backtests=[]),
 'deep': AssetData(asset_id='deep', price_data_length=406, signals=[], backtests=[]),
 'slerf': AssetData(asset_id='slerf', price_data_length=616, signals=[], backtests=[]),
 'conic-finance': AssetData(asset_id='conic-finance', price_data_length=1084, signals=[], backtests=[]),
 'grass': AssetData(asset_id='grass', price_data_length=392, signals=[], backtests=[]),
 'clearpool': AssetData(asset_id='clearpool', price_data_length=1488, signals=[], backtests=[]),
 'yne': AssetData(asset_id='yne', price_data_length=336, signals=[], backtests=[]),
 'raydium': AssetData(asset_id='raydium', price_data_length=1737, signals=[], backtests=[]),
 'mubarak': AssetData(asset_id='mubarak', price_data_length=253, signals=[], backtests=[]),
 'zksync': AssetData(asset_id='zksync', price_data_length=524, signals=[], backtests=[]),
 'kryptonite': AssetData(asset_id='kryptonite', price_data_length=833, signals=[], backtests=[]),
 'tribe-2': AssetData(asset_id='tribe-2', price_data_length=1696, signals=[], backtests=[]),
 'ethervista': AssetData(asset_id='ethervista', price_data_length=449, signals=[], backtests=[]),
 'euler': AssetData(asset_id='euler', price_data_length=1249, signals=[], backtests=[]),
 'zebec-network': AssetData(asset_id='zebec-network', price_data_length=588, signals=[], backtests=[]),
 'curve-dao-token': AssetData(asset_id='curve-dao-token', price_data_length=1928, signals=[], backtests=[]),
 'tokenbot-2': AssetData(asset_id='tokenbot-2', price_data_length=379, signals=[], backtests=[]),
 'usd-coin': AssetData(asset_id='usd-coin', price_data_length=2608, signals=[], backtests=[]),
 'arbitrum': AssetData(asset_id='arbitrum', price_data_length=977, signals=[], backtests=[]),
 'matic-network': AssetData(asset_id='matic-network', price_data_length=2409, signals=[], backtests=[]),
 'havven': AssetData(asset_id='havven', price_data_length=2806, signals=[], backtests=[]),
 'tether': AssetData(asset_id='tether', price_data_length=3925, signals=[], backtests=[]),
 'ronin': AssetData(asset_id='ronin', price_data_length=1397, signals=[], backtests=[]),
 'ethereum': AssetData(asset_id='ethereum', price_data_length=3762, signals=[], backtests=[]),
 'pancakeswap-token': AssetData(asset_id='pancakeswap-token', price_data_length=1882, signals=[], backtests=[]),
 'multibit': AssetData(asset_id='multibit', price_data_length=735, signals=[], backtests=[]),
 'arbdoge-ai': AssetData(asset_id='arbdoge-ai', price_data_length=951, signals=[], backtests=[]),
 'gigachad-2': AssetData(asset_id='gigachad-2', price_data_length=672, signals=[], backtests=[]),
 'botto': AssetData(asset_id='botto', price_data_length=1507, signals=[], backtests=[]),
 'baby-doge-coin': AssetData(asset_id='baby-doge-coin', price_data_length=1629, signals=[], backtests=[]),
 'zeus-network': AssetData(asset_id='zeus-network', price_data_length=598, signals=[], backtests=[]),
 'dogecoin': AssetData(asset_id='dogecoin', price_data_length=4362, signals=[], backtests=[]),
 'vela-token': AssetData(asset_id='vela-token', price_data_length=1023, signals=[], backtests=[]),
 'hedera-hashgraph': AssetData(asset_id='hedera-hashgraph', price_data_length=2260, signals=[], backtests=[]),
 'moonwell-artemis': AssetData(asset_id='moonwell-artemis', price_data_length=1250, signals=[], backtests=[]),
 'lisk': AssetData(asset_id='lisk', price_data_length=3519, signals=[], backtests=[]),
 'instadapp': AssetData(asset_id='instadapp', price_data_length=1622, signals=[], backtests=[]),
 'dash': AssetData(asset_id='dash', price_data_length=4301, signals=[], backtests=[]),
 'litecoin': AssetData(asset_id='litecoin', price_data_length=4593, signals=[], backtests=[]),
 'rari-governance-token': AssetData(asset_id='rari-governance-token', price_data_length=1868, signals=[], backtests=[]),
 'balancer': AssetData(asset_id='balancer', price_data_length=1980, signals=[], backtests=[]),
 'lagrange': AssetData(asset_id='lagrange', price_data_length=173, signals=[], backtests=[]),
 'uniswap': AssetData(asset_id='uniswap', price_data_length=1894, signals=[], backtests=[]),
 'orbit-3': AssetData(asset_id='orbit-3', price_data_length=351, signals=[], backtests=[]),
 'plume': AssetData(asset_id='plume', price_data_length=307, signals=[], backtests=[]),
 'audius': AssetData(asset_id='audius', price_data_length=1858, signals=[], backtests=[]),
 'akash-network': AssetData(asset_id='akash-network', price_data_length=1865, signals=[], backtests=[]),
 'griffain': AssetData(asset_id='griffain', price_data_length=353, signals=[], backtests=[]),
 'helium': AssetData(asset_id='helium', price_data_length=2047, signals=[], backtests=[]),
 'chainlink': AssetData(asset_id='chainlink', price_data_length=2937, signals=[], backtests=[]),
 'bubblemaps': AssetData(asset_id='bubblemaps', price_data_length=258, signals=[], backtests=[]),
 'kujira': AssetData(asset_id='kujira', price_data_length=1459, signals=[], backtests=[]),
 'bittensor': AssetData(asset_id='bittensor', price_data_length=997, signals=[], backtests=[]),
 'wrapped-nxm': AssetData(asset_id='wrapped-nxm', price_data_length=1946, signals=[], backtests=[]),
 'stellar': AssetData(asset_id='stellar', price_data_length=4128, signals=[], backtests=[]),
 'terra-luna-2': AssetData(asset_id='terra-luna-2', price_data_length=1276, signals=[], backtests=[]),
 'bitcoin-cash': AssetData(asset_id='bitcoin-cash', price_data_length=3036, signals=[], backtests=[]),
 'y': AssetData(asset_id='y', price_data_length=602, signals=[], backtests=[]),
 'heyanon': AssetData(asset_id='heyanon', price_data_length=332, signals=[], backtests=[]),
 'story-2': AssetData(asset_id='story-2', price_data_length=284, signals=[], backtests=[]),
 'pendle': AssetData(asset_id='pendle', price_data_length=1671, signals=[], backtests=[]),
 'monero': AssetData(asset_id='monero', price_data_length=4205, signals=[], backtests=[]),
 'neiro-3': AssetData(asset_id='neiro-3', price_data_length=480, signals=[], backtests=[]),
 'genesysgo-shadow': AssetData(asset_id='genesysgo-shadow', price_data_length=1419, signals=[], backtests=[]),
 'pepe': AssetData(asset_id='pepe', price_data_length=951, signals=[], backtests=[]),
 'ondo-finance': AssetData(asset_id='ondo-finance', price_data_length=676, signals=[], backtests=[]),
 'cosmos': AssetData(asset_id='cosmos', price_data_length=2467, signals=[], backtests=[]),
 'star-atlas-dao': AssetData(asset_id='star-atlas-dao', price_data_length=1544, signals=[], backtests=[]),
 'solana': AssetData(asset_id='solana', price_data_length=2054, signals=[], backtests=[]),
 'illuvium': AssetData(asset_id='illuvium', price_data_length=1699, signals=[], backtests=[]),
 'the-sandbox': AssetData(asset_id='the-sandbox', price_data_length=1928, signals=[], backtests=[]),
 'dog-go-to-the-moon-rune': AssetData(asset_id='dog-go-to-the-moon-rune', price_data_length=577, signals=[], backtests=[]),
 'ava-ai': AssetData(asset_id='ava-ai', price_data_length=368, signals=[], backtests=[]),
 'radiant-capital': AssetData(asset_id='radiant-capital', price_data_length=1217, signals=[], backtests=[]),
 'axelar': AssetData(asset_id='axelar', price_data_length=1154, signals=[], backtests=[]),
 'injective-protocol': AssetData(asset_id='injective-protocol', price_data_length=1860, signals=[], backtests=[]),
 'aerodrome-finance': AssetData(asset_id='aerodrome-finance', price_data_length=801, signals=[], backtests=[]),
 'echelon-prime': AssetData(asset_id='echelon-prime', price_data_length=998, signals=[], backtests=[]),
 'eigenlayer': AssetData(asset_id='eigenlayer', price_data_length=419, signals=[], backtests=[]),
 'badger-dao': AssetData(asset_id='badger-dao', price_data_length=1816, signals=[], backtests=[]),
 'kekius-maximus': AssetData(asset_id='kekius-maximus', price_data_length=344, signals=[], backtests=[]),
 'fantom': AssetData(asset_id='fantom', price_data_length=2583, signals=[], backtests=[]),
 'chill-guy': AssetData(asset_id='chill-guy', price_data_length=371, signals=[], backtests=[]),
 'sonic-3': AssetData(asset_id='sonic-3', price_data_length=324, signals=[], backtests=[]),
 'coredaoorg': AssetData(asset_id='coredaoorg', price_data_length=1020, signals=[], backtests=[]),
 'mantra-dao': AssetData(asset_id='mantra-dao', price_data_length=1924, signals=[], backtests=[]),
 'grok-2': AssetData(asset_id='grok-2', price_data_length=748, signals=[], backtests=[]),
 'bio-protocol': AssetData(asset_id='bio-protocol', price_data_length=324, signals=[], backtests=[]),
 'cardano': AssetData(asset_id='cardano', price_data_length=2959, signals=[], backtests=[]),
 'shiba-inu': AssetData(asset_id='shiba-inu', price_data_length=1927, signals=[], backtests=[]),
 'polkadot': AssetData(asset_id='polkadot', price_data_length=1923, signals=[], backtests=[]),
 'pudgy-penguins': AssetData(asset_id='pudgy-penguins', price_data_length=342, signals=[], backtests=[]),
 'blockstack': AssetData(asset_id='blockstack', price_data_length=2223, signals=[], backtests=[]),
 'prisma-governance-token': AssetData(asset_id='prisma-governance-token', price_data_length=753, signals=[], backtests=[]),
 'eos': AssetData(asset_id='eos', price_data_length=3060, signals=[], backtests=[]),
 'sturdy': AssetData(asset_id='sturdy', price_data_length=641, signals=[], backtests=[]),
 'flow': AssetData(asset_id='flow', price_data_length=1762, signals=[], backtests=[]),
 'siren-2': AssetData(asset_id='siren-2', price_data_length=278, signals=[], backtests=[]),
 'worldcoin-wld': AssetData(asset_id='worldcoin-wld', price_data_length=854, signals=[], backtests=[]),
 'acala': AssetData(asset_id='acala', price_data_length=1399, signals=[], backtests=[]),
 'liquity': AssetData(asset_id='liquity', price_data_length=1694, signals=[], backtests=[]),
 'kamino': AssetData(asset_id='kamino', price_data_length=573, signals=[], backtests=[]),
 'beam-2': AssetData(asset_id='beam-2', price_data_length=760, signals=[], backtests=[]),
 'yield-guild-games': AssetData(asset_id='yield-guild-games', price_data_length=1580, signals=[], backtests=[]),
 'prometeus': AssetData(asset_id='prometeus', price_data_length=2341, signals=[], backtests=[]),
 'solayer': AssetData(asset_id='solayer', price_data_length=286, signals=[], backtests=[]),
 'jasmycoin': AssetData(asset_id='jasmycoin', price_data_length=1644, signals=[], backtests=[]),
 'arweave': AssetData(asset_id='arweave', price_data_length=2216, signals=[], backtests=[]),
 'verasity': AssetData(asset_id='verasity', price_data_length=1738, signals=[], backtests=[]),
 'fartcoin': AssetData(asset_id='fartcoin', price_data_length=400, signals=[], backtests=[]),
 'official-trump': AssetData(asset_id='official-trump', price_data_length=310, signals=[], backtests=[]),
 'virtual-protocol': AssetData(asset_id='virtual-protocol', price_data_length=697, signals=[], backtests=[]),
 'cookie': AssetData(asset_id='cookie', price_data_length=529, signals=[], backtests=[]),
 'my-neighbor-alice': AssetData(asset_id='my-neighbor-alice', price_data_length=1715, signals=[], backtests=[]),
 'alchemy-pay': AssetData(asset_id='alchemy-pay', price_data_length=1903, signals=[], backtests=[]),
 'dogwifcoin': AssetData(asset_id='dogwifcoin', price_data_length=712, signals=[], backtests=[]),
 'constitutiondao': AssetData(asset_id='constitutiondao', price_data_length=1466, signals=[], backtests=[]),
 'apu-s-club': AssetData(asset_id='apu-s-club', price_data_length=621, signals=[], backtests=[]),
 'ai16z': AssetData(asset_id='ai16z', price_data_length=393, signals=[], backtests=[]),
 'jupiter-exchange-solana': AssetData(asset_id='jupiter-exchange-solana', price_data_length=663, signals=[], backtests=[]),
 'swarm': AssetData(asset_id='swarm', price_data_length=3497, signals=[], backtests=[]),
 'pump-fun': AssetData(asset_id='pump-fun', price_data_length=132, signals=[], backtests=[]),
 'dodo': AssetData(asset_id='dodo', price_data_length=1881, signals=[], backtests=[]),
 'chex-token': AssetData(asset_id='chex-token', price_data_length=2119, signals=[], backtests=[]),
 'ethena': AssetData(asset_id='ethena', price_data_length=601, signals=[], backtests=[]),
 'immutable-x': AssetData(asset_id='immutable-x', price_data_length=1480, signals=[], backtests=[]),
 'paal-ai': AssetData(asset_id='paal-ai', price_data_length=882, signals=[], backtests=[]),
 'aave': AssetData(asset_id='aave', price_data_length=1878, signals=[], backtests=[]),
 'perpetual-protocol': AssetData(asset_id='perpetual-protocol', price_data_length=1902, signals=[], backtests=[]),
 'the-open-network': AssetData(asset_id='the-open-network', price_data_length=1550, signals=[], backtests=[]),
 'ethereum-classic': AssetData(asset_id='ethereum-classic', price_data_length=3410, signals=[], backtests=[]),
 'arkham': AssetData(asset_id='arkham', price_data_length=860, signals=[], backtests=[]),
 'velvet': AssetData(asset_id='velvet', price_data_length=136, signals=[], backtests=[]),
 'yearn-finance': AssetData(asset_id='yearn-finance', price_data_length=1955, signals=[], backtests=[]),
 'useless-3': AssetData(asset_id='useless-3', price_data_length=197, signals=[], backtests=[]),
 'evan-2': AssetData(asset_id='evan-2', price_data_length=367, signals=[], backtests=[]),
 'maker': AssetData(asset_id='maker', price_data_length=2896, signals=[], backtests=[]),
 'metacade': AssetData(asset_id='metacade', price_data_length=958, signals=[], backtests=[]),

In [2]:
# Register specific signals by their exact names
signals = analyzer.register_signals_parallel(
    asset_ids=assets, 
    calculate_values=True,
    specific_signals=[
                      "DonchianEnsembleUSD", "DonchianEnsembleBTC",
                      "RSI_Bullish_USD", "RSI_Bullish_BTC",
                      "TrendMomentumUSD", "TrendMomentumBTC"]
)
signals

INFO: Registering signals in parallel for 220 assets...
INFO: Converted asset_ids to list with 220 items
INFO: Using 6 specific signals provided by user
INFO: Using 7 workers for parallel signal registration
INFO: Processing asset group 1/44 with 5 assets
INFO: Starting signal registration for cosmos
INFO: Starting signal registration for genesysgo-shadow
INFO: Registering 6 new signals for cosmos
INFO: Starting signal registration for tezos
INFO: Starting signal registration for the-sandbox

Registering signals group 1/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 6 new signals for genesysgo-shadow
INFO: Starting signal registration for goatseus-maximus
INFO: Registering 6 new signals for tezos
INFO: Registering 6 new signals for the-sandbox
INFO: Registering 6 new signals for goatseus-maximus
INFO: Adapted windows for data length 407: [5, 11, 16, 33, 50, 84]
INFO: Asset goatseus-maximus: Using 6 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on goatseus-maximus: 407 points
INFO: Asset genesysgo-shadow: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleBTC on goatseus-maximus: 407 points
INFO: Calculated initial values for DonchianEnsembleUSD on genesysgo-shadow: 1419 points
INFO: Calculated initial values for RSI_Bullish_USD on goatseus-maximus: 407 points
INFO: Calculated initial values for RSI_Bullish_BTC on goatseus-maximus: 407 points
INFO: Calculated initial values for TrendMomentumUSD on goatseus-maximus: 407 points
INFO: Asset cosmos: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on cosmos: 2467 points
INFO: Calculated initial values for TrendMomentumBTC on goatseus-maximus: 407 points
INFO: Asset the-sandbox: Using 9 windows with threshold 3
INFO: Completed signal registration for goatseus-maximus in 5.74 seconds

Registering signals group 1/44:  20%|██        | 1/5 [00:06<00:24,  6.14s/it]

INFO: Calculated initial values for DonchianEnsembleUSD on the-sandbox: 1928 points
INFO: Asset tezos: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on tezos: 2703 points
INFO: Calculated initial values for DonchianEnsembleBTC on genesysgo-shadow: 1419 points
INFO: Calculated initial values for RSI_Bullish_USD on genesysgo-shadow: 1419 points
INFO: Calculated initial values for RSI_Bullish_BTC on genesysgo-shadow: 1419 points
INFO: Calculated initial values for DonchianEnsembleBTC on the-sandbox: 1928 points
INFO: Calculated initial values for TrendMomentumUSD on genesysgo-shadow: 1419 points
INFO: Calculated initial values for DonchianEnsembleBTC on cosmos: 2467 points
INFO: Calculated initial values for TrendMomentumBTC on genesysgo-shadow: 1419 points
INFO: Completed signal registration for genesysgo-shadow in 18.80 seconds

Registering signals group 1/44:  40%|████      | 2/5 [00:18<00:29,  9.96s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on tezos: 2703 points
INFO: Calculated initial values for RSI_Bullish_USD on the-sandbox: 1928 points
INFO: Calculated initial values for RSI_Bullish_BTC on the-sandbox: 1928 points
INFO: Calculated initial values for TrendMomentumUSD on the-sandbox: 1928 points
INFO: Calculated initial values for RSI_Bullish_USD on cosmos: 2467 points
INFO: Calculated initial values for TrendMomentumBTC on the-sandbox: 1928 points
INFO: Completed signal registration for the-sandbox in 22.79 seconds

Registering signals group 1/44:  60%|██████    | 3/5 [00:22<00:14,  7.28s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on cosmos: 2467 points
INFO: Calculated initial values for TrendMomentumUSD on cosmos: 2467 points
INFO: Calculated initial values for TrendMomentumBTC on cosmos: 2467 points
INFO: Calculated initial values for RSI_Bullish_USD on tezos: 2703 points
INFO: Completed signal registration for cosmos in 24.12 seconds

Registering signals group 1/44:  80%|████████  | 4/5 [00:23<00:04,  4.83s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on tezos: 2703 points
INFO: Calculated initial values for TrendMomentumUSD on tezos: 2703 points
INFO: Calculated initial values for TrendMomentumBTC on tezos: 2703 points
INFO: Completed signal registration for tezos in 25.11 seconds

Registering signals group 1/44: 100%|██████████| 5/5 [00:24<00:00,  5.00s/it]

INFO: Processing asset group 2/44 with 5 assets
INFO: Starting signal registration for story-2
INFO: Starting signal registration for mubarak

INFO: Registering 6 new signals for mubarak
INFO: Starting signal registration for near

Registering signals group 2/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 6 new signals for story-2
INFO: Starting signal registration for alpha-finance
INFO: Starting signal registration for true-usd
INFO: Adapted windows for data length 253: [3, 7, 10, 21, 31, 52]
INFO: Registering 6 new signals for near
INFO: Adapted windows for data length 284: [3, 7, 11, 23, 35, 59]
INFO: Registering 6 new signals for alpha-finance
INFO: Registering 6 new signals for true-usd
INFO: Asset mubarak: Using 6 windows with threshold 3
INFO: Asset story-2: Using 6 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on mubarak: 253 points
INFO: Calculated initial values for DonchianEnsembleUSD on story-2: 284 points
INFO: Calculated initial values for DonchianEnsembleBTC on mubarak: 253 points
INFO: Calculated initial values for DonchianEnsembleBTC on story-2: 284 points
INFO: Calculated initial values for RSI_Bullish_USD on mubarak: 253 points
INFO: Calculated initial values for RSI_Bullish_BTC on mubarak: 253 points
INFO: Calculated initial values for TrendMomentumUSD on mubarak: 253 points
INFO: Calculated initial values for RSI_Bullish_USD on story-2: 284 points
INFO: Calculated initial values for TrendMomentumBTC on mubarak: 253 points
INFO: Calculated initial values for RSI_Bullish_BTC on story-2: 284 points
INFO: Completed signal registration for mubarak in 3.93 seconds

Registering signals group 2/44:  20%|██        | 1/5 [00:04<00:17,  4.28s/it]

INFO: Calculated initial values for TrendMomentumUSD on story-2: 284 points
INFO: Calculated initial values for TrendMomentumBTC on story-2: 284 points
INFO: Asset near: Using 9 windows with threshold 3
INFO: Completed signal registration for story-2 in 4.73 seconds

Registering signals group 2/44:  40%|████      | 2/5 [00:04<00:06,  2.09s/it]

INFO: Asset alpha-finance: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on near: 1867 points
INFO: Calculated initial values for DonchianEnsembleUSD on alpha-finance: 1871 points
INFO: Asset true-usd: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on true-usd: 2804 points
INFO: Calculated initial values for DonchianEnsembleBTC on near: 1867 points
INFO: Calculated initial values for DonchianEnsembleBTC on alpha-finance: 1871 points
INFO: Calculated initial values for RSI_Bullish_USD on near: 1867 points
INFO: Calculated initial values for RSI_Bullish_USD on alpha-finance: 1871 points
INFO: Calculated initial values for RSI_Bullish_BTC on near: 1867 points
INFO: Calculated initial values for RSI_Bullish_BTC on alpha-finance: 1871 points
INFO: Calculated initial values for DonchianEnsembleBTC on true-usd: 2804 points
INFO: Calculated initial values for TrendMomentumUSD on near: 1867 points
INFO: Calculated initial values for TrendMomentumUSD on alpha-finance: 1871 points
INFO: Calculated initial values for TrendMomentumBTC on near: 1867 points
INFO: Calculated initial values for TrendMomentumBTC on alpha-finance: 1871 points
INFO: Completed signal registration for near in 16.79 seconds
INFO: Completed signal registration for alpha-finance in 16.82 seconds

Registering signals group 2/44:  60%|██████    | 3/5 [00:16<00:13,  6.64s/it]

INFO: Calculated initial values for RSI_Bullish_USD on true-usd: 2804 points
INFO: Calculated initial values for RSI_Bullish_BTC on true-usd: 2804 points
INFO: Calculated initial values for TrendMomentumUSD on true-usd: 2804 points
INFO: Calculated initial values for TrendMomentumBTC on true-usd: 2804 points
INFO: Completed signal registration for true-usd in 18.66 seconds

Registering signals group 2/44: 100%|██████████| 5/5 [00:18<00:00,  3.73s/it]

INFO: Processing asset group 3/44 with 5 assets
INFO: Starting signal registration for spx6900
INFO: Registering 6 new signals for spx6900

INFO: Starting signal registration for sei-network
INFO: Starting signal registration for clearpool

Registering signals group 3/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for matic-network
INFO: Starting signal registration for crypto-com-chain
INFO: Registering 6 new signals for sei-network
INFO: Registering 6 new signals for clearpool
INFO: Registering 6 new signals for matic-network
INFO: Registering 6 new signals for crypto-com-chain
INFO: Asset spx6900: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on spx6900: 819 points
INFO: Asset sei-network: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on sei-network: 832 points
INFO: Asset clearpool: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on clearpool: 1488 points
INFO: Calculated initial values for DonchianEnsembleBTC on spx6900: 819 points
INFO: Calculated initial values for DonchianEnsembleBTC on sei-network: 832 points
INFO: Asset matic-network: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on matic-network: 2409 points
INFO: Asset crypto-com-chain: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on crypto-com-chain: 2519 points
INFO: Calculated initial values for RSI_Bullish_USD on spx6900: 819 points
INFO: Calculated initial values for RSI_Bullish_USD on sei-network: 832 points
INFO: Calculated initial values for RSI_Bullish_BTC on spx6900: 819 points
INFO: Calculated initial values for RSI_Bullish_BTC on sei-network: 832 points
INFO: Calculated initial values for TrendMomentumUSD on spx6900: 819 points
INFO: Calculated initial values for TrendMomentumUSD on sei-network: 832 points
INFO: Calculated initial values for TrendMomentumBTC on spx6900: 819 points
INFO: Calculated initial values for TrendMomentumBTC on sei-network: 832 points
INFO: Completed signal registration for spx6900 in 10.16 seconds

Registering signals group 3/44:  20%|██        | 1/5 [00:10<00:40, 10.20s/it]

INFO: Completed signal registration for sei-network in 10.34 seconds
INFO: Calculated initial values for DonchianEnsembleBTC on clearpool: 1488 points
INFO: Calculated initial values for RSI_Bullish_USD on clearpool: 1488 points
INFO: Calculated initial values for RSI_Bullish_BTC on clearpool: 1488 points
INFO: Calculated initial values for TrendMomentumUSD on clearpool: 1488 points
INFO: Calculated initial values for TrendMomentumBTC on clearpool: 1488 points
INFO: Calculated initial values for DonchianEnsembleBTC on matic-network: 2409 points
INFO: Completed signal registration for clearpool in 14.71 seconds

Registering signals group 3/44:  60%|██████    | 3/5 [00:14<00:08,  4.36s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on crypto-com-chain: 2519 points
ERROR: Error calculating RSI Bullish signal for matic-network: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
INFO: Calculated initial values for RSI_Bullish_USD on matic-network: 2409 points
INFO: Calculated initial values for RSI_Bullish_USD on crypto-com-chain: 2519 points
INFO: Calculated initial values for RSI_Bullish_BTC on crypto-com-chain: 2519 points
INFO: Calculated initial values for RSI_Bullish_BTC on matic-network: 2409 points
INFO: Calculated initial values for TrendMomentumUSD on crypto-com-chain: 2519 points
INFO: Calculated initial values for TrendMomentumBTC on crypto-com-chain: 2519 points
INFO: Completed signal registration for crypto-com-chain in 18.75 seconds

Registering signals group 3/44:  80%|████████  | 4/5 [00:18<00:04,  4.28s/it]

ERROR: Error calculating Trend Momentum signal for matic-network: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
INFO: Calculated initial values for TrendMomentumUSD on matic-network: 2409 points
INFO: Calculated initial values for TrendMomentumBTC on matic-network: 2409 points
INFO: Completed signal registration for matic-network in 19.20 seconds

Registering signals group 3/44: 100%|██████████| 5/5 [00:19<00:00,  3.87s/it]

INFO: Processing asset group 4/44 with 5 assets
INFO: Starting signal registration for akash-network
INFO: Starting signal registration for fwog

INFO: Starting signal registration for ava-ai

Registering signals group 4/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for kekius-maximus
INFO: Registering 6 new signals for akash-network
INFO: Starting signal registration for cookie
INFO: Registering 6 new signals for fwog
INFO: Registering 6 new signals for ava-ai
INFO: Registering 6 new signals for kekius-maximus
INFO: Registering 6 new signals for cookie
INFO: Adapted windows for data length 482: [3, 6, 13, 20, 40, 60, 100]
INFO: Adapted windows for data length 368: [5, 10, 15, 30, 46, 76]
INFO: Adapted windows for data length 344: [4, 9, 14, 28, 43, 71]
INFO: Adapted windows for data length 529: [3, 7, 14, 22, 44, 66, 110]
INFO: Asset ava-ai: Using 6 windows with threshold 3
INFO: Asset fwog: Using 7 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on ava-ai: 368 points
INFO: Asset kekius-maximus: Using 6 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on fwog: 482 points
INFO: Asset cookie: Using 7 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on kekius-maximus: 344 points
INFO: Calculated initial values for DonchianEnsembleUSD on cookie: 529 points
INFO: Calculated initial values for DonchianEnsembleBTC on ava-ai: 368 points
INFO: Asset akash-network: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on akash-network: 1865 points
INFO: Calculated initial values for DonchianEnsembleBTC on kekius-maximus: 344 points
INFO: Calculated initial values for RSI_Bullish_USD on ava-ai: 368 points
INFO: Calculated initial values for DonchianEnsembleBTC on fwog: 482 points
INFO: Calculated initial values for RSI_Bullish_BTC on ava-ai: 368 points
INFO: Calculated initial values for RSI_Bullish_USD on kekius-maximus: 344 points
INFO: Calculated initial values for DonchianEnsembleBTC on cookie: 529 points
INFO: Calculated initial values for TrendMomentumUSD on ava-ai: 368 points
INFO: Calculated initial values for RSI_Bullish_BTC on kekius-maximus: 344 points
INFO: Calculated initial values for TrendMomentumBTC on ava-ai: 368 points
INFO: Calculated initial values for RSI_Bullish_USD on fwog: 482 points
INFO: Calculated initial values for TrendMomentumUSD on kekius-maximus: 344 points
INFO: Completed signal registration for ava-ai in 5.14 seconds

Registering signals group 4/44:  20%|██        | 1/5 [00:05<00:21,  5.48s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on fwog: 482 points
INFO: Calculated initial values for TrendMomentumBTC on kekius-maximus: 344 points
INFO: Calculated initial values for RSI_Bullish_USD on cookie: 529 points
INFO: Calculated initial values for TrendMomentumUSD on fwog: 482 points
INFO: Completed signal registration for kekius-maximus in 5.73 seconds

Registering signals group 4/44:  40%|████      | 2/5 [00:05<00:07,  2.55s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on cookie: 529 points
INFO: Calculated initial values for TrendMomentumBTC on fwog: 482 points
INFO: Completed signal registration for fwog in 6.18 seconds
INFO: Calculated initial values for TrendMomentumUSD on cookie: 529 points

Registering signals group 4/44:  60%|██████    | 3/5 [00:06<00:03,  1.52s/it]

INFO: Calculated initial values for TrendMomentumBTC on cookie: 529 points
INFO: Completed signal registration for cookie in 6.51 seconds

Registering signals group 4/44:  80%|████████  | 4/5 [00:06<00:01,  1.03s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on akash-network: 1865 points
INFO: Calculated initial values for RSI_Bullish_USD on akash-network: 1865 points
INFO: Calculated initial values for RSI_Bullish_BTC on akash-network: 1865 points
INFO: Calculated initial values for TrendMomentumUSD on akash-network: 1865 points
INFO: Calculated initial values for TrendMomentumBTC on akash-network: 1865 points
INFO: Completed signal registration for akash-network in 8.49 seconds

Registering signals group 4/44: 100%|██████████| 5/5 [00:08<00:00,  1.70s/it]

INFO: Processing asset group 5/44 with 5 assets
INFO: Starting signal registration for ether-fi
INFO: Starting signal registration for frax-share

INFO: Starting signal registration for cardano

Registering signals group 5/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for lisk
INFO: Registering 6 new signals for ether-fi
INFO: Starting signal registration for slerf
INFO: Registering 6 new signals for frax-share
INFO: Registering 6 new signals for cardano
INFO: Registering 6 new signals for lisk
INFO: Adapted windows for data length 616: [4, 8, 17, 25, 51, 77, 128]
INFO: Registering 6 new signals for slerf
INFO: Asset ether-fi: Using 7 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on ether-fi: 616 points
INFO: Asset slerf: Using 7 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on slerf: 616 points
INFO: Asset frax-share: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on frax-share: 1799 points
INFO: Calculated initial values for DonchianEnsembleBTC on ether-fi: 616 points
INFO: Calculated initial values for DonchianEnsembleBTC on slerf: 616 points
INFO: Calculated initial values for RSI_Bullish_USD on ether-fi: 616 points
INFO: Calculated initial values for RSI_Bullish_USD on slerf: 616 points
INFO: Calculated initial values for RSI_Bullish_BTC on ether-fi: 616 points
INFO: Calculated initial values for RSI_Bullish_BTC on slerf: 616 points
INFO: Asset cardano: Using 9 windows with threshold 3
INFO: Calculated initial values for TrendMomentumUSD on ether-fi: 616 points
INFO: Calculated initial values for DonchianEnsembleUSD on cardano: 2959 points
INFO: Calculated initial values for TrendMomentumUSD on slerf: 616 points
INFO: Calculated initial values for TrendMomentumBTC on ether-fi: 616 points
INFO: Asset lisk: Using 9 windows with threshold 3
INFO: Completed signal registration for ether-fi in 8.52 seconds
INFO: Calculated initial values for TrendMomentumBTC on slerf: 616 points

Registering signals group 5/44:  20%|██        | 1/5 [00:08<00:34,  8.74s/it]

INFO: Calculated initial values for DonchianEnsembleUSD on lisk: 3519 points
INFO: Completed signal registration for slerf in 9.02 seconds

Registering signals group 5/44:  40%|████      | 2/5 [00:09<00:11,  3.92s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on frax-share: 1799 points
INFO: Calculated initial values for RSI_Bullish_USD on frax-share: 1799 points
INFO: Calculated initial values for RSI_Bullish_BTC on frax-share: 1799 points
INFO: Calculated initial values for TrendMomentumUSD on frax-share: 1799 points
INFO: Calculated initial values for TrendMomentumBTC on frax-share: 1799 points
INFO: Completed signal registration for frax-share in 16.47 seconds

Registering signals group 5/44:  60%|██████    | 3/5 [00:16<00:10,  5.45s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on cardano: 2959 points
INFO: Calculated initial values for DonchianEnsembleBTC on lisk: 3519 points
INFO: Calculated initial values for RSI_Bullish_USD on cardano: 2959 points
INFO: Calculated initial values for RSI_Bullish_BTC on cardano: 2959 points
INFO: Calculated initial values for TrendMomentumUSD on cardano: 2959 points
INFO: Calculated initial values for TrendMomentumBTC on cardano: 2959 points
INFO: Completed signal registration for cardano in 22.24 seconds

Registering signals group 5/44:  80%|████████  | 4/5 [00:22<00:05,  5.56s/it]

INFO: Calculated initial values for RSI_Bullish_USD on lisk: 3519 points
INFO: Calculated initial values for RSI_Bullish_BTC on lisk: 3519 points
INFO: Calculated initial values for TrendMomentumUSD on lisk: 3519 points
INFO: Calculated initial values for TrendMomentumBTC on lisk: 3519 points
INFO: Completed signal registration for lisk in 23.81 seconds

Registering signals group 5/44: 100%|██████████| 5/5 [00:23<00:00,  4.76s/it]

INFO: Processing asset group 6/44 with 5 assets
INFO: Starting signal registration for arbitrum
INFO: Starting signal registration for dogwifcoin
INFO: Registering 6 new signals for arbitrum

INFO: Starting signal registration for pancakeswap-token
INFO: Starting signal registration for yearn-finance

Registering signals group 6/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 6 new signals for dogwifcoin
INFO: Starting signal registration for neon
INFO: Registering 6 new signals for pancakeswap-token
INFO: Registering 6 new signals for yearn-finance
INFO: Adapted windows for data length 712: [4, 9, 19, 29, 59, 89, 148]
INFO: Registering 6 new signals for neon
INFO: Asset arbitrum: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on arbitrum: 977 points
INFO: Asset dogwifcoin: Using 7 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on dogwifcoin: 712 points
INFO: Asset neon: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on neon: 860 points
INFO: Asset pancakeswap-token: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleBTC on dogwifcoin: 712 points
INFO: Asset yearn-finance: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on pancakeswap-token: 1882 points
INFO: Calculated initial values for DonchianEnsembleUSD on yearn-finance: 1955 points
INFO: Calculated initial values for DonchianEnsembleBTC on arbitrum: 977 points
INFO: Calculated initial values for RSI_Bullish_USD on dogwifcoin: 712 points
INFO: Calculated initial values for RSI_Bullish_BTC on dogwifcoin: 712 points
INFO: Calculated initial values for DonchianEnsembleBTC on neon: 860 points
INFO: Calculated initial values for TrendMomentumUSD on dogwifcoin: 712 points
INFO: Calculated initial values for TrendMomentumBTC on dogwifcoin: 712 points
INFO: Completed signal registration for dogwifcoin in 8.14 seconds

Registering signals group 6/44:  20%|██        | 1/5 [00:08<00:32,  8.15s/it]

INFO: Calculated initial values for RSI_Bullish_USD on arbitrum: 977 points
INFO: Calculated initial values for RSI_Bullish_USD on neon: 860 points
INFO: Calculated initial values for RSI_Bullish_BTC on arbitrum: 977 points
INFO: Calculated initial values for RSI_Bullish_BTC on neon: 860 points
INFO: Calculated initial values for TrendMomentumUSD on arbitrum: 977 points
INFO: Calculated initial values for TrendMomentumUSD on neon: 860 points
INFO: Calculated initial values for TrendMomentumBTC on arbitrum: 977 points
INFO: Completed signal registration for arbitrum in 10.52 seconds

Registering signals group 6/44:  40%|████      | 2/5 [00:10<00:14,  4.75s/it]

INFO: Calculated initial values for TrendMomentumBTC on neon: 860 points
INFO: Completed signal registration for neon in 10.68 seconds

Registering signals group 6/44:  60%|██████    | 3/5 [00:10<00:05,  2.74s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on yearn-finance: 1955 points
INFO: Calculated initial values for DonchianEnsembleBTC on pancakeswap-token: 1882 points
INFO: Calculated initial values for RSI_Bullish_USD on yearn-finance: 1955 points
INFO: Calculated initial values for RSI_Bullish_USD on pancakeswap-token: 1882 points
INFO: Calculated initial values for RSI_Bullish_BTC on yearn-finance: 1955 points
INFO: Calculated initial values for RSI_Bullish_BTC on pancakeswap-token: 1882 points
INFO: Calculated initial values for TrendMomentumUSD on yearn-finance: 1955 points
INFO: Calculated initial values for TrendMomentumUSD on pancakeswap-token: 1882 points
INFO: Calculated initial values for TrendMomentumBTC on yearn-finance: 1955 points
INFO: Calculated initial values for TrendMomentumBTC on pancakeswap-token: 1882 points
INFO: Completed signal registration for yearn-finance in 15.09 seconds

Registering signals group 6/44:  80%|████████  | 4/5 [00:15<00:03,  3.31s/it]

INFO: Completed signal registration for pancakeswap-token in 15.19 seconds

Registering signals group 6/44: 100%|██████████| 5/5 [00:15<00:00,  3.01s/it]

INFO: Processing asset group 7/44 with 5 assets
INFO: Starting signal registration for chill-guy

INFO: Starting signal registration for optimism

Registering signals group 7/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for venice-token
INFO: Registering 6 new signals for chill-guy
INFO: Starting signal registration for balancer
INFO: Starting signal registration for mantra-dao
INFO: Registering 6 new signals for optimism
INFO: Registering 6 new signals for venice-token
INFO: Adapted windows for data length 371: [5, 10, 15, 30, 46, 77]
INFO: Registering 6 new signals for balancer
INFO: Registering 6 new signals for mantra-dao
INFO: Adapted windows for data length 301: [4, 8, 12, 25, 37, 62]
INFO: Asset chill-guy: Using 6 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on chill-guy: 371 points
INFO: Asset venice-token: Using 6 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on venice-token: 301 points
INFO: Calculated initial values for DonchianEnsembleBTC on venice-token: 301 points
INFO: Calculated initial values for DonchianEnsembleBTC on chill-guy: 371 points
INFO: Asset optimism: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on optimism: 1273 points
INFO: Calculated initial values for RSI_Bullish_USD on venice-token: 301 points
INFO: Calculated initial values for RSI_Bullish_USD on chill-guy: 371 points
INFO: Calculated initial values for RSI_Bullish_BTC on venice-token: 301 points
INFO: Calculated initial values for RSI_Bullish_BTC on chill-guy: 371 points
INFO: Calculated initial values for TrendMomentumUSD on venice-token: 301 points
INFO: Calculated initial values for TrendMomentumUSD on chill-guy: 371 points
INFO: Calculated initial values for TrendMomentumBTC on venice-token: 301 points
INFO: Calculated initial values for TrendMomentumBTC on chill-guy: 371 points
INFO: Completed signal registration for venice-token in 4.77 seconds

Registering signals group 7/44:  20%|██        | 1/5 [00:04<00:19,  5.00s/it]

INFO: Completed signal registration for chill-guy in 4.92 seconds
INFO: Asset balancer: Using 9 windows with threshold 3
INFO: Asset mantra-dao: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on balancer: 1980 points
INFO: Calculated initial values for DonchianEnsembleUSD on mantra-dao: 1924 points
INFO: Calculated initial values for DonchianEnsembleBTC on optimism: 1273 points
INFO: Calculated initial values for RSI_Bullish_USD on optimism: 1273 points
INFO: Calculated initial values for RSI_Bullish_BTC on optimism: 1273 points
INFO: Calculated initial values for TrendMomentumUSD on optimism: 1273 points
INFO: Calculated initial values for DonchianEnsembleBTC on balancer: 1980 points
INFO: Calculated initial values for DonchianEnsembleBTC on mantra-dao: 1924 points
INFO: Calculated initial values for TrendMomentumBTC on optimism: 1273 points
INFO: Completed signal registration for optimism in 11.65 seconds

Registering signals group 7/44:  60%|██████    | 3/5 [00:11<00:07,  3.82s/it]

INFO: Calculated initial values for RSI_Bullish_USD on balancer: 1980 points
INFO: Calculated initial values for RSI_Bullish_USD on mantra-dao: 1924 points
INFO: Calculated initial values for RSI_Bullish_BTC on balancer: 1980 points
INFO: Calculated initial values for RSI_Bullish_BTC on mantra-dao: 1924 points
INFO: Calculated initial values for TrendMomentumUSD on balancer: 1980 points
INFO: Calculated initial values for TrendMomentumBTC on balancer: 1980 points
INFO: Calculated initial values for TrendMomentumUSD on mantra-dao: 1924 points
INFO: Completed signal registration for balancer in 14.32 seconds

Registering signals group 7/44:  80%|████████  | 4/5 [00:14<00:03,  3.37s/it]

INFO: Calculated initial values for TrendMomentumBTC on mantra-dao: 1924 points
INFO: Completed signal registration for mantra-dao in 14.46 seconds

Registering signals group 7/44: 100%|██████████| 5/5 [00:14<00:00,  2.89s/it]

INFO: Processing asset group 8/44 with 5 assets
INFO: Starting signal registration for aioz-network

INFO: Starting signal registration for jasmycoin
INFO: Registering 6 new signals for jasmycoin

Registering signals group 8/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for stellar
INFO: Registering 6 new signals for stellar
INFO: Registering 6 new signals for aioz-network
INFO: Starting signal registration for helium
INFO: Starting signal registration for anzen-finance
INFO: Registering 6 new signals for helium
INFO: Registering 6 new signals for anzen-finance
INFO: Adapted windows for data length 350: [4, 9, 14, 29, 43, 72]
INFO: Asset anzen-finance: Using 6 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on anzen-finance: 350 points
INFO: Asset jasmycoin: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on jasmycoin: 1644 points
INFO: Calculated initial values for DonchianEnsembleBTC on anzen-finance: 350 points
INFO: Asset aioz-network: Using 9 windows with threshold 3
INFO: Calculated initial values for RSI_Bullish_USD on anzen-finance: 350 points
INFO: Calculated initial values for DonchianEnsembleUSD on aioz-network: 1696 points
INFO: Calculated initial values for RSI_Bullish_BTC on anzen-finance: 350 points
INFO: Calculated initial values for TrendMomentumUSD on anzen-finance: 350 points
INFO: Asset helium: Using 9 windows with threshold 3
INFO: Calculated initial values for TrendMomentumBTC on anzen-finance: 350 points
INFO: Calculated initial values for DonchianEnsembleUSD on helium: 2047 points
INFO: Completed signal registration for anzen-finance in 5.39 seconds

Registering signals group 8/44:  20%|██        | 1/5 [00:06<00:25,  6.43s/it]

INFO: Asset stellar: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on stellar: 4128 points
INFO: Calculated initial values for DonchianEnsembleBTC on jasmycoin: 1644 points
INFO: Calculated initial values for DonchianEnsembleBTC on aioz-network: 1696 points
INFO: Calculated initial values for RSI_Bullish_USD on jasmycoin: 1644 points
INFO: Calculated initial values for RSI_Bullish_BTC on jasmycoin: 1644 points
INFO: Calculated initial values for DonchianEnsembleBTC on helium: 2047 points
INFO: Calculated initial values for TrendMomentumUSD on jasmycoin: 1644 points
INFO: Calculated initial values for TrendMomentumBTC on jasmycoin: 1644 points
INFO: Calculated initial values for RSI_Bullish_USD on aioz-network: 1696 points
INFO: Completed signal registration for jasmycoin in 16.06 seconds

Registering signals group 8/44:  40%|████      | 2/5 [00:16<00:25,  8.36s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on aioz-network: 1696 points
INFO: Calculated initial values for TrendMomentumUSD on aioz-network: 1696 points
INFO: Calculated initial values for RSI_Bullish_USD on helium: 2047 points
INFO: Calculated initial values for TrendMomentumBTC on aioz-network: 1696 points
INFO: Completed signal registration for aioz-network in 18.19 seconds

Registering signals group 8/44:  60%|██████    | 3/5 [00:18<00:10,  5.50s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on helium: 2047 points
INFO: Calculated initial values for TrendMomentumUSD on helium: 2047 points
INFO: Calculated initial values for TrendMomentumBTC on helium: 2047 points
INFO: Completed signal registration for helium in 19.16 seconds

Registering signals group 8/44:  80%|████████  | 4/5 [00:19<00:03,  3.89s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on stellar: 4128 points
INFO: Calculated initial values for RSI_Bullish_USD on stellar: 4128 points
INFO: Calculated initial values for RSI_Bullish_BTC on stellar: 4128 points
INFO: Calculated initial values for TrendMomentumUSD on stellar: 4128 points
INFO: Calculated initial values for TrendMomentumBTC on stellar: 4128 points
INFO: Completed signal registration for stellar in 24.36 seconds

Registering signals group 8/44: 100%|██████████| 5/5 [00:24<00:00,  4.88s/it]

INFO: Processing asset group 9/44 with 5 assets
INFO: Starting signal registration for bitcoin

INFO: Registering 6 new signals for bitcoin
INFO: Starting signal registration for velvet

Registering signals group 9/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for botto
INFO: Starting signal registration for verasity
INFO: Starting signal registration for dogecoin
INFO: Registering 6 new signals for velvet
INFO: Registering 6 new signals for botto
INFO: Registering 6 new signals for verasity
INFO: Registering 6 new signals for dogecoin
INFO: Adapted windows for data length 136: [3, 5, 11, 17, 28]
INFO: Asset velvet: Using 5 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on velvet: 136 points
INFO: Calculated initial values for DonchianEnsembleBTC on velvet: 136 points
INFO: Calculated initial values for RSI_Bullish_USD on velvet: 136 points
INFO: Calculated initial values for RSI_Bullish_BTC on velvet: 136 points
INFO: Calculated initial values for TrendMomentumUSD on velvet: 136 points
INFO: Calculated initial values for TrendMomentumBTC on velvet: 136 points
INFO: Completed signal registration for velvet in 3.35 seconds

Registering signals group 9/44:  20%|██        | 1/5 [00:03<00:14,  3.61s/it]

INFO: Asset botto: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on botto: 1507 points
INFO: Asset verasity: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on verasity: 1738 points
INFO: Asset bitcoin: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on bitcoin: 4593 points
INFO: Calculated initial values for DonchianEnsembleBTC on botto: 1507 points
INFO: Asset dogecoin: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on dogecoin: 4362 points
INFO: Calculated initial values for DonchianEnsembleBTC on verasity: 1738 points
INFO: Calculated initial values for RSI_Bullish_USD on botto: 1507 points
INFO: Calculated initial values for RSI_Bullish_BTC on botto: 1507 points
INFO: Calculated initial values for TrendMomentumUSD on botto: 1507 points
INFO: Calculated initial values for RSI_Bullish_USD on verasity: 1738 points
INFO: Calculated initial values for TrendMomentumBTC on botto: 1507 points
INFO: Completed signal registration for botto in 15.49 seconds

Registering signals group 9/44:  40%|████      | 2/5 [00:15<00:25,  8.56s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on verasity: 1738 points
INFO: Calculated initial values for TrendMomentumUSD on verasity: 1738 points
INFO: Calculated initial values for TrendMomentumBTC on verasity: 1738 points
INFO: Completed signal registration for verasity in 17.26 seconds

Registering signals group 9/44:  60%|██████    | 3/5 [00:17<00:11,  5.50s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on bitcoin: 4593 points
INFO: Calculated initial values for RSI_Bullish_USD on bitcoin: 4593 points
INFO: Calculated initial values for RSI_Bullish_BTC on bitcoin: 4593 points
INFO: Calculated initial values for TrendMomentumUSD on bitcoin: 4593 points
INFO: Calculated initial values for TrendMomentumBTC on bitcoin: 4593 points
INFO: Completed signal registration for bitcoin in 19.72 seconds

Registering signals group 9/44:  80%|████████  | 4/5 [00:19<00:04,  4.22s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on dogecoin: 4362 points
INFO: Calculated initial values for RSI_Bullish_USD on dogecoin: 4362 points
INFO: Calculated initial values for RSI_Bullish_BTC on dogecoin: 4362 points
INFO: Calculated initial values for TrendMomentumUSD on dogecoin: 4362 points
INFO: Calculated initial values for TrendMomentumBTC on dogecoin: 4362 points
INFO: Completed signal registration for dogecoin in 24.63 seconds

Registering signals group 9/44: 100%|██████████| 5/5 [00:24<00:00,  4.97s/it]

INFO: Processing asset group 10/44 with 5 assets
INFO: Starting signal registration for kaspa

INFO: Starting signal registration for arweave
INFO: Starting signal registration for kaito

Registering signals group 10/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for neiro-3
INFO: Starting signal registration for polymath
INFO: Registering 6 new signals for kaspa
INFO: Registering 6 new signals for arweave
INFO: Registering 6 new signals for kaito
INFO: Registering 6 new signals for neiro-3
INFO: Registering 6 new signals for polymath
INFO: Adapted windows for data length 277: [3, 7, 11, 23, 34, 57]
INFO: Adapted windows for data length 480: [3, 6, 13, 20, 40, 60, 100]
INFO: Asset kaito: Using 6 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on kaito: 277 points
INFO: Asset neiro-3: Using 7 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on neiro-3: 480 points
INFO: Calculated initial values for DonchianEnsembleBTC on kaito: 277 points
INFO: Asset kaspa: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on kaspa: 1279 points
INFO: Calculated initial values for RSI_Bullish_USD on kaito: 277 points
INFO: Calculated initial values for RSI_Bullish_BTC on kaito: 277 points
INFO: Calculated initial values for TrendMomentumUSD on kaito: 277 points
INFO: Calculated initial values for TrendMomentumBTC on kaito: 277 points
INFO: Calculated initial values for DonchianEnsembleBTC on neiro-3: 480 points
INFO: Completed signal registration for kaito in 4.69 seconds
INFO: Asset arweave: Using 9 windows with threshold 3

Registering signals group 10/44:  20%|██        | 1/5 [00:04<00:19,  4.99s/it]

INFO: Calculated initial values for DonchianEnsembleUSD on arweave: 2216 points
INFO: Calculated initial values for RSI_Bullish_USD on neiro-3: 480 points
INFO: Calculated initial values for RSI_Bullish_BTC on neiro-3: 480 points
INFO: Calculated initial values for TrendMomentumUSD on neiro-3: 480 points
INFO: Calculated initial values for TrendMomentumBTC on neiro-3: 480 points
INFO: Completed signal registration for neiro-3 in 6.67 seconds

Registering signals group 10/44:  40%|████      | 2/5 [00:06<00:09,  3.12s/it]

INFO: Asset polymath: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on polymath: 2845 points
INFO: Calculated initial values for DonchianEnsembleBTC on kaspa: 1279 points
INFO: Calculated initial values for RSI_Bullish_USD on kaspa: 1279 points
INFO: Calculated initial values for RSI_Bullish_BTC on kaspa: 1279 points
INFO: Calculated initial values for TrendMomentumUSD on kaspa: 1279 points
INFO: Calculated initial values for TrendMomentumBTC on kaspa: 1279 points
INFO: Completed signal registration for kaspa in 11.59 seconds
INFO: Calculated initial values for DonchianEnsembleBTC on arweave: 2216 points

Registering signals group 10/44:  60%|██████    | 3/5 [00:11<00:07,  3.95s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on polymath: 2845 points
INFO: Calculated initial values for RSI_Bullish_USD on arweave: 2216 points
INFO: Calculated initial values for RSI_Bullish_BTC on arweave: 2216 points
INFO: Calculated initial values for TrendMomentumUSD on arweave: 2216 points
INFO: Calculated initial values for TrendMomentumBTC on arweave: 2216 points
INFO: Completed signal registration for arweave in 15.74 seconds

Registering signals group 10/44:  80%|████████  | 4/5 [00:15<00:03,  4.00s/it]

INFO: Calculated initial values for RSI_Bullish_USD on polymath: 2845 points
INFO: Calculated initial values for RSI_Bullish_BTC on polymath: 2845 points
INFO: Calculated initial values for TrendMomentumUSD on polymath: 2845 points
INFO: Calculated initial values for TrendMomentumBTC on polymath: 2845 points
INFO: Completed signal registration for polymath in 17.22 seconds

Registering signals group 10/44: 100%|██████████| 5/5 [00:17<00:00,  3.44s/it]

INFO: Processing asset group 11/44 with 5 assets
INFO: Starting signal registration for the-open-network
INFO: Starting signal registration for alchemy-pay

INFO: Registering 6 new signals for the-open-network
INFO: Starting signal registration for kyber-network-crystal

Registering signals group 11/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for genopets
INFO: Starting signal registration for turbo
INFO: Registering 6 new signals for alchemy-pay
INFO: Registering 6 new signals for kyber-network-crystal
INFO: Registering 6 new signals for genopets
INFO: Registering 6 new signals for turbo
INFO: Asset the-open-network: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on the-open-network: 1550 points
INFO: Asset turbo: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on turbo: 935 points
INFO: Asset genopets: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on genopets: 1467 points
INFO: Asset kyber-network-crystal: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on kyber-network-crystal: 1677 points
INFO: Asset alchemy-pay: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on alchemy-pay: 1903 points
INFO: Calculated initial values for DonchianEnsembleBTC on turbo: 935 points
INFO: Calculated initial values for DonchianEnsembleBTC on the-open-network: 1550 points
INFO: Calculated initial values for RSI_Bullish_USD on turbo: 935 points
INFO: Calculated initial values for DonchianEnsembleBTC on genopets: 1467 points
INFO: Calculated initial values for RSI_Bullish_BTC on turbo: 935 points
INFO: Calculated initial values for TrendMomentumUSD on turbo: 935 points
INFO: Calculated initial values for DonchianEnsembleBTC on kyber-network-crystal: 1677 points
INFO: Calculated initial values for TrendMomentumBTC on turbo: 935 points
INFO: Completed signal registration for turbo in 14.84 seconds

Registering signals group 11/44:  20%|██        | 1/5 [00:15<01:00, 15.06s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on alchemy-pay: 1903 points
INFO: Calculated initial values for RSI_Bullish_USD on the-open-network: 1550 points
INFO: Calculated initial values for RSI_Bullish_USD on genopets: 1467 points
INFO: Calculated initial values for RSI_Bullish_BTC on the-open-network: 1550 points
INFO: Calculated initial values for RSI_Bullish_BTC on genopets: 1467 points
INFO: Calculated initial values for TrendMomentumUSD on the-open-network: 1550 points
INFO: Calculated initial values for TrendMomentumUSD on genopets: 1467 points
INFO: Calculated initial values for TrendMomentumBTC on the-open-network: 1550 points
INFO: Calculated initial values for RSI_Bullish_USD on kyber-network-crystal: 1677 points
INFO: Calculated initial values for TrendMomentumBTC on genopets: 1467 points
INFO: Completed signal registration for the-open-network in 18.34 seconds

Registering signals group 11/44:  40%|████      | 2/5 [00:18<00:24,  8.18s/it]

INFO: Completed signal registration for genopets in 18.64 seconds

Registering signals group 11/44:  60%|██████    | 3/5 [00:18<00:09,  4.63s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on kyber-network-crystal: 1677 points
INFO: Calculated initial values for RSI_Bullish_USD on alchemy-pay: 1903 points
INFO: Calculated initial values for TrendMomentumUSD on kyber-network-crystal: 1677 points
INFO: Calculated initial values for RSI_Bullish_BTC on alchemy-pay: 1903 points
INFO: Calculated initial values for TrendMomentumBTC on kyber-network-crystal: 1677 points
INFO: Completed signal registration for kyber-network-crystal in 19.82 seconds

Registering signals group 11/44:  80%|████████  | 4/5 [00:19<00:03,  3.20s/it]

INFO: Calculated initial values for TrendMomentumUSD on alchemy-pay: 1903 points
INFO: Calculated initial values for TrendMomentumBTC on alchemy-pay: 1903 points
INFO: Completed signal registration for alchemy-pay in 20.21 seconds

Registering signals group 11/44: 100%|██████████| 5/5 [00:20<00:00,  4.02s/it]

INFO: Processing asset group 12/44 with 5 assets
INFO: Starting signal registration for usd-coin
INFO: Starting signal registration for blockstack

INFO: Starting signal registration for paal-ai

Registering signals group 12/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for based-brett
INFO: Registering 6 new signals for usd-coin
INFO: Starting signal registration for badger-dao
INFO: Registering 6 new signals for blockstack
INFO: Registering 6 new signals for paal-ai
INFO: Registering 6 new signals for based-brett
INFO: Registering 6 new signals for badger-dao
INFO: Adapted windows for data length 634: [4, 8, 17, 26, 52, 79, 132]
INFO: Asset based-brett: Using 7 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on based-brett: 634 points
INFO: Asset paal-ai: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on paal-ai: 882 points
INFO: Calculated initial values for DonchianEnsembleBTC on based-brett: 634 points
INFO: Asset badger-dao: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on badger-dao: 1816 points
INFO: Asset blockstack: Using 9 windows with threshold 3
INFO: Asset usd-coin: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on blockstack: 2223 points
INFO: Calculated initial values for DonchianEnsembleUSD on usd-coin: 2608 points
INFO: Calculated initial values for RSI_Bullish_USD on based-brett: 634 points
INFO: Calculated initial values for DonchianEnsembleBTC on paal-ai: 882 points
INFO: Calculated initial values for RSI_Bullish_BTC on based-brett: 634 points
INFO: Calculated initial values for TrendMomentumUSD on based-brett: 634 points
INFO: Calculated initial values for TrendMomentumBTC on based-brett: 634 points
INFO: Completed signal registration for based-brett in 8.60 seconds

Registering signals group 12/44:  20%|██        | 1/5 [00:08<00:34,  8.72s/it]

INFO: Calculated initial values for RSI_Bullish_USD on paal-ai: 882 points
INFO: Calculated initial values for RSI_Bullish_BTC on paal-ai: 882 points
INFO: Calculated initial values for TrendMomentumUSD on paal-ai: 882 points
INFO: Calculated initial values for TrendMomentumBTC on paal-ai: 882 points
INFO: Completed signal registration for paal-ai in 11.23 seconds

Registering signals group 12/44:  40%|████      | 2/5 [00:11<00:15,  5.22s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on badger-dao: 1816 points
INFO: Calculated initial values for DonchianEnsembleBTC on blockstack: 2223 points
INFO: Calculated initial values for RSI_Bullish_USD on badger-dao: 1816 points
INFO: Calculated initial values for DonchianEnsembleBTC on usd-coin: 2608 points
INFO: Calculated initial values for RSI_Bullish_BTC on badger-dao: 1816 points
INFO: Calculated initial values for TrendMomentumUSD on badger-dao: 1816 points
INFO: Calculated initial values for TrendMomentumBTC on badger-dao: 1816 points
INFO: Completed signal registration for badger-dao in 17.59 seconds

Registering signals group 12/44:  60%|██████    | 3/5 [00:17<00:11,  5.67s/it]

INFO: Calculated initial values for RSI_Bullish_USD on blockstack: 2223 points
INFO: Calculated initial values for RSI_Bullish_BTC on blockstack: 2223 points
INFO: Calculated initial values for TrendMomentumUSD on blockstack: 2223 points
INFO: Calculated initial values for TrendMomentumBTC on blockstack: 2223 points
INFO: Calculated initial values for RSI_Bullish_USD on usd-coin: 2608 points
INFO: Completed signal registration for blockstack in 19.20 seconds

Registering signals group 12/44:  80%|████████  | 4/5 [00:19<00:04,  4.05s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on usd-coin: 2608 points
INFO: Calculated initial values for TrendMomentumUSD on usd-coin: 2608 points
INFO: Calculated initial values for TrendMomentumBTC on usd-coin: 2608 points
INFO: Completed signal registration for usd-coin in 19.81 seconds

Registering signals group 12/44: 100%|██████████| 5/5 [00:19<00:00,  3.96s/it]

INFO: Processing asset group 13/44 with 5 assets
INFO: Starting signal registration for flow

INFO: Starting signal registration for tokenbot-2

Registering signals group 13/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for swarm
INFO: Starting signal registration for mog-coin
INFO: Registering 6 new signals for flow
INFO: Starting signal registration for bubblemaps
INFO: Registering 6 new signals for tokenbot-2
INFO: Registering 6 new signals for swarm
INFO: Registering 6 new signals for mog-coin
INFO: Registering 6 new signals for bubblemaps
INFO: Adapted windows for data length 379: [5, 10, 15, 31, 47, 78]
INFO: Adapted windows for data length 258: [3, 7, 10, 21, 32, 53]
INFO: Asset bubblemaps: Using 6 windows with threshold 3
INFO: Asset tokenbot-2: Using 6 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on bubblemaps: 258 points
INFO: Calculated initial values for DonchianEnsembleUSD on tokenbot-2: 379 points
INFO: Asset mog-coin: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on mog-coin: 857 points
INFO: Calculated initial values for DonchianEnsembleBTC on bubblemaps: 258 points
INFO: Calculated initial values for DonchianEnsembleBTC on tokenbot-2: 379 points
INFO: Asset flow: Using 9 windows with threshold 3
INFO: Calculated initial values for RSI_Bullish_USD on bubblemaps: 258 points
INFO: Calculated initial values for DonchianEnsembleUSD on flow: 1762 points
INFO: Calculated initial values for RSI_Bullish_BTC on bubblemaps: 258 points
INFO: Calculated initial values for RSI_Bullish_USD on tokenbot-2: 379 points
INFO: Calculated initial values for TrendMomentumUSD on bubblemaps: 258 points
INFO: Calculated initial values for RSI_Bullish_BTC on tokenbot-2: 379 points
INFO: Calculated initial values for TrendMomentumBTC on bubblemaps: 258 points
INFO: Completed signal registration for bubblemaps in 4.67 seconds
INFO: Calculated initial values for TrendMomentumUSD on tokenbot-2: 379 points

Registering signals group 13/44:  20%|██        | 1/5 [00:04<00:19,  4.80s/it]

INFO: Calculated initial values for TrendMomentumBTC on tokenbot-2: 379 points
INFO: Calculated initial values for DonchianEnsembleBTC on mog-coin: 857 points
INFO: Completed signal registration for tokenbot-2 in 5.27 seconds

Registering signals group 13/44:  40%|████      | 2/5 [00:05<00:07,  2.40s/it]

INFO: Asset swarm: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on swarm: 3497 points
INFO: Calculated initial values for RSI_Bullish_USD on mog-coin: 857 points
INFO: Calculated initial values for RSI_Bullish_BTC on mog-coin: 857 points
INFO: Calculated initial values for TrendMomentumUSD on mog-coin: 857 points
INFO: Calculated initial values for TrendMomentumBTC on mog-coin: 857 points
INFO: Completed signal registration for mog-coin in 8.52 seconds

Registering signals group 13/44:  60%|██████    | 3/5 [00:08<00:05,  2.75s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on flow: 1762 points
INFO: Calculated initial values for RSI_Bullish_USD on flow: 1762 points
INFO: Calculated initial values for RSI_Bullish_BTC on flow: 1762 points
INFO: Calculated initial values for TrendMomentumUSD on flow: 1762 points
INFO: Calculated initial values for TrendMomentumBTC on flow: 1762 points
INFO: Completed signal registration for flow in 12.25 seconds

Registering signals group 13/44:  80%|████████  | 4/5 [00:12<00:03,  3.10s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on swarm: 3497 points
ERROR: Error calculating RSI Bullish signal for swarm: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
INFO: Calculated initial values for RSI_Bullish_USD on swarm: 3497 points
INFO: Calculated initial values for RSI_Bullish_BTC on swarm: 3497 points
ERROR: Error calculating Trend Momentum signal for swarm: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
INFO: Calculated initial values for TrendMomentumUSD on swarm: 3497 points
INFO: Calculated initial values for TrendMomentumBTC on swarm: 3497 points
INFO: Completed signal registration for swarm in 16.26 seconds

Registering signals group 13/44: 100%|██████████| 5/5 [00:16<00:00,  3.25s/it]

INFO: Processing asset group 14/44 with 5 assets
INFO: Starting signal registration for apu-s-club
INFO: Starting signal registration for pax-gold
INFO: Starting signal registration for pump-fun

INFO: Registering 6 new signals for apu-s-club
INFO: Starting signal registration for injective-protocol

Registering signals group 14/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 6 new signals for pax-gold
INFO: Starting signal registration for solana
INFO: Registering 6 new signals for pump-fun
INFO: Adapted windows for data length 621: [4, 8, 17, 25, 51, 77, 129]
INFO: Registering 6 new signals for injective-protocol
INFO: Registering 6 new signals for solana
INFO: Adapted windows for data length 132: [3, 5, 11, 16, 27]
INFO: Asset pump-fun: Using 5 windows with threshold 3
INFO: Asset apu-s-club: Using 7 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on pump-fun: 132 points
INFO: Calculated initial values for DonchianEnsembleUSD on apu-s-club: 621 points
INFO: Calculated initial values for DonchianEnsembleBTC on pump-fun: 132 points
INFO: Calculated initial values for RSI_Bullish_USD on pump-fun: 132 points
INFO: Calculated initial values for RSI_Bullish_BTC on pump-fun: 132 points
INFO: Calculated initial values for TrendMomentumUSD on pump-fun: 132 points
INFO: Calculated initial values for TrendMomentumBTC on pump-fun: 132 points
INFO: Completed signal registration for pump-fun in 3.04 seconds

Registering signals group 14/44:  20%|██        | 1/5 [00:03<00:13,  3.42s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on apu-s-club: 621 points
INFO: Asset pax-gold: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on pax-gold: 2262 points
INFO: Asset injective-protocol: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on injective-protocol: 1860 points
INFO: Asset solana: Using 9 windows with threshold 3
INFO: Calculated initial values for RSI_Bullish_USD on apu-s-club: 621 points
INFO: Calculated initial values for DonchianEnsembleUSD on solana: 2054 points
INFO: Calculated initial values for RSI_Bullish_BTC on apu-s-club: 621 points
INFO: Calculated initial values for TrendMomentumUSD on apu-s-club: 621 points
INFO: Calculated initial values for TrendMomentumBTC on apu-s-club: 621 points
INFO: Completed signal registration for apu-s-club in 6.34 seconds

Registering signals group 14/44:  40%|████      | 2/5 [00:06<00:09,  3.25s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on injective-protocol: 1860 points
INFO: Calculated initial values for DonchianEnsembleBTC on solana: 2054 points
INFO: Calculated initial values for DonchianEnsembleBTC on pax-gold: 2262 points
INFO: Calculated initial values for RSI_Bullish_USD on injective-protocol: 1860 points
INFO: Calculated initial values for RSI_Bullish_BTC on injective-protocol: 1860 points
INFO: Calculated initial values for RSI_Bullish_USD on solana: 2054 points
INFO: Calculated initial values for TrendMomentumUSD on injective-protocol: 1860 points
INFO: Calculated initial values for RSI_Bullish_USD on pax-gold: 2262 points
INFO: Calculated initial values for RSI_Bullish_BTC on solana: 2054 points
INFO: Calculated initial values for TrendMomentumBTC on injective-protocol: 1860 points
INFO: Calculated initial values for TrendMomentumUSD on solana: 2054 points
INFO: Calculated initial values for RSI_Bullish_BTC on pax-gold: 2262 points
INFO: Completed signal registration for injective-protocol in 15.67 seconds

Registering signals group 14/44:  60%|██████    | 3/5 [00:15<00:11,  5.96s/it]

INFO: Calculated initial values for TrendMomentumBTC on solana: 2054 points
INFO: Completed signal registration for solana in 15.84 seconds

Registering signals group 14/44:  80%|████████  | 4/5 [00:16<00:03,  3.72s/it]

INFO: Calculated initial values for TrendMomentumUSD on pax-gold: 2262 points
INFO: Calculated initial values for TrendMomentumBTC on pax-gold: 2262 points
INFO: Completed signal registration for pax-gold in 16.27 seconds

Registering signals group 14/44: 100%|██████████| 5/5 [00:16<00:00,  3.25s/it]

INFO: Processing asset group 15/44 with 5 assets
INFO: Starting signal registration for zeus-network
INFO: Starting signal registration for bonk

INFO: Starting signal registration for dusk-network
INFO: Registering 6 new signals for zeus-network

Registering signals group 15/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for ronin
INFO: Starting signal registration for harrypotterobamasonic10in
INFO: Registering 6 new signals for bonk
INFO: Registering 6 new signals for dusk-network
INFO: Adapted windows for data length 598: [4, 8, 16, 24, 49, 74, 124]
INFO: Registering 6 new signals for ronin
INFO: Registering 6 new signals for harrypotterobamasonic10in
INFO: Asset zeus-network: Using 7 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on zeus-network: 598 points
INFO: Asset bonk: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on bonk: 1061 points
INFO: Asset harrypotterobamasonic10in: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on harrypotterobamasonic10in: 924 points
INFO: Asset ronin: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleBTC on zeus-network: 598 points
INFO: Calculated initial values for DonchianEnsembleUSD on ronin: 1397 points
INFO: Asset dusk-network: Using 9 windows with threshold 3
INFO: Calculated initial values for RSI_Bullish_USD on zeus-network: 598 points
INFO: Calculated initial values for DonchianEnsembleUSD on dusk-network: 2333 points
INFO: Calculated initial values for RSI_Bullish_BTC on zeus-network: 598 points
INFO: Calculated initial values for TrendMomentumUSD on zeus-network: 598 points
INFO: Calculated initial values for DonchianEnsembleBTC on bonk: 1061 points
INFO: Calculated initial values for DonchianEnsembleBTC on harrypotterobamasonic10in: 924 points
INFO: Calculated initial values for TrendMomentumBTC on zeus-network: 598 points
INFO: Completed signal registration for zeus-network in 8.66 seconds

Registering signals group 15/44:  20%|██        | 1/5 [00:08<00:35,  8.97s/it]

INFO: Calculated initial values for RSI_Bullish_USD on harrypotterobamasonic10in: 924 points
INFO: Calculated initial values for RSI_Bullish_USD on bonk: 1061 points
INFO: Calculated initial values for DonchianEnsembleBTC on ronin: 1397 points
INFO: Calculated initial values for RSI_Bullish_BTC on harrypotterobamasonic10in: 924 points
INFO: Calculated initial values for RSI_Bullish_BTC on bonk: 1061 points
INFO: Calculated initial values for TrendMomentumUSD on harrypotterobamasonic10in: 924 points
INFO: Calculated initial values for TrendMomentumUSD on bonk: 1061 points
INFO: Calculated initial values for TrendMomentumBTC on harrypotterobamasonic10in: 924 points
INFO: Calculated initial values for TrendMomentumBTC on bonk: 1061 points
INFO: Completed signal registration for harrypotterobamasonic10in in 12.37 seconds
INFO: Completed signal registration for bonk in 12.58 seconds

Registering signals group 15/44:  60%|██████    | 3/5 [00:12<00:06,  3.23s/it]

INFO: Calculated initial values for RSI_Bullish_USD on ronin: 1397 points
INFO: Calculated initial values for RSI_Bullish_BTC on ronin: 1397 points
INFO: Calculated initial values for TrendMomentumUSD on ronin: 1397 points
INFO: Calculated initial values for TrendMomentumBTC on ronin: 1397 points
INFO: Completed signal registration for ronin in 13.84 seconds
INFO: Calculated initial values for DonchianEnsembleBTC on dusk-network: 2333 points

Registering signals group 15/44:  80%|████████  | 4/5 [00:13<00:02,  2.40s/it]

INFO: Calculated initial values for RSI_Bullish_USD on dusk-network: 2333 points
INFO: Calculated initial values for RSI_Bullish_BTC on dusk-network: 2333 points
INFO: Calculated initial values for TrendMomentumUSD on dusk-network: 2333 points
INFO: Calculated initial values for TrendMomentumBTC on dusk-network: 2333 points
INFO: Completed signal registration for dusk-network in 15.92 seconds

Registering signals group 15/44: 100%|██████████| 5/5 [00:15<00:00,  3.18s/it]

INFO: Processing asset group 16/44 with 5 assets
INFO: Starting signal registration for bio-protocol

INFO: Starting signal registration for chex-token
INFO: Starting signal registration for gala

Registering signals group 16/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for band-protocol
INFO: Starting signal registration for euler
INFO: Registering 6 new signals for bio-protocol
INFO: Registering 6 new signals for chex-token
INFO: Registering 6 new signals for gala
INFO: Registering 6 new signals for band-protocol
INFO: Registering 6 new signals for euler
INFO: Adapted windows for data length 324: [4, 9, 13, 27, 40, 67]
INFO: Asset bio-protocol: Using 6 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on bio-protocol: 324 points
INFO: Calculated initial values for DonchianEnsembleBTC on bio-protocol: 324 points
INFO: Asset euler: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on euler: 1249 points
INFO: Calculated initial values for RSI_Bullish_USD on bio-protocol: 324 points
INFO: Calculated initial values for RSI_Bullish_BTC on bio-protocol: 324 points
INFO: Asset gala: Using 9 windows with threshold 3
INFO: Calculated initial values for TrendMomentumUSD on bio-protocol: 324 points
INFO: Asset chex-token: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on gala: 1895 points
INFO: Calculated initial values for TrendMomentumBTC on bio-protocol: 324 points
INFO: Calculated initial values for DonchianEnsembleUSD on chex-token: 2119 points
INFO: Asset band-protocol: Using 9 windows with threshold 3
INFO: Completed signal registration for bio-protocol in 4.95 seconds
INFO: Calculated initial values for DonchianEnsembleUSD on band-protocol: 2259 points

Registering signals group 16/44:  20%|██        | 1/5 [00:05<00:21,  5.36s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on euler: 1249 points
INFO: Calculated initial values for RSI_Bullish_USD on euler: 1249 points
INFO: Calculated initial values for RSI_Bullish_BTC on euler: 1249 points
INFO: Calculated initial values for DonchianEnsembleBTC on gala: 1895 points
INFO: Calculated initial values for TrendMomentumUSD on euler: 1249 points
INFO: Calculated initial values for TrendMomentumBTC on euler: 1249 points
INFO: Calculated initial values for DonchianEnsembleBTC on chex-token: 2119 points
INFO: Completed signal registration for euler in 14.00 seconds

Registering signals group 16/44:  40%|████      | 2/5 [00:14<00:22,  7.47s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on band-protocol: 2259 points
INFO: Calculated initial values for RSI_Bullish_USD on gala: 1895 points
INFO: Calculated initial values for RSI_Bullish_BTC on gala: 1895 points
INFO: Calculated initial values for TrendMomentumUSD on gala: 1895 points
INFO: Calculated initial values for RSI_Bullish_USD on chex-token: 2119 points
INFO: Calculated initial values for TrendMomentumBTC on gala: 1895 points
INFO: Calculated initial values for RSI_Bullish_BTC on chex-token: 2119 points
INFO: Completed signal registration for gala in 20.38 seconds
INFO: Calculated initial values for RSI_Bullish_USD on band-protocol: 2259 points

Registering signals group 16/44:  60%|██████    | 3/5 [00:20<00:13,  6.83s/it]

INFO: Calculated initial values for TrendMomentumUSD on chex-token: 2119 points
INFO: Calculated initial values for RSI_Bullish_BTC on band-protocol: 2259 points
INFO: Calculated initial values for TrendMomentumBTC on chex-token: 2119 points
INFO: Calculated initial values for TrendMomentumUSD on band-protocol: 2259 points
INFO: Completed signal registration for chex-token in 21.08 seconds

Registering signals group 16/44:  80%|████████  | 4/5 [00:21<00:04,  4.41s/it]

INFO: Calculated initial values for TrendMomentumBTC on band-protocol: 2259 points
INFO: Completed signal registration for band-protocol in 21.31 seconds

Registering signals group 16/44: 100%|██████████| 5/5 [00:21<00:00,  4.26s/it]

INFO: Processing asset group 17/44 with 5 assets
INFO: Starting signal registration for morpho
INFO: Starting signal registration for beam-2

INFO: Starting signal registration for deep

Registering signals group 17/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for power-ledger
INFO: Registering 6 new signals for morpho
INFO: Starting signal registration for fantom
INFO: Registering 6 new signals for beam-2
INFO: Registering 6 new signals for deep
INFO: Registering 6 new signals for power-ledger
INFO: Adapted windows for data length 369: [5, 10, 15, 30, 46, 76]
INFO: Registering 6 new signals for fantom
INFO: Adapted windows for data length 406: [5, 11, 16, 33, 50, 84]
INFO: Asset morpho: Using 6 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on morpho: 369 points
INFO: Asset deep: Using 6 windows with threshold 3
INFO: Asset beam-2: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on deep: 406 points
INFO: Calculated initial values for DonchianEnsembleUSD on beam-2: 760 points
INFO: Calculated initial values for DonchianEnsembleBTC on morpho: 369 points
INFO: Calculated initial values for RSI_Bullish_USD on morpho: 369 points
INFO: Calculated initial values for DonchianEnsembleBTC on deep: 406 points
INFO: Calculated initial values for RSI_Bullish_BTC on morpho: 369 points
INFO: Calculated initial values for TrendMomentumUSD on morpho: 369 points
INFO: Calculated initial values for TrendMomentumBTC on morpho: 369 points
INFO: Calculated initial values for RSI_Bullish_USD on deep: 406 points
INFO: Completed signal registration for morpho in 4.48 seconds
INFO: Calculated initial values for RSI_Bullish_BTC on deep: 406 points

Registering signals group 17/44:  20%|██        | 1/5 [00:04<00:19,  4.88s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on beam-2: 760 points
INFO: Calculated initial values for TrendMomentumUSD on deep: 406 points
INFO: Calculated initial values for TrendMomentumBTC on deep: 406 points
INFO: Asset fantom: Using 9 windows with threshold 3
INFO: Completed signal registration for deep in 5.56 seconds

Registering signals group 17/44:  40%|████      | 2/5 [00:05<00:07,  2.49s/it]

INFO: Calculated initial values for DonchianEnsembleUSD on fantom: 2583 points
INFO: Asset power-ledger: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on power-ledger: 2938 points
INFO: Calculated initial values for RSI_Bullish_USD on beam-2: 760 points
INFO: Calculated initial values for RSI_Bullish_BTC on beam-2: 760 points
INFO: Calculated initial values for TrendMomentumUSD on beam-2: 760 points
INFO: Calculated initial values for TrendMomentumBTC on beam-2: 760 points
INFO: Completed signal registration for beam-2 in 7.39 seconds

Registering signals group 17/44:  60%|██████    | 3/5 [00:07<00:04,  2.18s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on fantom: 2583 points
INFO: Calculated initial values for DonchianEnsembleBTC on power-ledger: 2938 points
INFO: Calculated initial values for RSI_Bullish_USD on fantom: 2583 points
INFO: Calculated initial values for RSI_Bullish_BTC on fantom: 2583 points
INFO: Calculated initial values for TrendMomentumUSD on fantom: 2583 points
INFO: Calculated initial values for RSI_Bullish_USD on power-ledger: 2938 points
INFO: Calculated initial values for TrendMomentumBTC on fantom: 2583 points
INFO: Calculated initial values for RSI_Bullish_BTC on power-ledger: 2938 points
INFO: Completed signal registration for fantom in 15.71 seconds

Registering signals group 17/44:  80%|████████  | 4/5 [00:15<00:04,  4.56s/it]

INFO: Calculated initial values for TrendMomentumUSD on power-ledger: 2938 points
INFO: Calculated initial values for TrendMomentumBTC on power-ledger: 2938 points
INFO: Completed signal registration for power-ledger in 16.17 seconds

Registering signals group 17/44: 100%|██████████| 5/5 [00:16<00:00,  3.23s/it]

INFO: Processing asset group 18/44 with 5 assets
INFO: Starting signal registration for dash

INFO: Starting signal registration for dodo

Registering signals group 18/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for rari-governance-token
INFO: Starting signal registration for secret
INFO: Starting signal registration for internet-computer
INFO: Registering 6 new signals for dash
INFO: Registering 6 new signals for dodo
INFO: Registering 6 new signals for rari-governance-token
INFO: Registering 6 new signals for secret
INFO: Registering 6 new signals for internet-computer
INFO: Asset dodo: Using 9 windows with threshold 3
INFO: Asset internet-computer: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on dodo: 1881 points
INFO: Calculated initial values for DonchianEnsembleUSD on internet-computer: 1659 points
INFO: Asset rari-governance-token: Using 9 windows with threshold 3
INFO: Asset secret: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on rari-governance-token: 1868 points
INFO: Calculated initial values for DonchianEnsembleUSD on secret: 1880 points
INFO: Asset dash: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on dash: 4301 points
INFO: Calculated initial values for DonchianEnsembleBTC on internet-computer: 1659 points
INFO: Calculated initial values for DonchianEnsembleBTC on dodo: 1881 points
INFO: Calculated initial values for DonchianEnsembleBTC on secret: 1880 points
INFO: Calculated initial values for DonchianEnsembleBTC on rari-governance-token: 1868 points
INFO: Calculated initial values for RSI_Bullish_USD on internet-computer: 1659 points
INFO: Calculated initial values for RSI_Bullish_BTC on internet-computer: 1659 points
INFO: Calculated initial values for RSI_Bullish_USD on dodo: 1881 points
INFO: Calculated initial values for TrendMomentumUSD on internet-computer: 1659 points
INFO: Calculated initial values for RSI_Bullish_USD on secret: 1880 points
INFO: Calculated initial values for TrendMomentumBTC on internet-computer: 1659 points
INFO: Calculated initial values for RSI_Bullish_BTC on dodo: 1881 points
INFO: Completed signal registration for internet-computer in 20.98 seconds

Registering signals group 18/44:  20%|██        | 1/5 [00:21<01:24, 21.08s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on secret: 1880 points
INFO: Calculated initial values for TrendMomentumUSD on dodo: 1881 points
INFO: Calculated initial values for TrendMomentumBTC on dodo: 1881 points
INFO: Calculated initial values for TrendMomentumUSD on secret: 1880 points
INFO: Completed signal registration for dodo in 22.08 seconds

Registering signals group 18/44:  40%|████      | 2/5 [00:22<00:27,  9.30s/it]

INFO: Calculated initial values for TrendMomentumBTC on secret: 1880 points
INFO: Completed signal registration for secret in 22.53 seconds

Registering signals group 18/44:  60%|██████    | 3/5 [00:22<00:10,  5.27s/it]

ERROR: Error calculating RSI Bullish signal for rari-governance-token: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
INFO: Calculated initial values for RSI_Bullish_USD on rari-governance-token: 1868 points
INFO: Calculated initial values for RSI_Bullish_BTC on rari-governance-token: 1868 points
ERROR: Error calculating Trend Momentum signal for rari-governance-token: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
INFO: Calculated initial values for TrendMomentumUSD on rari-governance-token: 1868 points
INFO: Calculated initial values for TrendMomentumBTC on rari-governance-token: 1868 points
INFO: Completed signal registration for rari-governance-token in 25.68 seconds

Registering signals group 18/44:  80%|████████  | 4/5 [00:25<00:04,  4.40s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on dash: 4301 points
INFO: Calculated initial values for RSI_Bullish_USD on dash: 4301 points
INFO: Calculated initial values for RSI_Bullish_BTC on dash: 4301 points
INFO: Calculated initial values for TrendMomentumUSD on dash: 4301 points
INFO: Calculated initial values for TrendMomentumBTC on dash: 4301 points
INFO: Completed signal registration for dash in 29.12 seconds

Registering signals group 18/44: 100%|██████████| 5/5 [00:29<00:00,  5.82s/it]

INFO: Processing asset group 19/44 with 5 assets
INFO: Starting signal registration for arkham
INFO: Starting signal registration for chainlink

INFO: Starting signal registration for numeraire

Registering signals group 19/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for aethir
INFO: Registering 6 new signals for arkham
INFO: Starting signal registration for sturdy
INFO: Registering 6 new signals for chainlink
INFO: Registering 6 new signals for numeraire
INFO: Registering 6 new signals for aethir
INFO: Registering 6 new signals for sturdy
INFO: Adapted windows for data length 530: [3, 7, 14, 22, 44, 66, 110]
INFO: Adapted windows for data length 641: [4, 8, 17, 26, 53, 80, 133]
INFO: Asset arkham: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on arkham: 860 points
INFO: Asset aethir: Using 7 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on aethir: 530 points
INFO: Asset sturdy: Using 7 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on sturdy: 641 points
INFO: Calculated initial values for DonchianEnsembleBTC on aethir: 530 points
INFO: Calculated initial values for DonchianEnsembleBTC on sturdy: 641 points
INFO: Calculated initial values for RSI_Bullish_USD on aethir: 530 points
INFO: Calculated initial values for DonchianEnsembleBTC on arkham: 860 points
INFO: Calculated initial values for RSI_Bullish_BTC on aethir: 530 points
INFO: Calculated initial values for TrendMomentumUSD on aethir: 530 points
INFO: Asset chainlink: Using 9 windows with threshold 3
INFO: Calculated initial values for TrendMomentumBTC on aethir: 530 points
INFO: Calculated initial values for DonchianEnsembleUSD on chainlink: 2937 points
INFO: Calculated initial values for RSI_Bullish_USD on sturdy: 641 points
INFO: Completed signal registration for aethir in 8.99 seconds

Registering signals group 19/44:  20%|██        | 1/5 [00:09<00:39,  9.89s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on sturdy: 641 points
INFO: Asset numeraire: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on numeraire: 3056 points
INFO: Calculated initial values for TrendMomentumUSD on sturdy: 641 points
INFO: Calculated initial values for RSI_Bullish_USD on arkham: 860 points
INFO: Calculated initial values for TrendMomentumBTC on sturdy: 641 points
INFO: Completed signal registration for sturdy in 12.17 seconds

Registering signals group 19/44:  40%|████      | 2/5 [00:12<00:16,  5.57s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on arkham: 860 points
INFO: Calculated initial values for TrendMomentumUSD on arkham: 860 points
INFO: Calculated initial values for TrendMomentumBTC on arkham: 860 points
INFO: Completed signal registration for arkham in 13.97 seconds

Registering signals group 19/44:  60%|██████    | 3/5 [00:14<00:07,  3.81s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on chainlink: 2937 points
INFO: Calculated initial values for DonchianEnsembleBTC on numeraire: 3056 points
INFO: Calculated initial values for RSI_Bullish_USD on chainlink: 2937 points
INFO: Calculated initial values for RSI_Bullish_USD on numeraire: 3056 points
INFO: Calculated initial values for RSI_Bullish_BTC on chainlink: 2937 points
INFO: Calculated initial values for TrendMomentumUSD on chainlink: 2937 points
INFO: Calculated initial values for RSI_Bullish_BTC on numeraire: 3056 points
INFO: Calculated initial values for TrendMomentumBTC on chainlink: 2937 points
INFO: Calculated initial values for TrendMomentumUSD on numeraire: 3056 points
INFO: Completed signal registration for chainlink in 1011.86 seconds

Registering signals group 19/44:  80%|████████  | 4/5 [16:51<06:36, 396.21s/it]

INFO: Calculated initial values for TrendMomentumBTC on numeraire: 3056 points
INFO: Completed signal registration for numeraire in 1012.08 seconds

Registering signals group 19/44: 100%|██████████| 5/5 [16:52<00:00, 202.42s/it]

INFO: Processing asset group 20/44 with 5 assets
INFO: Starting signal registration for dog-go-to-the-moon-rune
INFO: Starting signal registration for pepe

INFO: Starting signal registration for virtual-protocol
INFO: Registering 6 new signals for dog-go-to-the-moon-rune

Registering signals group 20/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for aixbt
INFO: Starting signal registration for pudgy-penguins
INFO: Registering 6 new signals for pepe
INFO: Registering 6 new signals for virtual-protocol
INFO: Adapted windows for data length 577: [4, 8, 16, 24, 48, 72, 120]
INFO: Registering 6 new signals for aixbt
INFO: Registering 6 new signals for pudgy-penguins
INFO: Adapted windows for data length 697: [4, 9, 19, 29, 58, 87, 145]
INFO: Adapted windows for data length 342: [4, 9, 14, 28, 42, 71]
INFO: Asset aixbt: Using 6 windows with threshold 3
INFO: Asset dog-go-to-the-moon-rune: Using 7 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on aixbt: 371 points
INFO: Asset pudgy-penguins: Using 6 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on dog-go-to-the-moon-rune: 577 points
INFO: Asset pepe: Using 9 windows with threshold 3
INFO: Asset virtual-protocol: Using 7 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on pudgy-penguins: 342 points
INFO: Calculated initial values for DonchianEnsembleUSD on pepe: 951 points
INFO: Calculated initial values for DonchianEnsembleUSD on virtual-protocol: 697 points
INFO: Calculated initial values for DonchianEnsembleBTC on aixbt: 371 points
INFO: Calculated initial values for DonchianEnsembleBTC on pudgy-penguins: 342 points
INFO: Calculated initial values for DonchianEnsembleBTC on dog-go-to-the-moon-rune: 577 points
INFO: Calculated initial values for RSI_Bullish_USD on aixbt: 371 points
INFO: Calculated initial values for RSI_Bullish_BTC on aixbt: 371 points
INFO: Calculated initial values for RSI_Bullish_USD on pudgy-penguins: 342 points
INFO: Calculated initial values for TrendMomentumUSD on aixbt: 371 points
INFO: Calculated initial values for DonchianEnsembleBTC on virtual-protocol: 697 points
INFO: Calculated initial values for RSI_Bullish_BTC on pudgy-penguins: 342 points
INFO: Calculated initial values for TrendMomentumBTC on aixbt: 371 points
INFO: Calculated initial values for RSI_Bullish_USD on dog-go-to-the-moon-rune: 577 points
INFO: Calculated initial values for TrendMomentumUSD on pudgy-penguins: 342 points
INFO: Completed signal registration for aixbt in 5.21 seconds

Registering signals group 20/44:  20%|██        | 1/5 [00:05<00:22,  5.56s/it]

INFO: Calculated initial values for TrendMomentumBTC on pudgy-penguins: 342 points
INFO: Calculated initial values for DonchianEnsembleBTC on pepe: 951 points
INFO: Calculated initial values for RSI_Bullish_BTC on dog-go-to-the-moon-rune: 577 points
INFO: Completed signal registration for pudgy-penguins in 5.63 seconds

Registering signals group 20/44:  40%|████      | 2/5 [00:05<00:07,  2.43s/it]

INFO: Calculated initial values for RSI_Bullish_USD on virtual-protocol: 697 points
INFO: Calculated initial values for TrendMomentumUSD on dog-go-to-the-moon-rune: 577 points
INFO: Calculated initial values for RSI_Bullish_BTC on virtual-protocol: 697 points
INFO: Calculated initial values for TrendMomentumBTC on dog-go-to-the-moon-rune: 577 points
INFO: Calculated initial values for TrendMomentumUSD on virtual-protocol: 697 points
INFO: Completed signal registration for dog-go-to-the-moon-rune in 6.28 seconds

Registering signals group 20/44:  60%|██████    | 3/5 [00:06<00:03,  1.54s/it]

INFO: Calculated initial values for TrendMomentumBTC on virtual-protocol: 697 points
INFO: Calculated initial values for RSI_Bullish_USD on pepe: 951 points
INFO: Completed signal registration for virtual-protocol in 6.38 seconds
INFO: Calculated initial values for RSI_Bullish_BTC on pepe: 951 points
INFO: Calculated initial values for TrendMomentumUSD on pepe: 951 points
INFO: Calculated initial values for TrendMomentumBTC on pepe: 951 points
INFO: Completed signal registration for pepe in 6.78 seconds

Registering signals group 20/44: 100%|██████████| 5/5 [00:06<00:00,  1.36s/it]

INFO: Processing asset group 21/44 with 5 assets
INFO: Starting signal registration for aurory
INFO: Starting signal registration for illuvium

INFO: Starting signal registration for tether

Registering signals group 21/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for curve-dao-token
INFO: Registering 6 new signals for aurory
INFO: Starting signal registration for multibit
INFO: Registering 6 new signals for illuvium
INFO: Registering 6 new signals for tether
INFO: Registering 6 new signals for curve-dao-token
INFO: Registering 6 new signals for multibit
INFO: Asset multibit: Using 9 windows with threshold 3
INFO: Asset aurory: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on multibit: 735 points
INFO: Calculated initial values for DonchianEnsembleUSD on aurory: 1492 points
INFO: Asset illuvium: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on illuvium: 1699 points
INFO: Asset curve-dao-token: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on curve-dao-token: 1928 points
INFO: Calculated initial values for DonchianEnsembleBTC on multibit: 735 points
INFO: Calculated initial values for RSI_Bullish_USD on multibit: 735 points
INFO: Calculated initial values for RSI_Bullish_BTC on multibit: 735 points
INFO: Calculated initial values for TrendMomentumUSD on multibit: 735 points
INFO: Asset tether: Using 9 windows with threshold 3
INFO: Calculated initial values for TrendMomentumBTC on multibit: 735 points
INFO: Calculated initial values for DonchianEnsembleUSD on tether: 3925 points
INFO: Completed signal registration for multibit in 10.06 seconds

Registering signals group 21/44:  20%|██        | 1/5 [00:10<00:41, 10.31s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on aurory: 1492 points
INFO: Calculated initial values for DonchianEnsembleBTC on illuvium: 1699 points
INFO: Calculated initial values for DonchianEnsembleBTC on curve-dao-token: 1928 points
INFO: Calculated initial values for RSI_Bullish_USD on aurory: 1492 points
INFO: Calculated initial values for RSI_Bullish_BTC on aurory: 1492 points
INFO: Calculated initial values for RSI_Bullish_USD on illuvium: 1699 points
INFO: Calculated initial values for TrendMomentumUSD on aurory: 1492 points
INFO: Calculated initial values for RSI_Bullish_BTC on illuvium: 1699 points
INFO: Calculated initial values for TrendMomentumBTC on aurory: 1492 points
INFO: Completed signal registration for aurory in 16.99 seconds

Registering signals group 21/44:  40%|████      | 2/5 [00:17<00:24,  8.26s/it]

INFO: Calculated initial values for TrendMomentumUSD on illuvium: 1699 points
INFO: Calculated initial values for RSI_Bullish_USD on curve-dao-token: 1928 points
INFO: Calculated initial values for TrendMomentumBTC on illuvium: 1699 points
INFO: Completed signal registration for illuvium in 18.01 seconds
INFO: Calculated initial values for RSI_Bullish_BTC on curve-dao-token: 1928 points

Registering signals group 21/44:  60%|██████    | 3/5 [00:18<00:09,  4.94s/it]

INFO: Calculated initial values for TrendMomentumUSD on curve-dao-token: 1928 points
INFO: Calculated initial values for TrendMomentumBTC on curve-dao-token: 1928 points
INFO: Completed signal registration for curve-dao-token in 19.24 seconds

Registering signals group 21/44:  80%|████████  | 4/5 [00:19<00:03,  3.44s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on tether: 3925 points
INFO: Calculated initial values for RSI_Bullish_USD on tether: 3925 points
INFO: Calculated initial values for RSI_Bullish_BTC on tether: 3925 points
INFO: Calculated initial values for TrendMomentumUSD on tether: 3925 points
INFO: Calculated initial values for TrendMomentumBTC on tether: 3925 points
INFO: Completed signal registration for tether in 23.71 seconds

Registering signals group 21/44: 100%|██████████| 5/5 [00:23<00:00,  4.74s/it]

INFO: Processing asset group 22/44 with 5 assets
INFO: Starting signal registration for ethereum-classic

INFO: Starting signal registration for tron

Registering signals group 22/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for hypercycle
INFO: Starting signal registration for orbit-3
INFO: Starting signal registration for axelar
INFO: Registering 6 new signals for ethereum-classic
INFO: Registering 6 new signals for tron
INFO: Registering 6 new signals for hypercycle
INFO: Registering 6 new signals for orbit-3
INFO: Registering 6 new signals for axelar
INFO: Adapted windows for data length 351: [4, 9, 14, 29, 43, 73]
INFO: Asset orbit-3: Using 6 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on orbit-3: 351 points
INFO: Asset hypercycle: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on hypercycle: 930 points
INFO: Calculated initial values for DonchianEnsembleBTC on orbit-3: 351 points
INFO: Asset axelar: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on axelar: 1154 points
INFO: Calculated initial values for RSI_Bullish_USD on orbit-3: 351 points
INFO: Calculated initial values for RSI_Bullish_BTC on orbit-3: 351 points
INFO: Calculated initial values for TrendMomentumUSD on orbit-3: 351 points
INFO: Calculated initial values for TrendMomentumBTC on orbit-3: 351 points
INFO: Completed signal registration for orbit-3 in 4.65 seconds

Registering signals group 22/44:  20%|██        | 1/5 [00:05<00:20,  5.19s/it]

INFO: Asset tron: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on tron: 2937 points
INFO: Calculated initial values for DonchianEnsembleBTC on hypercycle: 930 points
INFO: Asset ethereum-classic: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on ethereum-classic: 3410 points
INFO: Calculated initial values for DonchianEnsembleBTC on axelar: 1154 points
INFO: Calculated initial values for RSI_Bullish_USD on hypercycle: 930 points
INFO: Calculated initial values for RSI_Bullish_BTC on hypercycle: 930 points
INFO: Calculated initial values for TrendMomentumUSD on hypercycle: 930 points
INFO: Calculated initial values for TrendMomentumBTC on hypercycle: 930 points
INFO: Calculated initial values for RSI_Bullish_USD on axelar: 1154 points
INFO: Completed signal registration for hypercycle in 538.45 seconds

Registering signals group 22/44:  40%|████      | 2/5 [08:58<15:47, 315.87s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on axelar: 1154 points
INFO: Calculated initial values for TrendMomentumUSD on axelar: 1154 points
INFO: Calculated initial values for TrendMomentumBTC on axelar: 1154 points
INFO: Completed signal registration for axelar in 541.62 seconds

Registering signals group 22/44:  60%|██████    | 3/5 [09:01<05:46, 173.11s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on tron: 2937 points
INFO: Calculated initial values for DonchianEnsembleBTC on ethereum-classic: 3410 points
INFO: Calculated initial values for RSI_Bullish_USD on tron: 2937 points
INFO: Calculated initial values for RSI_Bullish_BTC on tron: 2937 points
INFO: Calculated initial values for TrendMomentumUSD on tron: 2937 points
INFO: Calculated initial values for RSI_Bullish_USD on ethereum-classic: 3410 points
INFO: Calculated initial values for TrendMomentumBTC on tron: 2937 points
INFO: Completed signal registration for tron in 560.35 seconds

Registering signals group 22/44:  80%|████████  | 4/5 [09:20<01:52, 112.17s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on ethereum-classic: 3410 points
INFO: Calculated initial values for TrendMomentumUSD on ethereum-classic: 3410 points
INFO: Calculated initial values for TrendMomentumBTC on ethereum-classic: 3410 points
INFO: Completed signal registration for ethereum-classic in 561.50 seconds

Registering signals group 22/44: 100%|██████████| 5/5 [09:21<00:00, 112.30s/it]

INFO: Processing asset group 23/44 with 5 assets

INFO: Starting signal registration for metacade
INFO: Starting signal registration for eigenlayer

Registering signals group 23/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for celestia
INFO: Starting signal registration for worldcoin-wld
INFO: Starting signal registration for decentraland
INFO: Registering 6 new signals for metacade
INFO: Registering 6 new signals for eigenlayer
INFO: Registering 6 new signals for celestia
INFO: Registering 6 new signals for worldcoin-wld
INFO: Registering 6 new signals for decentraland
INFO: Adapted windows for data length 419: [5, 11, 17, 34, 52, 87]
INFO: Asset eigenlayer: Using 6 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on eigenlayer: 419 points
INFO: Asset celestia: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on celestia: 755 points
INFO: Asset metacade: Using 9 windows with threshold 3
INFO: Asset worldcoin-wld: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on metacade: 958 points
INFO: Calculated initial values for DonchianEnsembleUSD on worldcoin-wld: 854 points
INFO: Calculated initial values for DonchianEnsembleBTC on eigenlayer: 419 points
INFO: Calculated initial values for RSI_Bullish_USD on eigenlayer: 419 points
INFO: Calculated initial values for RSI_Bullish_BTC on eigenlayer: 419 points
INFO: Calculated initial values for TrendMomentumUSD on eigenlayer: 419 points
INFO: Calculated initial values for TrendMomentumBTC on eigenlayer: 419 points
INFO: Completed signal registration for eigenlayer in 8.79 seconds

Registering signals group 23/44:  20%|██        | 1/5 [00:09<00:36,  9.00s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on celestia: 755 points
INFO: Calculated initial values for DonchianEnsembleBTC on worldcoin-wld: 854 points
INFO: Calculated initial values for DonchianEnsembleBTC on metacade: 958 points
INFO: Calculated initial values for RSI_Bullish_USD on celestia: 755 points
INFO: Asset decentraland: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on decentraland: 2949 points
INFO: Calculated initial values for RSI_Bullish_BTC on celestia: 755 points
INFO: Calculated initial values for RSI_Bullish_USD on worldcoin-wld: 854 points
INFO: Calculated initial values for TrendMomentumUSD on celestia: 755 points
INFO: Calculated initial values for TrendMomentumBTC on celestia: 755 points
INFO: Calculated initial values for RSI_Bullish_BTC on worldcoin-wld: 854 points
INFO: Calculated initial values for RSI_Bullish_USD on metacade: 958 points
INFO: Completed signal registration for celestia in 12.48 seconds
INFO: Calculated initial values for TrendMomentumUSD on worldcoin-wld: 854 points

Registering signals group 23/44:  40%|████      | 2/5 [00:12<00:17,  5.92s/it]

INFO: Calculated initial values for TrendMomentumBTC on worldcoin-wld: 854 points
INFO: Calculated initial values for RSI_Bullish_BTC on metacade: 958 points
INFO: Completed signal registration for worldcoin-wld in 13.42 seconds

Registering signals group 23/44:  60%|██████    | 3/5 [00:13<00:07,  3.60s/it]

INFO: Calculated initial values for TrendMomentumUSD on metacade: 958 points
INFO: Calculated initial values for TrendMomentumBTC on metacade: 958 points
INFO: Completed signal registration for metacade in 14.13 seconds

Registering signals group 23/44:  80%|████████  | 4/5 [00:14<00:02,  2.42s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on decentraland: 2949 points
INFO: Calculated initial values for RSI_Bullish_USD on decentraland: 2949 points
INFO: Calculated initial values for RSI_Bullish_BTC on decentraland: 2949 points
INFO: Calculated initial values for TrendMomentumUSD on decentraland: 2949 points
INFO: Calculated initial values for TrendMomentumBTC on decentraland: 2949 points
INFO: Completed signal registration for decentraland in 18.48 seconds

Registering signals group 23/44: 100%|██████████| 5/5 [00:18<00:00,  3.70s/it]

INFO: Processing asset group 24/44 with 5 assets
INFO: Starting signal registration for myria
INFO: Starting signal registration for yield-guild-games
INFO: Starting signal registration for prisma-governance-token

Registering signals group 24/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for evan-2
INFO: Registering 6 new signals for myria
INFO: Starting signal registration for audius
INFO: Registering 6 new signals for yield-guild-games
INFO: Registering 6 new signals for prisma-governance-token
INFO: Registering 6 new signals for evan-2
INFO: Registering 6 new signals for audius
INFO: Adapted windows for data length 367: [5, 10, 15, 30, 45, 76]
INFO: Asset evan-2: Using 6 windows with threshold 3
INFO: Asset prisma-governance-token: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on evan-2: 367 points
INFO: Asset myria: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on prisma-governance-token: 753 points
INFO: Calculated initial values for DonchianEnsembleUSD on myria: 963 points
INFO: Asset yield-guild-games: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleBTC on evan-2: 367 points
INFO: Calculated initial values for DonchianEnsembleUSD on yield-guild-games: 1580 points
INFO: Calculated initial values for RSI_Bullish_USD on evan-2: 367 points
INFO: Calculated initial values for RSI_Bullish_BTC on evan-2: 367 points
INFO: Asset audius: Using 9 windows with threshold 3
INFO: Calculated initial values for TrendMomentumUSD on evan-2: 367 points
INFO: Calculated initial values for DonchianEnsembleUSD on audius: 1858 points
INFO: Calculated initial values for TrendMomentumBTC on evan-2: 367 points
INFO: Calculated initial values for DonchianEnsembleBTC on prisma-governance-token: 753 points
INFO: Completed signal registration for evan-2 in 5.26 seconds

Registering signals group 24/44:  20%|██        | 1/5 [00:05<00:22,  5.52s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on myria: 963 points
INFO: Calculated initial values for RSI_Bullish_USD on prisma-governance-token: 753 points
INFO: Calculated initial values for RSI_Bullish_BTC on prisma-governance-token: 753 points
INFO: Calculated initial values for RSI_Bullish_USD on myria: 963 points
INFO: Calculated initial values for TrendMomentumUSD on prisma-governance-token: 753 points
INFO: Calculated initial values for RSI_Bullish_BTC on myria: 963 points
INFO: Calculated initial values for TrendMomentumBTC on prisma-governance-token: 753 points
INFO: Completed signal registration for prisma-governance-token in 8.99 seconds
INFO: Calculated initial values for TrendMomentumUSD on myria: 963 points

Registering signals group 24/44:  40%|████      | 2/5 [00:09<00:13,  4.38s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on yield-guild-games: 1580 points
INFO: Calculated initial values for TrendMomentumBTC on myria: 963 points
INFO: Completed signal registration for myria in 9.68 seconds

Registering signals group 24/44:  60%|██████    | 3/5 [00:09<00:05,  2.67s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on audius: 1858 points
INFO: Calculated initial values for RSI_Bullish_USD on yield-guild-games: 1580 points
INFO: Calculated initial values for RSI_Bullish_BTC on yield-guild-games: 1580 points
INFO: Calculated initial values for TrendMomentumUSD on yield-guild-games: 1580 points
INFO: Calculated initial values for TrendMomentumBTC on yield-guild-games: 1580 points
INFO: Completed signal registration for yield-guild-games in 12.48 seconds

Registering signals group 24/44:  80%|████████  | 4/5 [00:12<00:02,  2.72s/it]

INFO: Calculated initial values for RSI_Bullish_USD on audius: 1858 points
INFO: Calculated initial values for RSI_Bullish_BTC on audius: 1858 points
INFO: Calculated initial values for TrendMomentumUSD on audius: 1858 points
INFO: Calculated initial values for TrendMomentumBTC on audius: 1858 points
INFO: Completed signal registration for audius in 13.05 seconds

Registering signals group 24/44: 100%|██████████| 5/5 [00:13<00:00,  2.62s/it]

INFO: Processing asset group 25/44 with 5 assets
INFO: Starting signal registration for terra-luna-2
INFO: Starting signal registration for ai16z

INFO: Starting signal registration for moonwell-artemis

Registering signals group 25/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for raydium
INFO: Registering 6 new signals for terra-luna-2
INFO: Starting signal registration for uniswap
INFO: Registering 6 new signals for ai16z
INFO: Registering 6 new signals for moonwell-artemis
INFO: Registering 6 new signals for raydium
INFO: Registering 6 new signals for uniswap
INFO: Adapted windows for data length 393: [5, 10, 16, 32, 49, 81]
INFO: Asset ai16z: Using 6 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on ai16z: 393 points
INFO: Asset terra-luna-2: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on terra-luna-2: 1276 points
INFO: Asset moonwell-artemis: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleBTC on ai16z: 393 points
INFO: Calculated initial values for DonchianEnsembleUSD on moonwell-artemis: 1250 points
INFO: Calculated initial values for RSI_Bullish_USD on ai16z: 393 points
INFO: Asset raydium: Using 9 windows with threshold 3
INFO: Calculated initial values for RSI_Bullish_BTC on ai16z: 393 points
INFO: Calculated initial values for DonchianEnsembleUSD on raydium: 1737 points
INFO: Calculated initial values for TrendMomentumUSD on ai16z: 393 points
INFO: Asset uniswap: Using 9 windows with threshold 3
INFO: Calculated initial values for TrendMomentumBTC on ai16z: 393 points
INFO: Calculated initial values for DonchianEnsembleUSD on uniswap: 1894 points
INFO: Completed signal registration for ai16z in 5.52 seconds

Registering signals group 25/44:  20%|██        | 1/5 [00:05<00:23,  5.97s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on terra-luna-2: 1276 points
INFO: Calculated initial values for DonchianEnsembleBTC on moonwell-artemis: 1250 points
INFO: Calculated initial values for RSI_Bullish_USD on terra-luna-2: 1276 points
INFO: Calculated initial values for RSI_Bullish_USD on moonwell-artemis: 1250 points
INFO: Calculated initial values for RSI_Bullish_BTC on terra-luna-2: 1276 points
INFO: Calculated initial values for DonchianEnsembleBTC on raydium: 1737 points
INFO: Calculated initial values for RSI_Bullish_BTC on moonwell-artemis: 1250 points
INFO: Calculated initial values for TrendMomentumUSD on terra-luna-2: 1276 points
INFO: Calculated initial values for TrendMomentumUSD on moonwell-artemis: 1250 points
INFO: Calculated initial values for TrendMomentumBTC on terra-luna-2: 1276 points
INFO: Completed signal registration for terra-luna-2 in 12.78 seconds

Registering signals group 25/44:  40%|████      | 2/5 [00:12<00:19,  6.49s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on uniswap: 1894 points
INFO: Calculated initial values for TrendMomentumBTC on moonwell-artemis: 1250 points
INFO: Completed signal registration for moonwell-artemis in 13.24 seconds

Registering signals group 25/44:  60%|██████    | 3/5 [00:13<00:07,  3.78s/it]

INFO: Calculated initial values for RSI_Bullish_USD on raydium: 1737 points
INFO: Calculated initial values for RSI_Bullish_BTC on raydium: 1737 points
INFO: Calculated initial values for RSI_Bullish_USD on uniswap: 1894 points
INFO: Calculated initial values for TrendMomentumUSD on raydium: 1737 points
INFO: Calculated initial values for RSI_Bullish_BTC on uniswap: 1894 points
INFO: Calculated initial values for TrendMomentumBTC on raydium: 1737 points
INFO: Completed signal registration for raydium in 15.09 seconds

Registering signals group 25/44:  80%|████████  | 4/5 [00:15<00:02,  2.97s/it]

INFO: Calculated initial values for TrendMomentumUSD on uniswap: 1894 points
INFO: Calculated initial values for TrendMomentumBTC on uniswap: 1894 points
INFO: Completed signal registration for uniswap in 15.38 seconds

Registering signals group 25/44: 100%|██████████| 5/5 [00:15<00:00,  3.09s/it]

INFO: Processing asset group 26/44 with 5 assets
INFO: Starting signal registration for my-neighbor-alice
INFO: Registering 6 new signals for my-neighbor-alice
INFO: Starting signal registration for sonic-3

INFO: Starting signal registration for heyanon
INFO: Registering 6 new signals for sonic-3
INFO: Starting signal registration for aave

Registering signals group 26/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for instadapp
INFO: Registering 6 new signals for heyanon
INFO: Registering 6 new signals for aave
INFO: Asset sonic-3: Using 6 windows with threshold 3
INFO: Registering 6 new signals for instadapp
INFO: Adapted windows for data length 332: [4, 9, 13, 27, 41, 69]
INFO: Calculated initial values for DonchianEnsembleUSD on sonic-3: 324 points
INFO: Asset heyanon: Using 6 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on heyanon: 332 points
INFO: Calculated initial values for DonchianEnsembleBTC on sonic-3: 324 points
INFO: Asset my-neighbor-alice: Using 9 windows with threshold 3
INFO: Calculated initial values for RSI_Bullish_USD on sonic-3: 324 points
INFO: Calculated initial values for DonchianEnsembleUSD on my-neighbor-alice: 1715 points
INFO: Calculated initial values for DonchianEnsembleBTC on heyanon: 332 points
INFO: Calculated initial values for RSI_Bullish_BTC on sonic-3: 324 points
INFO: Calculated initial values for TrendMomentumUSD on sonic-3: 324 points
INFO: Asset instadapp: Using 9 windows with threshold 3
INFO: Calculated initial values for RSI_Bullish_USD on heyanon: 332 points
INFO: Asset aave: Using 9 windows with threshold 3
INFO: Calculated initial values for TrendMomentumBTC on sonic-3: 324 points
INFO: Calculated initial values for DonchianEnsembleUSD on instadapp: 1622 points
INFO: Calculated initial values for DonchianEnsembleUSD on aave: 1878 points
INFO: Calculated initial values for RSI_Bullish_BTC on heyanon: 332 points
INFO: Completed signal registration for sonic-3 in 4.66 seconds

Registering signals group 26/44:  20%|██        | 1/5 [00:04<00:19,  4.90s/it]

INFO: Calculated initial values for TrendMomentumUSD on heyanon: 332 points
INFO: Calculated initial values for TrendMomentumBTC on heyanon: 332 points
INFO: Completed signal registration for heyanon in 5.74 seconds

Registering signals group 26/44:  40%|████      | 2/5 [00:05<00:07,  2.50s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on my-neighbor-alice: 1715 points
INFO: Calculated initial values for DonchianEnsembleBTC on instadapp: 1622 points
INFO: Calculated initial values for DonchianEnsembleBTC on aave: 1878 points
INFO: Calculated initial values for RSI_Bullish_USD on my-neighbor-alice: 1715 points
INFO: Calculated initial values for RSI_Bullish_BTC on my-neighbor-alice: 1715 points
INFO: Calculated initial values for RSI_Bullish_USD on instadapp: 1622 points
INFO: Calculated initial values for TrendMomentumUSD on my-neighbor-alice: 1715 points
INFO: Calculated initial values for RSI_Bullish_BTC on instadapp: 1622 points
INFO: Calculated initial values for TrendMomentumBTC on my-neighbor-alice: 1715 points
INFO: Calculated initial values for TrendMomentumUSD on instadapp: 1622 points
INFO: Completed signal registration for my-neighbor-alice in 22.00 seconds
INFO: Calculated initial values for RSI_Bullish_USD on aave: 1878 points

Registering signals group 26/44:  60%|██████    | 3/5 [00:21<00:17,  8.68s/it]

INFO: Calculated initial values for TrendMomentumBTC on instadapp: 1622 points
INFO: Completed signal registration for instadapp in 21.85 seconds

Registering signals group 26/44:  80%|████████  | 4/5 [00:22<00:05,  5.35s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on aave: 1878 points
INFO: Calculated initial values for TrendMomentumUSD on aave: 1878 points
INFO: Calculated initial values for TrendMomentumBTC on aave: 1878 points
INFO: Completed signal registration for aave in 22.45 seconds

Registering signals group 26/44: 100%|██████████| 5/5 [00:22<00:00,  4.49s/it]

INFO: Processing asset group 27/44 with 5 assets
INFO: Starting signal registration for guild-of-guardians
INFO: Starting signal registration for coredaoorg

INFO: Starting signal registration for solayer
INFO: Starting signal registration for official-trump

Registering signals group 27/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 6 new signals for guild-of-guardians
INFO: Starting signal registration for gigachad-2
INFO: Registering 6 new signals for coredaoorg
INFO: Registering 6 new signals for solayer
INFO: Registering 6 new signals for official-trump
INFO: Registering 6 new signals for gigachad-2
INFO: Adapted windows for data length 286: [3, 7, 11, 23, 35, 59]
INFO: Adapted windows for data length 310: [4, 8, 12, 25, 38, 64]
INFO: Adapted windows for data length 672: [4, 9, 18, 28, 56, 84, 140]
INFO: Asset solayer: Using 6 windows with threshold 3
INFO: Asset official-trump: Using 6 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on solayer: 286 points
INFO: Calculated initial values for DonchianEnsembleUSD on official-trump: 310 points
INFO: Asset gigachad-2: Using 7 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on gigachad-2: 672 points
INFO: Asset coredaoorg: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on coredaoorg: 1020 points
INFO: Calculated initial values for DonchianEnsembleBTC on solayer: 286 points
INFO: Asset guild-of-guardians: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleBTC on official-trump: 310 points
INFO: Calculated initial values for DonchianEnsembleUSD on guild-of-guardians: 1433 points
INFO: Calculated initial values for RSI_Bullish_USD on solayer: 286 points
INFO: Calculated initial values for RSI_Bullish_BTC on solayer: 286 points
INFO: Calculated initial values for RSI_Bullish_USD on official-trump: 310 points
INFO: Calculated initial values for TrendMomentumUSD on solayer: 286 points
INFO: Calculated initial values for RSI_Bullish_BTC on official-trump: 310 points
INFO: Calculated initial values for TrendMomentumBTC on solayer: 286 points
INFO: Completed signal registration for solayer in 5.57 seconds
INFO: Calculated initial values for DonchianEnsembleBTC on gigachad-2: 672 points

Registering signals group 27/44:  20%|██        | 1/5 [00:05<00:22,  5.65s/it]

INFO: Calculated initial values for TrendMomentumUSD on official-trump: 310 points
INFO: Calculated initial values for TrendMomentumBTC on official-trump: 310 points
INFO: Completed signal registration for official-trump in 6.62 seconds

Registering signals group 27/44:  40%|████      | 2/5 [00:06<00:09,  3.01s/it]

INFO: Calculated initial values for RSI_Bullish_USD on gigachad-2: 672 points
INFO: Calculated initial values for RSI_Bullish_BTC on gigachad-2: 672 points
INFO: Calculated initial values for TrendMomentumUSD on gigachad-2: 672 points
INFO: Calculated initial values for DonchianEnsembleBTC on coredaoorg: 1020 points
INFO: Calculated initial values for TrendMomentumBTC on gigachad-2: 672 points
INFO: Completed signal registration for gigachad-2 in 11.03 seconds

Registering signals group 27/44:  60%|██████    | 3/5 [00:11<00:07,  3.67s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on guild-of-guardians: 1433 points
INFO: Calculated initial values for RSI_Bullish_USD on coredaoorg: 1020 points
INFO: Calculated initial values for RSI_Bullish_BTC on coredaoorg: 1020 points
INFO: Calculated initial values for TrendMomentumUSD on coredaoorg: 1020 points
INFO: Calculated initial values for TrendMomentumBTC on coredaoorg: 1020 points
INFO: Completed signal registration for coredaoorg in 14.74 seconds

Registering signals group 27/44:  80%|████████  | 4/5 [00:14<00:03,  3.61s/it]

INFO: Calculated initial values for RSI_Bullish_USD on guild-of-guardians: 1433 points
INFO: Calculated initial values for RSI_Bullish_BTC on guild-of-guardians: 1433 points
INFO: Calculated initial values for TrendMomentumUSD on guild-of-guardians: 1433 points
INFO: Calculated initial values for TrendMomentumBTC on guild-of-guardians: 1433 points
INFO: Completed signal registration for guild-of-guardians in 18.29 seconds

Registering signals group 27/44: 100%|██████████| 5/5 [00:18<00:00,  3.66s/it]

INFO: Processing asset group 28/44 with 5 assets
INFO: Starting signal registration for rainbow-token-2
INFO: Starting signal registration for monero
INFO: Registering 6 new signals for rainbow-token-2
INFO: Starting signal registration for prometeus

Registering signals group 28/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for wibx
INFO: Starting signal registration for echelon-prime
INFO: Registering 6 new signals for monero
INFO: Registering 6 new signals for prometeus
INFO: Registering 6 new signals for wibx
INFO: Registering 6 new signals for echelon-prime
INFO: Asset echelon-prime: Using 9 windows with threshold 3
INFO: Asset rainbow-token-2: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on echelon-prime: 998 points
INFO: Calculated initial values for DonchianEnsembleUSD on rainbow-token-2: 1348 points
INFO: Asset wibx: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on wibx: 2047 points
INFO: Asset prometeus: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on prometeus: 2341 points
INFO: Calculated initial values for DonchianEnsembleBTC on echelon-prime: 998 points
INFO: Calculated initial values for DonchianEnsembleBTC on rainbow-token-2: 1348 points
INFO: Asset monero: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on monero: 4205 points
INFO: Calculated initial values for RSI_Bullish_USD on echelon-prime: 998 points
INFO: Calculated initial values for RSI_Bullish_BTC on echelon-prime: 998 points
INFO: Calculated initial values for TrendMomentumUSD on echelon-prime: 998 points
INFO: Calculated initial values for TrendMomentumBTC on echelon-prime: 998 points
INFO: Completed signal registration for echelon-prime in 18.75 seconds

Registering signals group 28/44:  20%|██        | 1/5 [00:19<01:16, 19.04s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on wibx: 2047 points
ERROR: Error calculating RSI Bullish signal for rainbow-token-2: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
INFO: Calculated initial values for RSI_Bullish_USD on rainbow-token-2: 1348 points
INFO: Calculated initial values for DonchianEnsembleBTC on prometeus: 2341 points
INFO: Calculated initial values for RSI_Bullish_USD on wibx: 2047 points
INFO: Calculated initial values for RSI_Bullish_BTC on rainbow-token-2: 1348 points
INFO: Calculated initial values for RSI_Bullish_BTC on wibx: 2047 points
INFO: Calculated initial values for TrendMomentumUSD on wibx: 2047 points
INFO: Calculated initial values for TrendMomentumBTC on wibx: 2047 points
INFO: Completed signal registration for wibx in 34.25 seconds
INFO: Calculated initial values for RSI_Bullish_USD on prometeus: 2341 points

Registering signals group 28/44:  40%|████      | 2/5 [00:34<00:50, 16.83s/it]

ERROR: Error calculating Trend Momentum signal for rainbow-token-2: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
INFO: Calculated initial values for TrendMomentumUSD on rainbow-token-2: 1348 points
INFO: Calculated initial values for RSI_Bullish_BTC on prometeus: 2341 points
INFO: Calculated initial values for TrendMomentumUSD on prometeus: 2341 points
INFO: Calculated initial values for TrendMomentumBTC on rainbow-token-2: 1348 points
INFO: Calculated initial values for TrendMomentumBTC on prometeus: 2341 points
INFO: Completed signal registration for prometeus in 38.50 seconds

Registering signals group 28/44:  60%|██████    | 3/5 [00:38<00:22, 11.08s/it]

INFO: Completed signal registration for rainbow-token-2 in 39.14 seconds

Registering signals group 28/44:  80%|████████  | 4/5 [00:39<00:06,  6.89s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on monero: 4205 points
INFO: Calculated initial values for RSI_Bullish_USD on monero: 4205 points
INFO: Calculated initial values for RSI_Bullish_BTC on monero: 4205 points
INFO: Calculated initial values for TrendMomentumUSD on monero: 4205 points
INFO: Calculated initial values for TrendMomentumBTC on monero: 4205 points
INFO: Completed signal registration for monero in 44.64 seconds

Registering signals group 28/44: 100%|██████████| 5/5 [00:44<00:00,  8.90s/it]

INFO: Processing asset group 29/44 with 5 assets

INFO: Starting signal registration for gmx
INFO: Registering 6 new signals for gmx
INFO: Starting signal registration for plume
INFO: Starting signal registration for binancecoin

Registering signals group 29/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for syrup
INFO: Starting signal registration for cat-in-a-dogs-world
INFO: Registering 6 new signals for plume
INFO: Registering 6 new signals for binancecoin
INFO: Registering 6 new signals for syrup
INFO: Registering 6 new signals for cat-in-a-dogs-world
INFO: Adapted windows for data length 307: [4, 8, 12, 25, 38, 63]
INFO: Adapted windows for data length 376: [5, 10, 15, 31, 47, 78]
INFO: Adapted windows for data length 608: [4, 8, 16, 25, 50, 76, 126]
INFO: Asset plume: Using 6 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on plume: 307 points
INFO: Asset syrup: Using 6 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on syrup: 376 points
INFO: Asset cat-in-a-dogs-world: Using 7 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on cat-in-a-dogs-world: 608 points
INFO: Calculated initial values for DonchianEnsembleBTC on plume: 307 points
INFO: Calculated initial values for DonchianEnsembleBTC on syrup: 376 points
INFO: Asset gmx: Using 9 windows with threshold 3
INFO: Calculated initial values for RSI_Bullish_USD on plume: 307 points
INFO: Calculated initial values for DonchianEnsembleUSD on gmx: 1533 points
INFO: Calculated initial values for RSI_Bullish_BTC on plume: 307 points
INFO: Calculated initial values for RSI_Bullish_USD on syrup: 376 points
INFO: Calculated initial values for TrendMomentumUSD on plume: 307 points
INFO: Calculated initial values for TrendMomentumBTC on plume: 307 points
INFO: Calculated initial values for RSI_Bullish_BTC on syrup: 376 points
INFO: Completed signal registration for plume in 6.07 seconds

Registering signals group 29/44:  20%|██        | 1/5 [00:06<00:24,  6.22s/it]

INFO: Calculated initial values for TrendMomentumUSD on syrup: 376 points
INFO: Calculated initial values for DonchianEnsembleBTC on cat-in-a-dogs-world: 608 points
INFO: Calculated initial values for TrendMomentumBTC on syrup: 376 points
INFO: Completed signal registration for syrup in 6.92 seconds

Registering signals group 29/44:  40%|████      | 2/5 [00:07<00:09,  3.09s/it]

INFO: Calculated initial values for RSI_Bullish_USD on cat-in-a-dogs-world: 608 points
INFO: Calculated initial values for RSI_Bullish_BTC on cat-in-a-dogs-world: 608 points
INFO: Calculated initial values for TrendMomentumUSD on cat-in-a-dogs-world: 608 points
INFO: Asset binancecoin: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on binancecoin: 2991 points
INFO: Calculated initial values for TrendMomentumBTC on cat-in-a-dogs-world: 608 points
INFO: Completed signal registration for cat-in-a-dogs-world in 9.53 seconds

Registering signals group 29/44:  60%|██████    | 3/5 [00:09<00:05,  2.88s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on gmx: 1533 points
INFO: Calculated initial values for RSI_Bullish_USD on gmx: 1533 points
INFO: Calculated initial values for RSI_Bullish_BTC on gmx: 1533 points
INFO: Calculated initial values for TrendMomentumUSD on gmx: 1533 points
INFO: Calculated initial values for TrendMomentumBTC on gmx: 1533 points
INFO: Completed signal registration for gmx in 15.87 seconds

Registering signals group 29/44:  80%|████████  | 4/5 [00:15<00:04,  4.12s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on binancecoin: 2991 points
INFO: Calculated initial values for RSI_Bullish_USD on binancecoin: 2991 points
INFO: Calculated initial values for RSI_Bullish_BTC on binancecoin: 2991 points
INFO: Calculated initial values for TrendMomentumUSD on binancecoin: 2991 points
INFO: Calculated initial values for TrendMomentumBTC on binancecoin: 2991 points
INFO: Completed signal registration for binancecoin in 20.78 seconds

Registering signals group 29/44: 100%|██████████| 5/5 [00:20<00:00,  4.15s/it]

INFO: Processing asset group 30/44 with 5 assets
INFO: Starting signal registration for star-atlas-dao
INFO: Starting signal registration for wrapped-nxm
INFO: Registering 6 new signals for star-atlas-dao

Registering signals group 30/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for perpetual-protocol
INFO: Starting signal registration for maker
INFO: Starting signal registration for render-token
INFO: Registering 6 new signals for wrapped-nxm
INFO: Registering 6 new signals for perpetual-protocol
INFO: Registering 6 new signals for maker
INFO: Registering 6 new signals for render-token
INFO: Asset star-atlas-dao: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on star-atlas-dao: 1544 points
INFO: Asset wrapped-nxm: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on wrapped-nxm: 1946 points
INFO: Asset perpetual-protocol: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on perpetual-protocol: 1902 points
INFO: Asset render-token: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on render-token: 1988 points
INFO: Asset maker: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on maker: 2896 points
INFO: Calculated initial values for DonchianEnsembleBTC on star-atlas-dao: 1544 points
INFO: Calculated initial values for DonchianEnsembleBTC on perpetual-protocol: 1902 points
INFO: Calculated initial values for DonchianEnsembleBTC on wrapped-nxm: 1946 points
INFO: Calculated initial values for RSI_Bullish_USD on star-atlas-dao: 1544 points
INFO: Calculated initial values for DonchianEnsembleBTC on render-token: 1988 points
INFO: Calculated initial values for RSI_Bullish_BTC on star-atlas-dao: 1544 points
INFO: Calculated initial values for TrendMomentumUSD on star-atlas-dao: 1544 points
INFO: Calculated initial values for TrendMomentumBTC on star-atlas-dao: 1544 points
INFO: Completed signal registration for star-atlas-dao in 32.37 seconds

Registering signals group 30/44:  20%|██        | 1/5 [00:32<02:10, 32.58s/it]

INFO: Calculated initial values for RSI_Bullish_USD on perpetual-protocol: 1902 points
INFO: Calculated initial values for RSI_Bullish_USD on wrapped-nxm: 1946 points
INFO: Calculated initial values for RSI_Bullish_USD on render-token: 1988 points
INFO: Calculated initial values for DonchianEnsembleBTC on maker: 2896 points
INFO: Calculated initial values for RSI_Bullish_BTC on perpetual-protocol: 1902 points
INFO: Calculated initial values for RSI_Bullish_BTC on wrapped-nxm: 1946 points
INFO: Calculated initial values for RSI_Bullish_BTC on render-token: 1988 points
INFO: Calculated initial values for TrendMomentumUSD on perpetual-protocol: 1902 points
INFO: Calculated initial values for TrendMomentumUSD on wrapped-nxm: 1946 points
INFO: Calculated initial values for TrendMomentumUSD on render-token: 1988 points
INFO: Calculated initial values for TrendMomentumBTC on perpetual-protocol: 1902 points
INFO: Calculated initial values for TrendMomentumBTC on wrapped-nxm: 1946 points
INFO: Completed signal registration for perpetual-protocol in 36.25 seconds

Registering signals group 30/44:  40%|████      | 2/5 [00:36<00:46, 15.64s/it]

INFO: Completed signal registration for wrapped-nxm in 36.52 seconds
INFO: Calculated initial values for TrendMomentumBTC on render-token: 1988 points

Registering signals group 30/44:  60%|██████    | 3/5 [00:36<00:17,  8.58s/it]

INFO: Completed signal registration for render-token in 36.64 seconds

Registering signals group 30/44:  80%|████████  | 4/5 [00:36<00:05,  5.31s/it]

INFO: Calculated initial values for RSI_Bullish_USD on maker: 2896 points
INFO: Calculated initial values for RSI_Bullish_BTC on maker: 2896 points
INFO: Calculated initial values for TrendMomentumUSD on maker: 2896 points
INFO: Calculated initial values for TrendMomentumBTC on maker: 2896 points
INFO: Completed signal registration for maker in 39.54 seconds

Registering signals group 30/44: 100%|██████████| 5/5 [00:39<00:00,  7.92s/it]

INFO: Processing asset group 31/44 with 5 assets
INFO: Starting signal registration for zcash

INFO: Starting signal registration for bitcoin-cash
INFO: Starting signal registration for axie-infinity
INFO: Registering 6 new signals for zcash

Registering signals group 31/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for arbdoge-ai
INFO: Registering 6 new signals for bitcoin-cash
INFO: Starting signal registration for lagrange
INFO: Registering 6 new signals for axie-infinity
INFO: Registering 6 new signals for arbdoge-ai
INFO: Registering 6 new signals for lagrange
INFO: Adapted windows for data length 173: [4, 7, 14, 21, 36]
INFO: Asset lagrange: Using 5 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on lagrange: 173 points
INFO: Calculated initial values for DonchianEnsembleBTC on lagrange: 173 points
INFO: Calculated initial values for RSI_Bullish_USD on lagrange: 173 points
INFO: Calculated initial values for RSI_Bullish_BTC on lagrange: 173 points
INFO: Asset arbdoge-ai: Using 9 windows with threshold 3
INFO: Calculated initial values for TrendMomentumUSD on lagrange: 173 points
INFO: Calculated initial values for DonchianEnsembleUSD on arbdoge-ai: 951 points
INFO: Calculated initial values for TrendMomentumBTC on lagrange: 173 points
INFO: Completed signal registration for lagrange in 3.91 seconds

Registering signals group 31/44:  20%|██        | 1/5 [00:04<00:17,  4.39s/it]

INFO: Asset axie-infinity: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on axie-infinity: 1846 points
INFO: Asset bitcoin-cash: Using 9 windows with threshold 3
INFO: Asset zcash: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on bitcoin-cash: 3036 points
INFO: Calculated initial values for DonchianEnsembleUSD on zcash: 3313 points
INFO: Calculated initial values for DonchianEnsembleBTC on arbdoge-ai: 951 points
INFO: Calculated initial values for RSI_Bullish_USD on arbdoge-ai: 951 points
INFO: Calculated initial values for RSI_Bullish_BTC on arbdoge-ai: 951 points
INFO: Calculated initial values for TrendMomentumUSD on arbdoge-ai: 951 points
INFO: Calculated initial values for TrendMomentumBTC on arbdoge-ai: 951 points
INFO: Completed signal registration for arbdoge-ai in 16.31 seconds
INFO: Calculated initial values for DonchianEnsembleBTC on axie-infinity: 1846 points

Registering signals group 31/44:  40%|████      | 2/5 [00:16<00:26,  8.97s/it]

INFO: Calculated initial values for RSI_Bullish_USD on axie-infinity: 1846 points
INFO: Calculated initial values for RSI_Bullish_BTC on axie-infinity: 1846 points
INFO: Calculated initial values for TrendMomentumUSD on axie-infinity: 1846 points
INFO: Calculated initial values for DonchianEnsembleBTC on bitcoin-cash: 3036 points
INFO: Calculated initial values for TrendMomentumBTC on axie-infinity: 1846 points
INFO: Completed signal registration for axie-infinity in 24.55 seconds

Registering signals group 31/44:  60%|██████    | 3/5 [00:24<00:17,  8.52s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on zcash: 3313 points
INFO: Calculated initial values for RSI_Bullish_USD on bitcoin-cash: 3036 points
INFO: Calculated initial values for RSI_Bullish_BTC on bitcoin-cash: 3036 points
INFO: Calculated initial values for RSI_Bullish_USD on zcash: 3313 points
INFO: Calculated initial values for TrendMomentumUSD on bitcoin-cash: 3036 points
INFO: Calculated initial values for RSI_Bullish_BTC on zcash: 3313 points
INFO: Calculated initial values for TrendMomentumBTC on bitcoin-cash: 3036 points
INFO: Completed signal registration for bitcoin-cash in 29.66 seconds

Registering signals group 31/44:  80%|████████  | 4/5 [00:29<00:07,  7.18s/it]

INFO: Calculated initial values for TrendMomentumUSD on zcash: 3313 points
INFO: Calculated initial values for TrendMomentumBTC on zcash: 3313 points
INFO: Completed signal registration for zcash in 30.46 seconds

Registering signals group 31/44: 100%|██████████| 5/5 [00:30<00:00,  6.08s/it]

INFO: Processing asset group 32/44 with 5 assets
INFO: Starting signal registration for yne

INFO: Starting signal registration for constitutiondao

Registering signals group 32/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for floki
INFO: Starting signal registration for snek
INFO: Starting signal registration for bigcoin-2
INFO: Registering 6 new signals for yne
INFO: Registering 6 new signals for constitutiondao
INFO: Registering 6 new signals for floki
INFO: Registering 6 new signals for snek
INFO: Registering 6 new signals for bigcoin-2
INFO: Adapted windows for data length 336: [4, 9, 14, 28, 42, 70]
INFO: Adapted windows for data length 222: [3, 6, 9, 18, 27, 46]
INFO: Asset yne: Using 6 windows with threshold 3
INFO: Asset bigcoin-2: Using 6 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on yne: 336 points
INFO: Calculated initial values for DonchianEnsembleUSD on bigcoin-2: 222 points
INFO: Asset snek: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on snek: 917 points
INFO: Calculated initial values for DonchianEnsembleBTC on bigcoin-2: 222 points
INFO: Calculated initial values for DonchianEnsembleBTC on yne: 336 points
INFO: Asset constitutiondao: Using 9 windows with threshold 3
INFO: Calculated initial values for RSI_Bullish_USD on bigcoin-2: 222 points
INFO: Calculated initial values for DonchianEnsembleUSD on constitutiondao: 1466 points
INFO: Calculated initial values for RSI_Bullish_USD on yne: 336 points
INFO: Calculated initial values for RSI_Bullish_BTC on bigcoin-2: 222 points
INFO: Asset floki: Using 9 windows with threshold 3
INFO: Calculated initial values for RSI_Bullish_BTC on yne: 336 points
INFO: Calculated initial values for TrendMomentumUSD on bigcoin-2: 222 points
INFO: Calculated initial values for DonchianEnsembleUSD on floki: 1610 points
INFO: Calculated initial values for TrendMomentumUSD on yne: 336 points
INFO: Calculated initial values for TrendMomentumBTC on bigcoin-2: 222 points
INFO: Calculated initial values for TrendMomentumBTC on yne: 336 points
INFO: Completed signal registration for bigcoin-2 in 4.82 seconds
INFO: Completed signal registration for yne in 5.01 seconds

Registering signals group 32/44:  20%|██        | 1/5 [00:05<00:20,  5.11s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on snek: 917 points

Registering signals group 32/44:  40%|████      | 2/5 [00:05<00:06,  2.19s/it]

INFO: Calculated initial values for RSI_Bullish_USD on snek: 917 points
INFO: Calculated initial values for RSI_Bullish_BTC on snek: 917 points
INFO: Calculated initial values for DonchianEnsembleBTC on constitutiondao: 1466 points
INFO: Calculated initial values for TrendMomentumUSD on snek: 917 points
INFO: Calculated initial values for TrendMomentumBTC on snek: 917 points
INFO: Completed signal registration for snek in 8.33 seconds

Registering signals group 32/44:  60%|██████    | 3/5 [00:08<00:05,  2.65s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on floki: 1610 points
INFO: Calculated initial values for RSI_Bullish_USD on constitutiondao: 1466 points
INFO: Calculated initial values for RSI_Bullish_BTC on constitutiondao: 1466 points
INFO: Calculated initial values for TrendMomentumUSD on constitutiondao: 1466 points
INFO: Calculated initial values for TrendMomentumBTC on constitutiondao: 1466 points
INFO: Calculated initial values for RSI_Bullish_USD on floki: 1610 points
INFO: Completed signal registration for constitutiondao in 10.38 seconds

Registering signals group 32/44:  80%|████████  | 4/5 [00:10<00:02,  2.37s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on floki: 1610 points
INFO: Calculated initial values for TrendMomentumUSD on floki: 1610 points
INFO: Calculated initial values for TrendMomentumBTC on floki: 1610 points
INFO: Completed signal registration for floki in 10.76 seconds

Registering signals group 32/44: 100%|██████████| 5/5 [00:10<00:00,  2.15s/it]

INFO: Processing asset group 33/44 with 5 assets
INFO: Starting signal registration for kamino

INFO: Starting signal registration for vela-token

Registering signals group 33/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for ripple
INFO: Starting signal registration for equilibria-finance
INFO: Starting signal registration for griffain
INFO: Registering 6 new signals for kamino
INFO: Registering 6 new signals for vela-token
INFO: Registering 6 new signals for ripple
INFO: Registering 6 new signals for equilibria-finance
INFO: Registering 6 new signals for griffain
INFO: Adapted windows for data length 573: [3, 7, 15, 23, 47, 71, 119]
INFO: Adapted windows for data length 353: [4, 9, 14, 29, 44, 73]
INFO: Asset griffain: Using 6 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on griffain: 353 points
INFO: Asset kamino: Using 7 windows with threshold 3
INFO: Asset equilibria-finance: Using 9 windows with threshold 3
INFO: Asset vela-token: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on kamino: 573 points
INFO: Calculated initial values for DonchianEnsembleUSD on equilibria-finance: 901 points
INFO: Calculated initial values for DonchianEnsembleUSD on vela-token: 1023 points
INFO: Calculated initial values for DonchianEnsembleBTC on griffain: 353 points
INFO: Calculated initial values for RSI_Bullish_USD on griffain: 353 points
INFO: Calculated initial values for RSI_Bullish_BTC on griffain: 353 points
INFO: Calculated initial values for TrendMomentumUSD on griffain: 353 points
INFO: Calculated initial values for DonchianEnsembleBTC on kamino: 573 points
INFO: Calculated initial values for TrendMomentumBTC on griffain: 353 points
INFO: Completed signal registration for griffain in 6.23 seconds

Registering signals group 33/44:  20%|██        | 1/5 [00:06<00:25,  6.40s/it]

INFO: Calculated initial values for RSI_Bullish_USD on kamino: 573 points
INFO: Calculated initial values for DonchianEnsembleBTC on equilibria-finance: 901 points
INFO: Calculated initial values for RSI_Bullish_BTC on kamino: 573 points
INFO: Calculated initial values for TrendMomentumUSD on kamino: 573 points
INFO: Calculated initial values for DonchianEnsembleBTC on vela-token: 1023 points
INFO: Calculated initial values for TrendMomentumBTC on kamino: 573 points
INFO: Completed signal registration for kamino in 9.71 seconds

Registering signals group 33/44:  40%|████      | 2/5 [00:09<00:14,  4.68s/it]

INFO: Calculated initial values for RSI_Bullish_USD on equilibria-finance: 901 points
INFO: Calculated initial values for RSI_Bullish_BTC on equilibria-finance: 901 points
INFO: Calculated initial values for TrendMomentumUSD on equilibria-finance: 901 points
ERROR: Error calculating RSI Bullish signal for vela-token: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
INFO: Calculated initial values for RSI_Bullish_USD on vela-token: 1023 points
INFO: Calculated initial values for TrendMomentumBTC on equilibria-finance: 901 points
INFO: Asset ripple: Using 9 windows with threshold 3
INFO: Completed signal registration for equilibria-finance in 11.46 seconds

Registering signals group 33/44:  60%|██████    | 3/5 [00:11<00:06,  3.27s/it]

INFO: Calculated initial values for DonchianEnsembleUSD on ripple: 4495 points
INFO: Calculated initial values for RSI_Bullish_BTC on vela-token: 1023 points
ERROR: Error calculating Trend Momentum signal for vela-token: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
INFO: Calculated initial values for TrendMomentumUSD on vela-token: 1023 points
INFO: Calculated initial values for TrendMomentumBTC on vela-token: 1023 points
INFO: Completed signal registration for vela-token in 13.25 seconds

Registering signals group 33/44:  80%|████████  | 4/5 [00:13<00:02,  2.70s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on ripple: 4495 points
INFO: Calculated initial values for RSI_Bullish_USD on ripple: 4495 points
INFO: Calculated initial values for RSI_Bullish_BTC on ripple: 4495 points
INFO: Calculated initial values for TrendMomentumUSD on ripple: 4495 points
INFO: Calculated initial values for TrendMomentumBTC on ripple: 4495 points
INFO: Completed signal registration for ripple in 25.54 seconds

Registering signals group 33/44: 100%|██████████| 5/5 [00:25<00:00,  5.11s/it]

INFO: Processing asset group 34/44 with 5 assets
INFO: Starting signal registration for mamo
INFO: Starting signal registration for eos
INFO: Starting signal registration for hyperliquid

Registering signals group 34/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for alchemist-ai
INFO: Registering 6 new signals for mamo
INFO: Starting signal registration for bittensor
INFO: Registering 6 new signals for bittensor
INFO: Registering 6 new signals for hyperliquid
INFO: Registering 6 new signals for alchemist-ai
INFO: Adapted windows for data length 187: [5, 7, 15, 23, 38]
INFO: Registering 6 new signals for eos
INFO: Adapted windows for data length 361: [5, 10, 15, 30, 45, 75]
INFO: Adapted windows for data length 358: [4, 9, 14, 29, 44, 74]
INFO: Asset mamo: Using 5 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on mamo: 187 points
INFO: Asset alchemist-ai: Using 6 windows with threshold 3
INFO: Asset hyperliquid: Using 6 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on alchemist-ai: 358 points
INFO: Calculated initial values for DonchianEnsembleBTC on mamo: 187 points
INFO: Calculated initial values for DonchianEnsembleUSD on hyperliquid: 361 points
INFO: Asset bittensor: Using 9 windows with threshold 3
INFO: Calculated initial values for RSI_Bullish_USD on mamo: 187 points
INFO: Calculated initial values for DonchianEnsembleUSD on bittensor: 997 points
INFO: Calculated initial values for DonchianEnsembleBTC on alchemist-ai: 358 points
INFO: Calculated initial values for RSI_Bullish_BTC on mamo: 187 points
INFO: Calculated initial values for DonchianEnsembleBTC on hyperliquid: 361 points
INFO: Calculated initial values for TrendMomentumUSD on mamo: 187 points
INFO: Calculated initial values for RSI_Bullish_USD on alchemist-ai: 358 points
INFO: Calculated initial values for TrendMomentumBTC on mamo: 187 points
INFO: Calculated initial values for RSI_Bullish_USD on hyperliquid: 361 points
INFO: Calculated initial values for RSI_Bullish_BTC on alchemist-ai: 358 points
INFO: Completed signal registration for mamo in 3.47 seconds

Registering signals group 34/44:  20%|██        | 1/5 [00:03<00:15,  3.90s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on hyperliquid: 361 points
INFO: Calculated initial values for TrendMomentumUSD on alchemist-ai: 358 points
INFO: Calculated initial values for TrendMomentumUSD on hyperliquid: 361 points
INFO: Calculated initial values for TrendMomentumBTC on alchemist-ai: 358 points
INFO: Calculated initial values for TrendMomentumBTC on hyperliquid: 361 points
INFO: Completed signal registration for alchemist-ai in 4.48 seconds
INFO: Completed signal registration for hyperliquid in 4.61 seconds

Registering signals group 34/44:  40%|████      | 2/5 [00:04<00:06,  2.10s/it]

INFO: Asset eos: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on eos: 3060 points
INFO: Calculated initial values for DonchianEnsembleBTC on bittensor: 997 points
INFO: Calculated initial values for RSI_Bullish_USD on bittensor: 997 points
INFO: Calculated initial values for RSI_Bullish_BTC on bittensor: 997 points
INFO: Calculated initial values for TrendMomentumUSD on bittensor: 997 points
INFO: Calculated initial values for TrendMomentumBTC on bittensor: 997 points
INFO: Completed signal registration for bittensor in 7.61 seconds

Registering signals group 34/44:  80%|████████  | 4/5 [00:07<00:01,  1.70s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on eos: 3060 points
INFO: Calculated initial values for RSI_Bullish_USD on eos: 3060 points
INFO: Calculated initial values for RSI_Bullish_BTC on eos: 3060 points
INFO: Calculated initial values for TrendMomentumUSD on eos: 3060 points
INFO: Calculated initial values for TrendMomentumBTC on eos: 3060 points
INFO: Completed signal registration for eos in 23.95 seconds

Registering signals group 34/44: 100%|██████████| 5/5 [00:23<00:00,  4.79s/it]

INFO: Processing asset group 35/44 with 5 assets
INFO: Starting signal registration for pendle
INFO: Starting signal registration for sui
INFO: Registering 6 new signals for sui
INFO: Starting signal registration for dydx

Registering signals group 35/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for smartcash
INFO: Starting signal registration for polkadot
INFO: Registering 6 new signals for pendle
INFO: Registering 6 new signals for dydx
INFO: Registering 6 new signals for smartcash
INFO: Registering 6 new signals for polkadot
INFO: Asset sui: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on sui: 936 points
INFO: Asset dydx: Using 9 windows with threshold 3
INFO: Asset pendle: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on dydx: 1538 points
INFO: Calculated initial values for DonchianEnsembleUSD on pendle: 1671 points
INFO: Asset polkadot: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on polkadot: 1923 points
INFO: Calculated initial values for DonchianEnsembleBTC on sui: 936 points
INFO: Asset smartcash: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on smartcash: 2979 points
INFO: Calculated initial values for RSI_Bullish_USD on sui: 936 points
INFO: Calculated initial values for RSI_Bullish_BTC on sui: 936 points
INFO: Calculated initial values for TrendMomentumUSD on sui: 936 points
INFO: Calculated initial values for TrendMomentumBTC on sui: 936 points
INFO: Completed signal registration for sui in 18.68 seconds

Registering signals group 35/44:  20%|██        | 1/5 [00:18<01:15, 18.96s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on dydx: 1538 points
INFO: Calculated initial values for DonchianEnsembleBTC on pendle: 1671 points
INFO: Calculated initial values for DonchianEnsembleBTC on polkadot: 1923 points
INFO: Calculated initial values for RSI_Bullish_USD on dydx: 1538 points
INFO: Calculated initial values for RSI_Bullish_BTC on dydx: 1538 points
INFO: Calculated initial values for RSI_Bullish_USD on pendle: 1671 points
INFO: Calculated initial values for TrendMomentumUSD on dydx: 1538 points
INFO: Calculated initial values for RSI_Bullish_BTC on pendle: 1671 points
INFO: Calculated initial values for TrendMomentumBTC on dydx: 1538 points
INFO: Completed signal registration for dydx in 27.46 seconds

Registering signals group 35/44:  40%|████      | 2/5 [00:27<00:38, 12.94s/it]

INFO: Calculated initial values for TrendMomentumUSD on pendle: 1671 points
INFO: Calculated initial values for RSI_Bullish_USD on polkadot: 1923 points
INFO: Calculated initial values for TrendMomentumBTC on pendle: 1671 points
INFO: Completed signal registration for pendle in 28.52 seconds

Registering signals group 35/44:  60%|██████    | 3/5 [00:28<00:14,  7.44s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on polkadot: 1923 points
INFO: Calculated initial values for DonchianEnsembleBTC on smartcash: 2979 points
INFO: Calculated initial values for TrendMomentumUSD on polkadot: 1923 points
INFO: Calculated initial values for TrendMomentumBTC on polkadot: 1923 points
INFO: Completed signal registration for polkadot in 29.44 seconds

Registering signals group 35/44:  80%|████████  | 4/5 [00:29<00:04,  4.93s/it]

ERROR: Error calculating RSI Bullish signal for smartcash: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
INFO: Calculated initial values for RSI_Bullish_USD on smartcash: 2979 points
INFO: Calculated initial values for RSI_Bullish_BTC on smartcash: 2979 points
ERROR: Error calculating Trend Momentum signal for smartcash: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
INFO: Calculated initial values for TrendMomentumUSD on smartcash: 2979 points
INFO: Calculated initial values for TrendMomentumBTC on smartcash: 2979 points
INFO: Completed signal registration for smartcash in 31.91 seconds

Registering signals group 35/44: 100%|██████████| 5/5 [00:31<00:00,  6.39s/it]

INFO: Processing asset group 36/44 with 5 assets
INFO: Starting signal registration for immutable-x
INFO: Starting signal registration for sushi

INFO: Starting signal registration for y

Registering signals group 36/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for grok-2
INFO: Registering 6 new signals for immutable-x
INFO: Starting signal registration for arpa
INFO: Registering 6 new signals for sushi
INFO: Registering 6 new signals for y
INFO: Registering 6 new signals for grok-2
INFO: Registering 6 new signals for arpa
INFO: Adapted windows for data length 602: [4, 8, 16, 25, 50, 75, 125]
INFO: Asset grok-2: Using 9 windows with threshold 3
INFO: Asset y: Using 7 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on grok-2: 748 points
INFO: Calculated initial values for DonchianEnsembleUSD on y: 602 points
INFO: Asset immutable-x: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on immutable-x: 1480 points
INFO: Asset sushi: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on sushi: 1914 points
INFO: Calculated initial values for DonchianEnsembleBTC on y: 602 points
INFO: Calculated initial values for DonchianEnsembleBTC on grok-2: 748 points
INFO: Asset arpa: Using 9 windows with threshold 3
INFO: Calculated initial values for RSI_Bullish_USD on y: 602 points
INFO: Calculated initial values for DonchianEnsembleUSD on arpa: 2372 points
INFO: Calculated initial values for RSI_Bullish_BTC on y: 602 points
INFO: Calculated initial values for TrendMomentumUSD on y: 602 points
INFO: Calculated initial values for TrendMomentumBTC on y: 602 points
INFO: Completed signal registration for y in 12.67 seconds

Registering signals group 36/44:  20%|██        | 1/5 [00:12<00:51, 12.92s/it]

INFO: Calculated initial values for RSI_Bullish_USD on grok-2: 748 points
INFO: Calculated initial values for RSI_Bullish_BTC on grok-2: 748 points
INFO: Calculated initial values for TrendMomentumUSD on grok-2: 748 points
INFO: Calculated initial values for DonchianEnsembleBTC on immutable-x: 1480 points
INFO: Calculated initial values for TrendMomentumBTC on grok-2: 748 points
INFO: Completed signal registration for grok-2 in 14.68 seconds

Registering signals group 36/44:  40%|████      | 2/5 [00:14<00:19,  6.49s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on sushi: 1914 points
INFO: Calculated initial values for RSI_Bullish_USD on immutable-x: 1480 points
INFO: Calculated initial values for RSI_Bullish_BTC on immutable-x: 1480 points
INFO: Calculated initial values for TrendMomentumUSD on immutable-x: 1480 points
INFO: Calculated initial values for TrendMomentumBTC on immutable-x: 1480 points
INFO: Completed signal registration for immutable-x in 19.52 seconds

Registering signals group 36/44:  60%|██████    | 3/5 [00:19<00:11,  5.69s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on arpa: 2372 points
INFO: Calculated initial values for RSI_Bullish_USD on sushi: 1914 points
INFO: Calculated initial values for RSI_Bullish_BTC on sushi: 1914 points
INFO: Calculated initial values for TrendMomentumUSD on sushi: 1914 points
INFO: Calculated initial values for TrendMomentumBTC on sushi: 1914 points
INFO: Completed signal registration for sushi in 22.04 seconds

Registering signals group 36/44:  80%|████████  | 4/5 [00:22<00:04,  4.39s/it]

INFO: Calculated initial values for RSI_Bullish_USD on arpa: 2372 points
INFO: Calculated initial values for RSI_Bullish_BTC on arpa: 2372 points
INFO: Calculated initial values for TrendMomentumUSD on arpa: 2372 points
INFO: Calculated initial values for TrendMomentumBTC on arpa: 2372 points
INFO: Completed signal registration for arpa in 22.75 seconds

Registering signals group 36/44: 100%|██████████| 5/5 [00:22<00:00,  4.56s/it]

INFO: Processing asset group 37/44 with 5 assets
INFO: Starting signal registration for ethervista
INFO: Starting signal registration for grass
INFO: Starting signal registration for mintlayer
INFO: Registering 6 new signals for ethervista

Registering signals group 37/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for gains-network
INFO: Starting signal registration for hedera-hashgraph
INFO: Registering 6 new signals for grass
INFO: Registering 6 new signals for mintlayer
INFO: Adapted windows for data length 449: [3, 6, 12, 18, 37, 56, 93]
INFO: Registering 6 new signals for gains-network
INFO: Registering 6 new signals for hedera-hashgraph
INFO: Adapted windows for data length 392: [5, 10, 16, 32, 48, 81]
INFO: Asset ethervista: Using 7 windows with threshold 3
INFO: Asset grass: Using 6 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on ethervista: 449 points
INFO: Calculated initial values for DonchianEnsembleUSD on grass: 392 points
INFO: Asset mintlayer: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on mintlayer: 975 points
INFO: Calculated initial values for DonchianEnsembleBTC on ethervista: 449 points
INFO: Calculated initial values for DonchianEnsembleBTC on grass: 392 points
INFO: Asset gains-network: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on gains-network: 1483 points
INFO: Calculated initial values for RSI_Bullish_USD on grass: 392 points
INFO: Calculated initial values for RSI_Bullish_USD on ethervista: 449 points
INFO: Calculated initial values for RSI_Bullish_BTC on grass: 392 points
INFO: Calculated initial values for RSI_Bullish_BTC on ethervista: 449 points
INFO: Calculated initial values for TrendMomentumUSD on grass: 392 points
INFO: Calculated initial values for TrendMomentumUSD on ethervista: 449 points
INFO: Calculated initial values for TrendMomentumBTC on grass: 392 points
INFO: Completed signal registration for grass in 7.88 seconds

Registering signals group 37/44:  20%|██        | 1/5 [00:08<00:32,  8.05s/it]

INFO: Calculated initial values for TrendMomentumBTC on ethervista: 449 points
INFO: Asset hedera-hashgraph: Using 9 windows with threshold 3
INFO: Completed signal registration for ethervista in 9.19 seconds
INFO: Calculated initial values for DonchianEnsembleUSD on hedera-hashgraph: 2260 points

Registering signals group 37/44:  40%|████      | 2/5 [00:09<00:12,  4.15s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on mintlayer: 975 points
INFO: Calculated initial values for RSI_Bullish_USD on mintlayer: 975 points
INFO: Calculated initial values for RSI_Bullish_BTC on mintlayer: 975 points
INFO: Calculated initial values for TrendMomentumUSD on mintlayer: 975 points
INFO: Calculated initial values for DonchianEnsembleBTC on gains-network: 1483 points
INFO: Calculated initial values for TrendMomentumBTC on mintlayer: 975 points
INFO: Completed signal registration for mintlayer in 15.63 seconds

Registering signals group 37/44:  60%|██████    | 3/5 [00:15<00:10,  5.09s/it]

INFO: Calculated initial values for RSI_Bullish_USD on gains-network: 1483 points
INFO: Calculated initial values for RSI_Bullish_BTC on gains-network: 1483 points
INFO: Calculated initial values for TrendMomentumUSD on gains-network: 1483 points
INFO: Calculated initial values for DonchianEnsembleBTC on hedera-hashgraph: 2260 points
INFO: Calculated initial values for TrendMomentumBTC on gains-network: 1483 points
INFO: Completed signal registration for gains-network in 19.12 seconds

Registering signals group 37/44:  80%|████████  | 4/5 [00:19<00:04,  4.47s/it]

INFO: Calculated initial values for RSI_Bullish_USD on hedera-hashgraph: 2260 points
INFO: Calculated initial values for RSI_Bullish_BTC on hedera-hashgraph: 2260 points
INFO: Calculated initial values for TrendMomentumUSD on hedera-hashgraph: 2260 points
INFO: Calculated initial values for TrendMomentumBTC on hedera-hashgraph: 2260 points
INFO: Completed signal registration for hedera-hashgraph in 22.15 seconds

Registering signals group 37/44: 100%|██████████| 5/5 [00:22<00:00,  4.43s/it]

INFO: Processing asset group 38/44 with 5 assets
INFO: Starting signal registration for havven
INFO: Registering 6 new signals for havven
INFO: Starting signal registration for radiant-capital
INFO: Starting signal registration for avalanche-2

Registering signals group 38/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for fetch-ai
INFO: Starting signal registration for omisego
INFO: Registering 6 new signals for radiant-capital
INFO: Registering 6 new signals for avalanche-2
INFO: Registering 6 new signals for fetch-ai
INFO: Registering 6 new signals for omisego
INFO: Asset radiant-capital: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on radiant-capital: 1217 points
INFO: Asset avalanche-2: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on avalanche-2: 1889 points
INFO: Asset fetch-ai: Using 9 windows with threshold 3
INFO: Asset havven: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on fetch-ai: 2461 points
INFO: Calculated initial values for DonchianEnsembleUSD on havven: 2806 points
INFO: Asset omisego: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on omisego: 3053 points
INFO: Calculated initial values for DonchianEnsembleBTC on radiant-capital: 1217 points
INFO: Calculated initial values for RSI_Bullish_USD on radiant-capital: 1217 points
INFO: Calculated initial values for RSI_Bullish_BTC on radiant-capital: 1217 points
INFO: Calculated initial values for DonchianEnsembleBTC on avalanche-2: 1889 points
INFO: Calculated initial values for TrendMomentumUSD on radiant-capital: 1217 points
INFO: Calculated initial values for TrendMomentumBTC on radiant-capital: 1217 points
INFO: Completed signal registration for radiant-capital in 16.87 seconds

Registering signals group 38/44:  20%|██        | 1/5 [00:17<01:08, 17.09s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on fetch-ai: 2461 points
INFO: Calculated initial values for RSI_Bullish_USD on avalanche-2: 1889 points
INFO: Calculated initial values for RSI_Bullish_BTC on avalanche-2: 1889 points
INFO: Calculated initial values for DonchianEnsembleBTC on havven: 2806 points
INFO: Calculated initial values for TrendMomentumUSD on avalanche-2: 1889 points
INFO: Calculated initial values for TrendMomentumBTC on avalanche-2: 1889 points
INFO: Completed signal registration for avalanche-2 in 25.87 seconds

Registering signals group 38/44:  40%|████      | 2/5 [00:25<00:36, 12.27s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on omisego: 3053 points
INFO: Calculated initial values for RSI_Bullish_USD on fetch-ai: 2461 points
INFO: Calculated initial values for RSI_Bullish_BTC on fetch-ai: 2461 points
INFO: Calculated initial values for TrendMomentumUSD on fetch-ai: 2461 points
INFO: Calculated initial values for TrendMomentumBTC on fetch-ai: 2461 points
INFO: Calculated initial values for RSI_Bullish_USD on havven: 2806 points
INFO: Completed signal registration for fetch-ai in 32.47 seconds

Registering signals group 38/44:  60%|██████    | 3/5 [00:32<00:19,  9.65s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on havven: 2806 points
INFO: Calculated initial values for RSI_Bullish_USD on omisego: 3053 points
INFO: Calculated initial values for TrendMomentumUSD on havven: 2806 points
INFO: Calculated initial values for TrendMomentumBTC on havven: 2806 points
INFO: Calculated initial values for RSI_Bullish_BTC on omisego: 3053 points
INFO: Completed signal registration for havven in 34.05 seconds

Registering signals group 38/44:  80%|████████  | 4/5 [00:33<00:06,  6.39s/it]

INFO: Calculated initial values for TrendMomentumUSD on omisego: 3053 points
INFO: Calculated initial values for TrendMomentumBTC on omisego: 3053 points
INFO: Completed signal registration for omisego in 34.39 seconds

Registering signals group 38/44: 100%|██████████| 5/5 [00:34<00:00,  6.90s/it]

INFO: Processing asset group 39/44 with 5 assets
INFO: Starting signal registration for nunet
INFO: Starting signal registration for ethena
INFO: Registering 6 new signals for ethena
INFO: Starting signal registration for baby-doge-coin

Registering signals group 39/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 6 new signals for baby-doge-coin
INFO: Registering 6 new signals for nunet
INFO: Starting signal registration for bertram-the-pomeranian
INFO: Adapted windows for data length 601: [4, 8, 16, 25, 50, 75, 125]
INFO: Starting signal registration for liquity
INFO: Registering 6 new signals for bertram-the-pomeranian
INFO: Registering 6 new signals for liquity
INFO: Adapted windows for data length 377: [5, 10, 15, 31, 47, 78]
INFO: Asset ethena: Using 7 windows with threshold 3
INFO: Asset bertram-the-pomeranian: Using 6 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on ethena: 601 points
INFO: Calculated initial values for DonchianEnsembleUSD on bertram-the-pomeranian: 377 points
INFO: Asset nunet: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on nunet: 1457 points
INFO: Asset baby-doge-coin: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleBTC on bertram-the-pomeranian: 377 points
INFO: Calculated initial values for DonchianEnsembleUSD on baby-doge-coin: 1629 points
INFO: Asset liquity: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleBTC on ethena: 601 points
INFO: Calculated initial values for DonchianEnsembleUSD on liquity: 1694 points
INFO: Calculated initial values for RSI_Bullish_USD on bertram-the-pomeranian: 377 points
INFO: Calculated initial values for RSI_Bullish_BTC on bertram-the-pomeranian: 377 points
INFO: Calculated initial values for TrendMomentumUSD on bertram-the-pomeranian: 377 points
INFO: Calculated initial values for TrendMomentumBTC on bertram-the-pomeranian: 377 points
INFO: Completed signal registration for bertram-the-pomeranian in 6.04 seconds
INFO: Calculated initial values for RSI_Bullish_USD on ethena: 601 points

Registering signals group 39/44:  20%|██        | 1/5 [00:06<00:26,  6.67s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on ethena: 601 points
INFO: Calculated initial values for TrendMomentumUSD on ethena: 601 points
INFO: Calculated initial values for TrendMomentumBTC on ethena: 601 points
INFO: Completed signal registration for ethena in 8.36 seconds

Registering signals group 39/44:  40%|████      | 2/5 [00:08<00:11,  3.84s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on nunet: 1457 points
INFO: Calculated initial values for DonchianEnsembleBTC on baby-doge-coin: 1629 points
INFO: Calculated initial values for DonchianEnsembleBTC on liquity: 1694 points
INFO: Calculated initial values for RSI_Bullish_USD on nunet: 1457 points
INFO: Calculated initial values for RSI_Bullish_BTC on nunet: 1457 points
INFO: Calculated initial values for TrendMomentumUSD on nunet: 1457 points
INFO: Calculated initial values for TrendMomentumBTC on nunet: 1457 points
INFO: Calculated initial values for RSI_Bullish_USD on baby-doge-coin: 1629 points
INFO: Completed signal registration for nunet in 14.63 seconds

Registering signals group 39/44:  60%|██████    | 3/5 [00:14<00:09,  4.95s/it]

INFO: Calculated initial values for RSI_Bullish_USD on liquity: 1694 points
INFO: Calculated initial values for RSI_Bullish_BTC on baby-doge-coin: 1629 points
INFO: Calculated initial values for RSI_Bullish_BTC on liquity: 1694 points
INFO: Calculated initial values for TrendMomentumUSD on baby-doge-coin: 1629 points
INFO: Calculated initial values for TrendMomentumUSD on liquity: 1694 points
INFO: Calculated initial values for TrendMomentumBTC on baby-doge-coin: 1629 points
INFO: Completed signal registration for baby-doge-coin in 15.61 seconds

Registering signals group 39/44:  80%|████████  | 4/5 [00:15<00:03,  3.33s/it]

INFO: Calculated initial values for TrendMomentumBTC on liquity: 1694 points
INFO: Completed signal registration for liquity in 14.93 seconds

Registering signals group 39/44: 100%|██████████| 5/5 [00:15<00:00,  3.15s/it]

INFO: Processing asset group 40/44 with 5 assets
INFO: Starting signal registration for thorchain

INFO: Starting signal registration for lido-dao

Registering signals group 40/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for acala
INFO: Starting signal registration for siren-2
INFO: Starting signal registration for litecoin
INFO: Registering 6 new signals for thorchain
INFO: Registering 6 new signals for lido-dao
INFO: Registering 6 new signals for acala
INFO: Registering 6 new signals for siren-2
INFO: Registering 6 new signals for litecoin
INFO: Adapted windows for data length 278: [3, 7, 11, 23, 34, 57]
INFO: Asset siren-2: Using 6 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on siren-2: 278 points
INFO: Calculated initial values for DonchianEnsembleBTC on siren-2: 278 points
INFO: Calculated initial values for RSI_Bullish_USD on siren-2: 278 points
INFO: Asset acala: Using 9 windows with threshold 3
INFO: Calculated initial values for RSI_Bullish_BTC on siren-2: 278 points
INFO: Calculated initial values for DonchianEnsembleUSD on acala: 1399 points
INFO: Asset lido-dao: Using 9 windows with threshold 3
INFO: Calculated initial values for TrendMomentumUSD on siren-2: 278 points
INFO: Calculated initial values for DonchianEnsembleUSD on lido-dao: 1784 points
INFO: Calculated initial values for TrendMomentumBTC on siren-2: 278 points
INFO: Completed signal registration for siren-2 in 5.31 seconds

Registering signals group 40/44:  20%|██        | 1/5 [00:05<00:22,  5.57s/it]

INFO: Asset thorchain: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on thorchain: 2319 points
INFO: Calculated initial values for DonchianEnsembleBTC on acala: 1399 points
INFO: Asset litecoin: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on litecoin: 4593 points
INFO: Calculated initial values for DonchianEnsembleBTC on lido-dao: 1784 points
INFO: Calculated initial values for RSI_Bullish_USD on acala: 1399 points
INFO: Calculated initial values for RSI_Bullish_BTC on acala: 1399 points
INFO: Calculated initial values for TrendMomentumUSD on acala: 1399 points
INFO: Calculated initial values for DonchianEnsembleBTC on thorchain: 2319 points
INFO: Calculated initial values for TrendMomentumBTC on acala: 1399 points
INFO: Completed signal registration for acala in 18.08 seconds

Registering signals group 40/44:  40%|████      | 2/5 [00:18<00:29,  9.70s/it]

INFO: Calculated initial values for RSI_Bullish_USD on lido-dao: 1784 points
INFO: Calculated initial values for RSI_Bullish_BTC on lido-dao: 1784 points
INFO: Calculated initial values for TrendMomentumUSD on lido-dao: 1784 points
INFO: Calculated initial values for TrendMomentumBTC on lido-dao: 1784 points
INFO: Completed signal registration for lido-dao in 20.79 seconds

Registering signals group 40/44:  60%|██████    | 3/5 [00:20<00:12,  6.49s/it]

INFO: Calculated initial values for RSI_Bullish_USD on thorchain: 2319 points
INFO: Calculated initial values for RSI_Bullish_BTC on thorchain: 2319 points
INFO: Calculated initial values for TrendMomentumUSD on thorchain: 2319 points
INFO: Calculated initial values for TrendMomentumBTC on thorchain: 2319 points
INFO: Completed signal registration for thorchain in 22.36 seconds

Registering signals group 40/44:  80%|████████  | 4/5 [00:22<00:04,  4.56s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on litecoin: 4593 points
INFO: Calculated initial values for RSI_Bullish_USD on litecoin: 4593 points
INFO: Calculated initial values for RSI_Bullish_BTC on litecoin: 4593 points
INFO: Calculated initial values for TrendMomentumUSD on litecoin: 4593 points
INFO: Calculated initial values for TrendMomentumBTC on litecoin: 4593 points
INFO: Completed signal registration for litecoin in 27.82 seconds

Registering signals group 40/44: 100%|██████████| 5/5 [00:27<00:00,  5.56s/it]

INFO: Processing asset group 41/44 with 5 assets
INFO: Starting signal registration for fartcoin
INFO: Starting signal registration for jupiter-exchange-solana
INFO: Starting signal registration for book-of-meme

INFO: Registering 6 new signals for fartcoin

Registering signals group 41/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for spell-token
INFO: Registering 6 new signals for jupiter-exchange-solana
INFO: Starting signal registration for new-xai-gork
INFO: Registering 6 new signals for book-of-meme
INFO: Adapted windows for data length 400: [5, 11, 16, 33, 50, 83]
INFO: Registering 6 new signals for spell-token
INFO: Adapted windows for data length 663: [4, 9, 18, 27, 55, 82, 138]
INFO: Registering 6 new signals for new-xai-gork
INFO: Adapted windows for data length 620: [4, 8, 17, 25, 51, 77, 129]
INFO: Adapted windows for data length 206: [5, 8, 17, 25, 42]
INFO: Asset fartcoin: Using 6 windows with threshold 3
INFO: Asset new-xai-gork: Using 5 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on fartcoin: 400 points
INFO: Calculated initial values for DonchianEnsembleUSD on new-xai-gork: 206 points
INFO: Asset jupiter-exchange-solana: Using 7 windows with threshold 3
INFO: Asset book-of-meme: Using 7 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on jupiter-exchange-solana: 663 points
INFO: Calculated initial values for DonchianEnsembleUSD on book-of-meme: 620 points
INFO: Calculated initial values for DonchianEnsembleBTC on new-xai-gork: 206 points
INFO: Calculated initial values for DonchianEnsembleBTC on fartcoin: 400 points
INFO: Calculated initial values for RSI_Bullish_USD on new-xai-gork: 206 points
INFO: Calculated initial values for RSI_Bullish_BTC on new-xai-gork: 206 points
INFO: Calculated initial values for TrendMomentumUSD on new-xai-gork: 206 points
INFO: Asset spell-token: Using 9 windows with threshold 3
INFO: Calculated initial values for RSI_Bullish_USD on fartcoin: 400 points
INFO: Calculated initial values for TrendMomentumBTC on new-xai-gork: 206 points
INFO: Calculated initial values for DonchianEnsembleUSD on spell-token: 1641 points
INFO: Calculated initial values for DonchianEnsembleBTC on book-of-meme: 620 points
INFO: Calculated initial values for RSI_Bullish_BTC on fartcoin: 400 points
INFO: Completed signal registration for new-xai-gork in 4.40 seconds

Registering signals group 41/44:  20%|██        | 1/5 [00:04<00:18,  4.65s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on jupiter-exchange-solana: 663 points
INFO: Calculated initial values for TrendMomentumUSD on fartcoin: 400 points
INFO: Calculated initial values for TrendMomentumBTC on fartcoin: 400 points
INFO: Calculated initial values for RSI_Bullish_USD on book-of-meme: 620 points
INFO: Completed signal registration for fartcoin in 5.47 seconds

Registering signals group 41/44:  40%|████      | 2/5 [00:05<00:07,  2.52s/it]

INFO: Calculated initial values for RSI_Bullish_USD on jupiter-exchange-solana: 663 points
INFO: Calculated initial values for RSI_Bullish_BTC on book-of-meme: 620 points
INFO: Calculated initial values for TrendMomentumUSD on book-of-meme: 620 points
INFO: Calculated initial values for RSI_Bullish_BTC on jupiter-exchange-solana: 663 points
INFO: Calculated initial values for TrendMomentumBTC on book-of-meme: 620 points
INFO: Calculated initial values for TrendMomentumUSD on jupiter-exchange-solana: 663 points
INFO: Completed signal registration for book-of-meme in 6.24 seconds

Registering signals group 41/44:  60%|██████    | 3/5 [00:06<00:03,  1.69s/it]

INFO: Calculated initial values for TrendMomentumBTC on jupiter-exchange-solana: 663 points
INFO: Completed signal registration for jupiter-exchange-solana in 6.48 seconds

Registering signals group 41/44:  80%|████████  | 4/5 [00:06<00:01,  1.08s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on spell-token: 1641 points
INFO: Calculated initial values for RSI_Bullish_USD on spell-token: 1641 points
INFO: Calculated initial values for RSI_Bullish_BTC on spell-token: 1641 points
INFO: Calculated initial values for TrendMomentumUSD on spell-token: 1641 points
INFO: Calculated initial values for TrendMomentumBTC on spell-token: 1641 points
INFO: Completed signal registration for spell-token in 8.51 seconds

Registering signals group 41/44: 100%|██████████| 5/5 [00:08<00:00,  1.70s/it]

INFO: Processing asset group 42/44 with 5 assets
INFO: Starting signal registration for useless-3
INFO: Starting signal registration for kryptonite

INFO: Starting signal registration for zebec-network
INFO: Starting signal registration for aerodrome-finance

Registering signals group 42/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 6 new signals for useless-3
INFO: Starting signal registration for ethereum
INFO: Registering 6 new signals for kryptonite
INFO: Registering 6 new signals for zebec-network
INFO: Registering 6 new signals for aerodrome-finance
INFO: Adapted windows for data length 197: [5, 8, 16, 24, 41]
INFO: Registering 6 new signals for ethereum
INFO: Adapted windows for data length 588: [4, 8, 16, 24, 49, 73, 122]
INFO: Asset useless-3: Using 5 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on useless-3: 197 points
INFO: Asset kryptonite: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleBTC on useless-3: 197 points
INFO: Asset zebec-network: Using 7 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on kryptonite: 833 points
INFO: Asset aerodrome-finance: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on zebec-network: 588 points
INFO: Calculated initial values for RSI_Bullish_USD on useless-3: 197 points
INFO: Calculated initial values for DonchianEnsembleUSD on aerodrome-finance: 801 points
INFO: Calculated initial values for RSI_Bullish_BTC on useless-3: 197 points
INFO: Calculated initial values for TrendMomentumUSD on useless-3: 197 points
INFO: Calculated initial values for TrendMomentumBTC on useless-3: 197 points
INFO: Completed signal registration for useless-3 in 3.44 seconds

Registering signals group 42/44:  20%|██        | 1/5 [00:03<00:14,  3.65s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on zebec-network: 588 points
INFO: Calculated initial values for DonchianEnsembleBTC on kryptonite: 833 points
INFO: Calculated initial values for RSI_Bullish_USD on zebec-network: 588 points
INFO: Calculated initial values for DonchianEnsembleBTC on aerodrome-finance: 801 points
INFO: Calculated initial values for RSI_Bullish_BTC on zebec-network: 588 points
INFO: Calculated initial values for TrendMomentumUSD on zebec-network: 588 points
INFO: Calculated initial values for TrendMomentumBTC on zebec-network: 588 points
INFO: Calculated initial values for RSI_Bullish_USD on kryptonite: 833 points
INFO: Completed signal registration for zebec-network in 6.93 seconds
INFO: Calculated initial values for RSI_Bullish_USD on aerodrome-finance: 801 points

Registering signals group 42/44:  40%|████      | 2/5 [00:07<00:10,  3.60s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on kryptonite: 833 points
INFO: Asset ethereum: Using 9 windows with threshold 3
INFO: Calculated initial values for TrendMomentumUSD on kryptonite: 833 points
INFO: Calculated initial values for RSI_Bullish_BTC on aerodrome-finance: 801 points
INFO: Calculated initial values for DonchianEnsembleUSD on ethereum: 3762 points
INFO: Calculated initial values for TrendMomentumBTC on kryptonite: 833 points
INFO: Calculated initial values for TrendMomentumUSD on aerodrome-finance: 801 points
INFO: Completed signal registration for kryptonite in 7.73 seconds

Registering signals group 42/44:  60%|██████    | 3/5 [00:07<00:04,  2.24s/it]

INFO: Calculated initial values for TrendMomentumBTC on aerodrome-finance: 801 points
INFO: Completed signal registration for aerodrome-finance in 8.00 seconds

Registering signals group 42/44:  80%|████████  | 4/5 [00:08<00:01,  1.45s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on ethereum: 3762 points
INFO: Calculated initial values for RSI_Bullish_USD on ethereum: 3762 points
INFO: Calculated initial values for RSI_Bullish_BTC on ethereum: 3762 points
INFO: Calculated initial values for TrendMomentumUSD on ethereum: 3762 points
INFO: Calculated initial values for TrendMomentumBTC on ethereum: 3762 points
INFO: Completed signal registration for ethereum in 16.27 seconds

Registering signals group 42/44: 100%|██████████| 5/5 [00:16<00:00,  3.25s/it]

INFO: Processing asset group 43/44 with 5 assets
INFO: Starting signal registration for serum

INFO: Starting signal registration for conic-finance

Registering signals group 43/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for tribe-2
INFO: Starting signal registration for shiba-inu
INFO: Starting signal registration for popcat
INFO: Registering 6 new signals for serum
INFO: Registering 6 new signals for conic-finance
INFO: Registering 6 new signals for tribe-2
INFO: Registering 6 new signals for shiba-inu
INFO: Registering 6 new signals for popcat
INFO: Adapted windows for data length 706: [4, 9, 19, 29, 58, 88, 147]
INFO: Asset popcat: Using 7 windows with threshold 3
INFO: Asset conic-finance: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on popcat: 706 points
INFO: Calculated initial values for DonchianEnsembleUSD on conic-finance: 1084 points
INFO: Asset serum: Using 9 windows with threshold 3
INFO: Asset tribe-2: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on serum: 1931 points
INFO: Calculated initial values for DonchianEnsembleUSD on tribe-2: 1696 points
INFO: Asset shiba-inu: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleBTC on popcat: 706 points
INFO: Calculated initial values for DonchianEnsembleUSD on shiba-inu: 1927 points
INFO: Calculated initial values for RSI_Bullish_USD on popcat: 706 points
INFO: Calculated initial values for RSI_Bullish_BTC on popcat: 706 points
INFO: Calculated initial values for DonchianEnsembleBTC on conic-finance: 1084 points
INFO: Calculated initial values for TrendMomentumUSD on popcat: 706 points
INFO: Calculated initial values for TrendMomentumBTC on popcat: 706 points
INFO: Completed signal registration for popcat in 10.78 seconds

Registering signals group 43/44:  20%|██        | 1/5 [00:11<00:44, 11.03s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on tribe-2: 1696 points
INFO: Calculated initial values for DonchianEnsembleBTC on serum: 1931 points
INFO: Calculated initial values for DonchianEnsembleBTC on shiba-inu: 1927 points
ERROR: Error calculating RSI Bullish signal for conic-finance: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
INFO: Calculated initial values for RSI_Bullish_USD on conic-finance: 1084 points
INFO: Calculated initial values for RSI_Bullish_USD on tribe-2: 1696 points
INFO: Calculated initial values for RSI_Bullish_BTC on tribe-2: 1696 points
INFO: Calculated initial values for RSI_Bullish_BTC on conic-finance: 1084 points
INFO: Calculated initial values for RSI_Bullish_USD on serum: 1931 points
INFO: Calculated initial values for TrendMomentumUSD on tribe-2: 1696 points
INFO: Calculated initial values for TrendMomentumBTC on tribe-2: 1696 points
INFO: Calculated initial values for RSI_Bullish_USD on shiba-inu: 1927 points
INFO: Completed signal registration for tribe-2 in 20.54 seconds

Registering signals group 43/44:  40%|████      | 2/5 [00:20<00:30, 10.16s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on serum: 1931 points
INFO: Calculated initial values for RSI_Bullish_BTC on shiba-inu: 1927 points
INFO: Calculated initial values for TrendMomentumUSD on serum: 1931 points
ERROR: Error calculating Trend Momentum signal for conic-finance: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
INFO: Calculated initial values for TrendMomentumUSD on conic-finance: 1084 points
INFO: Calculated initial values for TrendMomentumBTC on serum: 1931 points
INFO: Calculated initial values for TrendMomentumUSD on shiba-inu: 1927 points
INFO: Completed signal registration for serum in 21.69 seconds

Registering signals group 43/44:  60%|██████    | 3/5 [00:21<00:12,  6.03s/it]

INFO: Calculated initial values for TrendMomentumBTC on shiba-inu: 1927 points
INFO: Completed signal registration for shiba-inu in 21.87 seconds

Registering signals group 43/44:  80%|████████  | 4/5 [00:21<00:03,  3.72s/it]

INFO: Calculated initial values for TrendMomentumBTC on conic-finance: 1084 points
INFO: Completed signal registration for conic-finance in 21.97 seconds

Registering signals group 43/44: 100%|██████████| 5/5 [00:21<00:00,  4.39s/it]

INFO: Processing asset group 44/44 with 5 assets
INFO: Starting signal registration for zksync

INFO: Starting signal registration for compound-governance-token

Registering signals group 44/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for kujira
INFO: Starting signal registration for quant-network
INFO: Starting signal registration for ondo-finance
INFO: Registering 6 new signals for zksync
INFO: Registering 6 new signals for compound-governance-token
INFO: Registering 6 new signals for kujira
INFO: Registering 6 new signals for quant-network
INFO: Registering 6 new signals for ondo-finance
INFO: Adapted windows for data length 524: [3, 7, 14, 21, 43, 65, 109]
INFO: Adapted windows for data length 676: [4, 9, 18, 28, 56, 84, 140]
INFO: Asset zksync: Using 7 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on zksync: 524 points
INFO: Asset ondo-finance: Using 7 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on ondo-finance: 676 points
INFO: Asset kujira: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on kujira: 1459 points
INFO: Calculated initial values for DonchianEnsembleBTC on zksync: 524 points
INFO: Asset compound-governance-token: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on compound-governance-token: 1987 points
INFO: Calculated initial values for DonchianEnsembleBTC on ondo-finance: 676 points
INFO: Calculated initial values for RSI_Bullish_USD on zksync: 524 points
INFO: Calculated initial values for RSI_Bullish_BTC on zksync: 524 points
INFO: Calculated initial values for TrendMomentumUSD on zksync: 524 points
INFO: Asset quant-network: Using 9 windows with threshold 3
INFO: Calculated initial values for RSI_Bullish_USD on ondo-finance: 676 points
INFO: Calculated initial values for DonchianEnsembleUSD on quant-network: 2705 points
INFO: Calculated initial values for TrendMomentumBTC on zksync: 524 points
INFO: Calculated initial values for RSI_Bullish_BTC on ondo-finance: 676 points
INFO: Completed signal registration for zksync in 7.75 seconds

Registering signals group 44/44:  20%|██        | 1/5 [00:08<00:32,  8.04s/it]

INFO: Calculated initial values for TrendMomentumUSD on ondo-finance: 676 points
INFO: Calculated initial values for TrendMomentumBTC on ondo-finance: 676 points
INFO: Completed signal registration for ondo-finance in 8.79 seconds

Registering signals group 44/44:  40%|████      | 2/5 [00:08<00:11,  3.80s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on kujira: 1459 points
INFO: Calculated initial values for DonchianEnsembleBTC on compound-governance-token: 1987 points
INFO: Calculated initial values for RSI_Bullish_USD on kujira: 1459 points
INFO: Calculated initial values for RSI_Bullish_BTC on kujira: 1459 points
INFO: Calculated initial values for TrendMomentumUSD on kujira: 1459 points
INFO: Calculated initial values for TrendMomentumBTC on kujira: 1459 points
INFO: Completed signal registration for kujira in 14.49 seconds

Registering signals group 44/44:  60%|██████    | 3/5 [00:14<00:09,  4.69s/it]

INFO: Calculated initial values for RSI_Bullish_USD on compound-governance-token: 1987 points
INFO: Calculated initial values for DonchianEnsembleBTC on quant-network: 2705 points
INFO: Calculated initial values for RSI_Bullish_BTC on compound-governance-token: 1987 points
INFO: Calculated initial values for TrendMomentumUSD on compound-governance-token: 1987 points
INFO: Calculated initial values for TrendMomentumBTC on compound-governance-token: 1987 points
INFO: Completed signal registration for compound-governance-token in 16.35 seconds

Registering signals group 44/44:  80%|████████  | 4/5 [00:16<00:03,  3.55s/it]

INFO: Calculated initial values for RSI_Bullish_USD on quant-network: 2705 points
INFO: Calculated initial values for RSI_Bullish_BTC on quant-network: 2705 points
INFO: Calculated initial values for TrendMomentumUSD on quant-network: 2705 points
INFO: Calculated initial values for TrendMomentumBTC on quant-network: 2705 points
INFO: Completed signal registration for quant-network in 17.96 seconds

Registering signals group 44/44: 100%|██████████| 5/5 [00:17<00:00,  3.59s/it]

INFO: Registered a total of 1320 signals across 220 assets

{'goatseus-maximus': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x169d57150>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x110c43dd0>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x169dd67d0>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x169dd4850>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x169b4da90>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x168eed7d0>},
 'genesysgo-shadow': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x169b4f4d0>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x168eff750>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x169dd6990>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x169f1d110>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x169dd7650>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x110a00310>},
 'the-sandbox': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x169d57710>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x169b4e510>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x169842c50>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x169f1e850>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x168efe450>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x169dd49d0>},
 'cosmos': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x110c51d10>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x15e9a7690>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x169f1c110>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x169dd54d0>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x169f1d050>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x16a359e50>},
 'tezos': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x169b4e4d0>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x169b4c3d0>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x169b4c810>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x169d54b90>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x169d55490>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x169f1dfd0>},
 'mubarak': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x16987c1d0>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x16987f250>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x169d56750>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x1694c2cd0>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x169d41650>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x169d40f10>},
 'story-2': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x169d57650>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x169f1ce10>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x16a222ad0>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x169d412d0>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x16a221410>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x16a466ed0>},
 'near': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x1694c3a50>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x16a35a6d0>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x1696d7d50>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x16a464b50>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x169d421d0>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x16a0758d0>},
 'alpha-finance': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x16a466590>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x169dd7950>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x1694c3dd0>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x16a222d10>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x1696d7190>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x169b4dad0>},
 'true-usd': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x16a466610>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x16a465f90>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x169842210>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x169b4f150>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x169d41510>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x1696d7850>},
 'spx6900': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x169dd5bd0>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x169dd7690>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x16a222b10>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x169eaefd0>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x16a4656d0>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x169f1e510>},
 'sei-network': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x16a465710>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x168efd5d0>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x169f1cf10>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x169eae890>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x16a077790>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x1696d5790>},
 'clearpool': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x16987d0d0>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x16a076690>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x16a359850>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x16a074e90>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x169841ad0>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x169ee0590>},
 'crypto-com-chain': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x169b4f510>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x16987e450>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x1696d4b10>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x169ead190>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x169ee0390>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x16a465990>},
 'matic-network': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x169eafd50>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x16a48cf10>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x169ee1dd0>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x169d40610>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x169ead590>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x16a222c50>},
 'ava-ai': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x1696d5f90>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x16987db90>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x1696d7250>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x169ce0d90>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x169fd7c10>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x16a48ee10>},
 'kekius-maximus': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x169b4fc90>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x168eff490>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x16a074a10>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x169934b50>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x16a4eb5d0>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x169937050>},
 'fwog': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x168f6d7d0>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x169b1c750>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x169fd6f10>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x169a15310>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x169936390>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x169b1ca10>},
 'cookie': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x169dd7190>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x16a466e50>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x169a17b10>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x16961a850>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x169d41350>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x1694c37d0>},
 'akash-network': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x16a4ea910>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x169d42590>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x16a222450>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x169896390>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x169fd70d0>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x169ce18d0>},
 'ether-fi': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x169937a90>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x169b1f990>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x1699915d0>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x16a7e33d0>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x169ce0390>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x169993310>},
 'slerf': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x169619350>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x169a8f6d0>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x16a4667d0>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x1699935d0>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x169d40e10>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x169936d50>},
 'frax-share': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x16a48f1d0>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x169843bd0>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x169ee1cd0>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x16a4e8d10>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x169b1f210>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x169992110>},
 'cardano': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x16961b4d0>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x169ee0550>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x171dd1110>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x16a264210>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x169a14c90>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x169618490>},
 'lisk': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x1699937d0>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x16a4eb250>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x16a264d90>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x16a222a50>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x169ee3310>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x169ee1210>},
 'dogwifcoin': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x171dd3350>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x16a220fd0>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x16a000590>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x171dd0450>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x16a000f10>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x171dd1750>},
 'arbitrum': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x169ead710>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x169b1fe50>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x169b4ccd0>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x169eae250>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x169991d50>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x169935690>},
 'neon': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x16a7b2ed0>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x169eaf510>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x169a15210>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x169993610>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x169a8c4d0>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x16a002750>},
 'yearn-finance': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x16a002150>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x169fd4710>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x16a7e2610>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x169937890>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x169a14f10>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x169dcfc90>},
 'pancakeswap-token': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x16a003ed0>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x169a8dc90>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x1694c35d0>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x16a7b2e50>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x16a7b3150>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x16961b7d0>},
 'venice-token': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x16983ab10>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x16a4676d0>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x169b4da10>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x171dd2a50>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x16a7b0390>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x169fd7a50>},
 'chill-guy': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x169839a50>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x169fd61d0>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x16a536990>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x16981af50>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x16a48c0d0>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x169a8ed50>},
 'optimism': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x169839050>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x169a8c190>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x16a781ed0>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x169a16710>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x169ead850>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x169ce1190>},
 'balancer': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x16981ba50>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x16a267110>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x169839cd0>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x169dd5150>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x16a4e9f50>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x16987dd10>},
 'mantra-dao': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x16a7b1450>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x169fd73d0>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x16a4e9c90>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x1696b4a90>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x158570f50>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x169a8e7d0>},
 'anzen-finance': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x16a13f1d0>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x171dd2c50>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x16a7b1050>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x16a0a60d0>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x16a782d10>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x16a13c950>},
 'jasmycoin': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x169838150>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x169d40690>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x1698197d0>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x16983aad0>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x16a13ce10>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x16a781250>},
 'aioz-network': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x169dcff50>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x169ee3bd0>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x16a82de50>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x1696b7390>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x169c8e890>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x169baad10>},
 'helium': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x169dd41d0>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x171dd1cd0>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x16a465d50>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x16a0a6550>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x16a783710>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x16a13cb50>},
 'stellar': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x16a13c7d0>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x16a13e810>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x16a82eb90>,

In [3]:
# Select exactly which signals you want to use
usd_signals = [
   
    #'DonchianEnsembleUSD',
    'TrendMomentumUSD',
    #'RSI_Ensemble_Signal_USD'
]
 
btc_signals = [
    #'RSI_Oversold_BTC',
    #'RSI_Bullish_BTC'
    #'BullRegimeSignalBTC'
    #'RSI_Ensemble_Signal_BTC'
]



# Run the backtest for all assets at once
results = analyzer.backtest_assets(
    asset_ids=assets,
    start_date="2023-1-1",
    end_date="2025-04-30",
    initial_capital=10000.0,
    btc_cost=0.001,  # Lower cost for Bitcoin
    alt_cost=0.005,  # Higher cost for altcoins
    usd_signals=usd_signals,
    btc_signals=btc_signals,
    use_btc_filter=True,
   # allow_short=True
)

INFO: Running backtests for 220 assets
INFO: Using Bitcoin as a filter with signals: ['TrendMomentumUSD']
INFO: Running backtest for bitcoin from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'bitcoin' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Stored backtest results in asset bitcoin with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset bitcoin with name 'USD:TrendMomentumUSD'
WARNING: Bitcoin filter enabled but no decisions generated
INFO: Running backtest for cosmos (identified as ATOM)
INFO: Running backtest for cosmos from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'cosmos' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Stored backtest results in asset cosmos with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset cosmos with name 'USD:TrendMomentumUSD'
INFO: Running backtest for genesysgo-shadow (identified as SHDW)
INFO: Running backtest for genesysgo-shadow from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'genesysgo-shadow' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Stored backtest results in asset genesysgo-shadow with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset genesysgo-shadow with name 'USD:TrendMomentumUSD'
INFO: Running backtest for tezos (identified as XTZ)
INFO: Running backtest for tezos from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'tezos' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Stored backtest results in asset tezos with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset tezos with name 'USD:TrendMomentumUSD'
INFO: Running backtest for the-sandbox (identified as SAND)
INFO: Running backtest for the-sandbox from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'the-sandbox' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Stored backtest results in asset the-sandbox with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset the-sandbox with name 'USD:TrendMomentumUSD'
INFO: Running backtest for goatseus-maximus (identified as GOAT)
INFO: Running backtest for goatseus-maximus from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'goatseus-maximus' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Stored backtest results in asset goatseus-maximus with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset goatseus-maximus with name 'USD:TrendMomentumUSD'
INFO: Running backtest for story-2 (identified as IP)
INFO: Running backtest for story-2 from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'story-2' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Stored backtest results in asset story-2 with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset story-2 with name 'USD:TrendMomentumUSD'
INFO: Running backtest for mubarak (identified as MUBARAK)
INFO: Running backtest for mubarak from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'mubarak' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Stored backtest results in asset mubarak with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset mubarak with name 'USD:TrendMomentumUSD'
INFO: Running backtest for true-usd (identified as TUSD)
INFO: Running backtest for true-usd from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'true-usd' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Stored backtest results in asset true-usd with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset true-usd with name 'USD:TrendMomentumUSD'
INFO: Running backtest for near (identified as NEAR)
INFO: Running backtest for near from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'near' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Stored backtest results in asset near with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset near with name 'USD:TrendMomentumUSD'
INFO: Running backtest for alpha-finance (identified as ALPHA)
INFO: Running backtest for alpha-finance from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'alpha-finance' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Stored backtest results in asset alpha-finance with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset alpha-finance with name 'USD:TrendMomentumUSD'
INFO: Running backtest for spx6900 (identified as SPX)
INFO: Running backtest for spx6900 from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'spx6900' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Stored backtest results in asset spx6900 with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset spx6900 with name 'USD:TrendMomentumUSD'
INFO: Running backtest for crypto-com-chain (identified as CRO)
INFO: Running backtest for crypto-com-chain from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'crypto-com-chain' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Stored backtest results in asset crypto-com-chain with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset crypto-com-chain with name 'USD:TrendMomentumUSD'
INFO: Running backtest for sei-network (identified as SEI)
INFO: Running backtest for sei-network from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'sei-network' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Stored backtest results in asset sei-network with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset sei-network with name 'USD:TrendMomentumUSD'
INFO: Running backtest for clearpool (identified as CPOOL)
INFO: Running backtest for clearpool from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'clearpool' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Stored backtest results in asset clearpool with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset clearpool with name 'USD:TrendMomentumUSD'
INFO: Running backtest for matic-network (identified as MATIC)
INFO: Running backtest for matic-network from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'matic-network' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
ERROR: Error backtesting matic-network: cannot reindex on an axis with duplicate labels
INFO: Running backtest for akash-network (identified as AKT)
INFO: Running backtest for akash-network from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'akash-network' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Stored backtest results in asset akash-network with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset akash-network with name 'USD:TrendMomentumUSD'
INFO: Running backtest for fwog (identified as FWOG)
INFO: Running backtest for fwog from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'fwog' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Stored backtest results in asset fwog with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset fwog with name 'USD:TrendMomentumUSD'
INFO: Running backtest for ava-ai (identified as AVA)
INFO: Running backtest for ava-ai from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'ava-ai' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Stored backtest results in asset ava-ai with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset ava-ai with name 'USD:TrendMomentumUSD'
INFO: Running backtest for kekius-maximus (identified as KEKIUS)
INFO: Running backtest for kekius-maximus from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'kekius-maximus' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Stored backtest results in asset kekius-maximus with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset kekius-maximus with name 'USD:TrendMomentumUSD'
INFO: Running backtest for cookie (identified as COOKIE)
INFO: Running backtest for cookie from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'cookie' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Stored backtest results in asset cookie with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset cookie with name 'USD:TrendMomentumUSD'
INFO: Running backtest for ether-fi (identified as ETHFI)
INFO: Running backtest for ether-fi from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'ether-fi' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Stored backtest results in asset ether-fi with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset ether-fi with name 'USD:TrendMomentumUSD'
INFO: Running backtest for frax-share (identified as FRAX)
INFO: Running backtest for frax-share from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'frax-share' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Stored backtest results in asset frax-share with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset frax-share with name 'USD:TrendMomentumUSD'
INFO: Running backtest for cardano (identified as ADA)
INFO: Running backtest for cardano from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'cardano' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Stored backtest results in asset cardano with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset cardano with name 'USD:TrendMomentumUSD'
INFO: Running backtest for lisk (identified as LSK)
INFO: Running backtest for lisk from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'lisk' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Stored backtest results in asset lisk with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset lisk with name 'USD:TrendMomentumUSD'
INFO: Running backtest for slerf (identified as SLERF)
INFO: Running backtest for slerf from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'slerf' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Stored backtest results in asset slerf with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset slerf with name 'USD:TrendMomentumUSD'
INFO: Running backtest for arbitrum (identified as ARB)
INFO: Running backtest for arbitrum from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'arbitrum' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Stored backtest results in asset arbitrum with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset arbitrum with name 'USD:TrendMomentumUSD'
INFO: Running backtest for dogwifcoin (identified as WIF)
INFO: Running backtest for dogwifcoin from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'dogwifcoin' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Stored backtest results in asset dogwifcoin with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset dogwifcoin with name 'USD:TrendMomentumUSD'
INFO: Running backtest for pancakeswap-token (identified as CAKE)
INFO: Running backtest for pancakeswap-token from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'pancakeswap-token' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Stored backtest results in asset pancakeswap-token with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset pancakeswap-token with name 'USD:TrendMomentumUSD'
INFO: Running backtest for yearn-finance (identified as YFI)
INFO: Running backtest for yearn-finance from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'yearn-finance' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Stored backtest results in asset yearn-finance with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset yearn-finance with name 'USD:TrendMomentumUSD'
INFO: Running backtest for neon (identified as NEON)
INFO: Running backtest for neon from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'neon' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Stored backtest results in asset neon with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset neon with name 'USD:TrendMomentumUSD'
INFO: Running backtest for chill-guy (identified as CHILLGUY)
INFO: Running backtest for chill-guy from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'chill-guy' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Stored backtest results in asset chill-guy with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset chill-guy with name 'USD:TrendMomentumUSD'
INFO: Running backtest for optimism (identified as OP)
INFO: Running backtest for optimism from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'optimism' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Stored backtest results in asset optimism with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset optimism with name 'USD:TrendMomentumUSD'
INFO: Running backtest for venice-token (identified as VVV)
INFO: Running backtest for venice-token from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'venice-token' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Stored backtest results in asset venice-token with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset venice-token with name 'USD:TrendMomentumUSD'
INFO: Running backtest for balancer (identified as BAL)
INFO: Running backtest for balancer from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'balancer' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Stored backtest results in asset balancer with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset balancer with name 'USD:TrendMomentumUSD'
INFO: Running backtest for mantra-dao (identified as OM)
INFO: Running backtest for mantra-dao from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'mantra-dao' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Stored backtest results in asset mantra-dao with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset mantra-dao with name 'USD:TrendMomentumUSD'
INFO: Running backtest for aioz-network (identified as AIOZ)
INFO: Running backtest for aioz-network from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'aioz-network' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Stored backtest results in asset aioz-network with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset aioz-network with name 'USD:TrendMomentumUSD'
INFO: Running backtest for jasmycoin (identified as JASMY)
INFO: Running backtest for jasmycoin from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'jasmycoin' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Stored backtest results in asset jasmycoin with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset jasmycoin with name 'USD:TrendMomentumUSD'
INFO: Running backtest for helium (identified as HNT)
INFO: Running backtest for helium from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'helium' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Stored backtest results in asset helium with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset helium with name 'USD:TrendMomentumUSD'
INFO: Running backtest for stellar (identified as XLM)
INFO: Running backtest for stellar from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'stellar' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Stored backtest results in asset stellar with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset stellar with name 'USD:TrendMomentumUSD'
INFO: Running backtest for anzen-finance (identified as ANZ)
INFO: Running backtest for anzen-finance from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'anzen-finance' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Stored backtest results in asset anzen-finance with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset anzen-finance with name 'USD:TrendMomentumUSD'
INFO: Running backtest for bitcoin (identified as BTC)
INFO: Running backtest for dogecoin (identified as DOGE)
INFO: Running backtest for dogecoin from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'dogecoin' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Stored backtest results in asset dogecoin with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset dogecoin with name 'USD:TrendMomentumUSD'
INFO: Running backtest for velvet (identified as VELVET)
INFO: Running backtest for velvet from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'velvet' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
WARNING: No data available for velvet in the specified date range
INFO: Running backtest for botto (identified as BOTTO)
INFO: Running backtest for botto from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'botto' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Stored backtest results in asset botto with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset botto with name 'USD:TrendMomentumUSD'
INFO: Running backtest for verasity (identified as VRA)
INFO: Running backtest for verasity from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'verasity' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Stored backtest results in asset verasity with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset verasity with name 'USD:TrendMomentumUSD'
INFO: Running backtest for kaspa (identified as KAS)
INFO: Running backtest for kaspa from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'kaspa' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Stored backtest results in asset kaspa with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset kaspa with name 'USD:TrendMomentumUSD'
INFO: Running backtest for arweave (identified as AR)
INFO: Running backtest for arweave from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'arweave' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Stored backtest results in asset arweave with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset arweave with name 'USD:TrendMomentumUSD'
INFO: Running backtest for kaito (identified as KAITO)
INFO: Running backtest for kaito from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'kaito' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Stored backtest results in asset kaito with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset kaito with name 'USD:TrendMomentumUSD'
INFO: Running backtest for neiro-3 (identified as NEIRO)
INFO: Running backtest for neiro-3 from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'neiro-3' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Stored backtest results in asset neiro-3 with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset neiro-3 with name 'USD:TrendMomentumUSD'
INFO: Running backtest for polymath (identified as POLY)
INFO: Running backtest for polymath from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Starting backtest for asset 'polymath' from 2023-01-01 00:00:00 to 2025-04-30 00:00:00
INFO: Stored backtest results in asset polymath with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset polymath with name 'USD:TrendMomentumUSD'

In [4]:
# Filter for results where strategy outperforms buy & hold, sorted by outperformance
outperformance_df = results['summary'].copy()
outperformance_df['Outperformance'] = outperformance_df['Total Return (%)'] - outperformance_df['Buy & Hold Return (%)']
# Filter for positive outperformance and positive total return
# Also exclude stablecoins like USDT, USDC, TUSD
filtered_df = outperformance_df[
    ((outperformance_df['Outperformance'] > 0) | 
    (outperformance_df['Total Return (%)'] > 0)) &
    (~outperformance_df.index.isin(['USDT', 'USDC', 'TUSD']))
]
filtered_df.sort_values('Outperformance', ascending=False)[:60]

,Total Return (%),Peak Return (%),Buy & Hold Return (%),Buy & Hold Peak (%),Sharpe Ratio,Buy & Hold Sharpe,Sortino Ratio,Buy & Hold Sortino,Max Drawdown (%),Buy & Hold Drawdown (%),Annualized Volatility (%),Buy & Hold Volatility (%),Trade Count,Total Cost,Outperformance
Asset,,,,,,,,,,,,,,,
VIRTUAL,59112.05,59112.05,10577.26,31247.24,65.72,14.06,125.88,33.78,-47.94,-90.48,177.00,225.14,5,89621.12,48534.79
WELL,6837.27,12191.94,758.01,3023.13,3.83,0.91,6.08,1.98,-61.36,-85.26,135.22,165.90,12,27467.25,6079.26
OM,7020.35,9193.10,1633.78,30043.89,4.48,1.67,7.75,2.32,-65.81,-94.25,117.14,144.02,16,32617.83,5386.57
AIOZ,3329.33,4347.94,1213.51,3728.29,2.58,1.23,5.29,2.99,-58.93,-84.22,137.99,164.26,16,24828.70,2115.82
CHEX,3199.06,7645.37,1350.48,5447.51,2.87,1.28,4.36,2.33,-66.73,-81.40,121.57,167.57,19,21818.35,1848.58
AERO,2522.78,3128.58,888.32,3497.30,4.16,1.58,8.66,4.28,-55.69,-85.92,155.37,196.18,10,13844.11,1634.46
COOKIE,1242.62,1646.90,58.37,441.12,9.86,0.30,16.59,0.77,-46.55,-88.25,184.34,231.96,3,1754.88,1184.25
BOTTO,1265.47,3498.52,372.64,4005.01,1.53,0.58,2.05,1.15,-74.08,-89.41,135.90,162.43,14,12309.25,892.83
RON,990.06,2224.33,102.44,1519.39,2.65,0.39,2.77,0.61,-57.48,-89.47,67.52,89.94,13,15181.85,887.62
SUI,844.69,859.48,150.71,278.57,2.67,0.53,4.41,1.02,-49.35,-74.31,78.06,111.15,10,3235.22,693.98
SEILOR,534.50,3858.56,-97.33,276.14,1.03,-0.37,1.79,-0.83,-83.97,-99.56,187.74,238.88,8,7830.29,631.83
CPOOL,938.10,1230.17,315.28,1551.90,1.47,0.57,2.29,1.09,-71.19,-81.60,117.40,148.43,15,4716.75,622.82
WLD,468.91,613.28,-48.40,437.61,1.53,-0.22,2.15,-0.44,-53.75,-94.74,109.18,143.33,9,2713.72,517.31
NTX,584.30,1234.01,91.94,950.56,1.25,0.25,1.58,0.47,-67.63,-88.48,102.36,131.80,14,7550.66,492.36
RUNE,416.92,883.01,4.69,729.69,1.30,0.02,1.73,0.03,-52.28,-90.65,79.02,114.11,15,6043.55,412.23
ML,333.76,1602.15,-76.63,488.64,0.67,-0.24,1.10,-0.59,-76.13,-96.82,150.91,208.30,14,6657.02,410.39
SNEK,1159.38,3067.39,761.50,1981.65,2.63,1.15,3.14,1.91,-62.39,-90.24,102.08,175.90,14,10995.78,397.88
VRA,347.32,603.23,-22.66,561.36,1.08,-0.09,1.23,-0.16,-61.88,-93.03,83.88,117.82,15,3730.05,369.98
KUJI,288.01,592.37,-32.51,1148.43,1.03,-0.13,1.23,-0.19,-53.01,-96.30,76.63,123.67,17,3845.64,320.52
SEI,328.20,646.03,20.87,493.36,1.52,0.09,2.15,0.18,-61.81,-86.49,88.31,123.51,11,4645.04,307.33
CRV,279.89,448.45,34.72,138.03,1.06,0.13,1.28,0.21,-50.23,-83.35,73.17,104.11,15,2868.69,245.17
ARKM,234.72,607.70,-10.04,501.90,0.96,-0.04,1.36,-0.08,-67.67,-89.50,101.06,133.41,12,2957.02,244.76
STX,495.98,1350.92,279.05,1631.35,1.26,0.66,1.90,1.28,-64.36,-85.72,91.15,116.15,14,8030.28,216.93
AXL,189.62,647.40,-24.90,368.68,0.78,-0.11,1.00,-0.20,-63.77,-87.88,73.75,102.34,14,4532.29,214.52
PRIME,183.98,748.87,-22.43,642.05,0.65,-0.08,0.95,-0.16,-71.31,-91.75,95.00,137.69,13,3772.54,206.41
YGG,232.69,681.32,26.88,919.32,0.58,0.08,0.79,0.14,-66.27,-91.53,116.14,142.88,12,2756.79,205.81
HNT,356.90,563.63,153.95,567.55,1.02,0.41,1.65,0.84,-55.46,-76.29,90.02,119.59,16,5181.79,202.95
POLIS,111.80,238.34,-79.70,95.06,0.49,-0.44,0.58,-0.82,-50.98,-91.57,77.83,111.99,12,1648.82,191.50
MYRIA,102.17,506.31,-87.62,106.10,0.43,-0.47,0.56,-0.90,-68.77,-95.80,93.39,136.17,12,2728.40,189.79
RDNT,152.66,708.89,-35.71,1062.21,0.50,-0.14,0.70,-0.25,-79.04,-96.43,98.01,124.84,14,4256.87,188.37
BABYDOGE,217.48,750.43,36.38,503.87,0.63,0.11,0.89,0.22,-63.13,-81.66,101.43,134.12,17,5247.19,181.10
HBAR,557.00,1179.32,376.56,882.10,1.43,0.83,2.39,1.83,-48.87,-72.83,87.17,114.88,14,4501.65,180.44
AIDOGE,163.78,995.40,-10.95,408.73,0.41,-0.03,0.46,-0.05,-81.27,-94.19,148.24,206.26,13,4054.09,174.73
AR,176.25,588.22,8.02,655.35,0.64,0.03,0.86,0.05,-68.64,-89.78,84.86,114.39,15,3719.35,168.23
HYPC,74.43,209.26,-82.37,183.95,0.52,-0.47,0.50,-0.83,-61.15,-98.30,62.50,123.76,10,1851.10,156.80
FET,853.39,2617.96,704.71,3467.57,1.71,1.17,2.45,2.29,-75.84,-88.42,95.47,124.28,19,13842.34,148.68
ALCH,247.77,397.01,104.52,208.66,10.38,1.24,15.00,3.03,-40.58,-92.72,190.32,380.37,1,223.88,143.25
DOGE,279.33,560.37,145.37,563.59,1.15,0.54,1.42,0.86,-42.56,-69.56,67.32,86.97,14,2757.51,133.96
PENGU,66.68,95.82,-60.32,50.13,4.29,-0.49,4.17,-0.93,-14.88,-91.00,70.43,185.85,1,133.34,127.00
AKT,781.38,1517.49,655.30,3075.20,1.62,1.12,2.53,2.31,-64.03,-85.43,95.67,123.22,16,9438.11,126.08
VVV,47.32,47.32,-76.85,-14.74,8.17,-0.41,NaN,-0.59,-3.02,-80.31,43.75,244.29,1,123.66,124.17
SHIB,176.88,486.91,62.65,345.82,0.70,0.24,1.04,0.44,-56.62,-70.68,78.83,95.07,17,4241.67,114.23
EVAN,23.04,91.28,-89.88,301.37,0.42,-0.29,0.76,-0.58,-35.68,-98.96,145.09,348.99,1,111.52,112.92
FWOG,394.95,622.77,284.77,5009.11,6.49,1.53,7.39,3.75,-45.76,-96.41,114.29,328.02,3,801.74,110.18
ILV,49.14,193.41,-59.99,287.64,0.28,-0.34,0.29,-0.55,-61.41,-92.95,67.83,96.86,16,2431.48,109.13
STRDY,174.75,597.63,66.29,732.30,0.66,0.18,1.06,0.48,-60.62,-93.21,203.77,292.24,5,1333.43,108.46
ACA,33.22,213.22,-71.08,78.04,0.16,-0.38,0.24,-0.70,-65.06,-86.59,81.02,109.74,16,2190.30,104.30
SCRT,35.81,184.87,-65.54,42.11,0.16,-0.32,0.22,-0.63,-69.81,-81.78,90.61,114.00,16,2098.58,101.35
GENE,12.11,179.41,-88.83,125.43,0.04,-0.33,0.05,-0.74,-82.72,-95.74,130.71,182.54,11,1264.61,100.94
VISTA,31.59,551.10,-69.08,184.71,0.25,-0.24,0.38,-0.68,-79.79,-89.52,203.15,347.78,4,718.65,100.67
LUNA,7.27,112.56,-85.76,79.69,0.03,-0.49,0.05,-0.86,-58.53,-93.74,88.41,115.32,14,1603.91,93.03
AURY,7.59,218.57,-82.24,174.47,0.04,-0.52,0.04,-0.85,-69.75,-94.95,77.57,100.65,16,1893.76,89.83
PEOPLE,67.06,430.49,-21.56,568.55,0.25,-0.07,0.33,-0.12,-71.38,-92.37,98.15,140.63,17,2452.36,88.62
JASMY,492.80,1109.57,405.11,1652.22,1.12,0.79,1.64,1.54,-62.79,-84.08,102.71,127.53,15,4843.87,87.69
ZK,13.58,90.16,-72.46,22.86,0.27,-0.70,0.23,-1.07,-41.24,-82.23,59.40,110.40,5,550.51,86.04
FLUID,965.40,1722.11,882.76,2187.78,1.98,1.51,2.59,2.49,-58.59,-69.50,89.07,110.66,18,9435.94,82.64
BIO,-8.71,0.00,-91.23,-0.41,-1.67,-0.64,-0.41,-0.98,-8.71,-94.25,14.94,156.81,1,95.65,82.52
BIG,0.00,0.00,-80.86,0.00,0.00,-0.21,0.00,-0.38,0.00,-79.31,0.00,484.03,0,0.00,80.86
CRO,132.99,297.71,55.14,277.82,0.62,0.24,0.80,0.46,-44.83,-65.81,71.20,86.18,17,2722.81,77.85
MANA,79.95,193.87,4.40,167.24,0.42,0.02,0.49,0.03,-58.12,-74.55,68.76,91.31,19,3030.44,75.55

In [5]:
# Filter out assets where buy & hold Sharpe ratio is larger than the strategy's Sharpe ratio
results['asset_results'].get('fartcoin')['trades']

[{'trade_id': 1,
  'asset': 'fartcoin',
  'entry_date': Timestamp('2024-12-09 00:00:00'),
  'exit_date': Timestamp('2025-01-12 00:00:00'),
  'holding_days': 34,
  'entry_price': 0.337665,
  'exit_price': 0.768864,
  'price_return': 1.2770023544045133,
  'entry_value': 9950.0,
  'entry_cost': 50.0,
  'exit_value': 22656.17342632491,
  'exit_cost': 113.28086713162455,
  'trade_return': 1.265617342632491,
  'is_open': False},
 {'trade_id': 2,
  'asset': 'fartcoin',
  'entry_date': Timestamp('2025-01-14 00:00:00'),
  'exit_date': Timestamp('2025-01-28 00:00:00'),
  'holding_days': 14,
  'entry_price': 1.022,
  'exit_price': 0.807749,
  'price_return': -0.20963894324853227,
  'entry_value': 22430.178096397318,
  'entry_cost': 112.71446279596643,
  'exit_value': 17727.93926339221,
  'exit_cost': 88.63969631696105,
  'trade_return': -0.21359074853228954,
  'is_open': False},
 {'trade_id': 3,
  'asset': 'fartcoin',
  'entry_date': Timestamp('2025-03-22 00:00:00'),
  'exit_date': Timestamp('2025-04-30 00:00:00'),
  'holding_days': 39,
  'entry_price': 0.420938,
  'exit_price': 1.24,
  'price_return': 1.9458019945930283,
  'entry_value': 17551.103069239874,
  'entry_cost': 88.19649783537625,
  'exit_value': 51702.07442867464,
  'exit_cost': 258.5103721433732,
  'trade_return': 1.9310729846200632,
  'is_open': False}]

In [ ]:
# Get the results dataframe for Bitcoin
bitcoin_results = results['asset_results'].get('dogecoin')['results_df']

# Import plotly
import plotly.graph_objects as go

# Create a plotly figure
fig = go.Figure()

# Add traces for portfolio value and buy & hold value
fig.add_trace(
    go.Scatter(
        x=bitcoin_results.index,
        y=bitcoin_results['portfolio_value'],
        mode='lines',
        name='SOROS V1',
        line=dict(width=2, color='blue')
    )
)

fig.add_trace(
    go.Scatter(
        x=bitcoin_results.index,
        y=bitcoin_results['buy_hold_value'],
        mode='lines',
        name='Buy & Hold',
        line=dict(width=2, color='red')
    )
)

# Update layout
fig.update_layout(
    title='SOROS vs. Buy n Hold',
    xaxis_title='',
    yaxis_title='Valor da Carteira (USD)',
    legend=dict(x=0.01, y=0.99),
    hovermode='x unified',
    template='plotly_white'
)

# Show the figure
fig.show()

In [ ]:
results['asset_results'].get('pendle')['metrics_comparison']

In [ ]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

# Read the CSV file
etf = pd.read_csv('/Users/valter.rebelo/MissionControl/ETF flows - Sheet1.csv')

# Replace all '-' values with 0
etf = etf.replace('-', 0)

# Convert columns to numeric where possible
for col in etf.columns:
    if col != 'Date':  # Skip the Date column
        etf[col] = pd.to_numeric(etf[col], errors='coerce')

# Convert Date to datetime
etf['Date'] = pd.to_datetime(etf['Date'], format='%d %b %Y')
etf.set_index('Date', inplace=True)

# Get BTC price data
btc_data = analyzer.get_asset_data('bitcoin').price_data
btc_close = btc_data['close'].to_frame('BTC_Price')

# Merge ETF flows with BTC price data
merged_data = etf.join(btc_close, how='left')

# Resample to weekly data
# For ETF flows, sum the daily flows
# For BTC price, take the last price of the week
weekly_etf = etf.resample('W').sum()
weekly_btc = btc_close.resample('W').last()

# Calculate weekly BTC returns
weekly_btc['BTC_Return'] = weekly_btc['BTC_Price'].pct_change() * 100

# Merge weekly ETF flows with weekly BTC returns
weekly_data = weekly_etf.join(weekly_btc, how='left')

# Create a scatter plot with regression line
plt.figure(figsize=(10, 6))

# Get all data points except the two most recent ones
main_data = weekly_data.iloc[:-2]
# Get the most recent data point
most_recent = weekly_data.iloc[-1:]
# Get the second most recent data point
second_most_recent = weekly_data.iloc[-2:-1]

# Plot main data points
sns.regplot(x='Total', y='BTC_Return', data=main_data, 
            scatter_kws={'alpha':0.6, 'color':'blue'}, 
            line_kws={'color':'red'})

# Plot the most recent data point with a different color
plt.scatter(most_recent['Total'], most_recent['BTC_Return'], 
            color='green', s=100, alpha=0.8, label='Dado Mais Recente')

# Plot the second most recent data point with a different color
plt.scatter(second_most_recent['Total'], second_most_recent['BTC_Return'], 
            color='purple', s=100, alpha=0.8, label='Segundo Dado Mais Recente')

plt.title('Retornos do BTC e Fluxos de ETFs Semanais')
plt.xlabel('Fluxos de ETFs (Total)')
plt.ylabel('Retorno do BTC (%)')
plt.grid(True, alpha=0.3)
plt.legend()

# Calculate correlation and regression
correlation = weekly_data['Total'].corr(weekly_data['BTC_Return'])
slope, intercept, r_value, p_value, std_err = stats.linregress(
    weekly_data['Total'].dropna(), 
    weekly_data['BTC_Return'].dropna()
)

# Add correlation and regression stats to the plot
plt.annotate(f'Correlation: {correlation:.3f}\nR-squared: {r_value**2:.3f}\np-value: {p_value:.4f}', 
             xy=(0.05, 0.85), xycoords='axes fraction', 
             bbox=dict(boxstyle="round,pad=0.3", fc="white", ec="gray", alpha=0.8))

plt.tight_layout()
plt.show()

# Display the data
weekly_data

In [ ]:
results['formatted_summary']

In [ ]:
analyzer.get_asset_data('ethereum').get_price_data()

In [ ]:
import pandas as pd
df = pd.DataFrame(results['summary_data'])
df.set_index('asset_id', inplace=True)
df

In [ ]:
asset_id = 'bitcoin'

In [ ]:
import numpy as np
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots


# Get price data
asset_data = analyzer.get_asset_data(asset_id).price_data
close_prices = asset_data['close']

# Determine if we should show BTC charts based on asset_id
show_btc_charts = asset_id != 'bitcoin'

# Create subplots with appropriate number of rows
if show_btc_charts:
    # Show both USD and BTC charts (4 rows)
    fig = make_subplots(rows=4, cols=1, 
                        subplot_titles=("TrendMomentumBTC", 
                                       "TrendMomentumUSD", 
                                       "RSI Bullish BTC",
                                       "RSI Bullish USD"),
                        vertical_spacing=0.1,
                        shared_xaxes=True)
    num_rows = 4
else:
    # Only show USD charts (2 rows)
    fig = make_subplots(rows=2, cols=1, 
                        subplot_titles=("Momentum 1 Model", 
                                        "Momentum 2 Model"),
                        vertical_spacing=0.1,
                        shared_xaxes=True)
    num_rows = 2

# Add background price line with low alpha to all charts
for i in range(1, num_rows + 1):
    fig.add_trace(go.Scatter(
        x=close_prices.index, 
        y=close_prices, 
        mode='lines', 
        name='Price',
        line=dict(color='gray', width=1),
        opacity=0.2,
        showlegend=False if i > 1 else True
    ), row=i, col=1)

# Current row tracker for USD-only mode
current_row = 1

# 1. Donchian Ensemble BTC (only if not bitcoin)
if show_btc_charts:
    values_btc = analyzer.get_asset_data(asset_id).get_signal('TrendMomentumBTC').values
    bull_btc = values_btc == 1
    bear_btc = values_btc == 0

    green_column_btc = pd.Series(np.nan, index=close_prices.index)
    red_column_btc = pd.Series(np.nan, index=close_prices.index)

    green_column_btc[bull_btc] = close_prices[bull_btc]
    red_column_btc[bear_btc] = close_prices[bear_btc]

    fig.add_trace(go.Scatter(
        x=green_column_btc.index, 
        y=green_column_btc, 
        mode='lines', 
        name='Bullish BTC (1)',
        line=dict(color='green')
    ), row=1, col=1)

    fig.add_trace(go.Scatter(
        x=red_column_btc.index, 
        y=red_column_btc, 
        mode='lines', 
        name='Bearish/Neutral BTC (0)',
        line=dict(color='red')
    ), row=1, col=1)
    
    current_row += 1

# 2. Donchian Ensemble USD
values_usd = analyzer.get_asset_data(asset_id).get_signal('TrendMomentumUSD').values
bull_usd = values_usd == 1
bear_usd = values_usd == 0

green_column_usd = pd.Series(np.nan, index=close_prices.index)
red_column_usd = pd.Series(np.nan, index=close_prices.index)

green_column_usd[bull_usd] = close_prices[bull_usd]
red_column_usd[bear_usd] = close_prices[bear_usd]

fig.add_trace(go.Scatter(
    x=green_column_usd.index, 
    y=green_column_usd, 
    mode='lines', 
    name='Apetite por Risco',
    line=dict(color='green'),
    showlegend=current_row == 1  # Only show in legend if it's the first row
), row=current_row, col=1)

fig.add_trace(go.Scatter(
    x=red_column_usd.index, 
    y=red_column_usd, 
    mode='lines', 
    name='Aversão por Risco',
    line=dict(color='red'),
    showlegend=current_row == 1  # Only show in legend if it's the first row
), row=current_row, col=1)

current_row += 1

# 3. RSI Bullish BTC (only if not bitcoin)
if show_btc_charts:
    rsi_bullish_btc = analyzer.get_asset_data(asset_id).get_signal('RSI_Bullish_BTC').values
    
    bull_rsi_btc = rsi_bullish_btc == 1
    not_bull_rsi_btc = ~bull_rsi_btc

    green_column_rsi_btc = pd.Series(np.nan, index=close_prices.index)
    red_column_rsi_btc = pd.Series(np.nan, index=close_prices.index)

    green_column_rsi_btc[bull_rsi_btc] = close_prices[bull_rsi_btc]
    red_column_rsi_btc[not_bull_rsi_btc] = close_prices[not_bull_rsi_btc]

    fig.add_trace(go.Scatter(
        x=green_column_rsi_btc.index, 
        y=green_column_rsi_btc, 
        mode='lines', 
        name='RSI Bullish BTC (1)',
        line=dict(color='green'),
        showlegend=True
    ), row=current_row, col=1)

    fig.add_trace(go.Scatter(
        x=red_column_rsi_btc.index, 
        y=red_column_rsi_btc, 
        mode='lines', 
        name='Not RSI Bullish BTC (0)',
        line=dict(color='red'),
        showlegend=True
    ), row=current_row, col=1)
    
    current_row += 1

# 4. RSI Bullish USD
rsi_bullish_usd = analyzer.get_asset_data(asset_id).get_signal('RSI_Bullish_USD').values

bull_rsi_usd = rsi_bullish_usd == 1
not_bull_rsi_usd = ~bull_rsi_usd

green_column_rsi_usd = pd.Series(np.nan, index=close_prices.index)
red_column_rsi_usd = pd.Series(np.nan, index=close_prices.index)

green_column_rsi_usd[bull_rsi_usd] = close_prices[bull_rsi_usd]
red_column_rsi_usd[not_bull_rsi_usd] = close_prices[not_bull_rsi_usd]

fig.add_trace(go.Scatter(
    x=green_column_rsi_usd.index, 
    y=green_column_rsi_usd, 
    mode='lines', 
    name='RSI Bullish USD (1)',
    line=dict(color='green'),
    showlegend=current_row == 3  # Only show in legend if it's the first row in USD-only mode
), row=current_row, col=1)

fig.add_trace(go.Scatter(
    x=red_column_rsi_usd.index, 
    y=red_column_rsi_usd, 
    mode='lines', 
    name='Not RSI Bullish USD (0)',
    line=dict(color='red'),
    showlegend=current_row == 3  # Only show in legend if it's the first row in USD-only mode
), row=current_row, col=1)

# Update layout
fig.update_layout(
    title=f'SOROS - {asset_id.capitalize()}',
    xaxis_title='',
    legend_title='Diagnóstico',
    height=800 if asset_id == 'bitcoin' else 1600,  # Adjust height based on number of charts
    width=1000,
    template='plotly_white'
)

# Update y-axis titles for all rows
for i in range(1, num_rows + 1):
    fig.update_yaxes(title_text="Preço (USD)", row=i, col=1)

# Show the plot
fig.show()

In [ ]:
analyzer.get_asset_data('dogecoin')

In [ ]:
results['asset_results'].get(asset_id)['metrics_comparison']

In [6]:

import pandas as pd
def display_all_assets_signals_for_date(analyzer, date_str):
    """
    Display Donchian Ensemble, RSI, and Variance signals for all assets on a specific date
    
    Args:
        analyzer: PortfolioAnalyzer instance
        date_str: Date string in 'YYYY-MM-DD' format
    
    Returns:
        DataFrame with signal values for all assets on the specified date
    """
    # Convert date string to datetime
    date = pd.to_datetime(date_str)
    
    # List of signals to check
    signals_to_check = [
        #'DonchianEnsembleBTC',
        #'DonchianEnsembleUSD',
        'TrendMomentumBTC',
    
        'TrendMomentumUSD',
        #'BullHighVarianceSignalBTC',
        #'BullHighVarianceSignalUSD',
        #'BullLowVarianceSignalBTC',
       # 'BullLowVarianceSignalUSD'
    ]
    
    # Get all asset IDs
    asset_ids = sorted(list(analyzer.assets.keys()))
    
    # Create empty DataFrame with assets as rows and signals as columns
    result_df = pd.DataFrame(index=asset_ids, columns=signals_to_check)
    
    # Fill the DataFrame with signal values
    for asset_id in asset_ids:
        asset_data = analyzer.get_asset_data(asset_id)
        if asset_data is None:
            continue
            
        for signal_name in signals_to_check:
            try:
                signal_data = asset_data.get_signal(signal_name)
                if signal_data is not None:
                    # Access the signal values directly
                    # SignalData objects typically have a 'values' attribute that is a pandas Series
                    if hasattr(signal_data, 'values') and isinstance(signal_data.values, pd.Series):
                        signal_series = signal_data.values
                        if date in signal_series.index:
                            result_df.loc[asset_id, signal_name] = signal_series.loc[date]
                        else:
                            result_df.loc[asset_id, signal_name] = None
                    else:
                        result_df.loc[asset_id, signal_name] = None
                else:
                    result_df.loc[asset_id, signal_name] = None
            except Exception as e:
                print(f"Error getting {signal_name} for {asset_id} on {date_str}: {e}")
                result_df.loc[asset_id, signal_name] = None
    
    # Replace NaN with None for cleaner display
    result_df = result_df.fillna("N/A")
    
    # Add a sum column that counts the number of active signals (value of 1)
    result_df['Signal_Sum'] = result_df.apply(
        lambda row: sum(1 for val in row if val == 1), 
        axis=1
    )

    result_df = result_df.sort_index()
    
    return result_df

# Example usage - replace with your desired date
date_to_check = "2025-5-11"   # Change to your desired date

signals_df = display_all_assets_signals_for_date(analyzer, date_to_check)
print(f"Signals for all assets on {date_to_check}:")
display(signals_df.tail(60))

Signals for all assets on 2025-5-11:

                      TrendMomentumBTC TrendMomentumUSD  Signal_Sum
pump-fun                           N/A              N/A           0
quant-network                        1                1           2
radiant-capital                      1                1           2
rainbow-token-2                      0                0           0
rari-governance-token                0                0           0
raydium                              1                1           2
render-token                         1                1           2
ripple                               0                1           1
ronin                                0                1           1
secret                               0                1           1
sei-network                          1                1           2
serum                                0                1           1
shiba-inu                            1                1           2
siren-2                              1                1           2
slerf                                1                1           2
smartcash                            0                0           0
snek                                 1                1           2
solana                               1                1           2
solayer                              0                0           0
sonic-3                              0                1           1
spell-token                          0                1           1
spx6900                              1                1           2
star-atlas-dao                       0                1           1
stellar                              0                1           1
story-2                              0                1           1
sturdy                               0                1           1
sui                                  1                1           2
sushi                                1                1           2
swarm                                0                0           0
syrup                                1                1           2
terra-luna-2                         1                1           2
tether                               0                1           1
tezos                                0                1           1
the-open-network                     0                1           1
the-sandbox                          1                1           2
thorchain                            1                1           2
tokenbot-2                           0                0           0
tribe-2                              0                1           1
tron                                 0                1           1
true-usd                             0                1           1
turbo                                1                1           2
uniswap                              1                1           2
usd-coin                             0                1           1
useless-3                            0                0           0
vela-token                           0                0           0
velvet                             N/A              N/A           0
venice-token                         1                1           2
verasity                             1                1           2
virtual-protocol                     1                1           2
wibx                                 0                0           0
worldcoin-wld                        1                1           2
wrapped-nxm                          1                1           2
y                                    1                1           2
yearn-finance                        1                1           2
yield-guild-games                    1                1           2
yne                                  0                0           0
zcash                                1                1           2
zebec-network                        1                1           2
zeus-network                         0                0           0
zksync                               0                1           1

In [7]:
def plot_signal_sums_through_time(analyzer, start_date=None, end_date=None, min_market_cap=1000000000, max_market_cap=None):
    """
    Create an interactive plotly lollipop chart showing signal sums for all assets through time.
    Assets are on the Y-axis and dates on the X-axis.
    
    Args:
        analyzer: The PortfolioAnalyzer instance
        start_date: Optional start date string in format 'YYYY-MM-DD'. If None, uses earliest available date.
        end_date: Optional end date string in format 'YYYY-MM-DD'. If None, uses latest available date.
        min_market_cap: Minimum market capitalization in USD to include an asset
        max_market_cap: Maximum market capitalization in USD to include an asset
    
    Returns:
        DataFrame with signal sums over time
    """
    import plotly.graph_objects as go
    import pandas as pd
    from soros_system.data.data_loader import DataLoader
    
    # Get all asset IDs
    asset_ids = list(analyzer.assets.keys())
    
    # Exclude stablecoins
    excluded_assets = ['tether', 'usd-coin', 'true-usd']
    asset_ids = [asset_id for asset_id in asset_ids if asset_id not in excluded_assets]
    
    # Create a data loader to get tickers
    data_loader = DataLoader(
        data_path=analyzer.data_path,
        btc_data_path=analyzer.btc_data_path,
        ssr_data_path=analyzer.ssr_data_path,
        market_data_path=analyzer.market_data_path,
        asset_ids=analyzer.asset_ids
    )
    
    # Create a mapping from asset_id to ticker
    ticker_mapping = {}
    for asset_id in asset_ids:
        ticker = data_loader.get_ticker_from_id(asset_id)
        ticker_mapping[asset_id] = ticker.upper() if ticker else asset_id.upper()
    
    # Create a dictionary to store market caps
    market_caps = {}
    
    # Filter assets by market cap if specified
    if min_market_cap > 0 or max_market_cap is not None:
        filtered_asset_ids = []
        for asset_id in asset_ids:
            asset_data = analyzer.get_asset_data(asset_id)
            if asset_data is not None:
                # Try different ways to access market cap
                market_cap = None
                
                # Try to get from metadata if available
                if hasattr(asset_data, 'metadata') and asset_data.metadata:
                    market_cap = asset_data.metadata.get('market_cap')
                
                # Try to get from asset_data directly
                if market_cap is None and hasattr(asset_data, 'market_cap'):
                    market_cap = asset_data.market_cap
                
                # Try to get from price_data if available
                if market_cap is None and hasattr(asset_data, 'price_data'):
                    if 'market_cap' in asset_data.price_data.columns:
                        # Use the most recent market cap value
                        market_cap = asset_data.price_data['market_cap'].iloc[-1]
                
                # Store market cap for later sorting
                market_caps[asset_id] = market_cap if market_cap is not None else 0
                
                # Debug print to see what we're working with
                ticker = ticker_mapping.get(asset_id, asset_id)
                print(f"Asset: {ticker}, Market Cap: {market_cap}")
                
                # Check if market cap meets criteria
                meets_min_criteria = market_cap is None or market_cap >= min_market_cap
                meets_max_criteria = max_market_cap is None or (market_cap is not None and market_cap <= max_market_cap)
                
                # Include asset if market cap meets criteria
                if meets_min_criteria and meets_max_criteria:
                    filtered_asset_ids.append(asset_id)
                    if market_cap is None:
                        print(f"Warning: No market cap data for {ticker}, including it anyway")
        
        asset_ids = filtered_asset_ids
        
        if not asset_ids:
            market_cap_msg = f"with market cap >= {min_market_cap}"
            if max_market_cap is not None:
                market_cap_msg += f" and <= {max_market_cap}"
            print(f"No assets found {market_cap_msg}")
            return pd.DataFrame()
    else:
        # If no market cap filtering, still collect market caps for sorting
        for asset_id in asset_ids:
            asset_data = analyzer.get_asset_data(asset_id)
            if asset_data is not None:
                market_cap = None
                
                if hasattr(asset_data, 'metadata') and asset_data.metadata:
                    market_cap = asset_data.metadata.get('market_cap')
                
                if market_cap is None and hasattr(asset_data, 'market_cap'):
                    market_cap = asset_data.market_cap
                
                if market_cap is None and hasattr(asset_data, 'price_data'):
                    if 'market_cap' in asset_data.price_data.columns:
                        market_cap = asset_data.price_data['market_cap'].iloc[-1]
                
                market_caps[asset_id] = market_cap if market_cap is not None else 0
    
    # Determine date range
    if start_date is None or end_date is None:
        # Find the common date range across assets
        min_dates = []
        max_dates = []
        for asset_id in asset_ids:
            asset_data = analyzer.get_asset_data(asset_id)
            if asset_data is not None and hasattr(asset_data, 'price_data') and len(asset_data.price_data) > 0:
                min_dates.append(asset_data.price_data.index[0])
                max_dates.append(asset_data.price_data.index[-1])
        
        if not min_dates or not max_dates:
            print("No data available for any assets")
            return
        
        if start_date is None:
            start_date = max(min_dates).strftime('%Y-%m-%d')
        if end_date is None:
            end_date = min(max_dates).strftime('%Y-%m-%d')
    
    # Convert to datetime objects
    start_dt = pd.to_datetime(start_date)
    end_dt = pd.to_datetime(end_date)
    
    # Generate a list of dates - daily intervals as requested
    date_range = pd.date_range(start=start_dt, end=end_dt, freq='D')
    date_strings = [date.strftime('%Y-%m-%d') for date in date_range]
    
    # Create a DataFrame to store signal sums for each asset and date
    signal_sums_over_time = pd.DataFrame(index=asset_ids)
    
    # Calculate signal sums for each date
    for date_str in date_strings:
        signals_df = display_all_assets_signals_for_date(analyzer, date_str)
        signal_sums_over_time[date_str] = signals_df['Signal_Sum']
    
    # Add market cap column for sorting
    signal_sums_over_time['market_cap'] = signal_sums_over_time.index.map(lambda x: market_caps.get(x, 0))
    
    # Sort by market cap in descending order
    signal_sums_over_time = signal_sums_over_time.sort_values(by='market_cap', ascending=True)
    
    # Calculate total signal sum (but don't include market_cap column)
    signal_sums_over_time['total_sum'] = signal_sums_over_time.drop(columns=['market_cap']).sum(axis=1)
    
    # Remove the sorting columns after sorting
    signal_sums_over_time = signal_sums_over_time.drop(columns=['market_cap', 'total_sum'])
    
    # Create a new DataFrame with tickers as index
    ticker_signal_sums = pd.DataFrame(index=[ticker_mapping[asset_id] for asset_id in signal_sums_over_time.index])
    for col in signal_sums_over_time.columns:
        ticker_signal_sums[col] = signal_sums_over_time[col].values
    
    # Create color mapping function based on signal sum (scaled from 0 to 2)
    def get_color(signal_sum):
        if signal_sum == 0:
            return 'rgb(180, 50, 50)'  # darker red
        elif signal_sum == 1:
            return 'rgb(220, 180, 50)'  # darker yellow
        else:  # 2 signals
            return 'rgb(50, 150, 50)'  # darker green
    
    # Create the figure
    fig = go.Figure()
    
    # Get all dates for x-axis
    all_dates = pd.to_datetime(ticker_signal_sums.columns)
    
    # Plot all points including zero values
    for ticker in ticker_signal_sums.index:
        ticker_data = ticker_signal_sums.loc[ticker]
        
        # Create lists to store data for this ticker
        x_dates = []
        y_tickers = []
        sizes = []
        colors = []
        hover_texts = []
        
        # Process each date point
        for date, sum_val in zip(all_dates, ticker_data):
            x_dates.append(date)
            y_tickers.append(ticker)
            sizes.append(10 + sum_val * 5)  # Size based on signal sum
            colors.append(get_color(sum_val))
            hover_texts.append(f"Date: {date.strftime('%Y-%m-%d')}<br>Ticker: {ticker}<br>Signal Sum: {sum_val}")
        
        # Add scatter plot (dots)
        fig.add_trace(go.Scatter(
            x=x_dates,
            y=y_tickers,
            mode='markers',
            marker=dict(
                size=sizes,
                color=colors,
                line=dict(width=1, color='rgba(0,0,0,0.5)')
            ),
            name=ticker,
            showlegend=False,
            hoverinfo='text',
            hovertext=hover_texts
        ))
    
    # Add a color legend
    for i, (sum_val, color_desc) in enumerate([
        (0, "0 signals (red)"),
        (1, "1 signal (yellow)"),
        (2, "2 signals (green)")
    ]):
        fig.add_trace(go.Scatter(
            x=[None],
            y=[None],
            mode='markers',
            marker=dict(size=10 + sum_val * 5, color=get_color(sum_val)),
            name=color_desc,
            showlegend=True
        ))
    
    # Update layout
    title_text = "Signal Sums for Assets Through Time (Ordered by Market Cap)"
    if min_market_cap > 0 or max_market_cap is not None:
        title_text += f" (Market Cap"
        if min_market_cap > 0:
            title_text += f" >= {min_market_cap:,} USD"
        if max_market_cap is not None:
            if min_market_cap > 0:
                title_text += " and"
            title_text += f" <= {max_market_cap:,} USD"
        title_text += ")"
        
    fig.update_layout(
        title=title_text,
        xaxis_title="Date",
        yaxis_title="Tickers",
        height=max(800, len(ticker_signal_sums) * 20),  # Dynamic height based on number of assets
        width=1200,  # Fixed width for better display
        yaxis=dict(
            categoryorder='array',
            categoryarray=ticker_signal_sums.index,  # Order by market cap (already sorted)
        ),
        xaxis=dict(
            type='date',
            tickformat='%Y-%m-%d',
            tickangle=45,
        ),
        legend_title="Signal Sum Legend",
        hovermode="closest",
        showlegend=True,
        margin=dict(l=150, r=50, t=50, b=100)  # Add margin for ticker names
    )
    
    fig.show()
    
    return ticker_signal_sums

# Example usage
signal_data_over_time = plot_signal_sums_through_time(
    analyzer, 
    start_date="2025-10-01",  # Change to your desired start date
    end_date="2025-11-23",    # Change to your desired end date

    min_market_cap = 10000,
    max_market_cap = 100000000000000

)

Asset: ATOM, Market Cap: 1195741342.1591537
Asset: IP, Market Cap: 813155257.9815772
Asset: GOAT, Market Cap: 39727251.91869732
Asset: SAND, Market Cap: 396250221.01137453
Asset: XTZ, Market Cap: 521147526.43362457
Asset: SHDW, Market Cap: 9773471.687394893
Asset: MUBARAK, Market Cap: 16179150.96132454
Asset: ALPHA, Market Cap: 6661518.055356571
Asset: NEAR, Market Cap: 2337062596.7675085
Asset: SPX, Market Cap: 467430083.6864215
Asset: CRO, Market Cap: 3968740266.7095785
Asset: SEI, Market Cap: 849276708.3600773
Asset: CPOOL, Market Cap: 39260849.83905558
Asset: FWOG, Market Cap: 9327217.62355054
Asset: MATIC, Market Cap: 0.0
Asset: AKT, Market Cap: 135542097.2577537
Asset: KEKIUS, Market Cap: 7981282.679369471
Asset: AVA, Market Cap: 9927745.020646883
Asset: ETHFI, Market Cap: 413511038.3816485
Asset: COOKIE, Market Cap: 31044946.15578403
Asset: ADA, Market Cap: 14971674523.124762
Asset: FRAX, Market Cap: 74911707.27482018
Asset: SLERF, Market Cap: 0.0
Asset: LSK, Market Cap: 40357756.3250189
Asset: ARB, Market Cap: 1129966606.1929815
Asset: CAKE, Market Cap: 761005653.8362025
Asset: YFI, Market Cap: 135729344.52461582
Asset: WIF, Market Cap: 336000445.9373164
Asset: OP, Market Cap: 572709742.5767863
Asset: CHILLGUY, Market Cap: 15837274.49614134
Asset: NEON, Market Cap: 13606243.884083876
Asset: VVV, Market Cap: 40327404.23998007
Asset: BAL, Market Cap: 43391610.73898112
Asset: OM, Market Cap: 81368009.29113539
Asset: AIOZ, Market Cap: 143046379.97536036
Asset: JASMY, Market Cap: 354441616.75044596
Asset: HNT, Market Cap: 346229564.27862173
Asset: ANZ, Market Cap: 578436.28289306
Asset: XLM, Market Cap: 7966997640.367822
Asset: BTC, Market Cap: 1732233225777.4016
Asset: DOGE, Market Cap: 22053236403.160934
Asset: VELVET, Market Cap: 16816424.13336474
Asset: BOTTO, Market Cap: 4060387.467158373
Asset: VRA, Market Cap: 27778238.31468847
Asset: KAS, Market Cap: 1072589269.0790056
Asset: KAITO, Market Cap: 156958015.7532509
Asset: AR, Market Cap: 254628619.26325756
Asset: NEIRO, Market Cap: 49436659.18317524
Asset: POLY, Market Cap: 2682015.1936673825
Asset: TON, Market Cap: 3664022257.05066
Asset: GENE, Market Cap: 412989.9905670482
Asset: KNC, Market Cap: 45995027.050846875
Asset: ACH, Market Cap: 45650840.89624287
Asset: STX, Market Cap: 558841058.3539166
Asset: TURBO, Market Cap: 94253175.46135582
Asset: PAAL, Market Cap: 16786275.788927406
Asset: BRETT, Market Cap: 134797105.5019401
Asset: BADGER, Market Cap: 11406029.035281437
Asset: FLOW, Market Cap: 380222893.6083228
Asset: SWM, Market Cap: 244027.60366894864
Asset: MOG, Market Cap: 107388571.08958878
Asset: CLANKER, Market Cap: 53957970.206417546
Asset: BMT, Market Cap: 7322740.335419222
Asset: APU, Market Cap: 16945575.39221533
Asset: PAXG, Market Cap: 1356410273.8067973
Asset: PUMP, Market Cap: 1490640410.131224
Asset: ZEUS, Market Cap: 12014234.651548456
Asset: INJ, Market Cap: 535826000.343351
Asset: BONK, Market Cap: 732388255.4836783
Asset: SOL, Market Cap: 73167233648.17833
Asset: DUSK, Market Cap: 28581761.637605324
Asset: BITCOIN, Market Cap: 39574729.13515771
Asset: RON, Market Cap: 135734330.95467958
Asset: BIO, Market Cap: 105587573.04329497
Asset: CHEX, Market Cap: 35027509.610080935
Asset: BAND, Market Cap: 62750343.1109781
Asset: GALA, Market Cap: 346988278.1830491
Asset: EUL, Market Cap: 71914632.65408169
Asset: BEAM, Market Cap: 166718168.2550572
Asset: MORPHO, Market Cap: 788520782.5628647
Asset: DEEP, Market Cap: 100986820.76145177
Asset: POWR, Market Cap: 47015913.51546079
Asset: FTM, Market Cap: 0.0
Asset: DASH, Market Cap: 711288060.0192971
Asset: DODO, Market Cap: 23348892.20159494
Asset: RGT, Market Cap: 490606.0302763647
Asset: ICP, Market Cap: 2198730527.120018
Asset: SCRT, Market Cap: 46918702.62250309
Asset: ARKM, Market Cap: 125800842.82684945
Asset: NMR, Market Cap: 89739766.36661972
Asset: ATH, Market Cap: 239619665.30397072
Asset: LINK, Market Cap: 8726740382.82391
Asset: STRDY, Market Cap: 389268.5444186476
Asset: DOG, Market Cap: 122557717.8978873
Asset: PEPE, Market Cap: 1751892165.5730078
Asset: VIRTUAL, Market Cap: 579422033.2936264
Asset: AIXBT, Market Cap: 42593057.45379982
Asset: PENGU, Market Cap: 649260198.9469529
Asset: ILV, Market Cap: 69366230.68760431
Asset: AURY, Market Cap: 6404597.189319995
Asset: MUBI, Market Cap: 1108881.8543035828
Asset: CRV, Market Cap: 547343345.8292576
Asset: ETC, Market Cap: 2097949664.638604
Asset: TRX, Market Cap: 26040313125.33179
Asset: HYPC, Market Cap: 0.0
Asset: GRIFT, Market Cap: 709803.0918770116
Asset: EIGEN, Market Cap: 240668923.90411356
Asset: AXL, Market Cap: 137860986.65073183
Asset: MCADE, Market Cap: 7130873.973873534
Asset: TIA, Market Cap: 514907840.57377714
Asset: WLD, Market Cap: 1424081184.8319826
Asset: MANA, Market Cap: 314364900.0255029
Asset: MYRIA, Market Cap: 4309260.842590154
Asset: YGG, Market Cap: 59397119.58136798
Asset: EVAN, Market Cap: 110948.23964105188
Asset: PRISMA, Market Cap: 2240273.944010955
Asset: AUDIO, Market Cap: 46487710.69146431
Asset: AI16Z, Market Cap: 13499800.176945232
Asset: LUNA, Market Cap: 49791136.607255146
Asset: WELL, Market Cap: 46002643.34151783
Asset: RAY, Market Cap: 283996562.1285467
Asset: ALICE, Market Cap: 22577604.46800382
Asset: UNI, Market Cap: 3862871599.0512543
Asset: S, Market Cap: 394304848.5800054
Asset: ANON, Market Cap: 16346634.039000772
Asset: AAVE, Market Cap: 2534713531.277188
Asset: FLUID, Market Cap: 252913494.0222791
Asset: LAYER, Market Cap: 50329352.75542921
Asset: CORE, Market Cap: 146053161.1882188
Asset: GOG, Market Cap: 2965264.4370709085
Asset: TRUMP, Market Cap: 1251787678.5047617
Asset: GIGA, Market Cap: 48848289.99254591
Asset: RBW, Market Cap: 135829.75645333587
Asset: XMR, Market Cap: 7161082802.059122
Asset: PROM, Market Cap: 167694030.9054138
Asset: WBX, Market Cap: 0.0
Asset: PRIME, Market Cap: 38529151.75603581
Asset: GMX, Market Cap: 87323934.49144885
Asset: PLUME, Market Cap: 81030835.10023695
Asset: BNB, Market Cap: 116123650605.58427
Asset: SYRUP, Market Cap: 347996233.702678
Asset: MEW, Market Cap: 101287701.7281873
Asset: WNXM, Market Cap: 32850417.418796606
Asset: POLIS, Market Cap: 11911490.934009047
Asset: MKR, Market Cap: 0.0
Asset: PERP, Market Cap: 5440125.740274998
Asset: RENDER, Market Cap: 888060259.4374449
Asset: BCH, Market Cap: 10776208818.685726
Asset: ZEC, Market Cap: 9422531736.451342
Asset: AIDOGE, Market Cap: 2610571.0316262143
Asset: AXS, Market Cap: 183627581.63447645
Asset: YNE, Market Cap: 1488987.6003982169
Asset: LA, Market Cap: 73530100.43802598
Asset: PEOPLE, Market Cap: 47700189.0609393
Asset: FLOKI, Market Cap: 438965019.5019523
Asset: SNEK, Market Cap: 112069756.37831189
Asset: BIG, Market Cap: 2625122.0824152846
Asset: VELA, Market Cap: nan
Asset: XRP, Market Cap: 123296237500.01305
Asset: KMNO, Market Cap: 171587430.75731367
Asset: EQB, Market Cap: 8617149.42139048
Asset: GRIFFAIN, Market Cap: 12653895.585800257
Asset: MAMO, Market Cap: 12521990.771919874
Asset: TAO, Market Cap: 2846257643.759034
Asset: HYPE, Market Cap: 8583724638.021919
Asset: EOS, Market Cap: 131694538.24955449
Asset: PENDLE, Market Cap: 366490251.92429346
Asset: ALCH, Market Cap: 119237936.91299108
Asset: SUI, Market Cap: 5037186499.325146
Asset: ETHDYDX, Market Cap: 9609945.880228708
Asset: DOT, Market Cap: 3702110598.253263
Asset: SMART, Market Cap: 149974.4925181622
Asset: SUSHI, Market Cap: 110013144.22968596
Asset: YAI, Market Cap: 323947.5233268122
Asset: IMX, Market Cap: 248288473.1113436
Asset: GROK, Market Cap: 3092633.765463111
Asset: VISTA, Market Cap: 3449645.907759203
Asset: ARPA, Market Cap: 14521808.549243612
Asset: GRASS, Market Cap: 163076197.8848032
Asset: ML, Market Cap: 2685258.2669981467
Asset: GNS, Market Cap: 37799642.50575339
Asset: HBAR, Market Cap: 6297945843.654614
Asset: SNX, Market Cap: 202094743.85835537
Asset: RDNT, Market Cap: 14912296.08671179
Asset: AVAX, Market Cap: 5701571552.107072
Asset: ENA, Market Cap: 1759053797.5020406
Asset: OMG, Market Cap: 12869612.598674748
Asset: NTX, Market Cap: 5539192.643153294
Asset: FET, Market Cap: 720664052.8200308
Asset: BABYDOGE, Market Cap: 121022352.10455345
Asset: BERT, Market Cap: 25728673.287084404
Asset: LQTY, Market Cap: 41427187.99144056
Asset: RUNE, Market Cap: 220479972.9756423
Asset: LDO, Market Cap: 551191622.0990514
Asset: FARTCOIN, Market Cap: 224667233.7410166
Asset: SIREN, Market Cap: 46300015.362559184
Asset: LTC, Market Cap: 6353960978.363359
Asset: ACA, Market Cap: 15694527.675562322
Asset: JUP, Market Cap: 759815275.8800112
Asset: BOME, Market Cap: 46630961.83388621
Asset: SPELL, Market Cap: 45494448.37263244
Asset: USELESS, Market Cap: 93302473.91461793
Asset: GORK, Market Cap: 1311230.0477300182
Asset: ZBCN, Market Cap: 296292891.5574342
Asset: AERO, Market Cap: 621721503.3776443
Asset: SEILOR, Market Cap: 101049.81381967357
Asset: ETH, Market Cap: 338053142179.2997
Asset: TRIBE, Market Cap: 20254138.90224119
Asset: SRM, Market Cap: 2690679.219730795
Asset: CNC, Market Cap: 12100.283499994766
Asset: SHIB, Market Cap: 4633410895.265953
Asset: POPCAT, Market Cap: 88546010.97191079
Asset: KUJI, Market Cap: 30629900.3171988
Asset: ZK, Market Cap: 272660268.0603488
Asset: COMP, Market Cap: 276016073.40770316
Asset: ONDO, Market Cap: 1503763164.8086138
Asset: QNT, Market Cap: 1129070655.903551
Error getting TrendMomentumBTC for conic-finance on 2025-10-03: Incompatible indexer with Series
Error getting TrendMomentumUSD for conic-finance on 2025-10-03: Incompatible indexer with Series
Error getting TrendMomentumBTC for vela-token on 2025-10-04: Incompatible indexer with Series
Error getting TrendMomentumUSD for vela-token on 2025-10-04: Incompatible indexer with Series
Error getting TrendMomentumBTC for smartcash on 2025-10-05: Incompatible indexer with Series
Error getting TrendMomentumUSD for smartcash on 2025-10-05: Incompatible indexer with Series
Error getting TrendMomentumBTC for swarm on 2025-10-07: Incompatible indexer with Series
Error getting TrendMomentumUSD for swarm on 2025-10-07: Incompatible indexer with Series
Error getting TrendMomentumBTC for rari-governance-token on 2025-10-08: Incompatible indexer with Series
Error getting TrendMomentumUSD for rari-governance-token on 2025-10-08: Incompatible indexer with Series
Error getting TrendMomentumBTC for swarm on 2025-10-09: Incompatible indexer with Series
Error getting TrendMomentumUSD for swarm on 2025-10-09: Incompatible indexer with Series
Error getting TrendMomentumBTC for vela-token on 2025-10-11: Incompatible indexer with Series
Error getting TrendMomentumUSD for vela-token on 2025-10-11: Incompatible indexer with Series
Error getting TrendMomentumBTC for smartcash on 2025-10-15: Incompatible indexer with Series
Error getting TrendMomentumUSD for smartcash on 2025-10-15: Incompatible indexer with Series
Error getting TrendMomentumBTC for swarm on 2025-10-15: Incompatible indexer with Series
Error getting TrendMomentumUSD for swarm on 2025-10-15: Incompatible indexer with Series
Error getting TrendMomentumBTC for matic-network on 2025-10-16: Incompatible indexer with Series
Error getting TrendMomentumUSD for matic-network on 2025-10-16: Incompatible indexer with Series
Error getting TrendMomentumBTC for vela-token on 2025-10-16: Incompatible indexer with Series
Error getting TrendMomentumUSD for vela-token on 2025-10-16: Incompatible indexer with Series
Error getting TrendMomentumBTC for conic-finance on 2025-10-19: Incompatible indexer with Series
Error getting TrendMomentumUSD for conic-finance on 2025-10-19: Incompatible indexer with Series
Error getting TrendMomentumBTC for rari-governance-token on 2025-10-20: Incompatible indexer with Series
Error getting TrendMomentumUSD for rari-governance-token on 2025-10-20: Incompatible indexer with Series
Error getting TrendMomentumBTC for smartcash on 2025-10-20: Incompatible indexer with Series
Error getting TrendMomentumUSD for smartcash on 2025-10-20: Incompatible indexer with Series
Error getting TrendMomentumBTC for swarm on 2025-10-20: Incompatible indexer with Series
Error getting TrendMomentumUSD for swarm on 2025-10-20: Incompatible indexer with Series
Error getting TrendMomentumBTC for rari-governance-token on 2025-10-25: Incompatible indexer with Series
Error getting TrendMomentumUSD for rari-governance-token on 2025-10-25: Incompatible indexer with Series
Error getting TrendMomentumBTC for smartcash on 2025-10-26: Incompatible indexer with Series
Error getting TrendMomentumUSD for smartcash on 2025-10-26: Incompatible indexer with Series
Error getting TrendMomentumBTC for swarm on 2025-10-26: Incompatible indexer with Series
Error getting TrendMomentumUSD for swarm on 2025-10-26: Incompatible indexer with Series
Error getting TrendMomentumBTC for swarm on 2025-10-27: Incompatible indexer with Series
Error getting TrendMomentumUSD for swarm on 2025-10-27: Incompatible indexer with Series
Error getting TrendMomentumBTC for smartcash on 2025-10-28: Incompatible indexer with Series
Error getting TrendMomentumUSD for smartcash on 2025-10-28: Incompatible indexer with Series
Error getting TrendMomentumBTC for vela-token on 2025-10-28: Incompatible indexer with Series
Error getting TrendMomentumUSD for vela-token on 2025-10-28: Incompatible indexer with Series
Error getting TrendMomentumBTC for vela-token on 2025-11-02: Incompatible indexer with Series
Error getting TrendMomentumUSD for vela-token on 2025-11-02: Incompatible indexer with Series
Error getting TrendMomentumBTC for vela-token on 2025-11-04: Incompatible indexer with Series
Error getting TrendMomentumUSD for vela-token on 2025-11-04: Incompatible indexer with Series
Error getting TrendMomentumBTC for rari-governance-token on 2025-11-05: Incompatible indexer with Series
Error getting TrendMomentumUSD for rari-governance-token on 2025-11-05: Incompatible indexer with Series
Error getting TrendMomentumBTC for smartcash on 2025-11-07: Incompatible indexer with Series
Error getting TrendMomentumUSD for smartcash on 2025-11-07: Incompatible indexer with Series
Error getting TrendMomentumBTC for rainbow-token-2 on 2025-11-11: Incompatible indexer with Series
Error getting TrendMomentumUSD for rainbow-token-2 on 2025-11-11: Incompatible indexer with Series
Error getting TrendMomentumBTC for swarm on 2025-11-18: Incompatible indexer with Series
Error getting TrendMomentumUSD for swarm on 2025-11-18: Incompatible indexer with Series
Error getting TrendMomentumBTC for conic-finance on 2025-11-21: Incompatible indexer with Series
Error getting TrendMomentumUSD for conic-finance on 2025-11-21: Incompatible indexer with Series

In [ ]:

btc = results['asset_results'].get('bitcoin')['results_df']
btc

In [ ]:
import pandas as pd
import numpy as np

def apply_triple_barrier_labeling(df, profit_factor=2, stop_factor=2, time_window=7, stdev_window=20, debug=False):
    """
    Apply triple barrier method labeling to a trading dataframe with the following rules:
    - Positive Label (+1): Upper barrier (profit target) is breached first
    - Negative Label (-1): Lower barrier (stop loss) is breached first
    - Neutral Label (0): Time barrier expires without hitting either barrier
    
    Parameters:
    -----------
    df : pandas.DataFrame
        The dataframe containing trading data
    profit_factor : float, default=2
        Multiplier for standard deviation to determine profit target
    stop_factor : float, default=2
        Multiplier for standard deviation to determine stop loss
    time_window : int, default=7
        Number of days to look forward for label determination
    stdev_window : int, default=20
        Window size for standard deviation calculation
    debug : bool, default=False
        Whether to print debugging information
        
    Returns:
    --------
    pandas.DataFrame
        The original dataframe with additional 'triple_barrier_label' column
    """
    # Make a copy of the dataframe to avoid modifying the original
    df_copy = df.copy()
    
    # Calculate rolling standard deviation
    df_copy['rolling_std'] = df_copy['close'].rolling(window=stdev_window).std()
    
    # Initialize the label column
    df_copy['triple_barrier_label'] = np.nan
    
    # Debugging counters
    if debug:
        skipped_beginning = 0
        skipped_end = 0
        processed = 0
        labels_positive = 0
        labels_negative = 0
        labels_neutral = 0
    
    # Find rows where position changes (actual trade entries)
    position_entries = []
    
    # Look for either:
    # 1. Where position changes from 0 to non-zero
    if 'position' in df_copy.columns:
        for i in range(1, len(df_copy)):
            if df_copy['position'].iloc[i-1] == 0 and df_copy['position'].iloc[i] != 0:
                position_entries.append(i)
    
    # 2. Or where trade_executed is True
    if 'trade_executed' in df_copy.columns:
        for i in range(len(df_copy)):
            if df_copy['trade_executed'].iloc[i] == True:
                if i not in position_entries:
                    position_entries.append(i)
    
    # 3. Or where final_decision_shifted is 1 (assuming this indicates a trade signal)
    for i in range(len(df_copy)):
        if not pd.isna(df_copy['final_decision_shifted'].iloc[i]) and df_copy['final_decision_shifted'].iloc[i] == 1:
            if i not in position_entries:
                position_entries.append(i)
    
    if debug:
        print(f"Found {len(position_entries)} potential trade entry points")
    
    # Loop through each identified trade entry
    for i in position_entries:
        # Skip if we're too close to the beginning or end of the dataframe
        if i < stdev_window:
            if debug: skipped_beginning += 1
            continue
            
        if i >= len(df_copy) - 1:
            if debug: skipped_end += 1
            continue
        
        # Calculate profit target and stop loss
        entry_price = df_copy['open'].iloc[i]
        std_dev = df_copy['rolling_std'].iloc[i-1]  # Using previous day's std for decision
        
        # Skip if std_dev is NaN or 0
        if pd.isna(std_dev) or std_dev == 0:
            if debug: print(f"Warning: Standard deviation is {std_dev} at index {i}")
            continue
        
        profit_target = entry_price + profit_factor * std_dev
        stop_loss = entry_price - stop_factor * std_dev
        
        # Look forward up to time_window days
        label = None
        exit_day = min(i+time_window, len(df_copy)-1)
        
        for forward_idx in range(i+1, exit_day+1):
            current_price = df_copy['close'].iloc[forward_idx]
            
            # Check if profit target is hit first
            if current_price >= profit_target:
                label = 1  # Positive label
                if debug: labels_positive += 1
                break
                
            # Check if stop loss is hit first
            if current_price <= stop_loss:
                label = -1  # Negative label
                if debug: labels_negative += 1
                break
        
        # If neither barrier is hit within the time window, assign neutral label
        if label is None:
            label = 0  # Neutral label - time barrier hit first
            if debug: labels_neutral += 1
        
        # Assign the label
        df_copy.loc[df_copy.index[i], 'triple_barrier_label'] = label
        
        if debug: processed += 1
    
    if debug:
        print(f"Skipped (beginning): {skipped_beginning}")
        print(f"Skipped (end): {skipped_end}")
        print(f"Processed entries: {processed}")
        print(f"Positive labels (+1): {labels_positive}")
        print(f"Negative labels (-1): {labels_negative}")
        print(f"Neutral labels (0): {labels_neutral}")
        print(f"Non-NaN labels: {df_copy['triple_barrier_label'].notna().sum()}")
    
    return df_copy

# Example usage:
labeled_df = apply_triple_barrier_labeling(btc)
labeled_df

In [ ]:
# Import plotly if not already imported
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Create a figure with two subplots stacked vertically
fig = make_subplots(rows=2, cols=1, shared_xaxes=True, vertical_spacing=0.1, 
                    subplot_titles=('BTC Price', 'Trading Signals'))

# Plot BTC price in the top subplot
fig.add_trace(
    go.Scatter(x=labeled_df.index, y=labeled_df['close'], name='BTC Price', line=dict(color='blue')),
    row=1, col=1
)

# Plot position and triple barrier label in the bottom subplot
fig.add_trace(
    go.Scatter(x=labeled_df.index, y=labeled_df['position'], name='Position', line=dict(color='green')),
    row=2, col=1
)
fig.add_trace(
    go.Scatter(x=labeled_df.index, y=labeled_df['triple_barrier_label'], name='Triple Barrier Label', 
               line=dict(color='red')),
    row=2, col=1
)

# Update layout
fig.update_layout(
    height=800, 
    width=1200,
    showlegend=True,
    legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1)
)

# Update y-axis labels
fig.update_yaxes(title_text="Price (USD)", row=1, col=1)
fig.update_yaxes(title_text="Signal Value", row=2, col=1)
fig.update_xaxes(title_text="Date", row=2, col=1)

# Add grid lines
fig.update_xaxes(showgrid=True, gridwidth=1, gridcolor='LightGrey')
fig.update_yaxes(showgrid=True, gridwidth=1, gridcolor='LightGrey')

# Show the figure
fig.show()

In [ ]:
def create_returns_df_from_signals(analyzer, signal_df, min_days=90, min_market_cap=1000000000, max_market_cap=None):
    """
    Create a DataFrame of returns for assets that have a signal sum >= 3
    and have at least the minimum number of days of price data.
    
    Args:
        analyzer: PortfolioAnalyzer instance
        signal_df: DataFrame with signal values and Signal_Sum column
        min_days: Minimum number of days of price data required (default: 365)
        min_market_cap: Minimum market capitalization in USD to include an asset (default: 0)
        max_market_cap: Maximum market capitalization in USD to include an asset (default: None)
    
    Returns:
        DataFrame with daily returns for qualifying assets
    """
    # Filter assets with signal sum >= 3
    # For bitcoin, we only require a signal sum of 2, for all other assets we require 3
    bitcoin_assets = signal_df[
        (signal_df.index == 'bitcoin') & (signal_df['Signal_Sum'] >= 2)
    ].index.tolist()
    other_assets = signal_df[
        (signal_df.index != 'bitcoin') & (signal_df['Signal_Sum'] >= 4)
    ].index.tolist()
    qualified_assets = bitcoin_assets + other_assets
    
    # Dictionary to store returns series
    returns_dict = {}
    
    # Process each qualified asset
    for asset_id in qualified_assets:
        asset_data = analyzer.get_asset_data(asset_id)
        
        # Skip if asset data is None
        if asset_data is None:
            continue
            
        # Check market cap if filtering is enabled
        if min_market_cap > 0 or max_market_cap is not None:
            market_cap = None
            
            # Try to get from metadata if available
            if hasattr(asset_data, 'metadata') and asset_data.metadata:
                market_cap = asset_data.metadata.get('market_cap')
            
            # Try to get from asset_data directly
            if market_cap is None and hasattr(asset_data, 'market_cap'):
                market_cap = asset_data.market_cap
            
            # Try to get from price_data if available
            if market_cap is None and hasattr(asset_data, 'price_data'):
                if 'market_cap' in asset_data.price_data.columns:
                    # Use the most recent market cap value
                    market_cap = asset_data.price_data['market_cap'].iloc[-1]
            
            # Skip if market cap doesn't meet criteria
            if market_cap is not None:
                if (min_market_cap > 0 and market_cap < min_market_cap) or \
                   (max_market_cap is not None and market_cap > max_market_cap):
                    print(f"Skipping {asset_id}: Market cap {market_cap} outside range [{min_market_cap}, {max_market_cap or 'inf'}]")
                    continue
            elif min_market_cap > 0:
                print(f"Skipping {asset_id}: No market cap data available")
                continue
            
        # Get price data
        try:
            price_data = asset_data.get_price_data()
            
            if price_data is None or len(price_data) < min_days:
                print(f"Skipping {asset_id}: Only has {len(price_data) if price_data is not None else 0} days of data (minimum required: {min_days})")
                continue
                
            if 'close' in price_data.columns:
                # Calculate daily returns
                returns = price_data['close'].pct_change().dropna()
                
                # Make sure the index is unique before adding to the dictionary
                if returns.index.is_unique:
                    returns_dict[asset_id] = returns
                else:
                    # Handle duplicate indices by keeping the first occurrence
                    print(f"Warning: {asset_id} has duplicate dates. Keeping first occurrence.")
                    returns = returns[~returns.index.duplicated(keep='first')]
                    returns_dict[asset_id] = returns
            else:
                print(f"Skipping {asset_id}: Price data missing 'close' column")
        except Exception as e:
            print(f"Error processing {asset_id}: {e}")
    
    # Create DataFrame from the dictionary
    if returns_dict:
        # Create an empty DataFrame with a unique index that spans all series
        all_dates = sorted(set().union(*[returns.index for returns in returns_dict.values()]))
        returns_df = pd.DataFrame(index=all_dates)
        
        # Add each series to the DataFrame
        for asset_id, returns in returns_dict.items():
            returns_df[asset_id] = returns
            
        print(f"Created returns DataFrame with {len(returns_df.columns)} assets")
        return returns_df
    else:
        print("No qualifying assets found")
        return pd.DataFrame()

# Example usage
# Get signals for a specific date
date_to_check = "2024-11-25"  # Change to your desired date
signals_df = display_all_assets_signals_for_date(analyzer, date_to_check)

# Create returns DataFrame for assets with signal sum >= 3
returns_df = create_returns_df_from_signals(analyzer, signals_df)

# Display the first few rows of the returns DataFrame
if not returns_df.empty:
    display(returns_df.tail())
    
    # Display basic statistics
    print(f"\nReturns DataFrame Shape: {returns_df.shape}")
    print(f"Date Range: {returns_df.index.min()} to {returns_df.index.max()}")

In [ ]:
def hrp_portfolio(returns_df):
    """
    Compute HRP portfolio allocations for a DataFrame of asset returns.

    Args:
        returns_df (pd.DataFrame): DataFrame with dates as rows, assets as columns,
                                   and daily returns as values (e.g., shape: (n_days, n_assets)).

    Returns:
        pd.DataFrame: Portfolio weights for each asset (index: asset names, column: 'weights').
    """
    # Step 1: Compute the covariance matrix and convert to NumPy array
    cov_matrix = returns_df.cov().values  # Convert to NumPy array
    
    # Ensure positive definiteness
    min_eig = np.min(np.real(np.linalg.eigvals(cov_matrix)))
    if min_eig <= 0:
        cov_matrix += (abs(min_eig) + 1e-5) * np.eye(cov_matrix.shape[0])

    # Step 2: Compute the correlation-based distance matrix
    std = np.sqrt(np.diag(cov_matrix))
    std[std == 0] = 1e-10  # Prevent division by zero
    corr = cov_matrix / np.outer(std, std)
    corr = np.clip(corr, -1, 1)  # Clip to valid range
    np.fill_diagonal(corr, 1)    # Ensure diagonal is 1 (now works since corr is a NumPy array)
    corr = (corr + corr.T) / 2   # Force symmetry

    distance = np.sqrt(np.maximum(0.5 * (1 - corr), 0))
    np.fill_diagonal(distance, 0)  # Ensure diagonal is 0
    distance = (distance + distance.T) / 2  # Force symmetry

    # Step 3: Perform hierarchical clustering
    dist_condensed = squareform(distance)
    clusters = linkage(dist_condensed, method='single')

    # Step 4: Allocate weights using HRP
    assets = returns_df.columns
    n = len(assets)
    weights = pd.Series(1.0, index=assets)
    clusters_dict = {i: [i] for i in range(n)}

    for i in range(n - 1):
        cluster1 = clusters_dict[int(clusters[i, 0])]
        cluster2 = clusters_dict[int(clusters[i, 1])]
        
        # Compute cluster variances (convert to NumPy array for slicing)
        cov_matrix_df = returns_df.cov()  # Keep as DataFrame for iloc indexing
        cluster_cov1 = cov_matrix_df.iloc[cluster1, cluster1].values
        cluster_cov2 = cov_matrix_df.iloc[cluster2, cluster2].values
        w1 = np.ones(len(cluster1)) / len(cluster1)
        w2 = np.ones(len(cluster2)) / len(cluster2)
        var1 = max(w1.T @ cluster_cov1 @ w1, 1e-10)
        var2 = max(w2.T @ cluster_cov2 @ w2, 1e-10)
        
        # Allocate weights inversely proportional to variance
        weight1 = 1 / var1
        weight2 = 1 / var2
        alpha = weight1 / (weight1 + weight2)
        
        weights.iloc[cluster1] *= alpha
        weights.iloc[cluster2] *= (1 - alpha)
        
        # Update clusters
        new_cluster_id = n + i
        clusters_dict[new_cluster_id] = cluster1 + cluster2

    # Normalize weights
    weights = weights / weights.sum()
    return pd.DataFrame(weights, columns=['weights'])

In [ ]:
hrp_portfolio(returns_df).sort_values(by='weights', ascending=False).head(10)