In [1]:
# Simple, clean approach with the unified interface
from soros_system.core.portfolio_analyzer import PortfolioAnalyzer
from scripts.assetsRoster import carteira_AC, carteira_HB, others, carteira_EXC, carteira_LC
import warnings

warnings.filterwarnings('ignore')

#assets = carteira_AC
assets = set(carteira_AC+carteira_HB+carteira_EXC+carteira_LC+others)
#assets=['bitcoin', 'ethereum', 'solana', 'dogecoin', 'chainlink', 'pendle']
#assets = ['bitcoin','dogecoin', 'pepe', 'spx', 'floki', 'fartcoin'  , 'bertram-the-pomeranian', 'fwog', 'neiro-3',
#          'evan-2', 'mubarak', 'baby-doge-coin', 'chill-guy', 'book-of-meme', 'slerf', 'shiba-inu', 
#          'official-trump', 'dogwifcoin', 'mog-coin', 'new-xai-gork', 'grok-2', 'bonk', 'goatseus-maximus',
#          'alchemist-ai', 'harrypotterobamasonic10in', 'kekius-maximus', 'aixbt', 'ava-ai', 'tokenbot-2',
#          'arbdoge-ai', 'based-brett', 'dog-go-to-the-moon-rune', 'siren-2', 'apu-s-club', 'turbo', 
#          'cat-in-a-dogs-world', 'snek', 'ai16z']


analyzer = PortfolioAnalyzer( 
    data_dir='/Users/valter.rebelo/MissionControl/data',
    data_path='/Users/valter.rebelo/MissionControl/data/micro/candleData/',
    btc_data_path='/Users/valter.rebelo/MissionControl/data/micro/candleData/bitcoin_candles.csv',
    ssr_data_path='/Users/valter.rebelo/MissionControl/data/onchainData/BTC_SSR.csv',
    market_data_path='/Users/valter.rebelo/MissionControl/data/micro/assetData/',
    asset_ids=assets

)

# Load assets - the analyzer handles paths internally

analyzer.load_data(assets=assets, start_date='2014-01-01', end_date='2025-12-31')

INFO: Using 7 workers for parallel processing
INFO: Loading data for assets...
INFO: Converted assets to list with 218 items
INFO: Using parallel loading for 218 assets

Loading assets:   0%|          | 0/218 [00:00<?, ?it/s]

INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/coredaoorg_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/axie-infinity_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/neiro-3_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/coredaoorg.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/heyanon_candles.csv
INFO: Added market data for coredaoorg
INFO: Successfully loaded data for coredaoorg with 898 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/axie-infinity.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/neiro-3.csv
INFO: Loaded data for coredaoorg with 898 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/heyanon.csv

Loading assets:   0%|          | 1/218 [00:01<03:37,  1.00s/it]

INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/tezos_candles.csv
INFO: Added market data for neiro-3
INFO: Added market data for heyanon
INFO: Added market data for axie-infinity
INFO: Successfully loaded data for neiro-3 with 358 rows.
INFO: Successfully loaded data for heyanon with 210 rows.
INFO: Successfully loaded data for axie-infinity with 1724 rows.
INFO: Loaded data for neiro-3 with 358 rows
INFO: Loaded data for heyanon with 210 rows
INFO: Loaded data for axie-infinity with 1724 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/tezos.csv
INFO: Added market data for tezos
INFO: Successfully loaded data for tezos with 2581 rows.
INFO: Loaded data for tezos with 2581 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/fartcoin_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/fartcoin.csv
INFO: Added market data for fartcoin
INFO: Successfully loaded data for fartcoin with 278 rows.
INFO: Loaded data for fartcoin with 278 rows

Loading assets:   3%|▎         | 6/218 [00:01<00:30,  6.99it/s]

INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/dodo_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/moonwell-artemis_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/dodo.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/grok-2_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/hyperliquid_candles.csv
INFO: Added market data for dodo
INFO: Successfully loaded data for dodo with 1759 rows.
INFO: Loaded data for dodo with 1759 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/moonwell-artemis.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/grok-2.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/hyperliquid.csv
INFO: Added market data for hyperliquid
INFO: Added market data for moonwell-artemis
INFO: Added market data for grok-2
INFO: Successfully loaded data for hyperliquid with 239 rows.
INFO: Successfully loaded data for moonwell-artemis with 1128 rows.
INFO: Successfully loaded data for grok-2 with 626 rows.
INFO: Loaded data for hyperliquid with 239 rows
INFO: Loaded data for moonwell-artemis with 1128 rows
INFO: Loaded data for grok-2 with 626 rows

Loading assets:   4%|▍         | 9/218 [00:01<00:21,  9.79it/s]

INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/optimism_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/optimism.csv
INFO: Added market data for optimism
INFO: Successfully loaded data for optimism with 1151 rows.
INFO: Loaded data for optimism with 1151 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/yearn-finance_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/yearn-finance.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/illuvium_candles.csv
INFO: Added market data for yearn-finance
INFO: Successfully loaded data for yearn-finance with 1833 rows.
INFO: Loaded data for yearn-finance with 1833 rows

Loading assets:   6%|▌         | 12/218 [00:01<00:17, 12.11it/s]

INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/ondo-finance_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/illuvium.csv
INFO: Added market data for illuvium
INFO: Successfully loaded data for illuvium with 1577 rows.
INFO: Loaded data for illuvium with 1577 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/ondo-finance.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/dusk-network_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/aixbt_candles.csv
INFO: Added market data for ondo-finance
INFO: Successfully loaded data for ondo-finance with 554 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/dogwifcoin_candles.csv
INFO: Loaded data for ondo-finance with 554 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/dusk-network.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/aixbt.csv
INFO: Added market data for dusk-network
INFO: Successfully loaded data for dusk-network with 2211 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/dogwifcoin.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/alchemist-ai_candles.csv
INFO: Added market data for aixbt
INFO: Loaded data for dusk-network with 2211 rows

Loading assets:   7%|▋         | 15/218 [00:01<00:16, 12.32it/s]

INFO: Successfully loaded data for aixbt with 249 rows.
INFO: Loaded data for aixbt with 249 rows
INFO: Added market data for dogwifcoin
INFO: Successfully loaded data for dogwifcoin with 590 rows.
INFO: Loaded data for dogwifcoin with 590 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/alchemist-ai.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/havven_candles.csv
INFO: Added market data for alchemist-ai
INFO: Successfully loaded data for alchemist-ai with 236 rows.
INFO: Loaded data for alchemist-ai with 236 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/fetch-ai_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/quant-network_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/havven.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/fetch-ai.csv
INFO: Added market data for havven
INFO: Successfully loaded data for havven with 2684 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/ronin_candles.csv
INFO: Loaded data for havven with 2684 rows

Loading assets:   9%|▊         | 19/218 [00:01<00:14, 14.07it/s]

INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/quant-network.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/omisego_candles.csv
INFO: Added market data for fetch-ai
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/acala_candles.csv
INFO: Successfully loaded data for fetch-ai with 2339 rows.
INFO: Loaded data for fetch-ai with 2339 rows
INFO: Added market data for quant-network
INFO: Successfully loaded data for quant-network with 2583 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/ronin.csv
INFO: Loaded data for quant-network with 2583 rows
INFO: Added market data for ronin
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/omisego.csv
INFO: Successfully loaded data for ronin with 1275 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/acala.csv
INFO: Loaded data for ronin with 1275 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/band-protocol_candles.csv
INFO: Added market data for omisego
INFO: Successfully loaded data for omisego with 2931 rows.
INFO: Added market data for acala
INFO: Loaded data for omisego with 2931 rows

Loading assets:  11%|█         | 23/218 [00:01<00:10, 18.16it/s]

INFO: Successfully loaded data for acala with 1277 rows.
INFO: Loaded data for acala with 1277 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/band-protocol.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/gala_candles.csv
INFO: Added market data for band-protocol
INFO: Successfully loaded data for band-protocol with 2137 rows.
INFO: Loaded data for band-protocol with 2137 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/gala.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/multibit_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/bitcoin_candles.csv
INFO: Added market data for gala
INFO: Successfully loaded data for gala with 1773 rows.
INFO: Loaded data for gala with 1773 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/multibit.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/bitcoin.csv
INFO: Added market data for multibit
INFO: Successfully loaded data for multibit with 613 rows.
INFO: Loaded data for multibit with 613 rows

Loading assets:  12%|█▏        | 27/218 [00:02<00:08, 21.75it/s]

INFO: Added market data for bitcoin
INFO: Successfully loaded data for bitcoin with 4471 rows.
INFO: Loaded data for bitcoin with 4471 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/apu-s-club_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/uniswap_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/stellar_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/apu-s-club.csv
INFO: Added market data for apu-s-club
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/the-sandbox_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/uniswap.csv
INFO: Successfully loaded data for apu-s-club with 499 rows.
INFO: Loaded data for apu-s-club with 499 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/turbo_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/stellar.csv
INFO: Added market data for uniswap
INFO: Successfully loaded data for uniswap with 1772 rows.
INFO: Loaded data for uniswap with 1772 rows

Loading assets:  14%|█▍        | 30/218 [00:02<00:08, 21.06it/s]

INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/the-sandbox.csv
INFO: Added market data for stellar
INFO: Successfully loaded data for stellar with 4006 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/turbo.csv
INFO: Loaded data for stellar with 4006 rows
INFO: Added market data for the-sandbox
INFO: Added market data for turbo
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/aethir_candles.csv
INFO: Successfully loaded data for the-sandbox with 1806 rows.
INFO: Successfully loaded data for turbo with 813 rows.
INFO: Loaded data for the-sandbox with 1806 rows
INFO: Loaded data for turbo with 813 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/pendle_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/aethir.csv
INFO: Added market data for aethir
INFO: Successfully loaded data for aethir with 408 rows.
INFO: Loaded data for aethir with 408 rows

Loading assets:  16%|█▌        | 34/218 [00:02<00:07, 24.76it/s]

INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/pendle.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/crypto-com-chain_candles.csv
INFO: Added market data for pendle
INFO: Successfully loaded data for pendle with 1549 rows.
INFO: Loaded data for pendle with 1549 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/crypto-com-chain.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/polymath_candles.csv
INFO: Added market data for crypto-com-chain
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/equilibria-finance_candles.csv
INFO: Successfully loaded data for crypto-com-chain with 2397 rows.
INFO: Loaded data for crypto-com-chain with 2397 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/polymath.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/equilibria-finance.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/gmx_candles.csv
INFO: Added market data for polymath
INFO: Added market data for equilibria-finance
INFO: Successfully loaded data for polymath with 2723 rows.
INFO: Successfully loaded data for equilibria-finance with 779 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/aave_candles.csv
INFO: Loaded data for polymath with 2723 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/zcash_candles.csv

Loading assets:  17%|█▋        | 37/218 [00:02<00:08, 20.67it/s]

INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/rainbow-token-2_candles.csv
INFO: Loaded data for equilibria-finance with 779 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/gmx.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/aave.csv
INFO: Added market data for gmx
INFO: Successfully loaded data for gmx with 1411 rows.
INFO: Loaded data for gmx with 1411 rows
INFO: Added market data for aave
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/zcash.csv
INFO: Successfully loaded data for aave with 1756 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/wrapped-nxm_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/rainbow-token-2.csv
INFO: Loaded data for aave with 1756 rows
INFO: Added market data for zcash
INFO: Successfully loaded data for zcash with 3191 rows.
INFO: Loaded data for zcash with 3191 rows
INFO: Added market data for rainbow-token-2
INFO: Successfully loaded data for rainbow-token-2 with 1224 rows.
INFO: Loaded data for rainbow-token-2 with 1224 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/wrapped-nxm.csv
INFO: Added market data for wrapped-nxm
INFO: Successfully loaded data for wrapped-nxm with 1824 rows.
INFO: Loaded data for wrapped-nxm with 1824 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/axelar_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/binancecoin_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/axelar.csv
INFO: Added market data for axelar
INFO: Successfully loaded data for axelar with 1032 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/binancecoin.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/ethena_candles.csv
INFO: Loaded data for axelar with 1032 rows

Loading assets:  20%|██        | 44/218 [00:02<00:06, 25.90it/s]

INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/harrypotterobamasonic10in_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/sui_candles.csv
INFO: Added market data for binancecoin
INFO: Successfully loaded data for binancecoin with 2869 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/ethena.csv
INFO: Loaded data for binancecoin with 2869 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/harrypotterobamasonic10in.csv
INFO: Added market data for ethena
INFO: Successfully loaded data for ethena with 479 rows.
INFO: Loaded data for ethena with 479 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/sui.csv
INFO: Added market data for harrypotterobamasonic10in
INFO: Successfully loaded data for harrypotterobamasonic10in with 802 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/beam-2_candles.csv
INFO: Loaded data for harrypotterobamasonic10in with 802 rows
INFO: Added market data for sui
INFO: Successfully loaded data for sui with 814 rows.
INFO: Loaded data for sui with 814 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/beam-2.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/rari-governance-token_candles.csv
INFO: Added market data for beam-2
INFO: Successfully loaded data for beam-2 with 638 rows.
INFO: Loaded data for beam-2 with 638 rows

Loading assets:  22%|██▏       | 49/218 [00:02<00:05, 29.34it/s]

INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/rari-governance-token.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/kamino_candles.csv
INFO: Added market data for rari-governance-token
INFO: Successfully loaded data for rari-governance-token with 1741 rows.
INFO: Loaded data for rari-governance-token with 1741 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/kamino.csv
INFO: Added market data for kamino
INFO: Successfully loaded data for kamino with 451 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/zebec-network_candles.csv
INFO: Loaded data for kamino with 451 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/dog-go-to-the-moon-rune_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/cat-in-a-dogs-world_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/zebec-network.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/cat-in-a-dogs-world.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/dog-go-to-the-moon-rune.csv
INFO: Added market data for zebec-network
INFO: Successfully loaded data for zebec-network with 466 rows.
INFO: Added market data for cat-in-a-dogs-world
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/dogecoin_candles.csv
INFO: Loaded data for zebec-network with 466 rows
INFO: Added market data for dog-go-to-the-moon-rune
INFO: Successfully loaded data for dog-go-to-the-moon-rune with 455 rows.
INFO: Successfully loaded data for cat-in-a-dogs-world with 486 rows.
INFO: Loaded data for dog-go-to-the-moon-rune with 455 rows

Loading assets:  24%|██▍       | 53/218 [00:03<00:06, 27.24it/s]

INFO: Loaded data for cat-in-a-dogs-world with 486 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/aurory_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/dogecoin.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/kekius-maximus_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/aurory.csv
INFO: Added market data for dogecoin
INFO: Successfully loaded data for dogecoin with 4240 rows.
INFO: Loaded data for dogecoin with 4240 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/kekius-maximus.csv
INFO: Added market data for aurory
INFO: Successfully loaded data for aurory with 1370 rows.
INFO: Added market data for kekius-maximus
INFO: Loaded data for aurory with 1370 rows
INFO: Successfully loaded data for kekius-maximus with 222 rows.
INFO: Loaded data for kekius-maximus with 222 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/secret_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/zeus-network_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/secret.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/jasmycoin_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/zeus-network.csv
INFO: Added market data for secret
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/ether-fi_candles.csv
INFO: Successfully loaded data for secret with 1758 rows.
INFO: Added market data for zeus-network
INFO: Loaded data for secret with 1758 rows

Loading assets:  27%|██▋       | 58/218 [00:03<00:07, 22.63it/s]

INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/jasmycoin.csv
INFO: Successfully loaded data for zeus-network with 476 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/kyber-network-crystal_candles.csv
INFO: Loaded data for zeus-network with 476 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/ether-fi.csv
INFO: Added market data for jasmycoin
INFO: Successfully loaded data for jasmycoin with 1522 rows.
INFO: Loaded data for jasmycoin with 1522 rows
INFO: Added market data for ether-fi
INFO: Successfully loaded data for ether-fi with 494 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/kyber-network-crystal.csv
INFO: Loaded data for ether-fi with 494 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/fantom_candles.csv
INFO: Added market data for kyber-network-crystal
INFO: Successfully loaded data for kyber-network-crystal with 1555 rows.
INFO: Loaded data for kyber-network-crystal with 1555 rows

Loading assets:  28%|██▊       | 62/218 [00:03<00:06, 24.31it/s]

INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/fantom.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/helium_candles.csv
INFO: Added market data for fantom
INFO: Successfully loaded data for fantom with 2461 rows.
INFO: Loaded data for fantom with 2461 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/helium.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/pancakeswap-token_candles.csv
INFO: Added market data for helium
INFO: Successfully loaded data for helium with 1925 rows.
INFO: Loaded data for helium with 1925 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/alpha-finance_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/dash_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/pancakeswap-token.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/my-neighbor-alice_candles.csv
INFO: Added market data for pancakeswap-token
INFO: Successfully loaded data for pancakeswap-token with 1760 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/alpha-finance.csv
INFO: Loaded data for pancakeswap-token with 1760 rows

Loading assets:  30%|██▉       | 65/218 [00:03<00:07, 21.60it/s]

INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/dash.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/my-neighbor-alice.csv
INFO: Added market data for alpha-finance
INFO: Successfully loaded data for alpha-finance with 1749 rows.
INFO: Loaded data for alpha-finance with 1749 rows
INFO: Added market data for my-neighbor-alice
INFO: Successfully loaded data for my-neighbor-alice with 1593 rows.
INFO: Added market data for dash
INFO: Loaded data for my-neighbor-alice with 1593 rows
INFO: Successfully loaded data for dash with 4179 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/bubblemaps_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/flow_candles.csv
INFO: Loaded data for dash with 4179 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/bubblemaps.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/flow.csv
INFO: Added market data for bubblemaps
INFO: Successfully loaded data for bubblemaps with 136 rows.
INFO: Loaded data for bubblemaps with 136 rows

Loading assets:  32%|███▏      | 69/218 [00:03<00:05, 25.04it/s]

INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/prisma-governance-token_candles.csv
INFO: Added market data for flow
INFO: Successfully loaded data for flow with 1640 rows.
INFO: Loaded data for flow with 1640 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/prisma-governance-token.csv
INFO: Added market data for prisma-governance-token
INFO: Successfully loaded data for prisma-governance-token with 631 rows.
INFO: Loaded data for prisma-governance-token with 631 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/book-of-meme_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/balancer_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/book-of-meme.csv
INFO: Added market data for book-of-meme
INFO: Successfully loaded data for book-of-meme with 498 rows.
INFO: Loaded data for book-of-meme with 498 rows

Loading assets:  33%|███▎      | 72/218 [00:03<00:05, 25.86it/s]

INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/balancer.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/pudgy-penguins_candles.csv
INFO: Added market data for balancer
INFO: Successfully loaded data for balancer with 1858 rows.
INFO: Loaded data for balancer with 1858 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/pudgy-penguins.csv
INFO: Added market data for pudgy-penguins
INFO: Successfully loaded data for pudgy-penguins with 220 rows.
INFO: Loaded data for pudgy-penguins with 220 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/cosmos_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/vela-token_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/render-token_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/dydx_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/cosmos.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/vela-token.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/render-token.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/dydx.csv
INFO: Added market data for cosmos
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/decentraland_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/yield-guild-games_candles.csv
INFO: Added market data for vela-token
INFO: Added market data for render-token
INFO: Successfully loaded data for cosmos with 2345 rows.
INFO: Added market data for dydx
INFO: Successfully loaded data for vela-token with 903 rows.
INFO: Successfully loaded data for render-token with 1866 rows.
INFO: Loaded data for cosmos with 2345 rows

Loading assets:  34%|███▍      | 75/218 [00:04<00:09, 14.43it/s]

INFO: Successfully loaded data for dydx with 1416 rows.
INFO: Loaded data for vela-token with 903 rows
INFO: Loaded data for render-token with 1866 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/anzen-finance_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/decentraland.csv
INFO: Loaded data for dydx with 1416 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/yield-guild-games.csv
INFO: Added market data for decentraland
INFO: Added market data for yield-guild-games
INFO: Successfully loaded data for decentraland with 2827 rows.
INFO: Successfully loaded data for yield-guild-games with 1458 rows.
INFO: Loaded data for decentraland with 2827 rows
INFO: Loaded data for yield-guild-games with 1458 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/anzen-finance.csv
INFO: Added market data for anzen-finance
INFO: Successfully loaded data for anzen-finance with 228 rows.
INFO: Loaded data for anzen-finance with 228 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/chill-guy_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/tron_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/chill-guy.csv
INFO: Added market data for chill-guy
INFO: Successfully loaded data for chill-guy with 249 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/terra-luna-2_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/ava-ai_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/worldcoin-wld_candles.csv
INFO: Loaded data for chill-guy with 249 rows

Loading assets:  38%|███▊      | 82/218 [00:04<00:07, 19.41it/s]

INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/tron.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/bertram-the-pomeranian_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/worldcoin-wld.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/terra-luna-2.csv
INFO: Added market data for tron
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/ava-ai.csv
INFO: Successfully loaded data for tron with 2815 rows.
INFO: Loaded data for tron with 2815 rows
INFO: Added market data for worldcoin-wld
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/grass_candles.csv
INFO: Added market data for terra-luna-2
INFO: Successfully loaded data for worldcoin-wld with 732 rows.
INFO: Added market data for ava-ai
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/bertram-the-pomeranian.csv
INFO: Successfully loaded data for terra-luna-2 with 1154 rows.
INFO: Loaded data for worldcoin-wld with 732 rows
INFO: Successfully loaded data for ava-ai with 246 rows.
INFO: Loaded data for terra-luna-2 with 1154 rows
INFO: Loaded data for ava-ai with 246 rows
INFO: Added market data for bertram-the-pomeranian
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/grass.csv
INFO: Successfully loaded data for bertram-the-pomeranian with 255 rows.
INFO: Loaded data for bertram-the-pomeranian with 255 rows

Loading assets:  40%|███▉      | 87/218 [00:04<00:05, 23.99it/s]

INFO: Added market data for grass
INFO: Successfully loaded data for grass with 270 rows.
INFO: Loaded data for grass with 270 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/bitcoin-cash_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/bitcoin-cash.csv
INFO: Added market data for bitcoin-cash
INFO: Successfully loaded data for bitcoin-cash with 2914 rows.
INFO: Loaded data for bitcoin-cash with 2914 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/polkadot_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/polkadot.csv
INFO: Added market data for polkadot
INFO: Successfully loaded data for polkadot with 1801 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/lisk_candles.csv
INFO: Loaded data for polkadot with 1801 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/aioz-network_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/spx6900_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/serum_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/lisk.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/aioz-network.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/lofi-2_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/spx6900.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/serum.csv
INFO: Added market data for lisk
INFO: Added market data for aioz-network
INFO: Successfully loaded data for lisk with 3397 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/chainlink_candles.csv
INFO: Added market data for spx6900
INFO: Successfully loaded data for aioz-network with 1574 rows.
INFO: Loaded data for lisk with 3397 rows

Loading assets:  42%|████▏     | 91/218 [00:04<00:06, 20.05it/s]

INFO: Successfully loaded data for spx6900 with 697 rows.
INFO: Loaded data for aioz-network with 1574 rows
INFO: Added market data for serum
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/lofi-2.csv
INFO: Loaded data for spx6900 with 697 rows
INFO: Successfully loaded data for serum with 1809 rows.
INFO: Loaded data for serum with 1809 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/chainlink.csv
INFO: Added market data for lofi-2
INFO: Successfully loaded data for lofi-2 with 243 rows.
INFO: Loaded data for lofi-2 with 243 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/arweave_candles.csv
INFO: Added market data for chainlink
INFO: Successfully loaded data for chainlink with 2815 rows.
INFO: Loaded data for chainlink with 2815 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/arweave.csv
INFO: Added market data for arweave
INFO: Successfully loaded data for arweave with 2094 rows.
INFO: Loaded data for arweave with 2094 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/mamo_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/mamo.csv
INFO: Added market data for mamo
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/nunet_candles.csv
INFO: Successfully loaded data for mamo with 65 rows.
INFO: Loaded data for mamo with 65 rows

Loading assets:  45%|████▍     | 98/218 [00:05<00:04, 26.87it/s]

INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/lido-dao_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/nunet.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/genesysgo-shadow_candles.csv
INFO: Added market data for nunet
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/bittensor_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/lido-dao.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/cookie_candles.csv
INFO: Successfully loaded data for nunet with 1335 rows.
INFO: Loaded data for nunet with 1335 rows
INFO: Added market data for lido-dao
INFO: Successfully loaded data for lido-dao with 1662 rows.
INFO: Loaded data for lido-dao with 1662 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/cookie.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/bittensor.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/genesysgo-shadow.csv
INFO: Added market data for cookie
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/baby-doge-coin_candles.csv
INFO: Added market data for bittensor
INFO: Successfully loaded data for cookie with 407 rows.
INFO: Added market data for genesysgo-shadow
INFO: Successfully loaded data for genesysgo-shadow with 1297 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/badger-dao_candles.csv
INFO: Loaded data for cookie with 407 rows
INFO: Successfully loaded data for bittensor with 875 rows.
INFO: Loaded data for genesysgo-shadow with 1297 rows

Loading assets:  47%|████▋     | 102/218 [00:05<00:04, 25.35it/s]

INFO: Loaded data for bittensor with 875 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/baby-doge-coin.csv
INFO: Added market data for baby-doge-coin
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/badger-dao.csv
INFO: Successfully loaded data for baby-doge-coin with 1507 rows.
INFO: Loaded data for baby-doge-coin with 1507 rows
INFO: Added market data for badger-dao
INFO: Successfully loaded data for badger-dao with 1694 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/siren-2_candles.csv
INFO: Loaded data for badger-dao with 1694 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/kryptonite_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/siren-2.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/eigenlayer_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/kryptonite.csv
INFO: Added market data for siren-2
INFO: Successfully loaded data for siren-2 with 156 rows.
INFO: Loaded data for siren-2 with 156 rows

Loading assets:  49%|████▊     | 106/218 [00:05<00:05, 19.31it/s]

INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/thorchain_candles.csv
INFO: Added market data for kryptonite
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/eigenlayer.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/conic-finance_candles.csv
INFO: Successfully loaded data for kryptonite with 711 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/pepe_candles.csv
INFO: Loaded data for kryptonite with 711 rows
INFO: Added market data for eigenlayer
INFO: Successfully loaded data for eigenlayer with 297 rows.
INFO: Loaded data for eigenlayer with 297 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/compound-governance-token_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/thorchain.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/conic-finance.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/pepe.csv
INFO: Added market data for thorchain
INFO: Successfully loaded data for thorchain with 2197 rows.
INFO: Loaded data for thorchain with 2197 rows

Loading assets:  50%|█████     | 109/218 [00:05<00:06, 16.95it/s]

INFO: Added market data for pepe
INFO: Added market data for conic-finance
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/compound-governance-token.csv
INFO: Successfully loaded data for pepe with 829 rows.
INFO: Successfully loaded data for conic-finance with 1012 rows.
INFO: Loaded data for pepe with 829 rows
INFO: Loaded data for conic-finance with 1012 rows
INFO: Added market data for compound-governance-token
INFO: Successfully loaded data for compound-governance-token with 1865 rows.
INFO: Loaded data for compound-governance-token with 1865 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/immutable-x_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/immutable-x.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/the-open-network_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/metacade_candles.csv
INFO: Added market data for immutable-x
INFO: Successfully loaded data for immutable-x with 1358 rows.
INFO: Loaded data for immutable-x with 1358 rows

Loading assets:  52%|█████▏    | 113/218 [00:06<00:05, 19.60it/s]

INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/the-open-network.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/metacade.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/prometeus_candles.csv
INFO: Added market data for the-open-network
INFO: Successfully loaded data for the-open-network with 1428 rows.
INFO: Added market data for metacade
INFO: Loaded data for the-open-network with 1428 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/raydium_candles.csv
INFO: Successfully loaded data for metacade with 836 rows.
INFO: Loaded data for metacade with 836 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/prometeus.csv
INFO: Added market data for prometeus
INFO: Successfully loaded data for prometeus with 2219 rows.
INFO: Loaded data for prometeus with 2219 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/raydium.csv

Loading assets:  53%|█████▎    | 116/218 [00:06<00:04, 21.25it/s]

INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/sei-network_candles.csv
INFO: Added market data for raydium
INFO: Successfully loaded data for raydium with 1615 rows.
INFO: Loaded data for raydium with 1615 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/sei-network.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/wibx_candles.csv
INFO: Added market data for sei-network
INFO: Successfully loaded data for sei-network with 710 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/sturdy_candles.csv
INFO: Loaded data for sei-network with 710 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/clearpool_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/guild-of-guardians_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/wibx.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/sturdy.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/clearpool.csv
INFO: Added market data for wibx
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/tether_candles.csv
INFO: Added market data for sturdy
INFO: Successfully loaded data for sturdy with 519 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/guild-of-guardians.csv
INFO: Added market data for clearpool
INFO: Successfully loaded data for wibx with 1925 rows.
INFO: Loaded data for sturdy with 519 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/echelon-prime_candles.csv

Loading assets:  55%|█████▍    | 119/218 [00:06<00:06, 14.47it/s]

INFO: Successfully loaded data for clearpool with 1366 rows.
INFO: Loaded data for wibx with 1925 rows
INFO: Loaded data for clearpool with 1366 rows
INFO: Added market data for guild-of-guardians
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/tether.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/usd-coin_candles.csv
INFO: Successfully loaded data for guild-of-guardians with 1311 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/echelon-prime.csv
INFO: Loaded data for guild-of-guardians with 1311 rows
INFO: Added market data for echelon-prime
INFO: Successfully loaded data for echelon-prime with 876 rows.
INFO: Added market data for tether
INFO: Successfully loaded data for tether with 3803 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/usd-coin.csv
INFO: Loaded data for echelon-prime with 876 rows
INFO: Loaded data for tether with 3803 rows

Loading assets:  56%|█████▋    | 123/218 [00:06<00:06, 13.90it/s]

INFO: Added market data for usd-coin
INFO: Successfully loaded data for usd-coin with 2486 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/arpa_candles.csv
INFO: Loaded data for usd-coin with 2486 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/celestia_candles.csv

Loading assets:  57%|█████▋    | 125/218 [00:07<00:07, 12.24it/s]

INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/ai16z_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/spell-token_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/arpa.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/celestia.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/ai16z.csv
INFO: Added market data for arpa
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/arbitrum_candles.csv
INFO: Successfully loaded data for arpa with 2250 rows.
INFO: Added market data for ai16z
INFO: Added market data for celestia
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/deep_candles.csv
INFO: Loaded data for arpa with 2250 rows
INFO: Successfully loaded data for ai16z with 271 rows.
INFO: Successfully loaded data for celestia with 633 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/spell-token.csv
INFO: Loaded data for ai16z with 271 rows
INFO: Loaded data for celestia with 633 rows

Loading assets:  58%|█████▊    | 127/218 [00:07<00:08, 10.84it/s]

INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/power-ledger_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/arbitrum.csv
INFO: Added market data for spell-token
INFO: Successfully loaded data for spell-token with 1519 rows.
INFO: Loaded data for spell-token with 1519 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/deep.csv
INFO: Added market data for arbitrum
INFO: Successfully loaded data for arbitrum with 855 rows.
INFO: Added market data for deep
INFO: Loaded data for arbitrum with 855 rows
INFO: Successfully loaded data for deep with 284 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/power-ledger.csv
INFO: Loaded data for deep with 284 rows
INFO: Added market data for power-ledger
INFO: Successfully loaded data for power-ledger with 2816 rows.
INFO: Loaded data for power-ledger with 2816 rows

Loading assets:  61%|██████    | 132/218 [00:07<00:05, 15.98it/s]

INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/tribe-2_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/tribe-2.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/virtual-protocol_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/tokenbot-2_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/ethervista_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/tokenbot-2.csv
INFO: Added market data for tribe-2
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/kujira_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/virtual-protocol.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/smartcash_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/orbit-3_candles.csv
INFO: Successfully loaded data for tribe-2 with 1574 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/ethervista.csv
INFO: Added market data for tokenbot-2
INFO: Loaded data for tribe-2 with 1574 rows
INFO: Added market data for virtual-protocol
INFO: Successfully loaded data for tokenbot-2 with 257 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/kujira.csv
INFO: Added market data for ethervista
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/smartcash.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/orbit-3.csv
INFO: Successfully loaded data for virtual-protocol with 575 rows.
INFO: Loaded data for tokenbot-2 with 257 rows
INFO: Successfully loaded data for ethervista with 327 rows.
INFO: Loaded data for virtual-protocol with 575 rows
INFO: Added market data for orbit-3

Loading assets:  62%|██████▏   | 135/218 [00:08<00:10,  7.77it/s]

INFO: Loaded data for ethervista with 327 rows
INFO: Added market data for kujira
INFO: Successfully loaded data for kujira with 1337 rows.
INFO: Successfully loaded data for orbit-3 with 229 rows.
INFO: Added market data for smartcash
INFO: Loaded data for kujira with 1337 rows
INFO: Loaded data for orbit-3 with 229 rows
INFO: Successfully loaded data for smartcash with 2877 rows.
INFO: Loaded data for smartcash with 2877 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/ethereum_candles.csv

Loading assets:  64%|██████▍   | 139/218 [00:08<00:07, 10.49it/s]

INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/griffain_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/ethereum.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/kaspa_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/new-xai-gork_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/griffain.csv
INFO: Added market data for ethereum
INFO: Added market data for griffain
INFO: Successfully loaded data for ethereum with 3640 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/kaspa.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/arkham_candles.csv
INFO: Successfully loaded data for griffain with 231 rows.
INFO: Loaded data for ethereum with 3640 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/audius_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/new-xai-gork.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/useless-3_candles.csv
INFO: Loaded data for griffain with 231 rows
INFO: Added market data for kaspa
INFO: Added market data for new-xai-gork
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/arkham.csv
INFO: Successfully loaded data for kaspa with 1157 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/audius.csv
INFO: Successfully loaded data for new-xai-gork with 84 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/useless-3.csv
INFO: Loaded data for kaspa with 1157 rows

Loading assets:  65%|██████▌   | 142/218 [00:09<00:10,  7.22it/s]

INFO: Loaded data for new-xai-gork with 84 rows
INFO: Added market data for arkham
INFO: Added market data for useless-3
INFO: Added market data for audius
INFO: Successfully loaded data for audius with 1736 rows.
INFO: Successfully loaded data for useless-3 with 75 rows.
INFO: Successfully loaded data for arkham with 738 rows.
INFO: Loaded data for audius with 1736 rows
INFO: Loaded data for useless-3 with 75 rows
INFO: Loaded data for arkham with 738 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/blockstack_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/blockstack.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/botto_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/yne_candles.csv
INFO: Added market data for blockstack
INFO: Successfully loaded data for blockstack with 2101 rows.
INFO: Loaded data for blockstack with 2101 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/evan-2_candles.csv

Loading assets:  67%|██████▋   | 147/218 [00:09<00:07,  9.77it/s]

INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/maker_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/yne.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/botto.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/instadapp_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/evan-2.csv
INFO: Added market data for yne
INFO: Added market data for botto
INFO: Successfully loaded data for botto with 1385 rows.
INFO: Added market data for evan-2
INFO: Successfully loaded data for yne with 214 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/maker.csv
INFO: Loaded data for botto with 1385 rows
INFO: Successfully loaded data for evan-2 with 245 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/venice-token_candles.csv
INFO: Loaded data for yne with 214 rows

Loading assets:  68%|██████▊   | 149/218 [00:09<00:07,  9.78it/s]

INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/instadapp.csv
INFO: Loaded data for evan-2 with 245 rows
INFO: Added market data for maker
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/sushi_candles.csv
INFO: Successfully loaded data for maker with 2774 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/venice-token.csv
INFO: Added market data for instadapp
INFO: Loaded data for maker with 2774 rows
INFO: Successfully loaded data for instadapp with 1500 rows.
INFO: Loaded data for instadapp with 1500 rows
INFO: Added market data for venice-token
INFO: Successfully loaded data for venice-token with 179 rows.
INFO: Loaded data for venice-token with 179 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/sushi.csv
INFO: Added market data for sushi
INFO: Successfully loaded data for sushi with 1792 rows.
INFO: Loaded data for sushi with 1792 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/akash-network_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/akash-network.csv
INFO: Added market data for akash-network
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/eos_candles.csv
INFO: Successfully loaded data for akash-network with 1743 rows.
INFO: Loaded data for akash-network with 1743 rows

Loading assets:  71%|███████   | 155/218 [00:09<00:04, 14.14it/s]

INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/story-2_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/arbdoge-ai_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/eos.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/gains-network_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/story-2.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/verasity_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/arbdoge-ai.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/bonk_candles.csv
INFO: Added market data for eos
INFO: Added market data for story-2
INFO: Added market data for arbdoge-ai
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/gains-network.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/verasity.csv
INFO: Successfully loaded data for eos with 2938 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/numeraire_candles.csv
INFO: Successfully loaded data for story-2 with 162 rows.
INFO: Successfully loaded data for arbdoge-ai with 829 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/bonk.csv
INFO: Added market data for gains-network
INFO: Successfully loaded data for gains-network with 1361 rows.
INFO: Added market data for verasity
INFO: Loaded data for story-2 with 162 rows
INFO: Loaded data for arbdoge-ai with 829 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/numeraire.csv
INFO: Loaded data for eos with 2938 rows
INFO: Loaded data for gains-network with 1361 rows

Loading assets:  72%|███████▏  | 158/218 [00:10<00:06,  8.98it/s]

INFO: Added market data for bonk
INFO: Successfully loaded data for verasity with 1616 rows.
INFO: Successfully loaded data for bonk with 939 rows.
INFO: Added market data for numeraire
INFO: Loaded data for verasity with 1616 rows
INFO: Loaded data for bonk with 939 rows
INFO: Successfully loaded data for numeraire with 2934 rows.
INFO: Loaded data for numeraire with 2934 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/star-atlas-dao_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/sonic-3_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/aerodrome-finance_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/sonic-3.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/star-atlas-dao.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/solayer_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/aerodrome-finance.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/plume_candles.csv
INFO: Added market data for sonic-3
INFO: Added market data for star-atlas-dao
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/jupiter-exchange-solana_candles.csv
INFO: Successfully loaded data for sonic-3 with 202 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/hedera-hashgraph_candles.csv
INFO: Added market data for aerodrome-finance
INFO: Successfully loaded data for star-atlas-dao with 1422 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/solayer.csv
INFO: Loaded data for sonic-3 with 202 rows

Loading assets:  75%|███████▍  | 163/218 [00:10<00:05, 10.21it/s]

INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/plume.csv
INFO: Successfully loaded data for aerodrome-finance with 679 rows.
INFO: Loaded data for star-atlas-dao with 1422 rows
INFO: Added market data for solayer
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/jupiter-exchange-solana.csv
INFO: Loaded data for aerodrome-finance with 679 rows
INFO: Successfully loaded data for solayer with 164 rows.
INFO: Added market data for plume
INFO: Successfully loaded data for plume with 185 rows.
INFO: Loaded data for solayer with 164 rows
INFO: Added market data for jupiter-exchange-solana
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/hedera-hashgraph.csv
INFO: Loaded data for plume with 185 rows
INFO: Successfully loaded data for jupiter-exchange-solana with 541 rows.
INFO: Loaded data for jupiter-exchange-solana with 541 rows
INFO: Added market data for hedera-hashgraph
INFO: Successfully loaded data for hedera-hashgraph with 2138 rows.
INFO: Loaded data for hedera-hashgraph with 2138 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/fwog_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/fwog.csv
INFO: Added market data for fwog
INFO: Successfully loaded data for fwog with 360 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/chex-token_candles.csv
INFO: Loaded data for fwog with 360 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/matic-network_candles.csv

Loading assets:  78%|███████▊  | 170/218 [00:11<00:03, 14.25it/s]

INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/popcat_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/official-trump_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/alchemy-pay_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/chex-token.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/official-trump.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/popcat.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/alchemy-pay.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/matic-network.csv
INFO: Added market data for official-trump
INFO: Added market data for chex-token
INFO: Successfully loaded data for chex-token with 1997 rows.
INFO: Successfully loaded data for official-trump with 188 rows.
INFO: Loaded data for chex-token with 1997 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/perpetual-protocol_candles.csv
INFO: Loaded data for official-trump with 188 rows

Loading assets:  79%|███████▉  | 172/218 [00:11<00:03, 14.56it/s]

INFO: Added market data for alchemy-pay
INFO: Added market data for matic-network
INFO: Added market data for popcat
INFO: Successfully loaded data for alchemy-pay with 1781 rows.
INFO: Successfully loaded data for matic-network with 2282 rows.
INFO: Successfully loaded data for popcat with 584 rows.
INFO: Loaded data for alchemy-pay with 1781 rows
INFO: Loaded data for matic-network with 2282 rows
INFO: Loaded data for popcat with 584 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/perpetual-protocol.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/shiba-inu_candles.csv
INFO: Added market data for perpetual-protocol
INFO: Successfully loaded data for perpetual-protocol with 1780 rows.
INFO: Loaded data for perpetual-protocol with 1780 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/shiba-inu.csv
INFO: Added market data for shiba-inu
INFO: Successfully loaded data for shiba-inu with 1805 rows.
INFO: Loaded data for shiba-inu with 1805 rows

Loading assets:  81%|████████  | 177/218 [00:11<00:02, 18.12it/s]

INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/snek_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/mog-coin_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/morpho_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/internet-computer_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/snek.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/morpho.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/mog-coin.csv
INFO: Added market data for snek
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/internet-computer.csv
INFO: Added market data for morpho
INFO: Successfully loaded data for snek with 795 rows.
INFO: Successfully loaded data for morpho with 247 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/litecoin_candles.csv
INFO: Added market data for mog-coin
INFO: Loaded data for snek with 795 rows
INFO: Loaded data for morpho with 247 rows
INFO: Added market data for internet-computer
INFO: Successfully loaded data for internet-computer with 1537 rows.
INFO: Successfully loaded data for mog-coin with 735 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/near_candles.csv
INFO: Loaded data for internet-computer with 1537 rows

Loading assets:  83%|████████▎ | 180/218 [00:11<00:02, 16.17it/s]

INFO: Loaded data for mog-coin with 735 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/litecoin.csv
INFO: Added market data for litecoin
INFO: Successfully loaded data for litecoin with 4471 rows.
INFO: Loaded data for litecoin with 4471 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/near.csv
INFO: Added market data for near
INFO: Successfully loaded data for near with 1745 rows.
INFO: Loaded data for near with 1745 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/injective-protocol_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/euler_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/radiant-capital_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/euler.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/injective-protocol.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/hypercycle_candles.csv
INFO: Added market data for euler
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/cow-protocol_candles.csv
INFO: Successfully loaded data for euler with 1127 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/radiant-capital.csv
INFO: Loaded data for euler with 1127 rows

Loading assets:  84%|████████▍ | 184/218 [00:11<00:02, 16.60it/s]

INFO: Added market data for injective-protocol
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/floki_candles.csv
INFO: Successfully loaded data for injective-protocol with 1738 rows.
INFO: Added market data for radiant-capital
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/cow-protocol.csv
INFO: Loaded data for injective-protocol with 1738 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/hypercycle.csv
INFO: Successfully loaded data for radiant-capital with 1095 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/swarm_candles.csv
INFO: Loaded data for radiant-capital with 1095 rows
INFO: Added market data for cow-protocol
INFO: Added market data for hypercycle
INFO: Successfully loaded data for cow-protocol with 1215 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/floki.csv
INFO: Successfully loaded data for hypercycle with 808 rows.
INFO: Loaded data for cow-protocol with 1215 rows
INFO: Loaded data for hypercycle with 808 rows
INFO: Added market data for floki

Loading assets:  86%|████████▌ | 188/218 [00:12<00:01, 19.73it/s]

INFO: Successfully loaded data for floki with 1488 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/swarm.csv
INFO: Loaded data for floki with 1488 rows
INFO: Added market data for swarm
INFO: Successfully loaded data for swarm with 3403 rows.
INFO: Loaded data for swarm with 3403 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/mubarak_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/mubarak.csv
INFO: Added market data for mubarak
INFO: Successfully loaded data for mubarak with 131 rows.
INFO: Loaded data for mubarak with 131 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/mintlayer_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/curve-dao-token_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/ethereum-classic_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/mintlayer.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/curve-dao-token.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/syrup_candles.csv
INFO: Added market data for mintlayer
INFO: Successfully loaded data for mintlayer with 853 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/gigachad-2_candles.csv
INFO: Loaded data for mintlayer with 853 rows

Loading assets:  88%|████████▊ | 192/218 [00:12<00:02, 12.06it/s]

INFO: Added market data for curve-dao-token
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/ethereum-classic.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/liquity_candles.csv
INFO: Successfully loaded data for curve-dao-token with 1806 rows.
INFO: Loaded data for curve-dao-token with 1806 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/syrup.csv
INFO: Added market data for ethereum-classic
INFO: Successfully loaded data for ethereum-classic with 3288 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/gigachad-2.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/liquity.csv
INFO: Loaded data for ethereum-classic with 3288 rows
INFO: Added market data for syrup
INFO: Added market data for gigachad-2
INFO: Successfully loaded data for syrup with 254 rows.
INFO: Successfully loaded data for gigachad-2 with 550 rows.
INFO: Loaded data for syrup with 254 rows
INFO: Added market data for liquity
INFO: Loaded data for gigachad-2 with 550 rows
INFO: Successfully loaded data for liquity with 1572 rows.
INFO: Loaded data for liquity with 1572 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/goatseus-maximus_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/goatseus-maximus.csv
INFO: Added market data for goatseus-maximus
INFO: Successfully loaded data for goatseus-maximus with 285 rows.
INFO: Loaded data for goatseus-maximus with 285 rows

Loading assets:  91%|█████████ | 198/218 [00:12<00:01, 17.27it/s]

INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/slerf_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/pax-gold_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/true-usd_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/slerf.csv
INFO: Added market data for slerf
INFO: Successfully loaded data for slerf with 494 rows.
INFO: Loaded data for slerf with 494 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/pax-gold.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/avalanche-2_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/true-usd.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/myria_candles.csv
INFO: Added market data for true-usd
INFO: Successfully loaded data for true-usd with 2682 rows.
INFO: Added market data for pax-gold
INFO: Loaded data for true-usd with 2682 rows
INFO: Successfully loaded data for pax-gold with 2140 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/avalanche-2.csv
INFO: Loaded data for pax-gold with 2140 rows

Loading assets:  92%|█████████▏| 201/218 [00:12<00:00, 17.21it/s]

INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/myria.csv
INFO: Added market data for avalanche-2
INFO: Successfully loaded data for avalanche-2 with 1767 rows.
INFO: Loaded data for avalanche-2 with 1767 rows
INFO: Added market data for myria
INFO: Successfully loaded data for myria with 841 rows.
INFO: Loaded data for myria with 841 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/y_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/y.csv
INFO: Added market data for y
INFO: Successfully loaded data for y with 480 rows.
INFO: Loaded data for y with 480 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/monero_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/mantra-dao_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/paal-ai_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/monero.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/mantra-dao.csv
INFO: Added market data for monero
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/constitutiondao_candles.csv
INFO: Successfully loaded data for monero with 4083 rows.
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/paal-ai.csv
INFO: Loaded data for monero with 4083 rows

Loading assets:  94%|█████████▍| 205/218 [00:13<00:00, 18.23it/s]

INFO: Added market data for mantra-dao
INFO: Successfully loaded data for mantra-dao with 1802 rows.
INFO: Loaded data for mantra-dao with 1802 rows
INFO: Added market data for paal-ai
INFO: Successfully loaded data for paal-ai with 760 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/cardano_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/constitutiondao.csv
INFO: Loaded data for paal-ai with 760 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/based-brett_candles.csv
INFO: Added market data for constitutiondao
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/ripple_candles.csv
INFO: Successfully loaded data for constitutiondao with 1344 rows.
INFO: Loaded data for constitutiondao with 1344 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/cardano.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/based-brett.csv
INFO: Added market data for cardano
INFO: Successfully loaded data for cardano with 2837 rows.
INFO: Added market data for based-brett
INFO: Loaded data for cardano with 2837 rows
INFO: Successfully loaded data for based-brett with 512 rows.

Loading assets:  96%|█████████▌| 209/218 [00:13<00:00, 21.00it/s]

INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/ripple.csv
INFO: Loaded data for based-brett with 512 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/osaka-protocol_candles.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/genopets_candles.csv
INFO: Added market data for ripple
INFO: Successfully loaded data for ripple with 4373 rows.
INFO: Loaded data for ripple with 4373 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/solana_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/osaka-protocol.csv
INFO: Added market data for osaka-protocol
INFO: Successfully loaded data for osaka-protocol with 749 rows.
INFO: Loaded data for osaka-protocol with 749 rows

Loading assets:  97%|█████████▋| 212/218 [00:13<00:00, 22.20it/s]

INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/genopets.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/solana.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/lagrange_candles.csv
INFO: Added market data for genopets
INFO: Successfully loaded data for genopets with 1345 rows.
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/frax-share_candles.csv
INFO: Added market data for solana
INFO: Loaded data for genopets with 1345 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/lagrange.csv
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/kaito_candles.csv
INFO: Successfully loaded data for solana with 1932 rows.
INFO: Loaded data for solana with 1932 rows
INFO: Added market data for lagrange
INFO: Successfully loaded data for lagrange with 51 rows.
INFO: Loaded data for lagrange with 51 rows
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/frax-share.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/kaito.csv
INFO: Added market data for frax-share
INFO: Successfully loaded data for frax-share with 1677 rows.
INFO: Loaded data for frax-share with 1677 rows
INFO: Added market data for kaito

Loading assets:  99%|█████████▉| 216/218 [00:13<00:00, 25.34it/s]

INFO: Successfully loaded data for kaito with 155 rows.
INFO: Loaded data for kaito with 155 rows
INFO: Loading data from file: /Users/valter.rebelo/MissionControl/data/micro/candleData/neon_candles.csv
INFO: Loading market data from file: /Users/valter.rebelo/MissionControl/data/micro/assetData/neon.csv
INFO: Added market data for neon
INFO: Successfully loaded data for neon with 738 rows.
INFO: Loaded data for neon with 738 rows

Loading assets: 100%|██████████| 218/218 [00:13<00:00, 16.10it/s]

INFO: Loaded data for 218 out of 218 assets

Loading assets: 100%|██████████| 218/218 [00:00<00:00, 426672.08it/s]

{'alpha-finance': AssetData(asset_id='alpha-finance', price_data_length=1749, signals=[], backtests=[]),
 'tokenbot-2': AssetData(asset_id='tokenbot-2', price_data_length=257, signals=[], backtests=[]),
 'lido-dao': AssetData(asset_id='lido-dao', price_data_length=1662, signals=[], backtests=[]),
 'mog-coin': AssetData(asset_id='mog-coin', price_data_length=735, signals=[], backtests=[]),
 'radiant-capital': AssetData(asset_id='radiant-capital', price_data_length=1095, signals=[], backtests=[]),
 'eos': AssetData(asset_id='eos', price_data_length=2938, signals=[], backtests=[]),
 'cardano': AssetData(asset_id='cardano', price_data_length=2837, signals=[], backtests=[]),
 'sturdy': AssetData(asset_id='sturdy', price_data_length=519, signals=[], backtests=[]),
 'secret': AssetData(asset_id='secret', price_data_length=1758, signals=[], backtests=[]),
 'genopets': AssetData(asset_id='genopets', price_data_length=1345, signals=[], backtests=[]),
 'liquity': AssetData(asset_id='liquity', price_data_length=1572, signals=[], backtests=[]),
 'acala': AssetData(asset_id='acala', price_data_length=1277, signals=[], backtests=[]),
 'litecoin': AssetData(asset_id='litecoin', price_data_length=4471, signals=[], backtests=[]),
 'star-atlas-dao': AssetData(asset_id='star-atlas-dao', price_data_length=1422, signals=[], backtests=[]),
 'terra-luna-2': AssetData(asset_id='terra-luna-2', price_data_length=1154, signals=[], backtests=[]),
 'ethervista': AssetData(asset_id='ethervista', price_data_length=327, signals=[], backtests=[]),
 'kyber-network-crystal': AssetData(asset_id='kyber-network-crystal', price_data_length=1555, signals=[], backtests=[]),
 'y': AssetData(asset_id='y', price_data_length=480, signals=[], backtests=[]),
 'sushi': AssetData(asset_id='sushi', price_data_length=1792, signals=[], backtests=[]),
 'my-neighbor-alice': AssetData(asset_id='my-neighbor-alice', price_data_length=1593, signals=[], backtests=[]),
 'aerodrome-finance': AssetData(asset_id='aerodrome-finance', price_data_length=679, signals=[], backtests=[]),
 'kujira': AssetData(asset_id='kujira', price_data_length=1337, signals=[], backtests=[]),
 'decentraland': AssetData(asset_id='decentraland', price_data_length=2827, signals=[], backtests=[]),
 'shiba-inu': AssetData(asset_id='shiba-inu', price_data_length=1805, signals=[], backtests=[]),
 'instadapp': AssetData(asset_id='instadapp', price_data_length=1500, signals=[], backtests=[]),
 'fwog': AssetData(asset_id='fwog', price_data_length=360, signals=[], backtests=[]),
 'clearpool': AssetData(asset_id='clearpool', price_data_length=1366, signals=[], backtests=[]),
 'heyanon': AssetData(asset_id='heyanon', price_data_length=210, signals=[], backtests=[]),
 'aioz-network': AssetData(asset_id='aioz-network', price_data_length=1574, signals=[], backtests=[]),
 'axelar': AssetData(asset_id='axelar', price_data_length=1032, signals=[], backtests=[]),
 'alchemist-ai': AssetData(asset_id='alchemist-ai', price_data_length=236, signals=[], backtests=[]),
 'internet-computer': AssetData(asset_id='internet-computer', price_data_length=1537, signals=[], backtests=[]),
 'ethereum': AssetData(asset_id='ethereum', price_data_length=3640, signals=[], backtests=[]),
 'quant-network': AssetData(asset_id='quant-network', price_data_length=2583, signals=[], backtests=[]),
 'mamo': AssetData(asset_id='mamo', price_data_length=65, signals=[], backtests=[]),
 'bitcoin-cash': AssetData(asset_id='bitcoin-cash', price_data_length=2914, signals=[], backtests=[]),
 'bittensor': AssetData(asset_id='bittensor', price_data_length=875, signals=[], backtests=[]),
 'ether-fi': AssetData(asset_id='ether-fi', price_data_length=494, signals=[], backtests=[]),
 'virtual-protocol': AssetData(asset_id='virtual-protocol', price_data_length=575, signals=[], backtests=[]),
 'zeus-network': AssetData(asset_id='zeus-network', price_data_length=476, signals=[], backtests=[]),
 'uniswap': AssetData(asset_id='uniswap', price_data_length=1772, signals=[], backtests=[]),
 'lisk': AssetData(asset_id='lisk', price_data_length=3397, signals=[], backtests=[]),
 'axie-infinity': AssetData(asset_id='axie-infinity', price_data_length=1724, signals=[], backtests=[]),
 'binancecoin': AssetData(asset_id='binancecoin', price_data_length=2869, signals=[], backtests=[]),
 'kaito': AssetData(asset_id='kaito', price_data_length=155, signals=[], backtests=[]),
 'gmx': AssetData(asset_id='gmx', price_data_length=1411, signals=[], backtests=[]),
 'gigachad-2': AssetData(asset_id='gigachad-2', price_data_length=550, signals=[], backtests=[]),
 'deep': AssetData(asset_id='deep', price_data_length=284, signals=[], backtests=[]),
 'euler': AssetData(asset_id='euler', price_data_length=1127, signals=[], backtests=[]),
 'sonic-3': AssetData(asset_id='sonic-3', price_data_length=202, signals=[], backtests=[]),
 'dydx': AssetData(asset_id='dydx', price_data_length=1416, signals=[], backtests=[]),
 'mintlayer': AssetData(asset_id='mintlayer', price_data_length=853, signals=[], backtests=[]),
 'venice-token': AssetData(asset_id='venice-token', price_data_length=179, signals=[], backtests=[]),
 'orbit-3': AssetData(asset_id='orbit-3', price_data_length=229, signals=[], backtests=[]),
 'tribe-2': AssetData(asset_id='tribe-2', price_data_length=1574, signals=[], backtests=[]),
 'tether': AssetData(asset_id='tether', price_data_length=3803, signals=[], backtests=[]),
 'baby-doge-coin': AssetData(asset_id='baby-doge-coin', price_data_length=1507, signals=[], backtests=[]),
 'stellar': AssetData(asset_id='stellar', price_data_length=4006, signals=[], backtests=[]),
 'yield-guild-games': AssetData(asset_id='yield-guild-games', price_data_length=1458, signals=[], backtests=[]),
 'zebec-network': AssetData(asset_id='zebec-network', price_data_length=466, signals=[], backtests=[]),
 'pancakeswap-token': AssetData(asset_id='pancakeswap-token', price_data_length=1760, signals=[], backtests=[]),
 'fantom': AssetData(asset_id='fantom', price_data_length=2461, signals=[], backtests=[]),
 'neiro-3': AssetData(asset_id='neiro-3', price_data_length=358, signals=[], backtests=[]),
 'metacade': AssetData(asset_id='metacade', price_data_length=836, signals=[], backtests=[]),
 'serum': AssetData(asset_id='serum', price_data_length=1809, signals=[], backtests=[]),
 'book-of-meme': AssetData(asset_id='book-of-meme', price_data_length=498, signals=[], backtests=[]),
 'goatseus-maximus': AssetData(asset_id='goatseus-maximus', price_data_length=285, signals=[], backtests=[]),
 'based-brett': AssetData(asset_id='based-brett', price_data_length=512, signals=[], backtests=[]),
 'floki': AssetData(asset_id='floki', price_data_length=1488, signals=[], backtests=[]),
 'polymath': AssetData(asset_id='polymath', price_data_length=2723, signals=[], backtests=[]),
 'botto': AssetData(asset_id='botto', price_data_length=1385, signals=[], backtests=[]),
 'the-open-network': AssetData(asset_id='the-open-network', price_data_length=1428, signals=[], backtests=[]),
 'nunet': AssetData(asset_id='nunet', price_data_length=1335, signals=[], backtests=[]),
 'gains-network': AssetData(asset_id='gains-network', price_data_length=1361, signals=[], backtests=[]),
 'immutable-x': AssetData(asset_id='immutable-x', price_data_length=1358, signals=[], backtests=[]),
 'lofi-2': AssetData(asset_id='lofi-2', price_data_length=243, signals=[], backtests=[]),
 'official-trump': AssetData(asset_id='official-trump', price_data_length=188, signals=[], backtests=[]),
 'celestia': AssetData(asset_id='celestia', price_data_length=633, signals=[], backtests=[]),
 'bubblemaps': AssetData(asset_id='bubblemaps', price_data_length=136, signals=[], backtests=[]),
 'aethir': AssetData(asset_id='aethir', price_data_length=408, signals=[], backtests=[]),
 'perpetual-protocol': AssetData(asset_id='perpetual-protocol', price_data_length=1780, signals=[], backtests=[]),
 'maker': AssetData(asset_id='maker', price_data_length=2774, signals=[], backtests=[]),
 'arkham': AssetData(asset_id='arkham', price_data_length=738, signals=[], backtests=[]),
 'arbdoge-ai': AssetData(asset_id='arbdoge-ai', price_data_length=829, signals=[], backtests=[]),
 'rari-governance-token': AssetData(asset_id='rari-governance-token', price_data_length=1741, signals=[], backtests=[]),
 'fartcoin': AssetData(asset_id='fartcoin', price_data_length=278, signals=[], backtests=[]),
 'eigenlayer': AssetData(asset_id='eigenlayer', price_data_length=297, signals=[], backtests=[]),
 'the-sandbox': AssetData(asset_id='the-sandbox', price_data_length=1806, signals=[], backtests=[]),
 'popcat': AssetData(asset_id='popcat', price_data_length=584, signals=[], backtests=[]),
 'dash': AssetData(asset_id='dash', price_data_length=4179, signals=[], backtests=[]),
 'hedera-hashgraph': AssetData(asset_id='hedera-hashgraph', price_data_length=2138, signals=[], backtests=[]),
 'helium': AssetData(asset_id='helium', price_data_length=1925, signals=[], backtests=[]),
 'dogecoin': AssetData(asset_id='dogecoin', price_data_length=4240, signals=[], backtests=[]),
 'dodo': AssetData(asset_id='dodo', price_data_length=1759, signals=[], backtests=[]),
 'harrypotterobamasonic10in': AssetData(asset_id='harrypotterobamasonic10in', price_data_length=802, signals=[], backtests=[]),
 'verasity': AssetData(asset_id='verasity', price_data_length=1616, signals=[], backtests=[]),
 'curve-dao-token': AssetData(asset_id='curve-dao-token', price_data_length=1806, signals=[], backtests=[]),
 'plume': AssetData(asset_id='plume', price_data_length=185, signals=[], backtests=[]),
 'compound-governance-token': AssetData(asset_id='compound-governance-token', price_data_length=1865, signals=[], backtests=[]),
 'turbo': AssetData(asset_id='turbo', price_data_length=813, signals=[], backtests=[]),
 'coredaoorg': AssetData(asset_id='coredaoorg', price_data_length=898, signals=[], backtests=[]),
 'slerf': AssetData(asset_id='slerf', price_data_length=494, signals=[], backtests=[]),
 'ethereum-classic': AssetData(asset_id='ethereum-classic', price_data_length=3288, signals=[], backtests=[]),
 'rainbow-token-2': AssetData(asset_id='rainbow-token-2', price_data_length=1224, signals=[], backtests=[]),
 'bonk': AssetData(asset_id='bonk', price_data_length=939, signals=[], backtests=[]),
 'aixbt': AssetData(asset_id='aixbt', price_data_length=249, signals=[], backtests=[]),
 'jupiter-exchange-solana': AssetData(asset_id='jupiter-exchange-solana', price_data_length=541, signals=[], backtests=[]),
 'useless-3': AssetData(asset_id='useless-3', price_data_length=75, signals=[], backtests=[]),
 'lagrange': AssetData(asset_id='lagrange', price_data_length=51, signals=[], backtests=[]),
 'raydium': AssetData(asset_id='raydium', price_data_length=1615, signals=[], backtests=[]),
 'arweave': AssetData(asset_id='arweave', price_data_length=2094, signals=[], backtests=[]),
 'aave': AssetData(asset_id='aave', price_data_length=1756, signals=[], backtests=[]),
 'equilibria-finance': AssetData(asset_id='equilibria-finance', price_data_length=779, signals=[], backtests=[]),
 'ava-ai': AssetData(asset_id='ava-ai', price_data_length=246, signals=[], backtests=[]),
 'blockstack': AssetData(asset_id='blockstack', price_data_length=2101, signals=[], backtests=[]),
 'chill-guy': AssetData(asset_id='chill-guy', price_data_length=249, signals=[], backtests=[]),
 'ai16z': AssetData(asset_id='ai16z', price_data_length=271, signals=[], backtests=[]),
 'balancer': AssetData(asset_id='balancer', price_data_length=1858, signals=[], backtests=[]),
 'new-xai-gork': AssetData(asset_id='new-xai-gork', price_data_length=84, signals=[], backtests=[]),
 'spell-token': AssetData(asset_id='spell-token', price_data_length=1519, signals=[], backtests=[]),
 'myria': AssetData(asset_id='myria', price_data_length=841, signals=[], backtests=[]),
 'ethena': AssetData(asset_id='ethena', price_data_length=479, signals=[], backtests=[]),
 'omisego': AssetData(asset_id='omisego', price_data_length=2931, signals=[], backtests=[]),
 'constitutiondao': AssetData(asset_id='constitutiondao', price_data_length=1344, signals=[], backtests=[]),
 'cow-protocol': AssetData(asset_id='cow-protocol', price_data_length=1215, signals=[], backtests=[]),
 'genesysgo-shadow': AssetData(asset_id='genesysgo-shadow', price_data_length=1297, signals=[], backtests=[]),
 'solayer': AssetData(asset_id='solayer', price_data_length=164, signals=[], backtests=[]),
 'kamino': AssetData(asset_id='kamino', price_data_length=451, signals=[], backtests=[]),
 'badger-dao': AssetData(asset_id='badger-dao', price_data_length=1694, signals=[], backtests=[]),
 'multibit': AssetData(asset_id='multibit', price_data_length=613, signals=[], backtests=[]),
 'swarm': AssetData(asset_id='swarm', price_data_length=3403, signals=[], backtests=[]),
 'snek': AssetData(asset_id='snek', price_data_length=795, signals=[], backtests=[]),
 'grass': AssetData(asset_id='grass', price_data_length=270, signals=[], backtests=[]),
 'prisma-governance-token': AssetData(asset_id='prisma-governance-token', price_data_length=631, signals=[], backtests=[]),
 'osaka-protocol': AssetData(asset_id='osaka-protocol', price_data_length=749, signals=[], backtests=[]),
 'chex-token': AssetData(asset_id='chex-token', price_data_length=1997, signals=[], backtests=[]),
 'power-ledger': AssetData(asset_id='power-ledger', price_data_length=2816, signals=[], backtests=[]),
 'cookie': AssetData(asset_id='cookie', price_data_length=407, signals=[], backtests=[]),
 'pax-gold': AssetData(asset_id='pax-gold', price_data_length=2140, signals=[], backtests=[]),
 'audius': AssetData(asset_id='audius', price_data_length=1736, signals=[], backtests=[]),
 'fetch-ai': AssetData(asset_id='fetch-ai', price_data_length=2339, signals=[], backtests=[]),
 'illuvium': AssetData(asset_id='illuvium', price_data_length=1577, signals=[], backtests=[]),
 'ripple': AssetData(asset_id='ripple', price_data_length=4373, signals=[], backtests=[]),
 'neon': AssetData(asset_id='neon', price_data_length=738, signals=[], backtests=[]),
 'evan-2': AssetData(asset_id='evan-2', price_data_length=245, signals=[], backtests=[]),
 'kekius-maximus': AssetData(asset_id='kekius-maximus', price_data_length=222, signals=[], backtests=[]),
 'numeraire': AssetData(asset_id='numeraire', price_data_length=2934, signals=[], backtests=[]),
 'prometeus': AssetData(asset_id='prometeus', price_data_length=2219, signals=[], backtests=[]),
 'optimism': AssetData(asset_id='optimism', price_data_length=1151, signals=[], backtests=[]),
 'cosmos': AssetData(asset_id='cosmos', price_data_length=2345, signals=[], backtests=[]),
 'render-token': AssetData(asset_id='render-token', price_data_length=1866, signals=[], backtests=[]),
 'crypto-com-chain': AssetData(asset_id='crypto-com-chain', price_data_length=2397, signals=[], backtests=[]),
 'injective-protocol': AssetData(asset_id='injective-protocol', price_data_length=1738, signals=[], backtests=[]),
 'spx6900': AssetData(asset_id='spx6900', price_data_length=697, signals=[], backtests=[]),
 'aurory': AssetData(asset_id='aurory', price_data_length=1370, signals=[], backtests=[]),
 'pendle': AssetData(asset_id='pendle', price_data_length=1549, signals=[], backtests=[]),
 'thorchain': AssetData(asset_id='thorchain', price_data_length=2197, signals=[], backtests=[]),
 'grok-2': AssetData(asset_id='grok-2', price_data_length=626, signals=[], backtests=[]),
 'true-usd': AssetData(asset_id='true-usd', price_data_length=2682, signals=[], backtests=[]),
 'anzen-finance': AssetData(asset_id='anzen-finance', price_data_length=228, signals=[], backtests=[]),
 'moonwell-artemis': AssetData(asset_id='moonwell-artemis', price_data_length=1128, signals=[], backtests=[]),
 'paal-ai': AssetData(asset_id='paal-ai', price_data_length=760, signals=[], backtests=[]),
 'havven': AssetData(asset_id='havven', price_data_length=2684, signals=[], backtests=[]),
 'kaspa': AssetData(asset_id='kaspa', price_data_length=1157, signals=[], backtests=[]),
 'avalanche-2': AssetData(asset_id='avalanche-2', price_data_length=1767, signals=[], backtests=[]),
 'band-protocol': AssetData(asset_id='band-protocol', price_data_length=2137, signals=[], backtests=[]),
 'worldcoin-wld': AssetData(asset_id='worldcoin-wld', price_data_length=732, signals=[], backtests=[]),
 'gala': AssetData(asset_id='gala', price_data_length=1773, signals=[], backtests=[]),
 'alchemy-pay': AssetData(asset_id='alchemy-pay', price_data_length=1781, signals=[], backtests=[]),
 'usd-coin': AssetData(asset_id='usd-coin', price_data_length=2486, signals=[], backtests=[]),
 'wibx': AssetData(asset_id='wibx', price_data_length=1925, signals=[], backtests=[]),
 'jasmycoin': AssetData(asset_id='jasmycoin', price_data_length=1522, signals=[], backtests=[]),
 'zcash': AssetData(asset_id='zcash', price_data_length=3191, signals=[], backtests=[]),
 'mantra-dao': AssetData(asset_id='mantra-dao', price_data_length=1802, signals=[], backtests=[]),
 'arpa': AssetData(asset_id='arpa', price_data_length=2250, signals=[], backtests=[]),
 'conic-finance': AssetData(asset_id='conic-finance', price_data_length=1012, signals=[], backtests=[]),
 'flow': AssetData(asset_id='flow', price_data_length=1640, signals=[], backtests=[]),
 'morpho': AssetData(asset_id='morpho', price_data_length=247, signals=[], backtests=[]),
 'griffain': AssetData(asset_id='griffain', price_data_length=231, signals=[], backtests=[]),
 'hypercycle': AssetData(asset_id='hypercycle', price_data_length=808, signals=[], backtests=[]),
 'ronin': AssetData(asset_id='ronin', price_data_length=1275, signals=[], backtests=[]),
 'hyperliquid': AssetData(asset_id='hyperliquid', price_data_length=239, signals=[], backtests=[]),
 'kryptonite': AssetData(asset_id='kryptonite', price_data_length=711, signals=[], backtests=[]),
 'apu-s-club': AssetData(asset_id='apu-s-club', price_data_length=499, signals=[], backtests=[]),
 'dogwifcoin': AssetData(asset_id='dogwifcoin', price_data_length=590, signals=[], backtests=[]),
 'frax-share': AssetData(asset_id='frax-share', price_data_length=1677, signals=[], backtests=[]),
 'echelon-prime': AssetData(asset_id='echelon-prime', price_data_length=876, signals=[], backtests=[]),
 'dusk-network': AssetData(asset_id='dusk-network', price_data_length=2211, signals=[], backtests=[]),
 'yearn-finance': AssetData(asset_id='yearn-finance', price_data_length=1833, signals=[], backtests=[]),
 'chainlink': AssetData(asset_id='chainlink', price_data_length=2815, signals=[], backtests=[]),
 'matic-network': AssetData(asset_id='matic-network', price_data_length=2282, signals=[], backtests=[]),
 'story-2': AssetData(asset_id='story-2', price_data_length=162, signals=[], backtests=[]),
 'sei-network': AssetData(asset_id='sei-network', price_data_length=710, signals=[], backtests=[]),
 'bitcoin': AssetData(asset_id='bitcoin', price_data_length=4471, signals=[], backtests=[]),
 'syrup': AssetData(asset_id='syrup', price_data_length=254, signals=[], backtests=[]),
 'tron': AssetData(asset_id='tron', price_data_length=2815, signals=[], backtests=[]),
 'ondo-finance': AssetData(asset_id='ondo-finance', price_data_length=554, signals=[], backtests=[]),
 'monero': AssetData(asset_id='monero', price_data_length=4083, signals=[], backtests=[]),
 'guild-of-guardians': AssetData(asset_id='guild-of-guardians', price_data_length=1311, signals=[], backtests=[]),
 'vela-token': AssetData(asset_id='vela-token', price_data_length=903, signals=[], backtests=[]),
 'tezos': AssetData(asset_id='tezos', price_data_length=2581, signals=[], backtests=[]),
 'arbitrum': AssetData(asset_id='arbitrum', price_data_length=855, signals=[], backtests=[]),
 'pepe': AssetData(asset_id='pepe', price_data_length=829, signals=[], backtests=[]),
 'beam-2': AssetData(asset_id='beam-2', price_data_length=638, signals=[], backtests=[]),
 'akash-network': AssetData(asset_id='akash-network', price_data_length=1743, signals=[], backtests=[]),

In [2]:
# Register specific signals by their exact names
signals = analyzer.register_signals_parallel(
    asset_ids=assets, 
    calculate_values=True,
    specific_signals=[
                      "DonchianEnsembleUSD", "DonchianEnsembleBTC",
                      "RSI_Bullish_USD", "RSI_Bullish_BTC",
                      "TrendMomentumUSD", "TrendMomentumBTC"]
)
signals

INFO: Registering signals in parallel for 218 assets...
INFO: Converted asset_ids to list with 218 items
INFO: Using 6 specific signals provided by user
INFO: Using 7 workers for parallel signal registration
INFO: Processing asset group 1/44 with 5 assets
INFO: Starting signal registration for axie-infinity
INFO: Starting signal registration for tezos
INFO: Registering 6 new signals for axie-infinity

Registering signals group 1/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for neiro-3
INFO: Starting signal registration for coredaoorg
INFO: Starting signal registration for heyanon
INFO: Registering 6 new signals for tezos
INFO: Registering 6 new signals for neiro-3
INFO: Registering 6 new signals for coredaoorg
INFO: Registering 6 new signals for heyanon
INFO: Adapted windows for data length 358: [4, 9, 14, 29, 44, 74]
INFO: Adapted windows for data length 210: [5, 8, 17, 26, 43]
INFO: Asset heyanon: Using 5 windows with threshold 3
INFO: Asset neiro-3: Using 6 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on heyanon: 210 points
INFO: Calculated initial values for DonchianEnsembleUSD on neiro-3: 358 points
INFO: Calculated initial values for DonchianEnsembleBTC on heyanon: 210 points
INFO: Asset coredaoorg: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on coredaoorg: 898 points
INFO: Calculated initial values for RSI_Bullish_USD on heyanon: 210 points
INFO: Asset axie-infinity: Using 9 windows with threshold 3
INFO: Calculated initial values for RSI_Bullish_BTC on heyanon: 210 points
INFO: Calculated initial values for DonchianEnsembleBTC on neiro-3: 358 points
INFO: Calculated initial values for DonchianEnsembleUSD on axie-infinity: 1724 points
INFO: Calculated initial values for TrendMomentumUSD on heyanon: 210 points
INFO: Calculated initial values for TrendMomentumBTC on heyanon: 210 points
INFO: Calculated initial values for RSI_Bullish_USD on neiro-3: 358 points
INFO: Completed signal registration for heyanon in 3.81 seconds
INFO: Calculated initial values for RSI_Bullish_BTC on neiro-3: 358 points

Registering signals group 1/44:  20%|██        | 1/5 [00:04<00:17,  4.37s/it]

INFO: Calculated initial values for TrendMomentumUSD on neiro-3: 358 points
INFO: Calculated initial values for TrendMomentumBTC on neiro-3: 358 points
INFO: Completed signal registration for neiro-3 in 5.06 seconds

Registering signals group 1/44:  40%|████      | 2/5 [00:05<00:06,  2.31s/it]

INFO: Asset tezos: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on tezos: 2581 points
INFO: Calculated initial values for DonchianEnsembleBTC on coredaoorg: 898 points
INFO: Calculated initial values for RSI_Bullish_USD on coredaoorg: 898 points
INFO: Calculated initial values for RSI_Bullish_BTC on coredaoorg: 898 points
INFO: Calculated initial values for TrendMomentumUSD on coredaoorg: 898 points
INFO: Calculated initial values for TrendMomentumBTC on coredaoorg: 898 points
INFO: Completed signal registration for coredaoorg in 10.08 seconds

Registering signals group 1/44:  60%|██████    | 3/5 [00:10<00:07,  3.52s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on axie-infinity: 1724 points
INFO: Calculated initial values for RSI_Bullish_USD on axie-infinity: 1724 points
INFO: Calculated initial values for RSI_Bullish_BTC on axie-infinity: 1724 points
INFO: Calculated initial values for TrendMomentumUSD on axie-infinity: 1724 points
INFO: Calculated initial values for DonchianEnsembleBTC on tezos: 2581 points
INFO: Calculated initial values for TrendMomentumBTC on axie-infinity: 1724 points
INFO: Completed signal registration for axie-infinity in 13.90 seconds

Registering signals group 1/44:  80%|████████  | 4/5 [00:13<00:03,  3.62s/it]

INFO: Calculated initial values for RSI_Bullish_USD on tezos: 2581 points
INFO: Calculated initial values for RSI_Bullish_BTC on tezos: 2581 points
INFO: Calculated initial values for TrendMomentumUSD on tezos: 2581 points
INFO: Calculated initial values for TrendMomentumBTC on tezos: 2581 points
INFO: Completed signal registration for tezos in 15.98 seconds

Registering signals group 1/44: 100%|██████████| 5/5 [00:15<00:00,  3.20s/it]

INFO: Processing asset group 2/44 with 5 assets
INFO: Starting signal registration for dogwifcoin
INFO: Starting signal registration for quant-network

INFO: Starting signal registration for fartcoin

Registering signals group 2/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 6 new signals for dogwifcoin
INFO: Starting signal registration for dodo
INFO: Starting signal registration for grok-2
INFO: Registering 6 new signals for quant-network
INFO: Registering 6 new signals for fartcoin
INFO: Adapted windows for data length 590: [4, 8, 16, 24, 49, 73, 122]
INFO: Registering 6 new signals for dodo
INFO: Registering 6 new signals for grok-2
INFO: Adapted windows for data length 278: [3, 7, 11, 23, 34, 57]
INFO: Adapted windows for data length 626: [4, 8, 17, 26, 52, 78, 130]
INFO: Asset dogwifcoin: Using 7 windows with threshold 3
INFO: Asset fartcoin: Using 6 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on dogwifcoin: 590 points
INFO: Calculated initial values for DonchianEnsembleUSD on fartcoin: 278 points
INFO: Asset grok-2: Using 7 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on grok-2: 626 points
INFO: Calculated initial values for DonchianEnsembleBTC on fartcoin: 278 points
INFO: Calculated initial values for RSI_Bullish_USD on fartcoin: 278 points
INFO: Calculated initial values for RSI_Bullish_BTC on fartcoin: 278 points
INFO: Calculated initial values for DonchianEnsembleBTC on dogwifcoin: 590 points
INFO: Asset dodo: Using 9 windows with threshold 3
INFO: Calculated initial values for TrendMomentumUSD on fartcoin: 278 points
INFO: Calculated initial values for DonchianEnsembleBTC on grok-2: 626 points
INFO: Calculated initial values for DonchianEnsembleUSD on dodo: 1759 points
INFO: Calculated initial values for TrendMomentumBTC on fartcoin: 278 points
INFO: Completed signal registration for fartcoin in 7.13 seconds

Registering signals group 2/44:  20%|██        | 1/5 [00:07<00:28,  7.23s/it]

INFO: Calculated initial values for RSI_Bullish_USD on dogwifcoin: 590 points
INFO: Asset quant-network: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on quant-network: 2583 points
INFO: Calculated initial values for RSI_Bullish_USD on grok-2: 626 points
INFO: Calculated initial values for RSI_Bullish_BTC on dogwifcoin: 590 points
INFO: Calculated initial values for RSI_Bullish_BTC on grok-2: 626 points
INFO: Calculated initial values for TrendMomentumUSD on dogwifcoin: 590 points
INFO: Calculated initial values for TrendMomentumUSD on grok-2: 626 points
INFO: Calculated initial values for TrendMomentumBTC on dogwifcoin: 590 points
INFO: Completed signal registration for dogwifcoin in 9.57 seconds

Registering signals group 2/44:  40%|████      | 2/5 [00:09<00:13,  4.40s/it]

INFO: Calculated initial values for TrendMomentumBTC on grok-2: 626 points
INFO: Completed signal registration for grok-2 in 9.98 seconds

Registering signals group 2/44:  60%|██████    | 3/5 [00:10<00:05,  2.61s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on dodo: 1759 points
INFO: Calculated initial values for RSI_Bullish_USD on dodo: 1759 points
INFO: Calculated initial values for DonchianEnsembleBTC on quant-network: 2583 points
INFO: Calculated initial values for RSI_Bullish_BTC on dodo: 1759 points
INFO: Calculated initial values for TrendMomentumUSD on dodo: 1759 points
INFO: Calculated initial values for TrendMomentumBTC on dodo: 1759 points
INFO: Completed signal registration for dodo in 16.07 seconds

Registering signals group 2/44:  80%|████████  | 4/5 [00:16<00:03,  3.95s/it]

INFO: Calculated initial values for RSI_Bullish_USD on quant-network: 2583 points
INFO: Calculated initial values for RSI_Bullish_BTC on quant-network: 2583 points
INFO: Calculated initial values for TrendMomentumUSD on quant-network: 2583 points
INFO: Calculated initial values for TrendMomentumBTC on quant-network: 2583 points
INFO: Completed signal registration for quant-network in 17.45 seconds

Registering signals group 2/44: 100%|██████████| 5/5 [00:17<00:00,  3.49s/it]

INFO: Processing asset group 3/44 with 5 assets
INFO: Starting signal registration for moonwell-artemis

INFO: Registering 6 new signals for moonwell-artemis

Registering signals group 3/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for optimism
INFO: Starting signal registration for yearn-finance
INFO: Starting signal registration for aixbt
INFO: Starting signal registration for hyperliquid
INFO: Registering 6 new signals for optimism
INFO: Registering 6 new signals for yearn-finance
INFO: Registering 6 new signals for aixbt
INFO: Registering 6 new signals for hyperliquid
INFO: Adapted windows for data length 249: [3, 6, 10, 20, 31, 51]
INFO: Adapted windows for data length 239: [3, 6, 9, 19, 29, 49]
INFO: Asset moonwell-artemis: Using 9 windows with threshold 3
INFO: Asset aixbt: Using 6 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on moonwell-artemis: 1128 points
INFO: Asset hyperliquid: Using 6 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on aixbt: 249 points
INFO: Calculated initial values for DonchianEnsembleUSD on hyperliquid: 239 points
INFO: Asset optimism: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on optimism: 1151 points
INFO: Calculated initial values for DonchianEnsembleBTC on aixbt: 249 points
INFO: Calculated initial values for DonchianEnsembleBTC on hyperliquid: 239 points
INFO: Calculated initial values for RSI_Bullish_USD on aixbt: 249 points
INFO: Calculated initial values for RSI_Bullish_USD on hyperliquid: 239 points
INFO: Calculated initial values for RSI_Bullish_BTC on aixbt: 249 points
INFO: Calculated initial values for RSI_Bullish_BTC on hyperliquid: 239 points
INFO: Calculated initial values for TrendMomentumUSD on aixbt: 249 points
INFO: Calculated initial values for TrendMomentumUSD on hyperliquid: 239 points
INFO: Calculated initial values for TrendMomentumBTC on aixbt: 249 points
INFO: Asset yearn-finance: Using 9 windows with threshold 3
INFO: Calculated initial values for TrendMomentumBTC on hyperliquid: 239 points
INFO: Completed signal registration for aixbt in 5.20 seconds
INFO: Calculated initial values for DonchianEnsembleUSD on yearn-finance: 1833 points

Registering signals group 3/44:  20%|██        | 1/5 [00:05<00:22,  5.73s/it]

INFO: Completed signal registration for hyperliquid in 5.35 seconds

Registering signals group 3/44:  40%|████      | 2/5 [00:06<00:07,  2.55s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on moonwell-artemis: 1128 points
INFO: Calculated initial values for DonchianEnsembleBTC on optimism: 1151 points
INFO: Calculated initial values for RSI_Bullish_USD on moonwell-artemis: 1128 points
INFO: Calculated initial values for RSI_Bullish_BTC on moonwell-artemis: 1128 points
INFO: Calculated initial values for TrendMomentumUSD on moonwell-artemis: 1128 points
INFO: Calculated initial values for RSI_Bullish_USD on optimism: 1151 points
INFO: Calculated initial values for TrendMomentumBTC on moonwell-artemis: 1128 points
INFO: Completed signal registration for moonwell-artemis in 10.13 seconds

Registering signals group 3/44:  60%|██████    | 3/5 [00:10<00:06,  3.25s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on optimism: 1151 points
INFO: Calculated initial values for TrendMomentumUSD on optimism: 1151 points
INFO: Calculated initial values for TrendMomentumBTC on optimism: 1151 points
INFO: Calculated initial values for DonchianEnsembleBTC on yearn-finance: 1833 points
INFO: Completed signal registration for optimism in 10.97 seconds

Registering signals group 3/44:  80%|████████  | 4/5 [00:11<00:02,  2.31s/it]

INFO: Calculated initial values for RSI_Bullish_USD on yearn-finance: 1833 points
INFO: Calculated initial values for RSI_Bullish_BTC on yearn-finance: 1833 points
INFO: Calculated initial values for TrendMomentumUSD on yearn-finance: 1833 points
INFO: Calculated initial values for TrendMomentumBTC on yearn-finance: 1833 points
INFO: Completed signal registration for yearn-finance in 12.39 seconds

Registering signals group 3/44: 100%|██████████| 5/5 [00:12<00:00,  2.50s/it]

INFO: Processing asset group 4/44 with 5 assets
INFO: Starting signal registration for illuvium

INFO: Registering 6 new signals for illuvium
INFO: Starting signal registration for dusk-network
INFO: Starting signal registration for alchemist-ai

Registering signals group 4/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for havven
INFO: Starting signal registration for ondo-finance
INFO: Registering 6 new signals for dusk-network
INFO: Registering 6 new signals for alchemist-ai
INFO: Registering 6 new signals for havven
INFO: Registering 6 new signals for ondo-finance
INFO: Adapted windows for data length 236: [3, 6, 9, 19, 29, 49]
INFO: Adapted windows for data length 554: [3, 7, 15, 23, 46, 69, 115]
INFO: Asset alchemist-ai: Using 6 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on alchemist-ai: 236 points
INFO: Asset ondo-finance: Using 7 windows with threshold 3
INFO: Asset illuvium: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on ondo-finance: 554 points
INFO: Calculated initial values for DonchianEnsembleBTC on alchemist-ai: 236 points
INFO: Calculated initial values for DonchianEnsembleUSD on illuvium: 1577 points
INFO: Calculated initial values for RSI_Bullish_USD on alchemist-ai: 236 points
INFO: Calculated initial values for RSI_Bullish_BTC on alchemist-ai: 236 points
INFO: Calculated initial values for TrendMomentumUSD on alchemist-ai: 236 points
INFO: Calculated initial values for TrendMomentumBTC on alchemist-ai: 236 points
INFO: Completed signal registration for alchemist-ai in 4.22 seconds

Registering signals group 4/44:  20%|██        | 1/5 [00:04<00:17,  4.36s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on ondo-finance: 554 points
INFO: Asset dusk-network: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on dusk-network: 2211 points
INFO: Calculated initial values for RSI_Bullish_USD on ondo-finance: 554 points
INFO: Calculated initial values for RSI_Bullish_BTC on ondo-finance: 554 points
INFO: Asset havven: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on havven: 2684 points
INFO: Calculated initial values for TrendMomentumUSD on ondo-finance: 554 points
INFO: Calculated initial values for TrendMomentumBTC on ondo-finance: 554 points
INFO: Completed signal registration for ondo-finance in 6.64 seconds

Registering signals group 4/44:  40%|████      | 2/5 [00:06<00:09,  3.31s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on illuvium: 1577 points
INFO: Calculated initial values for RSI_Bullish_USD on illuvium: 1577 points
INFO: Calculated initial values for RSI_Bullish_BTC on illuvium: 1577 points
INFO: Calculated initial values for DonchianEnsembleBTC on dusk-network: 2211 points
INFO: Calculated initial values for TrendMomentumUSD on illuvium: 1577 points
INFO: Calculated initial values for TrendMomentumBTC on illuvium: 1577 points
INFO: Completed signal registration for illuvium in 14.72 seconds

Registering signals group 4/44:  60%|██████    | 3/5 [00:14<00:10,  5.39s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on havven: 2684 points
INFO: Calculated initial values for RSI_Bullish_USD on dusk-network: 2211 points
INFO: Calculated initial values for RSI_Bullish_BTC on dusk-network: 2211 points
INFO: Calculated initial values for TrendMomentumUSD on dusk-network: 2211 points
INFO: Calculated initial values for TrendMomentumBTC on dusk-network: 2211 points
INFO: Completed signal registration for dusk-network in 17.49 seconds

Registering signals group 4/44:  80%|████████  | 4/5 [00:17<00:04,  4.33s/it]

INFO: Calculated initial values for RSI_Bullish_USD on havven: 2684 points
INFO: Calculated initial values for RSI_Bullish_BTC on havven: 2684 points
INFO: Calculated initial values for TrendMomentumUSD on havven: 2684 points
INFO: Calculated initial values for TrendMomentumBTC on havven: 2684 points
INFO: Completed signal registration for havven in 18.44 seconds

Registering signals group 4/44: 100%|██████████| 5/5 [00:18<00:00,  3.71s/it]

INFO: Processing asset group 5/44 with 5 assets
INFO: Starting signal registration for fetch-ai
INFO: Starting signal registration for ronin

INFO: Starting signal registration for omisego

Registering signals group 5/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 6 new signals for fetch-ai
INFO: Starting signal registration for acala
INFO: Registering 6 new signals for acala
INFO: Registering 6 new signals for ronin
INFO: Registering 6 new signals for omisego
INFO: Starting signal registration for band-protocol
INFO: Registering 6 new signals for band-protocol
INFO: Asset acala: Using 9 windows with threshold 3
INFO: Asset ronin: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on acala: 1277 points
INFO: Calculated initial values for DonchianEnsembleUSD on ronin: 1275 points
INFO: Asset fetch-ai: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on fetch-ai: 2339 points
INFO: Asset band-protocol: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on band-protocol: 2137 points
INFO: Asset omisego: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on omisego: 2931 points
INFO: Calculated initial values for DonchianEnsembleBTC on ronin: 1275 points
INFO: Calculated initial values for DonchianEnsembleBTC on acala: 1277 points
INFO: Calculated initial values for RSI_Bullish_USD on ronin: 1275 points
INFO: Calculated initial values for RSI_Bullish_USD on acala: 1277 points
INFO: Calculated initial values for RSI_Bullish_BTC on ronin: 1275 points
INFO: Calculated initial values for RSI_Bullish_BTC on acala: 1277 points
INFO: Calculated initial values for TrendMomentumUSD on ronin: 1275 points
INFO: Calculated initial values for TrendMomentumUSD on acala: 1277 points
INFO: Calculated initial values for TrendMomentumBTC on ronin: 1275 points
INFO: Calculated initial values for DonchianEnsembleBTC on fetch-ai: 2339 points
INFO: Completed signal registration for ronin in 20.07 seconds

Registering signals group 5/44:  20%|██        | 1/5 [00:20<01:21, 20.35s/it]

INFO: Calculated initial values for TrendMomentumBTC on acala: 1277 points
INFO: Calculated initial values for DonchianEnsembleBTC on band-protocol: 2137 points
INFO: Completed signal registration for acala in 20.69 seconds

Registering signals group 5/44:  40%|████      | 2/5 [00:20<00:26,  8.68s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on omisego: 2931 points
INFO: Calculated initial values for RSI_Bullish_USD on fetch-ai: 2339 points
INFO: Calculated initial values for RSI_Bullish_USD on band-protocol: 2137 points
INFO: Calculated initial values for RSI_Bullish_BTC on band-protocol: 2137 points
INFO: Calculated initial values for RSI_Bullish_BTC on fetch-ai: 2339 points
INFO: Calculated initial values for TrendMomentumUSD on band-protocol: 2137 points
INFO: Calculated initial values for TrendMomentumUSD on fetch-ai: 2339 points
INFO: Calculated initial values for TrendMomentumBTC on band-protocol: 2137 points
INFO: Calculated initial values for TrendMomentumBTC on fetch-ai: 2339 points
INFO: Completed signal registration for band-protocol in 26.11 seconds
INFO: Completed signal registration for fetch-ai in 26.95 seconds

Registering signals group 5/44:  60%|██████    | 3/5 [00:26<00:14,  7.49s/it]

INFO: Calculated initial values for RSI_Bullish_USD on omisego: 2931 points
INFO: Calculated initial values for RSI_Bullish_BTC on omisego: 2931 points
INFO: Calculated initial values for TrendMomentumUSD on omisego: 2931 points
INFO: Calculated initial values for TrendMomentumBTC on omisego: 2931 points
INFO: Completed signal registration for omisego in 28.23 seconds

Registering signals group 5/44: 100%|██████████| 5/5 [00:28<00:00,  5.65s/it]

INFO: Processing asset group 6/44 with 5 assets
INFO: Starting signal registration for gala

INFO: Starting signal registration for bitcoin

Registering signals group 6/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for multibit
INFO: Starting signal registration for stellar
INFO: Starting signal registration for uniswap
INFO: Registering 6 new signals for gala
INFO: Registering 6 new signals for bitcoin
INFO: Registering 6 new signals for multibit
INFO: Registering 6 new signals for stellar
INFO: Registering 6 new signals for uniswap
INFO: Adapted windows for data length 613: [4, 8, 17, 25, 51, 76, 127]
INFO: Asset multibit: Using 7 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on multibit: 613 points
INFO: Asset gala: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on gala: 1773 points
INFO: Asset uniswap: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleBTC on multibit: 613 points
INFO: Calculated initial values for DonchianEnsembleUSD on uniswap: 1772 points
INFO: Calculated initial values for RSI_Bullish_USD on multibit: 613 points
INFO: Calculated initial values for RSI_Bullish_BTC on multibit: 613 points
INFO: Calculated initial values for TrendMomentumUSD on multibit: 613 points
INFO: Calculated initial values for TrendMomentumBTC on multibit: 613 points
INFO: Completed signal registration for multibit in 9.41 seconds

Registering signals group 6/44:  20%|██        | 1/5 [00:09<00:38,  9.61s/it]

INFO: Asset stellar: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on stellar: 4006 points
INFO: Asset bitcoin: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on bitcoin: 4471 points
INFO: Calculated initial values for DonchianEnsembleBTC on gala: 1773 points
INFO: Calculated initial values for DonchianEnsembleBTC on uniswap: 1772 points
INFO: Calculated initial values for RSI_Bullish_USD on gala: 1773 points
INFO: Calculated initial values for RSI_Bullish_USD on uniswap: 1772 points
INFO: Calculated initial values for RSI_Bullish_BTC on gala: 1773 points
INFO: Calculated initial values for RSI_Bullish_BTC on uniswap: 1772 points
INFO: Calculated initial values for TrendMomentumUSD on gala: 1773 points
INFO: Calculated initial values for TrendMomentumUSD on uniswap: 1772 points
INFO: Calculated initial values for TrendMomentumBTC on gala: 1773 points
INFO: Completed signal registration for gala in 21.20 seconds
INFO: Calculated initial values for TrendMomentumBTC on uniswap: 1772 points

Registering signals group 6/44:  40%|████      | 2/5 [00:21<00:32, 10.88s/it]

INFO: Completed signal registration for uniswap in 22.03 seconds

Registering signals group 6/44:  60%|██████    | 3/5 [00:22<00:12,  6.23s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on bitcoin: 4471 points
INFO: Calculated initial values for RSI_Bullish_USD on bitcoin: 4471 points
INFO: Calculated initial values for RSI_Bullish_BTC on bitcoin: 4471 points
INFO: Calculated initial values for TrendMomentumUSD on bitcoin: 4471 points
INFO: Calculated initial values for TrendMomentumBTC on bitcoin: 4471 points
INFO: Completed signal registration for bitcoin in 24.71 seconds

Registering signals group 6/44:  80%|████████  | 4/5 [00:24<00:04,  4.84s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on stellar: 4006 points
INFO: Calculated initial values for RSI_Bullish_USD on stellar: 4006 points
INFO: Calculated initial values for RSI_Bullish_BTC on stellar: 4006 points
INFO: Calculated initial values for TrendMomentumUSD on stellar: 4006 points
INFO: Calculated initial values for TrendMomentumBTC on stellar: 4006 points
INFO: Completed signal registration for stellar in 28.85 seconds

Registering signals group 6/44: 100%|██████████| 5/5 [00:28<00:00,  5.77s/it]

INFO: Processing asset group 7/44 with 5 assets
INFO: Starting signal registration for apu-s-club
INFO: Starting signal registration for the-sandbox

INFO: Registering 6 new signals for apu-s-club
INFO: Starting signal registration for turbo

Registering signals group 7/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for aethir
INFO: Starting signal registration for pendle
INFO: Registering 6 new signals for the-sandbox
INFO: Adapted windows for data length 499: [3, 6, 13, 20, 41, 62, 103]
INFO: Registering 6 new signals for turbo
INFO: Registering 6 new signals for aethir
INFO: Registering 6 new signals for pendle
INFO: Adapted windows for data length 408: [5, 11, 17, 34, 51, 85]
INFO: Asset apu-s-club: Using 7 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on apu-s-club: 499 points
INFO: Asset aethir: Using 6 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on aethir: 408 points
INFO: Asset turbo: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on turbo: 813 points
INFO: Calculated initial values for DonchianEnsembleBTC on aethir: 408 points
INFO: Calculated initial values for DonchianEnsembleBTC on apu-s-club: 499 points
INFO: Asset pendle: Using 9 windows with threshold 3
INFO: Calculated initial values for RSI_Bullish_USD on aethir: 408 points
INFO: Asset the-sandbox: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on pendle: 1549 points
INFO: Calculated initial values for RSI_Bullish_USD on apu-s-club: 499 points
INFO: Calculated initial values for RSI_Bullish_BTC on aethir: 408 points
INFO: Calculated initial values for DonchianEnsembleUSD on the-sandbox: 1806 points
INFO: Calculated initial values for RSI_Bullish_BTC on apu-s-club: 499 points
INFO: Calculated initial values for TrendMomentumUSD on aethir: 408 points
INFO: Calculated initial values for DonchianEnsembleBTC on turbo: 813 points
INFO: Calculated initial values for TrendMomentumUSD on apu-s-club: 499 points
INFO: Calculated initial values for TrendMomentumBTC on aethir: 408 points
INFO: Calculated initial values for TrendMomentumBTC on apu-s-club: 499 points
INFO: Completed signal registration for aethir in 6.19 seconds
INFO: Completed signal registration for apu-s-club in 6.45 seconds

Registering signals group 7/44:  40%|████      | 2/5 [00:06<00:08,  2.85s/it]

INFO: Calculated initial values for RSI_Bullish_USD on turbo: 813 points
INFO: Calculated initial values for RSI_Bullish_BTC on turbo: 813 points
INFO: Calculated initial values for TrendMomentumUSD on turbo: 813 points
INFO: Calculated initial values for TrendMomentumBTC on turbo: 813 points
INFO: Completed signal registration for turbo in 9.21 seconds

Registering signals group 7/44:  60%|██████    | 3/5 [00:09<00:05,  2.72s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on pendle: 1549 points
INFO: Calculated initial values for DonchianEnsembleBTC on the-sandbox: 1806 points
INFO: Calculated initial values for RSI_Bullish_USD on pendle: 1549 points
INFO: Calculated initial values for RSI_Bullish_BTC on pendle: 1549 points
INFO: Calculated initial values for TrendMomentumUSD on pendle: 1549 points
INFO: Calculated initial values for TrendMomentumBTC on pendle: 1549 points
INFO: Completed signal registration for pendle in 13.16 seconds

Registering signals group 7/44:  80%|████████  | 4/5 [00:13<00:03,  3.14s/it]

INFO: Calculated initial values for RSI_Bullish_USD on the-sandbox: 1806 points
INFO: Calculated initial values for RSI_Bullish_BTC on the-sandbox: 1806 points
INFO: Calculated initial values for TrendMomentumUSD on the-sandbox: 1806 points
INFO: Calculated initial values for TrendMomentumBTC on the-sandbox: 1806 points
INFO: Completed signal registration for the-sandbox in 13.84 seconds

Registering signals group 7/44: 100%|██████████| 5/5 [00:13<00:00,  2.77s/it]

INFO: Processing asset group 8/44 with 5 assets
INFO: Starting signal registration for crypto-com-chain

INFO: Starting signal registration for polymath

Registering signals group 8/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for equilibria-finance
INFO: Starting signal registration for gmx
INFO: Starting signal registration for zcash
INFO: Registering 6 new signals for crypto-com-chain
INFO: Registering 6 new signals for polymath
INFO: Registering 6 new signals for equilibria-finance
INFO: Registering 6 new signals for gmx
INFO: Registering 6 new signals for zcash
INFO: Asset equilibria-finance: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on equilibria-finance: 779 points
INFO: Asset gmx: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on gmx: 1411 points
INFO: Asset crypto-com-chain: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on crypto-com-chain: 2397 points
INFO: Calculated initial values for DonchianEnsembleBTC on equilibria-finance: 779 points
INFO: Asset polymath: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on polymath: 2723 points
INFO: Asset zcash: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on zcash: 3191 points
INFO: Calculated initial values for RSI_Bullish_USD on equilibria-finance: 779 points
INFO: Calculated initial values for RSI_Bullish_BTC on equilibria-finance: 779 points
INFO: Calculated initial values for TrendMomentumUSD on equilibria-finance: 779 points
INFO: Calculated initial values for TrendMomentumBTC on equilibria-finance: 779 points
INFO: Calculated initial values for DonchianEnsembleBTC on gmx: 1411 points
INFO: Completed signal registration for equilibria-finance in 13.11 seconds

Registering signals group 8/44:  20%|██        | 1/5 [00:13<00:53, 13.27s/it]

INFO: Calculated initial values for RSI_Bullish_USD on gmx: 1411 points
INFO: Calculated initial values for RSI_Bullish_BTC on gmx: 1411 points
INFO: Calculated initial values for TrendMomentumUSD on gmx: 1411 points
INFO: Calculated initial values for TrendMomentumBTC on gmx: 1411 points
INFO: Calculated initial values for DonchianEnsembleBTC on crypto-com-chain: 2397 points
INFO: Completed signal registration for gmx in 19.19 seconds

Registering signals group 8/44:  40%|████      | 2/5 [00:19<00:27,  9.13s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on polymath: 2723 points
INFO: Calculated initial values for DonchianEnsembleBTC on zcash: 3191 points
INFO: Calculated initial values for RSI_Bullish_USD on crypto-com-chain: 2397 points
INFO: Calculated initial values for RSI_Bullish_BTC on crypto-com-chain: 2397 points
INFO: Calculated initial values for TrendMomentumUSD on crypto-com-chain: 2397 points
INFO: Calculated initial values for RSI_Bullish_USD on polymath: 2723 points
INFO: Calculated initial values for TrendMomentumBTC on crypto-com-chain: 2397 points
INFO: Completed signal registration for crypto-com-chain in 27.23 seconds

Registering signals group 8/44:  60%|██████    | 3/5 [00:27<00:17,  8.56s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on polymath: 2723 points
INFO: Calculated initial values for TrendMomentumUSD on polymath: 2723 points
INFO: Calculated initial values for TrendMomentumBTC on polymath: 2723 points
INFO: Completed signal registration for polymath in 29.41 seconds

Registering signals group 8/44:  80%|████████  | 4/5 [00:29<00:06,  6.01s/it]

INFO: Calculated initial values for RSI_Bullish_USD on zcash: 3191 points
INFO: Calculated initial values for RSI_Bullish_BTC on zcash: 3191 points
INFO: Calculated initial values for TrendMomentumUSD on zcash: 3191 points
INFO: Calculated initial values for TrendMomentumBTC on zcash: 3191 points
INFO: Completed signal registration for zcash in 30.31 seconds

Registering signals group 8/44: 100%|██████████| 5/5 [00:30<00:00,  6.06s/it]

INFO: Processing asset group 9/44 with 5 assets
INFO: Starting signal registration for rainbow-token-2

INFO: Starting signal registration for aave

Registering signals group 9/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for wrapped-nxm
INFO: Starting signal registration for axelar
INFO: Starting signal registration for binancecoin
INFO: Registering 6 new signals for rainbow-token-2
INFO: Registering 6 new signals for aave
INFO: Registering 6 new signals for wrapped-nxm
INFO: Registering 6 new signals for axelar
INFO: Registering 6 new signals for binancecoin
INFO: Asset rainbow-token-2: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on rainbow-token-2: 1224 points
INFO: Asset axelar: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on axelar: 1032 points
INFO: Asset aave: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on aave: 1756 points
INFO: Asset wrapped-nxm: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on wrapped-nxm: 1824 points
INFO: Calculated initial values for DonchianEnsembleBTC on axelar: 1032 points
INFO: Asset binancecoin: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on binancecoin: 2869 points
INFO: Calculated initial values for DonchianEnsembleBTC on rainbow-token-2: 1224 points
INFO: Calculated initial values for RSI_Bullish_USD on axelar: 1032 points
INFO: Calculated initial values for RSI_Bullish_BTC on axelar: 1032 points
INFO: Calculated initial values for TrendMomentumUSD on axelar: 1032 points
INFO: Calculated initial values for TrendMomentumBTC on axelar: 1032 points
INFO: Calculated initial values for DonchianEnsembleBTC on aave: 1756 points
INFO: Completed signal registration for axelar in 14.11 seconds

Registering signals group 9/44:  20%|██        | 1/5 [00:14<00:57, 14.26s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on wrapped-nxm: 1824 points
ERROR: Error calculating RSI Bullish signal for rainbow-token-2: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
INFO: Calculated initial values for RSI_Bullish_USD on rainbow-token-2: 1224 points
INFO: Calculated initial values for RSI_Bullish_USD on aave: 1756 points
INFO: Calculated initial values for RSI_Bullish_BTC on aave: 1756 points
INFO: Calculated initial values for RSI_Bullish_USD on wrapped-nxm: 1824 points
INFO: Calculated initial values for TrendMomentumUSD on aave: 1756 points
INFO: Calculated initial values for RSI_Bullish_BTC on wrapped-nxm: 1824 points
INFO: Calculated initial values for RSI_Bullish_BTC on rainbow-token-2: 1224 points
INFO: Calculated initial values for TrendMomentumBTC on aave: 1756 points
INFO: Completed signal registration for aave in 19.23 seconds
INFO: Calculated initial values for TrendMomentumUSD on wrapped-nxm: 1824 points

Registering signals group 9/44:  40%|████      | 2/5 [00:19<00:26,  8.84s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on binancecoin: 2869 points
INFO: Calculated initial values for TrendMomentumBTC on wrapped-nxm: 1824 points
INFO: Completed signal registration for wrapped-nxm in 19.77 seconds

Registering signals group 9/44:  60%|██████    | 3/5 [00:19<00:10,  5.05s/it]

ERROR: Error calculating Trend Momentum signal for rainbow-token-2: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
INFO: Calculated initial values for TrendMomentumUSD on rainbow-token-2: 1224 points
INFO: Calculated initial values for TrendMomentumBTC on rainbow-token-2: 1224 points
INFO: Completed signal registration for rainbow-token-2 in 20.64 seconds

Registering signals group 9/44:  80%|████████  | 4/5 [00:20<00:03,  3.41s/it]

INFO: Calculated initial values for RSI_Bullish_USD on binancecoin: 2869 points
INFO: Calculated initial values for RSI_Bullish_BTC on binancecoin: 2869 points
INFO: Calculated initial values for TrendMomentumUSD on binancecoin: 2869 points
INFO: Calculated initial values for TrendMomentumBTC on binancecoin: 2869 points
INFO: Completed signal registration for binancecoin in 22.74 seconds

Registering signals group 9/44: 100%|██████████| 5/5 [00:22<00:00,  4.55s/it]

INFO: Processing asset group 10/44 with 5 assets
INFO: Starting signal registration for ethena
INFO: Starting signal registration for harrypotterobamasonic10in

INFO: Starting signal registration for sui

Registering signals group 10/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for prisma-governance-token
INFO: Registering 6 new signals for ethena
INFO: Starting signal registration for beam-2
INFO: Registering 6 new signals for harrypotterobamasonic10in
INFO: Registering 6 new signals for sui
INFO: Registering 6 new signals for prisma-governance-token
INFO: Adapted windows for data length 479: [3, 6, 13, 19, 39, 59, 99]
INFO: Registering 6 new signals for beam-2
INFO: Adapted windows for data length 631: [4, 8, 17, 26, 52, 78, 131]
INFO: Adapted windows for data length 638: [4, 8, 17, 26, 53, 79, 132]
INFO: Asset ethena: Using 7 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on ethena: 479 points
INFO: Asset sui: Using 9 windows with threshold 3
INFO: Asset harrypotterobamasonic10in: Using 9 windows with threshold 3
INFO: Asset prisma-governance-token: Using 7 windows with threshold 3
INFO: Asset beam-2: Using 7 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on sui: 814 points
INFO: Calculated initial values for DonchianEnsembleUSD on harrypotterobamasonic10in: 802 points
INFO: Calculated initial values for DonchianEnsembleUSD on prisma-governance-token: 631 points
INFO: Calculated initial values for DonchianEnsembleUSD on beam-2: 638 points
INFO: Calculated initial values for DonchianEnsembleBTC on ethena: 479 points
INFO: Calculated initial values for RSI_Bullish_USD on ethena: 479 points
INFO: Calculated initial values for RSI_Bullish_BTC on ethena: 479 points
INFO: Calculated initial values for TrendMomentumUSD on ethena: 479 points
INFO: Calculated initial values for DonchianEnsembleBTC on prisma-governance-token: 631 points
INFO: Calculated initial values for TrendMomentumBTC on ethena: 479 points
INFO: Calculated initial values for DonchianEnsembleBTC on beam-2: 638 points
INFO: Completed signal registration for ethena in 5.38 seconds

Registering signals group 10/44:  20%|██        | 1/5 [00:05<00:22,  5.62s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on harrypotterobamasonic10in: 802 points
INFO: Calculated initial values for DonchianEnsembleBTC on sui: 814 points
INFO: Calculated initial values for RSI_Bullish_USD on prisma-governance-token: 631 points
INFO: Calculated initial values for RSI_Bullish_USD on beam-2: 638 points
INFO: Calculated initial values for RSI_Bullish_BTC on prisma-governance-token: 631 points
INFO: Calculated initial values for RSI_Bullish_BTC on beam-2: 638 points
INFO: Calculated initial values for TrendMomentumUSD on prisma-governance-token: 631 points
INFO: Calculated initial values for RSI_Bullish_USD on harrypotterobamasonic10in: 802 points
INFO: Calculated initial values for TrendMomentumUSD on beam-2: 638 points
INFO: Calculated initial values for TrendMomentumBTC on prisma-governance-token: 631 points
INFO: Calculated initial values for RSI_Bullish_BTC on harrypotterobamasonic10in: 802 points
INFO: Calculated initial values for RSI_Bullish_USD on sui: 814 points
INFO: Calculated initial values for TrendMomentumBTC on beam-2: 638 points
INFO: Completed signal registration for prisma-governance-token in 7.73 seconds
INFO: Calculated initial values for TrendMomentumUSD on harrypotterobamasonic10in: 802 points

Registering signals group 10/44:  40%|████      | 2/5 [00:07<00:10,  3.63s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on sui: 814 points
INFO: Completed signal registration for beam-2 in 7.86 seconds
INFO: Calculated initial values for TrendMomentumBTC on harrypotterobamasonic10in: 802 points
INFO: Completed signal registration for harrypotterobamasonic10in in 8.00 seconds
INFO: Calculated initial values for TrendMomentumUSD on sui: 814 points

Registering signals group 10/44:  80%|████████  | 4/5 [00:08<00:01,  1.40s/it]

INFO: Calculated initial values for TrendMomentumBTC on sui: 814 points
INFO: Completed signal registration for sui in 8.10 seconds

Registering signals group 10/44: 100%|██████████| 5/5 [00:08<00:00,  1.62s/it]

INFO: Processing asset group 11/44 with 5 assets
INFO: Starting signal registration for rari-governance-token
INFO: Registering 6 new signals for rari-governance-token

INFO: Starting signal registration for zebec-network
INFO: Starting signal registration for dog-go-to-the-moon-rune

Registering signals group 11/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for cat-in-a-dogs-world
INFO: Starting signal registration for kamino
INFO: Registering 6 new signals for zebec-network
INFO: Registering 6 new signals for dog-go-to-the-moon-rune
INFO: Registering 6 new signals for cat-in-a-dogs-world
INFO: Registering 6 new signals for kamino
INFO: Adapted windows for data length 466: [3, 6, 12, 19, 38, 58, 97]
INFO: Adapted windows for data length 455: [3, 6, 12, 18, 37, 56, 94]
INFO: Adapted windows for data length 486: [3, 6, 13, 20, 40, 60, 101]
INFO: Adapted windows for data length 451: [3, 6, 12, 18, 37, 56, 93]
INFO: Asset zebec-network: Using 7 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on zebec-network: 466 points
INFO: Asset dog-go-to-the-moon-rune: Using 7 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on dog-go-to-the-moon-rune: 455 points
INFO: Asset cat-in-a-dogs-world: Using 7 windows with threshold 3
INFO: Asset kamino: Using 7 windows with threshold 3
INFO: Asset rari-governance-token: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on cat-in-a-dogs-world: 486 points
INFO: Calculated initial values for DonchianEnsembleUSD on kamino: 451 points
INFO: Calculated initial values for DonchianEnsembleUSD on rari-governance-token: 1741 points
INFO: Calculated initial values for DonchianEnsembleBTC on zebec-network: 466 points
INFO: Calculated initial values for DonchianEnsembleBTC on dog-go-to-the-moon-rune: 455 points
INFO: Calculated initial values for RSI_Bullish_USD on zebec-network: 466 points
INFO: Calculated initial values for RSI_Bullish_USD on dog-go-to-the-moon-rune: 455 points
INFO: Calculated initial values for RSI_Bullish_BTC on zebec-network: 466 points
INFO: Calculated initial values for DonchianEnsembleBTC on cat-in-a-dogs-world: 486 points
INFO: Calculated initial values for DonchianEnsembleBTC on kamino: 451 points
INFO: Calculated initial values for RSI_Bullish_BTC on dog-go-to-the-moon-rune: 455 points
INFO: Calculated initial values for TrendMomentumUSD on zebec-network: 466 points
INFO: Calculated initial values for TrendMomentumUSD on dog-go-to-the-moon-rune: 455 points
INFO: Calculated initial values for TrendMomentumBTC on zebec-network: 466 points
INFO: Calculated initial values for RSI_Bullish_USD on cat-in-a-dogs-world: 486 points
INFO: Calculated initial values for TrendMomentumBTC on dog-go-to-the-moon-rune: 455 points
INFO: Calculated initial values for RSI_Bullish_USD on kamino: 451 points
INFO: Completed signal registration for zebec-network in 5.29 seconds
INFO: Completed signal registration for dog-go-to-the-moon-rune in 5.42 seconds

Registering signals group 11/44:  20%|██        | 1/5 [00:05<00:22,  5.53s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on cat-in-a-dogs-world: 486 points
INFO: Calculated initial values for RSI_Bullish_BTC on kamino: 451 points
INFO: Calculated initial values for TrendMomentumUSD on cat-in-a-dogs-world: 486 points
INFO: Calculated initial values for TrendMomentumUSD on kamino: 451 points
INFO: Calculated initial values for TrendMomentumBTC on cat-in-a-dogs-world: 486 points
INFO: Calculated initial values for TrendMomentumBTC on kamino: 451 points
INFO: Completed signal registration for cat-in-a-dogs-world in 5.90 seconds
INFO: Completed signal registration for kamino in 5.91 seconds

Registering signals group 11/44:  60%|██████    | 3/5 [00:06<00:03,  1.66s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on rari-governance-token: 1741 points
ERROR: Error calculating RSI Bullish signal for rari-governance-token: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
INFO: Calculated initial values for RSI_Bullish_USD on rari-governance-token: 1741 points
INFO: Calculated initial values for RSI_Bullish_BTC on rari-governance-token: 1741 points
ERROR: Error calculating Trend Momentum signal for rari-governance-token: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
INFO: Calculated initial values for TrendMomentumUSD on rari-governance-token: 1741 points
INFO: Calculated initial values for TrendMomentumBTC on rari-governance-token: 1741 points
INFO: Completed signal registration for rari-governance-token in 8.23 seconds

Registering signals group 11/44: 100%|██████████| 5/5 [00:08<00:00,  1.62s/it]

INFO: Processing asset group 12/44 with 5 assets
INFO: Starting signal registration for dogecoin
INFO: Starting signal registration for aurory

Registering signals group 12/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for kekius-maximus
INFO: Registering 6 new signals for dogecoin
INFO: Starting signal registration for secret
INFO: Registering 6 new signals for secret
INFO: Registering 6 new signals for aurory
INFO: Registering 6 new signals for kekius-maximus
INFO: Starting signal registration for zeus-network
INFO: Adapted windows for data length 222: [3, 6, 9, 18, 27, 46]
INFO: Registering 6 new signals for zeus-network
INFO: Adapted windows for data length 476: [3, 6, 13, 19, 39, 59, 99]
INFO: Asset kekius-maximus: Using 6 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on kekius-maximus: 222 points
INFO: Asset zeus-network: Using 7 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleBTC on kekius-maximus: 222 points
INFO: Calculated initial values for DonchianEnsembleUSD on zeus-network: 476 points
INFO: Calculated initial values for RSI_Bullish_USD on kekius-maximus: 222 points
INFO: Calculated initial values for RSI_Bullish_BTC on kekius-maximus: 222 points
INFO: Calculated initial values for TrendMomentumUSD on kekius-maximus: 222 points
INFO: Asset aurory: Using 9 windows with threshold 3
INFO: Calculated initial values for TrendMomentumBTC on kekius-maximus: 222 points
INFO: Calculated initial values for DonchianEnsembleUSD on aurory: 1370 points
INFO: Completed signal registration for kekius-maximus in 4.35 seconds
INFO: Asset secret: Using 9 windows with threshold 3

Registering signals group 12/44:  20%|██        | 1/5 [00:04<00:18,  4.61s/it]

INFO: Calculated initial values for DonchianEnsembleUSD on secret: 1758 points
INFO: Calculated initial values for DonchianEnsembleBTC on zeus-network: 476 points
INFO: Calculated initial values for RSI_Bullish_USD on zeus-network: 476 points
INFO: Calculated initial values for RSI_Bullish_BTC on zeus-network: 476 points
INFO: Calculated initial values for TrendMomentumUSD on zeus-network: 476 points
INFO: Calculated initial values for TrendMomentumBTC on zeus-network: 476 points
INFO: Completed signal registration for zeus-network in 6.22 seconds

Registering signals group 12/44:  40%|████      | 2/5 [00:06<00:09,  3.30s/it]

INFO: Asset dogecoin: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on dogecoin: 4240 points
INFO: Calculated initial values for DonchianEnsembleBTC on aurory: 1370 points
INFO: Calculated initial values for DonchianEnsembleBTC on secret: 1758 points
INFO: Calculated initial values for RSI_Bullish_USD on aurory: 1370 points
INFO: Calculated initial values for RSI_Bullish_BTC on aurory: 1370 points
INFO: Calculated initial values for TrendMomentumUSD on aurory: 1370 points
INFO: Calculated initial values for TrendMomentumBTC on aurory: 1370 points
INFO: Completed signal registration for aurory in 13.68 seconds

Registering signals group 12/44:  60%|██████    | 3/5 [00:13<00:09,  4.85s/it]

INFO: Calculated initial values for RSI_Bullish_USD on secret: 1758 points
INFO: Calculated initial values for RSI_Bullish_BTC on secret: 1758 points
INFO: Calculated initial values for TrendMomentumUSD on secret: 1758 points
INFO: Calculated initial values for TrendMomentumBTC on secret: 1758 points
INFO: Completed signal registration for secret in 15.00 seconds

Registering signals group 12/44:  80%|████████  | 4/5 [00:15<00:03,  3.51s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on dogecoin: 4240 points
INFO: Calculated initial values for RSI_Bullish_USD on dogecoin: 4240 points
INFO: Calculated initial values for RSI_Bullish_BTC on dogecoin: 4240 points
INFO: Calculated initial values for TrendMomentumUSD on dogecoin: 4240 points
INFO: Calculated initial values for TrendMomentumBTC on dogecoin: 4240 points
INFO: Completed signal registration for dogecoin in 22.20 seconds

Registering signals group 12/44: 100%|██████████| 5/5 [00:22<00:00,  4.44s/it]

INFO: Processing asset group 13/44 with 5 assets
INFO: Starting signal registration for jasmycoin
INFO: Starting signal registration for kyber-network-crystal

INFO: Registering 6 new signals for kyber-network-crystal
INFO: Starting signal registration for ether-fi
INFO: Starting signal registration for helium

Registering signals group 13/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 6 new signals for jasmycoin
INFO: Starting signal registration for fantom
INFO: Registering 6 new signals for ether-fi
INFO: Registering 6 new signals for helium
INFO: Registering 6 new signals for fantom
INFO: Adapted windows for data length 494: [3, 6, 13, 20, 41, 61, 102]
INFO: Asset ether-fi: Using 7 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on ether-fi: 494 points
INFO: Asset kyber-network-crystal: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on kyber-network-crystal: 1555 points
INFO: Asset jasmycoin: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on jasmycoin: 1522 points
INFO: Calculated initial values for DonchianEnsembleBTC on ether-fi: 494 points
INFO: Calculated initial values for RSI_Bullish_USD on ether-fi: 494 points
INFO: Asset helium: Using 9 windows with threshold 3
INFO: Calculated initial values for RSI_Bullish_BTC on ether-fi: 494 points
INFO: Calculated initial values for DonchianEnsembleUSD on helium: 1925 points
INFO: Calculated initial values for TrendMomentumUSD on ether-fi: 494 points
INFO: Calculated initial values for TrendMomentumBTC on ether-fi: 494 points
INFO: Completed signal registration for ether-fi in 8.31 seconds

Registering signals group 13/44:  20%|██        | 1/5 [00:08<00:33,  8.42s/it]

INFO: Asset fantom: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on fantom: 2461 points
INFO: Calculated initial values for DonchianEnsembleBTC on kyber-network-crystal: 1555 points
INFO: Calculated initial values for DonchianEnsembleBTC on jasmycoin: 1522 points
INFO: Calculated initial values for RSI_Bullish_USD on kyber-network-crystal: 1555 points
INFO: Calculated initial values for DonchianEnsembleBTC on helium: 1925 points
INFO: Calculated initial values for RSI_Bullish_BTC on kyber-network-crystal: 1555 points
INFO: Calculated initial values for RSI_Bullish_USD on jasmycoin: 1522 points
INFO: Calculated initial values for TrendMomentumUSD on kyber-network-crystal: 1555 points
INFO: Calculated initial values for RSI_Bullish_BTC on jasmycoin: 1522 points
INFO: Calculated initial values for TrendMomentumBTC on kyber-network-crystal: 1555 points
INFO: Completed signal registration for kyber-network-crystal in 18.28 seconds

Registering signals group 13/44:  40%|████      | 2/5 [00:18<00:27,  9.25s/it]

INFO: Calculated initial values for TrendMomentumUSD on jasmycoin: 1522 points
INFO: Calculated initial values for TrendMomentumBTC on jasmycoin: 1522 points
INFO: Calculated initial values for DonchianEnsembleBTC on fantom: 2461 points
INFO: Completed signal registration for jasmycoin in 18.96 seconds
INFO: Calculated initial values for RSI_Bullish_USD on helium: 1925 points

Registering signals group 13/44:  60%|██████    | 3/5 [00:18<00:10,  5.35s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on helium: 1925 points
INFO: Calculated initial values for TrendMomentumUSD on helium: 1925 points
INFO: Calculated initial values for TrendMomentumBTC on helium: 1925 points
INFO: Completed signal registration for helium in 20.31 seconds

Registering signals group 13/44:  80%|████████  | 4/5 [00:20<00:03,  3.84s/it]

INFO: Calculated initial values for RSI_Bullish_USD on fantom: 2461 points
INFO: Calculated initial values for RSI_Bullish_BTC on fantom: 2461 points
INFO: Calculated initial values for TrendMomentumUSD on fantom: 2461 points
INFO: Calculated initial values for TrendMomentumBTC on fantom: 2461 points
INFO: Completed signal registration for fantom in 21.29 seconds

Registering signals group 13/44: 100%|██████████| 5/5 [00:21<00:00,  4.32s/it]

INFO: Processing asset group 14/44 with 5 assets
INFO: Starting signal registration for dash
INFO: Starting signal registration for pancakeswap-token
INFO: Registering 6 new signals for dash

INFO: Starting signal registration for alpha-finance
INFO: Starting signal registration for my-neighbor-alice

Registering signals group 14/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 6 new signals for pancakeswap-token
INFO: Starting signal registration for bubblemaps
INFO: Registering 6 new signals for alpha-finance
INFO: Registering 6 new signals for my-neighbor-alice
INFO: Registering 6 new signals for bubblemaps
INFO: Adapted windows for data length 136: [3, 5, 11, 17, 28]
INFO: Asset bubblemaps: Using 5 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on bubblemaps: 136 points
INFO: Calculated initial values for DonchianEnsembleBTC on bubblemaps: 136 points
INFO: Calculated initial values for RSI_Bullish_USD on bubblemaps: 136 points
INFO: Calculated initial values for RSI_Bullish_BTC on bubblemaps: 136 points
INFO: Calculated initial values for TrendMomentumUSD on bubblemaps: 136 points
INFO: Calculated initial values for TrendMomentumBTC on bubblemaps: 136 points
INFO: Completed signal registration for bubblemaps in 4.58 seconds
INFO: Asset pancakeswap-token: Using 9 windows with threshold 3

Registering signals group 14/44:  20%|██        | 1/5 [00:05<00:20,  5.02s/it]

INFO: Asset my-neighbor-alice: Using 9 windows with threshold 3
INFO: Asset alpha-finance: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on pancakeswap-token: 1760 points
INFO: Calculated initial values for DonchianEnsembleUSD on my-neighbor-alice: 1593 points
INFO: Calculated initial values for DonchianEnsembleUSD on alpha-finance: 1749 points
INFO: Asset dash: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on dash: 4179 points
INFO: Calculated initial values for DonchianEnsembleBTC on my-neighbor-alice: 1593 points
INFO: Calculated initial values for DonchianEnsembleBTC on pancakeswap-token: 1760 points
INFO: Calculated initial values for DonchianEnsembleBTC on alpha-finance: 1749 points
INFO: Calculated initial values for RSI_Bullish_USD on my-neighbor-alice: 1593 points
INFO: Calculated initial values for RSI_Bullish_USD on pancakeswap-token: 1760 points
INFO: Calculated initial values for RSI_Bullish_BTC on my-neighbor-alice: 1593 points
INFO: Calculated initial values for RSI_Bullish_USD on alpha-finance: 1749 points
INFO: Calculated initial values for RSI_Bullish_BTC on pancakeswap-token: 1760 points
INFO: Calculated initial values for TrendMomentumUSD on my-neighbor-alice: 1593 points
INFO: Calculated initial values for RSI_Bullish_BTC on alpha-finance: 1749 points
INFO: Calculated initial values for TrendMomentumBTC on my-neighbor-alice: 1593 points
INFO: Calculated initial values for TrendMomentumUSD on pancakeswap-token: 1760 points
INFO: Completed signal registration for my-neighbor-alice in 18.78 seconds
INFO: Calculated initial values for TrendMomentumUSD on alpha-finance: 1749 points

Registering signals group 14/44:  40%|████      | 2/5 [00:19<00:31, 10.34s/it]

INFO: Calculated initial values for TrendMomentumBTC on pancakeswap-token: 1760 points
INFO: Completed signal registration for pancakeswap-token in 19.58 seconds
INFO: Calculated initial values for TrendMomentumBTC on alpha-finance: 1749 points

Registering signals group 14/44:  60%|██████    | 3/5 [00:19<00:11,  5.84s/it]

INFO: Completed signal registration for alpha-finance in 19.87 seconds

Registering signals group 14/44:  80%|████████  | 4/5 [00:19<00:03,  3.67s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on dash: 4179 points
INFO: Calculated initial values for RSI_Bullish_USD on dash: 4179 points
INFO: Calculated initial values for RSI_Bullish_BTC on dash: 4179 points
INFO: Calculated initial values for TrendMomentumUSD on dash: 4179 points
INFO: Calculated initial values for TrendMomentumBTC on dash: 4179 points
INFO: Completed signal registration for dash in 26.44 seconds

Registering signals group 14/44: 100%|██████████| 5/5 [00:26<00:00,  5.27s/it]

INFO: Processing asset group 15/44 with 5 assets
INFO: Starting signal registration for flow
INFO: Starting signal registration for book-of-meme

INFO: Starting signal registration for balancer

Registering signals group 15/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 6 new signals for flow
INFO: Starting signal registration for render-token
INFO: Starting signal registration for pudgy-penguins
INFO: Registering 6 new signals for book-of-meme
INFO: Registering 6 new signals for balancer
INFO: Registering 6 new signals for render-token
INFO: Registering 6 new signals for pudgy-penguins
INFO: Adapted windows for data length 498: [3, 6, 13, 20, 41, 62, 103]
INFO: Adapted windows for data length 220: [3, 6, 9, 18, 27, 45]
INFO: Asset pudgy-penguins: Using 6 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on pudgy-penguins: 220 points
INFO: Asset book-of-meme: Using 7 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on book-of-meme: 498 points
INFO: Calculated initial values for DonchianEnsembleBTC on pudgy-penguins: 220 points
INFO: Calculated initial values for RSI_Bullish_USD on pudgy-penguins: 220 points
INFO: Asset flow: Using 9 windows with threshold 3
INFO: Calculated initial values for RSI_Bullish_BTC on pudgy-penguins: 220 points
INFO: Calculated initial values for DonchianEnsembleUSD on flow: 1640 points
INFO: Calculated initial values for TrendMomentumUSD on pudgy-penguins: 220 points
INFO: Calculated initial values for DonchianEnsembleBTC on book-of-meme: 498 points
INFO: Asset balancer: Using 9 windows with threshold 3
INFO: Calculated initial values for TrendMomentumBTC on pudgy-penguins: 220 points
INFO: Calculated initial values for DonchianEnsembleUSD on balancer: 1858 points
INFO: Asset render-token: Using 9 windows with threshold 3
INFO: Completed signal registration for pudgy-penguins in 4.64 seconds
INFO: Calculated initial values for DonchianEnsembleUSD on render-token: 1866 points

Registering signals group 15/44:  20%|██        | 1/5 [00:05<00:20,  5.18s/it]

INFO: Calculated initial values for RSI_Bullish_USD on book-of-meme: 498 points
INFO: Calculated initial values for RSI_Bullish_BTC on book-of-meme: 498 points
INFO: Calculated initial values for TrendMomentumUSD on book-of-meme: 498 points
INFO: Calculated initial values for TrendMomentumBTC on book-of-meme: 498 points
INFO: Completed signal registration for book-of-meme in 6.24 seconds

Registering signals group 15/44:  40%|████      | 2/5 [00:06<00:08,  2.85s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on flow: 1640 points
INFO: Calculated initial values for DonchianEnsembleBTC on balancer: 1858 points
INFO: Calculated initial values for DonchianEnsembleBTC on render-token: 1866 points
INFO: Calculated initial values for RSI_Bullish_USD on flow: 1640 points
INFO: Calculated initial values for RSI_Bullish_BTC on flow: 1640 points
INFO: Calculated initial values for TrendMomentumUSD on flow: 1640 points
INFO: Calculated initial values for RSI_Bullish_USD on balancer: 1858 points
INFO: Calculated initial values for TrendMomentumBTC on flow: 1640 points
INFO: Completed signal registration for flow in 14.07 seconds

Registering signals group 15/44:  60%|██████    | 3/5 [00:14<00:10,  5.05s/it]

INFO: Calculated initial values for RSI_Bullish_USD on render-token: 1866 points
INFO: Calculated initial values for RSI_Bullish_BTC on balancer: 1858 points
INFO: Calculated initial values for TrendMomentumUSD on balancer: 1858 points
INFO: Calculated initial values for RSI_Bullish_BTC on render-token: 1866 points
INFO: Calculated initial values for TrendMomentumBTC on balancer: 1858 points
INFO: Calculated initial values for TrendMomentumUSD on render-token: 1866 points
INFO: Completed signal registration for balancer in 14.83 seconds

Registering signals group 15/44:  80%|████████  | 4/5 [00:14<00:03,  3.36s/it]

INFO: Calculated initial values for TrendMomentumBTC on render-token: 1866 points
INFO: Completed signal registration for render-token in 14.90 seconds

Registering signals group 15/44: 100%|██████████| 5/5 [00:15<00:00,  3.00s/it]

INFO: Processing asset group 16/44 with 5 assets
INFO: Starting signal registration for vela-token

INFO: Starting signal registration for cosmos

Registering signals group 16/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for dydx
INFO: Starting signal registration for decentraland
INFO: Registering 6 new signals for vela-token
INFO: Starting signal registration for yield-guild-games
INFO: Registering 6 new signals for cosmos
INFO: Registering 6 new signals for dydx
INFO: Registering 6 new signals for decentraland
INFO: Registering 6 new signals for yield-guild-games
INFO: Asset vela-token: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on vela-token: 903 points
INFO: Asset dydx: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on dydx: 1416 points
INFO: Asset yield-guild-games: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on yield-guild-games: 1458 points
INFO: Asset cosmos: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on cosmos: 2345 points
INFO: Calculated initial values for DonchianEnsembleBTC on vela-token: 903 points
INFO: Asset decentraland: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on decentraland: 2827 points
INFO: Calculated initial values for DonchianEnsembleBTC on dydx: 1416 points
INFO: Calculated initial values for DonchianEnsembleBTC on yield-guild-games: 1458 points
ERROR: Error calculating RSI Bullish signal for vela-token: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
INFO: Calculated initial values for RSI_Bullish_USD on vela-token: 903 points
INFO: Calculated initial values for RSI_Bullish_USD on dydx: 1416 points
INFO: Calculated initial values for RSI_Bullish_BTC on dydx: 1416 points
INFO: Calculated initial values for RSI_Bullish_USD on yield-guild-games: 1458 points
INFO: Calculated initial values for TrendMomentumUSD on dydx: 1416 points
INFO: Calculated initial values for DonchianEnsembleBTC on cosmos: 2345 points
INFO: Calculated initial values for TrendMomentumBTC on dydx: 1416 points
INFO: Calculated initial values for RSI_Bullish_BTC on yield-guild-games: 1458 points
INFO: Completed signal registration for dydx in 16.82 seconds

Registering signals group 16/44:  20%|██        | 1/5 [00:17<01:08, 17.10s/it]

INFO: Calculated initial values for TrendMomentumUSD on yield-guild-games: 1458 points
INFO: Calculated initial values for TrendMomentumBTC on yield-guild-games: 1458 points
INFO: Completed signal registration for yield-guild-games in 18.14 seconds

Registering signals group 16/44:  40%|████      | 2/5 [00:18<00:23,  7.71s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on vela-token: 903 points
INFO: Calculated initial values for DonchianEnsembleBTC on decentraland: 2827 points
ERROR: Error calculating Trend Momentum signal for vela-token: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
INFO: Calculated initial values for TrendMomentumUSD on vela-token: 903 points
INFO: Calculated initial values for RSI_Bullish_USD on cosmos: 2345 points
INFO: Calculated initial values for RSI_Bullish_BTC on cosmos: 2345 points
INFO: Calculated initial values for TrendMomentumBTC on vela-token: 903 points
INFO: Calculated initial values for TrendMomentumUSD on cosmos: 2345 points
INFO: Completed signal registration for vela-token in 20.95 seconds

Registering signals group 16/44:  60%|██████    | 3/5 [00:21<00:10,  5.48s/it]

INFO: Calculated initial values for TrendMomentumBTC on cosmos: 2345 points
INFO: Completed signal registration for cosmos in 21.47 seconds

Registering signals group 16/44:  80%|████████  | 4/5 [00:21<00:03,  3.50s/it]

INFO: Calculated initial values for RSI_Bullish_USD on decentraland: 2827 points
INFO: Calculated initial values for RSI_Bullish_BTC on decentraland: 2827 points
INFO: Calculated initial values for TrendMomentumUSD on decentraland: 2827 points
INFO: Calculated initial values for TrendMomentumBTC on decentraland: 2827 points
INFO: Completed signal registration for decentraland in 22.45 seconds

Registering signals group 16/44: 100%|██████████| 5/5 [00:22<00:00,  4.49s/it]

INFO: Processing asset group 17/44 with 5 assets

INFO: Starting signal registration for anzen-finance
INFO: Starting signal registration for ava-ai

Registering signals group 17/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for terra-luna-2
INFO: Starting signal registration for chill-guy
INFO: Starting signal registration for tron
INFO: Registering 6 new signals for anzen-finance
INFO: Registering 6 new signals for ava-ai
INFO: Registering 6 new signals for terra-luna-2
INFO: Registering 6 new signals for chill-guy
INFO: Registering 6 new signals for tron
INFO: Adapted windows for data length 228: [3, 6, 9, 19, 28, 47]
INFO: Adapted windows for data length 246: [3, 6, 10, 20, 30, 51]
INFO: Asset chill-guy: Using 6 windows with threshold 3
INFO: Asset anzen-finance: Using 6 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on chill-guy: 249 points
INFO: Asset ava-ai: Using 6 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on anzen-finance: 228 points
INFO: Calculated initial values for DonchianEnsembleUSD on ava-ai: 246 points
INFO: Calculated initial values for DonchianEnsembleBTC on chill-guy: 249 points
INFO: Calculated initial values for DonchianEnsembleBTC on anzen-finance: 228 points
INFO: Asset terra-luna-2: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on terra-luna-2: 1154 points
INFO: Calculated initial values for DonchianEnsembleBTC on ava-ai: 246 points
INFO: Calculated initial values for RSI_Bullish_USD on chill-guy: 249 points
INFO: Calculated initial values for RSI_Bullish_USD on anzen-finance: 228 points
INFO: Calculated initial values for RSI_Bullish_BTC on chill-guy: 249 points
INFO: Calculated initial values for RSI_Bullish_USD on ava-ai: 246 points
INFO: Calculated initial values for RSI_Bullish_BTC on anzen-finance: 228 points
INFO: Calculated initial values for TrendMomentumUSD on chill-guy: 249 points
INFO: Calculated initial values for RSI_Bullish_BTC on ava-ai: 246 points
INFO: Calculated initial values for TrendMomentumUSD on anzen-finance: 228 points
INFO: Calculated initial values for TrendMomentumBTC on chill-guy: 249 points
INFO: Calculated initial values for TrendMomentumUSD on ava-ai: 246 points
INFO: Calculated initial values for TrendMomentumBTC on anzen-finance: 228 points
INFO: Completed signal registration for chill-guy in 4.04 seconds
INFO: Calculated initial values for TrendMomentumBTC on ava-ai: 246 points

Registering signals group 17/44:  20%|██        | 1/5 [00:04<00:17,  4.38s/it]

INFO: Completed signal registration for anzen-finance in 4.27 seconds
INFO: Completed signal registration for ava-ai in 4.56 seconds

Registering signals group 17/44:  40%|████      | 2/5 [00:04<00:06,  2.02s/it]

INFO: Asset tron: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on tron: 2815 points
INFO: Calculated initial values for DonchianEnsembleBTC on terra-luna-2: 1154 points
INFO: Calculated initial values for RSI_Bullish_USD on terra-luna-2: 1154 points
INFO: Calculated initial values for RSI_Bullish_BTC on terra-luna-2: 1154 points
INFO: Calculated initial values for TrendMomentumUSD on terra-luna-2: 1154 points
INFO: Calculated initial values for TrendMomentumBTC on terra-luna-2: 1154 points
INFO: Completed signal registration for terra-luna-2 in 7.95 seconds

Registering signals group 17/44:  80%|████████  | 4/5 [00:07<00:01,  1.77s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on tron: 2815 points
INFO: Calculated initial values for RSI_Bullish_USD on tron: 2815 points
INFO: Calculated initial values for RSI_Bullish_BTC on tron: 2815 points
INFO: Calculated initial values for TrendMomentumUSD on tron: 2815 points
INFO: Calculated initial values for TrendMomentumBTC on tron: 2815 points
INFO: Completed signal registration for tron in 12.25 seconds

Registering signals group 17/44: 100%|██████████| 5/5 [00:12<00:00,  2.45s/it]

INFO: Processing asset group 18/44 with 5 assets
INFO: Starting signal registration for grass

INFO: Starting signal registration for worldcoin-wld

Registering signals group 18/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for bertram-the-pomeranian
INFO: Registering 6 new signals for grass
INFO: Starting signal registration for bitcoin-cash
INFO: Starting signal registration for polkadot
INFO: Registering 6 new signals for worldcoin-wld
INFO: Registering 6 new signals for bertram-the-pomeranian
INFO: Adapted windows for data length 270: [3, 7, 11, 22, 33, 56]
INFO: Registering 6 new signals for bitcoin-cash
INFO: Registering 6 new signals for polkadot
INFO: Adapted windows for data length 255: [3, 7, 10, 21, 31, 53]
INFO: Asset grass: Using 6 windows with threshold 3
INFO: Asset worldcoin-wld: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on grass: 270 points
INFO: Asset bertram-the-pomeranian: Using 6 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on worldcoin-wld: 732 points
INFO: Calculated initial values for DonchianEnsembleUSD on bertram-the-pomeranian: 255 points
INFO: Calculated initial values for DonchianEnsembleBTC on grass: 270 points
INFO: Calculated initial values for RSI_Bullish_USD on grass: 270 points
INFO: Calculated initial values for RSI_Bullish_BTC on grass: 270 points
INFO: Calculated initial values for DonchianEnsembleBTC on bertram-the-pomeranian: 255 points
INFO: Calculated initial values for TrendMomentumUSD on grass: 270 points
INFO: Calculated initial values for TrendMomentumBTC on grass: 270 points
INFO: Calculated initial values for RSI_Bullish_USD on bertram-the-pomeranian: 255 points
INFO: Completed signal registration for grass in 3.45 seconds
INFO: Calculated initial values for RSI_Bullish_BTC on bertram-the-pomeranian: 255 points

Registering signals group 18/44:  20%|██        | 1/5 [00:03<00:14,  3.69s/it]

INFO: Asset polkadot: Using 9 windows with threshold 3
INFO: Calculated initial values for TrendMomentumUSD on bertram-the-pomeranian: 255 points
INFO: Calculated initial values for DonchianEnsembleBTC on worldcoin-wld: 732 points
INFO: Calculated initial values for DonchianEnsembleUSD on polkadot: 1801 points
INFO: Calculated initial values for TrendMomentumBTC on bertram-the-pomeranian: 255 points
INFO: Completed signal registration for bertram-the-pomeranian in 4.51 seconds

Registering signals group 18/44:  40%|████      | 2/5 [00:04<00:06,  2.09s/it]

INFO: Asset bitcoin-cash: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on bitcoin-cash: 2914 points
INFO: Calculated initial values for RSI_Bullish_USD on worldcoin-wld: 732 points
INFO: Calculated initial values for RSI_Bullish_BTC on worldcoin-wld: 732 points
INFO: Calculated initial values for TrendMomentumUSD on worldcoin-wld: 732 points
INFO: Calculated initial values for TrendMomentumBTC on worldcoin-wld: 732 points
INFO: Completed signal registration for worldcoin-wld in 6.01 seconds

Registering signals group 18/44:  60%|██████    | 3/5 [00:06<00:03,  1.81s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on polkadot: 1801 points
INFO: Calculated initial values for RSI_Bullish_USD on polkadot: 1801 points
INFO: Calculated initial values for RSI_Bullish_BTC on polkadot: 1801 points
INFO: Calculated initial values for DonchianEnsembleBTC on bitcoin-cash: 2914 points
INFO: Calculated initial values for TrendMomentumUSD on polkadot: 1801 points
INFO: Calculated initial values for TrendMomentumBTC on polkadot: 1801 points
INFO: Completed signal registration for polkadot in 12.18 seconds

Registering signals group 18/44:  80%|████████  | 4/5 [00:12<00:03,  3.51s/it]

INFO: Calculated initial values for RSI_Bullish_USD on bitcoin-cash: 2914 points
INFO: Calculated initial values for RSI_Bullish_BTC on bitcoin-cash: 2914 points
INFO: Calculated initial values for TrendMomentumUSD on bitcoin-cash: 2914 points
INFO: Calculated initial values for TrendMomentumBTC on bitcoin-cash: 2914 points
INFO: Completed signal registration for bitcoin-cash in 15.48 seconds

Registering signals group 18/44: 100%|██████████| 5/5 [00:15<00:00,  3.10s/it]

INFO: Processing asset group 19/44 with 5 assets
INFO: Starting signal registration for lisk
INFO: Registering 6 new signals for lisk

INFO: Starting signal registration for serum
INFO: Starting signal registration for spx6900

Registering signals group 19/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for aioz-network
INFO: Starting signal registration for chainlink
INFO: Registering 6 new signals for serum
INFO: Registering 6 new signals for spx6900
INFO: Registering 6 new signals for aioz-network
INFO: Registering 6 new signals for chainlink
INFO: Adapted windows for data length 697: [4, 9, 19, 29, 58, 87, 145]
INFO: Asset spx6900: Using 7 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on spx6900: 697 points
INFO: Asset aioz-network: Using 9 windows with threshold 3
INFO: Asset serum: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on aioz-network: 1574 points
INFO: Calculated initial values for DonchianEnsembleUSD on serum: 1809 points
INFO: Calculated initial values for DonchianEnsembleBTC on spx6900: 697 points
INFO: Asset lisk: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on lisk: 3397 points
INFO: Calculated initial values for RSI_Bullish_USD on spx6900: 697 points
INFO: Calculated initial values for RSI_Bullish_BTC on spx6900: 697 points
INFO: Asset chainlink: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on chainlink: 2815 points
INFO: Calculated initial values for TrendMomentumUSD on spx6900: 697 points
INFO: Calculated initial values for TrendMomentumBTC on spx6900: 697 points
INFO: Completed signal registration for spx6900 in 10.53 seconds

Registering signals group 19/44:  20%|██        | 1/5 [00:10<00:43, 10.83s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on aioz-network: 1574 points
INFO: Calculated initial values for DonchianEnsembleBTC on serum: 1809 points
INFO: Calculated initial values for RSI_Bullish_USD on aioz-network: 1574 points
INFO: Calculated initial values for RSI_Bullish_BTC on aioz-network: 1574 points
INFO: Calculated initial values for TrendMomentumUSD on aioz-network: 1574 points
INFO: Calculated initial values for RSI_Bullish_USD on serum: 1809 points
INFO: Calculated initial values for TrendMomentumBTC on aioz-network: 1574 points
INFO: Completed signal registration for aioz-network in 19.64 seconds

Registering signals group 19/44:  40%|████      | 2/5 [00:19<00:29,  9.76s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on serum: 1809 points
INFO: Calculated initial values for TrendMomentumUSD on serum: 1809 points
INFO: Calculated initial values for DonchianEnsembleBTC on chainlink: 2815 points
INFO: Calculated initial values for TrendMomentumBTC on serum: 1809 points
INFO: Completed signal registration for serum in 22.07 seconds

Registering signals group 19/44:  60%|██████    | 3/5 [00:22<00:12,  6.35s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on lisk: 3397 points
INFO: Calculated initial values for RSI_Bullish_USD on chainlink: 2815 points
INFO: Calculated initial values for RSI_Bullish_BTC on chainlink: 2815 points
INFO: Calculated initial values for TrendMomentumUSD on chainlink: 2815 points
INFO: Calculated initial values for RSI_Bullish_USD on lisk: 3397 points
INFO: Calculated initial values for TrendMomentumBTC on chainlink: 2815 points
INFO: Completed signal registration for chainlink in 26.29 seconds
INFO: Calculated initial values for RSI_Bullish_BTC on lisk: 3397 points

Registering signals group 19/44:  80%|████████  | 4/5 [00:26<00:05,  5.56s/it]

INFO: Calculated initial values for TrendMomentumUSD on lisk: 3397 points
INFO: Calculated initial values for TrendMomentumBTC on lisk: 3397 points
INFO: Completed signal registration for lisk in 27.39 seconds

Registering signals group 19/44: 100%|██████████| 5/5 [00:27<00:00,  5.43s/it]

INFO: Processing asset group 20/44 with 5 assets
INFO: Starting signal registration for lofi-2

INFO: Starting signal registration for arweave
INFO: Starting signal registration for mamo

Registering signals group 20/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for nunet
INFO: Registering 6 new signals for lofi-2
INFO: Starting signal registration for lido-dao
INFO: Registering 6 new signals for arweave
INFO: Registering 6 new signals for mamo
INFO: Registering 6 new signals for nunet
INFO: Adapted windows for data length 243: [3, 6, 10, 20, 30, 50]
INFO: Registering 6 new signals for lido-dao
INFO: Adapted windows for data length 65: [5, 8, 13]
INFO: Asset lofi-2: Using 6 windows with threshold 3
INFO: Asset mamo: Using 3 windows with threshold 2
INFO: Calculated initial values for DonchianEnsembleUSD on lofi-2: 243 points
INFO: Calculated initial values for DonchianEnsembleUSD on mamo: 65 points
INFO: Calculated initial values for DonchianEnsembleBTC on mamo: 65 points
INFO: Calculated initial values for RSI_Bullish_USD on mamo: 65 points
INFO: Calculated initial values for DonchianEnsembleBTC on lofi-2: 243 points
INFO: Calculated initial values for RSI_Bullish_BTC on mamo: 65 points
INFO: Calculated initial values for TrendMomentumUSD on mamo: 65 points
INFO: Calculated initial values for TrendMomentumBTC on mamo: 65 points
INFO: Calculated initial values for RSI_Bullish_USD on lofi-2: 243 points
INFO: Completed signal registration for mamo in 2.83 seconds
INFO: Asset nunet: Using 9 windows with threshold 3

Registering signals group 20/44:  20%|██        | 1/5 [00:03<00:13,  3.31s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on lofi-2: 243 points
INFO: Calculated initial values for DonchianEnsembleUSD on nunet: 1335 points
INFO: Calculated initial values for TrendMomentumUSD on lofi-2: 243 points
INFO: Asset lido-dao: Using 9 windows with threshold 3
INFO: Calculated initial values for TrendMomentumBTC on lofi-2: 243 points
INFO: Asset arweave: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on lido-dao: 1662 points
INFO: Calculated initial values for DonchianEnsembleUSD on arweave: 2094 points
INFO: Completed signal registration for lofi-2 in 4.20 seconds

Registering signals group 20/44:  40%|████      | 2/5 [00:04<00:06,  2.10s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on nunet: 1335 points
INFO: Calculated initial values for DonchianEnsembleBTC on lido-dao: 1662 points
INFO: Calculated initial values for RSI_Bullish_USD on nunet: 1335 points
INFO: Calculated initial values for DonchianEnsembleBTC on arweave: 2094 points
INFO: Calculated initial values for RSI_Bullish_BTC on nunet: 1335 points
INFO: Calculated initial values for TrendMomentumUSD on nunet: 1335 points
INFO: Calculated initial values for TrendMomentumBTC on nunet: 1335 points
INFO: Completed signal registration for nunet in 13.94 seconds
INFO: Calculated initial values for RSI_Bullish_USD on lido-dao: 1662 points

Registering signals group 20/44:  60%|██████    | 3/5 [00:14<00:10,  5.48s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on lido-dao: 1662 points
INFO: Calculated initial values for TrendMomentumUSD on lido-dao: 1662 points
INFO: Calculated initial values for RSI_Bullish_USD on arweave: 2094 points
INFO: Calculated initial values for TrendMomentumBTC on lido-dao: 1662 points
INFO: Completed signal registration for lido-dao in 15.52 seconds

Registering signals group 20/44:  80%|████████  | 4/5 [00:15<00:03,  3.91s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on arweave: 2094 points
INFO: Calculated initial values for TrendMomentumUSD on arweave: 2094 points
INFO: Calculated initial values for TrendMomentumBTC on arweave: 2094 points
INFO: Completed signal registration for arweave in 16.12 seconds

Registering signals group 20/44: 100%|██████████| 5/5 [00:16<00:00,  3.22s/it]

INFO: Processing asset group 21/44 with 5 assets
INFO: Starting signal registration for genesysgo-shadow

INFO: Starting signal registration for cookie
INFO: Starting signal registration for bittensor

Registering signals group 21/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for baby-doge-coin
INFO: Starting signal registration for badger-dao
INFO: Registering 6 new signals for genesysgo-shadow
INFO: Registering 6 new signals for cookie
INFO: Registering 6 new signals for bittensor
INFO: Registering 6 new signals for baby-doge-coin
INFO: Registering 6 new signals for badger-dao
INFO: Adapted windows for data length 407: [5, 11, 16, 33, 50, 84]
INFO: Asset cookie: Using 6 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on cookie: 407 points
INFO: Asset bittensor: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on bittensor: 875 points
INFO: Asset genesysgo-shadow: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleBTC on cookie: 407 points
INFO: Calculated initial values for DonchianEnsembleUSD on genesysgo-shadow: 1297 points
INFO: Asset baby-doge-coin: Using 9 windows with threshold 3
INFO: Calculated initial values for RSI_Bullish_USD on cookie: 407 points
INFO: Calculated initial values for DonchianEnsembleUSD on baby-doge-coin: 1507 points
INFO: Calculated initial values for RSI_Bullish_BTC on cookie: 407 points
INFO: Asset badger-dao: Using 9 windows with threshold 3
INFO: Calculated initial values for TrendMomentumUSD on cookie: 407 points
INFO: Calculated initial values for DonchianEnsembleUSD on badger-dao: 1694 points
INFO: Calculated initial values for TrendMomentumBTC on cookie: 407 points
INFO: Completed signal registration for cookie in 5.21 seconds

Registering signals group 21/44:  20%|██        | 1/5 [00:05<00:21,  5.36s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on bittensor: 875 points
INFO: Calculated initial values for RSI_Bullish_USD on bittensor: 875 points
INFO: Calculated initial values for DonchianEnsembleBTC on genesysgo-shadow: 1297 points
INFO: Calculated initial values for RSI_Bullish_BTC on bittensor: 875 points
INFO: Calculated initial values for TrendMomentumUSD on bittensor: 875 points
INFO: Calculated initial values for TrendMomentumBTC on bittensor: 875 points
INFO: Completed signal registration for bittensor in 10.08 seconds
INFO: Calculated initial values for DonchianEnsembleBTC on baby-doge-coin: 1507 points

Registering signals group 21/44:  40%|████      | 2/5 [00:10<00:15,  5.13s/it]

INFO: Calculated initial values for RSI_Bullish_USD on genesysgo-shadow: 1297 points
INFO: Calculated initial values for DonchianEnsembleBTC on badger-dao: 1694 points
INFO: Calculated initial values for RSI_Bullish_BTC on genesysgo-shadow: 1297 points
INFO: Calculated initial values for TrendMomentumUSD on genesysgo-shadow: 1297 points
INFO: Calculated initial values for TrendMomentumBTC on genesysgo-shadow: 1297 points
INFO: Calculated initial values for RSI_Bullish_USD on baby-doge-coin: 1507 points
INFO: Completed signal registration for genesysgo-shadow in 14.15 seconds

Registering signals group 21/44:  60%|██████    | 3/5 [00:14<00:09,  4.60s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on baby-doge-coin: 1507 points
INFO: Calculated initial values for RSI_Bullish_USD on badger-dao: 1694 points
INFO: Calculated initial values for TrendMomentumUSD on baby-doge-coin: 1507 points
INFO: Calculated initial values for TrendMomentumBTC on baby-doge-coin: 1507 points
INFO: Calculated initial values for RSI_Bullish_BTC on badger-dao: 1694 points
INFO: Completed signal registration for baby-doge-coin in 15.09 seconds

Registering signals group 21/44:  80%|████████  | 4/5 [00:15<00:03,  3.10s/it]

INFO: Calculated initial values for TrendMomentumUSD on badger-dao: 1694 points
INFO: Calculated initial values for TrendMomentumBTC on badger-dao: 1694 points
INFO: Completed signal registration for badger-dao in 15.68 seconds

Registering signals group 21/44: 100%|██████████| 5/5 [00:15<00:00,  3.14s/it]

INFO: Processing asset group 22/44 with 5 assets
INFO: Starting signal registration for siren-2
INFO: Starting signal registration for kryptonite

INFO: Starting signal registration for pepe
INFO: Registering 6 new signals for siren-2

Registering signals group 22/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for eigenlayer
INFO: Starting signal registration for thorchain
INFO: Registering 6 new signals for kryptonite
INFO: Registering 6 new signals for pepe
INFO: Adapted windows for data length 156: [4, 6, 13, 19, 32]
INFO: Registering 6 new signals for eigenlayer
INFO: Registering 6 new signals for thorchain
INFO: Adapted windows for data length 711: [4, 9, 19, 29, 59, 88, 148]
INFO: Asset siren-2: Using 5 windows with threshold 3
INFO: Adapted windows for data length 297: [4, 8, 12, 24, 37, 61]
INFO: Calculated initial values for DonchianEnsembleUSD on siren-2: 156 points
INFO: Asset eigenlayer: Using 6 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleBTC on siren-2: 156 points
INFO: Calculated initial values for DonchianEnsembleUSD on eigenlayer: 297 points
INFO: Asset pepe: Using 9 windows with threshold 3
INFO: Calculated initial values for RSI_Bullish_USD on siren-2: 156 points
INFO: Asset kryptonite: Using 7 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on pepe: 829 points
INFO: Calculated initial values for RSI_Bullish_BTC on siren-2: 156 points
INFO: Calculated initial values for DonchianEnsembleUSD on kryptonite: 711 points
INFO: Calculated initial values for DonchianEnsembleBTC on eigenlayer: 297 points
INFO: Calculated initial values for TrendMomentumUSD on siren-2: 156 points
INFO: Calculated initial values for TrendMomentumBTC on siren-2: 156 points
INFO: Completed signal registration for siren-2 in 4.71 seconds
INFO: Calculated initial values for RSI_Bullish_USD on eigenlayer: 297 points

Registering signals group 22/44:  20%|██        | 1/5 [00:05<00:20,  5.02s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on eigenlayer: 297 points
INFO: Calculated initial values for TrendMomentumUSD on eigenlayer: 297 points
INFO: Calculated initial values for TrendMomentumBTC on eigenlayer: 297 points
INFO: Completed signal registration for eigenlayer in 5.80 seconds

Registering signals group 22/44:  40%|████      | 2/5 [00:05<00:07,  2.62s/it]

INFO: Asset thorchain: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleBTC on kryptonite: 711 points
INFO: Calculated initial values for DonchianEnsembleUSD on thorchain: 2197 points
INFO: Calculated initial values for DonchianEnsembleBTC on pepe: 829 points
INFO: Calculated initial values for RSI_Bullish_USD on kryptonite: 711 points
INFO: Calculated initial values for RSI_Bullish_BTC on kryptonite: 711 points
INFO: Calculated initial values for RSI_Bullish_USD on pepe: 829 points
INFO: Calculated initial values for TrendMomentumUSD on kryptonite: 711 points
INFO: Calculated initial values for TrendMomentumBTC on kryptonite: 711 points
INFO: Calculated initial values for RSI_Bullish_BTC on pepe: 829 points
INFO: Completed signal registration for kryptonite in 8.29 seconds
INFO: Calculated initial values for TrendMomentumUSD on pepe: 829 points

Registering signals group 22/44:  60%|██████    | 3/5 [00:08<00:05,  2.58s/it]

INFO: Calculated initial values for TrendMomentumBTC on pepe: 829 points
INFO: Completed signal registration for pepe in 8.80 seconds

Registering signals group 22/44:  80%|████████  | 4/5 [00:08<00:01,  1.69s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on thorchain: 2197 points
INFO: Calculated initial values for RSI_Bullish_USD on thorchain: 2197 points
INFO: Calculated initial values for RSI_Bullish_BTC on thorchain: 2197 points
INFO: Calculated initial values for TrendMomentumUSD on thorchain: 2197 points
INFO: Calculated initial values for TrendMomentumBTC on thorchain: 2197 points
INFO: Completed signal registration for thorchain in 12.23 seconds

Registering signals group 22/44: 100%|██████████| 5/5 [00:12<00:00,  2.45s/it]

INFO: Processing asset group 23/44 with 5 assets
INFO: Starting signal registration for conic-finance
INFO: Starting signal registration for compound-governance-token
INFO: Registering 6 new signals for conic-finance
INFO: Starting signal registration for raydium

Registering signals group 23/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for immutable-x
INFO: Starting signal registration for the-open-network
INFO: Registering 6 new signals for compound-governance-token
INFO: Registering 6 new signals for raydium
INFO: Registering 6 new signals for immutable-x
INFO: Registering 6 new signals for the-open-network
INFO: Asset conic-finance: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on conic-finance: 1012 points
INFO: Asset immutable-x: Using 9 windows with threshold 3
INFO: Asset the-open-network: Using 9 windows with threshold 3
INFO: Asset raydium: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on immutable-x: 1358 points
INFO: Calculated initial values for DonchianEnsembleUSD on the-open-network: 1428 points
INFO: Asset compound-governance-token: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on raydium: 1615 points
INFO: Calculated initial values for DonchianEnsembleUSD on compound-governance-token: 1865 points
INFO: Calculated initial values for DonchianEnsembleBTC on conic-finance: 1012 points
INFO: Calculated initial values for DonchianEnsembleBTC on immutable-x: 1358 points
INFO: Calculated initial values for DonchianEnsembleBTC on the-open-network: 1428 points
INFO: Calculated initial values for DonchianEnsembleBTC on raydium: 1615 points
ERROR: Error calculating RSI Bullish signal for conic-finance: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
INFO: Calculated initial values for RSI_Bullish_USD on conic-finance: 1012 points
INFO: Calculated initial values for RSI_Bullish_USD on immutable-x: 1358 points
INFO: Calculated initial values for DonchianEnsembleBTC on compound-governance-token: 1865 points
INFO: Calculated initial values for RSI_Bullish_BTC on immutable-x: 1358 points
INFO: Calculated initial values for RSI_Bullish_USD on the-open-network: 1428 points
INFO: Calculated initial values for TrendMomentumUSD on immutable-x: 1358 points
INFO: Calculated initial values for TrendMomentumBTC on immutable-x: 1358 points
INFO: Calculated initial values for RSI_Bullish_BTC on the-open-network: 1428 points
INFO: Calculated initial values for RSI_Bullish_USD on raydium: 1615 points
INFO: Completed signal registration for immutable-x in 17.90 seconds

Registering signals group 23/44:  20%|██        | 1/5 [00:18<01:12, 18.10s/it]

INFO: Calculated initial values for TrendMomentumUSD on the-open-network: 1428 points
INFO: Calculated initial values for RSI_Bullish_BTC on raydium: 1615 points
INFO: Calculated initial values for TrendMomentumBTC on the-open-network: 1428 points
INFO: Calculated initial values for TrendMomentumUSD on raydium: 1615 points
INFO: Calculated initial values for RSI_Bullish_BTC on conic-finance: 1012 points
INFO: Calculated initial values for RSI_Bullish_USD on compound-governance-token: 1865 points
INFO: Completed signal registration for the-open-network in 19.38 seconds

Registering signals group 23/44:  40%|████      | 2/5 [00:19<00:25,  8.40s/it]

INFO: Calculated initial values for TrendMomentumBTC on raydium: 1615 points
INFO: Completed signal registration for raydium in 20.20 seconds

Registering signals group 23/44:  60%|██████    | 3/5 [00:20<00:09,  4.81s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on compound-governance-token: 1865 points
INFO: Calculated initial values for TrendMomentumUSD on compound-governance-token: 1865 points
ERROR: Error calculating Trend Momentum signal for conic-finance: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
INFO: Calculated initial values for TrendMomentumUSD on conic-finance: 1012 points
INFO: Calculated initial values for TrendMomentumBTC on compound-governance-token: 1865 points
INFO: Calculated initial values for TrendMomentumBTC on conic-finance: 1012 points
INFO: Completed signal registration for compound-governance-token in 21.11 seconds
INFO: Completed signal registration for conic-finance in 21.13 seconds

Registering signals group 23/44: 100%|██████████| 5/5 [00:21<00:00,  4.21s/it]

INFO: Processing asset group 24/44 with 5 assets
INFO: Starting signal registration for metacade
INFO: Starting signal registration for clearpool
INFO: Starting signal registration for prometeus

Registering signals group 24/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for wibx
INFO: Registering 6 new signals for metacade
INFO: Starting signal registration for sei-network
INFO: Registering 6 new signals for clearpool
INFO: Registering 6 new signals for prometeus
INFO: Registering 6 new signals for wibx
INFO: Registering 6 new signals for sei-network
INFO: Adapted windows for data length 710: [4, 9, 19, 29, 59, 88, 147]
INFO: Asset metacade: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on metacade: 836 points
INFO: Asset sei-network: Using 7 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on sei-network: 710 points
INFO: Asset clearpool: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on clearpool: 1366 points
INFO: Calculated initial values for DonchianEnsembleBTC on sei-network: 710 points
INFO: Asset wibx: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on wibx: 1925 points
INFO: Asset prometeus: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleBTC on metacade: 836 points
INFO: Calculated initial values for DonchianEnsembleUSD on prometeus: 2219 points
INFO: Calculated initial values for RSI_Bullish_USD on sei-network: 710 points
INFO: Calculated initial values for RSI_Bullish_BTC on sei-network: 710 points
INFO: Calculated initial values for TrendMomentumUSD on sei-network: 710 points
INFO: Calculated initial values for RSI_Bullish_USD on metacade: 836 points
INFO: Calculated initial values for TrendMomentumBTC on sei-network: 710 points
INFO: Completed signal registration for sei-network in 12.34 seconds
INFO: Calculated initial values for RSI_Bullish_BTC on metacade: 836 points

Registering signals group 24/44:  20%|██        | 1/5 [00:12<00:50, 12.72s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on clearpool: 1366 points
INFO: Calculated initial values for TrendMomentumUSD on metacade: 836 points
INFO: Calculated initial values for TrendMomentumBTC on metacade: 836 points
INFO: Completed signal registration for metacade in 14.37 seconds

Registering signals group 24/44:  40%|████      | 2/5 [00:14<00:19,  6.38s/it]

INFO: Calculated initial values for RSI_Bullish_USD on clearpool: 1366 points
INFO: Calculated initial values for RSI_Bullish_BTC on clearpool: 1366 points
INFO: Calculated initial values for DonchianEnsembleBTC on wibx: 1925 points
INFO: Calculated initial values for TrendMomentumUSD on clearpool: 1366 points
INFO: Calculated initial values for TrendMomentumBTC on clearpool: 1366 points
INFO: Completed signal registration for clearpool in 18.17 seconds
INFO: Calculated initial values for DonchianEnsembleBTC on prometeus: 2219 points

Registering signals group 24/44:  60%|██████    | 3/5 [00:18<00:10,  5.12s/it]

INFO: Calculated initial values for RSI_Bullish_USD on wibx: 1925 points
INFO: Calculated initial values for RSI_Bullish_BTC on wibx: 1925 points
INFO: Calculated initial values for TrendMomentumUSD on wibx: 1925 points
INFO: Calculated initial values for RSI_Bullish_USD on prometeus: 2219 points
INFO: Calculated initial values for TrendMomentumBTC on wibx: 1925 points
INFO: Completed signal registration for wibx in 21.58 seconds

Registering signals group 24/44:  80%|████████  | 4/5 [00:21<00:04,  4.41s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on prometeus: 2219 points
INFO: Calculated initial values for TrendMomentumUSD on prometeus: 2219 points
INFO: Calculated initial values for TrendMomentumBTC on prometeus: 2219 points
INFO: Completed signal registration for prometeus in 22.64 seconds

Registering signals group 24/44: 100%|██████████| 5/5 [00:22<00:00,  4.53s/it]

INFO: Processing asset group 25/44 with 5 assets
INFO: Starting signal registration for guild-of-guardians
INFO: Starting signal registration for sturdy
INFO: Registering 6 new signals for guild-of-guardians
INFO: Starting signal registration for tether

Registering signals group 25/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for echelon-prime
INFO: Starting signal registration for usd-coin
INFO: Registering 6 new signals for sturdy
INFO: Registering 6 new signals for tether
INFO: Registering 6 new signals for echelon-prime
INFO: Registering 6 new signals for usd-coin
INFO: Adapted windows for data length 519: [3, 7, 14, 21, 43, 64, 108]
INFO: Asset sturdy: Using 7 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on sturdy: 519 points
INFO: Asset guild-of-guardians: Using 9 windows with threshold 3
INFO: Asset echelon-prime: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on guild-of-guardians: 1311 points
INFO: Calculated initial values for DonchianEnsembleUSD on echelon-prime: 876 points
INFO: Calculated initial values for DonchianEnsembleBTC on sturdy: 519 points
INFO: Calculated initial values for RSI_Bullish_USD on sturdy: 519 points
INFO: Calculated initial values for RSI_Bullish_BTC on sturdy: 519 points
INFO: Asset usd-coin: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleBTC on echelon-prime: 876 points
INFO: Calculated initial values for DonchianEnsembleUSD on usd-coin: 2486 points
INFO: Calculated initial values for TrendMomentumUSD on sturdy: 519 points
INFO: Calculated initial values for TrendMomentumBTC on sturdy: 519 points
INFO: Completed signal registration for sturdy in 12.57 seconds

Registering signals group 25/44:  20%|██        | 1/5 [00:12<00:50, 12.71s/it]

INFO: Calculated initial values for RSI_Bullish_USD on echelon-prime: 876 points
INFO: Calculated initial values for DonchianEnsembleBTC on guild-of-guardians: 1311 points
INFO: Calculated initial values for RSI_Bullish_BTC on echelon-prime: 876 points
INFO: Asset tether: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on tether: 3803 points
INFO: Calculated initial values for TrendMomentumUSD on echelon-prime: 876 points
INFO: Calculated initial values for TrendMomentumBTC on echelon-prime: 876 points
INFO: Completed signal registration for echelon-prime in 21.30 seconds

Registering signals group 25/44:  40%|████      | 2/5 [00:21<00:31, 10.43s/it]

INFO: Calculated initial values for RSI_Bullish_USD on guild-of-guardians: 1311 points
INFO: Calculated initial values for RSI_Bullish_BTC on guild-of-guardians: 1311 points
INFO: Calculated initial values for TrendMomentumUSD on guild-of-guardians: 1311 points
INFO: Calculated initial values for TrendMomentumBTC on guild-of-guardians: 1311 points
INFO: Completed signal registration for guild-of-guardians in 26.05 seconds

Registering signals group 25/44:  60%|██████    | 3/5 [00:26<00:15,  7.75s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on usd-coin: 2486 points
INFO: Calculated initial values for RSI_Bullish_USD on usd-coin: 2486 points
INFO: Calculated initial values for RSI_Bullish_BTC on usd-coin: 2486 points
INFO: Calculated initial values for DonchianEnsembleBTC on tether: 3803 points
INFO: Calculated initial values for TrendMomentumUSD on usd-coin: 2486 points
INFO: Calculated initial values for TrendMomentumBTC on usd-coin: 2486 points
INFO: Completed signal registration for usd-coin in 34.32 seconds

Registering signals group 25/44:  80%|████████  | 4/5 [00:34<00:08,  8.01s/it]

INFO: Calculated initial values for RSI_Bullish_USD on tether: 3803 points
INFO: Calculated initial values for RSI_Bullish_BTC on tether: 3803 points
INFO: Calculated initial values for TrendMomentumUSD on tether: 3803 points
INFO: Calculated initial values for TrendMomentumBTC on tether: 3803 points
INFO: Completed signal registration for tether in 37.76 seconds

Registering signals group 25/44: 100%|██████████| 5/5 [00:37<00:00,  7.55s/it]

INFO: Processing asset group 26/44 with 5 assets
INFO: Starting signal registration for arpa
INFO: Registering 6 new signals for arpa
INFO: Starting signal registration for celestia

INFO: Starting signal registration for spell-token

Registering signals group 26/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for ai16z
INFO: Starting signal registration for arbitrum
INFO: Registering 6 new signals for celestia
INFO: Registering 6 new signals for spell-token
INFO: Registering 6 new signals for ai16z
INFO: Registering 6 new signals for arbitrum
INFO: Adapted windows for data length 633: [4, 8, 17, 26, 52, 79, 131]
INFO: Adapted windows for data length 271: [3, 7, 11, 22, 33, 56]
INFO: Asset ai16z: Using 6 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on ai16z: 271 points
INFO: Asset celestia: Using 7 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on celestia: 633 points
INFO: Calculated initial values for DonchianEnsembleBTC on ai16z: 271 points
INFO: Asset arbitrum: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on arbitrum: 855 points
INFO: Calculated initial values for RSI_Bullish_USD on ai16z: 271 points
INFO: Calculated initial values for RSI_Bullish_BTC on ai16z: 271 points
INFO: Calculated initial values for TrendMomentumUSD on ai16z: 271 points
INFO: Calculated initial values for TrendMomentumBTC on ai16z: 271 points
INFO: Completed signal registration for ai16z in 5.52 seconds
INFO: Asset spell-token: Using 9 windows with threshold 3

Registering signals group 26/44:  20%|██        | 1/5 [00:05<00:22,  5.73s/it]

INFO: Calculated initial values for DonchianEnsembleUSD on spell-token: 1519 points
INFO: Asset arpa: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleBTC on celestia: 633 points
INFO: Calculated initial values for DonchianEnsembleUSD on arpa: 2250 points
INFO: Calculated initial values for DonchianEnsembleBTC on arbitrum: 855 points
INFO: Calculated initial values for RSI_Bullish_USD on celestia: 633 points
INFO: Calculated initial values for RSI_Bullish_BTC on celestia: 633 points
INFO: Calculated initial values for TrendMomentumUSD on celestia: 633 points
INFO: Calculated initial values for TrendMomentumBTC on celestia: 633 points
INFO: Completed signal registration for celestia in 10.95 seconds

Registering signals group 26/44:  40%|████      | 2/5 [00:10<00:16,  5.44s/it]

INFO: Calculated initial values for RSI_Bullish_USD on arbitrum: 855 points
INFO: Calculated initial values for RSI_Bullish_BTC on arbitrum: 855 points
INFO: Calculated initial values for TrendMomentumUSD on arbitrum: 855 points
INFO: Calculated initial values for TrendMomentumBTC on arbitrum: 855 points
INFO: Completed signal registration for arbitrum in 12.31 seconds

Registering signals group 26/44:  60%|██████    | 3/5 [00:12<00:07,  3.68s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on spell-token: 1519 points
INFO: Calculated initial values for RSI_Bullish_USD on spell-token: 1519 points
INFO: Calculated initial values for DonchianEnsembleBTC on arpa: 2250 points
INFO: Calculated initial values for RSI_Bullish_BTC on spell-token: 1519 points
INFO: Calculated initial values for TrendMomentumUSD on spell-token: 1519 points
INFO: Calculated initial values for TrendMomentumBTC on spell-token: 1519 points
INFO: Completed signal registration for spell-token in 15.95 seconds

Registering signals group 26/44:  80%|████████  | 4/5 [00:15<00:03,  3.57s/it]

INFO: Calculated initial values for RSI_Bullish_USD on arpa: 2250 points
INFO: Calculated initial values for RSI_Bullish_BTC on arpa: 2250 points
INFO: Calculated initial values for TrendMomentumUSD on arpa: 2250 points
INFO: Calculated initial values for TrendMomentumBTC on arpa: 2250 points
INFO: Completed signal registration for arpa in 17.33 seconds

Registering signals group 26/44: 100%|██████████| 5/5 [00:17<00:00,  3.42s/it]

INFO: Processing asset group 27/44 with 5 assets
INFO: Starting signal registration for deep
INFO: Starting signal registration for power-ledger
INFO: Registering 6 new signals for deep
INFO: Starting signal registration for tribe-2

Registering signals group 27/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for virtual-protocol
INFO: Starting signal registration for smartcash
INFO: Registering 6 new signals for power-ledger
INFO: Adapted windows for data length 284: [3, 7, 11, 23, 35, 59]
INFO: Registering 6 new signals for tribe-2
INFO: Registering 6 new signals for virtual-protocol
INFO: Registering 6 new signals for smartcash
INFO: Asset deep: Using 6 windows with threshold 3
INFO: Adapted windows for data length 575: [3, 7, 15, 23, 47, 71, 119]
INFO: Calculated initial values for DonchianEnsembleUSD on deep: 284 points
INFO: Asset virtual-protocol: Using 7 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleBTC on deep: 284 points
INFO: Calculated initial values for DonchianEnsembleUSD on virtual-protocol: 575 points
INFO: Calculated initial values for RSI_Bullish_USD on deep: 284 points
INFO: Calculated initial values for RSI_Bullish_BTC on deep: 284 points
INFO: Asset tribe-2: Using 9 windows with threshold 3
INFO: Calculated initial values for TrendMomentumUSD on deep: 284 points
INFO: Calculated initial values for DonchianEnsembleUSD on tribe-2: 1574 points
INFO: Calculated initial values for TrendMomentumBTC on deep: 284 points
INFO: Completed signal registration for deep in 5.08 seconds

Registering signals group 27/44:  20%|██        | 1/5 [00:05<00:20,  5.24s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on virtual-protocol: 575 points
INFO: Asset power-ledger: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on power-ledger: 2816 points
INFO: Calculated initial values for RSI_Bullish_USD on virtual-protocol: 575 points
INFO: Asset smartcash: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on smartcash: 2877 points
INFO: Calculated initial values for RSI_Bullish_BTC on virtual-protocol: 575 points
INFO: Calculated initial values for TrendMomentumUSD on virtual-protocol: 575 points
INFO: Calculated initial values for TrendMomentumBTC on virtual-protocol: 575 points
INFO: Completed signal registration for virtual-protocol in 9.39 seconds

Registering signals group 27/44:  40%|████      | 2/5 [00:09<00:14,  4.72s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on tribe-2: 1574 points
INFO: Calculated initial values for RSI_Bullish_USD on tribe-2: 1574 points
INFO: Calculated initial values for RSI_Bullish_BTC on tribe-2: 1574 points
INFO: Calculated initial values for TrendMomentumUSD on tribe-2: 1574 points
INFO: Calculated initial values for TrendMomentumBTC on tribe-2: 1574 points
INFO: Completed signal registration for tribe-2 in 16.31 seconds

Registering signals group 27/44:  60%|██████    | 3/5 [00:16<00:11,  5.70s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on power-ledger: 2816 points
INFO: Calculated initial values for DonchianEnsembleBTC on smartcash: 2877 points
INFO: Calculated initial values for RSI_Bullish_USD on power-ledger: 2816 points
ERROR: Error calculating RSI Bullish signal for smartcash: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
INFO: Calculated initial values for RSI_Bullish_USD on smartcash: 2877 points
INFO: Calculated initial values for RSI_Bullish_BTC on power-ledger: 2816 points
INFO: Calculated initial values for TrendMomentumUSD on power-ledger: 2816 points
INFO: Calculated initial values for RSI_Bullish_BTC on smartcash: 2877 points
INFO: Calculated initial values for TrendMomentumBTC on power-ledger: 2816 points
INFO: Completed signal registration for power-ledger in 21.88 seconds

Registering signals group 27/44:  80%|████████  | 4/5 [00:21<00:05,  5.59s/it]

ERROR: Error calculating Trend Momentum signal for smartcash: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
INFO: Calculated initial values for TrendMomentumUSD on smartcash: 2877 points
INFO: Calculated initial values for TrendMomentumBTC on smartcash: 2877 points
INFO: Completed signal registration for smartcash in 22.36 seconds

Registering signals group 27/44: 100%|██████████| 5/5 [00:22<00:00,  4.47s/it]

INFO: Processing asset group 28/44 with 5 assets
INFO: Starting signal registration for tokenbot-2
INFO: Starting signal registration for ethervista

INFO: Registering 6 new signals for tokenbot-2

Registering signals group 28/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for kujira
INFO: Starting signal registration for orbit-3
INFO: Starting signal registration for ethereum
INFO: Registering 6 new signals for ethervista
INFO: Adapted windows for data length 257: [3, 7, 10, 21, 32, 53]
INFO: Registering 6 new signals for kujira
INFO: Registering 6 new signals for orbit-3
INFO: Registering 6 new signals for ethereum
INFO: Adapted windows for data length 327: [4, 9, 13, 27, 40, 68]
INFO: Adapted windows for data length 229: [3, 6, 9, 19, 28, 47]
INFO: Asset tokenbot-2: Using 6 windows with threshold 3
INFO: Asset ethervista: Using 6 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on tokenbot-2: 257 points
INFO: Asset orbit-3: Using 6 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on ethervista: 327 points
INFO: Calculated initial values for DonchianEnsembleUSD on orbit-3: 229 points
INFO: Asset kujira: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleBTC on tokenbot-2: 257 points
INFO: Calculated initial values for DonchianEnsembleUSD on kujira: 1337 points
INFO: Calculated initial values for DonchianEnsembleBTC on orbit-3: 229 points
INFO: Calculated initial values for RSI_Bullish_USD on tokenbot-2: 257 points
INFO: Calculated initial values for DonchianEnsembleBTC on ethervista: 327 points
INFO: Calculated initial values for RSI_Bullish_BTC on tokenbot-2: 257 points
INFO: Calculated initial values for RSI_Bullish_USD on orbit-3: 229 points
INFO: Calculated initial values for TrendMomentumUSD on tokenbot-2: 257 points
INFO: Calculated initial values for RSI_Bullish_BTC on orbit-3: 229 points
INFO: Calculated initial values for RSI_Bullish_USD on ethervista: 327 points
INFO: Calculated initial values for TrendMomentumBTC on tokenbot-2: 257 points
INFO: Calculated initial values for TrendMomentumUSD on orbit-3: 229 points
INFO: Calculated initial values for RSI_Bullish_BTC on ethervista: 327 points
INFO: Completed signal registration for tokenbot-2 in 3.86 seconds

Registering signals group 28/44:  20%|██        | 1/5 [00:04<00:17,  4.25s/it]

INFO: Calculated initial values for TrendMomentumBTC on orbit-3: 229 points
INFO: Calculated initial values for TrendMomentumUSD on ethervista: 327 points
INFO: Completed signal registration for orbit-3 in 4.41 seconds

Registering signals group 28/44:  40%|████      | 2/5 [00:04<00:06,  2.01s/it]

INFO: Calculated initial values for TrendMomentumBTC on ethervista: 327 points
INFO: Completed signal registration for ethervista in 4.84 seconds

Registering signals group 28/44:  60%|██████    | 3/5 [00:05<00:02,  1.24s/it]

INFO: Asset ethereum: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on ethereum: 3640 points
INFO: Calculated initial values for DonchianEnsembleBTC on kujira: 1337 points
INFO: Calculated initial values for RSI_Bullish_USD on kujira: 1337 points
INFO: Calculated initial values for RSI_Bullish_BTC on kujira: 1337 points
INFO: Calculated initial values for TrendMomentumUSD on kujira: 1337 points
INFO: Calculated initial values for TrendMomentumBTC on kujira: 1337 points
INFO: Completed signal registration for kujira in 8.24 seconds

Registering signals group 28/44:  80%|████████  | 4/5 [00:08<00:02,  2.05s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on ethereum: 3640 points
INFO: Calculated initial values for RSI_Bullish_USD on ethereum: 3640 points
INFO: Calculated initial values for RSI_Bullish_BTC on ethereum: 3640 points
INFO: Calculated initial values for TrendMomentumUSD on ethereum: 3640 points
INFO: Calculated initial values for TrendMomentumBTC on ethereum: 3640 points
INFO: Completed signal registration for ethereum in 14.61 seconds

Registering signals group 28/44: 100%|██████████| 5/5 [00:14<00:00,  2.92s/it]

INFO: Processing asset group 29/44 with 5 assets
INFO: Starting signal registration for griffain

INFO: Starting signal registration for kaspa

Registering signals group 29/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for new-xai-gork
INFO: Starting signal registration for audius
INFO: Starting signal registration for arkham
INFO: Registering 6 new signals for griffain
INFO: Registering 6 new signals for kaspa
INFO: Registering 6 new signals for new-xai-gork
INFO: Registering 6 new signals for audius
INFO: Registering 6 new signals for arkham
INFO: Adapted windows for data length 231: [3, 6, 9, 19, 28, 48]
INFO: Adapted windows for data length 84: [3, 7, 10, 17]
INFO: Asset new-xai-gork: Using 4 windows with threshold 3
INFO: Asset griffain: Using 6 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on new-xai-gork: 84 points
INFO: Calculated initial values for DonchianEnsembleUSD on griffain: 231 points
INFO: Calculated initial values for DonchianEnsembleBTC on new-xai-gork: 84 points
INFO: Asset arkham: Using 9 windows with threshold 3
INFO: Calculated initial values for RSI_Bullish_USD on new-xai-gork: 84 points
INFO: Calculated initial values for DonchianEnsembleBTC on griffain: 231 points
INFO: Calculated initial values for DonchianEnsembleUSD on arkham: 738 points
INFO: Calculated initial values for RSI_Bullish_BTC on new-xai-gork: 84 points
INFO: Asset kaspa: Using 9 windows with threshold 3
INFO: Calculated initial values for TrendMomentumUSD on new-xai-gork: 84 points
INFO: Calculated initial values for RSI_Bullish_USD on griffain: 231 points
INFO: Calculated initial values for DonchianEnsembleUSD on kaspa: 1157 points
INFO: Calculated initial values for TrendMomentumBTC on new-xai-gork: 84 points
INFO: Calculated initial values for RSI_Bullish_BTC on griffain: 231 points
INFO: Completed signal registration for new-xai-gork in 3.57 seconds
INFO: Asset audius: Using 9 windows with threshold 3

Registering signals group 29/44:  20%|██        | 1/5 [00:03<00:15,  3.77s/it]

INFO: Calculated initial values for TrendMomentumUSD on griffain: 231 points
INFO: Calculated initial values for DonchianEnsembleUSD on audius: 1736 points
INFO: Calculated initial values for TrendMomentumBTC on griffain: 231 points
INFO: Completed signal registration for griffain in 4.48 seconds

Registering signals group 29/44:  40%|████      | 2/5 [00:04<00:06,  2.07s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on arkham: 738 points
INFO: Calculated initial values for RSI_Bullish_USD on arkham: 738 points
INFO: Calculated initial values for RSI_Bullish_BTC on arkham: 738 points
INFO: Calculated initial values for DonchianEnsembleBTC on kaspa: 1157 points
INFO: Calculated initial values for TrendMomentumUSD on arkham: 738 points
INFO: Calculated initial values for TrendMomentumBTC on arkham: 738 points
INFO: Completed signal registration for arkham in 8.20 seconds

Registering signals group 29/44:  60%|██████    | 3/5 [00:08<00:05,  2.81s/it]

INFO: Calculated initial values for RSI_Bullish_USD on kaspa: 1157 points
INFO: Calculated initial values for RSI_Bullish_BTC on kaspa: 1157 points
INFO: Calculated initial values for TrendMomentumUSD on kaspa: 1157 points
INFO: Calculated initial values for DonchianEnsembleBTC on audius: 1736 points
INFO: Calculated initial values for TrendMomentumBTC on kaspa: 1157 points
INFO: Completed signal registration for kaspa in 9.71 seconds

Registering signals group 29/44:  80%|████████  | 4/5 [00:09<00:02,  2.25s/it]

INFO: Calculated initial values for RSI_Bullish_USD on audius: 1736 points
INFO: Calculated initial values for RSI_Bullish_BTC on audius: 1736 points
INFO: Calculated initial values for TrendMomentumUSD on audius: 1736 points
INFO: Calculated initial values for TrendMomentumBTC on audius: 1736 points
INFO: Completed signal registration for audius in 11.04 seconds

Registering signals group 29/44: 100%|██████████| 5/5 [00:11<00:00,  2.21s/it]

INFO: Processing asset group 30/44 with 5 assets
INFO: Starting signal registration for useless-3
INFO: Starting signal registration for blockstack

Registering signals group 30/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for yne
INFO: Starting signal registration for evan-2
INFO: Registering 6 new signals for useless-3
INFO: Starting signal registration for botto
INFO: Registering 6 new signals for blockstack
INFO: Registering 6 new signals for yne
INFO: Registering 6 new signals for evan-2
INFO: Adapted windows for data length 75: [3, 6, 9, 15]
INFO: Registering 6 new signals for botto
INFO: Adapted windows for data length 214: [5, 8, 17, 26, 44]
INFO: Adapted windows for data length 245: [3, 6, 10, 20, 30, 51]
INFO: Asset useless-3: Using 4 windows with threshold 3
INFO: Asset yne: Using 5 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on useless-3: 75 points
INFO: Asset evan-2: Using 6 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on yne: 214 points
INFO: Calculated initial values for DonchianEnsembleBTC on useless-3: 75 points
INFO: Calculated initial values for DonchianEnsembleUSD on evan-2: 245 points
INFO: Calculated initial values for RSI_Bullish_USD on useless-3: 75 points
INFO: Calculated initial values for DonchianEnsembleBTC on yne: 214 points
INFO: Calculated initial values for RSI_Bullish_BTC on useless-3: 75 points
INFO: Calculated initial values for TrendMomentumUSD on useless-3: 75 points
INFO: Calculated initial values for RSI_Bullish_USD on yne: 214 points
INFO: Calculated initial values for TrendMomentumBTC on useless-3: 75 points
INFO: Calculated initial values for DonchianEnsembleBTC on evan-2: 245 points
INFO: Calculated initial values for RSI_Bullish_BTC on yne: 214 points
INFO: Completed signal registration for useless-3 in 3.01 seconds

Registering signals group 30/44:  20%|██        | 1/5 [00:03<00:13,  3.41s/it]

INFO: Asset botto: Using 9 windows with threshold 3
INFO: Calculated initial values for TrendMomentumUSD on yne: 214 points
INFO: Calculated initial values for DonchianEnsembleUSD on botto: 1385 points
INFO: Calculated initial values for RSI_Bullish_USD on evan-2: 245 points
INFO: Asset blockstack: Using 9 windows with threshold 3
INFO: Calculated initial values for TrendMomentumBTC on yne: 214 points
INFO: Calculated initial values for RSI_Bullish_BTC on evan-2: 245 points
INFO: Calculated initial values for DonchianEnsembleUSD on blockstack: 2101 points
INFO: Completed signal registration for yne in 3.66 seconds
INFO: Calculated initial values for TrendMomentumUSD on evan-2: 245 points

Registering signals group 30/44:  40%|████      | 2/5 [00:03<00:05,  1.70s/it]

INFO: Calculated initial values for TrendMomentumBTC on evan-2: 245 points
INFO: Completed signal registration for evan-2 in 4.28 seconds

Registering signals group 30/44:  60%|██████    | 3/5 [00:04<00:02,  1.14s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on botto: 1385 points
INFO: Calculated initial values for RSI_Bullish_USD on botto: 1385 points
INFO: Calculated initial values for RSI_Bullish_BTC on botto: 1385 points
INFO: Calculated initial values for DonchianEnsembleBTC on blockstack: 2101 points
INFO: Calculated initial values for TrendMomentumUSD on botto: 1385 points
INFO: Calculated initial values for TrendMomentumBTC on botto: 1385 points
INFO: Completed signal registration for botto in 10.31 seconds

Registering signals group 30/44:  80%|████████  | 4/5 [00:10<00:03,  3.05s/it]

INFO: Calculated initial values for RSI_Bullish_USD on blockstack: 2101 points
INFO: Calculated initial values for RSI_Bullish_BTC on blockstack: 2101 points
INFO: Calculated initial values for TrendMomentumUSD on blockstack: 2101 points
INFO: Calculated initial values for TrendMomentumBTC on blockstack: 2101 points
INFO: Completed signal registration for blockstack in 11.82 seconds

Registering signals group 30/44: 100%|██████████| 5/5 [00:11<00:00,  2.36s/it]

INFO: Processing asset group 31/44 with 5 assets
INFO: Starting signal registration for maker
INFO: Registering 6 new signals for maker
INFO: Starting signal registration for instadapp
INFO: Starting signal registration for venice-token
INFO: Starting signal registration for sushi

Registering signals group 31/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for akash-network
INFO: Registering 6 new signals for instadapp
INFO: Registering 6 new signals for venice-token
INFO: Registering 6 new signals for sushi
INFO: Registering 6 new signals for akash-network
INFO: Adapted windows for data length 179: [4, 7, 14, 22, 37]
INFO: Asset venice-token: Using 5 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on venice-token: 179 points
INFO: Calculated initial values for DonchianEnsembleBTC on venice-token: 179 points
INFO: Calculated initial values for RSI_Bullish_USD on venice-token: 179 points
INFO: Calculated initial values for RSI_Bullish_BTC on venice-token: 179 points
INFO: Calculated initial values for TrendMomentumUSD on venice-token: 179 points
INFO: Calculated initial values for TrendMomentumBTC on venice-token: 179 points
INFO: Completed signal registration for venice-token in 4.71 seconds

Registering signals group 31/44:  20%|██        | 1/5 [00:04<00:19,  4.86s/it]

INFO: Asset instadapp: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on instadapp: 1500 points
INFO: Asset sushi: Using 9 windows with threshold 3
INFO: Asset akash-network: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on sushi: 1792 points
INFO: Calculated initial values for DonchianEnsembleUSD on akash-network: 1743 points
INFO: Asset maker: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on maker: 2774 points
INFO: Calculated initial values for DonchianEnsembleBTC on instadapp: 1500 points
INFO: Calculated initial values for DonchianEnsembleBTC on akash-network: 1743 points
INFO: Calculated initial values for DonchianEnsembleBTC on sushi: 1792 points
INFO: Calculated initial values for RSI_Bullish_USD on instadapp: 1500 points
INFO: Calculated initial values for RSI_Bullish_BTC on instadapp: 1500 points
INFO: Calculated initial values for TrendMomentumUSD on instadapp: 1500 points
INFO: Calculated initial values for TrendMomentumBTC on instadapp: 1500 points
INFO: Completed signal registration for instadapp in 21.83 seconds

Registering signals group 31/44:  40%|████      | 2/5 [00:21<00:36, 12.01s/it]

INFO: Calculated initial values for RSI_Bullish_USD on akash-network: 1743 points
INFO: Calculated initial values for RSI_Bullish_USD on sushi: 1792 points
INFO: Calculated initial values for RSI_Bullish_BTC on akash-network: 1743 points
INFO: Calculated initial values for DonchianEnsembleBTC on maker: 2774 points
INFO: Calculated initial values for RSI_Bullish_BTC on sushi: 1792 points
INFO: Calculated initial values for TrendMomentumUSD on sushi: 1792 points
INFO: Calculated initial values for TrendMomentumUSD on akash-network: 1743 points
INFO: Calculated initial values for TrendMomentumBTC on akash-network: 1743 points
INFO: Calculated initial values for TrendMomentumBTC on sushi: 1792 points
INFO: Completed signal registration for akash-network in 23.86 seconds

Registering signals group 31/44:  60%|██████    | 3/5 [00:23<00:14,  7.47s/it]

INFO: Completed signal registration for sushi in 24.08 seconds

Registering signals group 31/44:  80%|████████  | 4/5 [00:24<00:04,  4.57s/it]

INFO: Calculated initial values for RSI_Bullish_USD on maker: 2774 points
INFO: Calculated initial values for RSI_Bullish_BTC on maker: 2774 points
INFO: Calculated initial values for TrendMomentumUSD on maker: 2774 points
INFO: Calculated initial values for TrendMomentumBTC on maker: 2774 points
INFO: Completed signal registration for maker in 26.55 seconds

Registering signals group 31/44: 100%|██████████| 5/5 [00:26<00:00,  5.26s/it]

INFO: Processing asset group 32/44 with 5 assets
INFO: Starting signal registration for eos

INFO: Starting signal registration for verasity
INFO: Registering 6 new signals for verasity

Registering signals group 32/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for gains-network
INFO: Registering 6 new signals for eos
INFO: Starting signal registration for arbdoge-ai
INFO: Starting signal registration for story-2
INFO: Registering 6 new signals for gains-network
INFO: Registering 6 new signals for arbdoge-ai
INFO: Registering 6 new signals for story-2
INFO: Adapted windows for data length 162: [4, 6, 13, 20, 33]
INFO: Asset story-2: Using 5 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on story-2: 162 points
INFO: Calculated initial values for DonchianEnsembleBTC on story-2: 162 points
INFO: Asset arbdoge-ai: Using 9 windows with threshold 3
INFO: Calculated initial values for RSI_Bullish_USD on story-2: 162 points
INFO: Calculated initial values for DonchianEnsembleUSD on arbdoge-ai: 829 points
INFO: Calculated initial values for RSI_Bullish_BTC on story-2: 162 points
INFO: Asset verasity: Using 9 windows with threshold 3
INFO: Asset gains-network: Using 9 windows with threshold 3
INFO: Calculated initial values for TrendMomentumUSD on story-2: 162 points
INFO: Calculated initial values for DonchianEnsembleUSD on verasity: 1616 points
INFO: Calculated initial values for DonchianEnsembleUSD on gains-network: 1361 points
INFO: Calculated initial values for TrendMomentumBTC on story-2: 162 points
INFO: Completed signal registration for story-2 in 4.10 seconds

Registering signals group 32/44:  20%|██        | 1/5 [00:05<00:20,  5.05s/it]

INFO: Asset eos: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleBTC on arbdoge-ai: 829 points
INFO: Calculated initial values for DonchianEnsembleUSD on eos: 2938 points
INFO: Calculated initial values for RSI_Bullish_USD on arbdoge-ai: 829 points
INFO: Calculated initial values for RSI_Bullish_BTC on arbdoge-ai: 829 points
INFO: Calculated initial values for TrendMomentumUSD on arbdoge-ai: 829 points
INFO: Calculated initial values for DonchianEnsembleBTC on gains-network: 1361 points
INFO: Calculated initial values for TrendMomentumBTC on arbdoge-ai: 829 points
INFO: Completed signal registration for arbdoge-ai in 10.73 seconds

Registering signals group 32/44:  40%|████      | 2/5 [00:11<00:17,  5.88s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on verasity: 1616 points
INFO: Calculated initial values for RSI_Bullish_USD on gains-network: 1361 points
INFO: Calculated initial values for RSI_Bullish_BTC on gains-network: 1361 points
INFO: Calculated initial values for RSI_Bullish_USD on verasity: 1616 points
INFO: Calculated initial values for TrendMomentumUSD on gains-network: 1361 points
INFO: Calculated initial values for TrendMomentumBTC on gains-network: 1361 points
INFO: Calculated initial values for RSI_Bullish_BTC on verasity: 1616 points
INFO: Completed signal registration for gains-network in 15.30 seconds

Registering signals group 32/44:  60%|██████    | 3/5 [00:15<00:09,  4.94s/it]

INFO: Calculated initial values for TrendMomentumUSD on verasity: 1616 points
INFO: Calculated initial values for TrendMomentumBTC on verasity: 1616 points
INFO: Completed signal registration for verasity in 16.32 seconds

Registering signals group 32/44:  80%|████████  | 4/5 [00:16<00:03,  3.38s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on eos: 2938 points
INFO: Calculated initial values for RSI_Bullish_USD on eos: 2938 points
INFO: Calculated initial values for RSI_Bullish_BTC on eos: 2938 points
INFO: Calculated initial values for TrendMomentumUSD on eos: 2938 points
INFO: Calculated initial values for TrendMomentumBTC on eos: 2938 points
INFO: Completed signal registration for eos in 19.93 seconds

Registering signals group 32/44: 100%|██████████| 5/5 [00:19<00:00,  3.97s/it]

INFO: Processing asset group 33/44 with 5 assets
INFO: Starting signal registration for bonk

INFO: Starting signal registration for numeraire

Registering signals group 33/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for plume
INFO: Starting signal registration for sonic-3
INFO: Registering 6 new signals for bonk
INFO: Starting signal registration for jupiter-exchange-solana
INFO: Registering 6 new signals for numeraire
INFO: Registering 6 new signals for plume
INFO: Registering 6 new signals for sonic-3
INFO: Registering 6 new signals for jupiter-exchange-solana
INFO: Adapted windows for data length 185: [5, 7, 15, 23, 38]
INFO: Adapted windows for data length 202: [5, 8, 16, 25, 42]
INFO: Adapted windows for data length 541: [3, 7, 15, 22, 45, 67, 112]
INFO: Asset plume: Using 5 windows with threshold 3
INFO: Asset sonic-3: Using 5 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on plume: 185 points
INFO: Asset bonk: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on sonic-3: 202 points
INFO: Calculated initial values for DonchianEnsembleUSD on bonk: 939 points
INFO: Asset jupiter-exchange-solana: Using 7 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleBTC on plume: 185 points
INFO: Calculated initial values for DonchianEnsembleBTC on sonic-3: 202 points
INFO: Calculated initial values for DonchianEnsembleUSD on jupiter-exchange-solana: 541 points
INFO: Calculated initial values for RSI_Bullish_USD on plume: 185 points
INFO: Calculated initial values for RSI_Bullish_USD on sonic-3: 202 points
INFO: Calculated initial values for RSI_Bullish_BTC on plume: 185 points
INFO: Calculated initial values for RSI_Bullish_BTC on sonic-3: 202 points
INFO: Calculated initial values for TrendMomentumUSD on plume: 185 points
INFO: Calculated initial values for TrendMomentumUSD on sonic-3: 202 points
INFO: Calculated initial values for TrendMomentumBTC on plume: 185 points
INFO: Calculated initial values for TrendMomentumBTC on sonic-3: 202 points
INFO: Completed signal registration for plume in 3.87 seconds
INFO: Completed signal registration for sonic-3 in 4.01 seconds

Registering signals group 33/44:  20%|██        | 1/5 [00:04<00:16,  4.17s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on jupiter-exchange-solana: 541 points

Registering signals group 33/44:  40%|████      | 2/5 [00:04<00:05,  1.85s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on bonk: 939 points
INFO: Calculated initial values for RSI_Bullish_USD on jupiter-exchange-solana: 541 points
INFO: Asset numeraire: Using 9 windows with threshold 3
INFO: Calculated initial values for RSI_Bullish_BTC on jupiter-exchange-solana: 541 points
INFO: Calculated initial values for DonchianEnsembleUSD on numeraire: 2934 points
INFO: Calculated initial values for TrendMomentumUSD on jupiter-exchange-solana: 541 points
INFO: Calculated initial values for TrendMomentumBTC on jupiter-exchange-solana: 541 points
INFO: Completed signal registration for jupiter-exchange-solana in 6.31 seconds
INFO: Calculated initial values for RSI_Bullish_USD on bonk: 939 points

Registering signals group 33/44:  60%|██████    | 3/5 [00:06<00:03,  1.94s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on bonk: 939 points
INFO: Calculated initial values for TrendMomentumUSD on bonk: 939 points
INFO: Calculated initial values for TrendMomentumBTC on bonk: 939 points
INFO: Completed signal registration for bonk in 7.44 seconds

Registering signals group 33/44:  80%|████████  | 4/5 [00:07<00:01,  1.59s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on numeraire: 2934 points
INFO: Calculated initial values for RSI_Bullish_USD on numeraire: 2934 points
INFO: Calculated initial values for RSI_Bullish_BTC on numeraire: 2934 points
INFO: Calculated initial values for TrendMomentumUSD on numeraire: 2934 points
INFO: Calculated initial values for TrendMomentumBTC on numeraire: 2934 points
INFO: Completed signal registration for numeraire in 12.44 seconds

Registering signals group 33/44: 100%|██████████| 5/5 [00:12<00:00,  2.49s/it]

INFO: Processing asset group 34/44 with 5 assets
INFO: Starting signal registration for star-atlas-dao
INFO: Starting signal registration for hedera-hashgraph

INFO: Starting signal registration for solayer

Registering signals group 34/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 6 new signals for star-atlas-dao
INFO: Starting signal registration for aerodrome-finance
INFO: Starting signal registration for perpetual-protocol
INFO: Registering 6 new signals for perpetual-protocol
INFO: Registering 6 new signals for solayer
INFO: Registering 6 new signals for aerodrome-finance
INFO: Registering 6 new signals for hedera-hashgraph
INFO: Adapted windows for data length 164: [4, 6, 13, 20, 34]
INFO: Adapted windows for data length 679: [4, 9, 18, 28, 56, 84, 141]
INFO: Asset solayer: Using 5 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on solayer: 164 points
INFO: Calculated initial values for DonchianEnsembleBTC on solayer: 164 points
INFO: Asset aerodrome-finance: Using 7 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on aerodrome-finance: 679 points
INFO: Calculated initial values for RSI_Bullish_USD on solayer: 164 points
INFO: Asset star-atlas-dao: Using 9 windows with threshold 3
INFO: Calculated initial values for RSI_Bullish_BTC on solayer: 164 points
INFO: Calculated initial values for DonchianEnsembleUSD on star-atlas-dao: 1422 points
INFO: Calculated initial values for TrendMomentumUSD on solayer: 164 points
INFO: Calculated initial values for TrendMomentumBTC on solayer: 164 points
INFO: Completed signal registration for solayer in 3.87 seconds
INFO: Asset perpetual-protocol: Using 9 windows with threshold 3

Registering signals group 34/44:  20%|██        | 1/5 [00:04<00:16,  4.08s/it]

INFO: Calculated initial values for DonchianEnsembleUSD on perpetual-protocol: 1780 points
INFO: Calculated initial values for DonchianEnsembleBTC on aerodrome-finance: 679 points
INFO: Asset hedera-hashgraph: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on hedera-hashgraph: 2138 points
INFO: Calculated initial values for RSI_Bullish_USD on aerodrome-finance: 679 points
INFO: Calculated initial values for RSI_Bullish_BTC on aerodrome-finance: 679 points
INFO: Calculated initial values for TrendMomentumUSD on aerodrome-finance: 679 points
INFO: Calculated initial values for TrendMomentumBTC on aerodrome-finance: 679 points
INFO: Completed signal registration for aerodrome-finance in 8.32 seconds

Registering signals group 34/44:  40%|████      | 2/5 [00:08<00:12,  4.25s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on star-atlas-dao: 1422 points
INFO: Calculated initial values for DonchianEnsembleBTC on perpetual-protocol: 1780 points
INFO: Calculated initial values for RSI_Bullish_USD on star-atlas-dao: 1422 points
INFO: Calculated initial values for RSI_Bullish_BTC on star-atlas-dao: 1422 points
INFO: Calculated initial values for TrendMomentumUSD on star-atlas-dao: 1422 points
INFO: Calculated initial values for TrendMomentumBTC on star-atlas-dao: 1422 points
INFO: Calculated initial values for DonchianEnsembleBTC on hedera-hashgraph: 2138 points
INFO: Completed signal registration for star-atlas-dao in 13.99 seconds

Registering signals group 34/44:  60%|██████    | 3/5 [00:14<00:09,  4.91s/it]

INFO: Calculated initial values for RSI_Bullish_USD on perpetual-protocol: 1780 points
INFO: Calculated initial values for RSI_Bullish_BTC on perpetual-protocol: 1780 points
INFO: Calculated initial values for TrendMomentumUSD on perpetual-protocol: 1780 points
INFO: Calculated initial values for TrendMomentumBTC on perpetual-protocol: 1780 points
INFO: Completed signal registration for perpetual-protocol in 15.78 seconds

Registering signals group 34/44:  80%|████████  | 4/5 [00:15<00:03,  3.67s/it]

INFO: Calculated initial values for RSI_Bullish_USD on hedera-hashgraph: 2138 points
INFO: Calculated initial values for RSI_Bullish_BTC on hedera-hashgraph: 2138 points
INFO: Calculated initial values for TrendMomentumUSD on hedera-hashgraph: 2138 points
INFO: Calculated initial values for TrendMomentumBTC on hedera-hashgraph: 2138 points
INFO: Completed signal registration for hedera-hashgraph in 16.51 seconds

Registering signals group 34/44: 100%|██████████| 5/5 [00:16<00:00,  3.30s/it]

INFO: Processing asset group 35/44 with 5 assets
INFO: Starting signal registration for fwog
INFO: Starting signal registration for chex-token

INFO: Registering 6 new signals for fwog
INFO: Starting signal registration for official-trump

Registering signals group 35/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for matic-network
INFO: Starting signal registration for alchemy-pay
INFO: Registering 6 new signals for chex-token
INFO: Adapted windows for data length 360: [5, 10, 15, 30, 45, 75]
INFO: Registering 6 new signals for official-trump
INFO: Registering 6 new signals for matic-network
INFO: Registering 6 new signals for alchemy-pay
INFO: Adapted windows for data length 188: [5, 7, 15, 23, 39]
INFO: Asset fwog: Using 6 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on fwog: 360 points
INFO: Asset official-trump: Using 5 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on official-trump: 188 points
INFO: Calculated initial values for DonchianEnsembleBTC on official-trump: 188 points
INFO: Calculated initial values for DonchianEnsembleBTC on fwog: 360 points
INFO: Calculated initial values for RSI_Bullish_USD on official-trump: 188 points
INFO: Calculated initial values for RSI_Bullish_BTC on official-trump: 188 points
INFO: Calculated initial values for TrendMomentumUSD on official-trump: 188 points
INFO: Calculated initial values for RSI_Bullish_USD on fwog: 360 points
INFO: Calculated initial values for TrendMomentumBTC on official-trump: 188 points
INFO: Calculated initial values for RSI_Bullish_BTC on fwog: 360 points
INFO: Completed signal registration for official-trump in 3.76 seconds

Registering signals group 35/44:  20%|██        | 1/5 [00:03<00:15,  3.93s/it]

INFO: Calculated initial values for TrendMomentumUSD on fwog: 360 points
INFO: Asset chex-token: Using 9 windows with threshold 3
INFO: Calculated initial values for TrendMomentumBTC on fwog: 360 points
INFO: Calculated initial values for DonchianEnsembleUSD on chex-token: 1997 points
INFO: Asset alchemy-pay: Using 9 windows with threshold 3
INFO: Completed signal registration for fwog in 4.30 seconds

Registering signals group 35/44:  40%|████      | 2/5 [00:04<00:06,  2.03s/it]

INFO: Calculated initial values for DonchianEnsembleUSD on alchemy-pay: 1781 points
INFO: Asset matic-network: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on matic-network: 2282 points
INFO: Calculated initial values for DonchianEnsembleBTC on alchemy-pay: 1781 points
INFO: Calculated initial values for DonchianEnsembleBTC on chex-token: 1997 points
INFO: Calculated initial values for DonchianEnsembleBTC on matic-network: 2282 points
INFO: Calculated initial values for RSI_Bullish_USD on alchemy-pay: 1781 points
INFO: Calculated initial values for RSI_Bullish_BTC on alchemy-pay: 1781 points
INFO: Calculated initial values for RSI_Bullish_USD on chex-token: 1997 points
INFO: Calculated initial values for TrendMomentumUSD on alchemy-pay: 1781 points
INFO: Calculated initial values for RSI_Bullish_BTC on chex-token: 1997 points
INFO: Calculated initial values for TrendMomentumBTC on alchemy-pay: 1781 points
INFO: Completed signal registration for alchemy-pay in 16.34 seconds

Registering signals group 35/44:  60%|██████    | 3/5 [00:16<00:12,  6.47s/it]

INFO: Calculated initial values for TrendMomentumUSD on chex-token: 1997 points
INFO: Calculated initial values for RSI_Bullish_USD on matic-network: 2282 points
INFO: Calculated initial values for TrendMomentumBTC on chex-token: 1997 points
INFO: Completed signal registration for chex-token in 16.87 seconds

Registering signals group 35/44:  80%|████████  | 4/5 [00:16<00:04,  4.12s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on matic-network: 2282 points
INFO: Calculated initial values for TrendMomentumUSD on matic-network: 2282 points
INFO: Calculated initial values for TrendMomentumBTC on matic-network: 2282 points
INFO: Completed signal registration for matic-network in 18.51 seconds

Registering signals group 35/44: 100%|██████████| 5/5 [00:18<00:00,  3.70s/it]

INFO: Processing asset group 36/44 with 5 assets
INFO: Starting signal registration for popcat
INFO: Starting signal registration for shiba-inu
INFO: Registering 6 new signals for popcat

Registering signals group 36/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for internet-computer
INFO: Starting signal registration for snek
INFO: Starting signal registration for mog-coin
INFO: Registering 6 new signals for shiba-inu
INFO: Adapted windows for data length 584: [4, 8, 16, 24, 48, 73, 121]
INFO: Registering 6 new signals for internet-computer
INFO: Registering 6 new signals for snek
INFO: Registering 6 new signals for mog-coin
INFO: Asset popcat: Using 7 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on popcat: 584 points
INFO: Asset mog-coin: Using 9 windows with threshold 3
INFO: Asset snek: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on mog-coin: 735 points
INFO: Calculated initial values for DonchianEnsembleUSD on snek: 795 points
INFO: Asset internet-computer: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on internet-computer: 1537 points
INFO: Calculated initial values for DonchianEnsembleBTC on popcat: 584 points
INFO: Asset shiba-inu: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on shiba-inu: 1805 points
INFO: Calculated initial values for RSI_Bullish_USD on popcat: 584 points
INFO: Calculated initial values for DonchianEnsembleBTC on mog-coin: 735 points
INFO: Calculated initial values for RSI_Bullish_BTC on popcat: 584 points
INFO: Calculated initial values for DonchianEnsembleBTC on snek: 795 points
INFO: Calculated initial values for TrendMomentumUSD on popcat: 584 points
INFO: Calculated initial values for TrendMomentumBTC on popcat: 584 points
INFO: Completed signal registration for popcat in 10.55 seconds

Registering signals group 36/44:  20%|██        | 1/5 [00:10<00:42, 10.74s/it]

INFO: Calculated initial values for RSI_Bullish_USD on mog-coin: 735 points
INFO: Calculated initial values for RSI_Bullish_USD on snek: 795 points
INFO: Calculated initial values for RSI_Bullish_BTC on mog-coin: 735 points
INFO: Calculated initial values for RSI_Bullish_BTC on snek: 795 points
INFO: Calculated initial values for TrendMomentumUSD on mog-coin: 735 points
INFO: Calculated initial values for TrendMomentumUSD on snek: 795 points
INFO: Calculated initial values for TrendMomentumBTC on mog-coin: 735 points
INFO: Calculated initial values for TrendMomentumBTC on snek: 795 points
INFO: Completed signal registration for mog-coin in 13.45 seconds
INFO: Completed signal registration for snek in 13.68 seconds

Registering signals group 36/44:  40%|████      | 2/5 [00:13<00:18,  6.19s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on internet-computer: 1537 points
INFO: Calculated initial values for DonchianEnsembleBTC on shiba-inu: 1805 points
INFO: Calculated initial values for RSI_Bullish_USD on internet-computer: 1537 points
INFO: Calculated initial values for RSI_Bullish_BTC on internet-computer: 1537 points
INFO: Calculated initial values for TrendMomentumUSD on internet-computer: 1537 points
INFO: Calculated initial values for RSI_Bullish_USD on shiba-inu: 1805 points
INFO: Calculated initial values for TrendMomentumBTC on internet-computer: 1537 points
INFO: Completed signal registration for internet-computer in 16.92 seconds

Registering signals group 36/44:  80%|████████  | 4/5 [00:16<00:03,  3.31s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on shiba-inu: 1805 points
INFO: Calculated initial values for TrendMomentumUSD on shiba-inu: 1805 points
INFO: Calculated initial values for TrendMomentumBTC on shiba-inu: 1805 points
INFO: Completed signal registration for shiba-inu in 17.33 seconds

Registering signals group 36/44: 100%|██████████| 5/5 [00:17<00:00,  3.47s/it]

INFO: Processing asset group 37/44 with 5 assets
INFO: Starting signal registration for morpho
INFO: Registering 6 new signals for morpho
INFO: Starting signal registration for litecoin

INFO: Starting signal registration for near
INFO: Adapted windows for data length 247: [3, 6, 10, 20, 30, 51]

Registering signals group 37/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for euler
INFO: Starting signal registration for radiant-capital
INFO: Registering 6 new signals for litecoin
INFO: Registering 6 new signals for near
INFO: Asset morpho: Using 6 windows with threshold 3
INFO: Registering 6 new signals for euler
INFO: Registering 6 new signals for radiant-capital
INFO: Calculated initial values for DonchianEnsembleUSD on morpho: 247 points
INFO: Calculated initial values for DonchianEnsembleBTC on morpho: 247 points
INFO: Calculated initial values for RSI_Bullish_USD on morpho: 247 points
INFO: Calculated initial values for RSI_Bullish_BTC on morpho: 247 points
INFO: Calculated initial values for TrendMomentumUSD on morpho: 247 points
INFO: Calculated initial values for TrendMomentumBTC on morpho: 247 points
INFO: Completed signal registration for morpho in 3.19 seconds
INFO: Asset euler: Using 9 windows with threshold 3

Registering signals group 37/44:  20%|██        | 1/5 [00:03<00:13,  3.28s/it]

INFO: Asset radiant-capital: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on euler: 1127 points
INFO: Calculated initial values for DonchianEnsembleUSD on radiant-capital: 1095 points
INFO: Asset near: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on near: 1745 points
INFO: Calculated initial values for DonchianEnsembleBTC on euler: 1127 points
INFO: Calculated initial values for DonchianEnsembleBTC on radiant-capital: 1095 points
INFO: Asset litecoin: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on litecoin: 4471 points
INFO: Calculated initial values for RSI_Bullish_USD on euler: 1127 points
INFO: Calculated initial values for RSI_Bullish_USD on radiant-capital: 1095 points
INFO: Calculated initial values for DonchianEnsembleBTC on near: 1745 points
INFO: Calculated initial values for RSI_Bullish_BTC on euler: 1127 points
INFO: Calculated initial values for RSI_Bullish_BTC on radiant-capital: 1095 points
INFO: Calculated initial values for TrendMomentumUSD on euler: 1127 points
INFO: Calculated initial values for TrendMomentumUSD on radiant-capital: 1095 points
INFO: Calculated initial values for TrendMomentumBTC on euler: 1127 points
INFO: Completed signal registration for euler in 15.20 seconds
INFO: Calculated initial values for TrendMomentumBTC on radiant-capital: 1095 points

Registering signals group 37/44:  40%|████      | 2/5 [00:15<00:25,  8.49s/it]

INFO: Completed signal registration for radiant-capital in 15.59 seconds

Registering signals group 37/44:  60%|██████    | 3/5 [00:15<00:09,  4.78s/it]

INFO: Calculated initial values for RSI_Bullish_USD on near: 1745 points
INFO: Calculated initial values for RSI_Bullish_BTC on near: 1745 points
INFO: Calculated initial values for TrendMomentumUSD on near: 1745 points
INFO: Calculated initial values for TrendMomentumBTC on near: 1745 points
INFO: Completed signal registration for near in 18.10 seconds

Registering signals group 37/44:  80%|████████  | 4/5 [00:18<00:03,  3.81s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on litecoin: 4471 points
INFO: Calculated initial values for RSI_Bullish_USD on litecoin: 4471 points
INFO: Calculated initial values for RSI_Bullish_BTC on litecoin: 4471 points
INFO: Calculated initial values for TrendMomentumUSD on litecoin: 4471 points
INFO: Calculated initial values for TrendMomentumBTC on litecoin: 4471 points
INFO: Completed signal registration for litecoin in 24.65 seconds

Registering signals group 37/44: 100%|██████████| 5/5 [00:24<00:00,  4.92s/it]

INFO: Processing asset group 38/44 with 5 assets
INFO: Starting signal registration for injective-protocol
INFO: Starting signal registration for cow-protocol

INFO: Starting signal registration for hypercycle
INFO: Registering 6 new signals for hypercycle

Registering signals group 38/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 6 new signals for injective-protocol
INFO: Starting signal registration for swarm
INFO: Registering 6 new signals for cow-protocol
INFO: Starting signal registration for floki
INFO: Registering 6 new signals for swarm
INFO: Registering 6 new signals for floki
INFO: Asset hypercycle: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on hypercycle: 808 points
INFO: Asset cow-protocol: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on cow-protocol: 1215 points
INFO: Asset injective-protocol: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on injective-protocol: 1738 points
INFO: Asset floki: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on floki: 1488 points
INFO: Calculated initial values for DonchianEnsembleBTC on hypercycle: 808 points
INFO: Calculated initial values for RSI_Bullish_USD on hypercycle: 808 points
INFO: Calculated initial values for RSI_Bullish_BTC on hypercycle: 808 points
INFO: Calculated initial values for TrendMomentumUSD on hypercycle: 808 points
INFO: Asset swarm: Using 9 windows with threshold 3
INFO: Calculated initial values for TrendMomentumBTC on hypercycle: 808 points
INFO: Calculated initial values for DonchianEnsembleBTC on cow-protocol: 1215 points
INFO: Calculated initial values for DonchianEnsembleUSD on swarm: 3403 points
INFO: Completed signal registration for hypercycle in 10.15 seconds

Registering signals group 38/44:  20%|██        | 1/5 [00:10<00:42, 10.57s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on floki: 1488 points
INFO: Calculated initial values for DonchianEnsembleBTC on injective-protocol: 1738 points
INFO: Calculated initial values for RSI_Bullish_USD on cow-protocol: 1215 points
INFO: Calculated initial values for RSI_Bullish_BTC on cow-protocol: 1215 points
INFO: Calculated initial values for TrendMomentumUSD on cow-protocol: 1215 points
INFO: Calculated initial values for RSI_Bullish_USD on floki: 1488 points
INFO: Calculated initial values for TrendMomentumBTC on cow-protocol: 1215 points
INFO: Completed signal registration for cow-protocol in 15.48 seconds

Registering signals group 38/44:  40%|████      | 2/5 [00:15<00:21,  7.26s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on floki: 1488 points
INFO: Calculated initial values for RSI_Bullish_USD on injective-protocol: 1738 points
INFO: Calculated initial values for TrendMomentumUSD on floki: 1488 points
INFO: Calculated initial values for TrendMomentumBTC on floki: 1488 points
INFO: Calculated initial values for RSI_Bullish_BTC on injective-protocol: 1738 points
INFO: Completed signal registration for floki in 16.03 seconds

Registering signals group 38/44:  60%|██████    | 3/5 [00:16<00:08,  4.40s/it]

INFO: Calculated initial values for TrendMomentumUSD on injective-protocol: 1738 points
INFO: Calculated initial values for TrendMomentumBTC on injective-protocol: 1738 points
INFO: Completed signal registration for injective-protocol in 17.41 seconds

Registering signals group 38/44:  80%|████████  | 4/5 [00:17<00:03,  3.02s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on swarm: 3403 points
ERROR: Error calculating RSI Bullish signal for swarm: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
INFO: Calculated initial values for RSI_Bullish_USD on swarm: 3403 points
INFO: Calculated initial values for RSI_Bullish_BTC on swarm: 3403 points
ERROR: Error calculating Trend Momentum signal for swarm: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
INFO: Calculated initial values for TrendMomentumUSD on swarm: 3403 points
INFO: Calculated initial values for TrendMomentumBTC on swarm: 3403 points
INFO: Completed signal registration for swarm in 21.49 seconds

Registering signals group 38/44: 100%|██████████| 5/5 [00:21<00:00,  4.34s/it]

INFO: Processing asset group 39/44 with 5 assets
INFO: Starting signal registration for mubarak

INFO: Starting signal registration for curve-dao-token

Registering signals group 39/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for mintlayer
INFO: Starting signal registration for gigachad-2
INFO: Starting signal registration for ripple
INFO: Registering 6 new signals for mubarak
INFO: Registering 6 new signals for curve-dao-token
INFO: Registering 6 new signals for mintlayer
INFO: Registering 6 new signals for gigachad-2
INFO: Registering 6 new signals for ripple
INFO: Adapted windows for data length 131: [3, 5, 10, 16, 27]
INFO: Adapted windows for data length 550: [3, 7, 15, 22, 45, 68, 114]
INFO: Asset mubarak: Using 5 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on mubarak: 131 points
INFO: Calculated initial values for DonchianEnsembleBTC on mubarak: 131 points
INFO: Asset mintlayer: Using 9 windows with threshold 3
INFO: Asset gigachad-2: Using 7 windows with threshold 3
INFO: Calculated initial values for RSI_Bullish_USD on mubarak: 131 points
INFO: Calculated initial values for DonchianEnsembleUSD on mintlayer: 853 points
INFO: Calculated initial values for DonchianEnsembleUSD on gigachad-2: 550 points
INFO: Calculated initial values for RSI_Bullish_BTC on mubarak: 131 points
INFO: Asset curve-dao-token: Using 9 windows with threshold 3
INFO: Calculated initial values for TrendMomentumUSD on mubarak: 131 points
INFO: Calculated initial values for DonchianEnsembleUSD on curve-dao-token: 1806 points
INFO: Calculated initial values for TrendMomentumBTC on mubarak: 131 points
INFO: Completed signal registration for mubarak in 4.12 seconds

Registering signals group 39/44:  20%|██        | 1/5 [00:04<00:17,  4.36s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on gigachad-2: 550 points
INFO: Calculated initial values for RSI_Bullish_USD on gigachad-2: 550 points
INFO: Calculated initial values for DonchianEnsembleBTC on mintlayer: 853 points
INFO: Calculated initial values for RSI_Bullish_BTC on gigachad-2: 550 points
INFO: Calculated initial values for TrendMomentumUSD on gigachad-2: 550 points
INFO: Calculated initial values for TrendMomentumBTC on gigachad-2: 550 points
INFO: Completed signal registration for gigachad-2 in 7.42 seconds

Registering signals group 39/44:  40%|████      | 2/5 [00:07<00:11,  3.68s/it]

INFO: Calculated initial values for RSI_Bullish_USD on mintlayer: 853 points
INFO: Calculated initial values for RSI_Bullish_BTC on mintlayer: 853 points
INFO: Asset ripple: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on ripple: 4373 points
INFO: Calculated initial values for TrendMomentumUSD on mintlayer: 853 points
INFO: Calculated initial values for TrendMomentumBTC on mintlayer: 853 points
INFO: Completed signal registration for mintlayer in 9.34 seconds
INFO: Calculated initial values for DonchianEnsembleBTC on curve-dao-token: 1806 points

Registering signals group 39/44:  60%|██████    | 3/5 [00:09<00:05,  2.86s/it]

INFO: Calculated initial values for RSI_Bullish_USD on curve-dao-token: 1806 points
INFO: Calculated initial values for RSI_Bullish_BTC on curve-dao-token: 1806 points
INFO: Calculated initial values for TrendMomentumUSD on curve-dao-token: 1806 points
INFO: Calculated initial values for TrendMomentumBTC on curve-dao-token: 1806 points
INFO: Completed signal registration for curve-dao-token in 13.22 seconds

Registering signals group 39/44:  80%|████████  | 4/5 [00:13<00:03,  3.26s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on ripple: 4373 points
INFO: Calculated initial values for RSI_Bullish_USD on ripple: 4373 points
INFO: Calculated initial values for RSI_Bullish_BTC on ripple: 4373 points
INFO: Calculated initial values for TrendMomentumUSD on ripple: 4373 points
INFO: Calculated initial values for TrendMomentumBTC on ripple: 4373 points
INFO: Completed signal registration for ripple in 21.03 seconds

Registering signals group 39/44: 100%|██████████| 5/5 [00:21<00:00,  4.21s/it]

INFO: Processing asset group 40/44 with 5 assets
INFO: Starting signal registration for ethereum-classic

INFO: Starting signal registration for syrup

Registering signals group 40/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Registering 6 new signals for syrup
INFO: Starting signal registration for goatseus-maximus
INFO: Registering 6 new signals for goatseus-maximus
INFO: Registering 6 new signals for ethereum-classic
INFO: Starting signal registration for liquity
INFO: Adapted windows for data length 254: [3, 7, 10, 21, 31, 52]
INFO: Starting signal registration for slerf
INFO: Adapted windows for data length 285: [3, 7, 11, 23, 35, 59]
INFO: Registering 6 new signals for liquity
INFO: Registering 6 new signals for slerf
INFO: Asset syrup: Using 6 windows with threshold 3
INFO: Asset goatseus-maximus: Using 6 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on syrup: 254 points
INFO: Calculated initial values for DonchianEnsembleUSD on goatseus-maximus: 285 points
INFO: Asset slerf: Using 7 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on slerf: 494 points
INFO: Calculated initial values for DonchianEnsembleBTC on syrup: 254 points
INFO: Calculated initial values for DonchianEnsembleBTC on goatseus-maximus: 285 points
INFO: Calculated initial values for RSI_Bullish_USD on syrup: 254 points
INFO: Calculated initial values for RSI_Bullish_USD on goatseus-maximus: 285 points
INFO: Calculated initial values for RSI_Bullish_BTC on syrup: 254 points
INFO: Calculated initial values for RSI_Bullish_BTC on goatseus-maximus: 285 points
INFO: Calculated initial values for TrendMomentumUSD on syrup: 254 points
INFO: Calculated initial values for DonchianEnsembleBTC on slerf: 494 points
INFO: Calculated initial values for TrendMomentumUSD on goatseus-maximus: 285 points
INFO: Calculated initial values for TrendMomentumBTC on syrup: 254 points
INFO: Asset liquity: Using 9 windows with threshold 3
INFO: Calculated initial values for TrendMomentumBTC on goatseus-maximus: 285 points
INFO: Completed signal registration for syrup in 5.13 seconds
INFO: Calculated initial values for DonchianEnsembleUSD on liquity: 1572 points

Registering signals group 40/44:  20%|██        | 1/5 [00:05<00:21,  5.46s/it]

INFO: Completed signal registration for goatseus-maximus in 5.41 seconds
INFO: Calculated initial values for RSI_Bullish_USD on slerf: 494 points

Registering signals group 40/44:  40%|████      | 2/5 [00:05<00:07,  2.36s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on slerf: 494 points
INFO: Calculated initial values for TrendMomentumUSD on slerf: 494 points
INFO: Calculated initial values for TrendMomentumBTC on slerf: 494 points
INFO: Completed signal registration for slerf in 6.37 seconds
INFO: Asset ethereum-classic: Using 9 windows with threshold 3

Registering signals group 40/44:  60%|██████    | 3/5 [00:06<00:03,  1.75s/it]

INFO: Calculated initial values for DonchianEnsembleUSD on ethereum-classic: 3288 points
INFO: Calculated initial values for DonchianEnsembleBTC on liquity: 1572 points
INFO: Calculated initial values for RSI_Bullish_USD on liquity: 1572 points
INFO: Calculated initial values for RSI_Bullish_BTC on liquity: 1572 points
INFO: Calculated initial values for TrendMomentumUSD on liquity: 1572 points
INFO: Calculated initial values for TrendMomentumBTC on liquity: 1572 points
INFO: Completed signal registration for liquity in 12.74 seconds

Registering signals group 40/44:  80%|████████  | 4/5 [00:12<00:03,  3.51s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on ethereum-classic: 3288 points
INFO: Calculated initial values for RSI_Bullish_USD on ethereum-classic: 3288 points
INFO: Calculated initial values for RSI_Bullish_BTC on ethereum-classic: 3288 points
INFO: Calculated initial values for TrendMomentumUSD on ethereum-classic: 3288 points
INFO: Calculated initial values for TrendMomentumBTC on ethereum-classic: 3288 points
INFO: Completed signal registration for ethereum-classic in 16.31 seconds

Registering signals group 40/44: 100%|██████████| 5/5 [00:16<00:00,  3.26s/it]

INFO: Processing asset group 41/44 with 5 assets
INFO: Starting signal registration for true-usd
INFO: Registering 6 new signals for true-usd
INFO: Starting signal registration for myria

INFO: Starting signal registration for avalanche-2
INFO: Starting signal registration for pax-gold

Registering signals group 41/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for y
INFO: Registering 6 new signals for myria
INFO: Registering 6 new signals for avalanche-2
INFO: Registering 6 new signals for pax-gold
INFO: Registering 6 new signals for y
INFO: Adapted windows for data length 480: [3, 6, 13, 20, 40, 60, 100]
INFO: Asset myria: Using 9 windows with threshold 3
INFO: Asset y: Using 7 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on myria: 841 points
INFO: Calculated initial values for DonchianEnsembleUSD on y: 480 points
INFO: Asset avalanche-2: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on avalanche-2: 1767 points
INFO: Calculated initial values for DonchianEnsembleBTC on y: 480 points
INFO: Asset true-usd: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on true-usd: 2682 points
INFO: Asset pax-gold: Using 9 windows with threshold 3
INFO: Calculated initial values for RSI_Bullish_USD on y: 480 points
INFO: Calculated initial values for DonchianEnsembleUSD on pax-gold: 2140 points
INFO: Calculated initial values for RSI_Bullish_BTC on y: 480 points
INFO: Calculated initial values for DonchianEnsembleBTC on myria: 841 points
INFO: Calculated initial values for TrendMomentumUSD on y: 480 points
INFO: Calculated initial values for TrendMomentumBTC on y: 480 points
INFO: Completed signal registration for y in 7.75 seconds

Registering signals group 41/44:  20%|██        | 1/5 [00:08<00:32,  8.22s/it]

INFO: Calculated initial values for RSI_Bullish_USD on myria: 841 points
INFO: Calculated initial values for RSI_Bullish_BTC on myria: 841 points
INFO: Calculated initial values for TrendMomentumUSD on myria: 841 points
INFO: Calculated initial values for TrendMomentumBTC on myria: 841 points
INFO: Completed signal registration for myria in 10.75 seconds

Registering signals group 41/44:  40%|████      | 2/5 [00:10<00:14,  4.86s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on avalanche-2: 1767 points
INFO: Calculated initial values for DonchianEnsembleBTC on pax-gold: 2140 points
INFO: Calculated initial values for RSI_Bullish_USD on avalanche-2: 1767 points
INFO: Calculated initial values for DonchianEnsembleBTC on true-usd: 2682 points
INFO: Calculated initial values for RSI_Bullish_BTC on avalanche-2: 1767 points
INFO: Calculated initial values for TrendMomentumUSD on avalanche-2: 1767 points
INFO: Calculated initial values for TrendMomentumBTC on avalanche-2: 1767 points
INFO: Completed signal registration for avalanche-2 in 16.74 seconds

Registering signals group 41/44:  60%|██████    | 3/5 [00:16<00:10,  5.43s/it]

INFO: Calculated initial values for RSI_Bullish_USD on pax-gold: 2140 points
INFO: Calculated initial values for RSI_Bullish_BTC on pax-gold: 2140 points
INFO: Calculated initial values for TrendMomentumUSD on pax-gold: 2140 points
INFO: Calculated initial values for RSI_Bullish_USD on true-usd: 2682 points
INFO: Calculated initial values for TrendMomentumBTC on pax-gold: 2140 points
INFO: Completed signal registration for pax-gold in 18.55 seconds

Registering signals group 41/44:  80%|████████  | 4/5 [00:18<00:03,  3.96s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on true-usd: 2682 points
INFO: Calculated initial values for TrendMomentumUSD on true-usd: 2682 points
INFO: Calculated initial values for TrendMomentumBTC on true-usd: 2682 points
INFO: Completed signal registration for true-usd in 19.31 seconds

Registering signals group 41/44: 100%|██████████| 5/5 [00:19<00:00,  3.82s/it]

INFO: Processing asset group 42/44 with 5 assets
INFO: Starting signal registration for monero

Registering signals group 42/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for mantra-dao
INFO: Starting signal registration for paal-ai
INFO: Registering 6 new signals for paal-ai
INFO: Starting signal registration for cardano
INFO: Registering 6 new signals for monero
INFO: Registering 6 new signals for mantra-dao
INFO: Starting signal registration for constitutiondao
INFO: Registering 6 new signals for cardano
INFO: Registering 6 new signals for constitutiondao
INFO: Asset paal-ai: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on paal-ai: 760 points
INFO: Asset constitutiondao: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on constitutiondao: 1344 points
INFO: Asset mantra-dao: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleBTC on paal-ai: 760 points
INFO: Calculated initial values for DonchianEnsembleUSD on mantra-dao: 1802 points
INFO: Calculated initial values for RSI_Bullish_USD on paal-ai: 760 points
INFO: Calculated initial values for RSI_Bullish_BTC on paal-ai: 760 points
INFO: Asset cardano: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on cardano: 2837 points
INFO: Calculated initial values for TrendMomentumUSD on paal-ai: 760 points
INFO: Calculated initial values for TrendMomentumBTC on paal-ai: 760 points
INFO: Completed signal registration for paal-ai in 10.22 seconds

Registering signals group 42/44:  20%|██        | 1/5 [00:10<00:41, 10.35s/it]

INFO: Asset monero: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on monero: 4083 points
INFO: Calculated initial values for DonchianEnsembleBTC on constitutiondao: 1344 points
INFO: Calculated initial values for DonchianEnsembleBTC on mantra-dao: 1802 points
INFO: Calculated initial values for RSI_Bullish_USD on constitutiondao: 1344 points
INFO: Calculated initial values for RSI_Bullish_BTC on constitutiondao: 1344 points
INFO: Calculated initial values for TrendMomentumUSD on constitutiondao: 1344 points
INFO: Calculated initial values for TrendMomentumBTC on constitutiondao: 1344 points
INFO: Completed signal registration for constitutiondao in 17.50 seconds

Registering signals group 42/44:  40%|████      | 2/5 [00:18<00:26,  8.78s/it]

INFO: Calculated initial values for RSI_Bullish_USD on mantra-dao: 1802 points
INFO: Calculated initial values for RSI_Bullish_BTC on mantra-dao: 1802 points
INFO: Calculated initial values for TrendMomentumUSD on mantra-dao: 1802 points
INFO: Calculated initial values for TrendMomentumBTC on mantra-dao: 1802 points
INFO: Calculated initial values for DonchianEnsembleBTC on cardano: 2837 points
INFO: Completed signal registration for mantra-dao in 21.06 seconds

Registering signals group 42/44:  60%|██████    | 3/5 [00:21<00:12,  6.23s/it]

INFO: Calculated initial values for RSI_Bullish_USD on cardano: 2837 points
INFO: Calculated initial values for DonchianEnsembleBTC on monero: 4083 points
INFO: Calculated initial values for RSI_Bullish_BTC on cardano: 2837 points
INFO: Calculated initial values for TrendMomentumUSD on cardano: 2837 points
INFO: Calculated initial values for TrendMomentumBTC on cardano: 2837 points
INFO: Completed signal registration for cardano in 26.20 seconds

Registering signals group 42/44:  80%|████████  | 4/5 [00:26<00:05,  5.80s/it]

INFO: Calculated initial values for RSI_Bullish_USD on monero: 4083 points
INFO: Calculated initial values for RSI_Bullish_BTC on monero: 4083 points
INFO: Calculated initial values for TrendMomentumUSD on monero: 4083 points
INFO: Calculated initial values for TrendMomentumBTC on monero: 4083 points
INFO: Completed signal registration for monero in 29.87 seconds

Registering signals group 42/44: 100%|██████████| 5/5 [00:29<00:00,  5.97s/it]

INFO: Processing asset group 43/44 with 5 assets
INFO: Starting signal registration for based-brett

INFO: Starting signal registration for osaka-protocol

Registering signals group 43/44:   0%|          | 0/5 [00:00<?, ?it/s]

INFO: Starting signal registration for genopets
INFO: Starting signal registration for solana
INFO: Starting signal registration for lagrange
INFO: Registering 6 new signals for based-brett
INFO: Registering 6 new signals for osaka-protocol
INFO: Registering 6 new signals for genopets
INFO: Registering 6 new signals for solana
INFO: Registering 6 new signals for lagrange
INFO: Adapted windows for data length 512: [3, 7, 14, 21, 42, 64, 106]
INFO: Adapted windows for data length 51: [4, 6, 10, 17]
INFO: Asset lagrange: Using 4 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on lagrange: 51 points
INFO: Calculated initial values for DonchianEnsembleBTC on lagrange: 51 points
INFO: Calculated initial values for RSI_Bullish_USD on lagrange: 51 points
INFO: Asset based-brett: Using 7 windows with threshold 3
INFO: Calculated initial values for RSI_Bullish_BTC on lagrange: 51 points
INFO: Asset osaka-protocol: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on based-brett: 512 points
WARNING: Insufficient data for lagrange: 51 samples, need at least 60
INFO: Calculated initial values for DonchianEnsembleUSD on osaka-protocol: 749 points
INFO: Calculated initial values for TrendMomentumUSD on lagrange: 51 points
INFO: Asset genopets: Using 9 windows with threshold 3
INFO: Calculated initial values for TrendMomentumBTC on lagrange: 51 points
INFO: Calculated initial values for DonchianEnsembleUSD on genopets: 1345 points
INFO: Completed signal registration for lagrange in 2.75 seconds

Registering signals group 43/44:  20%|██        | 1/5 [00:03<00:12,  3.10s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on based-brett: 512 points
INFO: Asset solana: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on solana: 1932 points
INFO: Calculated initial values for RSI_Bullish_USD on based-brett: 512 points
INFO: Calculated initial values for DonchianEnsembleBTC on osaka-protocol: 749 points
INFO: Calculated initial values for RSI_Bullish_BTC on based-brett: 512 points
INFO: Calculated initial values for TrendMomentumUSD on based-brett: 512 points
INFO: Calculated initial values for TrendMomentumBTC on based-brett: 512 points
INFO: Completed signal registration for based-brett in 6.29 seconds
INFO: Calculated initial values for RSI_Bullish_USD on osaka-protocol: 749 points

Registering signals group 43/44:  40%|████      | 2/5 [00:06<00:09,  3.23s/it]

INFO: Calculated initial values for RSI_Bullish_BTC on osaka-protocol: 749 points
INFO: Calculated initial values for DonchianEnsembleBTC on genopets: 1345 points
INFO: Calculated initial values for TrendMomentumUSD on osaka-protocol: 749 points
INFO: Calculated initial values for TrendMomentumBTC on osaka-protocol: 749 points
INFO: Completed signal registration for osaka-protocol in 7.80 seconds

Registering signals group 43/44:  60%|██████    | 3/5 [00:07<00:04,  2.46s/it]

INFO: Calculated initial values for RSI_Bullish_USD on genopets: 1345 points
INFO: Calculated initial values for RSI_Bullish_BTC on genopets: 1345 points
INFO: Calculated initial values for DonchianEnsembleBTC on solana: 1932 points
INFO: Calculated initial values for TrendMomentumUSD on genopets: 1345 points
INFO: Calculated initial values for TrendMomentumBTC on genopets: 1345 points
INFO: Completed signal registration for genopets in 10.67 seconds

Registering signals group 43/44:  80%|████████  | 4/5 [00:10<00:02,  2.59s/it]

INFO: Calculated initial values for RSI_Bullish_USD on solana: 1932 points
INFO: Calculated initial values for RSI_Bullish_BTC on solana: 1932 points
INFO: Calculated initial values for TrendMomentumUSD on solana: 1932 points
INFO: Calculated initial values for TrendMomentumBTC on solana: 1932 points
INFO: Completed signal registration for solana in 12.51 seconds

Registering signals group 43/44: 100%|██████████| 5/5 [00:12<00:00,  2.50s/it]

INFO: Processing asset group 44/44 with 3 assets
INFO: Starting signal registration for frax-share
INFO: Starting signal registration for kaito

INFO: Registering 6 new signals for frax-share

Registering signals group 44/44:   0%|          | 0/3 [00:00<?, ?it/s]

INFO: Starting signal registration for neon
INFO: Registering 6 new signals for kaito
INFO: Registering 6 new signals for neon
INFO: Adapted windows for data length 155: [4, 6, 12, 19, 32]
INFO: Asset kaito: Using 5 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on kaito: 155 points
INFO: Calculated initial values for DonchianEnsembleBTC on kaito: 155 points
INFO: Asset neon: Using 9 windows with threshold 3
INFO: Calculated initial values for RSI_Bullish_USD on kaito: 155 points
INFO: Calculated initial values for DonchianEnsembleUSD on neon: 738 points
INFO: Calculated initial values for RSI_Bullish_BTC on kaito: 155 points
INFO: Calculated initial values for TrendMomentumUSD on kaito: 155 points
INFO: Calculated initial values for TrendMomentumBTC on kaito: 155 points
INFO: Completed signal registration for kaito in 2.24 seconds

Registering signals group 44/44:  33%|███▎      | 1/3 [00:02<00:04,  2.24s/it]

INFO: Asset frax-share: Using 9 windows with threshold 3
INFO: Calculated initial values for DonchianEnsembleUSD on frax-share: 1677 points
INFO: Calculated initial values for DonchianEnsembleBTC on neon: 738 points
INFO: Calculated initial values for RSI_Bullish_USD on neon: 738 points
INFO: Calculated initial values for RSI_Bullish_BTC on neon: 738 points
INFO: Calculated initial values for TrendMomentumUSD on neon: 738 points
INFO: Calculated initial values for TrendMomentumBTC on neon: 738 points
INFO: Completed signal registration for neon in 4.99 seconds

Registering signals group 44/44:  67%|██████▋   | 2/3 [00:05<00:02,  2.57s/it]

INFO: Calculated initial values for DonchianEnsembleBTC on frax-share: 1677 points
INFO: Calculated initial values for RSI_Bullish_USD on frax-share: 1677 points
INFO: Calculated initial values for RSI_Bullish_BTC on frax-share: 1677 points
INFO: Calculated initial values for TrendMomentumUSD on frax-share: 1677 points
INFO: Calculated initial values for TrendMomentumBTC on frax-share: 1677 points
INFO: Completed signal registration for frax-share in 6.78 seconds

Registering signals group 44/44: 100%|██████████| 3/3 [00:06<00:00,  2.25s/it]

INFO: Registered a total of 1308 signals across 218 assets

{'heyanon': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x169faee10>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x143a2ad50>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x169fad050>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x169d2ee10>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x169d04dd0>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x313264950>},
 'neiro-3': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x169e937d0>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x169afc710>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x169d2e190>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x169d05610>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x169faf710>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x169d2f810>},
 'coredaoorg': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x3132667d0>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x169d2f090>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x109604550>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x169e932d0>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x169e93810>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x16fa10710>},
 'axie-infinity': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x143fad610>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x143a8a010>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x16fa12850>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x169fada50>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x169faf550>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x169d05110>},
 'tezos': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x313266190>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x143acda50>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x16fa10090>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x313267890>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x169faec50>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x16fa134d0>},
 'fartcoin': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x17f065e90>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x169e6ec90>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x16ff5d0d0>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x17f067b10>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x16f68ef90>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x17f064510>},
 'dogwifcoin': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x16ff5f210>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x3132679d0>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x3132650d0>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x143fac850>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x169e6dd50>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x16ff5e4d0>},
 'grok-2': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x169e6e390>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x313266350>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x16f6c8110>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x169e6eb10>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x17f0669d0>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x16ff5e8d0>},
 'dodo': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x17f064ed0>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x169fafe90>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x16a2ca690>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x17f067b50>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x16a2c9510>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x16f68cf90>},
 'quant-network': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x17f067fd0>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x169d07b50>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x13ecca550>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x16f68f810>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x16f6c8890>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x16a2cb750>},
 'aixbt': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x16f706910>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x313267250>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x16f6cb7d0>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x16f707810>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x169fc36d0>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x1697220d0>},
 'hyperliquid': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x16ff5ebd0>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x169d06450>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x169e6c790>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x16face6d0>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x16fb8f990>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x169e12e10>},
 'moonwell-artemis': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x16fb8f210>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x16f707190>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x16f6cb850>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x169d2cf10>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x16f68d3d0>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x17f066690>},
 'optimism': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x169fc3650>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x16fa10a50>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x169e92990>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x169e136d0>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x16f68d650>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x169e13ed0>},
 'yearn-finance': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x16f705350>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x16ff5ef10>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x16facc890>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x17f065410>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x169fc0d10>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x169fc0e50>},
 'alchemist-ai': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x16a0da410>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x169e10690>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x169ee1a90>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x16a0d80d0>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x16f6c8790>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x16facc950>},
 'ondo-finance': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x169fb3650>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x16f6c8090>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x169fc2ad0>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x16a0d8610>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x16f6a0d90>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x169d2e2d0>},
 'illuvium': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x16fb8ff10>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x17f064650>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x169faf3d0>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x16fb8e810>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x3132f7550>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x169e90810>},
 'dusk-network': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x16a0d8e50>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x313264bd0>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x16f6ca8d0>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x3132f73d0>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x16fa12e50>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x3131c1610>},
 'havven': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x169fb3590>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x3132f49d0>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x16f706e50>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x16f6a3450>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x16a0dae90>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x3132f7b90>},
 'ronin': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x16f72bc50>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x16fb8c510>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x16face550>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x169fc1a10>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x313267dd0>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x16fa3c950>},
 'acala': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x16f729290>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x169ee0e10>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x169fb1e50>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x16f9d4150>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x16fa3c890>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x16face7d0>},
 'band-protocol': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x16f72b1d0>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x16fb802d0>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x169ee2a50>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x169e6ec10>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x16facd050>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x169f37210>},
 'fetch-ai': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x3131c2f50>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x169fb1110>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x3132f62d0>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x169e6e950>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x16f705950>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x16ff5ed90>},
 'omisego': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x16f7294d0>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x3132f7410>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x17f0645d0>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x16a0d8890>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x16f72a650>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x16f707e50>},
 'multibit': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x17f067310>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x16a0dbd10>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x16f9d5610>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x16f9d43d0>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x16f7208d0>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x16f6cbb90>},
 'gala': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x16f9d7210>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x169f65350>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x169fc3310>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x16f722310>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x3131c2110>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x169f66cd0>},
 'uniswap': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x169f66150>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x16f729f10>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x16fa3e590>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x313271290>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x16a240e90>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x169e6e3d0>},
 'bitcoin': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x16f68f990>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x169fc3550>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x169fb3f50>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x16a0d9950>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x16f6ac390>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x16f6ae890>},
 'stellar': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x16fb86b10>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x3131c2610>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x169f36b50>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x169fb1050>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x169e13790>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x16fb826d0>},
 'aethir': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x16a0db010>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x169d051d0>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x16f7237d0>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x16f9d4c50>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x313270a50>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x313270110>},
 'apu-s-club': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x16f6af210>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x16f9d5250>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x169e90c10>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x169e6ecd0>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x16f660410>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x16fb869d0>},
 'turbo': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x16f660d90>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x16f6a3910>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x16fa3dc50>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x16f661410>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x16f6af7d0>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x16f6c9c10>},
 'pendle': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x169e12010>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x16fb83490>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x169e6e150>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x16f6f1310>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x16f721ed0>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x16f67c950>},
 'the-sandbox': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x16f7226d0>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x16a2408d0>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x169fb2f90>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x169fc3a10>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x169ee0d10>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x16f9d7550>},
 'equilibria-finance': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x3132738d0>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x16f663550>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x16fac7b10>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x169d11bd0>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x16fcd6f90>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x169d12a50>},
 'gmx': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x16f6f0c10>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x16f67e350>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x16a1e3f10>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x169d12850>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x16fb87f10>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x16fa3d890>},
 'crypto-com-chain': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x16fac7210>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x16f6acc10>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x16fa3c9d0>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x313272410>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x16fac6410>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x3131c0310>},
 'polymath': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x16a243d90>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x16a240350>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x16a1e3e50>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x16a1e07d0>,
  'TrendMomentumUSD': <soros_system.core.signal_data.SignalData at 0x16a1e2050>,
  'TrendMomentumBTC': <soros_system.core.signal_data.SignalData at 0x16f6f0350>},
 'zcash': {'DonchianEnsembleUSD': <soros_system.core.signal_data.SignalData at 0x16a2c8190>,
  'DonchianEnsembleBTC': <soros_system.core.signal_data.SignalData at 0x16f6ac510>,
  'RSI_Bullish_USD': <soros_system.core.signal_data.SignalData at 0x3132f40d0>,
  'RSI_Bullish_BTC': <soros_system.core.signal_data.SignalData at 0x16f7056d0>,

In [9]:
# Select exactly which signals you want to use
usd_signals = [
   
    #'DonchianEnsembleUSD',
    'TrendMomentumUSD',
    #'RSI_Ensemble_Signal_USD'
]
 
btc_signals = [
    #'RSI_Oversold_BTC',
    #'RSI_Bullish_BTC'
    #'BullRegimeSignalBTC'
    #'RSI_Ensemble_Signal_BTC'
]



# Run the backtest for all assets at once
results = analyzer.backtest_assets(
    asset_ids=assets,
    start_date="2023-1-1",
    end_date="2025-04-30",
    initial_capital=10000.0,
    btc_cost=0.001,  # Lower cost for Bitcoin
    alt_cost=0.005,  # Higher cost for altcoins
    usd_signals=usd_signals,
    btc_signals=btc_signals,
    use_btc_filter=True,
   # allow_short=True
)

INFO: Using Bitcoin as a filter with signals: ['TrendMomentumUSD']
INFO: Stored backtest results in asset bitcoin with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset bitcoin with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset axie-infinity with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset axie-infinity with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset tezos with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset tezos with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset neiro-3 with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset neiro-3 with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset coredaoorg with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset coredaoorg with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset heyanon with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset heyanon with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset dogwifcoin with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset dogwifcoin with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset quant-network with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset quant-network with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset fartcoin with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset fartcoin with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset dodo with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset dodo with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset grok-2 with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset grok-2 with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset moonwell-artemis with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset moonwell-artemis with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset hyperliquid with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset hyperliquid with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset optimism with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset optimism with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset yearn-finance with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset yearn-finance with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset aixbt with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset aixbt with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset illuvium with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset illuvium with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset ondo-finance with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset ondo-finance with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset dusk-network with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset dusk-network with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset alchemist-ai with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset alchemist-ai with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset havven with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset havven with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset fetch-ai with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset fetch-ai with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset ronin with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset ronin with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset omisego with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset omisego with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset acala with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset acala with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset band-protocol with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset band-protocol with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset gala with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset gala with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset multibit with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset multibit with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset stellar with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset stellar with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset uniswap with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset uniswap with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset apu-s-club with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset apu-s-club with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset the-sandbox with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset the-sandbox with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset turbo with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset turbo with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset aethir with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset aethir with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset pendle with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset pendle with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset crypto-com-chain with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset crypto-com-chain with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset polymath with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset polymath with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset equilibria-finance with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset equilibria-finance with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset gmx with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset gmx with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset zcash with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset zcash with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset aave with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset aave with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset wrapped-nxm with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset wrapped-nxm with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset axelar with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset axelar with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset binancecoin with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset binancecoin with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset ethena with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset ethena with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset harrypotterobamasonic10in with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset harrypotterobamasonic10in with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset sui with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset sui with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset prisma-governance-token with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset prisma-governance-token with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset beam-2 with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset beam-2 with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset kamino with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset kamino with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset zebec-network with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset zebec-network with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset dog-go-to-the-moon-rune with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset dog-go-to-the-moon-rune with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset cat-in-a-dogs-world with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset cat-in-a-dogs-world with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset dogecoin with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset dogecoin with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset aurory with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset aurory with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset kekius-maximus with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset kekius-maximus with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset secret with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset secret with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset zeus-network with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset zeus-network with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset jasmycoin with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset jasmycoin with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset kyber-network-crystal with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset kyber-network-crystal with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset fantom with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset fantom with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset ether-fi with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset ether-fi with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset helium with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset helium with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset dash with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset dash with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset pancakeswap-token with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset pancakeswap-token with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset alpha-finance with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset alpha-finance with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset my-neighbor-alice with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset my-neighbor-alice with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset bubblemaps with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset bubblemaps with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset flow with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset flow with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset book-of-meme with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset book-of-meme with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset balancer with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset balancer with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset render-token with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset render-token with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset pudgy-penguins with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset pudgy-penguins with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset cosmos with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset cosmos with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset dydx with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset dydx with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset decentraland with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset decentraland with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset yield-guild-games with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset yield-guild-games with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset anzen-finance with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset anzen-finance with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset ava-ai with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset ava-ai with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset terra-luna-2 with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset terra-luna-2 with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset chill-guy with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset chill-guy with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset tron with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset tron with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset grass with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset grass with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset worldcoin-wld with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset worldcoin-wld with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset bertram-the-pomeranian with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset bertram-the-pomeranian with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset bitcoin-cash with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset bitcoin-cash with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset polkadot with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset polkadot with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset lisk with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset lisk with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset aioz-network with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset aioz-network with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset serum with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset serum with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset spx6900 with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset spx6900 with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset chainlink with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset chainlink with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset lofi-2 with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset lofi-2 with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset arweave with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset arweave with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset nunet with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset nunet with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset lido-dao with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset lido-dao with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset genesysgo-shadow with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset genesysgo-shadow with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset cookie with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset cookie with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset bittensor with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset bittensor with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset baby-doge-coin with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset baby-doge-coin with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset badger-dao with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset badger-dao with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset siren-2 with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset siren-2 with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset kryptonite with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset kryptonite with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset pepe with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset pepe with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset eigenlayer with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset eigenlayer with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset thorchain with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset thorchain with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset compound-governance-token with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset compound-governance-token with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset raydium with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset raydium with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset immutable-x with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset immutable-x with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset the-open-network with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset the-open-network with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset metacade with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset metacade with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset clearpool with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset clearpool with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset prometeus with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset prometeus with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset wibx with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset wibx with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset sei-network with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset sei-network with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset guild-of-guardians with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset guild-of-guardians with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset sturdy with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset sturdy with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset tether with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset tether with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset echelon-prime with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset echelon-prime with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset usd-coin with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset usd-coin with name 'USD:TrendMomentumUSD'
INFO: Stored backtest results in asset arpa with name 'USD:TrendMomentumUSD'

In [ ]:
# Filter for results where strategy outperforms buy & hold, sorted by outperformance
outperformance_df = results['summary'].copy()
outperformance_df['Outperformance'] = outperformance_df['Total Return (%)'] - outperformance_df['Buy & Hold Return (%)']
# Filter for positive outperformance and positive total return
# Also exclude stablecoins like USDT, USDC, TUSD
filtered_df = outperformance_df[
    ((outperformance_df['Outperformance'] > 0) | 
    (outperformance_df['Total Return (%)'] > 0)) &
    (~outperformance_df.index.isin(['USDT', 'USDC', 'TUSD']))
]
filtered_df.sort_values('Outperformance', ascending=False)[:60]

In [10]:
# Filter out assets where buy & hold Sharpe ratio is larger than the strategy's Sharpe ratio
results['asset_results'].get('fartcoin')['trades']

[{'trade_id': 1,
  'asset': 'fartcoin',
  'entry_date': Timestamp('2024-12-09 00:00:00'),
  'exit_date': Timestamp('2025-01-12 00:00:00'),
  'holding_days': 34,
  'entry_price': 0.337665,
  'exit_price': 0.768864,
  'price_return': 1.2770023544045133,
  'entry_value': 9950.0,
  'entry_cost': 50.0,
  'exit_value': 22656.17342632491,
  'exit_cost': 113.28086713162455,
  'trade_return': 1.265617342632491,
  'is_open': False},
 {'trade_id': 2,
  'asset': 'fartcoin',
  'entry_date': Timestamp('2025-01-14 00:00:00'),
  'exit_date': Timestamp('2025-01-28 00:00:00'),
  'holding_days': 14,
  'entry_price': 1.022,
  'exit_price': 0.807749,
  'price_return': -0.20963894324853227,
  'entry_value': 22430.178096397318,
  'entry_cost': 112.71446279596643,
  'exit_value': 17727.93926339221,
  'exit_cost': 88.63969631696105,
  'trade_return': -0.21359074853228954,
  'is_open': False},
 {'trade_id': 3,
  'asset': 'fartcoin',
  'entry_date': Timestamp('2025-03-22 00:00:00'),
  'exit_date': Timestamp('2025-04-30 00:00:00'),
  'holding_days': 39,
  'entry_price': 0.420938,
  'exit_price': 1.24,
  'price_return': 1.9458019945930283,
  'entry_value': 17551.103069239874,
  'entry_cost': 88.19649783537625,
  'exit_value': 51702.07442867464,
  'exit_cost': 258.5103721433732,
  'trade_return': 1.9310729846200632,
  'is_open': False}]

In [ ]:
# Get the results dataframe for Bitcoin
bitcoin_results = results['asset_results'].get('dogecoin')['results_df']

# Import plotly
import plotly.graph_objects as go

# Create a plotly figure
fig = go.Figure()

# Add traces for portfolio value and buy & hold value
fig.add_trace(
    go.Scatter(
        x=bitcoin_results.index,
        y=bitcoin_results['portfolio_value'],
        mode='lines',
        name='SOROS V1',
        line=dict(width=2, color='blue')
    )
)

fig.add_trace(
    go.Scatter(
        x=bitcoin_results.index,
        y=bitcoin_results['buy_hold_value'],
        mode='lines',
        name='Buy & Hold',
        line=dict(width=2, color='red')
    )
)

# Update layout
fig.update_layout(
    title='SOROS vs. Buy n Hold',
    xaxis_title='',
    yaxis_title='Valor da Carteira (USD)',
    legend=dict(x=0.01, y=0.99),
    hovermode='x unified',
    template='plotly_white'
)

# Show the figure
fig.show()

In [17]:
results['asset_results'].get('pendle')['metrics_comparison']

                        Strategy  Buy & Hold
Total Return           36.251700   73.665106
Max Drawdown           -0.658289   -0.724138
Sharpe Ratio            3.247126    3.858693
Sortino Ratio           5.665031    7.639710
Calmar Ratio            5.663017    7.419753
Win Rate                0.368421    0.000000
Annualized Volatility   1.148063    1.392421
Annualized Return       3.727904    5.372924
Accuracy                0.676471    0.500000
Precision               0.492620    0.494465
Recall                  1.000000    0.639618
F1 Score                0.660074    0.557752

In [ ]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

# Read the CSV file
etf = pd.read_csv('/Users/valter.rebelo/MissionControl/ETF flows - Sheet1.csv')

# Replace all '-' values with 0
etf = etf.replace('-', 0)

# Convert columns to numeric where possible
for col in etf.columns:
    if col != 'Date':  # Skip the Date column
        etf[col] = pd.to_numeric(etf[col], errors='coerce')

# Convert Date to datetime
etf['Date'] = pd.to_datetime(etf['Date'], format='%d %b %Y')
etf.set_index('Date', inplace=True)

# Get BTC price data
btc_data = analyzer.get_asset_data('bitcoin').price_data
btc_close = btc_data['close'].to_frame('BTC_Price')

# Merge ETF flows with BTC price data
merged_data = etf.join(btc_close, how='left')

# Resample to weekly data
# For ETF flows, sum the daily flows
# For BTC price, take the last price of the week
weekly_etf = etf.resample('W').sum()
weekly_btc = btc_close.resample('W').last()

# Calculate weekly BTC returns
weekly_btc['BTC_Return'] = weekly_btc['BTC_Price'].pct_change() * 100

# Merge weekly ETF flows with weekly BTC returns
weekly_data = weekly_etf.join(weekly_btc, how='left')

# Create a scatter plot with regression line
plt.figure(figsize=(10, 6))

# Get all data points except the two most recent ones
main_data = weekly_data.iloc[:-2]
# Get the most recent data point
most_recent = weekly_data.iloc[-1:]
# Get the second most recent data point
second_most_recent = weekly_data.iloc[-2:-1]

# Plot main data points
sns.regplot(x='Total', y='BTC_Return', data=main_data, 
            scatter_kws={'alpha':0.6, 'color':'blue'}, 
            line_kws={'color':'red'})

# Plot the most recent data point with a different color
plt.scatter(most_recent['Total'], most_recent['BTC_Return'], 
            color='green', s=100, alpha=0.8, label='Dado Mais Recente')

# Plot the second most recent data point with a different color
plt.scatter(second_most_recent['Total'], second_most_recent['BTC_Return'], 
            color='purple', s=100, alpha=0.8, label='Segundo Dado Mais Recente')

plt.title('Retornos do BTC e Fluxos de ETFs Semanais')
plt.xlabel('Fluxos de ETFs (Total)')
plt.ylabel('Retorno do BTC (%)')
plt.grid(True, alpha=0.3)
plt.legend()

# Calculate correlation and regression
correlation = weekly_data['Total'].corr(weekly_data['BTC_Return'])
slope, intercept, r_value, p_value, std_err = stats.linregress(
    weekly_data['Total'].dropna(), 
    weekly_data['BTC_Return'].dropna()
)

# Add correlation and regression stats to the plot
plt.annotate(f'Correlation: {correlation:.3f}\nR-squared: {r_value**2:.3f}\np-value: {p_value:.4f}', 
             xy=(0.05, 0.85), xycoords='axes fraction', 
             bbox=dict(boxstyle="round,pad=0.3", fc="white", ec="gray", alpha=0.8))

plt.tight_layout()
plt.show()

# Display the data
weekly_data

In [ ]:
results['formatted_summary']

In [ ]:
analyzer.get_asset_data('ethereum').get_price_data()

In [ ]:
import pandas as pd
df = pd.DataFrame(results['summary_data'])
df.set_index('asset_id', inplace=True)
df

In [5]:
asset_id = 'bitcoin'

In [6]:
import numpy as np
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots


# Get price data
asset_data = analyzer.get_asset_data(asset_id).price_data
close_prices = asset_data['close']

# Determine if we should show BTC charts based on asset_id
show_btc_charts = asset_id != 'bitcoin'

# Create subplots with appropriate number of rows
if show_btc_charts:
    # Show both USD and BTC charts (4 rows)
    fig = make_subplots(rows=4, cols=1, 
                        subplot_titles=("TrendMomentumBTC", 
                                       "TrendMomentumUSD", 
                                       "RSI Bullish BTC",
                                       "RSI Bullish USD"),
                        vertical_spacing=0.1,
                        shared_xaxes=True)
    num_rows = 4
else:
    # Only show USD charts (2 rows)
    fig = make_subplots(rows=2, cols=1, 
                        subplot_titles=("Momentum 1 Model", 
                                        "Momentum 2 Model"),
                        vertical_spacing=0.1,
                        shared_xaxes=True)
    num_rows = 2

# Add background price line with low alpha to all charts
for i in range(1, num_rows + 1):
    fig.add_trace(go.Scatter(
        x=close_prices.index, 
        y=close_prices, 
        mode='lines', 
        name='Price',
        line=dict(color='gray', width=1),
        opacity=0.2,
        showlegend=False if i > 1 else True
    ), row=i, col=1)

# Current row tracker for USD-only mode
current_row = 1

# 1. Donchian Ensemble BTC (only if not bitcoin)
if show_btc_charts:
    values_btc = analyzer.get_asset_data(asset_id).get_signal('TrendMomentumBTC').values
    bull_btc = values_btc == 1
    bear_btc = values_btc == 0

    green_column_btc = pd.Series(np.nan, index=close_prices.index)
    red_column_btc = pd.Series(np.nan, index=close_prices.index)

    green_column_btc[bull_btc] = close_prices[bull_btc]
    red_column_btc[bear_btc] = close_prices[bear_btc]

    fig.add_trace(go.Scatter(
        x=green_column_btc.index, 
        y=green_column_btc, 
        mode='lines', 
        name='Bullish BTC (1)',
        line=dict(color='green')
    ), row=1, col=1)

    fig.add_trace(go.Scatter(
        x=red_column_btc.index, 
        y=red_column_btc, 
        mode='lines', 
        name='Bearish/Neutral BTC (0)',
        line=dict(color='red')
    ), row=1, col=1)
    
    current_row += 1

# 2. Donchian Ensemble USD
values_usd = analyzer.get_asset_data(asset_id).get_signal('TrendMomentumUSD').values
bull_usd = values_usd == 1
bear_usd = values_usd == 0

green_column_usd = pd.Series(np.nan, index=close_prices.index)
red_column_usd = pd.Series(np.nan, index=close_prices.index)

green_column_usd[bull_usd] = close_prices[bull_usd]
red_column_usd[bear_usd] = close_prices[bear_usd]

fig.add_trace(go.Scatter(
    x=green_column_usd.index, 
    y=green_column_usd, 
    mode='lines', 
    name='Apetite por Risco',
    line=dict(color='green'),
    showlegend=current_row == 1  # Only show in legend if it's the first row
), row=current_row, col=1)

fig.add_trace(go.Scatter(
    x=red_column_usd.index, 
    y=red_column_usd, 
    mode='lines', 
    name='Aversão por Risco',
    line=dict(color='red'),
    showlegend=current_row == 1  # Only show in legend if it's the first row
), row=current_row, col=1)

current_row += 1

# 3. RSI Bullish BTC (only if not bitcoin)
if show_btc_charts:
    rsi_bullish_btc = analyzer.get_asset_data(asset_id).get_signal('RSI_Bullish_BTC').values
    
    bull_rsi_btc = rsi_bullish_btc == 1
    not_bull_rsi_btc = ~bull_rsi_btc

    green_column_rsi_btc = pd.Series(np.nan, index=close_prices.index)
    red_column_rsi_btc = pd.Series(np.nan, index=close_prices.index)

    green_column_rsi_btc[bull_rsi_btc] = close_prices[bull_rsi_btc]
    red_column_rsi_btc[not_bull_rsi_btc] = close_prices[not_bull_rsi_btc]

    fig.add_trace(go.Scatter(
        x=green_column_rsi_btc.index, 
        y=green_column_rsi_btc, 
        mode='lines', 
        name='RSI Bullish BTC (1)',
        line=dict(color='green'),
        showlegend=True
    ), row=current_row, col=1)

    fig.add_trace(go.Scatter(
        x=red_column_rsi_btc.index, 
        y=red_column_rsi_btc, 
        mode='lines', 
        name='Not RSI Bullish BTC (0)',
        line=dict(color='red'),
        showlegend=True
    ), row=current_row, col=1)
    
    current_row += 1

# 4. RSI Bullish USD
rsi_bullish_usd = analyzer.get_asset_data(asset_id).get_signal('RSI_Bullish_USD').values

bull_rsi_usd = rsi_bullish_usd == 1
not_bull_rsi_usd = ~bull_rsi_usd

green_column_rsi_usd = pd.Series(np.nan, index=close_prices.index)
red_column_rsi_usd = pd.Series(np.nan, index=close_prices.index)

green_column_rsi_usd[bull_rsi_usd] = close_prices[bull_rsi_usd]
red_column_rsi_usd[not_bull_rsi_usd] = close_prices[not_bull_rsi_usd]

fig.add_trace(go.Scatter(
    x=green_column_rsi_usd.index, 
    y=green_column_rsi_usd, 
    mode='lines', 
    name='RSI Bullish USD (1)',
    line=dict(color='green'),
    showlegend=current_row == 3  # Only show in legend if it's the first row in USD-only mode
), row=current_row, col=1)

fig.add_trace(go.Scatter(
    x=red_column_rsi_usd.index, 
    y=red_column_rsi_usd, 
    mode='lines', 
    name='Not RSI Bullish USD (0)',
    line=dict(color='red'),
    showlegend=current_row == 3  # Only show in legend if it's the first row in USD-only mode
), row=current_row, col=1)

# Update layout
fig.update_layout(
    title=f'SOROS - {asset_id.capitalize()}',
    xaxis_title='',
    legend_title='Diagnóstico',
    height=800 if asset_id == 'bitcoin' else 1600,  # Adjust height based on number of charts
    width=1000,
    template='plotly_white'
)

# Update y-axis titles for all rows
for i in range(1, num_rows + 1):
    fig.update_yaxes(title_text="Preço (USD)", row=i, col=1)

# Show the plot
fig.show()

In [7]:
analyzer.get_asset_data('dogecoin')

AssetData(asset_id='dogecoin', price_data_length=4240, signals=[DonchianEnsembleUSD, DonchianEnsembleBTC, RSI_Bullish_USD, RSI_Bullish_BTC, TrendMomentumUSD, TrendMomentumBTC], backtests=[asset_id, results_df, trades, metrics_comparison, strategy_metrics, buy_hold_metrics, parameters])

In [8]:
results['asset_results'].get(asset_id)['metrics_comparison']

                       Strategy  Buy & Hold
Total Return           2.312530    4.671411
Max Drawdown          -0.344138   -0.281149
Sharpe Ratio           1.749578    2.260663
Sortino Ratio          2.335508    3.636959
Calmar Ratio           1.954119    3.937052
Win Rate               0.538462    0.000000
Annualized Volatility  0.384371    0.489635
Annualized Return      0.672487    1.106900
Accuracy               0.680000    0.498824
Precision              0.501859    0.505576
Recall                 0.985401    0.629630
F1 Score               0.665025    0.560825

In [ ]:

import pandas as pd
def display_all_assets_signals_for_date(analyzer, date_str):
    """
    Display Donchian Ensemble, RSI, and Variance signals for all assets on a specific date
    
    Args:
        analyzer: PortfolioAnalyzer instance
        date_str: Date string in 'YYYY-MM-DD' format
    
    Returns:
        DataFrame with signal values for all assets on the specified date
    """
    # Convert date string to datetime
    date = pd.to_datetime(date_str)
    
    # List of signals to check
    signals_to_check = [
        #'DonchianEnsembleBTC',
        #'DonchianEnsembleUSD',
        'TrendMomentumBTC',
        'TrendMomentumUSD',
        #'BullHighVarianceSignalBTC',
        #'BullHighVarianceSignalUSD',
        #'BullLowVarianceSignalBTC',
       # 'BullLowVarianceSignalUSD'
    ]
    
    # Get all asset IDs
    asset_ids = sorted(list(analyzer.assets.keys()))
    
    # Create empty DataFrame with assets as rows and signals as columns
    result_df = pd.DataFrame(index=asset_ids, columns=signals_to_check)
    
    # Fill the DataFrame with signal values
    for asset_id in asset_ids:
        asset_data = analyzer.get_asset_data(asset_id)
        if asset_data is None:
            continue
            
        for signal_name in signals_to_check:
            try:
                signal_data = asset_data.get_signal(signal_name)
                if signal_data is not None:
                    # Access the signal values directly
                    # SignalData objects typically have a 'values' attribute that is a pandas Series
                    if hasattr(signal_data, 'values') and isinstance(signal_data.values, pd.Series):
                        signal_series = signal_data.values
                        if date in signal_series.index:
                            result_df.loc[asset_id, signal_name] = signal_series.loc[date]
                        else:
                            result_df.loc[asset_id, signal_name] = None
                    else:
                        result_df.loc[asset_id, signal_name] = None
                else:
                    result_df.loc[asset_id, signal_name] = None
            except Exception as e:
                print(f"Error getting {signal_name} for {asset_id} on {date_str}: {e}")
                result_df.loc[asset_id, signal_name] = None
    
    # Replace NaN with None for cleaner display
    result_df = result_df.fillna("N/A")
    
    # Add a sum column that counts the number of active signals (value of 1)
    result_df['Signal_Sum'] = result_df.apply(
        lambda row: sum(1 for val in row if val == 1), 
        axis=1
    )

    result_df = result_df.sort_index()
    
    return result_df

# Example usage - replace with your desired date
date_to_check = "2025-5-11"   # Change to your desired date

signals_df = display_all_assets_signals_for_date(analyzer, date_to_check)
print(f"Signals for all assets on {date_to_check}:")
display(signals_df.tail(60))

In [ ]:
def plot_signal_sums_through_time(analyzer, start_date=None, end_date=None, min_market_cap=1000000000, max_market_cap=None):
    """
    Create an interactive plotly lollipop chart showing signal sums for all assets through time.
    Assets are on the Y-axis and dates on the X-axis.
    
    Args:
        analyzer: The PortfolioAnalyzer instance
        start_date: Optional start date string in format 'YYYY-MM-DD'. If None, uses earliest available date.
        end_date: Optional end date string in format 'YYYY-MM-DD'. If None, uses latest available date.
        min_market_cap: Minimum market capitalization in USD to include an asset
        max_market_cap: Maximum market capitalization in USD to include an asset
    
    Returns:
        DataFrame with signal sums over time
    """
    import plotly.graph_objects as go
    import pandas as pd
    from soros_system.data.data_loader import DataLoader
    
    # Get all asset IDs
    asset_ids = list(analyzer.assets.keys())
    
    # Exclude stablecoins
    excluded_assets = ['tether', 'usd-coin']
    asset_ids = [asset_id for asset_id in asset_ids if asset_id not in excluded_assets]
    
    # Create a data loader to get tickers
    data_loader = DataLoader(
        data_path=analyzer.data_path,
        btc_data_path=analyzer.btc_data_path,
        ssr_data_path=analyzer.ssr_data_path,
        market_data_path=analyzer.market_data_path,
        asset_ids=analyzer.asset_ids
    )
    
    # Create a mapping from asset_id to ticker
    ticker_mapping = {}
    for asset_id in asset_ids:
        ticker = data_loader.get_ticker_from_id(asset_id)
        ticker_mapping[asset_id] = ticker.upper() if ticker else asset_id.upper()
    
    # Create a dictionary to store market caps
    market_caps = {}
    
    # Filter assets by market cap if specified
    if min_market_cap > 0 or max_market_cap is not None:
        filtered_asset_ids = []
        for asset_id in asset_ids:
            asset_data = analyzer.get_asset_data(asset_id)
            if asset_data is not None:
                # Try different ways to access market cap
                market_cap = None
                
                # Try to get from metadata if available
                if hasattr(asset_data, 'metadata') and asset_data.metadata:
                    market_cap = asset_data.metadata.get('market_cap')
                
                # Try to get from asset_data directly
                if market_cap is None and hasattr(asset_data, 'market_cap'):
                    market_cap = asset_data.market_cap
                
                # Try to get from price_data if available
                if market_cap is None and hasattr(asset_data, 'price_data'):
                    if 'market_cap' in asset_data.price_data.columns:
                        # Use the most recent market cap value
                        market_cap = asset_data.price_data['market_cap'].iloc[-1]
                
                # Store market cap for later sorting
                market_caps[asset_id] = market_cap if market_cap is not None else 0
                
                # Debug print to see what we're working with
                ticker = ticker_mapping.get(asset_id, asset_id)
                print(f"Asset: {ticker}, Market Cap: {market_cap}")
                
                # Check if market cap meets criteria
                meets_min_criteria = market_cap is None or market_cap >= min_market_cap
                meets_max_criteria = max_market_cap is None or (market_cap is not None and market_cap <= max_market_cap)
                
                # Include asset if market cap meets criteria
                if meets_min_criteria and meets_max_criteria:
                    filtered_asset_ids.append(asset_id)
                    if market_cap is None:
                        print(f"Warning: No market cap data for {ticker}, including it anyway")
        
        asset_ids = filtered_asset_ids
        
        if not asset_ids:
            market_cap_msg = f"with market cap >= {min_market_cap}"
            if max_market_cap is not None:
                market_cap_msg += f" and <= {max_market_cap}"
            print(f"No assets found {market_cap_msg}")
            return pd.DataFrame()
    else:
        # If no market cap filtering, still collect market caps for sorting
        for asset_id in asset_ids:
            asset_data = analyzer.get_asset_data(asset_id)
            if asset_data is not None:
                market_cap = None
                
                if hasattr(asset_data, 'metadata') and asset_data.metadata:
                    market_cap = asset_data.metadata.get('market_cap')
                
                if market_cap is None and hasattr(asset_data, 'market_cap'):
                    market_cap = asset_data.market_cap
                
                if market_cap is None and hasattr(asset_data, 'price_data'):
                    if 'market_cap' in asset_data.price_data.columns:
                        market_cap = asset_data.price_data['market_cap'].iloc[-1]
                
                market_caps[asset_id] = market_cap if market_cap is not None else 0
    
    # Determine date range
    if start_date is None or end_date is None:
        # Find the common date range across assets
        min_dates = []
        max_dates = []
        for asset_id in asset_ids:
            asset_data = analyzer.get_asset_data(asset_id)
            if asset_data is not None and hasattr(asset_data, 'price_data') and len(asset_data.price_data) > 0:
                min_dates.append(asset_data.price_data.index[0])
                max_dates.append(asset_data.price_data.index[-1])
        
        if not min_dates or not max_dates:
            print("No data available for any assets")
            return
        
        if start_date is None:
            start_date = max(min_dates).strftime('%Y-%m-%d')
        if end_date is None:
            end_date = min(max_dates).strftime('%Y-%m-%d')
    
    # Convert to datetime objects
    start_dt = pd.to_datetime(start_date)
    end_dt = pd.to_datetime(end_date)
    
    # Generate a list of dates - daily intervals as requested
    date_range = pd.date_range(start=start_dt, end=end_dt, freq='D')
    date_strings = [date.strftime('%Y-%m-%d') for date in date_range]
    
    # Create a DataFrame to store signal sums for each asset and date
    signal_sums_over_time = pd.DataFrame(index=asset_ids)
    
    # Calculate signal sums for each date
    for date_str in date_strings:
        signals_df = display_all_assets_signals_for_date(analyzer, date_str)
        signal_sums_over_time[date_str] = signals_df['Signal_Sum']
    
    # Add market cap column for sorting
    signal_sums_over_time['market_cap'] = signal_sums_over_time.index.map(lambda x: market_caps.get(x, 0))
    
    # Sort by market cap in descending order
    signal_sums_over_time = signal_sums_over_time.sort_values(by='market_cap', ascending=True)
    
    # Calculate total signal sum (but don't include market_cap column)
    signal_sums_over_time['total_sum'] = signal_sums_over_time.drop(columns=['market_cap']).sum(axis=1)
    
    # Remove the sorting columns after sorting
    signal_sums_over_time = signal_sums_over_time.drop(columns=['market_cap', 'total_sum'])
    
    # Create a new DataFrame with tickers as index
    ticker_signal_sums = pd.DataFrame(index=[ticker_mapping[asset_id] for asset_id in signal_sums_over_time.index])
    for col in signal_sums_over_time.columns:
        ticker_signal_sums[col] = signal_sums_over_time[col].values
    
    # Create color mapping function based on signal sum (scaled from 0 to 2)
    def get_color(signal_sum):
        if signal_sum == 0:
            return 'rgb(180, 50, 50)'  # darker red
        elif signal_sum == 1:
            return 'rgb(220, 180, 50)'  # darker yellow
        else:  # 2 signals
            return 'rgb(50, 150, 50)'  # darker green
    
    # Create the figure
    fig = go.Figure()
    
    # Get all dates for x-axis
    all_dates = pd.to_datetime(ticker_signal_sums.columns)
    
    # Plot all points including zero values
    for ticker in ticker_signal_sums.index:
        ticker_data = ticker_signal_sums.loc[ticker]
        
        # Create lists to store data for this ticker
        x_dates = []
        y_tickers = []
        sizes = []
        colors = []
        hover_texts = []
        
        # Process each date point
        for date, sum_val in zip(all_dates, ticker_data):
            x_dates.append(date)
            y_tickers.append(ticker)
            sizes.append(10 + sum_val * 5)  # Size based on signal sum
            colors.append(get_color(sum_val))
            hover_texts.append(f"Date: {date.strftime('%Y-%m-%d')}<br>Ticker: {ticker}<br>Signal Sum: {sum_val}")
        
        # Add scatter plot (dots)
        fig.add_trace(go.Scatter(
            x=x_dates,
            y=y_tickers,
            mode='markers',
            marker=dict(
                size=sizes,
                color=colors,
                line=dict(width=1, color='rgba(0,0,0,0.5)')
            ),
            name=ticker,
            showlegend=False,
            hoverinfo='text',
            hovertext=hover_texts
        ))
    
    # Add a color legend
    for i, (sum_val, color_desc) in enumerate([
        (0, "0 signals (red)"),
        (1, "1 signal (yellow)"),
        (2, "2 signals (green)")
    ]):
        fig.add_trace(go.Scatter(
            x=[None],
            y=[None],
            mode='markers',
            marker=dict(size=10 + sum_val * 5, color=get_color(sum_val)),
            name=color_desc,
            showlegend=True
        ))
    
    # Update layout
    title_text = "Signal Sums for Assets Through Time (Ordered by Market Cap)"
    if min_market_cap > 0 or max_market_cap is not None:
        title_text += f" (Market Cap"
        if min_market_cap > 0:
            title_text += f" >= {min_market_cap:,} USD"
        if max_market_cap is not None:
            if min_market_cap > 0:
                title_text += " and"
            title_text += f" <= {max_market_cap:,} USD"
        title_text += ")"
        
    fig.update_layout(
        title=title_text,
        xaxis_title="Date",
        yaxis_title="Tickers",
        height=max(800, len(ticker_signal_sums) * 20),  # Dynamic height based on number of assets
        width=1200,  # Fixed width for better display
        yaxis=dict(
            categoryorder='array',
            categoryarray=ticker_signal_sums.index,  # Order by market cap (already sorted)
        ),
        xaxis=dict(
            type='date',
            tickformat='%Y-%m-%d',
            tickangle=45,
        ),
        legend_title="Signal Sum Legend",
        hovermode="closest",
        showlegend=True,
        margin=dict(l=150, r=50, t=50, b=100)  # Add margin for ticker names
    )
    
    fig.show()
    
    return ticker_signal_sums

# Example usage
signal_data_over_time = plot_signal_sums_through_time(
    analyzer, 
    start_date="2025-06-01",  # Change to your desired start date
    end_date="2025-07-23",    # Change to your desired end date
    min_market_cap = 100000000,
    max_market_cap = None

)

In [ ]:

btc = results['asset_results'].get('bitcoin')['results_df']
btc

In [ ]:
import pandas as pd
import numpy as np

def apply_triple_barrier_labeling(df, profit_factor=2, stop_factor=2, time_window=7, stdev_window=20, debug=False):
    """
    Apply triple barrier method labeling to a trading dataframe with the following rules:
    - Positive Label (+1): Upper barrier (profit target) is breached first
    - Negative Label (-1): Lower barrier (stop loss) is breached first
    - Neutral Label (0): Time barrier expires without hitting either barrier
    
    Parameters:
    -----------
    df : pandas.DataFrame
        The dataframe containing trading data
    profit_factor : float, default=2
        Multiplier for standard deviation to determine profit target
    stop_factor : float, default=2
        Multiplier for standard deviation to determine stop loss
    time_window : int, default=7
        Number of days to look forward for label determination
    stdev_window : int, default=20
        Window size for standard deviation calculation
    debug : bool, default=False
        Whether to print debugging information
        
    Returns:
    --------
    pandas.DataFrame
        The original dataframe with additional 'triple_barrier_label' column
    """
    # Make a copy of the dataframe to avoid modifying the original
    df_copy = df.copy()
    
    # Calculate rolling standard deviation
    df_copy['rolling_std'] = df_copy['close'].rolling(window=stdev_window).std()
    
    # Initialize the label column
    df_copy['triple_barrier_label'] = np.nan
    
    # Debugging counters
    if debug:
        skipped_beginning = 0
        skipped_end = 0
        processed = 0
        labels_positive = 0
        labels_negative = 0
        labels_neutral = 0
    
    # Find rows where position changes (actual trade entries)
    position_entries = []
    
    # Look for either:
    # 1. Where position changes from 0 to non-zero
    if 'position' in df_copy.columns:
        for i in range(1, len(df_copy)):
            if df_copy['position'].iloc[i-1] == 0 and df_copy['position'].iloc[i] != 0:
                position_entries.append(i)
    
    # 2. Or where trade_executed is True
    if 'trade_executed' in df_copy.columns:
        for i in range(len(df_copy)):
            if df_copy['trade_executed'].iloc[i] == True:
                if i not in position_entries:
                    position_entries.append(i)
    
    # 3. Or where final_decision_shifted is 1 (assuming this indicates a trade signal)
    for i in range(len(df_copy)):
        if not pd.isna(df_copy['final_decision_shifted'].iloc[i]) and df_copy['final_decision_shifted'].iloc[i] == 1:
            if i not in position_entries:
                position_entries.append(i)
    
    if debug:
        print(f"Found {len(position_entries)} potential trade entry points")
    
    # Loop through each identified trade entry
    for i in position_entries:
        # Skip if we're too close to the beginning or end of the dataframe
        if i < stdev_window:
            if debug: skipped_beginning += 1
            continue
            
        if i >= len(df_copy) - 1:
            if debug: skipped_end += 1
            continue
        
        # Calculate profit target and stop loss
        entry_price = df_copy['open'].iloc[i]
        std_dev = df_copy['rolling_std'].iloc[i-1]  # Using previous day's std for decision
        
        # Skip if std_dev is NaN or 0
        if pd.isna(std_dev) or std_dev == 0:
            if debug: print(f"Warning: Standard deviation is {std_dev} at index {i}")
            continue
        
        profit_target = entry_price + profit_factor * std_dev
        stop_loss = entry_price - stop_factor * std_dev
        
        # Look forward up to time_window days
        label = None
        exit_day = min(i+time_window, len(df_copy)-1)
        
        for forward_idx in range(i+1, exit_day+1):
            current_price = df_copy['close'].iloc[forward_idx]
            
            # Check if profit target is hit first
            if current_price >= profit_target:
                label = 1  # Positive label
                if debug: labels_positive += 1
                break
                
            # Check if stop loss is hit first
            if current_price <= stop_loss:
                label = -1  # Negative label
                if debug: labels_negative += 1
                break
        
        # If neither barrier is hit within the time window, assign neutral label
        if label is None:
            label = 0  # Neutral label - time barrier hit first
            if debug: labels_neutral += 1
        
        # Assign the label
        df_copy.loc[df_copy.index[i], 'triple_barrier_label'] = label
        
        if debug: processed += 1
    
    if debug:
        print(f"Skipped (beginning): {skipped_beginning}")
        print(f"Skipped (end): {skipped_end}")
        print(f"Processed entries: {processed}")
        print(f"Positive labels (+1): {labels_positive}")
        print(f"Negative labels (-1): {labels_negative}")
        print(f"Neutral labels (0): {labels_neutral}")
        print(f"Non-NaN labels: {df_copy['triple_barrier_label'].notna().sum()}")
    
    return df_copy

# Example usage:
labeled_df = apply_triple_barrier_labeling(btc)
labeled_df

In [ ]:
# Import plotly if not already imported
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Create a figure with two subplots stacked vertically
fig = make_subplots(rows=2, cols=1, shared_xaxes=True, vertical_spacing=0.1, 
                    subplot_titles=('BTC Price', 'Trading Signals'))

# Plot BTC price in the top subplot
fig.add_trace(
    go.Scatter(x=labeled_df.index, y=labeled_df['close'], name='BTC Price', line=dict(color='blue')),
    row=1, col=1
)

# Plot position and triple barrier label in the bottom subplot
fig.add_trace(
    go.Scatter(x=labeled_df.index, y=labeled_df['position'], name='Position', line=dict(color='green')),
    row=2, col=1
)
fig.add_trace(
    go.Scatter(x=labeled_df.index, y=labeled_df['triple_barrier_label'], name='Triple Barrier Label', 
               line=dict(color='red')),
    row=2, col=1
)

# Update layout
fig.update_layout(
    height=800, 
    width=1200,
    showlegend=True,
    legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1)
)

# Update y-axis labels
fig.update_yaxes(title_text="Price (USD)", row=1, col=1)
fig.update_yaxes(title_text="Signal Value", row=2, col=1)
fig.update_xaxes(title_text="Date", row=2, col=1)

# Add grid lines
fig.update_xaxes(showgrid=True, gridwidth=1, gridcolor='LightGrey')
fig.update_yaxes(showgrid=True, gridwidth=1, gridcolor='LightGrey')

# Show the figure
fig.show()

In [ ]:
def create_returns_df_from_signals(analyzer, signal_df, min_days=90, min_market_cap=1000000000, max_market_cap=None):
    """
    Create a DataFrame of returns for assets that have a signal sum >= 3
    and have at least the minimum number of days of price data.
    
    Args:
        analyzer: PortfolioAnalyzer instance
        signal_df: DataFrame with signal values and Signal_Sum column
        min_days: Minimum number of days of price data required (default: 365)
        min_market_cap: Minimum market capitalization in USD to include an asset (default: 0)
        max_market_cap: Maximum market capitalization in USD to include an asset (default: None)
    
    Returns:
        DataFrame with daily returns for qualifying assets
    """
    # Filter assets with signal sum >= 3
    # For bitcoin, we only require a signal sum of 2, for all other assets we require 3
    bitcoin_assets = signal_df[
        (signal_df.index == 'bitcoin') & (signal_df['Signal_Sum'] >= 2)
    ].index.tolist()
    other_assets = signal_df[
        (signal_df.index != 'bitcoin') & (signal_df['Signal_Sum'] >= 4)
    ].index.tolist()
    qualified_assets = bitcoin_assets + other_assets
    
    # Dictionary to store returns series
    returns_dict = {}
    
    # Process each qualified asset
    for asset_id in qualified_assets:
        asset_data = analyzer.get_asset_data(asset_id)
        
        # Skip if asset data is None
        if asset_data is None:
            continue
            
        # Check market cap if filtering is enabled
        if min_market_cap > 0 or max_market_cap is not None:
            market_cap = None
            
            # Try to get from metadata if available
            if hasattr(asset_data, 'metadata') and asset_data.metadata:
                market_cap = asset_data.metadata.get('market_cap')
            
            # Try to get from asset_data directly
            if market_cap is None and hasattr(asset_data, 'market_cap'):
                market_cap = asset_data.market_cap
            
            # Try to get from price_data if available
            if market_cap is None and hasattr(asset_data, 'price_data'):
                if 'market_cap' in asset_data.price_data.columns:
                    # Use the most recent market cap value
                    market_cap = asset_data.price_data['market_cap'].iloc[-1]
            
            # Skip if market cap doesn't meet criteria
            if market_cap is not None:
                if (min_market_cap > 0 and market_cap < min_market_cap) or \
                   (max_market_cap is not None and market_cap > max_market_cap):
                    print(f"Skipping {asset_id}: Market cap {market_cap} outside range [{min_market_cap}, {max_market_cap or 'inf'}]")
                    continue
            elif min_market_cap > 0:
                print(f"Skipping {asset_id}: No market cap data available")
                continue
            
        # Get price data
        try:
            price_data = asset_data.get_price_data()
            
            if price_data is None or len(price_data) < min_days:
                print(f"Skipping {asset_id}: Only has {len(price_data) if price_data is not None else 0} days of data (minimum required: {min_days})")
                continue
                
            if 'close' in price_data.columns:
                # Calculate daily returns
                returns = price_data['close'].pct_change().dropna()
                
                # Make sure the index is unique before adding to the dictionary
                if returns.index.is_unique:
                    returns_dict[asset_id] = returns
                else:
                    # Handle duplicate indices by keeping the first occurrence
                    print(f"Warning: {asset_id} has duplicate dates. Keeping first occurrence.")
                    returns = returns[~returns.index.duplicated(keep='first')]
                    returns_dict[asset_id] = returns
            else:
                print(f"Skipping {asset_id}: Price data missing 'close' column")
        except Exception as e:
            print(f"Error processing {asset_id}: {e}")
    
    # Create DataFrame from the dictionary
    if returns_dict:
        # Create an empty DataFrame with a unique index that spans all series
        all_dates = sorted(set().union(*[returns.index for returns in returns_dict.values()]))
        returns_df = pd.DataFrame(index=all_dates)
        
        # Add each series to the DataFrame
        for asset_id, returns in returns_dict.items():
            returns_df[asset_id] = returns
            
        print(f"Created returns DataFrame with {len(returns_df.columns)} assets")
        return returns_df
    else:
        print("No qualifying assets found")
        return pd.DataFrame()

# Example usage
# Get signals for a specific date
date_to_check = "2024-11-25"  # Change to your desired date
signals_df = display_all_assets_signals_for_date(analyzer, date_to_check)

# Create returns DataFrame for assets with signal sum >= 3
returns_df = create_returns_df_from_signals(analyzer, signals_df)

# Display the first few rows of the returns DataFrame
if not returns_df.empty:
    display(returns_df.tail())
    
    # Display basic statistics
    print(f"\nReturns DataFrame Shape: {returns_df.shape}")
    print(f"Date Range: {returns_df.index.min()} to {returns_df.index.max()}")

In [ ]:
def hrp_portfolio(returns_df):
    """
    Compute HRP portfolio allocations for a DataFrame of asset returns.

    Args:
        returns_df (pd.DataFrame): DataFrame with dates as rows, assets as columns,
                                   and daily returns as values (e.g., shape: (n_days, n_assets)).

    Returns:
        pd.DataFrame: Portfolio weights for each asset (index: asset names, column: 'weights').
    """
    # Step 1: Compute the covariance matrix and convert to NumPy array
    cov_matrix = returns_df.cov().values  # Convert to NumPy array
    
    # Ensure positive definiteness
    min_eig = np.min(np.real(np.linalg.eigvals(cov_matrix)))
    if min_eig <= 0:
        cov_matrix += (abs(min_eig) + 1e-5) * np.eye(cov_matrix.shape[0])

    # Step 2: Compute the correlation-based distance matrix
    std = np.sqrt(np.diag(cov_matrix))
    std[std == 0] = 1e-10  # Prevent division by zero
    corr = cov_matrix / np.outer(std, std)
    corr = np.clip(corr, -1, 1)  # Clip to valid range
    np.fill_diagonal(corr, 1)    # Ensure diagonal is 1 (now works since corr is a NumPy array)
    corr = (corr + corr.T) / 2   # Force symmetry

    distance = np.sqrt(np.maximum(0.5 * (1 - corr), 0))
    np.fill_diagonal(distance, 0)  # Ensure diagonal is 0
    distance = (distance + distance.T) / 2  # Force symmetry

    # Step 3: Perform hierarchical clustering
    dist_condensed = squareform(distance)
    clusters = linkage(dist_condensed, method='single')

    # Step 4: Allocate weights using HRP
    assets = returns_df.columns
    n = len(assets)
    weights = pd.Series(1.0, index=assets)
    clusters_dict = {i: [i] for i in range(n)}

    for i in range(n - 1):
        cluster1 = clusters_dict[int(clusters[i, 0])]
        cluster2 = clusters_dict[int(clusters[i, 1])]
        
        # Compute cluster variances (convert to NumPy array for slicing)
        cov_matrix_df = returns_df.cov()  # Keep as DataFrame for iloc indexing
        cluster_cov1 = cov_matrix_df.iloc[cluster1, cluster1].values
        cluster_cov2 = cov_matrix_df.iloc[cluster2, cluster2].values
        w1 = np.ones(len(cluster1)) / len(cluster1)
        w2 = np.ones(len(cluster2)) / len(cluster2)
        var1 = max(w1.T @ cluster_cov1 @ w1, 1e-10)
        var2 = max(w2.T @ cluster_cov2 @ w2, 1e-10)
        
        # Allocate weights inversely proportional to variance
        weight1 = 1 / var1
        weight2 = 1 / var2
        alpha = weight1 / (weight1 + weight2)
        
        weights.iloc[cluster1] *= alpha
        weights.iloc[cluster2] *= (1 - alpha)
        
        # Update clusters
        new_cluster_id = n + i
        clusters_dict[new_cluster_id] = cluster1 + cluster2

    # Normalize weights
    weights = weights / weights.sum()
    return pd.DataFrame(weights, columns=['weights'])

In [ ]:
hrp_portfolio(returns_df).sort_values(by='weights', ascending=False).head(10)