In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime, timedelta
import warnings
warnings.filterwarnings('ignore')

# Import the refactored TrendAnalyzer
from soros_system.main import TrendAnalyzer

# Define asset IDs and paths to your data
asset_ids = [
    'bitcoin', 'ethereum', 'binancecoin', 'solana'
    # Add more assets as needed
]

data_path='/Users/valter.rebelo/MissionControl/data/micro/candleData/'
btc_data_path='/Users/valter.rebelo/MissionControl/data/micro/candleData/bitcoin_candles.csv'
ssr_data_path='/Users/valter.rebelo/MissionControl/data/onchainData/BTC_SSR.csv'


from soros_system.analysis.markov import MarkovAnalyzer

# Create the MarkovAnalyzer instance first
markov_analyzer = MarkovAnalyzer(markov_model='20250325_144631')


# Initialize the TrendAnalyzer
analyzer = TrendAnalyzer(
    asset_ids=asset_ids,
    data_path=data_path,
    btc_data_path=btc_data_path,
    lookback_days='all',
    ssr_data_path=ssr_data_path,        
    markov_analyzer=markov_analyzer
)

# Analyze all assets
results = analyzer.analyze_multiple_assets()

Analyzing assets:   0%|          | 0/4 [00:00<?, ?it/s]

Classifying bitcoin:   0%|          | 0/1 [00:00<?, ?it/s]

Creating trend data for bitcoin:   0%|          | 0/2 [00:00<?, ?it/s]

Classifying ethereum:   0%|          | 0/1 [00:00<?, ?it/s]

Creating trend data for ethereum:   0%|          | 0/2 [00:00<?, ?it/s]

Classifying binancecoin:   0%|          | 0/1 [00:00<?, ?it/s]

Creating trend data for binancecoin:   0%|          | 0/2 [00:00<?, ?it/s]

Classifying solana:   0%|          | 0/1 [00:00<?, ?it/s]

Creating trend data for solana:   0%|          | 0/2 [00:00<?, ?it/s]

Computing metrics:   0%|          | 0/4 [00:00<?, ?it/s]

Column Overall_Trend_BTC not found in data for bitcoin. Skipping BTC trend metrics calculation.

In [ ]:
analyzer.get_asset_processed_data('ethereum')

,date,open,high,low,close,ethereum_btc_open,ethereum_btc_high,ethereum_btc_low,ethereum_btc,asset_id,...,MA252_ethereum_btc,RoC252_ethereum_btc,MA365_ethereum_btc,RoC365_ethereum_btc,Trend_Short Term_BTC,Trend_Medium Term_BTC,Trend_Long Term_BTC,Overall_Trend_BTC,returns_usd,returns_btc
0,2015-08-07,2.830000,2.830000,2.830000,2.830000,0.010161,0.010161,0.010161,0.010161,ethereum,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2015-08-08,1.330000,1.330000,1.330000,1.330000,0.005119,0.005119,0.005119,0.005119,ethereum,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.530035,-0.496190
2,2015-08-09,1.008793,1.008793,1.008793,1.008793,0.003816,0.003816,0.003816,0.003816,ethereum,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.241509,-0.254536
3,2015-08-10,0.687586,0.687586,0.687586,0.687586,0.002609,0.002609,0.002609,0.002609,ethereum,...,NaN,NaN,NaN,NaN,-2.0,NaN,NaN,NaN,-0.318407,-0.316442
4,2015-08-11,1.067000,1.067000,1.067000,1.067000,0.003954,0.003954,0.003954,0.003954,ethereum,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.551806,0.515637
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3519,2025-03-26,2066.470000,2078.190000,1985.690000,2009.880000,0.023637,0.023544,0.023126,0.023112,ethereum,...,0.036296,-56.265967,0.041039,-54.900661,-1.0,-2.0,-2.0,-2.0,-0.028386,-0.022129
3520,2025-03-27,2009.340000,2034.400000,1989.020000,2003.300000,0.023119,0.023178,0.023164,0.022967,ethereum,...,0.036174,-57.155703,0.040963,-54.504916,-2.0,-2.0,-2.0,-2.0,-0.003274,-0.006313
3521,2025-03-28,2002.150000,2015.310000,1866.540000,1896.920000,0.022957,0.023032,0.022325,0.022486,ethereum,...,0.036055,-57.217808,0.040887,-55.340206,-2.0,-2.0,-2.0,-2.0,-0.053102,-0.020910
3522,2025-03-29,1896.320000,1911.020000,1804.600000,1829.270000,0.022486,0.022605,0.022069,0.022125,ethereum,...,0.035934,-57.791234,0.040810,-56.003656,-2.0,-2.0,-2.0,-2.0,-0.035663,-0.016068
3523,2025-03-30,1827.770000,1847.220000,1782.690000,1805.340000,0.022127,0.022123,0.021859,0.021921,ethereum,...,0.035816,-57.754938,0.040732,-56.439635,-2.0,-2.0,-2.0,-2.0,-0.013082,-0.009211

In [4]:
latest_trends = analyzer.get_latest_trends()
latest_trends

,ticker,date,close,Trend_Short Term_USD,Trend_Medium Term_USD,Trend_Long Term_USD,Overall_Trend_USD,Trend_Short Term_BTC,Trend_Medium Term_BTC,Trend_Long Term_BTC,Overall_Trend_BTC
0,BTC,2025-03-30,82356.00,-2.0,-1.0,0.0,-1.0,NaN,NaN,NaN,NaN
1,ETH,2025-03-30,1805.34,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0
2,BNB,2025-03-30,601.47,-2.0,0.0,0.0,-1.0,0.0,2.0,0.0,1.0
3,SOL,2025-03-30,124.58,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0

In [5]:
# Get processed data for Cardano
ada_processed = analyzer.get_asset_processed_data('ethereum')
print(ada_processed.columns)  # See available columns including trend classifications

Index(['date', 'open', 'high', 'low', 'close', 'ethereum_btc_open',
       'ethereum_btc_high', 'ethereum_btc_low', 'ethereum_btc', 'asset_id',
       'MA3_close', 'RoC3_close', 'MA5_close', 'RoC5_close', 'MA7_close',
       'RoC7_close', 'MA14_close', 'RoC14_close', 'MA21_close', 'RoC21_close',
       'MA30_close', 'RoC30_close', 'MA45_close', 'RoC45_close', 'MA63_close',
       'RoC63_close', 'MA84_close', 'RoC84_close', 'MA100_close',
       'RoC100_close', 'MA120_close', 'RoC120_close', 'MA150_close',
       'RoC150_close', 'MA200_close', 'RoC200_close', 'MA252_close',
       'RoC252_close', 'MA365_close', 'RoC365_close', 'Trend_Short Term_USD',
       'Trend_Medium Term_USD', 'Trend_Long Term_USD', 'Overall_Trend_USD',
       'MA3_ethereum_btc', 'RoC3_ethereum_btc', 'MA5_ethereum_btc',
       'RoC5_ethereum_btc', 'MA7_ethereum_btc', 'RoC7_ethereum_btc',
       'MA14_ethereum_btc', 'RoC14_ethereum_btc', 'MA21_ethereum_btc',
       'RoC21_ethereum_btc', 'MA30_ethereum_btc', 'RoC30_ethereum_btc',
       'MA45_ethereum_btc', 'RoC45_ethereum_btc', 'MA63_ethereum_btc',
       'RoC63_ethereum_btc', 'MA84_ethereum_btc', 'RoC84_ethereum_btc',
       'MA100_ethereum_btc', 'RoC100_ethereum_btc', 'MA120_ethereum_btc',
       'RoC120_ethereum_btc', 'MA150_ethereum_btc', 'RoC150_ethereum_btc',
       'MA200_ethereum_btc', 'RoC200_ethereum_btc', 'MA252_ethereum_btc',
       'RoC252_ethereum_btc', 'MA365_ethereum_btc', 'RoC365_ethereum_btc',
       'Trend_Short Term_BTC', 'Trend_Medium Term_BTC', 'Trend_Long Term_BTC',
       'Overall_Trend_BTC', 'returns_usd', 'returns_btc'],
      dtype='object')

In [6]:
info = analyzer.get_asset_information('ethereum')
short_term_matrix = info.get('transition_matrix_usd_short_term')
medium_term_matrix = info.get('transition_matrix_usd_medium_term')
long_term_matrix = info.get('transition_matrix_usd_long_term')
overall_matrix = info.get('transition_matrix_usd_overall')

In [ ]:
info.get('transition_matrix_btc_short_term')

In [8]:
#['asset_id', 'raw_data', 'processed_data', 'consolidated_trend_metrics_usd', 'consolidated_trend_metrics_btc', 'trend_metrics_usd', 
# 'trend_metrics_btc', 'trend_metrics_usd_short_term', 'trend_metrics_usd_medium_term', 'trend_metrics_usd_long_term', 
# 'trend_metrics_btc_short_term', 'trend_metrics_btc_medium_term', 'trend_metrics_btc_long_term', 'transition_matrix_usd_short_term', 
# 'transition_matrix_usd_medium_term', 'transition_matrix_usd_long_term', 'transition_matrix_usd_overall', 'transition_matrix_btc_short_term',
# 'transition_matrix_btc_medium_term', 'transition_matrix_btc_long_term', 'transition_matrix_btc_overall'])

In [ ]:
info = analyzer.get_asset_information('solana')
info.get('transition_matrix_usd')
info.get('consolidated_trend_metrics_usd')

In [ ]:
info.get('transition_matrix_btc_short_term')

In [ ]:
analyzer.delete_portfolio('btc_trend_follower')

In [ ]:
analyzer.delete_portfolio('alt_example')

In [ ]:
btc_trend_performance = analyzer.compare_trend_performance('bitcoin')
print(btc_trend_performance)

In [ ]:
analyzer.create_portfolio(
    'btc_trend_follower',
    #btc_trend_gating=1,
    usd_conditions={'Short Term': [1,2], 'Overall': [1,2]},
    #btc_conditions={'Short Term': ['Neutral', 'Weak Bull', 'Strong Bull']},
    rsi_conditions_usd=True,
    use_volatility_filter=True,
    volatility_weight=1,
    alt_cost=0.005,
    btc_cost=0.001,
    btc_only=True
)

analyzer.create_portfolio(
    'alt_example',
    #btc_trend_gating=1,
    usd_conditions={'Short Term': [1,2], 'Overall': [1,2]},
    btc_conditions={'Short Term': [1,2]},
    rsi_conditions_usd=True,
    use_volatility_filter=True,
    volatility_weight=1,
    alt_cost=0.005,
    btc_cost=0.001,
    btc_only=False
)

In [ ]:
analyzer.list_portfolios()

In [ ]:
# ['asset_id', 'raw_data', 'processed_data', 'trend_metrics_usd', 'trend_metrics_btc', 'transition_matrix_usd', 'transition_matrix_btc'])
portfolio_info = analyzer.get_portfolio_details('btc_trend_follower')
print(portfolio_info)

In [ ]:
# Get asset-specific performance metrics
backtest_results = analyzer.backtest_portfolio('btc_trend_follower', '2022-01-01', '2024-12-31')
#asset_metrics = analyzer.get_portfolio_asset_metrics(backtest_results)
#print(asset_metrics)

In [ ]:
# Get signals from backtest results
backtest_results = analyzer.backtest_portfolio('btc_trend_follower', '2022-01-01', '2025-12-31')
backtest_results

In [ ]:
backtest_results.get('strategy_metrics'), backtest_results.get('buy_hold_metrics')

In [26]:
backtest_results.get('trades_metrics')

In [ ]:
#['results_df', 'signals_df', 'metrics_df', 'trades_df', 'trade_metrics', 'strategy_metrics', 'buy_hold_metrics']
backtest_results.get('trades_df')

In [ ]:
backtest_results.get('signals_df')['volatility_signal'].plot()

In [ ]:
# Get table of recommended assets
backtest_results = analyzer.backtest_portfolio('btc_trend_follower', '2022-01-01', '2022-12-31')
recommendations = analyzer.get_recommended_assets_table(backtest_results)
print(recommendations.head())

In [ ]:
# Plot trend distribution for Bitcoin
fig = analyzer.plot_trend_distribution('bitcoin', trend_type='USD', show_plot=True)

In [ ]:
# Plot the transition matrix for Ethereum
fig = analyzer.plot_transition_matrix('bitcoin', trend_type='USD', trend_term='Medium Term')

In [15]:
analyzer.clear_cache()

In [ ]:
analyzer.get_ticker_from_id('pussifer')