In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime, timedelta
import warnings
warnings.filterwarnings('ignore')

# Import the refactored TrendAnalyzer
from soros_system.main import TrendAnalyzer

# Define asset IDs and paths to your data
asset_ids = [
    'bitcoin', 'ethereum', 'solana', 'ripple'
    # Add more assets as needed
]

data_path='/Users/valter.rebelo/MissionControl/data/micro/candleData/'
btc_data_path='/Users/valter.rebelo/MissionControl/data/micro/candleData/bitcoin_candles.csv'
ssr_data_path='/Users/valter.rebelo/MissionControl/data/onchainData/BTC_SSR.csv'


from soros_system.analysis.markov import MarkovAnalyzer

# Create the MarkovAnalyzer instance first
markov_analyzer = MarkovAnalyzer(markov_model='20250325_144631')


# Initialize the TrendAnalyzer
analyzer = TrendAnalyzer(
    asset_ids=asset_ids,
    data_path=data_path,
    btc_data_path=btc_data_path,
    lookback_days='all',
    ssr_data_path=ssr_data_path,        
    markov_analyzer=markov_analyzer
)

# Analyze all assets
results = analyzer.analyze_multiple_assets()

Analyzing assets:   0%|          | 0/4 [00:00<?, ?it/s]

Classifying bitcoin:   0%|          | 0/1 [00:00<?, ?it/s]

Creating trend data for bitcoin:   0%|          | 0/2 [00:00<?, ?it/s]

Classifying ethereum:   0%|          | 0/1 [00:00<?, ?it/s]

Creating trend data for ethereum:   0%|          | 0/2 [00:00<?, ?it/s]

Classifying solana:   0%|          | 0/1 [00:00<?, ?it/s]

Creating trend data for solana:   0%|          | 0/2 [00:00<?, ?it/s]

Classifying ripple:   0%|          | 0/1 [00:00<?, ?it/s]

Creating trend data for ripple:   0%|          | 0/2 [00:00<?, ?it/s]

Computing metrics:   0%|          | 0/4 [00:00<?, ?it/s]

Column overall_trend_BTC not found in data for bitcoin. Skipping BTC trend metrics calculation.

In [2]:
analyzer.get_asset_processed_data('ethereum')

,date,open,high,low,close,ethereum_btc_open,ethereum_btc_high,ethereum_btc_low,ethereum_btc,asset_id,...,MA365_ethereum_btc,RoC365_ethereum_btc,short_term_trend_BTC,medium_term_trend_BTC,long_term_trend_BTC,overall_trend_BTC,RSI_Signal_28_USD,RSI_Signal_28_BTC,returns_usd,returns_btc
0,2015-08-07,2.830000,2.830000,2.830000,2.830000,0.010161,0.010161,0.010161,0.010161,ethereum,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2015-08-08,1.330000,1.330000,1.330000,1.330000,0.005119,0.005119,0.005119,0.005119,ethereum,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.530035,-0.496190
2,2015-08-09,1.008793,1.008793,1.008793,1.008793,0.003816,0.003816,0.003816,0.003816,ethereum,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.241509,-0.254536
3,2015-08-10,0.687586,0.687586,0.687586,0.687586,0.002609,0.002609,0.002609,0.002609,ethereum,...,NaN,NaN,-2.0,NaN,NaN,NaN,NaN,NaN,-0.318407,-0.316442
4,2015-08-11,1.067000,1.067000,1.067000,1.067000,0.003954,0.003954,0.003954,0.003954,ethereum,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.551806,0.515637
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3519,2025-03-26,2066.470000,2078.190000,1985.690000,2009.880000,0.023637,0.023544,0.023126,0.023112,ethereum,...,0.041039,-54.900661,-1.0,-2.0,-2.0,-2.0,-1.0,-1.0,-0.028386,-0.022129
3520,2025-03-27,2009.340000,2034.400000,1989.020000,2003.300000,0.023119,0.023178,0.023164,0.022967,ethereum,...,0.040963,-54.504916,-2.0,-2.0,-2.0,-2.0,-1.0,-1.0,-0.003274,-0.006313
3521,2025-03-28,2002.150000,2015.310000,1866.540000,1896.920000,0.022957,0.023032,0.022325,0.022486,ethereum,...,0.040887,-55.340206,-2.0,-2.0,-2.0,-2.0,-1.0,-1.0,-0.053102,-0.020910
3522,2025-03-29,1896.320000,1911.020000,1804.600000,1829.270000,0.022486,0.022605,0.022069,0.022125,ethereum,...,0.040810,-56.003656,-2.0,-2.0,-2.0,-2.0,-1.0,-1.0,-0.035663,-0.016068
3523,2025-03-30,1827.770000,1847.220000,1782.690000,1805.340000,0.022127,0.022123,0.021859,0.021921,ethereum,...,0.040732,-56.439635,-2.0,-2.0,-2.0,-2.0,-1.0,-1.0,-0.013082,-0.009211

In [3]:
latest_trends = analyzer.get_latest_signals()
latest_trends

,ticker,asset_id,date,short_term_trend_USD,medium_term_trend_USD,long_term_trend_USD,overall_trend_USD,rsi_signal_28_USD,short_term_trend_BTC,medium_term_trend_BTC,long_term_trend_BTC,overall_trend_BTC,rsi_signal_28_BTC
0,BTC,bitcoin,2025-03-30,-2.0,-1.0,0.0,-1.0,-1.0,NaN,NaN,NaN,NaN,NaN
1,ETH,ethereum,2025-03-30,-2.0,-2.0,-2.0,-2.0,-1.0,-2.0,-2.0,-2.0,-2.0,-1.0
2,SOL,solana,2025-03-30,-2.0,-2.0,-2.0,-2.0,-1.0,-2.0,-2.0,-2.0,-2.0,-1.0
3,XRP,ripple,2025-03-30,-2.0,-1.0,0.0,-1.0,-1.0,-1.0,-1.0,0.0,-1.0,-1.0

In [4]:
# Get processed data for Cardano
eth_processed = analyzer.get_asset_processed_data('ethereum')
eth_processed  # See available columns including trend classifications

,date,open,high,low,close,ethereum_btc_open,ethereum_btc_high,ethereum_btc_low,ethereum_btc,asset_id,...,MA365_ethereum_btc,RoC365_ethereum_btc,short_term_trend_BTC,medium_term_trend_BTC,long_term_trend_BTC,overall_trend_BTC,RSI_Signal_28_USD,RSI_Signal_28_BTC,returns_usd,returns_btc
0,2015-08-07,2.830000,2.830000,2.830000,2.830000,0.010161,0.010161,0.010161,0.010161,ethereum,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2015-08-08,1.330000,1.330000,1.330000,1.330000,0.005119,0.005119,0.005119,0.005119,ethereum,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.530035,-0.496190
2,2015-08-09,1.008793,1.008793,1.008793,1.008793,0.003816,0.003816,0.003816,0.003816,ethereum,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.241509,-0.254536
3,2015-08-10,0.687586,0.687586,0.687586,0.687586,0.002609,0.002609,0.002609,0.002609,ethereum,...,NaN,NaN,-2.0,NaN,NaN,NaN,NaN,NaN,-0.318407,-0.316442
4,2015-08-11,1.067000,1.067000,1.067000,1.067000,0.003954,0.003954,0.003954,0.003954,ethereum,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.551806,0.515637
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3519,2025-03-26,2066.470000,2078.190000,1985.690000,2009.880000,0.023637,0.023544,0.023126,0.023112,ethereum,...,0.041039,-54.900661,-1.0,-2.0,-2.0,-2.0,-1.0,-1.0,-0.028386,-0.022129
3520,2025-03-27,2009.340000,2034.400000,1989.020000,2003.300000,0.023119,0.023178,0.023164,0.022967,ethereum,...,0.040963,-54.504916,-2.0,-2.0,-2.0,-2.0,-1.0,-1.0,-0.003274,-0.006313
3521,2025-03-28,2002.150000,2015.310000,1866.540000,1896.920000,0.022957,0.023032,0.022325,0.022486,ethereum,...,0.040887,-55.340206,-2.0,-2.0,-2.0,-2.0,-1.0,-1.0,-0.053102,-0.020910
3522,2025-03-29,1896.320000,1911.020000,1804.600000,1829.270000,0.022486,0.022605,0.022069,0.022125,ethereum,...,0.040810,-56.003656,-2.0,-2.0,-2.0,-2.0,-1.0,-1.0,-0.035663,-0.016068
3523,2025-03-30,1827.770000,1847.220000,1782.690000,1805.340000,0.022127,0.022123,0.021859,0.021921,ethereum,...,0.040732,-56.439635,-2.0,-2.0,-2.0,-2.0,-1.0,-1.0,-0.013082,-0.009211

In [5]:
info = analyzer.get_asset_information('ethereum')
short_term_matrix = info.get('transition_matrix_usd_short_term')
medium_term_matrix = info.get('transition_matrix_usd_medium_term')
long_term_matrix = info.get('transition_matrix_usd_long_term')
overall_matrix = info.get('transition_matrix_usd_overall')

In [ ]:
info = analyzer.get_asset_information('solana')
info.get('transition_matrix_usd')
trends_usd = info.get('consolidated_trend_metrics_usd')
positive_usd_trends = trends_usd[(trends_usd['Sortino'] > 0) & 
                         (trends_usd['Sharpe'] > 0) & 
                         (trends_usd['Return_Skew'] > 0) & 
                         (trends_usd['Avg_Return'] > 0) & 
                         (trends_usd['Median_Return'] > 0)]
positive_usd_trends
trends_btc = info.get('consolidated_trend_metrics_btc')
positive_btc_trends = trends_btc[(trends_btc['Sortino'] > 0) & 
                         (trends_btc['Sharpe'] > 0) & 
                         (trends_btc['Return_Skew'] > 0) & 
                         (trends_btc['Avg_Return'] > 0) &   
                         (trends_btc['Median_Return'] > 0)]
positive_btc_trends

# Get the processed data to analyze concurrent trends
solana_data = analyzer.get_asset_processed_data('solana')

# Extract positive trend conditions for USD
positive_usd_trend_conditions = []
for _, row in positive_usd_trends.iterrows():
    term = row['Term'].lower().replace(' ', '_')
    trend = row['Trend']
    positive_usd_trend_conditions.append((f"{term}_trend_USD", trend))

# Extract positive trend conditions for BTC
positive_btc_trend_conditions = []
for _, row in positive_btc_trends.iterrows():
    term = row['Term'].lower().replace(' ', '_')
    trend = row['Trend']
    positive_btc_trend_conditions.append((f"{term}_trend_BTC", trend))

# Create masks for each condition
usd_masks = []
for col, trend in positive_usd_trend_conditions:
    if col in solana_data.columns:
        usd_masks.append(solana_data[col] == trend)

btc_masks = []
for col, trend in positive_btc_trend_conditions:
    if col in solana_data.columns:
        btc_masks.append(solana_data[col] == trend)

# Calculate concurrent trends if we have valid conditions
if usd_masks and btc_masks:
    # Combine all USD positive trend conditions with OR
    usd_positive = pd.concat(usd_masks, axis=1).any(axis=1)
    
    # Combine all BTC positive trend conditions with OR
    btc_positive = pd.concat(btc_masks, axis=1).any(axis=1)
    
    # Calculate concurrent positive trends
    concurrent_positive = usd_positive & btc_positive
    
    # Calculate percentages
    total_days = len(solana_data)
    usd_positive_pct = usd_positive.mean() * 100
    btc_positive_pct = btc_positive.mean() * 100
    concurrent_positive_pct = concurrent_positive.mean() * 100
    
    print(f"USD positive trends: {usd_positive_pct:.2f}% of the time")
    print(f"BTC positive trends: {btc_positive_pct:.2f}% of the time")
    print(f"Concurrent positive trends: {concurrent_positive_pct:.2f}% of the time")
    print(f"Percentage of USD positive trends that are also BTC positive: {(concurrent_positive_pct/usd_positive_pct*100) if usd_positive_pct > 0 else 0:.2f}%")
    print(f"Percentage of BTC positive trends that are also USD positive: {(concurrent_positive_pct/btc_positive_pct*100) if btc_positive_pct > 0 else 0:.2f}%")
else:
    print("Not enough data to calculate concurrent trends")

In [6]:
info.get('consolidated_trend_metrics_btc')

,Trend,Description,Term,Count,Frequency,Avg_Return,Median_Return,Return_Skew,Sharpe,Sortino,Max_Drawdown,Avg_Duration,Max_Duration
0,-2,Strong Bear,Short Term,868,0.246311,-0.022836,-0.015951,-2.609964,-0.678098,-0.716173,1.000000,2.638298,11
1,-1,Weak Bear,Short Term,633,0.179625,-0.006694,-0.005488,-0.361889,-0.216487,-0.271257,0.989262,1.528986,7
2,0,Neutral,Short Term,900,0.255392,0.002413,0.000054,2.572936,0.059077,0.090178,0.577993,1.675978,6
3,1,Weak Bull,Short Term,490,0.139047,0.008717,0.003614,1.460403,0.220566,0.344298,0.283910,1.462687,5
4,2,Strong Bull,Short Term,630,0.178774,0.036207,0.020502,2.606468,0.649608,2.447606,0.101671,2.647059,17
5,-2,Strong Bear,Medium Term,1086,0.308173,-0.007072,-0.006756,0.283268,-0.186505,-0.252822,0.999800,7.985294,71
6,-1,Weak Bear,Medium Term,467,0.132520,-0.003388,-0.001572,0.021558,-0.102809,-0.132757,0.856311,2.346734,15
7,0,Neutral,Medium Term,931,0.264188,0.000833,-0.001848,0.658839,0.022187,0.033372,0.584492,4.119469,28
8,1,Weak Bull,Medium Term,361,0.102440,0.005797,0.003034,0.455966,0.163852,0.256609,0.302941,2.242236,20
9,2,Strong Bull,Medium Term,658,0.186720,0.016693,0.005980,1.522516,0.279788,0.531503,0.326384,7.741176,40
10,-2,Strong Bear,Long Term,1177,0.333995,-0.003284,-0.003217,-0.055916,-0.103173,-0.141055,0.988277,21.796296,138
11,-1,Weak Bear,Long Term,171,0.048524,0.000037,-0.001567,1.910897,0.000878,0.001413,0.491189,2.342466,15
12,0,Neutral,Long Term,1080,0.306470,0.000806,-0.001169,0.256464,0.022914,0.031994,0.580606,10.588235,82
13,1,Weak Bull,Long Term,225,0.063848,0.002511,-0.000587,0.997081,0.074262,0.124647,0.305415,2.710843,28
14,2,Strong Bull,Long Term,787,0.223326,0.009039,0.000424,1.397715,0.150795,0.286202,0.449520,17.108696,129
15,-2,Strong Bear,Overall,543,0.154086,-0.016662,-0.012109,-1.550374,-0.585242,-0.656489,0.999909,3.668919,21
16,-1,Weak Bear,Overall,984,0.279228,-0.002922,-0.002877,0.280746,-0.086679,-0.117054,0.986946,3.133758,27
17,0,Neutral,Overall,874,0.248014,-0.000343,-0.001206,0.304497,-0.009800,-0.013673,0.873662,2.714286,29
18,1,Weak Bull,Overall,735,0.208570,0.007588,0.003814,0.554559,0.181260,0.267918,0.540014,2.987805,16
19,2,Strong Bull,Overall,304,0.086266,0.037290,0.020732,1.450711,0.539089,1.157539,0.182402,3.454545,14

In [4]:
analyzer.delete_portfolio('btc_example')

Portfolio 'btc_example' does not exist.

False

In [5]:
analyzer.delete_portfolio('alt_example')

True

In [6]:
analyzer.create_portfolio(
    'btc_trend_follower',
    #btc_trend_gating=1,
    usd_conditions={'Short Term': [1,2], 'Overall': [1,2]},
    #btc_conditions={'Short Term': ['Neutral', 'Weak Bull', 'Strong Bull']},
    rsi_conditions_usd=True,
    use_volatility_filter=True,
    volatility_weight=1,
    alt_cost=0.005,
    btc_cost=0.001,
    btc_only=True
)

analyzer.create_portfolio(
    'alt_example',
    #btc_trend_gating=1,
    usd_conditions={'Short Term': [1,2], 'Overall': [1,2]},
    btc_conditions={'Short Term': [1,2]},
    rsi_conditions_usd=True,
    use_volatility_filter=True,
    volatility_weight=1,
    alt_cost=0.005,
    btc_cost=0.001,
    btc_only=False
)

Portfolio 'btc_trend_follower' already exists.

True

In [7]:
analyzer.list_portfolios()

,Name,Created,Updated,Summary,Assets
0,btc_trend_follower,2025-03-31T20:13:37.455858,2025-03-31T20:13:37.455866,"USD cond: {'Short Term': [1, 2], 'Overall': [1...",0
1,alt_example,2025-03-31T20:14:58.795461,2025-03-31T20:14:58.795486,"USD cond: {'Short Term': [1, 2], 'Overall': [1...",0

In [8]:
# ['asset_id', 'raw_data', 'processed_data', 'trend_metrics_usd', 'trend_metrics_btc', 'transition_matrix_usd', 'transition_matrix_btc'])
portfolio_info = analyzer.get_portfolio_details('btc_trend_follower')
print(portfolio_info)

{'criteria': {'usd_conditions': {'Short Term': [1, 2], 'Overall': [1, 2]}, 'signal_weights': {'usd_trend': 0.7, 'rsi': 0.2, 'volatility': 0.1}, 'rsi_conditions_usd': True, 'use_volatility_filter': True, 'trade_mode': 'all_in', 'btc_only': True}, 'created_at': '2025-03-31T20:13:37.455858', 'updated_at': '2025-03-31T20:13:37.455866', 'assets': []}

In [15]:
# Get asset-specific performance metrics
backtest_results = analyzer.backtest_portfolio('alt_example', '2022-01-01', '2024-12-31')
backtest_results

Backtesting:   0%|          | 1/1096 [00:00<00:01, 657.00it/s]

AttributeError: 'list' object has no attribute 'get'

In [14]:
backtest_results.get('trades').get('BTC')

,trade_id,entry_date,exit_date,holding_days,entry_price,exit_price,price_return,entry_value,entry_cost,exit_value,exit_cost,trade_return,is_open
0,1,2022-02-04,2022-02-08,4,41674.00,44184.0,6.02%,9990.000000,-10.000000,11811.870815,-11.823695,18.00%,False
1,2,2022-03-22,2022-03-31,9,42402.00,45528.0,7.37%,11800.058944,-11.811871,13511.052260,-13.524577,14.27%,False
2,3,2022-10-28,2022-10-31,3,20591.00,20495.0,-0.47%,13497.541208,-13.511052,13714.119567,-13.727847,1.40%,False
3,4,2022-11-04,2022-11-07,3,21150.00,20598.0,-2.61%,13700.405448,-13.714120,14158.029901,-14.172202,3.13%,False
4,5,2023-01-11,2023-01-18,7,17996.83,20727.0,15.17%,14143.871871,-14.158030,17144.254728,-17.161416,20.97%,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,71,2024-11-17,2024-11-24,7,90535.00,93005.0,2.73%,652393.764488,-653.046811,711045.983380,-711.757741,8.77%,False
71,72,2024-11-29,2024-12-01,2,96513.00,95833.0,-0.70%,710334.937396,-711.045983,708597.881178,-709.307188,-0.44%,False
72,73,2024-12-03,2024-12-08,5,98881.00,97354.0,-1.54%,707889.283297,-708.597881,745496.380613,-746.242623,5.10%,False
73,74,2024-12-10,2024-12-17,7,101124.00,100356.0,-0.76%,744750.884232,-745.496381,816251.322809,-817.068391,9.38%,False
74,75,2024-12-23,2024-12-24,1,98696.00,99345.0,0.66%,815435.071487,-816.251323,849487.026632,-850.337364,3.97%,False

In [15]:
backtest_results.keys()

dict_keys(['results_df', 'signals_df', 'trades_df', 'metrics_df', 'trade_metrics', 'holdings'])

In [ ]:
backtest_results.get('strategy_metrics'), backtest_results.get('buy_hold_metrics')

In [26]:
backtest_results.get('trades_metrics')

In [ ]:
#['results_df', 'signals_df', 'metrics_df', 'trades_df', 'trade_metrics', 'strategy_metrics', 'buy_hold_metrics']
backtest_results.get('trades_df')

In [ ]:
backtest_results.get('signals_df')['volatility_signal'].plot()

In [ ]:
# Get table of recommended assets
backtest_results = analyzer.backtest_portfolio('btc_trend_follower', '2022-01-01', '2022-12-31')
recommendations = analyzer.get_recommended_assets_table(backtest_results)
print(recommendations.head())

In [ ]:
# Plot trend distribution for Bitcoin
fig = analyzer.plot_trend_distribution('bitcoin', trend_type='USD', show_plot=True)

In [ ]:
# Plot the transition matrix for Ethereum
fig = analyzer.plot_trend_distribution('solana', trend_type='BTC')

In [15]:
analyzer.clear_cache()

In [ ]:
analyzer.get_ticker_from_id('cardano')