In [3]:
from pycoingecko import CoinGeckoAPI
from dotenv import load_dotenv
import os
from geckoAPI.utils import datetime_to_unix, parse_gecko_ohlcv, parse_gecko_prices

load_dotenv()

# Exemplo de lista de ativos (IDs no CoinGecko)
coin_ids = ["bitcoin", "ethereum", "cardano"]  
# Ajuste aqui para os ativos que você quer buscar.

# Inicializa a API
cg = CoinGeckoAPI(api_key=os.getenv('GECKO_API_KEY'))

In [23]:
data = cg.get_coin_ohlc_by_id_range(
            id='heyanon', 
            vs_currency='usd',
            from_timestamp=datetime_to_unix('2025-01-01'),
            to_timestamp=datetime_to_unix('2025-01-07'),
            interval='daily'
        )
parse_gecko_ohlcv(data)

        date   open   high    low  close
0 2025-01-01  1.062   1.26  1.048   1.10
1 2025-01-02  1.100   1.36  1.088   1.32
2 2025-01-03  1.230   2.37  1.220   2.37
3 2025-01-04  2.470   5.34  2.450   4.77
4 2025-01-05  4.810   6.69  4.570   6.67
5 2025-01-06  6.720   9.35  6.720   9.03
6 2025-01-07  9.120  11.04  7.470   9.47

In [2]:
data = cg.get_coin_market_chart_by_id(
            id='bitcoin', 
            vs_currency='usd',
            days=100000,
            interval='daily'
        )

parse_gecko_prices(data)

                     date          close    market_cap  total_volume
0     2013-04-28 00:00:00     135.300000  1.500518e+09  0.000000e+00
1     2013-04-29 00:00:00     141.960000  1.575032e+09  0.000000e+00
2     2013-04-30 00:00:00     135.300000  1.501657e+09  0.000000e+00
3     2013-05-01 00:00:00     117.000000  1.298952e+09  0.000000e+00
4     2013-05-02 00:00:00     103.430000  1.148668e+09  0.000000e+00
...                   ...            ...           ...           ...
4281  2025-01-18 00:00:00  104160.693585  2.063855e+12  6.913512e+10
4282  2025-01-19 00:00:00  104334.615757  2.067151e+12  4.941645e+10
4283  2025-01-20 00:00:00  101275.337148  2.014843e+12  7.297031e+10
4284  2025-01-21 00:00:00  101764.908602  2.017837e+12  1.201585e+11
4285  2025-01-21 03:33:39  102827.593688  2.036801e+12  1.203069e+11

[4286 rows x 4 columns]

In [3]:
data = cg.get_coin_ohlc_by_id(
            id='bitcoin', 
            vs_currency='usd',
            days=180,
            interval='daily'
        )
parse_gecko_ohlcv(data)

          date      open      high       low     close
0   2024-07-26   65365.0   66041.0   63515.0   65750.0
1   2024-07-27   65806.0   68223.0   65806.0   67920.0
2   2024-07-28   67935.0   69371.0   66608.0   68055.0
3   2024-07-29   67777.0   68294.0   67042.0   68242.0
4   2024-07-30   68261.0   69908.0   66648.0   66770.0
..         ...       ...       ...       ...       ...
175 2025-01-17  100555.0  100667.0   97532.0  100045.0
176 2025-01-18   99978.0  105850.0   99978.0  104161.0
177 2025-01-19  104125.0  104839.0  102214.0  104335.0
178 2025-01-20  104452.0  106307.0   99836.0  101275.0
179 2025-01-21  101184.0  108786.0   99702.0  101765.0

[180 rows x 5 columns]

In [22]:
parse_gecko_ohlcv(data)

          date      open      high       low     close
0   2024-07-26   65365.0   66041.0   63515.0   65750.0
1   2024-07-27   65806.0   68223.0   65806.0   67920.0
2   2024-07-28   67935.0   69371.0   66608.0   68055.0
3   2024-07-29   67777.0   68294.0   67042.0   68242.0
4   2024-07-30   68261.0   69908.0   66648.0   66770.0
..         ...       ...       ...       ...       ...
175 2025-01-17  100555.0  100667.0   97532.0  100045.0
176 2025-01-18   99978.0  105850.0   99978.0  104161.0
177 2025-01-19  104125.0  104839.0  102214.0  104335.0
178 2025-01-20  104452.0  106307.0   99836.0  101275.0
179 2025-01-21  101184.0  108786.0   99702.0  101765.0

[180 rows x 5 columns]